/* العرّاف: things (kind 't': food, objects, places, nature) and jobs (kind 'j'). One line each:
   id, icon, ar, en, and the question ids (OracleQuestions.js) that are true (yes), partly or
   "most would say probably" (maybe), and firmly not, where a player might think otherwise (no).
   A question about the entry's kind in none of the three reads as «غالباً لأ».
   notes/games/oracle.md, "Writing entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_THINGS = { kind: 't', list: [
  /* ---------- food and drink ---------- */
  { id: 'apple',      icon: '🍎', ar: 'تفاحة', en: 'Apple', yes: 'fruit sweet red round', maybe: 'green kitchen', no: 'plant' },
  { id: 'banana',     icon: '🍌', ar: 'موزة', en: 'Banana', yes: 'fruit sweet yellow', no: 'round' },
  { id: 'orange',     icon: '🍊', ar: 'برتقانة', en: 'Orange', yes: 'fruit sweet orange round', maybe: 'drink' },
  { id: 'watermelon', icon: '🍉', ar: 'بطيخة', en: 'Watermelon', yes: 'fruit sweet green red round summer', maybe: 'big' },
  { id: 'mango',      icon: '🥭', ar: 'مانجا', en: 'Mango', yes: 'fruit sweet yellow summer', maybe: 'orange green egypt drink' },
  { id: 'grapes',     icon: '🍇', ar: 'عنب', en: 'Grapes', yes: 'fruit sweet small', maybe: 'green round' },
  { id: 'strawberry', icon: '🍓', ar: 'فراولة', en: 'Strawberry', yes: 'fruit sweet red small' },
  { id: 'dates',      icon: '🌴', ar: 'بلح', en: 'Dates', yes: 'fruit sweet ramadan brown small', maybe: 'egypt' },
  { id: 'tomato',     icon: '🍅', ar: 'طماطم', en: 'Tomato', yes: 'veg red round kitchen' },
  { id: 'potato',     icon: '🥔', ar: 'بطاطس', en: 'Potato', yes: 'veg brown kitchen', maybe: 'round' },
  { id: 'onion',      icon: '🧅', ar: 'بصلة', en: 'Onion', yes: 'veg kitchen round', maybe: 'white' },
  { id: 'carrot',     icon: '🥕', ar: 'جزرة', en: 'Carrot', yes: 'veg orange', maybe: 'kitchen' },
  { id: 'molokhia',   icon: '🥬', ar: 'ملوخية', en: 'Molokhia', yes: 'dish green egypt hot', maybe: 'veg liquid' },
  { id: 'koshary',    icon: '🍝', ar: 'كشري', en: 'Koshary', yes: 'dish egypt hot', maybe: 'street' },
  { id: 'ful',        icon: '🫘', ar: 'فول', en: 'Ful medames', yes: 'dish egypt brown hot breakfast', maybe: 'ramadan street' },
  { id: 'taameya',    icon: '🧆', ar: 'طعمية', en: 'Taameya', yes: 'dish egypt hot breakfast round', maybe: 'green brown street' },
  { id: 'bread',      icon: '🍞', ar: 'عيش', en: 'Bread', yes: 'edible home kitchen breakfast', maybe: 'round brown hot' },
  { id: 'cheese',     icon: '🧀', ar: 'جبنة', en: 'Cheese', yes: 'edible white kitchen breakfast', maybe: 'yellow cold' },
  { id: 'egg',        icon: '🥚', ar: 'بيضة', en: 'Egg', yes: 'edible breaks kitchen small breakfast', maybe: 'white round' },
  { id: 'pizza',      icon: '🍕', ar: 'بيتزا', en: 'Pizza', yes: 'dish round hot' },
  { id: 'konafa',     icon: '🍯', ar: 'كنافة', en: 'Konafa', yes: 'dish sweet ramadan', maybe: 'orange hot' },
  { id: 'kahk',       icon: '🍪', ar: 'كحك العيد', en: 'Eid cookies (kahk)', yes: 'dish sweet ramadan round small', maybe: 'white egypt' },
  { id: 'chocolate',  icon: '🍫', ar: 'شوكولاتة', en: 'Chocolate', yes: 'edible sweet brown', maybe: 'small' },
  { id: 'icecream',   icon: '🍦', ar: 'آيس كريم', en: 'Ice cream', yes: 'edible sweet cold summer', maybe: 'white' },
  { id: 'water',      icon: '💧', ar: 'مية', en: 'Water', yes: 'drink liquid nature home wet', maybe: 'cold' },
  { id: 'milk',       icon: '🥛', ar: 'لبن', en: 'Milk', yes: 'drink liquid white', maybe: 'cold home breakfast' },
  { id: 'tea',        icon: '🫖', ar: 'شاي', en: 'Tea', yes: 'drink liquid hot home', maybe: 'kitchen brown breakfast' },
  { id: 'sugarcane',  icon: '🥤', ar: 'عصير قصب', en: 'Sugarcane juice', yes: 'drink liquid sweet egypt summer', maybe: 'cold green street' },
  /* ---------- around the house ---------- */
  { id: 'phone',      icon: '📱', ar: 'موبايل', en: 'Mobile phone', yes: 'electric screen talk home pocket', maybe: 'small black buttons', no: 'big' },
  { id: 'tv',         icon: '📺', ar: 'تلفزيون', en: 'Television', yes: 'electric screen talk home', maybe: 'black big', no: 'small pocket' },
  { id: 'computer',   icon: '💻', ar: 'كمبيوتر', en: 'Computer', yes: 'electric screen buttons', maybe: 'home school talk', no: 'pocket' },
  { id: 'fridge',     icon: '🧊', ar: 'تلاجة', en: 'Fridge', yes: 'electric kitchen cold big home container', maybe: 'white' },
  { id: 'fan',        icon: '🌀', ar: 'مروحة', en: 'Fan', yes: 'electric cold home noise summer', maybe: 'round buttons engine' },
  { id: 'lamp',       icon: '💡', ar: 'لمبة', en: 'Light bulb', yes: 'electric light glass breaks home', maybe: 'round small' },
  { id: 'clock',      icon: '⏰', ar: 'ساعة حيطة', en: 'Wall clock', yes: 'time round home', maybe: 'electric noise' },
  { id: 'watch',      icon: '⌚', ar: 'ساعة إيد', en: 'Wristwatch', yes: 'time wear small', maybe: 'metal round electric' },
  { id: 'lantern',    icon: '🏮', ar: 'فانوس رمضان', en: 'Ramadan lantern', yes: 'ramadan light', maybe: 'toy egypt metal glass electric noise' },
  { id: 'chair',      icon: '🪑', ar: 'كرسي', en: 'Chair', yes: 'furniture home sit', maybe: 'wood school' },
  { id: 'bed',        icon: '🛏️', ar: 'سرير', en: 'Bed', yes: 'furniture home big sit', maybe: 'wood' },
  { id: 'table',      icon: '🪵', ar: 'ترابيزة', en: 'Table', yes: 'furniture home wood', maybe: 'kitchen' },
  { id: 'door',       icon: '🚪', ar: 'باب', en: 'Door', yes: 'home wood', maybe: 'big' },
  { id: 'key',        icon: '🔑', ar: 'مفتاح', en: 'Key', yes: 'metal small home pocket', maybe: 'handtool' },
  { id: 'mirror',     icon: '🪞', ar: 'مراية', en: 'Mirror', yes: 'glass breaks home', maybe: 'round bathroom' },
  { id: 'pillow',     icon: '🛌', ar: 'مخدّة', en: 'Pillow', yes: 'cloth home', maybe: 'white' },
  { id: 'soap',       icon: '🧼', ar: 'صابونة', en: 'Soap', yes: 'clean home wet bathroom', maybe: 'small white' },
  { id: 'toothbrush', icon: '🪥', ar: 'فرشة سنان', en: 'Toothbrush', yes: 'clean home handtool bathroom', maybe: 'small wet' },
  { id: 'broom',      icon: '🧹', ar: 'مقشّة', en: 'Broom', yes: 'clean home handtool', maybe: 'wood' },
  { id: 'cup',        icon: '🥛', ar: 'كوباية', en: 'Glass (to drink)', yes: 'kitchen glass breaks container', maybe: 'small' },
  { id: 'spoon',      icon: '🥄', ar: 'معلقة', en: 'Spoon', yes: 'kitchen metal handtool', maybe: 'small' },
  { id: 'knife',      icon: '🔪', ar: 'سكينة', en: 'Knife', yes: 'sharp kitchen metal handtool' },
  { id: 'scissors',   icon: '✂️', ar: 'مقص', en: 'Scissors', yes: 'sharp handtool metal', maybe: 'school' },
  { id: 'umbrella',   icon: '☂️', ar: 'شمسية', en: 'Umbrella', yes: 'cloth wet', maybe: 'black street' },
  { id: 'money',      icon: '💵', ar: 'فلوس', en: 'Money', yes: 'paper home pocket', maybe: 'green small' },
  { id: 'camera',     icon: '📷', ar: 'كاميرا', en: 'Camera', yes: 'electric black buttons', maybe: 'screen small' },
  /* ---------- school, play and music ---------- */
  { id: 'pencil',     icon: '✏️', ar: 'قلم رصاص', en: 'Pencil', yes: 'write school wood handtool', maybe: 'yellow small pocket' },
  { id: 'book',       icon: '📖', ar: 'كتاب', en: 'Book', yes: 'paper school', maybe: 'home' },
  { id: 'notebook',   icon: '📒', ar: 'كشكول', en: 'Notebook', yes: 'paper school write' },
  { id: 'ball',       icon: '⚽', ar: 'كورة', en: 'Ball', yes: 'sport round toy', maybe: 'white black street' },
  { id: 'teddy',      icon: '🧸', ar: 'دبدوب', en: 'Teddy bear', yes: 'toy cloth', maybe: 'brown home' },
  { id: 'kite',       icon: '🪁', ar: 'طيارة ورق', en: 'Kite', yes: 'toy flies sky', maybe: 'paper' },
  { id: 'balloon',    icon: '🎈', ar: 'بالونة', en: 'Balloon', yes: 'toy round breaks', maybe: 'red flies' },
  { id: 'guitar',     icon: '🎸', ar: 'جيتار', en: 'Guitar', yes: 'music wood noise', no: 'arab' },
  { id: 'oud',        icon: '🪕', ar: 'عود', en: 'Oud', yes: 'music wood noise arab', maybe: 'egypt brown' },
  { id: 'drum',       icon: '🥁', ar: 'طبلة', en: 'Drum (tabla)', yes: 'music noise', maybe: 'round egypt' },
  /* ---------- on the road ---------- */
  { id: 'car',        icon: '🚗', ar: 'عربية', en: 'Car', yes: 'vehicle wheels metal street engine', maybe: 'big', no: 'passengers' },
  { id: 'bicycle',    icon: '🚲', ar: 'عجلة', en: 'Bicycle', yes: 'vehicle wheels metal street', maybe: 'sport toy', no: 'big engine' },
  { id: 'bus',        icon: '🚌', ar: 'أتوبيس', en: 'Bus', yes: 'vehicle wheels big street metal engine passengers', maybe: 'school' },
  { id: 'train',      icon: '🚆', ar: 'قطر', en: 'Train', yes: 'vehicle wheels big metal noise engine passengers', maybe: 'electric' },
  { id: 'plane',      icon: '✈️', ar: 'طيارة', en: 'Aeroplane', yes: 'vehicle flies sky big metal noise engine passengers', maybe: 'white' },
  { id: 'boat',       icon: '⛵', ar: 'مركب', en: 'Boat', yes: 'vehicle wet big', maybe: 'wood white engine passengers' },
  /* ---------- clothes ---------- */
  { id: 'shoe',       icon: '👞', ar: 'جزمة', en: 'Shoe', yes: 'wear home', maybe: 'black brown' },
  { id: 'shirt',      icon: '👕', ar: 'قميص', en: 'Shirt', yes: 'wear cloth buttons' },
  { id: 'glasses',    icon: '👓', ar: 'نضارة', en: 'Glasses', yes: 'wear glass breaks', maybe: 'small' },
  { id: 'cap',        icon: '🧢', ar: 'كاب', en: 'Cap', yes: 'wear cloth', maybe: 'sport' },
  /* ---------- nature and places ---------- */
  { id: 'sun',        icon: '☀️', ar: 'الشمس', en: 'The Sun', yes: 'nature sky hot light yellow round big' },
  { id: 'moon',       icon: '🌙', ar: 'القمر', en: 'The Moon', yes: 'nature sky light round', maybe: 'white ramadan big' },
  { id: 'star',       icon: '⭐', ar: 'نجمة في السما', en: 'A star', yes: 'nature sky light', maybe: 'yellow white' },
  { id: 'cloud',      icon: '☁️', ar: 'سحابة', en: 'Cloud', yes: 'nature sky white wet', maybe: 'gray big' },
  { id: 'tree',       icon: '🌳', ar: 'شجرة', en: 'Tree', yes: 'plant nature green big', maybe: 'wood street' },
  { id: 'rose',       icon: '🌹', ar: 'وردة', en: 'Rose', yes: 'plant nature red', maybe: 'pink small' },
  { id: 'cactus',     icon: '🌵', ar: 'صبّارة', en: 'Cactus', yes: 'plant nature green', maybe: 'sharp' },
  { id: 'sea',        icon: '🌊', ar: 'البحر', en: 'The sea', yes: 'nature wet blue big place', maybe: 'liquid summer' },
  { id: 'nile',       icon: '🏞️', ar: 'النيل', en: 'The Nile', yes: 'nature egypt wet big place', maybe: 'blue liquid' },
  { id: 'pyramids',   icon: '🔺', ar: 'الأهرامات', en: 'The Pyramids', yes: 'place egypt big', maybe: 'yellow brown', no: 'nature' },
  { id: 'school_p',   icon: '🏫', ar: 'مدرسة', en: 'School', yes: 'place big school', maybe: 'street' },
  { id: 'fire',       icon: '🔥', ar: 'نار', en: 'Fire', yes: 'hot light', maybe: 'nature red orange' },
  { id: 'ice',        icon: '🧊', ar: 'تلج', en: 'Ice', yes: 'cold wet white', maybe: 'nature breaks' },
]};

const ORACLE_JOBS = { kind: 'j', list: [
  { id: 'doctor',     icon: '🩺', ar: 'دكتور', en: 'Doctor', yes: 'hospital study rescue night_j', maybe: 'uniform' },
  { id: 'nurse',      icon: '💉', ar: 'ممرضة', en: 'Nurse', yes: 'hospital uniform', maybe: 'night_j rescue' },
  { id: 'dentist',    icon: '🦷', ar: 'دكتور أسنان', en: 'Dentist', yes: 'hospital study', maybe: 'uniform', no: 'night_j rescue' },
  { id: 'vet',        icon: '🐾', ar: 'دكتور بيطري', en: 'Vet', yes: 'animals_j study', maybe: 'hospital' },
  { id: 'teacher',    icon: '🧑‍🏫', ar: 'مدرّس', en: 'Teacher', yes: 'teach kids_j', maybe: 'study' },
  { id: 'engineer',   icon: '👷', ar: 'مهندس', en: 'Engineer', yes: 'study build', maybe: 'desk power_j outdoors' },
  { id: 'pilot',      icon: '👨‍✈️', ar: 'طيّار', en: 'Pilot', yes: 'drives flies uniform night_j', maybe: 'study' },
  { id: 'astronaut',  icon: '👩‍🚀', ar: 'رائد فضاء', en: 'Astronaut', yes: 'flies uniform study', maybe: 'drives' },
  { id: 'police',     icon: '👮', ar: 'ظابط شرطة', en: 'Police officer', yes: 'uniform rescue outdoors night_j', maybe: 'drives law' },
  { id: 'firefighter', icon: '🧑‍🚒', ar: 'رجل مطافي', en: 'Firefighter', yes: 'uniform rescue outdoors night_j wet fire_j', maybe: 'drives' },
  { id: 'chef',       icon: '🧑‍🍳', ar: 'شيف (طبّاخ)', en: 'Chef', yes: 'food_j fire_j', maybe: 'hands uniform night_j', no: 'sells' },
  { id: 'baker',      icon: '🥖', ar: 'فرّان', en: 'Baker', yes: 'food_j hands fire_j sells', maybe: 'night_j' },
  { id: 'butcher',    icon: '🥩', ar: 'جزّار', en: 'Butcher', yes: 'food_j sells', maybe: 'animals_j hands' },
  { id: 'farmer',     icon: '🧑‍🌾', ar: 'فلّاح', en: 'Farmer', yes: 'outdoors animals_j', maybe: 'food_j hands wet' },
  { id: 'fisherman',  icon: '🎣', ar: 'صيّاد سمك', en: 'Fisherman', yes: 'sea_j outdoors wet', maybe: 'food_j animals_j sells' },
  { id: 'captain',    icon: '⚓', ar: 'قبطان مركب', en: 'Ship captain', yes: 'sea_j drives uniform wet', maybe: 'outdoors' },
  { id: 'carpenter',  icon: '🪚', ar: 'نجّار', en: 'Carpenter', yes: 'hands build' },
  { id: 'plumber',    icon: '🔧', ar: 'سبّاك', en: 'Plumber', yes: 'hands build wet' },
  { id: 'electrician', icon: '⚡', ar: 'كهربائي', en: 'Electrician', yes: 'hands build power_j' },
  { id: 'mechanic',   icon: '🔩', ar: 'ميكانيكي', en: 'Mechanic', yes: 'hands build cars_j' },
  { id: 'driver',     icon: '🚕', ar: 'سوّاق', en: 'Driver', yes: 'drives cars_j outdoors', maybe: 'night_j' },
  { id: 'lawyer',     icon: '⚖️', ar: 'محامي', en: 'Lawyer', yes: 'law desk study' },
  { id: 'accountant', icon: '🧾', ar: 'محاسب', en: 'Accountant', yes: 'money_j desk', maybe: 'study power_j' },
  { id: 'programmer', icon: '👩‍💻', ar: 'مبرمج', en: 'Programmer', yes: 'power_j desk', maybe: 'study night_j' },
  { id: 'barber',     icon: '💈', ar: 'حلّاق', en: 'Barber', yes: 'looks_j hands', maybe: 'sells' },
  { id: 'photographer', icon: '📸', ar: 'مصوّر', en: 'Photographer', yes: 'art_j outdoors', maybe: 'power_j' },
  { id: 'artist',     icon: '🎨', ar: 'رسّام', en: 'Painter (artist)', yes: 'art_j hands' },
  { id: 'postman',    icon: '📮', ar: 'بوسطجي', en: 'Postman', yes: 'outdoors uniform', maybe: 'drives' },
  { id: 'waiter',     icon: '🍽️', ar: 'جرسون', en: 'Waiter', yes: 'food_j uniform', maybe: 'night_j' },
  { id: 'gardener',   icon: '🌷', ar: 'جنايني', en: 'Gardener', yes: 'outdoors hands', maybe: 'wet' },
]};
