/* العرّاف: famous people (kind 'p'). Egyptian and Arab first, then the world-famous; only
   facts that don't change (where they are from, what they did, what they won, when they were
   born) - never whether they are alive or still playing. No politicians of our time, nothing
   divisive. One line each: id, icon (what they are known for, shown on a drawn silhouette -
   never a photo), ar, en, and the question ids (OracleQuestions.js) that are true (yes),
   partly (maybe) and firmly not (no). A question about people in none of the three reads as
   «غالباً لأ». notes/games/oracle.md, "Writing entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_PEOPLE = { kind: 'p', list: [
  /* ---------- football ---------- */
  { id: 'salah',       icon: '⚽', ar: 'محمد صلاح', en: 'Mohamed Salah', yes: 'egypt arab athlete football england striker italy', no: 'ahly zamalek worldcup afcon' },
  { id: 'aboutrika',   icon: '⚽', ar: 'محمد أبو تريكة', en: 'Mohamed Aboutrika', yes: 'egypt arab athlete football ahly afcon midfield born1980', maybe: 'striker', no: 'zamalek england' },
  { id: 'hossamhassan', icon: '⚽', ar: 'حسام حسن', en: 'Hossam Hassan', yes: 'egypt arab athlete football ahly zamalek striker afcon coach born1970' },
  { id: 'hadary',      icon: '🧤', ar: 'عصام الحضري', en: 'Essam El-Hadary', yes: 'egypt arab athlete football ahly keeper afcon born1975', maybe: 'zamalek coach' },
  { id: 'khatib',      icon: '⚽', ar: 'محمود الخطيب', en: 'Mahmoud El Khatib', yes: 'egypt arab athlete football ahly striker afcon born1970', maybe: 'midfield', no: 'zamalek' },
  { id: 'shikabala',   icon: '⚽', ar: 'شيكابالا', en: 'Shikabala', yes: 'egypt arab athlete football zamalek midfield', maybe: 'south striker', no: 'ahly' },
  { id: 'ahmedhassan', icon: '⚽', ar: 'أحمد حسن', en: 'Ahmed Hassan', yes: 'egypt arab south athlete football ahly zamalek afcon midfield born1980', maybe: 'defender', no: 'striker' },
  { id: 'elneny',      icon: '⚽', ar: 'محمد النني', en: 'Mohamed Elneny', yes: 'egypt arab athlete football england midfield', no: 'ahly zamalek striker' },
  { id: 'messi',       icon: '⚽', ar: 'ليونيل ميسي', en: 'Lionel Messi', yes: 'latam athlete football spain striker worldcup ballon olympic', maybe: 'midfield' },
  { id: 'ronaldo',     icon: '⚽', ar: 'كريستيانو رونالدو', en: 'Cristiano Ronaldo', yes: 'europe athlete football england spain striker ballon italy', no: 'worldcup' },
  { id: 'zidane',      icon: '⚽', ar: 'زين الدين زيدان', en: 'Zinedine Zidane', yes: 'europe athlete football spain worldcup ballon coach france italy midfield born1975', maybe: 'arab maghreb' },
  { id: 'maradona',    icon: '⚽', ar: 'دييجو مارادونا', en: 'Diego Maradona', yes: 'latam athlete football spain worldcup coach born1970 italy midfield', maybe: 'striker' },
  { id: 'pele',        icon: '⚽', ar: 'بيليه', en: 'Pelé', yes: 'latam born1950 athlete football striker worldcup born1970' },
  { id: 'mahrez',      icon: '⚽', ar: 'رياض محرز', en: 'Riyad Mahrez', yes: 'arab maghreb athlete football england afcon', maybe: 'striker france midfield' },
  { id: 'hakimi',      icon: '⚽', ar: 'أشرف حكيمي', en: 'Achraf Hakimi', yes: 'arab maghreb athlete football spain olympic italy defender', no: 'striker' },
  { id: 'mane',        icon: '⚽', ar: 'ساديو ماني', en: 'Sadio Mané', yes: 'africa athlete football england striker afcon' },
  /* ---------- other sports ---------- */
  { id: 'muhammadali', icon: '🥊', ar: 'محمد علي كلاي', en: 'Muhammad Ali', yes: 'usa born1950 athlete othersport fighter olympic born1970' },
  { id: 'bolt',        icon: '🏃', ar: 'يوسين بولت', en: 'Usain Bolt', yes: 'athlete othersport olympic runner' },
  { id: 'jordan',      icon: '🏀', ar: 'مايكل جوردان', en: 'Michael Jordan', yes: 'usa athlete othersport olympic born1970 basket', maybe: 'hollywood' },
  { id: 'karamgaber',  icon: '🤼', ar: 'كرم جابر', en: 'Karam Gaber', yes: 'egypt arab athlete othersport fighter olympic born1980' },
  /* ---------- actors ---------- */
  { id: 'adelimam',    icon: '🎭', ar: 'عادل إمام', en: 'Adel Imam', yes: 'egypt arab born1950 actor comedy theater born1970', maybe: 'bw series', no: 'born1930' },
  { id: 'ahmedzaki',   icon: '🎬', ar: 'أحمد زكي', en: 'Ahmed Zaki', yes: 'egypt arab born1950 actor born1970', no: 'comedy' },
  { id: 'omarsharif',  icon: '🎬', ar: 'عمر الشريف', en: 'Omar Sharif', yes: 'egypt arab born1950 actor bw hollywood born1970' },
  { id: 'ismailyassin', icon: '😂', ar: 'إسماعيل ياسين', en: 'Ismail Yassin', yes: 'egypt arab born1930 born1950 actor comedy bw born1970', maybe: 'theater singer' },
  { id: 'fouad',       icon: '🎭', ar: 'فؤاد المهندس', en: 'Fouad El-Mohandes', yes: 'egypt arab born1930 born1950 actor comedy bw theater series fawazeer born1970', maybe: 'singer' },
  { id: 'fareedshawqi', icon: '🎬', ar: 'فريد شوقي', en: 'Farid Shawqi', yes: 'egypt arab born1930 born1950 actor bw action born1970', maybe: 'villainroles' },
  { id: 'henedy',      icon: '😄', ar: 'محمد هنيدي', en: 'Mohamed Henedy', yes: 'egypt arab actor comedy born1970', maybe: 'theater' },
  { id: 'helmy',       icon: '😄', ar: 'أحمد حلمي', en: 'Ahmed Helmy', yes: 'egypt arab actor comedy tvhost born1970', no: 'theater' },
  { id: 'fakharany',   icon: '🎭', ar: 'يحيى الفخراني', en: 'Yehia El-Fakharany', yes: 'egypt arab born1950 actor theater series born1970' },
  { id: 'sakka',       icon: '🎬', ar: 'أحمد السقا', en: 'Ahmed El Sakka', yes: 'egypt arab actor action born1975', maybe: 'series', no: 'comedy' },
  { id: 'faten',       icon: '🎬', ar: 'فاتن حمامة', en: 'Faten Hamama', yes: 'female egypt arab born1950 actor bw born1970' },
  { id: 'soad',        icon: '🎬', ar: 'سعاد حسني', en: 'Soad Hosny', yes: 'female egypt arab born1950 actor bw singer born1970 dance' },
  { id: 'sherihan',    icon: '💃', ar: 'شريهان', en: 'Sherihan', yes: 'female egypt arab actor fawazeer born1970 dance', maybe: 'comedy theater series singer' },
  { id: 'yousra',      icon: '🎬', ar: 'يسرا', en: 'Yousra', yes: 'female egypt arab actor series born1970', maybe: 'singer' },
  { id: 'chaplin',     icon: '🎩', ar: 'شارلي شابلن', en: 'Charlie Chaplin', yes: 'europe born1930 born1950 actor comedy bw hollywood born1970 director oscar uk' },
  { id: 'brucelee',    icon: '🥋', ar: 'بروس لي', en: 'Bruce Lee', yes: 'asia born1950 actor action hollywood fighter born1970', maybe: 'usa' },
  { id: 'jackiechan',  icon: '🥋', ar: 'جاكي شان', en: 'Jackie Chan', yes: 'asia actor action hollywood fighter born1970', maybe: 'comedy director oscar' },
  /* ---------- singers and musicians ---------- */
  { id: 'umkulthum',   icon: '🎤', ar: 'أم كلثوم', en: 'Umm Kulthum', yes: 'female egypt arab born1930 born1950 bw singer born1970', maybe: 'actor' },
  { id: 'abdelhalim',  icon: '🎤', ar: 'عبد الحليم حافظ', en: 'Abdel Halim Hafez', yes: 'egypt arab born1930 born1950 actor bw singer born1970' },
  { id: 'abdelwahab',  icon: '🎼', ar: 'محمد عبد الوهاب', en: 'Mohamed Abdel Wahab', yes: 'egypt arab born1930 born1950 bw singer composer born1970', maybe: 'actor' },
  { id: 'fareedatrash', icon: '🎼', ar: 'فريد الأطرش', en: 'Farid al-Atrash', yes: 'arab levant born1930 born1950 actor bw singer composer born1970', maybe: 'egypt' },
  { id: 'sayeddarwish', icon: '🎼', ar: 'سيد درويش', en: 'Sayed Darwish', yes: 'egypt arab born1930 born1950 singer composer born1970', maybe: 'theater', no: 'bw actor' },
  { id: 'fairuz',      icon: '🎤', ar: 'فيروز', en: 'Fairuz', yes: 'female arab levant born1950 singer born1970' },
  { id: 'warda',       icon: '🎤', ar: 'وردة الجزائرية', en: 'Warda', yes: 'female arab maghreb born1950 singer born1970', maybe: 'egypt levant actor' },
  { id: 'amrdiab',     icon: '🎤', ar: 'عمرو دياب', en: 'Amr Diab', yes: 'egypt arab singer born1970', maybe: 'actor composer' },
  { id: 'mounir',      icon: '🎤', ar: 'محمد منير', en: 'Mohamed Mounir', yes: 'egypt arab south singer born1970', maybe: 'actor' },
  { id: 'tamer',       icon: '🎤', ar: 'تامر حسني', en: 'Tamer Hosny', yes: 'egypt arab actor singer born1980', maybe: 'comedy composer' },
  { id: 'sherine',     icon: '🎤', ar: 'شيرين عبد الوهاب', en: 'Sherine', yes: 'female egypt arab singer' },
  { id: 'nancy',       icon: '🎤', ar: 'نانسي عجرم', en: 'Nancy Ajram', yes: 'female arab levant singer' },
  { id: 'kazem',       icon: '🎤', ar: 'كاظم الساهر', en: 'Kadim Al Sahir', yes: 'arab gulf singer composer born1970' },
  { id: 'mj',          icon: '🕺', ar: 'مايكل جاكسون', en: 'Michael Jackson', yes: 'usa singer born1970 dance', maybe: 'hollywood composer' },
  { id: 'mozart',      icon: '🎹', ar: 'موتسارت', en: 'Mozart', yes: 'europe before1800 born1930 born1950 composer born1970' },
  /* ---------- history ---------- */
  { id: 'ramses',      icon: '👑', ar: 'رمسيس التاني', en: 'Ramesses II', yes: 'egypt before1800 bc pharaoh born1930 born1950 ruler warrior born1970 built', maybe: 'arab' },
  { id: 'tut',         icon: '👑', ar: 'توت عنخ آمون', en: 'Tutankhamun', yes: 'egypt before1800 bc pharaoh born1930 born1950 ruler born1970', maybe: 'arab', no: 'warrior' },
  { id: 'nefertiti',   icon: '👑', ar: 'نفرتيتي', en: 'Nefertiti', yes: 'female egypt before1800 bc pharaoh born1930 born1950 ruler born1970', maybe: 'arab' },
  { id: 'cleopatra',   icon: '👑', ar: 'كليوباترا', en: 'Cleopatra', yes: 'female before1800 bc born1930 born1950 ruler born1970', maybe: 'egypt arab europe pharaoh', no: 'bc1000' },
  { id: 'alexander',   icon: '⚔️', ar: 'الإسكندر الأكبر', en: 'Alexander the Great', yes: 'europe before1800 bc born1930 born1950 ruler warrior born1970', maybe: 'built' },
  { id: 'saladin',     icon: '⚔️', ar: 'صلاح الدين الأيوبي', en: 'Saladin', yes: 'before1800 born1930 born1950 ruler warrior born1970 built before1500', maybe: 'egypt arab gulf' },
  { id: 'napoleon',    icon: '⚔️', ar: 'نابليون بونابرت', en: 'Napoleon', yes: 'europe before1800 born1930 born1950 ruler warrior born1970 france' },
  { id: 'mutanabbi',   icon: '📜', ar: 'المتنبي', en: 'Al-Mutanabbi', yes: 'arab gulf before1800 born1930 born1950 writer poet born1970 before1500' },
  { id: 'ibnsina',     icon: '⚕️', ar: 'ابن سينا', en: 'Avicenna', yes: 'before1800 born1930 born1950 science medic born1970 before1500', maybe: 'arab writer' },
  { id: 'khwarizmi',   icon: '🧮', ar: 'الخوارزمي', en: 'Al-Khwarizmi', yes: 'before1800 born1930 born1950 science born1970 before1500 math', maybe: 'arab gulf' },
  { id: 'ibnbattuta',  icon: '🧭', ar: 'ابن بطوطة', en: 'Ibn Battuta', yes: 'arab maghreb before1800 born1930 born1950 explorer born1970 before1500', maybe: 'writer' },
  { id: 'davinci',     icon: '🎨', ar: 'ليوناردو دافنشي', en: 'Leonardo da Vinci', yes: 'europe before1800 born1930 born1950 science painter born1970 before1500' },
  { id: 'shakespeare', icon: '✍️', ar: 'شكسبير', en: 'Shakespeare', yes: 'europe before1800 born1930 born1950 theater writer poet born1970 uk' },
  { id: 'newton',      icon: '🍎', ar: 'إسحاق نيوتن', en: 'Isaac Newton', yes: 'europe before1800 born1930 born1950 science born1970 uk math' },
  /* ---------- science, letters, the arts ---------- */
  { id: 'zewail',      icon: '🔬', ar: 'أحمد زويل', en: 'Ahmed Zewail', yes: 'egypt arab born1950 science nobel born1970', maybe: 'usa' },
  { id: 'mahfouz',     icon: '✍️', ar: 'نجيب محفوظ', en: 'Naguib Mahfouz', yes: 'egypt arab born1930 born1950 writer nobel born1970' },
  { id: 'tahahussein', icon: '✍️', ar: 'طه حسين', en: 'Taha Hussein', yes: 'egypt arab south born1930 born1950 writer blind born1970' },
  { id: 'shawqi',      icon: '📜', ar: 'أحمد شوقي', en: 'Ahmed Shawqi', yes: 'egypt arab born1930 born1950 writer poet born1970', maybe: 'theater' },
  { id: 'magdiyacoub', icon: '🫀', ar: 'مجدي يعقوب', en: 'Magdi Yacoub', yes: 'egypt arab born1950 medic born1970', maybe: 'science' },
  { id: 'einstein',    icon: '🧠', ar: 'أينشتاين', en: 'Albert Einstein', yes: 'europe born1930 born1950 science nobel born1970', maybe: 'usa math' },
  { id: 'curie',       icon: '⚛️', ar: 'ماري كوري', en: 'Marie Curie', yes: 'female europe born1930 born1950 science nobel born1970', maybe: 'france' },
  { id: 'edison',      icon: '💡', ar: 'توماس إديسون', en: 'Thomas Edison', yes: 'usa born1930 born1950 science born1970' },
  { id: 'armstrong',   icon: '🚀', ar: 'نيل أرمسترونج', en: 'Neil Armstrong', yes: 'usa born1950 explorer born1970' },
  { id: 'picasso',     icon: '🎨', ar: 'بيكاسو', en: 'Pablo Picasso', yes: 'europe born1930 born1950 painter born1970' },
  /* ==================== the second batch (9 Oct 2026) ==================== */
  /* ---------- Egyptian actresses ---------- */
  { id: 'marymounib',  icon: '😂', ar: 'ماري منيب', en: 'Mary Mounib', yes: 'female egypt arab born1930 born1950 actor comedy bw theater born1970 levant' },
  { id: 'zeinatsedky', icon: '😂', ar: 'زينات صدقي', en: 'Zeinat Sedki', yes: 'female egypt arab born1930 born1950 actor comedy bw born1970', maybe: 'theater' },
  { id: 'aminarizk',   icon: '🎭', ar: 'أمينة رزق', en: 'Amina Rizk', yes: 'female egypt arab born1930 born1950 actor bw theater born1970', maybe: 'series' },
  { id: 'hindrostom',  icon: '🎬', ar: 'هند رستم', en: 'Hind Rostom', yes: 'female egypt arab born1930 born1950 actor bw born1970' },
  { id: 'sanaagamil',  icon: '🎭', ar: 'سناء جميل', en: 'Sanaa Gamil', yes: 'female egypt arab born1950 actor bw theater born1970', maybe: 'series' },
  { id: 'nadiagendy',  icon: '🎬', ar: 'نادية الجندي', en: 'Nadia El Gendy', yes: 'female egypt arab born1950 actor action born1970', maybe: 'bw' },
  { id: 'nelly',       icon: '💃', ar: 'نيللي', en: 'Nelly', yes: 'female egypt arab born1950 actor fawazeer born1970 dance', maybe: 'bw singer' },
  { id: 'soheirbabli', icon: '🎭', ar: 'سهير البابلي', en: 'Soheir El Babli', yes: 'female egypt arab born1950 actor comedy theater born1970', maybe: 'bw series' },
  { id: 'ablakamel',   icon: '😄', ar: 'عبلة كامل', en: 'Abla Kamel', yes: 'female egypt arab actor comedy born1970', maybe: 'series' },
  { id: 'karimamokhtar', icon: '📺', ar: 'كريمة مختار', en: 'Karima Mokhtar', yes: 'female egypt arab born1950 actor series born1970', maybe: 'bw' },
  { id: 'isaadyounis', icon: '📺', ar: 'إسعاد يونس', en: 'Isaad Younis', yes: 'female egypt arab actor comedy tvhost born1970', maybe: 'series writer' },
  { id: 'monazaki',    icon: '🎬', ar: 'منى زكي', en: 'Mona Zaki', yes: 'female egypt arab actor born1980', maybe: 'comedy series' },
  { id: 'yasminabdelaziz', icon: '😄', ar: 'ياسمين عبد العزيز', en: 'Yasmin Abdulaziz', yes: 'female egypt arab actor comedy', maybe: 'series' },
  { id: 'doniasamir',  icon: '😄', ar: 'دنيا سمير غانم', en: 'Donia Samir Ghanem', yes: 'female egypt arab actor comedy singer', maybe: 'series' },
  { id: 'nellykarim',  icon: '🎬', ar: 'نيللي كريم', en: 'Nelly Karim', yes: 'female egypt arab actor series born1975', maybe: 'dance' },
  { id: 'somaya',      icon: '🎤', ar: 'سمية الخشاب', en: 'Somaya El Khashab', yes: 'female egypt arab actor singer born1980', maybe: 'series' },
  { id: 'hendsabry',   icon: '🎬', ar: 'هند صبري', en: 'Hend Sabry', yes: 'female arab maghreb actor born1980', maybe: 'series' },
  /* ---------- Egyptian actors ---------- */
  { id: 'rushdyabaza', icon: '🎬', ar: 'رشدي أباظة', en: 'Rushdy Abaza', yes: 'egypt arab born1930 born1950 actor bw born1970' },
  { id: 'meligy',      icon: '😈', ar: 'محمود المليجي', en: 'Mahmoud El-Meligy', yes: 'egypt arab born1930 born1950 actor bw born1970 villainroles' },
  { id: 'stephanrosti', icon: '😈', ar: 'استيفان روستي', en: 'Stephan Rosti', yes: 'egypt arab born1930 born1950 actor comedy bw born1970 villainroles', maybe: 'director' },
  { id: 'youssefwahbi', icon: '🎭', ar: 'يوسف وهبي', en: 'Youssef Wahbi', yes: 'egypt arab born1930 born1950 actor bw theater born1970 director' },
  { id: 'madbouly',    icon: '🎭', ar: 'عبد المنعم مدبولي', en: 'Abdel Moneim Madbouly', yes: 'egypt arab born1930 born1950 actor comedy bw theater series born1970', maybe: 'director' },
  { id: 'samirghanem', icon: '😂', ar: 'سمير غانم', en: 'Samir Ghanem', yes: 'egypt arab born1950 actor comedy theater fawazeer born1970', maybe: 'bw series singer' },
  { id: 'mohamedsobhi', icon: '🎭', ar: 'محمد صبحي', en: 'Mohamed Sobhy', yes: 'egypt arab born1950 actor comedy theater series born1970 director' },
  { id: 'noursherif',  icon: '🎬', ar: 'نور الشريف', en: 'Nour El-Sherif', yes: 'egypt arab born1950 actor series born1970', maybe: 'bw' },
  { id: 'khalednabawy', icon: '🎬', ar: 'خالد النبوي', en: 'Khaled El Nabawy', yes: 'egypt arab actor hollywood born1970', maybe: 'series' },
  { id: 'karimabdelaziz', icon: '🎬', ar: 'كريم عبد العزيز', en: 'Karim Abdel Aziz', yes: 'egypt arab actor comedy action born1980', maybe: 'series' },
  { id: 'mekky',       icon: '😄', ar: 'أحمد مكي', en: 'Ahmed Mekky', yes: 'egypt arab actor comedy series singer born1980', maybe: 'director' },
  { id: 'mohamedramadan', icon: '🎬', ar: 'محمد رمضان', en: 'Mohamed Ramadan', yes: 'egypt arab actor action series singer', maybe: 'south villainroles' },
  { id: 'amirkarara',  icon: '🎬', ar: 'أمير كرارة', en: 'Amir Karara', yes: 'egypt arab actor action series born1980' },
  { id: 'chahine',     icon: '🎥', ar: 'يوسف شاهين', en: 'Youssef Chahine', yes: 'egypt arab born1930 born1950 born1970 director', maybe: 'actor bw' },
  /* ---------- Arab actors ---------- */
  { id: 'duraidlahham', icon: '😂', ar: 'دريد لحام', en: 'Duraid Lahham', yes: 'arab levant born1950 actor comedy theater series born1970', maybe: 'bw director' },
  { id: 'abdelhussein', icon: '😂', ar: 'عبد الحسين عبد الرضا', en: 'Abdulhussain Abdulredha', yes: 'arab gulf born1950 actor comedy theater series born1970' },
  { id: 'nasserqasabi', icon: '😂', ar: 'ناصر القصبي', en: 'Nasser Al Qasabi', yes: 'arab gulf actor comedy series born1970' },
  { id: 'hayatfahad',  icon: '🎭', ar: 'حياة الفهد', en: 'Hayat Al-Fahad', yes: 'female arab gulf born1950 actor series born1970', maybe: 'theater' },
  { id: 'ghassanmassoud', icon: '🎬', ar: 'غسان مسعود', en: 'Ghassan Massoud', yes: 'arab levant actor hollywood series born1970' },
  /* ---------- world film ---------- */
  { id: 'ramimalek',   icon: '🎬', ar: 'رامي مالك', en: 'Rami Malek', yes: 'usa actor hollywood series oscar', maybe: 'egypt arab' },
  { id: 'tomhanks',    icon: '🎬', ar: 'توم هانكس', en: 'Tom Hanks', yes: 'usa actor hollywood born1970 oscar' },
  { id: 'tomcruise',   icon: '🎬', ar: 'توم كروز', en: 'Tom Cruise', yes: 'usa actor action hollywood born1970', maybe: 'oscar' },
  { id: 'dicaprio',    icon: '🎬', ar: 'ليوناردو دي كابريو', en: 'Leonardo DiCaprio', yes: 'usa actor hollywood oscar born1975' },
  { id: 'stallone',    icon: '🥊', ar: 'سيلفستر ستالون', en: 'Sylvester Stallone', yes: 'usa born1950 actor action hollywood born1970', maybe: 'fighter director' },
  { id: 'jimcarrey',   icon: '😂', ar: 'جيم كاري', en: 'Jim Carrey', yes: 'actor comedy hollywood born1970', maybe: 'usa' },
  { id: 'robinwilliams', icon: '😂', ar: 'روبن ويليامز', en: 'Robin Williams', yes: 'usa actor comedy hollywood born1970 oscar' },
  { id: 'morganfreeman', icon: '🎬', ar: 'مورجان فريمان', en: 'Morgan Freeman', yes: 'usa born1950 actor hollywood born1970 oscar' },
  { id: 'clinteastwood', icon: '🤠', ar: 'كلينت إيستوود', en: 'Clint Eastwood', yes: 'usa born1950 actor action hollywood born1970 director oscar' },
  { id: 'merylstreep', icon: '🎬', ar: 'ميريل ستريب', en: 'Meryl Streep', yes: 'female usa born1950 actor hollywood born1970 oscar' },
  { id: 'juliaroberts', icon: '🎬', ar: 'جوليا روبرتس', en: 'Julia Roberts', yes: 'female usa actor hollywood born1970 oscar' },
  { id: 'angelinajolie', icon: '🎬', ar: 'أنجلينا جولي', en: 'Angelina Jolie', yes: 'female usa actor action hollywood oscar born1980', maybe: 'director' },
  { id: 'audreyhepburn', icon: '🎬', ar: 'أودري هيبورن', en: 'Audrey Hepburn', yes: 'female europe born1930 born1950 actor bw hollywood born1970 oscar', maybe: 'uk' },
  { id: 'therock',     icon: '💪', ar: 'ذا روك (دواين جونسون)', en: 'The Rock (Dwayne Johnson)', yes: 'usa actor action hollywood fighter born1975', maybe: 'comedy athlete othersport' },
  { id: 'vandamme',    icon: '🥋', ar: 'جان كلود فان دام', en: 'Jean-Claude Van Damme', yes: 'europe actor action hollywood fighter born1970', maybe: 'othersport' },
  { id: 'statham',     icon: '🎬', ar: 'جيسون ستاثام', en: 'Jason Statham', yes: 'europe actor action hollywood born1970 uk' },
  { id: 'anthonyhopkins', icon: '🎬', ar: 'أنتوني هوبكنز', en: 'Anthony Hopkins', yes: 'europe born1950 actor hollywood born1970 oscar uk', maybe: 'villainroles' },
  { id: 'seanconnery', icon: '🕴️', ar: 'شون كونري', en: 'Sean Connery', yes: 'europe born1950 actor action hollywood born1970 oscar uk' },
  { id: 'emmawatson',  icon: '🎬', ar: 'إيما واتسون', en: 'Emma Watson', yes: 'female europe actor hollywood uk' },
  { id: 'katewinslet', icon: '🎬', ar: 'كيت وينسلت', en: 'Kate Winslet', yes: 'female europe actor hollywood oscar uk born1980' },
  { id: 'radcliffe',   icon: '🎬', ar: 'دانيال رادكليف', en: 'Daniel Radcliffe', yes: 'europe actor hollywood uk' },
  { id: 'defunes',     icon: '😂', ar: 'لوي دي فونيس', en: 'Louis de Funès', yes: 'europe born1930 born1950 actor comedy born1970 france', maybe: 'bw' },
  { id: 'amitabh',     icon: '🎬', ar: 'أميتاب باتشان', en: 'Amitabh Bachchan', yes: 'born1950 actor tvhost born1970', maybe: 'action hollywood singer' },
  { id: 'spielberg',   icon: '🎥', ar: 'ستيفن سبيلبرج', en: 'Steven Spielberg', yes: 'usa born1950 born1970 director oscar' },
  { id: 'hitchcock',   icon: '🎥', ar: 'ألفريد هيتشكوك', en: 'Alfred Hitchcock', yes: 'europe born1930 born1950 born1970 director uk', maybe: 'usa oscar' },
  { id: 'miyazaki',    icon: '🎥', ar: 'هاياو ميازاكي', en: 'Hayao Miyazaki', yes: 'asia born1950 born1970 director oscar', maybe: 'painter kids_v' },
  { id: 'waltdisney',  icon: '🐭', ar: 'والت ديزني', en: 'Walt Disney', yes: 'usa born1930 born1950 born1970 oscar', maybe: 'painter director kids_v' },
  /* ---------- Egyptian and Arab singers and composers ---------- */
  { id: 'hamaki',      icon: '🎤', ar: 'محمد حماقي', en: 'Mohamed Hamaki', yes: 'egypt arab singer born1980' },
  { id: 'adaweya',     icon: '🎤', ar: 'أحمد عدوية', en: 'Ahmed Adaweya', yes: 'egypt arab born1950 singer born1970', maybe: 'actor' },
  { id: 'najat',       icon: '🎤', ar: 'نجاة الصغيرة', en: 'Najat Al Saghira', yes: 'female egypt arab born1950 bw singer born1970', maybe: 'actor' },
  { id: 'abdelmottaleb', icon: '🎤', ar: 'محمد عبد المطلب', en: 'Mohamed Abdel Muttalib', yes: 'egypt arab born1930 born1950 singer born1970' },
  { id: 'mounib',      icon: '🎤', ar: 'أحمد منيب', en: 'Ahmed Mounib', yes: 'egypt arab south born1930 born1950 singer composer born1970' },
  { id: 'baligh',      icon: '🎼', ar: 'بليغ حمدي', en: 'Baligh Hamdi', yes: 'egypt arab born1950 composer born1970' },
  { id: 'ammarsherei', icon: '🎹', ar: 'عمار الشريعي', en: 'Ammar El Sherei', yes: 'egypt arab born1950 composer blind born1970', maybe: 'tvhost' },
  { id: 'mekkawy',     icon: '🎼', ar: 'سيد مكاوي', en: 'Sayed Mekkawy', yes: 'egypt arab born1930 born1950 singer composer blind born1970' },
  { id: 'latifa',      icon: '🎤', ar: 'لطيفة', en: 'Latifa', yes: 'female arab maghreb singer born1970', maybe: 'actor' },
  { id: 'chebkhaled',  icon: '🎤', ar: 'الشاب خالد', en: 'Cheb Khaled', yes: 'arab maghreb singer born1970' },
  { id: 'mohammedabdu', icon: '🎤', ar: 'محمد عبده', en: 'Mohammed Abdu', yes: 'arab gulf born1950 singer born1970', maybe: 'composer' },
  { id: 'jassmi',      icon: '🎤', ar: 'حسين الجسمي', en: 'Hussain Al Jassmi', yes: 'arab gulf singer born1980' },
  { id: 'ahlam',       icon: '🎤', ar: 'أحلام', en: 'Ahlam', yes: 'female arab gulf singer born1970' },
  { id: 'assala',      icon: '🎤', ar: 'أصالة', en: 'Assala', yes: 'female arab levant singer born1970' },
  { id: 'sabah',       icon: '🎤', ar: 'صباح', en: 'Sabah', yes: 'female arab levant born1930 born1950 actor bw singer born1970' },
  { id: 'wadihsafi',   icon: '🎤', ar: 'وديع الصافي', en: 'Wadih El Safi', yes: 'arab levant born1930 born1950 singer born1970', maybe: 'composer' },
  { id: 'sabahfakhri', icon: '🎤', ar: 'صباح فخري', en: 'Sabah Fakhri', yes: 'arab levant born1950 singer born1970' },
  { id: 'ragheb',      icon: '🎤', ar: 'راغب علامة', en: 'Ragheb Alama', yes: 'arab levant singer born1970' },
  { id: 'mohammedassaf', icon: '🎤', ar: 'محمد عساف', en: 'Mohammed Assaf', yes: 'arab levant singer' },
  /* ---------- world music ---------- */
  { id: 'dalida',      icon: '🎤', ar: 'داليدا', en: 'Dalida', yes: 'female europe born1950 singer born1970 france', maybe: 'egypt arab actor dance' },
  { id: 'piaf',        icon: '🎤', ar: 'إديث بياف', en: 'Edith Piaf', yes: 'female europe born1930 born1950 singer born1970 france' },
  { id: 'elvis',       icon: '🎸', ar: 'إلفيس بريسلي', en: 'Elvis Presley', yes: 'usa born1950 actor hollywood singer born1970', maybe: 'bw dance' },
  { id: 'whitney',     icon: '🎤', ar: 'ويتني هيوستن', en: 'Whitney Houston', yes: 'female usa actor hollywood singer born1970' },
  { id: 'taylorswift', icon: '🎤', ar: 'تايلور سويفت', en: 'Taylor Swift', yes: 'female usa singer', maybe: 'composer' },
  { id: 'shakira',     icon: '💃', ar: 'شاكيرا', en: 'Shakira', yes: 'female latam singer born1980 dance' },
  { id: 'adele',       icon: '🎤', ar: 'أديل', en: 'Adele', yes: 'female europe singer oscar uk' },
  { id: 'edsheeran',   icon: '🎸', ar: 'إد شيران', en: 'Ed Sheeran', yes: 'europe singer uk', maybe: 'composer' },
  { id: 'enrique',     icon: '🎤', ar: 'إنريكي إجليسياس', en: 'Enrique Iglesias', yes: 'europe singer born1980' },
  { id: 'pavarotti',   icon: '🎶', ar: 'بافاروتي', en: 'Luciano Pavarotti', yes: 'europe born1950 singer born1970' },
  { id: 'tchaikovsky', icon: '🎼', ar: 'تشايكوفسكي', en: 'Tchaikovsky', yes: 'europe born1930 born1950 composer born1970' },
  { id: 'yanni',       icon: '🎹', ar: 'ياني', en: 'Yanni', yes: 'europe composer born1970', maybe: 'usa' },
  /* ---------- Egyptian football ---------- */
  { id: 'trezeguet',   icon: '⚽', ar: 'محمود تريزيجيه', en: 'Mahmoud Trézéguet', yes: 'egypt arab athlete football ahly england', maybe: 'striker midfield', no: 'zamalek afcon' },
  { id: 'hegazi',      icon: '⚽', ar: 'أحمد حجازي', en: 'Ahmed Hegazi', yes: 'egypt arab athlete football ahly england italy defender', no: 'zamalek afcon' },
  { id: 'amrzaki',     icon: '⚽', ar: 'عمرو زكي', en: 'Amr Zaki', yes: 'egypt arab athlete football zamalek england striker afcon', no: 'ahly' },
  { id: 'moteab',      icon: '⚽', ar: 'عماد متعب', en: 'Emad Moteab', yes: 'egypt arab athlete football ahly striker afcon', no: 'zamalek england' },
  { id: 'waelgomaa',   icon: '⚽', ar: 'وائل جمعة', en: 'Wael Gomaa', yes: 'egypt arab athlete football ahly afcon defender born1980', no: 'zamalek' },
  { id: 'ahmedfathy',  icon: '⚽', ar: 'أحمد فتحي', en: 'Ahmed Fathy', yes: 'egypt arab athlete football ahly england afcon defender', maybe: 'midfield', no: 'zamalek' },
  { id: 'elmohamady',  icon: '⚽', ar: 'أحمد المحمدي', en: 'Ahmed Elmohamady', yes: 'egypt arab athlete football england afcon defender', maybe: 'midfield', no: 'ahly zamalek' },
  { id: 'ibrahimhassan', icon: '⚽', ar: 'إبراهيم حسن', en: 'Ibrahim Hassan', yes: 'egypt arab athlete football ahly zamalek afcon born1970 defender', maybe: 'coach' },
  { id: 'gabaski',     icon: '🧤', ar: 'محمد أبو جبل (جباسكي)', en: 'Mohamed Abou Gabal (Gabaski)', yes: 'egypt arab athlete football zamalek keeper', no: 'ahly afcon' },
  { id: 'shobeir',     icon: '🧤', ar: 'أحمد شوبير', en: 'Ahmed Shobeir', yes: 'egypt arab tvhost athlete football ahly keeper born1970', maybe: 'sports_v', no: 'zamalek' },
  { id: 'mostafamohamed', icon: '⚽', ar: 'مصطفى محمد', en: 'Mostafa Mohamed', yes: 'egypt arab athlete football zamalek striker', no: 'ahly afcon' },
  { id: 'marmoush',    icon: '⚽', ar: 'عمر مرموش', en: 'Omar Marmoush', yes: 'egypt arab athlete football england striker', no: 'ahly zamalek afcon' },
  { id: 'mido',        icon: '⚽', ar: 'ميدو (أحمد حسام)', en: 'Mido (Ahmed Hossam)', yes: 'egypt arab athlete football zamalek england spain striker afcon coach italy', maybe: 'tvhost', no: 'ahly' },
  { id: 'hazememam',   icon: '⚽', ar: 'حازم إمام', en: 'Hazem Emam', yes: 'egypt arab athlete football zamalek italy midfield born1980', maybe: 'striker afcon', no: 'ahly' },
  { id: 'magdiabdelghani', icon: '⚽', ar: 'مجدي عبد الغني', en: 'Magdi Abdelghani', yes: 'egypt arab athlete football ahly born1970 midfield', maybe: 'tvhost afcon', no: 'zamalek' },
  { id: 'faroukgaafar', icon: '⚽', ar: 'فاروق جعفر', en: 'Farouk Gaafar', yes: 'egypt arab athlete football zamalek coach born1970', maybe: 'striker midfield', no: 'ahly' },
  { id: 'salehselim',  icon: '⚽', ar: 'صالح سليم', en: 'Saleh Selim', yes: 'egypt arab born1950 bw athlete football ahly born1970', maybe: 'actor', no: 'zamalek' },
  { id: 'hassanshehata', icon: '📋', ar: 'حسن شحاتة', en: 'Hassan Shehata', yes: 'egypt arab born1950 athlete football zamalek afcon coach born1970', no: 'ahly' },
  { id: 'gohary',      icon: '📋', ar: 'محمود الجوهري', en: 'Mahmoud El-Gohary', yes: 'egypt arab born1950 athlete football ahly afcon coach born1970' },
  { id: 'manueljose',  icon: '📋', ar: 'مانويل جوزيه', en: 'Manuel José', yes: 'europe born1950 coach born1970', no: 'ahly' },
  /* ---------- Arab and African football ---------- */
  { id: 'ziyech',      icon: '⚽', ar: 'حكيم زياش', en: 'Hakim Ziyech', yes: 'arab maghreb athlete football england midfield', no: 'afcon' },
  { id: 'bounou',      icon: '🧤', ar: 'ياسين بونو', en: 'Yassine Bounou', yes: 'arab maghreb athlete football spain keeper', no: 'afcon' },
  { id: 'benatia',     icon: '⚽', ar: 'المهدي بن عطية', en: 'Medhi Benatia', yes: 'arab maghreb athlete football italy defender', maybe: 'france' },
  { id: 'ennesyri',    icon: '⚽', ar: 'يوسف النصيري', en: 'Youssef En-Nesyri', yes: 'arab maghreb athlete football spain striker' },
  { id: 'madjer',      icon: '⚽', ar: 'رابح ماجر', en: 'Rabah Madjer', yes: 'arab maghreb athlete football spain striker afcon coach born1970' },
  { id: 'maaloul',     icon: '⚽', ar: 'علي معلول', en: 'Ali Maaloul', yes: 'arab maghreb athlete football ahly defender' },
  { id: 'samijaber',   icon: '⚽', ar: 'سامي الجابر', en: 'Sami Al-Jaber', yes: 'arab gulf athlete football striker born1975', maybe: 'england coach' },
  { id: 'majedabdullah', icon: '⚽', ar: 'ماجد عبد الله', en: 'Majed Abdullah', yes: 'arab gulf athlete football striker born1970' },
  { id: 'deayea',      icon: '🧤', ar: 'محمد الدعيع', en: 'Mohamed Al-Deayea', yes: 'arab gulf athlete football keeper born1975' },
  { id: 'drogba',      icon: '⚽', ar: 'ديدييه دروجبا', en: 'Didier Drogba', yes: 'africa athlete football england striker born1980', no: 'afcon worldcup' },
  { id: 'etoo',        icon: '⚽', ar: 'صامويل إيتو', en: "Samuel Eto'o", yes: 'africa athlete football england spain striker afcon olympic italy' },
  { id: 'percytau',    icon: '⚽', ar: 'بيرسي تاو', en: 'Percy Tau', yes: 'africa athlete football ahly england', maybe: 'striker midfield' },
  /* ---------- world football ---------- */
  { id: 'benzema',     icon: '⚽', ar: 'كريم بنزيما', en: 'Karim Benzema', yes: 'europe athlete football spain striker ballon france', maybe: 'arab maghreb', no: 'worldcup' },
  { id: 'mbappe',      icon: '⚽', ar: 'كيليان مبابي', en: 'Kylian Mbappé', yes: 'europe athlete football spain striker worldcup france' },
  { id: 'henry',       icon: '⚽', ar: 'تيري هنري', en: 'Thierry Henry', yes: 'europe athlete football england spain striker worldcup coach france italy born1980' },
  { id: 'ronaldinho',  icon: '⚽', ar: 'رونالدينيو', en: 'Ronaldinho', yes: 'latam athlete football spain worldcup ballon olympic italy midfield', maybe: 'striker' },
  { id: 'ronaldonazario', icon: '⚽', ar: 'رونالدو البرازيلي', en: 'Ronaldo Nazário', yes: 'latam athlete football spain striker worldcup ballon olympic italy born1980' },
  { id: 'neymar',      icon: '⚽', ar: 'نيمار', en: 'Neymar', yes: 'latam athlete football spain striker olympic', maybe: 'midfield', no: 'worldcup' },
  { id: 'robertocarlos', icon: '⚽', ar: 'روبرتو كارلوس', en: 'Roberto Carlos', yes: 'latam athlete football spain worldcup olympic italy defender born1975' },
  { id: 'dimaria',     icon: '⚽', ar: 'أنخيل دي ماريا', en: 'Ángel Di María', yes: 'latam athlete football england spain worldcup olympic italy midfield', maybe: 'striker' },
  { id: 'suarez',      icon: '⚽', ar: 'لويس سواريز', en: 'Luis Suárez', yes: 'latam athlete football england spain striker', no: 'worldcup' },
  { id: 'distefano',   icon: '⚽', ar: 'ألفريدو دي ستيفانو', en: 'Alfredo Di Stéfano', yes: 'latam born1930 born1950 athlete football spain striker ballon coach born1970', maybe: 'europe midfield' },
  { id: 'beckham',     icon: '⚽', ar: 'ديفيد بيكهام', en: 'David Beckham', yes: 'europe athlete football england spain uk italy midfield born1980', no: 'worldcup' },
  { id: 'rooney',      icon: '⚽', ar: 'واين روني', en: 'Wayne Rooney', yes: 'europe athlete football england striker coach uk', maybe: 'midfield', no: 'worldcup' },
  { id: 'gerrard',     icon: '⚽', ar: 'ستيفن جيرارد', en: 'Steven Gerrard', yes: 'europe athlete football england coach uk midfield', no: 'worldcup' },
  { id: 'buffon',      icon: '🧤', ar: 'جيانلويجي بوفون', en: 'Gianluigi Buffon', yes: 'europe athlete football keeper worldcup italy born1980' },
  { id: 'maldini',     icon: '⚽', ar: 'باولو مالديني', en: 'Paolo Maldini', yes: 'europe athlete football born1970 italy defender', no: 'worldcup' },
  { id: 'totti',       icon: '⚽', ar: 'فرانشيسكو توتي', en: 'Francesco Totti', yes: 'europe athlete football worldcup italy born1980', maybe: 'striker midfield' },
  { id: 'ramos',       icon: '⚽', ar: 'سيرجيو راموس', en: 'Sergio Ramos', yes: 'europe athlete football spain worldcup defender' },
  { id: 'iniesta',     icon: '⚽', ar: 'أندريس إنييستا', en: 'Andrés Iniesta', yes: 'europe athlete football spain worldcup midfield' },
  { id: 'casillas',    icon: '🧤', ar: 'إيكر كاسياس', en: 'Iker Casillas', yes: 'europe athlete football spain keeper worldcup' },
  { id: 'modric',      icon: '⚽', ar: 'لوكا مودريتش', en: 'Luka Modrić', yes: 'europe athlete football england spain ballon italy midfield', no: 'worldcup' },
  { id: 'lewandowski', icon: '⚽', ar: 'روبرت ليفاندوفسكي', en: 'Robert Lewandowski', yes: 'europe athlete football spain striker', no: 'worldcup' },
  { id: 'haaland',     icon: '⚽', ar: 'إرلينج هالاند', en: 'Erling Haaland', yes: 'europe athlete football england striker' },
  { id: 'vandijk',     icon: '⚽', ar: 'فيرجيل فان دايك', en: 'Virgil van Dijk', yes: 'europe athlete football england defender' },
  { id: 'debruyne',    icon: '⚽', ar: 'كيفن دي بروين', en: 'Kevin De Bruyne', yes: 'europe athlete football england italy midfield' },
  { id: 'zlatan',      icon: '⚽', ar: 'زلاتان إبراهيموفيتش', en: 'Zlatan Ibrahimović', yes: 'europe athlete football england spain striker italy', no: 'worldcup' },
  { id: 'son',         icon: '⚽', ar: 'سون هيونج مين', en: 'Son Heung-min', yes: 'asia athlete football england striker' },
  { id: 'cruyff',      icon: '⚽', ar: 'يوهان كرويف', en: 'Johan Cruyff', yes: 'europe born1950 athlete football spain ballon coach born1970', maybe: 'striker midfield', no: 'worldcup' },
  { id: 'beckenbauer', icon: '⚽', ar: 'فرانز بيكنباور', en: 'Franz Beckenbauer', yes: 'europe born1950 athlete football worldcup ballon coach born1970 defender', maybe: 'midfield' },
  { id: 'yashin',      icon: '🧤', ar: 'ليف ياشين', en: 'Lev Yashin', yes: 'europe born1930 born1950 athlete football keeper ballon olympic born1970' },
  { id: 'eusebio',     icon: '⚽', ar: 'أوزيبيو', en: 'Eusébio', yes: 'europe born1950 athlete football striker ballon born1970', maybe: 'africa' },
  { id: 'puskas',      icon: '⚽', ar: 'فيرينتس بوشكاش', en: 'Ferenc Puskás', yes: 'europe born1930 born1950 athlete football spain striker coach olympic born1970' },
  { id: 'guardiola',   icon: '📋', ar: 'بيب جوارديولا', en: 'Pep Guardiola', yes: 'europe athlete football spain coach olympic italy midfield born1975', maybe: 'england' },
  { id: 'ferguson',    icon: '📋', ar: 'أليكس فيرجسون', en: 'Alex Ferguson', yes: 'europe born1950 coach born1970 uk', maybe: 'athlete football england' },
  /* ---------- other sports ---------- */
  { id: 'alifarag',    icon: '🏆', ar: 'علي فرج', en: 'Ali Farag', yes: 'egypt arab athlete othersport squash' },
  { id: 'noursherbini', icon: '🏆', ar: 'نور الشربيني', en: 'Nour El Sherbini', yes: 'female egypt arab athlete othersport squash' },
  { id: 'mayarsherif', icon: '🎾', ar: 'ميار شريف', en: 'Mayar Sherif', yes: 'female egypt arab athlete othersport tennis' },
  { id: 'onsjabeur',   icon: '🎾', ar: 'أنس جابر', en: 'Ons Jabeur', yes: 'female arab maghreb athlete othersport tennis' },
  { id: 'elahmar',     icon: '🤾', ar: 'أحمد الأحمر', en: 'Ahmed El-Ahmar', yes: 'egypt arab athlete othersport' },
  { id: 'nahlaramadan', icon: '🏋️', ar: 'نهلة رمضان', en: 'Nahla Ramadan', yes: 'female egypt arab athlete othersport lifter' },
  { id: 'abeerabdelrahman', icon: '🏋️', ar: 'عبير عبد الرحمن', en: 'Abeer Abdel Rahman', yes: 'female egypt arab athlete othersport olympic lifter' },
  { id: 'mohamedehab', icon: '🏋️', ar: 'محمد إيهاب', en: 'Mohamed Ehab', yes: 'egypt arab athlete othersport olympic lifter' },
  { id: 'hedayamalak', icon: '🥋', ar: 'هداية ملاك', en: 'Hedaya Malak', yes: 'female egypt arab athlete othersport fighter olympic' },
  { id: 'rashwan',     icon: '🥋', ar: 'محمد رشوان', en: 'Mohamed Rashwan', yes: 'egypt arab athlete othersport fighter olympic born1970' },
  { id: 'faridaosman', icon: '🏊', ar: 'فريدة عثمان', en: 'Farida Osman', yes: 'female egypt arab athlete othersport swimmer' },
  { id: 'abouheif',    icon: '🏊', ar: 'عبد اللطيف أبو هيف', en: 'Abdel Latif Abou Heif', yes: 'egypt arab born1930 born1950 athlete othersport born1970 swimmer' },
  { id: 'elgendy',     icon: '🏅', ar: 'أحمد الجندي', en: 'Ahmed Elgendy', yes: 'egypt arab athlete othersport olympic' },
  { id: 'guerrouj',    icon: '🏃', ar: 'هشام الكروج', en: 'Hicham El Guerrouj', yes: 'arab maghreb athlete othersport olympic runner born1975' },
  { id: 'aouita',      icon: '🏃', ar: 'سعيد عويطة', en: 'Said Aouita', yes: 'arab maghreb athlete othersport olympic born1970 runner' },
  { id: 'barshim',     icon: '🏃', ar: 'معتز برشم', en: 'Mutaz Barshim', yes: 'arab gulf athlete othersport olympic runner' },
  { id: 'federer',     icon: '🎾', ar: 'روجر فيدرر', en: 'Roger Federer', yes: 'europe athlete othersport olympic tennis' },
  { id: 'serena',      icon: '🎾', ar: 'سيرينا ويليامز', en: 'Serena Williams', yes: 'female usa athlete othersport olympic tennis' },
  { id: 'phelps',      icon: '🏊', ar: 'مايكل فيلبس', en: 'Michael Phelps', yes: 'usa athlete othersport olympic swimmer' },
  { id: 'carllewis',   icon: '🏃', ar: 'كارل لويس', en: 'Carl Lewis', yes: 'usa athlete othersport olympic born1970 runner' },
  { id: 'mofarah',     icon: '🏃', ar: 'مو فرح', en: 'Mo Farah', yes: 'europe athlete othersport olympic uk runner', maybe: 'africa' },
  { id: 'kipchoge',    icon: '🏃', ar: 'إليود كيبتشوجي', en: 'Eliud Kipchoge', yes: 'africa athlete othersport olympic runner' },
  { id: 'kobe',        icon: '🏀', ar: 'كوبي براينت', en: 'Kobe Bryant', yes: 'usa athlete othersport olympic oscar basket born1980' },
  { id: 'yaoming',     icon: '🏀', ar: 'ياو مينج', en: 'Yao Ming', yes: 'asia athlete othersport basket' },
  { id: 'comaneci',    icon: '🤸', ar: 'نادية كومانتشي', en: 'Nadia Comăneci', yes: 'female europe athlete othersport olympic born1970' },
  { id: 'biles',       icon: '🤸', ar: 'سيمون بايلز', en: 'Simone Biles', yes: 'female usa athlete othersport olympic' },
  { id: 'schumacher',  icon: '🏎️', ar: 'مايكل شوماخر', en: 'Michael Schumacher', yes: 'europe athlete othersport born1970' },
  { id: 'senna',       icon: '🏎️', ar: 'أيرتون سينا', en: 'Ayrton Senna', yes: 'latam athlete othersport born1970' },
  { id: 'hamilton',    icon: '🏎️', ar: 'لويس هاميلتون', en: 'Lewis Hamilton', yes: 'europe athlete othersport uk' },
  /* ---------- writers and poets ---------- */
  { id: 'tawfikhakim', icon: '✍️', ar: 'توفيق الحكيم', en: 'Tawfiq al-Hakim', yes: 'egypt arab born1930 born1950 theater writer born1970' },
  { id: 'youssefidris', icon: '✍️', ar: 'يوسف إدريس', en: 'Yusuf Idris', yes: 'egypt arab born1930 born1950 writer medic born1970' },
  { id: 'mostafamahmoud', icon: '🔭', ar: 'مصطفى محمود', en: 'Mostafa Mahmoud', yes: 'egypt arab born1930 born1950 tvhost writer medic born1970 explain_v' },
  { id: 'ahmedkhaledtawfik', icon: '📚', ar: 'أحمد خالد توفيق', en: 'Ahmed Khaled Tawfik', yes: 'egypt arab writer medic born1970' },
  { id: 'salahjahin',  icon: '📜', ar: 'صلاح جاهين', en: 'Salah Jahin', yes: 'egypt arab born1950 writer poet born1970', maybe: 'actor painter' },
  { id: 'abnudi',      icon: '📜', ar: 'عبد الرحمن الأبنودي', en: 'Abdel Rahman el-Abnudi', yes: 'egypt arab south born1950 writer poet born1970' },
  { id: 'mahmouddarwish', icon: '📜', ar: 'محمود درويش', en: 'Mahmoud Darwish', yes: 'arab levant born1950 writer poet born1970' },
  { id: 'nizar',       icon: '📜', ar: 'نزار قباني', en: 'Nizar Qabbani', yes: 'arab levant born1930 born1950 writer poet born1970' },
  { id: 'gibran',      icon: '✍️', ar: 'جبران خليل جبران', en: 'Kahlil Gibran', yes: 'arab levant born1930 born1950 writer poet painter born1970', maybe: 'usa' },
  { id: 'maiziadeh',   icon: '✍️', ar: 'مي زيادة', en: 'May Ziadeh', yes: 'female arab levant born1930 born1950 writer born1970', maybe: 'egypt poet' },
  { id: 'antara',      icon: '⚔️', ar: 'عنترة بن شداد', en: 'Antarah ibn Shaddad', yes: 'arab before1800 born1930 born1950 warrior writer poet born1970 before1500', maybe: 'gulf' },
  { id: 'khansa',      icon: '📜', ar: 'الخنساء', en: 'Al-Khansa', yes: 'female arab before1800 born1930 born1950 writer poet born1970 before1500', maybe: 'gulf' },
  { id: 'maarri',      icon: '📜', ar: 'أبو العلاء المعري', en: "Al-Ma'arri", yes: 'arab levant before1800 born1930 born1950 writer poet blind born1970 before1500' },
  { id: 'ibnkhaldun',  icon: '📜', ar: 'ابن خلدون', en: 'Ibn Khaldun', yes: 'arab maghreb before1800 born1930 born1950 writer born1970 before1500', maybe: 'science' },
  { id: 'dickens',     icon: '✍️', ar: 'تشارلز ديكنز', en: 'Charles Dickens', yes: 'europe born1930 born1950 writer born1970 uk' },
  { id: 'agatha',      icon: '🔍', ar: 'أجاثا كريستي', en: 'Agatha Christie', yes: 'female europe born1930 born1950 writer born1970 uk' },
  { id: 'victorhugo',  icon: '✍️', ar: 'فيكتور هوجو', en: 'Victor Hugo', yes: 'europe born1930 born1950 writer poet born1970 france' },
  { id: 'verne',       icon: '✍️', ar: 'جول فيرن', en: 'Jules Verne', yes: 'europe born1930 born1950 writer born1970 france' },
  { id: 'tolstoy',     icon: '✍️', ar: 'تولستوي', en: 'Leo Tolstoy', yes: 'europe born1930 born1950 writer born1970' },
  { id: 'twain',       icon: '✍️', ar: 'مارك توين', en: 'Mark Twain', yes: 'usa born1930 born1950 writer born1970' },
  { id: 'hemingway',   icon: '✍️', ar: 'إرنست همنجواي', en: 'Ernest Hemingway', yes: 'usa born1930 born1950 writer nobel born1970' },
  { id: 'homer',       icon: '📜', ar: 'هوميروس', en: 'Homer', yes: 'europe before1800 bc born1930 born1950 writer poet born1970', maybe: 'blind' },
  { id: 'aristotle',   icon: '📜', ar: 'أرسطو', en: 'Aristotle', yes: 'europe before1800 bc born1930 born1950 writer science born1970' },
  { id: 'confucius',   icon: '📜', ar: 'كونفوشيوس', en: 'Confucius', yes: 'asia before1800 bc born1930 born1950 writer born1970' },
  /* ---------- science and invention ---------- */
  { id: 'imhotep',     icon: '🏛️', ar: 'إمحوتب', en: 'Imhotep', yes: 'egypt before1800 bc pharaoh born1930 born1950 science medic born1970 built', maybe: 'arab' },
  { id: 'mosharafa',   icon: '🔬', ar: 'علي مصطفى مشرفة', en: 'Ali Moustafa Mosharafa', yes: 'egypt arab born1930 born1950 science born1970', maybe: 'math' },
  { id: 'sameeramoussa', icon: '⚛️', ar: 'سميرة موسى', en: 'Sameera Moussa', yes: 'female egypt arab born1930 born1950 science born1970' },
  { id: 'faroukelbaz', icon: '🚀', ar: 'فاروق الباز', en: 'Farouk El-Baz', yes: 'egypt arab born1950 science born1970', maybe: 'usa explorer' },
  { id: 'hassanfathy', icon: '🏛️', ar: 'حسن فتحي', en: 'Hassan Fathy', yes: 'egypt arab born1930 born1950 born1970 built' },
  { id: 'zahahadid',   icon: '🏛️', ar: 'زها حديد', en: 'Zaha Hadid', yes: 'female arab gulf born1970 built', maybe: 'europe uk' },
  { id: 'ibnhaytham',  icon: '🔭', ar: 'ابن الهيثم', en: 'Ibn al-Haytham', yes: 'arab gulf before1800 born1930 born1950 science born1970 before1500', maybe: 'egypt' },
  { id: 'ibnnafis',    icon: '⚕️', ar: 'ابن النفيس', en: 'Ibn al-Nafis', yes: 'arab levant before1800 born1930 born1950 science medic born1970 before1500', maybe: 'egypt' },
  { id: 'archimedes',  icon: '🛁', ar: 'أرشميدس', en: 'Archimedes', yes: 'europe before1800 bc born1930 born1950 science born1970 math' },
  { id: 'hippocrates', icon: '⚕️', ar: 'أبقراط', en: 'Hippocrates', yes: 'europe before1800 bc born1930 born1950 medic born1970', maybe: 'writer science' },
  { id: 'galileo',     icon: '🔭', ar: 'جاليليو', en: 'Galileo Galilei', yes: 'europe before1800 born1930 born1950 science born1970', maybe: 'math' },
  { id: 'champollion', icon: '📜', ar: 'شامبليون', en: 'Champollion', yes: 'europe born1930 born1950 science born1970 france before1800' },
  { id: 'tesla',       icon: '⚡', ar: 'نيكولا تسلا', en: 'Nikola Tesla', yes: 'europe born1930 born1950 science born1970', maybe: 'usa' },
  { id: 'bell',        icon: '☎️', ar: 'جراهام بيل', en: 'Alexander Graham Bell', yes: 'europe born1930 born1950 science born1970 uk', maybe: 'usa' },
  { id: 'pasteur',     icon: '🧪', ar: 'لويس باستير', en: 'Louis Pasteur', yes: 'europe born1930 born1950 science born1970 france', maybe: 'medic' },
  { id: 'fleming',     icon: '🧫', ar: 'ألكسندر فليمنج', en: 'Alexander Fleming', yes: 'europe born1930 born1950 science medic nobel born1970 uk' },
  { id: 'hawking',     icon: '🌌', ar: 'ستيفن هوكينج', en: 'Stephen Hawking', yes: 'europe born1950 science born1970 uk', maybe: 'writer math' },
  { id: 'gustaveeiffel',      icon: '🗼', ar: 'جوستاف إيفل', en: 'Gustave Eiffel', yes: 'europe born1930 born1950 born1970 built france', maybe: 'science' },
  /* ---------- history: rulers, leaders, explorers ---------- */
  { id: 'khufu',       icon: '👑', ar: 'خوفو', en: 'Khufu', yes: 'egypt before1800 bc pharaoh born1930 born1950 ruler born1970 built', maybe: 'arab' },
  { id: 'hatshepsut',  icon: '👑', ar: 'حتشبسوت', en: 'Hatshepsut', yes: 'female egypt before1800 bc pharaoh born1930 born1950 ruler born1970 built', maybe: 'arab' },
  { id: 'ahmose',      icon: '⚔️', ar: 'أحمس', en: 'Ahmose I', yes: 'egypt before1800 bc pharaoh born1930 born1950 ruler warrior born1970', maybe: 'arab' },
  { id: 'qutuz',       icon: '⚔️', ar: 'سيف الدين قطز', en: 'Qutuz', yes: 'before1800 born1930 born1950 ruler warrior born1970 before1500', maybe: 'egypt arab' },
  { id: 'shajar',      icon: '👑', ar: 'شجر الدر', en: 'Shajar al-Durr', yes: 'female before1800 born1930 born1950 ruler born1970 before1500', maybe: 'egypt arab warrior' },
  { id: 'harun',       icon: '👑', ar: 'هارون الرشيد', en: 'Harun al-Rashid', yes: 'arab gulf before1800 born1930 born1950 ruler born1970 before1500' },
  { id: 'muhammadalipasha', icon: '🏰', ar: 'محمد علي باشا', en: 'Muhammad Ali Pasha', yes: 'born1930 born1950 ruler born1970 built before1800 warrior', maybe: 'egypt arab europe' },
  { id: 'khediveismail', icon: '👑', ar: 'الخديوي إسماعيل', en: 'Khedive Ismail', yes: 'egypt arab born1930 born1950 ruler born1970 built' },
  { id: 'kingfarouk',  icon: '👑', ar: 'الملك فاروق', en: 'King Farouk', yes: 'egypt arab born1930 born1950 ruler born1970' },
  { id: 'orabi',       icon: '⚔️', ar: 'أحمد عرابي', en: 'Ahmed Orabi', yes: 'egypt arab born1930 born1950 warrior born1970' },
  { id: 'victoria',    icon: '👑', ar: 'الملكة فيكتوريا', en: 'Queen Victoria', yes: 'female europe born1930 born1950 ruler born1970 uk' },
  { id: 'genghis',     icon: '⚔️', ar: 'جنكيز خان', en: 'Genghis Khan', yes: 'asia before1800 born1930 born1950 ruler warrior born1970 before1500' },
  { id: 'washington',  icon: '⚔️', ar: 'جورج واشنطن', en: 'George Washington', yes: 'usa before1800 born1930 born1950 ruler warrior born1970' },
  { id: 'lincoln',     icon: '🎩', ar: 'أبراهام لينكولن', en: 'Abraham Lincoln', yes: 'usa born1930 born1950 ruler born1970' },
  { id: 'columbus',    icon: '⛵', ar: 'كريستوفر كولومبوس', en: 'Christopher Columbus', yes: 'europe before1800 born1930 born1950 explorer born1970 before1500' },
  { id: 'gagarin',     icon: '🚀', ar: 'يوري جاجارين', en: 'Yuri Gagarin', yes: 'europe born1950 explorer born1970' },
  { id: 'cousteau',    icon: '🤿', ar: 'جاك كوستو', en: 'Jacques Cousteau', yes: 'europe born1930 born1950 explorer born1970 france', maybe: 'tvhost science explain_v' },
  { id: 'howardcarter', icon: '⛏️', ar: 'هوارد كارتر', en: 'Howard Carter', yes: 'europe born1930 born1950 explorer born1970 uk', maybe: 'science' },
  /* ---------- painters ---------- */
  { id: 'michelangelo', icon: '🎨', ar: 'مايكل أنجلو', en: 'Michelangelo', yes: 'europe before1800 born1930 born1950 painter born1970 before1500', maybe: 'built' },
  { id: 'mahmoudsaid', icon: '🎨', ar: 'محمود سعيد', en: 'Mahmoud Saïd', yes: 'egypt arab born1930 born1950 painter born1970' },
]};
