/* العرّاف: famous people (kind 'p'). Egyptian and Arab first, then the world-famous; only
   facts that don't change (where they are from, what they did, what they won, when they were
   born) - never whether they are alive or still playing. No politicians of our time, nothing
   divisive. One line each: id, icon (what they are known for, shown on a drawn silhouette -
   never a photo), ar, en, and the question ids (OracleQuestions.js) that are true (yes),
   partly (maybe) and firmly not (no). A question about people in none of the three reads as
   «غالباً لأ». notes/games/oracle.md, "Writing entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_PEOPLE = { kind: 'p', list: [
  /* ---------- football ---------- */
  { id: 'salah',       icon: '⚽', ar: 'محمد صلاح', en: 'Mohamed Salah', yes: 'egypt england striker italy', no: 'ahly zamalek worldcup afcon' },
  { id: 'aboutrika',   icon: '⚽', ar: 'محمد أبو تريكة', en: 'Mohamed Aboutrika', yes: 'egypt ahly afcon', no: 'zamalek england' },
  { id: 'hossamhassan', icon: '⚽', ar: 'حسام حسن', en: 'Hossam Hassan', yes: 'egypt ahly zamalek striker afcon coach born1970' },
  { id: 'hadary',      icon: '🧤', ar: 'عصام الحضري', en: 'Essam El-Hadary', yes: 'egypt ahly keeper afcon', maybe: 'zamalek' },
  { id: 'khatib',      icon: '⚽', ar: 'محمود الخطيب', en: 'Mahmoud El Khatib', yes: 'egypt ahly striker afcon born1970', no: 'zamalek' },
  { id: 'shikabala',   icon: '⚽', ar: 'شيكابالا', en: 'Shikabala', yes: 'egypt zamalek', no: 'ahly' },
  { id: 'ahmedhassan', icon: '⚽', ar: 'أحمد حسن', en: 'Ahmed Hassan', yes: 'egypt ahly zamalek afcon', maybe: 'defender', no: 'striker' },
  { id: 'elneny',      icon: '⚽', ar: 'محمد النني', en: 'Mohamed Elneny', yes: 'egypt england', no: 'ahly zamalek striker' },
  { id: 'messi',       icon: '⚽', ar: 'ليونيل ميسي', en: 'Lionel Messi', yes: 'latam spain worldcup ballon striker olympic' },
  { id: 'ronaldo',     icon: '⚽', ar: 'كريستيانو رونالدو', en: 'Cristiano Ronaldo', yes: 'europe england spain ballon striker italy', no: 'worldcup' },
  { id: 'zidane',      icon: '⚽', ar: 'زين الدين زيدان', en: 'Zinedine Zidane', yes: 'europe spain worldcup ballon coach italy france', maybe: 'maghreb' },
  { id: 'maradona',    icon: '⚽', ar: 'دييجو مارادونا', en: 'Diego Maradona', yes: 'latam spain worldcup coach born1970 italy', maybe: 'striker' },
  { id: 'pele',        icon: '⚽', ar: 'بيليه', en: 'Pelé', yes: 'latam worldcup striker born1950' },
  { id: 'mahrez',      icon: '⚽', ar: 'رياض محرز', en: 'Riyad Mahrez', yes: 'maghreb england afcon' },
  { id: 'hakimi',      icon: '⚽', ar: 'أشرف حكيمي', en: 'Achraf Hakimi', yes: 'maghreb spain italy defender olympic', no: 'striker' },
  { id: 'mane',        icon: '⚽', ar: 'ساديو ماني', en: 'Sadio Mané', yes: 'africa england afcon striker' },
  /* ---------- other sports ---------- */
  { id: 'muhammadali', icon: '🥊', ar: 'محمد علي كلاي', en: 'Muhammad Ali', yes: 'usa fighter othersport olympic born1950' },
  { id: 'bolt',        icon: '🏃', ar: 'يوسين بولت', en: 'Usain Bolt', yes: 'othersport olympic runner' },
  { id: 'jordan',      icon: '🏀', ar: 'مايكل جوردان', en: 'Michael Jordan', yes: 'usa othersport olympic born1970 basket' },
  { id: 'karamgaber',  icon: '🤼', ar: 'كرم جابر', en: 'Karam Gaber', yes: 'egypt othersport olympic fighter' },
  /* ---------- actors ---------- */
  { id: 'adelimam',    icon: '🎭', ar: 'عادل إمام', en: 'Adel Imam', yes: 'egypt actor comedy theater born1950', maybe: 'series bw', no: 'born1930' },
  { id: 'ahmedzaki',   icon: '🎬', ar: 'أحمد زكي', en: 'Ahmed Zaki', yes: 'egypt actor born1950', no: 'comedy' },
  { id: 'omarsharif',  icon: '🎬', ar: 'عمر الشريف', en: 'Omar Sharif', yes: 'egypt actor hollywood bw born1950' },
  { id: 'ismailyassin', icon: '😂', ar: 'إسماعيل ياسين', en: 'Ismail Yassin', yes: 'egypt actor comedy bw born1930', maybe: 'theater singer' },
  { id: 'fouad',       icon: '🎭', ar: 'فؤاد المهندس', en: 'Fouad El-Mohandes', yes: 'egypt actor comedy theater bw born1930 series fawazeer' },
  { id: 'fareedshawqi', icon: '🎬', ar: 'فريد شوقي', en: 'Farid Shawqi', yes: 'egypt actor bw born1930 action', maybe: 'villainroles' },
  { id: 'henedy',      icon: '😄', ar: 'محمد هنيدي', en: 'Mohamed Henedy', yes: 'egypt actor comedy born1970', maybe: 'theater' },
  { id: 'helmy',       icon: '😄', ar: 'أحمد حلمي', en: 'Ahmed Helmy', yes: 'egypt actor comedy tvhost born1970', no: 'theater' },
  { id: 'fakharany',   icon: '🎭', ar: 'يحيى الفخراني', en: 'Yehia El-Fakharany', yes: 'egypt actor series theater born1950' },
  { id: 'sakka',       icon: '🎬', ar: 'أحمد السقا', en: 'Ahmed El Sakka', yes: 'egypt actor action', no: 'comedy' },
  { id: 'faten',       icon: '🎬', ar: 'فاتن حمامة', en: 'Faten Hamama', yes: 'female egypt actor bw born1950' },
  { id: 'soad',        icon: '🎬', ar: 'سعاد حسني', en: 'Soad Hosny', yes: 'female egypt actor bw born1950 singer' },
  { id: 'sherihan',    icon: '💃', ar: 'شريهان', en: 'Sherihan', yes: 'female egypt actor fawazeer born1970', maybe: 'series singer theater' },
  { id: 'yousra',      icon: '🎬', ar: 'يسرا', en: 'Yousra', yes: 'female egypt actor series born1970' },
  { id: 'chaplin',     icon: '🎩', ar: 'شارلي شابلن', en: 'Charlie Chaplin', yes: 'europe actor comedy bw hollywood born1930 uk director', maybe: 'oscar' },
  { id: 'brucelee',    icon: '🥋', ar: 'بروس لي', en: 'Bruce Lee', yes: 'asia actor action fighter hollywood born1950' },
  { id: 'jackiechan',  icon: '🥋', ar: 'جاكي شان', en: 'Jackie Chan', yes: 'asia actor action fighter hollywood born1970', maybe: 'comedy oscar' },
  /* ---------- singers and musicians ---------- */
  { id: 'umkulthum',   icon: '🎤', ar: 'أم كلثوم', en: 'Umm Kulthum', yes: 'female egypt singer born1930 bw', maybe: 'actor' },
  { id: 'abdelhalim',  icon: '🎤', ar: 'عبد الحليم حافظ', en: 'Abdel Halim Hafez', yes: 'egypt singer actor bw born1930' },
  { id: 'abdelwahab',  icon: '🎼', ar: 'محمد عبد الوهاب', en: 'Mohamed Abdel Wahab', yes: 'egypt singer composer bw born1930', maybe: 'actor' },
  { id: 'fareedatrash', icon: '🎼', ar: 'فريد الأطرش', en: 'Farid al-Atrash', yes: 'levant singer composer actor bw born1930', maybe: 'egypt' },
  { id: 'sayeddarwish', icon: '🎼', ar: 'سيد درويش', en: 'Sayed Darwish', yes: 'egypt composer singer born1930', no: 'bw actor' },
  { id: 'fairuz',      icon: '🎤', ar: 'فيروز', en: 'Fairuz', yes: 'female levant singer born1950' },
  { id: 'warda',       icon: '🎤', ar: 'وردة الجزائرية', en: 'Warda', yes: 'female maghreb singer born1950', maybe: 'egypt actor' },
  { id: 'amrdiab',     icon: '🎤', ar: 'عمرو دياب', en: 'Amr Diab', yes: 'egypt singer born1970', maybe: 'composer' },
  { id: 'mounir',      icon: '🎤', ar: 'محمد منير', en: 'Mohamed Mounir', yes: 'south singer born1970', maybe: 'actor' },
  { id: 'tamer',       icon: '🎤', ar: 'تامر حسني', en: 'Tamer Hosny', yes: 'egypt singer actor', maybe: 'composer comedy' },
  { id: 'sherine',     icon: '🎤', ar: 'شيرين عبد الوهاب', en: 'Sherine', yes: 'female egypt singer' },
  { id: 'nancy',       icon: '🎤', ar: 'نانسي عجرم', en: 'Nancy Ajram', yes: 'female levant singer' },
  { id: 'kazem',       icon: '🎤', ar: 'كاظم الساهر', en: 'Kadim Al Sahir', yes: 'gulf singer composer born1970' },
  { id: 'mj',          icon: '🕺', ar: 'مايكل جاكسون', en: 'Michael Jackson', yes: 'usa singer born1970' },
  { id: 'mozart',      icon: '🎹', ar: 'موتسارت', en: 'Mozart', yes: 'europe composer before1800' },
  /* ---------- history ---------- */
  { id: 'ramses',      icon: '👑', ar: 'رمسيس التاني', en: 'Ramesses II', yes: 'egypt pharaoh ruler warrior built' },
  { id: 'tut',         icon: '👑', ar: 'توت عنخ آمون', en: 'Tutankhamun', yes: 'egypt pharaoh ruler', no: 'warrior' },
  { id: 'nefertiti',   icon: '👑', ar: 'نفرتيتي', en: 'Nefertiti', yes: 'female egypt pharaoh ruler' },
  { id: 'cleopatra',   icon: '👑', ar: 'كليوباترا', en: 'Cleopatra', yes: 'female ruler bc', maybe: 'egypt' },
  { id: 'alexander',   icon: '⚔️', ar: 'الإسكندر الأكبر', en: 'Alexander the Great', yes: 'europe bc ruler warrior', maybe: 'built' },
  { id: 'saladin',     icon: '⚔️', ar: 'صلاح الدين الأيوبي', en: 'Saladin', yes: 'before1800 ruler warrior built', maybe: 'arab egypt' },
  { id: 'napoleon',    icon: '⚔️', ar: 'نابليون بونابرت', en: 'Napoleon', yes: 'europe before1800 ruler warrior france' },
  { id: 'mutanabbi',   icon: '📜', ar: 'المتنبي', en: 'Al-Mutanabbi', yes: 'gulf poet before1800' },
  { id: 'ibnsina',     icon: '⚕️', ar: 'ابن سينا', en: 'Avicenna', yes: 'before1800 science medic', maybe: 'writer arab' },
  { id: 'khwarizmi',   icon: '🧮', ar: 'الخوارزمي', en: 'Al-Khwarizmi', yes: 'before1800 science', maybe: 'arab' },
  { id: 'ibnbattuta',  icon: '🧭', ar: 'ابن بطوطة', en: 'Ibn Battuta', yes: 'maghreb before1800 explorer', maybe: 'writer' },
  { id: 'davinci',     icon: '🎨', ar: 'ليوناردو دافنشي', en: 'Leonardo da Vinci', yes: 'europe painter science before1800' },
  { id: 'shakespeare', icon: '✍️', ar: 'شكسبير', en: 'Shakespeare', yes: 'europe writer poet before1800 uk' },
  { id: 'newton',      icon: '🍎', ar: 'إسحاق نيوتن', en: 'Isaac Newton', yes: 'europe science before1800 uk' },
  /* ---------- science, letters, the arts ---------- */
  { id: 'zewail',      icon: '🔬', ar: 'أحمد زويل', en: 'Ahmed Zewail', yes: 'egypt science nobel born1950', maybe: 'usa' },
  { id: 'mahfouz',     icon: '✍️', ar: 'نجيب محفوظ', en: 'Naguib Mahfouz', yes: 'egypt writer nobel born1930' },
  { id: 'tahahussein', icon: '✍️', ar: 'طه حسين', en: 'Taha Hussein', yes: 'egypt writer blind born1930' },
  { id: 'shawqi',      icon: '📜', ar: 'أحمد شوقي', en: 'Ahmed Shawqi', yes: 'egypt poet born1930' },
  { id: 'magdiyacoub', icon: '🫀', ar: 'مجدي يعقوب', en: 'Magdi Yacoub', yes: 'egypt medic born1950', maybe: 'science' },
  { id: 'einstein',    icon: '🧠', ar: 'أينشتاين', en: 'Albert Einstein', yes: 'europe science nobel born1930', maybe: 'usa' },
  { id: 'curie',       icon: '⚛️', ar: 'ماري كوري', en: 'Marie Curie', yes: 'female europe science nobel born1930', maybe: 'france' },
  { id: 'edison',      icon: '💡', ar: 'توماس إديسون', en: 'Thomas Edison', yes: 'usa science born1930' },
  { id: 'armstrong',   icon: '🚀', ar: 'نيل أرمسترونج', en: 'Neil Armstrong', yes: 'usa explorer born1950' },
  { id: 'picasso',     icon: '🎨', ar: 'بيكاسو', en: 'Pablo Picasso', yes: 'europe painter born1930' },
  /* ==================== the second batch (9 Oct 2026) ==================== */
  /* ---------- Egyptian actresses ---------- */
  { id: 'marymounib',  icon: '😂', ar: 'ماري منيب', en: 'Mary Mounib', yes: 'female egypt actor comedy bw theater born1930' },
  { id: 'zeinatsedky', icon: '😂', ar: 'زينات صدقي', en: 'Zeinat Sedki', yes: 'female egypt actor comedy bw born1930' },
  { id: 'aminarizk',   icon: '🎭', ar: 'أمينة رزق', en: 'Amina Rizk', yes: 'female egypt actor bw theater born1930', maybe: 'series' },
  { id: 'hindrostom',  icon: '🎬', ar: 'هند رستم', en: 'Hind Rostom', yes: 'female egypt actor bw born1930' },
  { id: 'sanaagamil',  icon: '🎭', ar: 'سناء جميل', en: 'Sanaa Gamil', yes: 'female egypt actor bw theater born1950', maybe: 'series' },
  { id: 'nadiagendy',  icon: '🎬', ar: 'نادية الجندي', en: 'Nadia El Gendy', yes: 'female egypt actor action born1950', maybe: 'bw' },
  { id: 'nelly',       icon: '💃', ar: 'نيللي', en: 'Nelly', yes: 'female egypt actor fawazeer born1950', maybe: 'singer bw' },
  { id: 'soheirbabli', icon: '🎭', ar: 'سهير البابلي', en: 'Soheir El Babli', yes: 'female egypt actor comedy theater born1950', maybe: 'series bw' },
  { id: 'ablakamel',   icon: '😄', ar: 'عبلة كامل', en: 'Abla Kamel', yes: 'female egypt actor comedy born1970', maybe: 'series' },
  { id: 'karimamokhtar', icon: '📺', ar: 'كريمة مختار', en: 'Karima Mokhtar', yes: 'female egypt actor series born1950', maybe: 'bw' },
  { id: 'isaadyounis', icon: '📺', ar: 'إسعاد يونس', en: 'Isaad Younis', yes: 'female egypt actor comedy tvhost born1970', maybe: 'writer' },
  { id: 'monazaki',    icon: '🎬', ar: 'منى زكي', en: 'Mona Zaki', yes: 'female egypt actor' },
  { id: 'yasminabdelaziz', icon: '😄', ar: 'ياسمين عبد العزيز', en: 'Yasmin Abdulaziz', yes: 'female egypt actor comedy', maybe: 'series' },
  { id: 'doniasamir',  icon: '😄', ar: 'دنيا سمير غانم', en: 'Donia Samir Ghanem', yes: 'female egypt actor comedy singer', maybe: 'series' },
  { id: 'nellykarim',  icon: '🎬', ar: 'نيللي كريم', en: 'Nelly Karim', yes: 'female egypt actor series' },
  { id: 'somaya',      icon: '🎤', ar: 'سمية الخشاب', en: 'Somaya El Khashab', yes: 'female egypt singer actor', maybe: 'series' },
  { id: 'hendsabry',   icon: '🎬', ar: 'هند صبري', en: 'Hend Sabry', yes: 'female maghreb actor', maybe: 'series' },
  /* ---------- Egyptian actors ---------- */
  { id: 'rushdyabaza', icon: '🎬', ar: 'رشدي أباظة', en: 'Rushdy Abaza', yes: 'egypt actor bw born1930' },
  { id: 'meligy',      icon: '😈', ar: 'محمود المليجي', en: 'Mahmoud El-Meligy', yes: 'egypt actor bw villainroles born1930' },
  { id: 'stephanrosti', icon: '😈', ar: 'استيفان روستي', en: 'Stephan Rosti', yes: 'egypt actor bw villainroles comedy born1930', maybe: 'director' },
  { id: 'youssefwahbi', icon: '🎭', ar: 'يوسف وهبي', en: 'Youssef Wahbi', yes: 'egypt actor theater bw director born1930' },
  { id: 'madbouly',    icon: '🎭', ar: 'عبد المنعم مدبولي', en: 'Abdel Moneim Madbouly', yes: 'egypt actor comedy theater bw series born1930', maybe: 'director' },
  { id: 'samirghanem', icon: '😂', ar: 'سمير غانم', en: 'Samir Ghanem', yes: 'egypt actor comedy theater fawazeer born1950', maybe: 'bw series' },
  { id: 'mohamedsobhi', icon: '🎭', ar: 'محمد صبحي', en: 'Mohamed Sobhy', yes: 'egypt actor comedy theater series director born1950' },
  { id: 'noursherif',  icon: '🎬', ar: 'نور الشريف', en: 'Nour El-Sherif', yes: 'egypt actor series born1950', maybe: 'bw' },
  { id: 'khalednabawy', icon: '🎬', ar: 'خالد النبوي', en: 'Khaled El Nabawy', yes: 'egypt actor hollywood born1970' },
  { id: 'karimabdelaziz', icon: '🎬', ar: 'كريم عبد العزيز', en: 'Karim Abdel Aziz', yes: 'egypt actor comedy action' },
  { id: 'mekky',       icon: '😄', ar: 'أحمد مكي', en: 'Ahmed Mekky', yes: 'egypt actor comedy singer series', maybe: 'director' },
  { id: 'mohamedramadan', icon: '🎬', ar: 'محمد رمضان', en: 'Mohamed Ramadan', yes: 'egypt actor action series singer' },
  { id: 'amirkarara',  icon: '🎬', ar: 'أمير كرارة', en: 'Amir Karara', yes: 'egypt actor action series' },
  { id: 'chahine',     icon: '🎥', ar: 'يوسف شاهين', en: 'Youssef Chahine', yes: 'egypt director born1930', maybe: 'actor bw' },
  /* ---------- Arab actors ---------- */
  { id: 'duraidlahham', icon: '😂', ar: 'دريد لحام', en: 'Duraid Lahham', yes: 'levant actor comedy series theater born1950' },
  { id: 'abdelhussein', icon: '😂', ar: 'عبد الحسين عبد الرضا', en: 'Abdulhussain Abdulredha', yes: 'gulf actor comedy theater series born1950' },
  { id: 'nasserqasabi', icon: '😂', ar: 'ناصر القصبي', en: 'Nasser Al Qasabi', yes: 'gulf actor comedy series born1970' },
  { id: 'hayatfahad',  icon: '🎭', ar: 'حياة الفهد', en: 'Hayat Al-Fahad', yes: 'female gulf actor series born1950' },
  { id: 'ghassanmassoud', icon: '🎬', ar: 'غسان مسعود', en: 'Ghassan Massoud', yes: 'levant actor hollywood series born1970' },
  /* ---------- world film ---------- */
  { id: 'ramimalek',   icon: '🎬', ar: 'رامي مالك', en: 'Rami Malek', yes: 'usa actor hollywood oscar series', maybe: 'egypt' },
  { id: 'tomhanks',    icon: '🎬', ar: 'توم هانكس', en: 'Tom Hanks', yes: 'usa actor hollywood oscar born1970' },
  { id: 'tomcruise',   icon: '🎬', ar: 'توم كروز', en: 'Tom Cruise', yes: 'usa actor hollywood action born1970' },
  { id: 'dicaprio',    icon: '🎬', ar: 'ليوناردو دي كابريو', en: 'Leonardo DiCaprio', yes: 'usa actor hollywood oscar' },
  { id: 'stallone',    icon: '🥊', ar: 'سيلفستر ستالون', en: 'Sylvester Stallone', yes: 'usa actor hollywood action born1950', maybe: 'director' },
  { id: 'jimcarrey',   icon: '😂', ar: 'جيم كاري', en: 'Jim Carrey', yes: 'actor hollywood comedy born1970', maybe: 'usa' },
  { id: 'robinwilliams', icon: '😂', ar: 'روبن ويليامز', en: 'Robin Williams', yes: 'usa actor hollywood comedy oscar born1970' },
  { id: 'morganfreeman', icon: '🎬', ar: 'مورجان فريمان', en: 'Morgan Freeman', yes: 'usa actor hollywood oscar born1950' },
  { id: 'clinteastwood', icon: '🤠', ar: 'كلينت إيستوود', en: 'Clint Eastwood', yes: 'usa actor hollywood director oscar born1950', maybe: 'action' },
  { id: 'merylstreep', icon: '🎬', ar: 'ميريل ستريب', en: 'Meryl Streep', yes: 'female usa actor hollywood oscar born1950' },
  { id: 'juliaroberts', icon: '🎬', ar: 'جوليا روبرتس', en: 'Julia Roberts', yes: 'female usa actor hollywood oscar born1970' },
  { id: 'angelinajolie', icon: '🎬', ar: 'أنجلينا جولي', en: 'Angelina Jolie', yes: 'female usa actor hollywood oscar action' },
  { id: 'audreyhepburn', icon: '🎬', ar: 'أودري هيبورن', en: 'Audrey Hepburn', yes: 'female europe actor hollywood oscar bw born1930', maybe: 'uk' },
  { id: 'therock',     icon: '💪', ar: 'ذا روك (دواين جونسون)', en: 'The Rock (Dwayne Johnson)', yes: 'usa actor hollywood action fighter' },
  { id: 'vandamme',    icon: '🥋', ar: 'جان كلود فان دام', en: 'Jean-Claude Van Damme', yes: 'europe actor hollywood action fighter born1970' },
  { id: 'statham',     icon: '🎬', ar: 'جيسون ستاثام', en: 'Jason Statham', yes: 'uk actor hollywood action born1970' },
  { id: 'anthonyhopkins', icon: '🎬', ar: 'أنتوني هوبكنز', en: 'Anthony Hopkins', yes: 'uk actor hollywood oscar born1950' },
  { id: 'seanconnery', icon: '🕴️', ar: 'شون كونري', en: 'Sean Connery', yes: 'uk actor hollywood action oscar born1950' },
  { id: 'emmawatson',  icon: '🎬', ar: 'إيما واتسون', en: 'Emma Watson', yes: 'female uk actor hollywood' },
  { id: 'katewinslet', icon: '🎬', ar: 'كيت وينسلت', en: 'Kate Winslet', yes: 'female uk actor hollywood oscar' },
  { id: 'radcliffe',   icon: '🎬', ar: 'دانيال رادكليف', en: 'Daniel Radcliffe', yes: 'uk actor hollywood' },
  { id: 'defunes',     icon: '😂', ar: 'لوي دي فونيس', en: 'Louis de Funès', yes: 'france actor comedy born1930', maybe: 'bw' },
  { id: 'amitabh',     icon: '🎬', ar: 'أميتاب باتشان', en: 'Amitabh Bachchan', yes: 'actor tvhost born1950', maybe: 'action singer' },
  { id: 'spielberg',   icon: '🎥', ar: 'ستيفن سبيلبرج', en: 'Steven Spielberg', yes: 'usa director oscar born1950' },
  { id: 'hitchcock',   icon: '🎥', ar: 'ألفريد هيتشكوك', en: 'Alfred Hitchcock', yes: 'uk director born1930' },
  { id: 'miyazaki',    icon: '🎥', ar: 'هاياو ميازاكي', en: 'Hayao Miyazaki', yes: 'asia director oscar born1950', maybe: 'painter' },
  { id: 'waltdisney',  icon: '🐭', ar: 'والت ديزني', en: 'Walt Disney', yes: 'usa oscar born1930', maybe: 'director painter' },
  /* ---------- Egyptian and Arab singers and composers ---------- */
  { id: 'mohamedfouad', icon: '🎤', ar: 'محمد فؤاد', en: 'Mohamed Fouad', yes: 'egypt singer actor born1970' },
  { id: 'hamaki',      icon: '🎤', ar: 'محمد حماقي', en: 'Mohamed Hamaki', yes: 'egypt singer' },
  { id: 'adaweya',     icon: '🎤', ar: 'أحمد عدوية', en: 'Ahmed Adaweya', yes: 'egypt singer born1950', maybe: 'actor' },
  { id: 'najat',       icon: '🎤', ar: 'نجاة الصغيرة', en: 'Najat Al Saghira', yes: 'female egypt singer born1950' },
  { id: 'abdelmottaleb', icon: '🎤', ar: 'محمد عبد المطلب', en: 'Mohamed Abdel Muttalib', yes: 'egypt singer born1930' },
  { id: 'mounib',      icon: '🎤', ar: 'أحمد منيب', en: 'Ahmed Mounib', yes: 'south singer composer born1930' },
  { id: 'baligh',      icon: '🎼', ar: 'بليغ حمدي', en: 'Baligh Hamdi', yes: 'egypt composer born1950' },
  { id: 'ammarsherei', icon: '🎹', ar: 'عمار الشريعي', en: 'Ammar El Sherei', yes: 'egypt composer blind born1950', maybe: 'tvhost' },
  { id: 'mekkawy',     icon: '🎼', ar: 'سيد مكاوي', en: 'Sayed Mekkawy', yes: 'egypt composer singer blind born1930' },
  { id: 'latifa',      icon: '🎤', ar: 'لطيفة', en: 'Latifa', yes: 'female maghreb singer born1970' },
  { id: 'chebkhaled',  icon: '🎤', ar: 'الشاب خالد', en: 'Cheb Khaled', yes: 'maghreb singer born1970' },
  { id: 'mohammedabdu', icon: '🎤', ar: 'محمد عبده', en: 'Mohammed Abdu', yes: 'gulf singer born1950', maybe: 'composer' },
  { id: 'jassmi',      icon: '🎤', ar: 'حسين الجسمي', en: 'Hussain Al Jassmi', yes: 'gulf singer' },
  { id: 'ahlam',       icon: '🎤', ar: 'أحلام', en: 'Ahlam', yes: 'female gulf singer born1970' },
  { id: 'assala',      icon: '🎤', ar: 'أصالة', en: 'Assala', yes: 'female levant singer born1970' },
  { id: 'sabah',       icon: '🎤', ar: 'صباح', en: 'Sabah', yes: 'female levant singer actor bw born1930' },
  { id: 'wadihsafi',   icon: '🎤', ar: 'وديع الصافي', en: 'Wadih El Safi', yes: 'levant singer born1930', maybe: 'composer' },
  { id: 'sabahfakhri', icon: '🎤', ar: 'صباح فخري', en: 'Sabah Fakhri', yes: 'levant singer born1950' },
  { id: 'ragheb',      icon: '🎤', ar: 'راغب علامة', en: 'Ragheb Alama', yes: 'levant singer born1970' },
  { id: 'mohammedassaf', icon: '🎤', ar: 'محمد عساف', en: 'Mohammed Assaf', yes: 'levant singer' },
  /* ---------- world music ---------- */
  { id: 'dalida',      icon: '🎤', ar: 'داليدا', en: 'Dalida', yes: 'female france singer born1950', maybe: 'egypt actor' },
  { id: 'piaf',        icon: '🎤', ar: 'إديث بياف', en: 'Edith Piaf', yes: 'female france singer born1930' },
  { id: 'elvis',       icon: '🎸', ar: 'إلفيس بريسلي', en: 'Elvis Presley', yes: 'usa singer actor hollywood born1950' },
  { id: 'whitney',     icon: '🎤', ar: 'ويتني هيوستن', en: 'Whitney Houston', yes: 'female usa singer actor hollywood born1970' },
  { id: 'taylorswift', icon: '🎤', ar: 'تايلور سويفت', en: 'Taylor Swift', yes: 'female usa singer', maybe: 'composer' },
  { id: 'shakira',     icon: '💃', ar: 'شاكيرا', en: 'Shakira', yes: 'female latam singer' },
  { id: 'adele',       icon: '🎤', ar: 'أديل', en: 'Adele', yes: 'female uk singer oscar' },
  { id: 'edsheeran',   icon: '🎸', ar: 'إد شيران', en: 'Ed Sheeran', yes: 'uk singer', maybe: 'composer' },
  { id: 'enrique',     icon: '🎤', ar: 'إنريكي إجليسياس', en: 'Enrique Iglesias', yes: 'europe singer' },
  { id: 'pavarotti',   icon: '🎶', ar: 'بافاروتي', en: 'Luciano Pavarotti', yes: 'europe singer born1950' },
  { id: 'tchaikovsky', icon: '🎼', ar: 'تشايكوفسكي', en: 'Tchaikovsky', yes: 'europe composer born1930' },
  { id: 'yanni',       icon: '🎹', ar: 'ياني', en: 'Yanni', yes: 'europe composer born1970' },
  /* ---------- Egyptian football ---------- */
  { id: 'trezeguet',   icon: '⚽', ar: 'محمود تريزيجيه', en: 'Mahmoud Trézéguet', yes: 'egypt ahly england', maybe: 'striker', no: 'zamalek afcon' },
  { id: 'hegazi',      icon: '⚽', ar: 'أحمد حجازي', en: 'Ahmed Hegazi', yes: 'egypt ahly england italy defender', no: 'zamalek afcon' },
  { id: 'amrzaki',     icon: '⚽', ar: 'عمرو زكي', en: 'Amr Zaki', yes: 'egypt zamalek england striker afcon', no: 'ahly' },
  { id: 'moteab',      icon: '⚽', ar: 'عماد متعب', en: 'Emad Moteab', yes: 'egypt ahly striker afcon', no: 'zamalek england' },
  { id: 'waelgomaa',   icon: '⚽', ar: 'وائل جمعة', en: 'Wael Gomaa', yes: 'egypt ahly defender afcon', no: 'zamalek' },
  { id: 'ahmedfathy',  icon: '⚽', ar: 'أحمد فتحي', en: 'Ahmed Fathy', yes: 'egypt ahly england defender afcon', no: 'zamalek' },
  { id: 'elmohamady',  icon: '⚽', ar: 'أحمد المحمدي', en: 'Ahmed Elmohamady', yes: 'egypt england defender afcon', no: 'ahly zamalek' },
  { id: 'ibrahimhassan', icon: '⚽', ar: 'إبراهيم حسن', en: 'Ibrahim Hassan', yes: 'egypt ahly zamalek defender afcon born1970' },
  { id: 'gabaski',     icon: '🧤', ar: 'محمد أبو جبل (جباسكي)', en: 'Mohamed Abou Gabal (Gabaski)', yes: 'egypt zamalek keeper', no: 'ahly afcon' },
  { id: 'shobeir',     icon: '🧤', ar: 'أحمد شوبير', en: 'Ahmed Shobeir', yes: 'egypt ahly keeper tvhost born1970', no: 'zamalek' },
  { id: 'mostafamohamed', icon: '⚽', ar: 'مصطفى محمد', en: 'Mostafa Mohamed', yes: 'egypt zamalek striker', no: 'ahly afcon' },
  { id: 'marmoush',    icon: '⚽', ar: 'عمر مرموش', en: 'Omar Marmoush', yes: 'egypt england striker', no: 'ahly zamalek afcon' },
  { id: 'mido',        icon: '⚽', ar: 'ميدو (أحمد حسام)', en: 'Mido (Ahmed Hossam)', yes: 'egypt zamalek england spain italy striker afcon coach', no: 'ahly' },
  { id: 'hazememam',   icon: '⚽', ar: 'حازم إمام', en: 'Hazem Emam', yes: 'egypt zamalek italy', maybe: 'afcon', no: 'ahly' },
  { id: 'magdiabdelghani', icon: '⚽', ar: 'مجدي عبد الغني', en: 'Magdi Abdelghani', yes: 'egypt ahly born1970', maybe: 'afcon', no: 'zamalek' },
  { id: 'faroukgaafar', icon: '⚽', ar: 'فاروق جعفر', en: 'Farouk Gaafar', yes: 'egypt zamalek coach born1970', no: 'ahly' },
  { id: 'salehselim',  icon: '⚽', ar: 'صالح سليم', en: 'Saleh Selim', yes: 'egypt ahly actor bw born1950', no: 'zamalek' },
  { id: 'hassanshehata', icon: '📋', ar: 'حسن شحاتة', en: 'Hassan Shehata', yes: 'egypt zamalek coach afcon born1950', no: 'ahly' },
  { id: 'gohary',      icon: '📋', ar: 'محمود الجوهري', en: 'Mahmoud El-Gohary', yes: 'egypt ahly coach afcon born1950' },
  { id: 'manueljose',  icon: '📋', ar: 'مانويل جوزيه', en: 'Manuel José', yes: 'europe coach born1950', no: 'ahly' },
  /* ---------- Arab and African football ---------- */
  { id: 'ziyech',      icon: '⚽', ar: 'حكيم زياش', en: 'Hakim Ziyech', yes: 'maghreb england', no: 'afcon' },
  { id: 'bounou',      icon: '🧤', ar: 'ياسين بونو', en: 'Yassine Bounou', yes: 'maghreb spain keeper', no: 'afcon' },
  { id: 'benatia',     icon: '⚽', ar: 'المهدي بن عطية', en: 'Medhi Benatia', yes: 'maghreb italy defender' },
  { id: 'ennesyri',    icon: '⚽', ar: 'يوسف النصيري', en: 'Youssef En-Nesyri', yes: 'maghreb spain striker' },
  { id: 'madjer',      icon: '⚽', ar: 'رابح ماجر', en: 'Rabah Madjer', yes: 'maghreb afcon coach born1970', maybe: 'striker' },
  { id: 'maaloul',     icon: '⚽', ar: 'علي معلول', en: 'Ali Maaloul', yes: 'maghreb ahly defender' },
  { id: 'samijaber',   icon: '⚽', ar: 'سامي الجابر', en: 'Sami Al-Jaber', yes: 'gulf striker' },
  { id: 'majedabdullah', icon: '⚽', ar: 'ماجد عبد الله', en: 'Majed Abdullah', yes: 'gulf striker born1970' },
  { id: 'deayea',      icon: '🧤', ar: 'محمد الدعيع', en: 'Mohamed Al-Deayea', yes: 'gulf keeper' },
  { id: 'drogba',      icon: '⚽', ar: 'ديدييه دروجبا', en: 'Didier Drogba', yes: 'africa england striker', no: 'afcon worldcup' },
  { id: 'etoo',        icon: '⚽', ar: 'صامويل إيتو', en: "Samuel Eto'o", yes: 'africa spain italy england striker afcon olympic' },
  { id: 'percytau',    icon: '⚽', ar: 'بيرسي تاو', en: 'Percy Tau', yes: 'africa ahly england' },
  /* ---------- world football ---------- */
  { id: 'benzema',     icon: '⚽', ar: 'كريم بنزيما', en: 'Karim Benzema', yes: 'france spain striker ballon', no: 'worldcup' },
  { id: 'mbappe',      icon: '⚽', ar: 'كيليان مبابي', en: 'Kylian Mbappé', yes: 'france spain striker worldcup' },
  { id: 'henry',       icon: '⚽', ar: 'تيري هنري', en: 'Thierry Henry', yes: 'france england spain italy striker worldcup coach' },
  { id: 'ronaldinho',  icon: '⚽', ar: 'رونالدينيو', en: 'Ronaldinho', yes: 'latam spain italy worldcup ballon olympic' },
  { id: 'ronaldonazario', icon: '⚽', ar: 'رونالدو البرازيلي', en: 'Ronaldo Nazário', yes: 'latam spain italy worldcup ballon striker olympic' },
  { id: 'neymar',      icon: '⚽', ar: 'نيمار', en: 'Neymar', yes: 'latam spain striker olympic', no: 'worldcup' },
  { id: 'robertocarlos', icon: '⚽', ar: 'روبرتو كارلوس', en: 'Roberto Carlos', yes: 'latam spain italy defender worldcup' },
  { id: 'dimaria',     icon: '⚽', ar: 'أنخيل دي ماريا', en: 'Ángel Di María', yes: 'latam spain england italy worldcup olympic' },
  { id: 'suarez',      icon: '⚽', ar: 'لويس سواريز', en: 'Luis Suárez', yes: 'latam spain england striker', no: 'worldcup' },
  { id: 'distefano',   icon: '⚽', ar: 'ألفريدو دي ستيفانو', en: 'Alfredo Di Stéfano', yes: 'latam spain striker ballon coach born1930' },
  { id: 'beckham',     icon: '⚽', ar: 'ديفيد بيكهام', en: 'David Beckham', yes: 'uk england spain italy', no: 'worldcup' },
  { id: 'rooney',      icon: '⚽', ar: 'واين روني', en: 'Wayne Rooney', yes: 'uk england striker coach', no: 'worldcup' },
  { id: 'gerrard',     icon: '⚽', ar: 'ستيفن جيرارد', en: 'Steven Gerrard', yes: 'uk england coach', no: 'worldcup' },
  { id: 'buffon',      icon: '🧤', ar: 'جيانلويجي بوفون', en: 'Gianluigi Buffon', yes: 'europe italy keeper worldcup' },
  { id: 'maldini',     icon: '⚽', ar: 'باولو مالديني', en: 'Paolo Maldini', yes: 'europe italy defender born1970', no: 'worldcup' },
  { id: 'totti',       icon: '⚽', ar: 'فرانشيسكو توتي', en: 'Francesco Totti', yes: 'europe italy worldcup', maybe: 'striker' },
  { id: 'ramos',       icon: '⚽', ar: 'سيرجيو راموس', en: 'Sergio Ramos', yes: 'europe spain defender worldcup' },
  { id: 'iniesta',     icon: '⚽', ar: 'أندريس إنييستا', en: 'Andrés Iniesta', yes: 'europe spain worldcup' },
  { id: 'casillas',    icon: '🧤', ar: 'إيكر كاسياس', en: 'Iker Casillas', yes: 'europe spain keeper worldcup' },
  { id: 'modric',      icon: '⚽', ar: 'لوكا مودريتش', en: 'Luka Modrić', yes: 'europe spain england ballon', maybe: 'italy', no: 'worldcup' },
  { id: 'lewandowski', icon: '⚽', ar: 'روبرت ليفاندوفسكي', en: 'Robert Lewandowski', yes: 'europe spain striker', no: 'worldcup' },
  { id: 'haaland',     icon: '⚽', ar: 'إرلينج هالاند', en: 'Erling Haaland', yes: 'europe england striker' },
  { id: 'vandijk',     icon: '⚽', ar: 'فيرجيل فان دايك', en: 'Virgil van Dijk', yes: 'europe england defender' },
  { id: 'debruyne',    icon: '⚽', ar: 'كيفن دي بروين', en: 'Kevin De Bruyne', yes: 'europe england', maybe: 'italy' },
  { id: 'zlatan',      icon: '⚽', ar: 'زلاتان إبراهيموفيتش', en: 'Zlatan Ibrahimović', yes: 'europe spain italy england striker', no: 'worldcup' },
  { id: 'son',         icon: '⚽', ar: 'سون هيونج مين', en: 'Son Heung-min', yes: 'asia england striker' },
  { id: 'cruyff',      icon: '⚽', ar: 'يوهان كرويف', en: 'Johan Cruyff', yes: 'europe spain ballon coach born1950', no: 'worldcup' },
  { id: 'beckenbauer', icon: '⚽', ar: 'فرانز بيكنباور', en: 'Franz Beckenbauer', yes: 'europe worldcup ballon coach defender born1950' },
  { id: 'yashin',      icon: '🧤', ar: 'ليف ياشين', en: 'Lev Yashin', yes: 'europe keeper ballon born1930' },
  { id: 'eusebio',     icon: '⚽', ar: 'أوزيبيو', en: 'Eusébio', yes: 'europe striker ballon born1950', maybe: 'africa' },
  { id: 'puskas',      icon: '⚽', ar: 'فيرينتس بوشكاش', en: 'Ferenc Puskás', yes: 'europe spain striker coach born1930' },
  { id: 'guardiola',   icon: '📋', ar: 'بيب جوارديولا', en: 'Pep Guardiola', yes: 'europe spain italy coach' },
  { id: 'ferguson',    icon: '📋', ar: 'أليكس فيرجسون', en: 'Alex Ferguson', yes: 'uk coach born1950' },
  /* ---------- other sports ---------- */
  { id: 'alifarag',    icon: '🏆', ar: 'علي فرج', en: 'Ali Farag', yes: 'egypt squash' },
  { id: 'noursherbini', icon: '🏆', ar: 'نور الشربيني', en: 'Nour El Sherbini', yes: 'female egypt squash' },
  { id: 'mayarsherif', icon: '🎾', ar: 'ميار شريف', en: 'Mayar Sherif', yes: 'female egypt tennis' },
  { id: 'onsjabeur',   icon: '🎾', ar: 'أنس جابر', en: 'Ons Jabeur', yes: 'female maghreb tennis' },
  { id: 'elahmar',     icon: '🤾', ar: 'أحمد الأحمر', en: 'Ahmed El-Ahmar', yes: 'egypt othersport' },
  { id: 'nahlaramadan', icon: '🏋️', ar: 'نهلة رمضان', en: 'Nahla Ramadan', yes: 'female egypt lifter' },
  { id: 'abeerabdelrahman', icon: '🏋️', ar: 'عبير عبد الرحمن', en: 'Abeer Abdel Rahman', yes: 'female egypt lifter olympic' },
  { id: 'mohamedehab', icon: '🏋️', ar: 'محمد إيهاب', en: 'Mohamed Ehab', yes: 'egypt lifter olympic' },
  { id: 'hedayamalak', icon: '🥋', ar: 'هداية ملاك', en: 'Hedaya Malak', yes: 'female egypt othersport fighter olympic' },
  { id: 'rashwan',     icon: '🥋', ar: 'محمد رشوان', en: 'Mohamed Rashwan', yes: 'egypt othersport fighter olympic born1970' },
  { id: 'faridaosman', icon: '🏊', ar: 'فريدة عثمان', en: 'Farida Osman', yes: 'female egypt swimmer' },
  { id: 'abouheif',    icon: '🏊', ar: 'عبد اللطيف أبو هيف', en: 'Abdel Latif Abou Heif', yes: 'egypt swimmer born1930' },
  { id: 'elgendy',     icon: '🏅', ar: 'أحمد الجندي', en: 'Ahmed Elgendy', yes: 'egypt othersport olympic' },
  { id: 'guerrouj',    icon: '🏃', ar: 'هشام الكروج', en: 'Hicham El Guerrouj', yes: 'maghreb runner olympic' },
  { id: 'aouita',      icon: '🏃', ar: 'سعيد عويطة', en: 'Said Aouita', yes: 'maghreb runner olympic born1970' },
  { id: 'barshim',     icon: '🏃', ar: 'معتز برشم', en: 'Mutaz Barshim', yes: 'gulf runner olympic' },
  { id: 'federer',     icon: '🎾', ar: 'روجر فيدرر', en: 'Roger Federer', yes: 'europe tennis olympic' },
  { id: 'serena',      icon: '🎾', ar: 'سيرينا ويليامز', en: 'Serena Williams', yes: 'female usa tennis olympic' },
  { id: 'phelps',      icon: '🏊', ar: 'مايكل فيلبس', en: 'Michael Phelps', yes: 'usa swimmer olympic' },
  { id: 'carllewis',   icon: '🏃', ar: 'كارل لويس', en: 'Carl Lewis', yes: 'usa runner olympic born1970' },
  { id: 'mofarah',     icon: '🏃', ar: 'مو فرح', en: 'Mo Farah', yes: 'uk runner olympic', maybe: 'africa' },
  { id: 'kipchoge',    icon: '🏃', ar: 'إليود كيبتشوجي', en: 'Eliud Kipchoge', yes: 'africa runner olympic' },
  { id: 'kobe',        icon: '🏀', ar: 'كوبي براينت', en: 'Kobe Bryant', yes: 'usa basket olympic', maybe: 'oscar' },
  { id: 'yaoming',     icon: '🏀', ar: 'ياو مينج', en: 'Yao Ming', yes: 'asia basket' },
  { id: 'comaneci',    icon: '🤸', ar: 'نادية كومانتشي', en: 'Nadia Comăneci', yes: 'female europe othersport olympic born1970' },
  { id: 'biles',       icon: '🤸', ar: 'سيمون بايلز', en: 'Simone Biles', yes: 'female usa othersport olympic' },
  { id: 'schumacher',  icon: '🏎️', ar: 'مايكل شوماخر', en: 'Michael Schumacher', yes: 'europe othersport born1970' },
  { id: 'senna',       icon: '🏎️', ar: 'أيرتون سينا', en: 'Ayrton Senna', yes: 'latam othersport born1970' },
  { id: 'hamilton',    icon: '🏎️', ar: 'لويس هاميلتون', en: 'Lewis Hamilton', yes: 'uk othersport' },
  /* ---------- writers and poets ---------- */
  { id: 'tawfikhakim', icon: '✍️', ar: 'توفيق الحكيم', en: 'Tawfiq al-Hakim', yes: 'egypt writer born1930', maybe: 'theater' },
  { id: 'youssefidris', icon: '✍️', ar: 'يوسف إدريس', en: 'Yusuf Idris', yes: 'egypt writer medic born1930' },
  { id: 'mostafamahmoud', icon: '🔭', ar: 'مصطفى محمود', en: 'Mostafa Mahmoud', yes: 'egypt writer medic tvhost born1930' },
  { id: 'ahmedkhaledtawfik', icon: '📚', ar: 'أحمد خالد توفيق', en: 'Ahmed Khaled Tawfik', yes: 'egypt writer medic born1970' },
  { id: 'salahjahin',  icon: '📜', ar: 'صلاح جاهين', en: 'Salah Jahin', yes: 'egypt poet born1950', maybe: 'painter actor' },
  { id: 'abnudi',      icon: '📜', ar: 'عبد الرحمن الأبنودي', en: 'Abdel Rahman el-Abnudi', yes: 'south poet born1950' },
  { id: 'mahmouddarwish', icon: '📜', ar: 'محمود درويش', en: 'Mahmoud Darwish', yes: 'levant poet born1950' },
  { id: 'nizar',       icon: '📜', ar: 'نزار قباني', en: 'Nizar Qabbani', yes: 'levant poet born1930' },
  { id: 'gibran',      icon: '✍️', ar: 'جبران خليل جبران', en: 'Kahlil Gibran', yes: 'levant writer poet painter born1930', maybe: 'usa' },
  { id: 'maiziadeh',   icon: '✍️', ar: 'مي زيادة', en: 'May Ziadeh', yes: 'female levant writer born1930', maybe: 'egypt' },
  { id: 'antara',      icon: '⚔️', ar: 'عنترة بن شداد', en: 'Antarah ibn Shaddad', yes: 'arab poet warrior before1800', maybe: 'gulf' },
  { id: 'khansa',      icon: '📜', ar: 'الخنساء', en: 'Al-Khansa', yes: 'female arab poet before1800', maybe: 'gulf' },
  { id: 'maarri',      icon: '📜', ar: 'أبو العلاء المعري', en: "Al-Ma'arri", yes: 'levant poet blind before1800' },
  { id: 'ibnkhaldun',  icon: '📜', ar: 'ابن خلدون', en: 'Ibn Khaldun', yes: 'maghreb writer before1800', maybe: 'science' },
  { id: 'dickens',     icon: '✍️', ar: 'تشارلز ديكنز', en: 'Charles Dickens', yes: 'uk writer born1930' },
  { id: 'agatha',      icon: '🔍', ar: 'أجاثا كريستي', en: 'Agatha Christie', yes: 'female uk writer born1930' },
  { id: 'victorhugo',  icon: '✍️', ar: 'فيكتور هوجو', en: 'Victor Hugo', yes: 'france writer poet born1930' },
  { id: 'verne',       icon: '✍️', ar: 'جول فيرن', en: 'Jules Verne', yes: 'france writer born1930' },
  { id: 'tolstoy',     icon: '✍️', ar: 'تولستوي', en: 'Leo Tolstoy', yes: 'europe writer born1930' },
  { id: 'twain',       icon: '✍️', ar: 'مارك توين', en: 'Mark Twain', yes: 'usa writer born1930' },
  { id: 'hemingway',   icon: '✍️', ar: 'إرنست همنجواي', en: 'Ernest Hemingway', yes: 'usa writer nobel born1930' },
  { id: 'homer',       icon: '📜', ar: 'هوميروس', en: 'Homer', yes: 'europe poet bc', maybe: 'blind' },
  { id: 'aristotle',   icon: '📜', ar: 'أرسطو', en: 'Aristotle', yes: 'europe writer science bc' },
  { id: 'confucius',   icon: '📜', ar: 'كونفوشيوس', en: 'Confucius', yes: 'asia writer bc' },
  /* ---------- science and invention ---------- */
  { id: 'imhotep',     icon: '🏛️', ar: 'إمحوتب', en: 'Imhotep', yes: 'egypt pharaoh science medic built' },
  { id: 'mosharafa',   icon: '🔬', ar: 'علي مصطفى مشرفة', en: 'Ali Moustafa Mosharafa', yes: 'egypt science born1930' },
  { id: 'sameeramoussa', icon: '⚛️', ar: 'سميرة موسى', en: 'Sameera Moussa', yes: 'female egypt science born1930' },
  { id: 'faroukelbaz', icon: '🚀', ar: 'فاروق الباز', en: 'Farouk El-Baz', yes: 'egypt science born1950', maybe: 'usa explorer' },
  { id: 'hassanfathy', icon: '🏛️', ar: 'حسن فتحي', en: 'Hassan Fathy', yes: 'egypt built born1930' },
  { id: 'zahahadid',   icon: '🏛️', ar: 'زها حديد', en: 'Zaha Hadid', yes: 'female gulf built born1970', maybe: 'uk' },
  { id: 'ibnhaytham',  icon: '🔭', ar: 'ابن الهيثم', en: 'Ibn al-Haytham', yes: 'gulf science before1800', maybe: 'egypt' },
  { id: 'ibnnafis',    icon: '⚕️', ar: 'ابن النفيس', en: 'Ibn al-Nafis', yes: 'levant medic science before1800', maybe: 'egypt' },
  { id: 'archimedes',  icon: '🛁', ar: 'أرشميدس', en: 'Archimedes', yes: 'europe science bc' },
  { id: 'hippocrates', icon: '⚕️', ar: 'أبقراط', en: 'Hippocrates', yes: 'europe medic bc', maybe: 'science writer' },
  { id: 'galileo',     icon: '🔭', ar: 'جاليليو', en: 'Galileo Galilei', yes: 'europe science before1800' },
  { id: 'champollion', icon: '📜', ar: 'شامبليون', en: 'Champollion', yes: 'france science before1800' },
  { id: 'tesla',       icon: '⚡', ar: 'نيكولا تسلا', en: 'Nikola Tesla', yes: 'europe science born1930', maybe: 'usa' },
  { id: 'bell',        icon: '☎️', ar: 'جراهام بيل', en: 'Alexander Graham Bell', yes: 'uk science born1930', maybe: 'usa' },
  { id: 'pasteur',     icon: '🧪', ar: 'لويس باستير', en: 'Louis Pasteur', yes: 'france science born1930', maybe: 'medic' },
  { id: 'fleming',     icon: '🧫', ar: 'ألكسندر فليمنج', en: 'Alexander Fleming', yes: 'uk science medic nobel born1930' },
  { id: 'hawking',     icon: '🌌', ar: 'ستيفن هوكينج', en: 'Stephen Hawking', yes: 'uk science born1950' },
  { id: 'eiffel',      icon: '🗼', ar: 'جوستاف إيفل', en: 'Gustave Eiffel', yes: 'france built born1930', maybe: 'science' },
  /* ---------- history: rulers, leaders, explorers ---------- */
  { id: 'khufu',       icon: '👑', ar: 'خوفو', en: 'Khufu', yes: 'egypt pharaoh ruler built' },
  { id: 'hatshepsut',  icon: '👑', ar: 'حتشبسوت', en: 'Hatshepsut', yes: 'female egypt pharaoh ruler built' },
  { id: 'ahmose',      icon: '⚔️', ar: 'أحمس', en: 'Ahmose I', yes: 'egypt pharaoh ruler warrior' },
  { id: 'qutuz',       icon: '⚔️', ar: 'سيف الدين قطز', en: 'Qutuz', yes: 'ruler warrior before1800', maybe: 'egypt' },
  { id: 'shajar',      icon: '👑', ar: 'شجر الدر', en: 'Shajar al-Durr', yes: 'female ruler before1800', maybe: 'egypt' },
  { id: 'harun',       icon: '👑', ar: 'هارون الرشيد', en: 'Harun al-Rashid', yes: 'gulf ruler before1800' },
  { id: 'muhammadalipasha', icon: '🏰', ar: 'محمد علي باشا', en: 'Muhammad Ali Pasha', yes: 'ruler before1800 built', maybe: 'egypt europe' },
  { id: 'khediveismail', icon: '👑', ar: 'الخديوي إسماعيل', en: 'Khedive Ismail', yes: 'egypt ruler built born1930' },
  { id: 'kingfarouk',  icon: '👑', ar: 'الملك فاروق', en: 'King Farouk', yes: 'egypt ruler born1930' },
  { id: 'orabi',       icon: '⚔️', ar: 'أحمد عرابي', en: 'Ahmed Orabi', yes: 'egypt warrior born1930' },
  { id: 'victoria',    icon: '👑', ar: 'الملكة فيكتوريا', en: 'Queen Victoria', yes: 'female uk ruler born1930' },
  { id: 'genghis',     icon: '⚔️', ar: 'جنكيز خان', en: 'Genghis Khan', yes: 'asia ruler warrior before1800' },
  { id: 'washington',  icon: '⚔️', ar: 'جورج واشنطن', en: 'George Washington', yes: 'usa ruler warrior before1800' },
  { id: 'lincoln',     icon: '🎩', ar: 'أبراهام لينكولن', en: 'Abraham Lincoln', yes: 'usa ruler born1930' },
  { id: 'columbus',    icon: '⛵', ar: 'كريستوفر كولومبوس', en: 'Christopher Columbus', yes: 'europe explorer before1800' },
  { id: 'gagarin',     icon: '🚀', ar: 'يوري جاجارين', en: 'Yuri Gagarin', yes: 'europe explorer born1950' },
  { id: 'cousteau',    icon: '🤿', ar: 'جاك كوستو', en: 'Jacques Cousteau', yes: 'france explorer born1930', maybe: 'science' },
  { id: 'howardcarter', icon: '⛏️', ar: 'هوارد كارتر', en: 'Howard Carter', yes: 'uk explorer born1930', maybe: 'science' },
  /* ---------- painters ---------- */
  { id: 'michelangelo', icon: '🎨', ar: 'مايكل أنجلو', en: 'Michelangelo', yes: 'europe painter before1800', maybe: 'built' },
  { id: 'mahmoudsaid', icon: '🎨', ar: 'محمود سعيد', en: 'Mahmoud Saïd', yes: 'egypt painter born1930' },
]};
