/* العرّاف: places - countries and cities (kind 'l'). One line each, as in the other files (notes/games/oracle.md, "Writing entries");
   check with `cd tools && npm run check:oracle`. Added 10 Oct 2026. The names of the countries are the app's own
   (content/Countries.js). A city carries its country's flag colours (the flag questions say «علم البلد»), its
   continent and its language. */
const ORACLE_PLACES = { kind: 'l', list: [
  /* ---------- the Arab countries ---------- */
  { id: 'l_egypt',      icon: '🇪🇬', ar: 'مصر', en: 'Egypt', yes: 'egypt africa_l med redsea desert_l nile_l canal_l nubia pharaonic history_l cinema afcon_l flag_red flag_white flag_black', maybe: 'huge delta south_l sinai flag_yellow' },
  { id: 'l_sudan',      icon: '🇸🇩', ar: 'السودان', en: 'Sudan', yes: 'arab africa_l redsea desert_l nile_l nubia neighbor_eg afcon_l flag_red flag_white flag_black flag_green', maybe: 'huge pharaonic history_l' },
  { id: 'l_libya',      icon: '🇱🇾', ar: 'ليبيا', en: 'Libya', yes: 'maghreb_l med desert_l neighbor_eg flag_red flag_black flag_green flag_white flag_star', maybe: 'huge history_l' },
  { id: 'l_tunisia',    icon: '🇹🇳', ar: 'تونس', en: 'Tunisia', yes: 'maghreb_l med desert_l afcon_l flag_red flag_white flag_star', maybe: 'history_l lang_fr' },
  { id: 'l_algeria',    icon: '🇩🇿', ar: 'الجزائر', en: 'Algeria', yes: 'maghreb_l med desert_l huge afcon_l flag_green flag_white flag_red flag_star', maybe: 'lang_fr' },
  { id: 'l_morocco',    icon: '🇲🇦', ar: 'المغرب', en: 'Morocco', yes: 'maghreb_l med desert_l afcon_l royal flag_red flag_green flag_star', maybe: 'lang_fr history_l' },
  { id: 'l_mauritania', icon: '🇲🇷', ar: 'موريتانيا', en: 'Mauritania', yes: 'maghreb_l sea_l desert_l flag_green flag_yellow flag_red flag_star', maybe: 'huge lang_fr' },
  { id: 'l_somalia',    icon: '🇸🇴', ar: 'الصومال', en: 'Somalia', yes: 'africa_l sea_l flag_blue flag_white flag_star', maybe: 'arab desert_l' },
  { id: 'l_djibouti',   icon: '🇩🇯', ar: 'جيبوتي', en: 'Djibouti', yes: 'africa_l sea_l desert_l lang_fr flag_blue flag_green flag_white flag_red flag_star', maybe: 'arab tiny redsea' },
  { id: 'l_comoros',    icon: '🇰🇲', ar: 'جزر القمر', en: 'Comoros', yes: 'africa_l sea_l island_l lang_fr flag_yellow flag_white flag_red flag_blue flag_green flag_star', maybe: 'arab tiny' },
  { id: 'l_saudi',      icon: '🇸🇦', ar: 'السعودية', en: 'Saudi Arabia', yes: 'gulf_l redsea desert_l huge royal flag_green flag_white', maybe: 'skyscraper' },
  { id: 'l_uae',        icon: '🇦🇪', ar: 'الإمارات', en: 'United Arab Emirates', yes: 'gulf_l sea_l desert_l skyscraper flag_red flag_green flag_white flag_black', maybe: 'royal lang_en' },
  { id: 'l_kuwait',     icon: '🇰🇼', ar: 'الكويت', en: 'Kuwait', yes: 'gulf_l sea_l desert_l royal flag_green flag_white flag_red flag_black', maybe: 'tiny' },
  { id: 'l_qatar',      icon: '🇶🇦', ar: 'دولة قطر', en: 'Qatar', yes: 'gulf_l sea_l desert_l royal flag_white', maybe: 'tiny skyscraper flag_red' },
  { id: 'l_bahrain',    icon: '🇧🇭', ar: 'البحرين', en: 'Bahrain', yes: 'gulf_l sea_l island_l tiny royal flag_red flag_white', maybe: 'desert_l' },
  { id: 'l_oman',       icon: '🇴🇲', ar: 'عمان', en: 'Oman', yes: 'gulf_l sea_l desert_l royal flag_red flag_white flag_green' },
  { id: 'l_yemen',      icon: '🇾🇪', ar: 'اليمن', en: 'Yemen', yes: 'arab asia_l redsea desert_l flag_red flag_white flag_black', maybe: 'gulf_l history_l' },
  { id: 'l_iraq',       icon: '🇮🇶', ar: 'العراق', en: 'Iraq', yes: 'arab asia_l sea_l desert_l history_l flag_red flag_white flag_black flag_green', maybe: 'gulf_l' },
  { id: 'l_syria',      icon: '🇸🇾', ar: 'سوريا', en: 'Syria', yes: 'levant_l med desert_l history_l flag_red flag_white flag_black flag_green flag_star', maybe: 'snow_l' },
  { id: 'l_lebanon',    icon: '🇱🇧', ar: 'لبنان', en: 'Lebanon', yes: 'levant_l med flag_red flag_white flag_green', maybe: 'tiny lang_fr snow_l history_l' },
  { id: 'l_jordan',     icon: '🇯🇴', ar: 'الأردن', en: 'Jordan', yes: 'levant_l sea_l desert_l royal history_l flag_black flag_white flag_green flag_red flag_star', maybe: 'redsea' },
  { id: 'l_palestine',  icon: '🇵🇸', ar: 'فلسطين', en: 'Palestine', yes: 'levant_l med neighbor_eg flag_black flag_white flag_green flag_red', maybe: 'tiny history_l' },

  /* ---------- Africa ---------- */
  { id: 'l_nigeria',    icon: '🇳🇬', ar: 'نيجيريا', en: 'Nigeria', yes: 'africa_l sea_l lang_en afcon_l flag_green flag_white', maybe: 'jungle huge' },
  { id: 'l_southafrica', icon: '🇿🇦', ar: 'جنوب أفريقيا', en: 'South Africa', yes: 'africa_l sea_l lang_en afcon_l flag_red flag_blue flag_green flag_black flag_yellow flag_white', maybe: 'desert_l huge' },
  { id: 'l_ethiopia',   icon: '🇪🇹', ar: 'إثيوبيا', en: 'Ethiopia', yes: 'africa_l nile_l afcon_l flag_green flag_yellow flag_red flag_blue flag_star', maybe: 'history_l' },
  { id: 'l_kenya',      icon: '🇰🇪', ar: 'كينيا', en: 'Kenya', yes: 'africa_l sea_l lang_en flag_black flag_red flag_green flag_white' },
  { id: 'l_ghana',      icon: '🇬🇭', ar: 'غانا', en: 'Ghana', yes: 'africa_l sea_l lang_en afcon_l flag_red flag_yellow flag_green flag_black flag_star', maybe: 'jungle' },
  { id: 'l_senegal',    icon: '🇸🇳', ar: 'السنغال', en: 'Senegal', yes: 'africa_l sea_l lang_fr afcon_l flag_green flag_yellow flag_red flag_star' },
  { id: 'l_cameroon',   icon: '🇨🇲', ar: 'الكاميرون', en: 'Cameroon', yes: 'africa_l sea_l jungle lang_fr lang_en afcon_l flag_green flag_red flag_yellow flag_star' },
  { id: 'l_ivorycoast', icon: '🇨🇮', ar: 'ساحل العاج', en: 'Ivory Coast', yes: 'africa_l sea_l lang_fr afcon_l flag_orange flag_white flag_green', maybe: 'jungle' },
  { id: 'l_mali',       icon: '🇲🇱', ar: 'مالي', en: 'Mali', yes: 'africa_l desert_l flag_green flag_yellow flag_red', maybe: 'lang_fr huge history_l' },
  { id: 'l_niger',      icon: '🇳🇪', ar: 'النيجر', en: 'Niger', yes: 'africa_l desert_l flag_orange flag_white flag_green', maybe: 'lang_fr huge' },
  { id: 'l_chad',       icon: '🇹🇩', ar: 'تشاد', en: 'Chad', yes: 'africa_l desert_l lang_fr flag_blue flag_yellow flag_red', maybe: 'huge arab' },
  { id: 'l_uganda',     icon: '🇺🇬', ar: 'أوغندا', en: 'Uganda', yes: 'africa_l nile_l lang_en flag_black flag_yellow flag_red flag_white', maybe: 'jungle' },
  { id: 'l_tanzania',   icon: '🇹🇿', ar: 'تنزانيا', en: 'Tanzania', yes: 'africa_l sea_l lang_en flag_green flag_yellow flag_black flag_blue', maybe: 'jungle' },
  { id: 'l_drcongo',    icon: '🇨🇩', ar: 'الكونغو الديمقراطية', en: 'DR Congo', yes: 'africa_l sea_l jungle huge lang_fr afcon_l flag_blue flag_red flag_yellow flag_star' },
  { id: 'l_angola',     icon: '🇦🇴', ar: 'أنغولا', en: 'Angola', yes: 'africa_l sea_l lang_pt flag_red flag_black flag_yellow flag_star', maybe: 'desert_l jungle huge' },
  { id: 'l_zimbabwe',   icon: '🇿🇼', ar: 'زيمبابوي', en: 'Zimbabwe', yes: 'africa_l lang_en flag_green flag_yellow flag_red flag_black flag_white flag_star' },
  { id: 'l_madagascar', icon: '🇲🇬', ar: 'مدغشقر', en: 'Madagascar', yes: 'africa_l sea_l island_l lang_fr flag_white flag_red flag_green', maybe: 'jungle' },
  { id: 'l_southsudan', icon: '🇸🇸', ar: 'جنوب السودان', en: 'South Sudan', yes: 'africa_l nile_l lang_en flag_black flag_white flag_red flag_green flag_blue flag_yellow flag_star' },

  /* ---------- Asia ---------- */
  { id: 'l_china',      icon: '🇨🇳', ar: 'الصين', en: 'China', yes: 'eastasia sea_l huge desert_l history_l skyscraper flag_red flag_yellow flag_star', maybe: 'snow_l' },
  { id: 'l_japan',      icon: '🇯🇵', ar: 'اليابان', en: 'Japan', yes: 'eastasia sea_l island_l flag_white flag_red', maybe: 'royal snow_l skyscraper' },
  { id: 'l_korea',      icon: '🇰🇷', ar: 'كوريا الجنوبية', en: 'South Korea', yes: 'eastasia sea_l flag_white flag_red flag_blue flag_black', maybe: 'snow_l skyscraper' },
  { id: 'l_mongolia',   icon: '🇲🇳', ar: 'منغوليا', en: 'Mongolia', yes: 'eastasia desert_l flag_red flag_blue flag_yellow', maybe: 'huge snow_l' },
  { id: 'l_india',      icon: '🇮🇳', ar: 'الهند', en: 'India', yes: 'southasia sea_l huge history_l cinema lang_en flag_orange flag_white flag_green flag_blue', maybe: 'desert_l jungle snow_l' },
  { id: 'l_pakistan',   icon: '🇵🇰', ar: 'باكستان', en: 'Pakistan', yes: 'southasia sea_l lang_en flag_green flag_white flag_star', maybe: 'desert_l snow_l' },
  { id: 'l_bangladesh', icon: '🇧🇩', ar: 'بنغلاديش', en: 'Bangladesh', yes: 'southasia sea_l flag_green flag_red' },
  { id: 'l_srilanka',   icon: '🇱🇰', ar: 'سريلانكا', en: 'Sri Lanka', yes: 'southasia sea_l island_l flag_yellow flag_orange flag_green', maybe: 'flag_red jungle' },
  { id: 'l_nepal',      icon: '🇳🇵', ar: 'نيبال', en: 'Nepal', yes: 'southasia snow_l flag_red flag_blue flag_white' },
  { id: 'l_maldives',   icon: '🇲🇻', ar: 'جزر المالديف', en: 'Maldives', yes: 'southasia sea_l island_l tiny flag_red flag_green flag_white' },
  { id: 'l_indonesia',  icon: '🇮🇩', ar: 'إندونيسيا', en: 'Indonesia', yes: 'seasia sea_l island_l jungle flag_red flag_white', maybe: 'huge' },
  { id: 'l_malaysia',   icon: '🇲🇾', ar: 'ماليزيا', en: 'Malaysia', yes: 'seasia sea_l jungle royal skyscraper flag_red flag_white flag_blue flag_yellow flag_star', maybe: 'lang_en' },
  { id: 'l_thailand',   icon: '🇹🇭', ar: 'تايلاند', en: 'Thailand', yes: 'seasia sea_l royal flag_red flag_white flag_blue', maybe: 'jungle' },
  { id: 'l_philippines', icon: '🇵🇭', ar: 'الفلبين', en: 'Philippines', yes: 'seasia sea_l island_l lang_en flag_blue flag_red flag_white flag_yellow flag_star', maybe: 'jungle' },
  { id: 'l_vietnam',    icon: '🇻🇳', ar: 'فيتنام', en: 'Vietnam', yes: 'seasia sea_l flag_red flag_yellow flag_star', maybe: 'jungle' },
  { id: 'l_singapore',  icon: '🇸🇬', ar: 'سنغافورة', en: 'Singapore', yes: 'seasia sea_l island_l tiny lang_en skyscraper flag_red flag_white flag_star' },
  { id: 'l_iran',       icon: '🇮🇷', ar: 'إيران', en: 'Iran', yes: 'asia_l sea_l desert_l history_l flag_green flag_white flag_red', maybe: 'huge snow_l' },
  { id: 'l_turkey',     icon: '🇹🇷', ar: 'تركيا', en: 'Turkey (the country)', yes: 'asia_l med history_l flag_red flag_white flag_star', maybe: 'europe_l snow_l' },
  { id: 'l_kazakhstan', icon: '🇰🇿', ar: 'كازاخستان', en: 'Kazakhstan', yes: 'asia_l huge desert_l snow_l flag_blue flag_yellow', maybe: 'sea_l' },
  { id: 'l_uzbekistan', icon: '🇺🇿', ar: 'أوزبكستان', en: 'Uzbekistan', yes: 'asia_l desert_l flag_blue flag_white flag_green flag_red flag_star', maybe: 'history_l snow_l' },

  /* ---------- Europe ---------- */
  { id: 'l_uk',         icon: '🇬🇧', ar: 'المملكة المتحدة', en: 'United Kingdom', yes: 'europe_l sea_l island_l lang_en royal flag_red flag_white flag_blue', maybe: 'wc_l snow_l history_l skyscraper' },
  { id: 'l_ireland',    icon: '🇮🇪', ar: 'أيرلندا', en: 'Ireland', yes: 'europe_l sea_l island_l lang_en flag_green flag_white flag_orange' },
  { id: 'l_france',     icon: '🇫🇷', ar: 'فرنسا', en: 'France', yes: 'europe_l med lang_fr wc_l flag_blue flag_white flag_red', maybe: 'history_l snow_l' },
  { id: 'l_germany',    icon: '🇩🇪', ar: 'ألمانيا', en: 'Germany', yes: 'europe_l sea_l lang_de wc_l flag_black flag_red flag_yellow', maybe: 'snow_l' },
  { id: 'l_italy',      icon: '🇮🇹', ar: 'إيطاليا', en: 'Italy', yes: 'europe_l med wc_l history_l flag_green flag_white flag_red', maybe: 'snow_l' },
  { id: 'l_spain',      icon: '🇪🇸', ar: 'إسبانيا', en: 'Spain', yes: 'europe_l med lang_es wc_l royal flag_red flag_yellow', maybe: 'history_l' },
  { id: 'l_portugal',   icon: '🇵🇹', ar: 'البرتغال', en: 'Portugal', yes: 'europe_l sea_l lang_pt flag_green flag_red flag_yellow' },
  { id: 'l_netherlands', icon: '🇳🇱', ar: 'هولندا', en: 'Netherlands', yes: 'europe_l sea_l royal flag_red flag_white flag_blue' },
  { id: 'l_belgium',    icon: '🇧🇪', ar: 'بلجيكا', en: 'Belgium', yes: 'europe_l sea_l royal lang_fr flag_black flag_yellow flag_red', maybe: 'lang_de' },
  { id: 'l_switzerland', icon: '🇨🇭', ar: 'سويسرا', en: 'Switzerland', yes: 'europe_l snow_l lang_de lang_fr flag_red flag_white' },
  { id: 'l_austria',    icon: '🇦🇹', ar: 'النمسا', en: 'Austria', yes: 'europe_l snow_l lang_de flag_red flag_white' },
  { id: 'l_luxembourg', icon: '🇱🇺', ar: 'لوكسمبورغ', en: 'Luxembourg', yes: 'europe_l tiny royal lang_fr lang_de flag_red flag_white flag_blue' },
  { id: 'l_monaco',     icon: '🇲🇨', ar: 'موناكو', en: 'Monaco', yes: 'europe_l med tiny royal lang_fr flag_red flag_white' },
  { id: 'l_greece',     icon: '🇬🇷', ar: 'اليونان', en: 'Greece', yes: 'europe_l med history_l flag_blue flag_white', maybe: 'island_l' },
  { id: 'l_sweden',     icon: '🇸🇪', ar: 'السويد', en: 'Sweden', yes: 'north_eu sea_l snow_l royal flag_blue flag_yellow' },
  { id: 'l_norway',     icon: '🇳🇴', ar: 'النرويج', en: 'Norway', yes: 'north_eu sea_l snow_l royal flag_red flag_white flag_blue' },
  { id: 'l_denmark',    icon: '🇩🇰', ar: 'الدنمارك', en: 'Denmark', yes: 'north_eu sea_l royal flag_red flag_white', maybe: 'snow_l' },
  { id: 'l_finland',    icon: '🇫🇮', ar: 'فنلندا', en: 'Finland', yes: 'north_eu sea_l snow_l flag_white flag_blue' },
  { id: 'l_iceland',    icon: '🇮🇸', ar: 'آيسلندا', en: 'Iceland', yes: 'north_eu sea_l island_l snow_l flag_blue flag_white flag_red' },
  { id: 'l_poland',     icon: '🇵🇱', ar: 'بولندا', en: 'Poland', yes: 'easteu sea_l snow_l flag_white flag_red' },
  { id: 'l_czechia',    icon: '🇨🇿', ar: 'التشيك', en: 'Czechia', yes: 'easteu snow_l flag_white flag_red flag_blue' },
  { id: 'l_hungary',    icon: '🇭🇺', ar: 'المجر', en: 'Hungary', yes: 'easteu flag_red flag_white flag_green', maybe: 'snow_l' },
  { id: 'l_romania',    icon: '🇷🇴', ar: 'رومانيا', en: 'Romania', yes: 'easteu sea_l snow_l flag_blue flag_yellow flag_red' },
  { id: 'l_bulgaria',   icon: '🇧🇬', ar: 'بلغاريا', en: 'Bulgaria', yes: 'easteu sea_l flag_white flag_green flag_red', maybe: 'snow_l' },
  { id: 'l_croatia',    icon: '🇭🇷', ar: 'كرواتيا', en: 'Croatia', yes: 'europe_l med flag_red flag_white flag_blue', maybe: 'easteu' },
  { id: 'l_ukraine',    icon: '🇺🇦', ar: 'أوكرانيا', en: 'Ukraine', yes: 'easteu sea_l snow_l flag_blue flag_yellow' },
  { id: 'l_russia',     icon: '🇷🇺', ar: 'روسيا', en: 'Russia', yes: 'easteu sea_l snow_l huge flag_white flag_blue flag_red', maybe: 'asia_l' },
  { id: 'l_albania',    icon: '🇦🇱', ar: 'ألبانيا', en: 'Albania', yes: 'europe_l med flag_red flag_black', maybe: 'easteu' },
  { id: 'l_bosnia',     icon: '🇧🇦', ar: 'البوسنة والهرسك', en: 'Bosnia and Herzegovina', yes: 'europe_l flag_blue flag_yellow flag_white flag_star', maybe: 'easteu sea_l snow_l' },
  { id: 'l_cyprus',     icon: '🇨🇾', ar: 'قبرص', en: 'Cyprus', yes: 'europe_l med island_l flag_white flag_green', maybe: 'asia_l tiny flag_orange' },
  { id: 'l_malta',      icon: '🇲🇹', ar: 'مالطا', en: 'Malta', yes: 'europe_l med island_l tiny lang_en flag_white flag_red' },

  /* ---------- the Americas and Oceania ---------- */
  { id: 'l_usa',        icon: '🇺🇸', ar: 'الولايات المتحدة', en: 'United States', yes: 'america_l sea_l huge lang_en skyscraper cinema flag_red flag_white flag_blue flag_star', maybe: 'desert_l snow_l lang_es' },
  { id: 'l_canada',     icon: '🇨🇦', ar: 'كندا', en: 'Canada', yes: 'america_l sea_l huge snow_l lang_en lang_fr flag_red flag_white', maybe: 'royal' },
  { id: 'l_mexico',     icon: '🇲🇽', ar: 'المكسيك', en: 'Mexico', yes: 'america_l sea_l desert_l lang_es history_l flag_green flag_white flag_red', maybe: 'huge' },
  { id: 'l_cuba',       icon: '🇨🇺', ar: 'كوبا', en: 'Cuba', yes: 'america_l sea_l island_l lang_es flag_blue flag_white flag_red flag_star' },
  { id: 'l_jamaica',    icon: '🇯🇲', ar: 'جامايكا', en: 'Jamaica', yes: 'america_l sea_l island_l lang_en flag_green flag_yellow flag_black', maybe: 'tiny royal' },
  { id: 'l_costarica',  icon: '🇨🇷', ar: 'كوستاريكا', en: 'Costa Rica', yes: 'america_l sea_l lang_es jungle flag_blue flag_white flag_red' },
  { id: 'l_panama',     icon: '🇵🇦', ar: 'بنما', en: 'Panama', yes: 'america_l sea_l lang_es jungle canal_l flag_white flag_red flag_blue flag_star' },
  { id: 'l_brazil',     icon: '🇧🇷', ar: 'البرازيل', en: 'Brazil', yes: 'southam sea_l huge jungle lang_pt wc_l flag_green flag_yellow flag_blue flag_white flag_star' },
  { id: 'l_argentina',  icon: '🇦🇷', ar: 'الأرجنتين', en: 'Argentina', yes: 'southam sea_l huge lang_es wc_l flag_blue flag_white', maybe: 'flag_yellow snow_l' },
  { id: 'l_uruguay',    icon: '🇺🇾', ar: 'أوروغواي', en: 'Uruguay', yes: 'southam sea_l lang_es wc_l flag_white flag_blue', maybe: 'flag_yellow' },
  { id: 'l_chile',      icon: '🇨🇱', ar: 'تشيلي', en: 'Chile', yes: 'southam sea_l lang_es desert_l flag_red flag_white flag_blue flag_star', maybe: 'snow_l' },
  { id: 'l_colombia',   icon: '🇨🇴', ar: 'كولومبيا', en: 'Colombia', yes: 'southam sea_l lang_es jungle flag_yellow flag_blue flag_red' },
  { id: 'l_venezuela',  icon: '🇻🇪', ar: 'فنزويلا', en: 'Venezuela', yes: 'southam sea_l lang_es jungle flag_yellow flag_blue flag_red flag_white flag_star' },
  { id: 'l_peru',       icon: '🇵🇪', ar: 'بيرو', en: 'Peru', yes: 'southam sea_l lang_es history_l flag_red flag_white', maybe: 'jungle desert_l snow_l' },
  { id: 'l_bolivia',    icon: '🇧🇴', ar: 'بوليفيا', en: 'Bolivia', yes: 'southam lang_es flag_red flag_yellow flag_green', maybe: 'snow_l jungle' },
  { id: 'l_paraguay',   icon: '🇵🇾', ar: 'باراغواي', en: 'Paraguay', yes: 'southam lang_es flag_red flag_white flag_blue' },
  { id: 'l_australia',  icon: '🇦🇺', ar: 'أستراليا', en: 'Australia', yes: 'oceania sea_l huge desert_l lang_en flag_blue flag_red flag_white flag_star', maybe: 'island_l royal jungle' },
  { id: 'l_newzealand', icon: '🇳🇿', ar: 'نيوزيلندا', en: 'New Zealand', yes: 'oceania sea_l island_l lang_en flag_blue flag_red flag_white flag_star', maybe: 'snow_l royal' },

  /* ---------- Egyptian cities ---------- */
  { id: 'l_cairo',      icon: '🏙️', ar: 'القاهرة', en: 'Cairo', yes: 'capital egypt africa_l nile_l river_city history_l cinema flag_red flag_white flag_black', maybe: 'pharaonic flag_yellow' },
  { id: 'l_giza',       icon: '🔺', ar: 'الجيزة', en: 'Giza', yes: 'river_city egypt africa_l nile_l pharaonic history_l flag_red flag_white flag_black', maybe: 'flag_yellow' },
  { id: 'l_alexandria', icon: '⛱️', ar: 'الإسكندرية', en: 'Alexandria', yes: 'beach_city egypt africa_l med history_l flag_red flag_white flag_black', maybe: 'delta pharaonic flag_yellow' },
  { id: 'l_luxor',      icon: '🏛️', ar: 'الأقصر', en: 'Luxor', yes: 'river_city south_l africa_l nile_l pharaonic history_l flag_red flag_white flag_black', maybe: 'desert_l flag_yellow' },
  { id: 'l_aswan',      icon: '⛵', ar: 'أسوان', en: 'Aswan', yes: 'river_city south_l africa_l nile_l nubia pharaonic history_l flag_red flag_white flag_black', maybe: 'desert_l flag_yellow' },
  { id: 'l_asyut',      icon: '🌾', ar: 'أسيوط', en: 'Asyut', yes: 'river_city south_l africa_l nile_l flag_red flag_white flag_black', maybe: 'flag_yellow' },
  { id: 'l_sharm',      icon: '🤿', ar: 'شرم الشيخ', en: 'Sharm El Sheikh', yes: 'beach_city sinai redsea flag_red flag_white flag_black', maybe: 'africa_l asia_l desert_l flag_yellow' },
  { id: 'l_hurghada',   icon: '🐠', ar: 'الغردقة', en: 'Hurghada', yes: 'beach_city egypt africa_l redsea flag_red flag_white flag_black', maybe: 'desert_l flag_yellow' },
  { id: 'l_portsaid',   icon: '⚓', ar: 'بورسعيد', en: 'Port Said', yes: 'city egypt africa_l med canal_l flag_red flag_white flag_black', maybe: 'beach_city delta flag_yellow' },
  { id: 'l_ismailia',   icon: '🚢', ar: 'الإسماعيلية', en: 'Ismailia', yes: 'city egypt africa_l canal_l flag_red flag_white flag_black', maybe: 'flag_yellow' },
  { id: 'l_suez',       icon: '🛳️', ar: 'السويس', en: 'Suez', yes: 'city egypt africa_l redsea canal_l flag_red flag_white flag_black', maybe: 'flag_yellow' },
  { id: 'l_mansoura',   icon: '🌉', ar: 'المنصورة', en: 'Mansoura', yes: 'river_city delta africa_l nile_l flag_red flag_white flag_black', maybe: 'flag_yellow' },
  { id: 'l_tanta',      icon: '🚉', ar: 'طنطا', en: 'Tanta', yes: 'city delta africa_l flag_red flag_white flag_black', maybe: 'flag_yellow' },
  { id: 'l_damietta',   icon: '🪑', ar: 'دمياط', en: 'Damietta', yes: 'river_city delta africa_l med nile_l flag_red flag_white flag_black', maybe: 'beach_city flag_yellow' },
  { id: 'l_matrouh',    icon: '🏖️', ar: 'مرسى مطروح', en: 'Marsa Matrouh', yes: 'beach_city egypt africa_l med flag_red flag_white flag_black', maybe: 'desert_l flag_yellow' },
  { id: 'l_siwa',       icon: '🌴', ar: 'سيوة', en: 'Siwa', yes: 'city egypt africa_l desert_l flag_red flag_white flag_black', maybe: 'flag_yellow' },

  /* ---------- cities of the world ---------- */
  { id: 'l_dubai',      icon: '🏙️', ar: 'دبي', en: 'Dubai', yes: 'city gulf_l sea_l desert_l skyscraper flag_red flag_green flag_white flag_black', maybe: 'beach_city lang_en' },
  { id: 'l_abudhabi',   icon: '🌇', ar: 'أبوظبي', en: 'Abu Dhabi', yes: 'capital gulf_l sea_l desert_l flag_red flag_green flag_white flag_black', maybe: 'skyscraper' },
  { id: 'l_riyadh',     icon: '🏜️', ar: 'الرياض', en: 'Riyadh', yes: 'capital gulf_l desert_l flag_green flag_white', maybe: 'skyscraper' },
  { id: 'l_jeddah',     icon: '⛲', ar: 'جدة', en: 'Jeddah', yes: 'city gulf_l redsea flag_green flag_white', maybe: 'beach_city desert_l history_l' },
  { id: 'l_doha',       icon: '🏟️', ar: 'الدوحة', en: 'Doha', yes: 'capital gulf_l sea_l desert_l flag_white', maybe: 'skyscraper flag_red' },
  { id: 'l_beirut',     icon: '🌲', ar: 'بيروت', en: 'Beirut', yes: 'capital levant_l med flag_red flag_white flag_green', maybe: 'lang_fr beach_city' },
  { id: 'l_damascus',   icon: '🌹', ar: 'دمشق', en: 'Damascus', yes: 'capital levant_l history_l flag_red flag_white flag_black flag_green flag_star', maybe: 'river_city' },
  { id: 'l_baghdad',    icon: '🌴', ar: 'بغداد', en: 'Baghdad', yes: 'capital river_city arab asia_l history_l flag_red flag_white flag_black flag_green' },
  { id: 'l_casablanca', icon: '🌊', ar: 'الدار البيضاء', en: 'Casablanca', yes: 'city maghreb_l sea_l flag_red flag_green flag_star', maybe: 'lang_fr beach_city' },
  { id: 'l_marrakech',  icon: '🏮', ar: 'مراكش', en: 'Marrakech', yes: 'city maghreb_l flag_red flag_green flag_star', maybe: 'history_l desert_l lang_fr' },
  { id: 'l_istanbul',   icon: '🌉', ar: 'إسطنبول', en: 'Istanbul', yes: 'city sea_l history_l flag_red flag_white flag_star', maybe: 'europe_l asia_l snow_l' },
  { id: 'l_paris',      icon: '🗼', ar: 'باريس', en: 'Paris', yes: 'capital river_city europe_l lang_fr flag_blue flag_white flag_red', maybe: 'history_l' },
  { id: 'l_london',     icon: '💂', ar: 'لندن', en: 'London', yes: 'capital river_city europe_l lang_en flag_red flag_white flag_blue', maybe: 'skyscraper history_l' },
  { id: 'l_rome',       icon: '🏛️', ar: 'روما', en: 'Rome', yes: 'capital river_city europe_l history_l flag_green flag_white flag_red' },
  { id: 'l_venice',     icon: '🛶', ar: 'فينيسيا', en: 'Venice', yes: 'canals_city europe_l sea_l flag_green flag_white flag_red', maybe: 'med history_l island_l canal_l' },
  { id: 'l_milan',      icon: '👗', ar: 'ميلانو', en: 'Milan', yes: 'city europe_l flag_green flag_white flag_red' },
  { id: 'l_madrid',     icon: '⚽', ar: 'مدريد', en: 'Madrid', yes: 'capital europe_l lang_es flag_red flag_yellow' },
  { id: 'l_barcelona',  icon: '🏖️', ar: 'برشلونة', en: 'Barcelona', yes: 'city europe_l med lang_es flag_red flag_yellow', maybe: 'beach_city' },
  { id: 'l_berlin',     icon: '🐻', ar: 'برلين', en: 'Berlin', yes: 'capital river_city europe_l lang_de flag_black flag_red flag_yellow', maybe: 'snow_l' },
  { id: 'l_amsterdam',  icon: '🌷', ar: 'أمستردام', en: 'Amsterdam', yes: 'capital europe_l flag_red flag_white flag_blue', maybe: 'canals_city river_city canal_l' },
  { id: 'l_moscow',     icon: '🏰', ar: 'موسكو', en: 'Moscow', yes: 'capital river_city easteu snow_l flag_white flag_blue flag_red' },
  { id: 'l_athens',     icon: '🏛️', ar: 'أثينا', en: 'Athens', yes: 'capital europe_l history_l flag_blue flag_white', maybe: 'sea_l med' },
  { id: 'l_newyork',    icon: '🗽', ar: 'نيويورك', en: 'New York', yes: 'city america_l sea_l lang_en skyscraper flag_red flag_white flag_blue flag_star', maybe: 'snow_l river_city' },
  { id: 'l_losangeles', icon: '🎬', ar: 'لوس أنجلوس', en: 'Los Angeles', yes: 'city america_l sea_l lang_en cinema flag_red flag_white flag_blue flag_star', maybe: 'beach_city lang_es' },
  { id: 'l_tokyo',      icon: '🗼', ar: 'طوكيو', en: 'Tokyo', yes: 'capital eastasia sea_l skyscraper flag_white flag_red' },
  { id: 'l_beijing',    icon: '🏯', ar: 'بكين', en: 'Beijing', yes: 'capital eastasia history_l flag_red flag_yellow flag_star', maybe: 'skyscraper snow_l' },
  { id: 'l_sydney',     icon: '🦘', ar: 'سيدني', en: 'Sydney', yes: 'city oceania sea_l lang_en flag_blue flag_red flag_white flag_star', maybe: 'beach_city skyscraper' },
  { id: 'l_rio',        icon: '🎉', ar: 'ريو دي جانيرو', en: 'Rio de Janeiro', yes: 'beach_city southam sea_l lang_pt flag_green flag_yellow flag_blue flag_white flag_star' },
] };
