/* العرّاف: animals (kind 'a'). One line each: id, icon, ar, en, and the question ids
   (OracleQuestions.js) that are true of it (yes), partly or "most would say probably" (maybe),
   and firmly not, where a player might think otherwise (no). A question about animals that
   is in none of the three reads as «غالباً لأ». notes/games/oracle.md, "Writing entries";
   check with `cd tools && npm run check:oracle`. */
const ORACLE_ANIMALS = { kind: 'a', list: [
  { id: 'lion',      icon: '🦁', ar: 'أسد', en: 'Lion', yes: 'mammal wild meat africa_a legs4 fur tail danger fast', maybe: 'big yellow brown' },
  { id: 'tiger',     icon: '🐯', ar: 'نمر', en: 'Tiger', yes: 'mammal wild meat legs4 fur tail stripes danger fast orange', maybe: 'big black', no: 'africa_a' },
  { id: 'cheetah',   icon: '🐆', ar: 'فهد', en: 'Cheetah', yes: 'mammal wild meat africa_a legs4 fur tail spots fast yellow', maybe: 'danger' },
  { id: 'wolf',      icon: '🐺', ar: 'ديب', en: 'Wolf', yes: 'mammal wild meat legs4 fur tail night gray danger', maybe: 'snow' },
  { id: 'fox',       icon: '🦊', ar: 'تعلب', en: 'Fox', yes: 'mammal wild meat legs4 fur tail orange night', maybe: 'inegypt desert' },
  { id: 'bear',      icon: '🐻', ar: 'دبّ', en: 'Bear', yes: 'mammal wild meat plants legs4 fur big danger brown climb', maybe: 'snow' },
  { id: 'polarbear', icon: '🐻‍❄️', ar: 'دبّ قطبي', en: 'Polar bear', yes: 'mammal wild meat legs4 fur big danger white snow', maybe: 'water' },
  { id: 'elephant',  icon: '🐘', ar: 'فيل', en: 'Elephant', yes: 'mammal wild plants africa_a legs4 big bigears gray', maybe: 'ride danger' },
  { id: 'giraffe',   icon: '🦒', ar: 'زرافة', en: 'Giraffe', yes: 'mammal wild plants africa_a legs4 longneck spots big yellow', maybe: 'brown' },
  { id: 'rhino',     icon: '🦏', ar: 'وحيد القرن', en: 'Rhino', yes: 'mammal wild plants africa_a legs4 horns big gray danger' },
  { id: 'hippo',     icon: '🦛', ar: 'فرس النهر', en: 'Hippo', yes: 'mammal wild plants africa_a legs4 big gray water danger' },
  { id: 'zebra',     icon: '🦓', ar: 'حمار وحشي', en: 'Zebra', yes: 'mammal wild plants africa_a legs4 stripes fast white black tail' },
  { id: 'camel',     icon: '🐪', ar: 'جمل', en: 'Camel', yes: 'mammal plants desert legs4 ride inegypt longneck brown gives', maybe: 'africa_a farm big yellow edible' },
  { id: 'horse',     icon: '🐴', ar: 'حصان', en: 'Horse', yes: 'mammal plants legs4 ride fast tail farm inegypt', maybe: 'brown big white black' },
  { id: 'donkey',    icon: '🫏', ar: 'حمار', en: 'Donkey', yes: 'mammal plants legs4 ride farm inegypt gray bigears', maybe: 'brown slow', no: 'fast' },
  { id: 'cow',       icon: '🐄', ar: 'بقرة', en: 'Cow', yes: 'mammal plants legs4 farm horns gives edible inegypt', maybe: 'white brown big spots' },
  { id: 'buffalo',   icon: '🐃', ar: 'جاموسة', en: 'Water buffalo', yes: 'mammal plants legs4 farm horns gives edible inegypt black', maybe: 'big water', no: 'white spots' },
  { id: 'sheep',     icon: '🐑', ar: 'خروف', en: 'Sheep', yes: 'mammal plants legs4 farm fur gives edible inegypt white', maybe: 'horns' },
  { id: 'goat',      icon: '🐐', ar: 'معزة', en: 'Goat', yes: 'mammal plants legs4 farm horns gives edible inegypt jump', maybe: 'black brown white climb' },
  { id: 'dog',       icon: '🐕', ar: 'كلب', en: 'Dog', yes: 'mammal pet legs4 fur tail inegypt meat', maybe: 'brown black white fast danger' },
  { id: 'cat',       icon: '🐈', ar: 'قطة', en: 'Cat', yes: 'mammal pet legs4 fur tail inegypt meat climb jump', maybe: 'night' },
  { id: 'rabbit',    icon: '🐇', ar: 'أرنب', en: 'Rabbit', yes: 'mammal pet plants legs4 fur bigears jump inegypt edible farm', maybe: 'white fast' },
  { id: 'mouse',     icon: '🐭', ar: 'فار', en: 'Mouse', yes: 'mammal small legs4 tail fur inegypt gray night', maybe: 'pet' },
  { id: 'squirrel',  icon: '🐿️', ar: 'سنجاب', en: 'Squirrel', yes: 'mammal wild plants legs4 climb fur tail brown jump', maybe: 'small orange' },
  { id: 'monkey',    icon: '🐒', ar: 'قرد', en: 'Monkey', yes: 'mammal wild plants climb tail jump brown', maybe: 'africa_a fur' },
  { id: 'gorilla',   icon: '🦍', ar: 'غوريلا', en: 'Gorilla', yes: 'mammal wild plants africa_a fur black big climb', maybe: 'danger', no: 'tail' },
  { id: 'panda',     icon: '🐼', ar: 'باندا', en: 'Panda', yes: 'mammal wild plants legs4 fur white black climb', maybe: 'big slow' },
  { id: 'kangaroo',  icon: '🦘', ar: 'كنغر', en: 'Kangaroo', yes: 'mammal wild plants jump tail fast brown', maybe: 'big', no: 'legs4' },
  { id: 'koala',     icon: '🐨', ar: 'كوالا', en: 'Koala', yes: 'mammal wild plants climb fur gray slow bigears' },
  { id: 'bat',       icon: '🦇', ar: 'خفاش', en: 'Bat', yes: 'mammal flies night black wild', maybe: 'small inegypt' },
  { id: 'hedgehog',  icon: '🦔', ar: 'قنفد', en: 'Hedgehog', yes: 'mammal wild small night brown legs4', maybe: 'inegypt shell' },
  { id: 'dolphin',   icon: '🐬', ar: 'دولفين', en: 'Dolphin', yes: 'mammal water gray fast wild meat nolegs', maybe: 'big blue', no: 'fish' },
  { id: 'whale',     icon: '🐋', ar: 'حوت', en: 'Whale', yes: 'mammal water big blue wild nolegs', maybe: 'gray', no: 'fish' },
  { id: 'shark',     icon: '🦈', ar: 'سمكة قرش', en: 'Shark', yes: 'fish water meat danger big gray fast wild nolegs', maybe: 'blue' },
  { id: 'octopus',   icon: '🐙', ar: 'أخطبوط', en: 'Octopus', yes: 'water wild meat', maybe: 'red pink orange sting' },
  { id: 'goldfish',  icon: '🐠', ar: 'سمكة زينة', en: 'Goldfish', yes: 'fish water pet small orange nolegs', maybe: 'yellow' },
  { id: 'fish',      icon: '🐟', ar: 'سمكة بلطي', en: 'Tilapia', yes: 'fish water edible nolegs inegypt gray' },
  { id: 'turtle',    icon: '🐢', ar: 'سلحفاة', en: 'Turtle', yes: 'reptile shell slow legs4 pet plants green', maybe: 'water brown' },
  { id: 'crocodile', icon: '🐊', ar: 'تمساح', en: 'Crocodile', yes: 'reptile water meat danger green tail legs4 wild big africa_a', maybe: 'inegypt' },
  { id: 'snake',     icon: '🐍', ar: 'تعبان', en: 'Snake', yes: 'reptile nolegs sting danger meat wild', maybe: 'desert inegypt green black tail' },
  { id: 'lizard',    icon: '🦎', ar: 'سحلية', en: 'Lizard', yes: 'reptile legs4 tail inegypt', maybe: 'small green desert brown' },
  { id: 'chameleon', icon: '🦎', ar: 'حرباية', en: 'Chameleon', yes: 'reptile green tail legs4 slow climb', maybe: 'small' },
  { id: 'frog',      icon: '🐸', ar: 'ضفدعة', en: 'Frog', yes: 'water jump green inegypt', maybe: 'small meat', no: 'reptile fish' },
  { id: 'eagle',     icon: '🦅', ar: 'نسر', en: 'Eagle', yes: 'bird flies meat wild brown', maybe: 'big danger fast' },
  { id: 'owl',       icon: '🦉', ar: 'بومة', en: 'Owl', yes: 'bird flies night meat wild brown', maybe: 'white' },
  { id: 'crow',      icon: '🐦‍⬛', ar: 'غراب', en: 'Crow', yes: 'bird flies black inegypt' },
  { id: 'parrot',    icon: '🦜', ar: 'ببغان', en: 'Parrot', yes: 'bird flies pet green', maybe: 'red yellow blue' },
  { id: 'pigeon',    icon: '🕊️', ar: 'حمامة', en: 'Pigeon', yes: 'bird flies inegypt edible gray', maybe: 'white farm pet' },
  { id: 'sparrow',   icon: '🐦', ar: 'عصفورة', en: 'Sparrow', yes: 'bird flies small inegypt brown', maybe: 'pet' },
  { id: 'duck',      icon: '🦆', ar: 'بطّة', en: 'Duck', yes: 'bird water farm edible inegypt', maybe: 'flies white gives' },
  { id: 'chicken',   icon: '🐔', ar: 'فرخة', en: 'Chicken', yes: 'bird farm edible gives inegypt', maybe: 'white brown', no: 'flies' },
  { id: 'rooster',   icon: '🐓', ar: 'ديك', en: 'Rooster', yes: 'bird farm inegypt', maybe: 'red edible', no: 'flies gives' },
  { id: 'turkey',    icon: '🦃', ar: 'ديك رومي', en: 'Turkey', yes: 'bird farm edible brown', maybe: 'inegypt big', no: 'flies' },
  { id: 'peacock',   icon: '🦚', ar: 'طاووس', en: 'Peacock', yes: 'bird blue green tail', maybe: 'flies' },
  { id: 'ostrich',   icon: '🐦', ar: 'نعامة', en: 'Ostrich', yes: 'bird africa_a fast longneck big wild', maybe: 'desert black', no: 'flies' },
  { id: 'penguin',   icon: '🐧', ar: 'بطريق', en: 'Penguin', yes: 'bird snow water black white wild colony', no: 'flies' },
  { id: 'flamingo',  icon: '🦩', ar: 'بشروش (فلامنجو)', en: 'Flamingo', yes: 'bird pink water longneck flies colony', maybe: 'wild' },
  { id: 'bee',       icon: '🐝', ar: 'نحلة', en: 'Bee', yes: 'insect flies sting small gives yellow black stripes inegypt colony' },
  { id: 'ant',       icon: '🐜', ar: 'نملة', en: 'Ant', yes: 'insect small black inegypt colony', maybe: 'sting red' },
  { id: 'butterfly', icon: '🦋', ar: 'فراشة', en: 'Butterfly', yes: 'insect flies small', maybe: 'inegypt' },
  { id: 'fly',       icon: '🪰', ar: 'دبّانة', en: 'Fly', yes: 'insect flies small black inegypt' },
  { id: 'mosquito',  icon: '🦟', ar: 'ناموسة', en: 'Mosquito', yes: 'insect flies small sting night inegypt' },
  { id: 'spider',    icon: '🕷️', ar: 'عنكبوت', en: 'Spider', yes: 'insect small black', maybe: 'sting inegypt' },
  { id: 'scorpion',  icon: '🦂', ar: 'عقربة', en: 'Scorpion', yes: 'sting danger desert', maybe: 'insect tail black yellow small inegypt' },
  { id: 'cockroach', icon: '🪳', ar: 'صرصار', en: 'Cockroach', yes: 'insect small brown inegypt night', maybe: 'flies' },
  { id: 'snail',     icon: '🐌', ar: 'حلزونة', en: 'Snail', yes: 'shell slow small', maybe: 'water' },
  { id: 'shrimp',    icon: '🦐', ar: 'جمبري', en: 'Shrimp', yes: 'water edible small', maybe: 'pink orange' },
  { id: 'crab',      icon: '🦀', ar: 'كابوريا', en: 'Crab', yes: 'water shell edible', maybe: 'red sting small' },
  { id: 'jellyfish', icon: '🪼', ar: 'قنديل البحر', en: 'Jellyfish', yes: 'water sting nolegs', maybe: 'white pink blue' },
  { id: 'starfish',  icon: '⭐', ar: 'نجمة البحر', en: 'Starfish', yes: 'water slow', maybe: 'small orange pink' },
  { id: 'dinosaur',  icon: '🦖', ar: 'ديناصور', en: 'Dinosaur', yes: 'extinct big danger tail wild', maybe: 'reptile green meat' },
  { id: 'seal',      icon: '🦭', ar: 'فقمة', en: 'Seal', yes: 'mammal water snow gray meat wild', maybe: 'black' },
]};
