/* العرّاف: video games and apps (kind 't': things). One line each, as in the other files (notes/games/oracle.md, "Writing entries");
   check with `cd tools && npm run check:oracle`. Added 10 Oct 2026. A game here is the game itself: its hero is a character
   in OracleCharacters.js (ماريو, باك مان, ستيف), told apart by the kind questions. Family-clean games only (no GTA, no Call of Duty). */
const ORACLE_APPS = { kind: 't', list: [
  /* ---------- video games ---------- */
  { id: 'pubg',          icon: '🪂', ar: 'ببجي', en: 'PUBG', yes: 'vgame onphone onconsole online battle internet', maybe: 'screen touch' },
  { id: 'freefire',      icon: '🔥', ar: 'فري فاير', en: 'Free Fire', yes: 'vgame onphone online battle internet', maybe: 'screen touch', no: 'onconsole' },
  { id: 'fortnite',      icon: '🦙', ar: 'فورتنايت', en: 'Fortnite', yes: 'vgame onconsole online battle building internet colorful', maybe: 'onphone screen' },
  { id: 'brawlstars',    icon: '⭐', ar: 'براول ستارز', en: 'Brawl Stars', yes: 'vgame onphone online battle internet colorful', maybe: 'screen touch toy' },
  { id: 'clashofclans',  icon: '🏰', ar: 'كلاش أوف كلانز', en: 'Clash of Clans', yes: 'vgame onphone online battle building internet', maybe: 'screen touch colorful' },
  { id: 'clashroyale',   icon: '👑', ar: 'كلاش رويال', en: 'Clash Royale', yes: 'vgame onphone online battle cardgame internet', maybe: 'screen touch colorful puzzle' },
  { id: 'conquer',       icon: '⚔️', ar: 'كونكر', en: 'Conquer Online', yes: 'vgame onconsole online battle internet', maybe: 'screen' },
  { id: 'minecraft',     icon: '⛏️', ar: 'ماينكرافت', en: 'Minecraft', yes: 'vgame onphone onconsole building square', maybe: 'green online internet brown battle toy screen' },
  { id: 'roblox',        icon: '🧱', ar: 'روبلوكس', en: 'Roblox', yes: 'vgame onphone onconsole online internet', maybe: 'building colorful toy screen touch' },
  { id: 'amongus',       icon: '👨‍🚀', ar: 'أمونج أس', en: 'Among Us', yes: 'vgame onphone onconsole online internet colorful red', maybe: 'puzzle screen touch' },
  { id: 'fifa',          icon: '⚽', ar: 'فيفا', en: 'FIFA (EA Sports FC)', yes: 'vgame footgame onconsole', maybe: 'onphone online internet sport screen' },
  { id: 'pes',           icon: '🥅', ar: 'بيس', en: 'PES (eFootball)', yes: 'vgame footgame onconsole japan_g', maybe: 'onphone online internet sport screen' },
  { id: 'dls',           icon: '👟', ar: 'دريم ليج', en: 'Dream League Soccer', yes: 'vgame footgame onphone', maybe: 'online internet sport screen touch', no: 'onconsole' },
  { id: 'needforspeed',  icon: '🏎️', ar: 'نيد فور سبيد', en: 'Need for Speed', yes: 'vgame onconsole racing cargame', maybe: 'onphone online internet oldgame screen' },
  { id: 'mariokart',     icon: '🏁', ar: 'ماريو كارت', en: 'Mario Kart', yes: 'vgame onconsole racing cargame japan_g colorful', maybe: 'onphone online oldgame screen' },
  { id: 'hillclimb',     icon: '🚙', ar: 'هيل كلايمب', en: 'Hill Climb Racing', yes: 'vgame onphone racing cargame', maybe: 'colorful screen touch' },
  { id: 'subwaysurfers', icon: '🛹', ar: 'صب واي سيرفرز', en: 'Subway Surfers', yes: 'vgame onphone racing colorful', maybe: 'toy screen touch' },
  { id: 'templerun',     icon: '🏃', ar: 'تمبل رن', en: 'Temple Run', yes: 'vgame onphone racing', maybe: 'brown screen touch' },
  { id: 'supermario',    icon: '🍄', ar: 'سوبر ماريو', en: 'Super Mario Bros.', yes: 'vgame onconsole oldgame japan_g red', maybe: 'colorful racing toy screen' },
  { id: 'candycrush',    icon: '🍬', ar: 'كاندي كراش', en: 'Candy Crush', yes: 'vgame onphone puzzle colorful', maybe: 'internet screen touch', no: 'edible sweet' },
  { id: 'angrybirds_g',  icon: '🐦', ar: 'أنجري بيردز', en: 'Angry Birds', yes: 'vgame onphone red', maybe: 'puzzle toy screen touch' },
  { id: 'flappybird',    icon: '🐤', ar: 'فلابي بيرد', en: 'Flappy Bird', yes: 'vgame onphone yellow', maybe: 'green flies screen touch colorful' },
  { id: 'fruitninja',    icon: '🍉', ar: 'فروت نينجا', en: 'Fruit Ninja', yes: 'vgame onphone colorful', maybe: 'sharp screen touch', no: 'edible' },
  { id: 'pou',           icon: '🥔', ar: 'لعبة بو', en: 'Pou', yes: 'vgame onphone toy brown', maybe: 'screen touch' },
  { id: 'pokemongo',     icon: '🗺️', ar: 'بوكيمون جو', en: 'Pokémon Go', yes: 'vgame onphone internet', maybe: 'japan_g mapapp street online colorful screen touch' },
  { id: 'tetris',        icon: '🟦', ar: 'تيترس', en: 'Tetris', yes: 'vgame puzzle oldgame building colorful square', maybe: 'onphone onconsole screen' },
  { id: 'pacman_g',      icon: '🟡', ar: 'لعبة باك مان', en: 'Pac-Man (the game)', yes: 'vgame oldgame japan_g yellow black', maybe: 'onconsole puzzle screen' },
  { id: 'snake_g',       icon: '🐍', ar: 'لعبة التعبان (نوكيا)', en: 'Snake (the Nokia game)', yes: 'vgame onphone oldgame', maybe: 'green black screen buttons' },
  { id: 'solitaire',     icon: '🂡', ar: 'سوليتير', en: 'Solitaire', yes: 'vgame onconsole cardgame oldgame', maybe: 'green tablegame puzzle onphone screen' },
  { id: 'minesweeper',   icon: '💣', ar: 'كاسحة الألغام', en: 'Minesweeper', yes: 'vgame onconsole puzzle oldgame', maybe: 'gray square screen' },
  { id: 'zuma',          icon: '🐸', ar: 'زوما', en: 'Zuma', yes: 'vgame onconsole puzzle colorful', maybe: 'green round onphone screen' },
  { id: 'eightball',     icon: '🎱', ar: 'بلياردو أونلاين (8 بول بول)', en: '8 Ball Pool', yes: 'vgame onphone online tablegame internet', maybe: 'green sport round screen touch' },
  { id: 'ludostar',      icon: '🎲', ar: 'لودو ستار', en: 'Ludo Star', yes: 'vgame onphone online tablegame internet colorful', maybe: 'screen touch' },
  { id: 'jawaker',       icon: '🃏', ar: 'جواكر', en: 'Jawaker', yes: 'arab vgame onphone online cardgame tablegame internet', maybe: 'screen touch' },
  /* ---------- games devices (the PlayStation is «console» in OracleThings.js) ---------- */
  { id: 'switch',        icon: '🎮', ar: 'نينتندو سويتش', en: 'Nintendo Switch', yes: 'electric screen buttons toy touch japan_g colorful', maybe: 'appgame vgame internet red blue listen', no: 'onphone' },
  { id: 'gameboy',       icon: '👾', ar: 'جيم بوي', en: 'Game Boy', yes: 'electric screen buttons toy oldgame japan_g gray', maybe: 'appgame vgame small pocket' },
  { id: 'atari',         icon: '🕹️', ar: 'أتاري', en: 'Atari', yes: 'electric buttons toy oldgame', maybe: 'appgame vgame black wood home' },
  /* ---------- apps: talking, posting, watching ---------- */
  { id: 'whatsapp',      icon: '💬', ar: 'واتساب', en: 'WhatsApp', yes: 'appgame onphone chatapp meta green internet talk', maybe: 'posts write screen touch' },
  { id: 'messenger',     icon: '🗨️', ar: 'ماسنجر', en: 'Messenger', yes: 'appgame onphone chatapp meta internet talk', maybe: 'blue pink write screen touch' },
  { id: 'facebook',      icon: '👍', ar: 'فيسبوك', en: 'Facebook', yes: 'appgame onphone posts meta blue internet talk', maybe: 'chatapp watchapp read write screen touch' },
  { id: 'instagram',     icon: '📸', ar: 'إنستجرام', en: 'Instagram', yes: 'appgame onphone posts meta internet colorful', maybe: 'pink orange chatapp watchapp talk screen touch' },
  { id: 'tiktok',        icon: '🎵', ar: 'تيك توك', en: 'TikTok', yes: 'appgame onphone posts watchapp internet black talk', maybe: 'listen screen touch' },
  { id: 'snapchat',      icon: '👻', ar: 'سناب شات', en: 'Snapchat', yes: 'appgame onphone posts chatapp yellow internet', maybe: 'white talk screen touch' },
  { id: 'twitter',       icon: '🐦', ar: 'إكس (تويتر)', en: 'X (Twitter)', yes: 'appgame onphone posts internet black write read', maybe: 'blue talk screen touch' },
  { id: 'telegram',      icon: '✈️', ar: 'تيليجرام', en: 'Telegram', yes: 'appgame onphone chatapp blue internet talk', maybe: 'watchapp read write screen touch' },
  { id: 'zoom',          icon: '🎥', ar: 'زووم', en: 'Zoom', yes: 'appgame workapp blue internet talk', maybe: 'onphone chatapp school screen' },
  { id: 'youtube',       icon: '▶️', ar: 'يوتيوب', en: 'YouTube', yes: 'appgame onphone watchapp google red internet talk', maybe: 'posts listen white screen touch' },
  { id: 'netflix',       icon: '🎬', ar: 'نتفليكس', en: 'Netflix', yes: 'appgame watchapp red black internet talk', maybe: 'onphone screen byremote' },
  { id: 'shahid',        icon: '📺', ar: 'شاهد', en: 'Shahid', yes: 'arab appgame watchapp internet talk', maybe: 'onphone ramadan screen' },
  { id: 'watchit',       icon: '🎞️', ar: 'واتش إت', en: 'Watch It', yes: 'egypt appgame watchapp internet talk', maybe: 'onphone ramadan screen' },
  /* ---------- apps: music, questions, work ---------- */
  { id: 'spotify',       icon: '🎧', ar: 'سبوتيفاي', en: 'Spotify', yes: 'appgame onphone listen green black internet', maybe: 'screen touch' },
  { id: 'anghami',       icon: '🎶', ar: 'أنغامي', en: 'Anghami', yes: 'arab appgame onphone listen internet', maybe: 'screen touch' },
  { id: 'shazam',        icon: '🎼', ar: 'شازام', en: 'Shazam', yes: 'appgame onphone listen blue internet', maybe: 'askapp screen touch' },
  { id: 'google',        icon: '🔍', ar: 'جوجل', en: 'Google', yes: 'appgame google askapp internet colorful', maybe: 'onphone read school workapp blue screen touch' },
  { id: 'googlemaps',    icon: '📍', ar: 'جوجل مابس', en: 'Google Maps', yes: 'appgame onphone google mapapp internet', maybe: 'colorful street travel screen touch' },
  { id: 'gmail',         icon: '📧', ar: 'جيميل', en: 'Gmail', yes: 'appgame google write workapp internet', maybe: 'red colorful onphone white read screen' },
  { id: 'googletranslate', icon: '🌐', ar: 'جوجل ترانسليت', en: 'Google Translate', yes: 'appgame google internet blue write', maybe: 'onphone school workapp askapp read talk screen' },
  { id: 'wikipedia',     icon: '📚', ar: 'ويكيبيديا', en: 'Wikipedia', yes: 'appgame internet read', maybe: 'white black askapp school workapp onphone screen' },
  { id: 'chatgpt',       icon: '🤖', ar: 'شات جي بي تي', en: 'ChatGPT', yes: 'appgame askapp internet write', maybe: 'black white onphone workapp school chatapp talk screen' },
  { id: 'duolingo',      icon: '🦉', ar: 'دولينجو', en: 'Duolingo', yes: 'appgame onphone green workapp internet', maybe: 'school puzzle screen touch' },
  { id: 'word',          icon: '📝', ar: 'وورد', en: 'Microsoft Word', yes: 'appgame workapp write blue', maybe: 'onphone school read screen' },
  { id: 'excel',         icon: '📊', ar: 'إكسل', en: 'Microsoft Excel', yes: 'appgame workapp green', maybe: 'onphone write school square screen' },
  { id: 'photoshop',     icon: '🖌️', ar: 'فوتوشوب', en: 'Photoshop', yes: 'appgame workapp blue', maybe: 'colorful screen' },
  /* ---------- apps: money, rides, food, shopping ---------- */
  { id: 'instapay',      icon: '💸', ar: 'إنستاباي', en: 'InstaPay', yes: 'egypt appgame onphone payapp internet', maybe: 'screen touch' },
  { id: 'vodafonecash',  icon: '📲', ar: 'فودافون كاش', en: 'Vodafone Cash', yes: 'appgame onphone payapp red', maybe: 'egypt internet screen touch' },
  { id: 'fawry',         icon: '🧾', ar: 'فوري', en: 'Fawry', yes: 'egypt appgame payapp street', maybe: 'onphone internet blue yellow screen' },
  { id: 'uber',          icon: '🚕', ar: 'أوبر', en: 'Uber', yes: 'appgame onphone orderapp black internet', maybe: 'mapapp fare screen touch' },
  { id: 'careem',        icon: '🚗', ar: 'كريم', en: 'Careem', yes: 'arab appgame onphone orderapp green internet', maybe: 'mapapp fare screen touch' },
  { id: 'indrive',       icon: '🚙', ar: 'إن درايف', en: 'inDrive', yes: 'appgame onphone orderapp internet', maybe: 'green mapapp fare screen touch' },
  { id: 'talabat',       icon: '🛵', ar: 'طلبات', en: 'Talabat', yes: 'arab appgame onphone orderapp orange internet', maybe: 'shopapp screen touch' },
  { id: 'amazon',        icon: '📦', ar: 'أمازون', en: 'Amazon', yes: 'appgame shopapp orange internet', maybe: 'onphone black screen' },
  { id: 'noon',          icon: '🛒', ar: 'نون', en: 'noon', yes: 'arab appgame shopapp yellow internet', maybe: 'onphone screen' },
  { id: 'shein',         icon: '👗', ar: 'شي إن', en: 'SHEIN', yes: 'appgame shopapp black internet', maybe: 'onphone wear screen touch' },
] };
