/* العرّاف: characters from cartoons, films, tales and games (kind 'c'). One line each: id, icon,
   ar, en, and the question ids (OracleQuestions.js) that are true (yes), partly (maybe) and
   firmly not (no). Every character says whether it is human (in yes, maybe or no). A question
   about characters in none of the three reads as «غالباً لأ». notes/games/oracle.md, "Writing
   entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_CHARACTERS = { kind: 'c', list: [
  { id: 'mickey',     icon: '🐭', ar: 'ميكي ماوس', en: 'Mickey Mouse', yes: 'animal mammal mouse cartoon disney black bigears tail classic', maybe: 'red duo series_c', no: 'human' },
  { id: 'minnie',     icon: '🎀', ar: 'ميني ماوس', en: 'Minnie Mouse', yes: 'animal mammal mouse cartoon disney female bigears black classic', maybe: 'pink red duo series_c', no: 'human' },
  { id: 'donald',     icon: '🦆', ar: 'بطوط', en: 'Donald Duck', yes: 'animal bird cartoon disney white hat classic', maybe: 'blue series_c', no: 'human' },
  { id: 'tom',        icon: '🐱', ar: 'توم (توم وجيري)', en: 'Tom (Tom and Jerry)', yes: 'animal mammal cat cartoon gray tail duo classic series_c', maybe: 'legs4', no: 'human disney' },
  { id: 'jerry',      icon: '🐭', ar: 'جيري (توم وجيري)', en: 'Jerry (Tom and Jerry)', yes: 'animal mammal mouse cartoon brown duo tail classic series_c', maybe: 'bigears', no: 'human disney' },
  { id: 'spongebob',  icon: '🧽', ar: 'سبونج بوب', en: 'SpongeBob', yes: 'cartoon yellow water kidshow series_c', maybe: 'animal duo classic', no: 'human' },
  { id: 'patrick',    icon: '⭐', ar: 'بسيط (صاحب سبونج بوب)', en: 'Patrick Star', yes: 'cartoon pink water kidshow series_c', maybe: 'animal duo classic', no: 'human' },
  { id: 'bugsbunny',  icon: '🐰', ar: 'باجز باني', en: 'Bugs Bunny', yes: 'animal mammal cartoon gray bigears classic', maybe: 'white series_c comedy', no: 'human' },
  { id: 'popeye',     icon: '⚓', ar: 'باباي', en: 'Popeye', yes: 'human cartoon hat classic', maybe: 'powers fighter series_c' },
  { id: 'pinkpanther', icon: '🐆', ar: 'النمر الوردي', en: 'The Pink Panther', yes: 'animal cat cartoon pink tail classic', maybe: 'series_c comedy', no: 'human' },
  { id: 'garfield',   icon: '🐱', ar: 'جارفيلد', en: 'Garfield', yes: 'animal mammal cat cartoon orange stripes tail classic', maybe: 'legs4 series_c comedy', no: 'human' },
  { id: 'scooby',     icon: '🐶', ar: 'سكوبي دو', en: 'Scooby-Doo', yes: 'animal mammal dog cartoon brown spots detective legs4 tail classic series_c', maybe: 'group', no: 'human' },
  { id: 'simba',      icon: '🦁', ar: 'سيمبا (الأسد الملك)', en: 'Simba (The Lion King)', yes: 'animal mammal cat cartoon disney ruler legs4 tail classic', maybe: 'yellow child', no: 'human series_c' },
  { id: 'aladdin',    icon: '🪔', ar: 'علاء الدين', en: 'Aladdin', yes: 'human cartoon disney tale arab classic', maybe: 'flies liveaction hat' },
  { id: 'genie',      icon: '🧞', ar: 'جني المصباح', en: 'The Genie of the lamp', yes: 'cartoon disney tale powers blue flies classic', maybe: 'human big arab beard comedy' },
  { id: 'jasmine',    icon: '👸', ar: 'الأميرة ياسمين', en: 'Princess Jasmine', yes: 'human female princess cartoon disney tale arab classic', maybe: 'liveaction' },
  { id: 'cinderella', icon: '👠', ar: 'سندريلا', en: 'Cinderella', yes: 'human female princess cartoon disney tale blue classic' },
  { id: 'snowwhite',  icon: '🍎', ar: 'سنو وايت', en: 'Snow White', yes: 'human female princess cartoon disney tale classic', maybe: 'group', no: 'blue' },
  { id: 'elsa',       icon: '❄️', ar: 'إلسا (فروزن)', en: 'Elsa (Frozen)', yes: 'human female cartoon disney ruler powers blue', maybe: 'princess white duo', no: 'classic series_c' },
  { id: 'ariel',      icon: '🧜‍♀️', ar: 'عروسة البحر (آرييل)', en: 'Ariel (The Little Mermaid)', yes: 'female princess cartoon disney water classic', maybe: 'human fish red tale tail' },
  { id: 'pooh',       icon: '🍯', ar: 'ويني الدبدوب', en: 'Winnie the Pooh', yes: 'animal mammal cartoon disney yellow classic', maybe: 'toy kidshow', no: 'human' },
  { id: 'shrek',      icon: '👹', ar: 'شريك', en: 'Shrek', yes: 'cartoon green big', maybe: 'comedy', no: 'human villain disney classic' },
  { id: 'woody',      icon: '🤠', ar: 'وودي (حكاية لعبة)', en: 'Woody (Toy Story)', yes: 'cartoon disney toy hat classic', maybe: 'human duo brown' },
  { id: 'buzz',       icon: '🚀', ar: 'باز يطير (حكاية لعبة)', en: 'Buzz Lightyear', yes: 'cartoon disney toy classic', maybe: 'flies white green robot duo', no: 'human' },
  { id: 'nemo',       icon: '🐠', ar: 'نيمو', en: 'Nemo', yes: 'animal fish water cartoon disney orange white stripes child', no: 'human classic' },
  { id: 'mcqueen',    icon: '🏎️', ar: 'ماكوين (عربيات)', en: 'Lightning McQueen (Cars)', yes: 'cartoon disney robot vehicle wheels red', no: 'human animal classic' },
  { id: 'mario',      icon: '🍄', ar: 'ماريو', en: 'Mario', yes: 'human videogame hat red beard classic', maybe: 'cartoon blue duo' },
  { id: 'sonic',      icon: '🦔', ar: 'سونيك', en: 'Sonic', yes: 'animal videogame blue classic', maybe: 'mammal cartoon', no: 'human' },
  { id: 'pikachu',    icon: '⚡', ar: 'بيكاتشو', en: 'Pikachu', yes: 'animal anime cartoon yellow powers classic', maybe: 'videogame tail mammal series_c', no: 'human' },
  { id: 'pacman',     icon: '🟡', ar: 'باك مان', en: 'Pac-Man', yes: 'videogame yellow classic', maybe: 'cartoon', no: 'human animal' },
  { id: 'majed',      icon: '⚽', ar: 'كابتن ماجد', en: 'Captain Majed (Tsubasa)', yes: 'human anime cartoon football classic series_c', maybe: 'child kidshow' },
  { id: 'grendizer',  icon: '🤖', ar: 'جريندايزر', en: 'Grendizer', yes: 'anime cartoon robot flies big warrior classic series_c alien', maybe: 'hero powers weapon', no: 'human animal' },
  { id: 'conan',      icon: '🔎', ar: 'المحقق كونان', en: 'Detective Conan', yes: 'human anime cartoon detective child classic series_c glasses', maybe: 'kidshow' },
  { id: 'smurf',      icon: '🍄', ar: 'سنفور (السنافر)', en: 'A Smurf', yes: 'cartoon blue group hat classic series_c', maybe: 'white kidshow', no: 'animal human' },
  { id: 'superman',   icon: '🦸', ar: 'سوبرمان', en: 'Superman', yes: 'human hero powers flies blue red classic cape alien', maybe: 'liveaction cartoon' },
  { id: 'batman',     icon: '🦇', ar: 'باتمان', en: 'Batman', yes: 'human hero mask black classic cape', maybe: 'liveaction cartoon', no: 'powers' },
  { id: 'spiderman',  icon: '🕷️', ar: 'سبايدر مان', en: 'Spider-Man', yes: 'human hero powers mask red blue classic', maybe: 'liveaction cartoon', no: 'cape' },
  { id: 'hulk',       icon: '💪', ar: 'هالك', en: 'Hulk', yes: 'human hero powers green big classic', maybe: 'liveaction' },
  { id: 'ironman',    icon: '🦾', ar: 'أيرون مان', en: 'Iron Man', yes: 'human hero flies red liveaction', maybe: 'yellow mask robot classic beard' },
  { id: 'harrypotter', icon: '🪄', ar: 'هاري بوتر', en: 'Harry Potter', yes: 'human liveaction powers glasses', maybe: 'child flies classic' },
  { id: 'sherlock',   icon: '🔍', ar: 'شيرلوك هولمز', en: 'Sherlock Holmes', yes: 'human detective liveaction classic', maybe: 'hat duo series_c' },
  { id: 'pinocchio',  icon: '🤥', ar: 'بينوكيو', en: 'Pinocchio', yes: 'toy tale child classic', maybe: 'cartoon disney human' },
  { id: 'peterpan',   icon: '🧚', ar: 'بيتر بان', en: 'Peter Pan', yes: 'human child flies classic', maybe: 'cartoon disney tale green hat' },
  { id: 'tarzan',     icon: '🌴', ar: 'طرزان', en: 'Tarzan', yes: 'human cartoon disney classic', maybe: 'tale liveaction' },
  { id: 'mrbean',     icon: '🤓', ar: 'مستر بين', en: 'Mr. Bean', yes: 'human liveaction comedy classic series_c', maybe: 'cartoon' },
  { id: 'bakkar',     icon: '🐐', ar: 'بكار', en: 'Bakkar', yes: 'human egypt cartoon child kidshow classic series_c ramadan_c', maybe: 'duo' },
  { id: 'boogie',     icon: '🧸', ar: 'بوجي وطمطم', en: 'Boogie and Tamtam', yes: 'egypt kidshow duo toy classic series_c ramadan_c', maybe: 'animal', no: 'human cartoon' },
  { id: 'alibaba',    icon: '💰', ar: 'علي بابا', en: 'Ali Baba', yes: 'human tale arab classic', maybe: 'cartoon beard' },
  { id: 'sindbad',    icon: '⛵', ar: 'سندباد', en: 'Sinbad', yes: 'human tale arab explorer classic', maybe: 'water cartoon beard' },
  { id: 'shahrazad',  icon: '📜', ar: 'شهرزاد', en: 'Scheherazade', yes: 'human female tale arab classic', maybe: 'ruler' },
  { id: 'goha',       icon: '🫏', ar: 'جحا', en: 'Goha', yes: 'human tale arab comedy classic beard', maybe: 'egypt hat old' },
  { id: 'fattouta',   icon: '🟢', ar: 'فطوطة', en: 'Fattouta', yes: 'human egypt liveaction comedy fawazeer classic series_c ramadan_c', maybe: 'kidshow' },
  { id: 'lembi',      icon: '😄', ar: 'اللمبي', en: 'El Lembi', yes: 'human egypt liveaction comedy', no: 'kidshow fawazeer classic series_c' },
  { id: 'turtles',    icon: '🐢', ar: 'سلاحف النينجا', en: 'The Ninja Turtles', yes: 'animal reptile shell green group mask cartoon hero classic weapon', maybe: 'warrior fighter series_c', no: 'human' },
  { id: 'peppa',      icon: '🐷', ar: 'ببا بيج', en: 'Peppa Pig', yes: 'animal mammal cartoon kidshow pink female child series_c', no: 'human classic' },
  { id: 'dora',       icon: '🎒', ar: 'دورا', en: 'Dora', yes: 'human female cartoon kidshow child series_c', no: 'classic' },
  { id: 'masha',      icon: '👧', ar: 'ماشا والدب', en: 'Masha and the Bear', yes: 'human female cartoon kidshow child duo series_c', no: 'classic' },
  { id: 'minions',    icon: '🍌', ar: 'المينيونز', en: 'The Minions', yes: 'cartoon yellow group', maybe: 'blue glasses comedy', no: 'human animal classic' },
  { id: 'doraemon',   icon: '🔔', ar: 'دورايمون', en: 'Doraemon', yes: 'anime cartoon robot blue classic series_c', maybe: 'animal powers kidshow cat', no: 'human' },
  { id: 'tweety',     icon: '🐤', ar: 'تويتي', en: 'Tweety', yes: 'animal bird cartoon yellow flies classic', maybe: 'child', no: 'human' },
  { id: 'olaf',       icon: '⛄', ar: 'أولاف (فروزن)', en: 'Olaf (Frozen)', yes: 'cartoon disney white', maybe: 'comedy', no: 'human animal classic' },
  { id: 'po',         icon: '🐼', ar: 'بو (كونج فو باندا)', en: 'Po (Kung Fu Panda)', yes: 'animal mammal cartoon fighter black white', maybe: 'warrior big comedy', no: 'human classic' },
  { id: 'heidi',      icon: '⛰️', ar: 'هايدي', en: 'Heidi', yes: 'human female cartoon anime child classic series_c', maybe: 'kidshow' },
  { id: 'jafar',      icon: '🐍', ar: 'جعفر (علاء الدين)', en: 'Jafar (Aladdin)', yes: 'human villain cartoon disney tale arab powers classic beard', maybe: 'hat old' },
  { id: 'scar',       icon: '🦁', ar: 'سكار (الأسد الملك)', en: 'Scar (The Lion King)', yes: 'animal mammal cat villain cartoon disney legs4 tail classic', maybe: 'brown ruler', no: 'human' },
  { id: 'joker',      icon: '🃏', ar: 'الجوكر', en: 'The Joker', yes: 'human villain classic', maybe: 'liveaction cartoon green' },
  { id: 'gargamel',   icon: '🧙', ar: 'شرشبيل (السنافر)', en: 'Gargamel (The Smurfs)', yes: 'human villain cartoon powers classic series_c', maybe: 'kidshow black old' },
  { id: 'hook',       icon: '🪝', ar: 'كابتن هوك', en: 'Captain Hook', yes: 'human villain hat classic beard weapon', maybe: 'cartoon disney red water' },
  { id: 'dumbo',      icon: '🐘', ar: 'دامبو', en: 'Dumbo', yes: 'animal mammal cartoon disney flies bigears gray classic', maybe: 'child big', no: 'human' },

  /* ---------- phase 2 (9 Oct 2026): Egyptian and Arab, Ramadan, films and series ---------- */
  { id: 'zaza',       icon: '🥬', ar: 'ظاظا وجرجير', en: 'Zaza and Gargir', yes: 'egypt kidshow duo series_c', maybe: 'cartoon human classic ramadan_c' },
  { id: 'rashida',    icon: '🐐', ar: 'رشيدة (معزة بكار)', en: "Rashida (Bakkar's goat)", yes: 'animal mammal cartoon egypt kidshow female series_c ramadan_c classic legs4 duo', no: 'human' },
  { id: 'wanis',      icon: '👨‍👩‍👧', ar: 'ونيس (يوميات ونيس)', en: 'Wanis (The Diaries of Wanis)', yes: 'human egypt liveaction comedy series_c ramadan_c classic', maybe: 'old', no: 'cartoon villain kidshow' },
  { id: 'kabeer',     icon: '👳', ar: 'الكبير أوي', en: 'El Kabeer Awi', yes: 'human egypt liveaction comedy series_c ramadan_c', maybe: 'beard ruler', no: 'classic cartoon' },
  { id: 'ramadanmabrouk', icon: '📚', ar: 'رمضان مبروك أبو العلمين حمودة', en: 'Ramadan Mabrouk Abul-Alamein Hamouda', yes: 'human egypt liveaction comedy beard', no: 'series_c classic cartoon' },
  { id: 'sisayed',    icon: '🎩', ar: 'سي السيد', en: 'Si El-Sayed', yes: 'human egypt liveaction classic beard', maybe: 'old series_c', no: 'comedy cartoon' },
  { id: 'sheikhhosny', icon: '🕶️', ar: 'الشيخ حسني (الكيت كات)', en: 'Sheikh Hosny (Kit Kat)', yes: 'human egypt liveaction classic', maybe: 'old glasses comedy', no: 'series_c cartoon' },
  { id: 'sonbol',     icon: '🎒', ar: 'سنبل', en: 'Sonbol', yes: 'human egypt liveaction comedy classic series_c', no: 'cartoon' },
  { id: 'amofouad',   icon: '👴', ar: 'عمو فؤاد', en: 'Uncle Fouad', yes: 'human egypt liveaction comedy kidshow ramadan_c classic series_c', maybe: 'old glasses', no: 'cartoon' },
  { id: 'adham',      icon: '🔫', ar: 'أدهم صبري (رجل المستحيل)', en: 'Adham Sabri (The Man of the Impossible)', yes: 'human egypt weapon fighter classic', maybe: 'detective hero', no: 'liveaction cartoon comedy' },
  { id: 'baqlaz',     icon: '🧸', ar: 'بقلظ (ماما نجوى)', en: 'Baqlaz', yes: 'egypt kidshow toy duo classic series_c', maybe: 'human comedy', no: 'cartoon' },
  { id: 'shaterhassan', icon: '🗡️', ar: 'الشاطر حسن', en: 'Clever Hassan', yes: 'human tale egypt classic', maybe: 'child cartoon', no: 'female liveaction villain' },
  { id: 'ghoula',     icon: '👹', ar: 'أمنا الغولة', en: 'The Ogress (Ommena el-Ghoula)', yes: 'villain tale female powers egypt classic', maybe: 'old big', no: 'human' },
  { id: 'shahryar',   icon: '👑', ar: 'شهريار', en: 'Shahryar', yes: 'human ruler tale arab classic beard', maybe: 'duo' },
  { id: 'fortythieves', icon: '🗝️', ar: 'الأربعين حرامي', en: 'The Forty Thieves', yes: 'human tale arab villain group classic weapon', maybe: 'beard' },
  { id: 'kalila',     icon: '🦊', ar: 'كليلة ودمنة', en: 'Kalila and Dimna', yes: 'animal mammal tale arab duo classic legs4 tail', maybe: 'brown dog', no: 'human' },

  /* ---------- anime known in Egypt ---------- */
  { id: 'adnanconan', icon: '🏝️', ar: 'عدنان (عدنان ولينا)', en: 'Adnan (Future Boy Conan)', yes: 'human anime cartoon child series_c classic duo', maybe: 'water' },
  { id: 'lanaconan',  icon: '🌸', ar: 'لينا (عدنان ولينا)', en: 'Lana (Future Boy Conan)', yes: 'human female anime cartoon child series_c classic duo' },
  { id: 'remianime',  icon: '🎻', ar: 'ريمي', en: "Remi (Nobody's Boy)", yes: 'human anime cartoon child series_c classic hat' },
  { id: 'tigermask',  icon: '🐯', ar: 'النمر المقنع', en: 'Tiger Mask', yes: 'human anime cartoon fighter mask classic series_c', maybe: 'hero athlete' },
  { id: 'nils',       icon: '🪿', ar: 'نيلز', en: 'Nils Holgersson', yes: 'human anime cartoon child series_c classic flies', maybe: 'duo' },
  { id: 'mayabee',    icon: '🐝', ar: 'زينة النحلة', en: 'Maya the Bee', yes: 'animal insect flies anime cartoon female yellow black stripes series_c classic kidshow', no: 'human' },
  { id: 'bellesebastian', icon: '🐕', ar: 'بيل وسبستيان', en: 'Belle and Sebastian', yes: 'anime cartoon dog white duo series_c classic', maybe: 'human animal child big' },
  { id: 'mazinger',   icon: '🦾', ar: 'مازنجر', en: 'Mazinger Z', yes: 'anime cartoon robot big warrior classic series_c black', maybe: 'flies hero gray weapon', no: 'human animal alien' },
  { id: 'goku',       icon: '🐉', ar: 'جوكو (دراجون بول)', en: 'Goku (Dragon Ball)', yes: 'anime cartoon fighter powers alien series_c classic flies', maybe: 'human orange warrior' },
  { id: 'naruto',     icon: '🍥', ar: 'ناروتو', en: 'Naruto', yes: 'human anime cartoon fighter powers series_c orange', maybe: 'child classic warrior weapon' },
  { id: 'luffy',      icon: '👒', ar: 'لوفي (ون بيس)', en: 'Luffy (One Piece)', yes: 'human anime cartoon hat powers series_c classic', maybe: 'red fighter water' },
  { id: 'ashketchum', icon: '🧢', ar: 'آش (بوكيمون)', en: 'Ash (Pokémon)', yes: 'human anime cartoon child hat series_c classic duo', maybe: 'kidshow videogame' },
  { id: 'sailormoon', icon: '🌙', ar: 'سيلور مون', en: 'Sailor Moon', yes: 'human female anime cartoon powers hero series_c classic', maybe: 'child group' },

  /* ---------- Disney and Pixar ---------- */
  { id: 'goofy',      icon: '🐕', ar: 'جوفي', en: 'Goofy', yes: 'animal dog cartoon disney classic hat comedy', maybe: 'bigears series_c', no: 'human' },
  { id: 'plutodog',   icon: '🦴', ar: 'بلوتو (كلب ميكي)', en: "Pluto (Mickey's dog)", yes: 'animal dog cartoon disney classic legs4 tail yellow', maybe: 'orange', no: 'human' },
  { id: 'daisyduck',  icon: '🦆', ar: 'ديزي (صاحبة بطوط)', en: 'Daisy Duck', yes: 'animal bird cartoon disney classic female white', maybe: 'pink duo', no: 'human' },
  { id: 'belle',      icon: '🌹', ar: 'بيل (الجميلة والوحش)', en: 'Belle (Beauty and the Beast)', yes: 'human female cartoon disney classic yellow', maybe: 'princess liveaction duo tale' },
  { id: 'thebeast',   icon: '🥀', ar: 'الوحش (الجميلة والوحش)', en: 'The Beast (Beauty and the Beast)', yes: 'cartoon disney classic big brown', maybe: 'human animal ruler liveaction duo tale' },
  { id: 'sleepingbeauty', icon: '💤', ar: 'الأميرة النائمة', en: 'Sleeping Beauty (Aurora)', yes: 'human princess cartoon disney classic tale pink', maybe: 'blue liveaction', no: 'series_c powers' },
  { id: 'rapunzel',   icon: '👱‍♀️', ar: 'رابونزل', en: 'Rapunzel (Tangled)', yes: 'human princess cartoon disney tale', maybe: 'pink', no: 'classic' },
  { id: 'moana',      icon: '🌊', ar: 'موانا', en: 'Moana', yes: 'human female cartoon disney', maybe: 'princess ruler', no: 'classic' },
  { id: 'mulan',      icon: '⚔️', ar: 'مولان', en: 'Mulan', yes: 'human female cartoon disney warrior weapon classic', maybe: 'princess liveaction fighter' },
  { id: 'pocahontas', icon: '🍃', ar: 'بوكاهونتس', en: 'Pocahontas', yes: 'human female cartoon disney classic', maybe: 'princess brown' },
  { id: 'maleficent', icon: '🖤', ar: 'ماليفسنت (الساحرة الشريرة)', en: 'Maleficent', yes: 'villain female cartoon disney powers classic black', maybe: 'liveaction human tale' },
  { id: 'ursula',     icon: '🐙', ar: 'أورسولا (عروسة البحر)', en: 'Ursula (The Little Mermaid)', yes: 'villain female cartoon disney powers water classic big', maybe: 'human' },
  { id: 'cruella',    icon: '🧥', ar: 'كرويلا', en: 'Cruella de Vil', yes: 'human villain female cartoon disney classic', maybe: 'liveaction white black' },
  { id: 'dalmatians', icon: '🐶', ar: 'الـ101 كلب دلماسي', en: '101 Dalmatians', yes: 'animal dog cartoon disney classic white black spots group legs4', no: 'human' },
  { id: 'stitch',     icon: '👽', ar: 'ستيتش', en: 'Stitch', yes: 'cartoon disney alien blue bigears', maybe: 'animal duo', no: 'human classic' },
  { id: 'bambi',      icon: '🦌', ar: 'بامبي', en: 'Bambi', yes: 'animal mammal cartoon disney classic brown spots child legs4', no: 'human' },
  { id: 'mowgli',     icon: '🌿', ar: 'ماوكلي', en: 'Mowgli (The Jungle Book)', yes: 'human child cartoon disney classic', maybe: 'tale liveaction anime' },
  { id: 'baloo',      icon: '🐻', ar: 'بالو (كتاب الأدغال)', en: 'Baloo (The Jungle Book)', yes: 'animal mammal cartoon disney classic big gray', maybe: 'duo comedy', no: 'human' },
  { id: 'sherekhan',  icon: '🐅', ar: 'شير خان', en: 'Shere Khan', yes: 'animal cat cartoon disney classic villain stripes orange legs4 tail', no: 'human' },
  { id: 'timon',      icon: '🦦', ar: 'تيمون', en: 'Timon (The Lion King)', yes: 'animal mammal cartoon disney classic duo tail', maybe: 'brown comedy', no: 'human' },
  { id: 'pumbaa',     icon: '🐗', ar: 'بومبا', en: 'Pumbaa (The Lion King)', yes: 'animal mammal cartoon disney classic duo legs4 brown comedy', maybe: 'big', no: 'human' },
  { id: 'mufasa',     icon: '🦁', ar: 'موفاسا', en: 'Mufasa (The Lion King)', yes: 'animal cat cartoon disney classic ruler legs4 tail big', maybe: 'yellow brown', no: 'human' },
  { id: 'walle',      icon: '🤖', ar: 'وول-إي', en: 'WALL-E', yes: 'robot cartoon disney', maybe: 'brown yellow wheels', no: 'human animal classic' },
  { id: 'sulley',     icon: '👾', ar: 'سولي (شركة المرعبين)', en: 'Sulley (Monsters, Inc.)', yes: 'cartoon disney big blue spots duo', maybe: 'animal', no: 'human classic' },
  { id: 'mikewazowski', icon: '👁️', ar: 'مايك (شركة المرعبين)', en: 'Mike Wazowski (Monsters, Inc.)', yes: 'cartoon disney green duo comedy', no: 'human classic animal' },
  { id: 'dory',       icon: '🐟', ar: 'دوري', en: 'Dory', yes: 'animal fish water cartoon disney blue yellow female', maybe: 'comedy', no: 'human classic' },
  { id: 'remy',       icon: '🐀', ar: 'الفار ريمي (راتاتوي)', en: 'Remy (Ratatouille)', yes: 'animal mouse cartoon disney gray', maybe: 'tail', no: 'human classic' },
  { id: 'incredible', icon: '💥', ar: 'مستر إنكريديبل (الخارقون)', en: 'Mr. Incredible (The Incredibles)', yes: 'human hero powers cartoon disney big', maybe: 'red mask', no: 'classic' },
  { id: 'mater',      icon: '🛻', ar: 'ماتر (عربيات)', en: 'Mater (Cars)', yes: 'cartoon disney robot vehicle wheels brown duo comedy', no: 'human animal classic' },
  { id: 'jessie',     icon: '🤠', ar: 'جيسي (حكاية لعبة)', en: 'Jessie (Toy Story)', yes: 'cartoon disney toy female hat classic', maybe: 'red human duo' },
  { id: 'tinkerbell', icon: '🧚‍♀️', ar: 'تينكربل', en: 'Tinker Bell', yes: 'female cartoon disney flies powers classic green', maybe: 'human tale' },
  { id: 'jacksparrow', icon: '🏴‍☠️', ar: 'جاك سبارو', en: 'Jack Sparrow', yes: 'human liveaction disney hat weapon beard', maybe: 'comedy', no: 'cartoon classic' },
  { id: 'marypoppins', icon: '☂️', ar: 'ماري بوبينز', en: 'Mary Poppins', yes: 'human female liveaction disney flies powers classic hat', maybe: 'cartoon' },
  { id: 'merida',     icon: '🏹', ar: 'ميريدا (الشجاعة)', en: 'Merida (Brave)', yes: 'human princess cartoon disney weapon', maybe: 'red', no: 'classic' },
  { id: 'herculesdisney', icon: '💪', ar: 'هرقل', en: 'Hercules', yes: 'human cartoon disney powers classic', maybe: 'warrior fighter tale liveaction' },
  { id: 'baymax',     icon: '🤍', ar: 'بايماكس', en: 'Baymax', yes: 'robot cartoon disney white big', no: 'human animal classic' },
  { id: 'judyhopps',  icon: '🐰', ar: 'جودي (زوتوبيا)', en: 'Judy Hopps (Zootopia)', yes: 'animal mammal cartoon disney female bigears gray', maybe: 'detective', no: 'human classic' },
  { id: 'carlup',     icon: '🎈', ar: 'كارل (فوق)', en: 'Carl (Up)', yes: 'human old glasses cartoon disney', maybe: 'flies duo', no: 'classic' },
  { id: 'chipdale',   icon: '🐿️', ar: 'تشيب وديل', en: "Chip 'n Dale", yes: 'animal mammal cartoon disney classic duo brown tail stripes', maybe: 'series_c', no: 'human' },
  { id: 'dwarfs',     icon: '⛏️', ar: 'الأقزام السبعة', en: 'The Seven Dwarfs', yes: 'human cartoon disney classic group hat beard old tale', maybe: 'comedy' },
  { id: 'alice',      icon: '🐇', ar: 'أليس في بلاد العجائب', en: 'Alice in Wonderland', yes: 'human female child cartoon disney classic tale blue', maybe: 'liveaction' },
  { id: 'annafrozen', icon: '❄️', ar: 'آنا (فروزن)', en: 'Anna (Frozen)', yes: 'human princess cartoon disney duo', no: 'classic powers' },
  { id: 'nephews',    icon: '🐥', ar: 'سوسو ولولو وتوتو', en: 'Huey, Dewey and Louie', yes: 'animal bird cartoon disney classic child group hat', no: 'human' },
  { id: 'scrooge',    icon: '💰', ar: 'عم دهب', en: 'Scrooge McDuck', yes: 'animal bird cartoon disney classic old glasses hat', no: 'human' },

  /* ---------- Looney Tunes and other cartoons ---------- */
  { id: 'daffy',      icon: '🦆', ar: 'دافي داك', en: 'Daffy Duck', yes: 'animal bird cartoon classic black comedy', no: 'human disney' },
  { id: 'sylvester',  icon: '🐈‍⬛', ar: 'سيلفستر (قط تويتي)', en: 'Sylvester', yes: 'animal cat cartoon classic black white tail duo', no: 'human disney' },
  { id: 'roadrunner', icon: '🐦', ar: 'رود رنر', en: 'Road Runner', yes: 'animal bird cartoon classic blue duo', no: 'human disney flies' },
  { id: 'coyote',     icon: '🐺', ar: 'ويلي كايوتي (رود رنر)', en: 'Wile E. Coyote', yes: 'animal mammal cartoon classic brown duo tail', maybe: 'villain', no: 'human disney dog' },
  { id: 'speedy',     icon: '🐭', ar: 'سبيدي جونزاليس', en: 'Speedy Gonzales', yes: 'animal mouse cartoon classic hat', maybe: 'white', no: 'human disney' },
  { id: 'porky',      icon: '🐷', ar: 'بوركي بيج', en: 'Porky Pig', yes: 'animal mammal cartoon classic pink', maybe: 'comedy', no: 'human disney' },
  { id: 'taz',        icon: '🌪️', ar: 'تاز', en: 'Taz (the Tasmanian Devil)', yes: 'animal mammal cartoon classic brown', maybe: 'villain', no: 'human disney' },
  { id: 'woodywoodpecker', icon: '🐦', ar: 'نقار الخشب وودي', en: 'Woody Woodpecker', yes: 'animal bird cartoon classic red blue comedy', maybe: 'flies', no: 'human disney' },
  { id: 'snoopy',     icon: '🐶', ar: 'سنوبي', en: 'Snoopy', yes: 'animal dog cartoon classic white black', maybe: 'duo flies', no: 'human disney' },
  { id: 'odie',       icon: '🐕', ar: 'أودي (كلب جارفيلد)', en: "Odie (Garfield's dog)", yes: 'animal dog cartoon classic yellow bigears duo', no: 'human disney' },
  { id: 'spikedog',   icon: '🐕', ar: 'سبايك (كلب توم وجيري)', en: 'Spike (Tom and Jerry)', yes: 'animal dog cartoon classic gray series_c', maybe: 'big', no: 'human disney' },
  { id: 'casper',     icon: '👻', ar: 'كاسبر', en: 'Casper', yes: 'cartoon classic white flies child', maybe: 'human liveaction' },
  { id: 'tintin',     icon: '📰', ar: 'تان تان', en: 'Tintin', yes: 'human cartoon classic detective', maybe: 'duo explorer series_c' },
  { id: 'asterix',    icon: '🪖', ar: 'أستريكس', en: 'Asterix', yes: 'human cartoon classic warrior powers beard hat duo', maybe: 'fighter liveaction' },
  { id: 'obelix',     icon: '🪨', ar: 'أوبليكس', en: 'Obelix', yes: 'human cartoon classic big duo warrior powers beard', maybe: 'comedy stripes liveaction' },
  { id: 'luckyluke',  icon: '🤠', ar: 'لاكي لوك', en: 'Lucky Luke', yes: 'human cartoon classic hat weapon', maybe: 'yellow series_c' },
  { id: 'homersimpson', icon: '🍩', ar: 'هومر سيمبسون', en: 'Homer Simpson', yes: 'human cartoon series_c classic yellow comedy', maybe: 'old' },
  { id: 'bartsimpson', icon: '🛹', ar: 'بارت سيمبسون', en: 'Bart Simpson', yes: 'human cartoon series_c classic yellow comedy child' },
  { id: 'fredflintstone', icon: '🦴', ar: 'فريد فلينستون', en: 'Fred Flintstone', yes: 'human cartoon series_c classic comedy', maybe: 'orange' },
  { id: 'squidward',  icon: '🦑', ar: 'شفيق (سبونج بوب)', en: 'Squidward (SpongeBob)', yes: 'cartoon water kidshow series_c', maybe: 'animal green blue classic', no: 'human' },
  { id: 'krabs',      icon: '🦀', ar: 'السيد سلطع (سبونج بوب)', en: 'Mr. Krabs (SpongeBob)', yes: 'animal cartoon water kidshow series_c red shell', maybe: 'classic', no: 'human' },
  { id: 'planktonsb', icon: '🦠', ar: 'بلانكتون (سبونج بوب)', en: 'Plankton (SpongeBob)', yes: 'cartoon water kidshow series_c villain green', maybe: 'animal classic', no: 'human' },
  { id: 'oggy',       icon: '🐈', ar: 'أوجي (أوجي والصراصير)', en: 'Oggy (Oggy and the Cockroaches)', yes: 'animal cat cartoon series_c blue', maybe: 'comedy classic', no: 'human disney' },
  { id: 'oggyroaches', icon: '🪳', ar: 'الصراصير (أوجي والصراصير)', en: 'The Cockroaches (Oggy)', yes: 'animal insect cartoon series_c villain', maybe: 'comedy classic group', no: 'human' },
  { id: 'shaunsheep', icon: '🐑', ar: 'شون الخروف', en: 'Shaun the Sheep', yes: 'animal mammal cartoon series_c white kidshow', maybe: 'black legs4', no: 'human' },
  { id: 'thomastrain', icon: '🚂', ar: 'توماس (القطر)', en: 'Thomas the Tank Engine', yes: 'robot vehicle wheels blue kidshow series_c classic big', maybe: 'cartoon', no: 'human animal' },
  { id: 'pingu',      icon: '🐧', ar: 'بينجو', en: 'Pingu', yes: 'animal bird kidshow series_c classic black white', maybe: 'cartoon', no: 'human flies' },
  { id: 'bobbuilder', icon: '👷', ar: 'بوب البنّا', en: 'Bob the Builder', yes: 'human kidshow series_c hat classic', maybe: 'cartoon yellow' },
  { id: 'ben10',      icon: '⌚', ar: 'بن تن', en: 'Ben 10', yes: 'human cartoon child powers hero series_c green', no: 'classic' },
  { id: 'barbie',     icon: '💗', ar: 'باربي', en: 'Barbie', yes: 'toy female pink classic', maybe: 'human cartoon liveaction princess' },
  { id: 'powerpuff',  icon: '💥', ar: 'فتيات القوة', en: 'The Powerpuff Girls', yes: 'female cartoon hero powers flies child group series_c classic', maybe: 'human' },
  { id: 'hellokitty', icon: '🎀', ar: 'هيلو كيتي', en: 'Hello Kitty', yes: 'animal cat cartoon female white classic', maybe: 'kidshow pink', no: 'human' },
  { id: 'miraculousladybug', icon: '🐞', ar: 'ليدي باج (ميراكولوس)', en: 'Ladybug (Miraculous)', yes: 'human female hero powers mask red black spots cartoon series_c', no: 'classic' },

  /* ---------- superheroes ---------- */
  { id: 'wonderwoman', icon: '🦸‍♀️', ar: 'وندر وومان', en: 'Wonder Woman', yes: 'human female hero powers classic liveaction', maybe: 'cartoon weapon red blue warrior' },
  { id: 'captainamerica', icon: '🛡️', ar: 'كابتن أمريكا', en: 'Captain America', yes: 'human hero classic liveaction blue red white', maybe: 'cartoon mask weapon powers warrior' },
  { id: 'thor',       icon: '🔨', ar: 'ثور', en: 'Thor', yes: 'hero powers liveaction weapon flies classic beard', maybe: 'human alien cape red warrior' },
  { id: 'blackpanther', icon: '🐾', ar: 'بلاك بانثر', en: 'Black Panther', yes: 'human hero mask black liveaction ruler', maybe: 'powers classic' },
  { id: 'theflash',   icon: '⚡', ar: 'فلاش', en: 'The Flash', yes: 'human hero powers red mask', maybe: 'classic liveaction cartoon yellow' },
  { id: 'aquaman',    icon: '🔱', ar: 'أكوامان', en: 'Aquaman', yes: 'human hero powers water liveaction beard weapon', maybe: 'classic ruler' },
  { id: 'wolverine',  icon: '🐺', ar: 'وولفرين', en: 'Wolverine', yes: 'human hero powers liveaction fighter', maybe: 'weapon classic yellow beard' },
  { id: 'drstrange',  icon: '🌀', ar: 'دكتور سترينج', en: 'Doctor Strange', yes: 'human hero powers liveaction cape beard', maybe: 'classic red' },
  { id: 'thanos',     icon: '🧤', ar: 'ثانوس', en: 'Thanos', yes: 'villain alien powers big liveaction', maybe: 'human' },
  { id: 'optimus',    icon: '🚛', ar: 'أوبتيموس برايم (المتحولون)', en: 'Optimus Prime (Transformers)', yes: 'robot vehicle wheels alien big red blue liveaction classic', maybe: 'cartoon hero warrior', no: 'human' },
  { id: 'bumblebeecar', icon: '🚗', ar: 'بامبلبي (المتحولون)', en: 'Bumblebee (Transformers)', yes: 'robot vehicle wheels alien yellow liveaction classic', maybe: 'cartoon black hero', no: 'human animal' },

  /* ---------- video games ---------- */
  { id: 'luigi',      icon: '🍄', ar: 'لويجي', en: 'Luigi', yes: 'human videogame hat green beard classic duo', maybe: 'blue cartoon' },
  { id: 'princesspeach', icon: '👑', ar: 'الأميرة بيتش', en: 'Princess Peach', yes: 'human princess videogame pink classic', maybe: 'cartoon' },
  { id: 'bowser',     icon: '🐲', ar: 'باوزر', en: 'Bowser', yes: 'villain videogame big shell classic ruler', maybe: 'animal reptile green', no: 'human' },
  { id: 'yoshi',      icon: '🦖', ar: 'يوشي', en: 'Yoshi', yes: 'animal videogame green classic', maybe: 'reptile', no: 'human' },
  { id: 'zeldalink',  icon: '🗡️', ar: 'لينك (زيلدا)', en: 'Link (Zelda)', yes: 'human videogame green hat weapon classic', maybe: 'warrior' },
  { id: 'donkeykong', icon: '🦍', ar: 'دونكي كونج', en: 'Donkey Kong', yes: 'animal mammal videogame big brown classic', maybe: 'cartoon', no: 'human' },
  { id: 'laracroft',  icon: '🏺', ar: 'لارا كروفت', en: 'Lara Croft', yes: 'human female videogame weapon classic liveaction explorer' },
  { id: 'minecraftsteve', icon: '⛏️', ar: 'ستيف (ماينكرافت)', en: 'Steve (Minecraft)', yes: 'human videogame blue', no: 'classic' },
  { id: 'creeper',    icon: '💣', ar: 'كريبر (ماينكرافت)', en: 'Creeper (Minecraft)', yes: 'videogame green villain', no: 'human animal classic' },
  { id: 'angrybird',  icon: '🐦', ar: 'العصفور الغضبان (أنجري بيردز)', en: 'Red (Angry Birds)', yes: 'animal bird videogame red', maybe: 'cartoon flies', no: 'human classic' },
  { id: 'crashbandicoot', icon: '🦊', ar: 'كراش بانديكوت', en: 'Crash Bandicoot', yes: 'animal mammal videogame orange classic', no: 'human' },
  { id: 'ryu',        icon: '🥋', ar: 'ريو (ستريت فايتر)', en: 'Ryu (Street Fighter)', yes: 'human videogame fighter classic white', maybe: 'warrior' },
  { id: 'talkingtom', icon: '😺', ar: 'توم المتكلّم', en: 'Talking Tom', yes: 'animal cat videogame gray tail', maybe: 'comedy cartoon', no: 'human classic' },

  /* ---------- fairy tales and storybooks ---------- */
  { id: 'redhood',    icon: '🧺', ar: 'ليلى والذئب (ليلى)', en: 'Little Red Riding Hood', yes: 'human female child tale red classic', maybe: 'hat cartoon' },
  { id: 'bigbadwolf', icon: '🐺', ar: 'الذئب (ليلى والذئب)', en: 'The Big Bad Wolf', yes: 'animal mammal villain tale classic gray', maybe: 'legs4 tail cartoon', no: 'human dog' },
  { id: 'threepigs',  icon: '🐖', ar: 'التلات خنازير الصغيرين', en: 'The Three Little Pigs', yes: 'animal mammal tale group pink classic', maybe: 'cartoon disney', no: 'human' },
  { id: 'puss',       icon: '🐈', ar: 'القط ذو الحذاء', en: 'Puss in Boots', yes: 'animal cat tale hat weapon classic orange', maybe: 'cartoon', no: 'human disney' },
  { id: 'uglyduckling', icon: '🦢', ar: 'البطة القبيحة', en: 'The Ugly Duckling', yes: 'animal bird tale child classic', maybe: 'gray white water cartoon', no: 'human' },
  { id: 'gulliver',   icon: '🏝️', ar: 'جاليفر', en: 'Gulliver', yes: 'human tale explorer classic', maybe: 'big cartoon' },
  { id: 'robinhood',  icon: '🏹', ar: 'روبن هود', en: 'Robin Hood', yes: 'human tale weapon hat green classic', maybe: 'cartoon disney liveaction hero' },
  { id: 'donquixote', icon: '🛡️', ar: 'دون كيشوت', en: 'Don Quixote', yes: 'human tale classic old weapon beard comedy', maybe: 'warrior duo' },

  /* ---------- films ---------- */
  { id: 'jamesbond',  icon: '🔫', ar: 'جيمس بوند', en: 'James Bond', yes: 'human liveaction weapon classic', maybe: 'detective', no: 'powers cartoon villain' },
  { id: 'indianajones', icon: '🤠', ar: 'إنديانا جونز', en: 'Indiana Jones', yes: 'human liveaction hat explorer classic', maybe: 'weapon' },
  { id: 'darthvader', icon: '⚫', ar: 'دارث فيدر', en: 'Darth Vader', yes: 'villain liveaction mask black cape classic weapon powers', maybe: 'human' },
  { id: 'yoda',       icon: '🟢', ar: 'يودا', en: 'Yoda', yes: 'green old powers liveaction classic bigears weapon', maybe: 'alien warrior', no: 'human' },
  { id: 'gandalf',    icon: '🧙‍♂️', ar: 'جاندالف', en: 'Gandalf', yes: 'old beard hat powers liveaction', maybe: 'human white gray weapon classic' },
  { id: 'kingkong',   icon: '🦍', ar: 'كينج كونج', en: 'King Kong', yes: 'animal mammal big liveaction classic black', maybe: 'brown', no: 'human' },
  { id: 'godzilla',   icon: '🦖', ar: 'جودزيلا', en: 'Godzilla', yes: 'big liveaction classic reptile', maybe: 'animal green gray villain', no: 'human' },
  { id: 'etalien',    icon: '👽', ar: 'إي تي', en: 'E.T.', yes: 'alien liveaction classic brown', maybe: 'child', no: 'human' },
  { id: 'zorro',      icon: '🎭', ar: 'زورو', en: 'Zorro', yes: 'human mask hat cape black weapon classic liveaction', maybe: 'hero' },
  { id: 'rockybalboa', icon: '🥊', ar: 'روكي', en: 'Rocky Balboa', yes: 'human liveaction fighter athlete classic' },
  { id: 'paddington', icon: '🐻', ar: 'بادينجتون', en: 'Paddington Bear', yes: 'animal mammal brown hat liveaction classic', no: 'human' },
  { id: 'gru',        icon: '🦹', ar: 'جرو (أنا الشرير)', en: 'Gru (Despicable Me)', yes: 'human cartoon villain', maybe: 'black gray comedy', no: 'classic disney' },
  { id: 'kevinhomealone', icon: '🏠', ar: 'كيفين (وحدي في البيت)', en: 'Kevin (Home Alone)', yes: 'human child liveaction classic comedy' },
  { id: 'alexlion',   icon: '🦁', ar: 'أليكس الأسد (مدغشقر)', en: 'Alex the Lion (Madagascar)', yes: 'animal cat cartoon legs4 tail big comedy', maybe: 'yellow ruler', no: 'human disney classic' },
  { id: 'sidiceage',  icon: '🦥', ar: 'سيد (العصر الجليدي)', en: 'Sid (Ice Age)', yes: 'animal mammal cartoon comedy', maybe: 'gray green', no: 'human disney classic' },
  { id: 'mannymammoth', icon: '🦣', ar: 'ماني الماموث (العصر الجليدي)', en: 'Manny the Mammoth (Ice Age)', yes: 'animal mammal cartoon big brown legs4', no: 'human disney classic bigears flies' },
  { id: 'toothless',  icon: '🐉', ar: 'توثلس (روّض تنينك)', en: 'Toothless (How to Train Your Dragon)', yes: 'animal flies black cartoon tail legs4 duo', maybe: 'reptile', no: 'human classic disney' },
  { id: 'shrekdonkey', icon: '🫏', ar: 'الحمار (صاحب شريك)', en: "Donkey (Shrek's friend)", yes: 'animal mammal cartoon gray comedy duo legs4 bigears', no: 'human disney classic' },
  { id: 'fiona',      icon: '👸', ar: 'الأميرة فيونا (شريك)', en: 'Princess Fiona (Shrek)', yes: 'princess cartoon green', maybe: 'human', no: 'disney classic' },
  { id: 'hermione',   icon: '📖', ar: 'هيرميوني (هاري بوتر)', en: 'Hermione (Harry Potter)', yes: 'human female liveaction powers', maybe: 'child classic' },
  { id: 'voldemort',  icon: '🐍', ar: 'فولدمورت (هاري بوتر)', en: 'Voldemort (Harry Potter)', yes: 'human villain liveaction powers', maybe: 'white black classic' },
  { id: 'dumbledore', icon: '🧙', ar: 'دمبلدور (هاري بوتر)', en: 'Dumbledore (Harry Potter)', yes: 'human old beard powers liveaction glasses', maybe: 'hat classic' },
]};
