/* العرّاف: things (kind 't': food, objects, places, nature) and jobs (kind 'j'). One line each:
   id, icon, ar, en, and the question ids (OracleQuestions.js) that are true (yes), partly or
   "most would say probably" (maybe), and firmly not, where a player might think otherwise (no).
   A question about the entry's kind in none of the three reads as «غالباً لأ».
   notes/games/oracle.md, "Writing entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_THINGS = { kind: 't', list: [
  /* ---------- food and drink ---------- */
  { id: 'apple',      icon: '🍎', ar: 'تفاحة', en: 'Apple', yes: 'red edible fruit sweet nature round', maybe: 'green kitchen home peel', no: 'plant' },
  { id: 'banana',     icon: '🍌', ar: 'موزة', en: 'Banana', yes: 'yellow edible fruit sweet nature peel long', maybe: 'breakfast soft', no: 'round' },
  { id: 'orange',     icon: '🍊', ar: 'برتقانة', en: 'Orange', yes: 'orange edible fruit sweet nature round peel', maybe: 'drink smell rainy' },
  { id: 'watermelon', icon: '🍉', ar: 'بطيخة', en: 'Watermelon', yes: 'red green edible summer fruit sweet nature round seeds', maybe: 'big cold street peel' },
  { id: 'mango',      icon: '🥭', ar: 'مانجا', en: 'Mango', yes: 'yellow edible summer fruit sweet nature peel', maybe: 'egypt arab green orange drink soft smell' },
  { id: 'grapes',     icon: '🍇', ar: 'عنب', en: 'Grapes', yes: 'small edible summer fruit sweet nature', maybe: 'green round seeds' },
  { id: 'strawberry', icon: '🍓', ar: 'فراولة', en: 'Strawberry', yes: 'small red edible fruit sweet nature', maybe: 'drink soft smell seeds' },
  { id: 'dates',      icon: '🌴', ar: 'بلح', en: 'Dates', yes: 'arab small brown edible fruit sweet nature ramadan', maybe: 'egypt soft' },
  { id: 'tomato',     icon: '🍅', ar: 'طماطم', en: 'Tomato', yes: 'red edible veg kitchen nature round', maybe: 'breakfast home soft seeds' },
  { id: 'potato',     icon: '🥔', ar: 'بطاطس', en: 'Potato', yes: 'brown edible veg kitchen nature peel', maybe: 'breakfast dish home round fried' },
  { id: 'onion',      icon: '🧅', ar: 'بصلة', en: 'Onion', yes: 'edible veg kitchen home nature round peel', maybe: 'red white' },
  { id: 'carrot',     icon: '🥕', ar: 'جزرة', en: 'Carrot', yes: 'orange edible veg kitchen nature long', maybe: 'peel' },
  { id: 'molokhia',   icon: '🥬', ar: 'ملوخية', en: 'Molokhia', yes: 'egypt arab green edible dish kitchen hot leaves', maybe: 'veg home liquid meat_t smell' },
  { id: 'koshary',    icon: '🍝', ar: 'كشري', en: 'Koshary', yes: 'egypt arab edible dish hot street', maybe: 'brown smell' },
  { id: 'ful',        icon: '🫘', ar: 'فول', en: 'Ful medames', yes: 'egypt arab brown edible breakfast dish hot street', maybe: 'ramadan' },
  { id: 'taameya',    icon: '🧆', ar: 'طعمية', en: 'Taameya', yes: 'egypt arab small brown edible breakfast dish hot round fried', maybe: 'green street smell' },
  { id: 'bread',      icon: '🍞', ar: 'عيش', en: 'Bread', yes: 'brown edible breakfast kitchen home round soft', maybe: 'dish hot smell' },
  { id: 'cheese',     icon: '🧀', ar: 'جبنة', en: 'Cheese', yes: 'white edible breakfast kitchen home', maybe: 'yellow square soft' },
  { id: 'egg',        icon: '🥚', ar: 'بيضة', en: 'Egg', yes: 'small edible breakfast kitchen home breaks', maybe: 'yellow white dish nature round peel fried' },
  { id: 'pizza',      icon: '🍕', ar: 'بيتزا', en: 'Pizza', yes: 'edible dish hot round', maybe: 'red meat_t soft smell colorful' },
  { id: 'konafa',     icon: '🍯', ar: 'كنافة', en: 'Konafa', yes: 'arab edible sweet dish ramadan stuffed', maybe: 'egypt yellow brown orange hot round smell' },
  { id: 'kahk',       icon: '🍪', ar: 'كحك العيد', en: 'Eid cookies (kahk)', yes: 'egypt arab small edible sweet dish ramadan round', maybe: 'white brown smell stuffed' },
  { id: 'chocolate',  icon: '🍫', ar: 'شوكولاتة', en: 'Chocolate', yes: 'brown edible sweet', maybe: 'small pocket square smell' },
  { id: 'icecream',   icon: '🍦', ar: 'آيس كريم', en: 'Ice cream', yes: 'edible summer sweet cold soft', maybe: 'white pink round street colorful' },
  { id: 'water',      icon: '💧', ar: 'مية', en: 'Water', yes: 'drink home nature liquid wet', maybe: 'kitchen bathroom cold clean' },
  { id: 'milk',       icon: '🥛', ar: 'لبن', en: 'Milk', yes: 'white drink kitchen liquid', maybe: 'edible breakfast home nature cold' },
  { id: 'tea',        icon: '🫖', ar: 'شاي', en: 'Tea', yes: 'drink kitchen home hot liquid leaves', maybe: 'brown breakfast sweet smell' },
  { id: 'sugarcane',  icon: '🥤', ar: 'عصير قصب', en: 'Sugarcane juice', yes: 'egypt arab summer drink sweet liquid', maybe: 'green cold street' },
  /* ---------- around the house ---------- */
  { id: 'phone',      icon: '📱', ar: 'موبايل', en: 'Mobile phone', yes: 'electric screen home pocket noise talk square internet touch listen', maybe: 'small black buttons glass light breaks time read', no: 'big' },
  { id: 'tv',         icon: '📺', ar: 'تلفزيون', en: 'Television', yes: 'electric screen home noise talk square byremote listen', maybe: 'big black buttons glass light breaks internet', no: 'small pocket' },
  { id: 'computer',   icon: '💻', ar: 'كمبيوتر', en: 'Computer', yes: 'electric screen buttons square internet', maybe: 'black gray home school write light noise talk read listen', no: 'pocket' },
  { id: 'fridge',     icon: '🧊', ar: 'تلاجة', en: 'Fridge', yes: 'big electric engine kitchen home metal cold container square', maybe: 'white noise holdsdrink' },
  { id: 'fan',        icon: '🌀', ar: 'مروحة', en: 'Fan', yes: 'summer electric engine home buttons cold noise', maybe: 'metal round bedroom byremote' },
  { id: 'lamp',       icon: '💡', ar: 'لمبة', en: 'Light bulb', yes: 'electric home glass light breaks', maybe: 'small yellow hot round bedroom' },
  { id: 'clock',      icon: '⏰', ar: 'ساعة حيطة', en: 'Wall clock', yes: 'home round time', maybe: 'electric metal glass noise bedroom' },
  { id: 'watch',      icon: '⌚', ar: 'ساعة إيد', en: 'Wristwatch', yes: 'small wear time', maybe: 'electric screen pocket buttons metal glass round internet touch' },
  { id: 'lantern',    icon: '🏮', ar: 'فانوس رمضان', en: 'Ramadan lantern', yes: 'egypt arab ramadan light colorful', maybe: 'electric home toy metal glass breaks noise street flame' },
  { id: 'chair',      icon: '🪑', ar: 'كرسي', en: 'Chair', yes: 'home sit furniture', maybe: 'brown kitchen school metal wood' },
  { id: 'bed',        icon: '🛏️', ar: 'سرير', en: 'Bed', yes: 'big home sit furniture square soft bedroom', maybe: 'wood cloth' },
  { id: 'table',      icon: '🪵', ar: 'ترابيزة', en: 'Table', yes: 'home furniture wood', maybe: 'big brown kitchen school square' },
  { id: 'door',       icon: '🚪', ar: 'باب', en: 'Door', yes: 'big home wood square', maybe: 'brown metal noise' },
  { id: 'key',        icon: '🔑', ar: 'مفتاح', en: 'Key', yes: 'small home pocket metal', maybe: 'handtool long' },
  { id: 'mirror',     icon: '🪞', ar: 'مراية', en: 'Mirror', yes: 'home bathroom glass breaks', maybe: 'furniture round square bedroom' },
  { id: 'pillow',     icon: '🛌', ar: 'مخدّة', en: 'Pillow', yes: 'home sit cloth soft bedroom', maybe: 'white square' },
  { id: 'soap',       icon: '🧼', ar: 'صابونة', en: 'Soap', yes: 'home bathroom clean wet smell', maybe: 'small white kitchen square' },
  { id: 'toothbrush', icon: '🪥', ar: 'فرشة سنان', en: 'Toothbrush', yes: 'home bathroom handtool clean long', maybe: 'small wet colorful' },
  { id: 'broom',      icon: '🧹', ar: 'مقشّة', en: 'Broom', yes: 'home handtool clean long', maybe: 'wood' },
  { id: 'cup',        icon: '🥛', ar: 'كوباية', en: 'Glass (to drink)', yes: 'kitchen home glass breaks container holdsdrink', maybe: 'small round wet' },
  { id: 'spoon',      icon: '🥄', ar: 'معلقة', en: 'Spoon', yes: 'kitchen home handtool metal', maybe: 'small gray long' },
  { id: 'knife',      icon: '🔪', ar: 'سكينة', en: 'Knife', yes: 'kitchen home handtool metal sharp', maybe: 'gray long' },
  { id: 'scissors',   icon: '✂️', ar: 'مقص', en: 'Scissors', yes: 'home handtool metal sharp', maybe: 'school' },
  { id: 'umbrella',   icon: '☂️', ar: 'شمسية', en: 'Umbrella', yes: 'summer cloth', maybe: 'black handtool metal wet street long colorful rainy' },
  { id: 'money',      icon: '💵', ar: 'فلوس', en: 'Money', yes: 'home pocket paper square', maybe: 'small green metal ramadan colorful' },
  { id: 'camera',     icon: '📷', ar: 'كاميرا', en: 'Camera', yes: 'black electric buttons', maybe: 'small screen glass light noise square' },
  /* ---------- school, play and music ---------- */
  { id: 'pencil',     icon: '✏️', ar: 'قلم رصاص', en: 'Pencil', yes: 'school handtool wood write long', maybe: 'small yellow pocket breaks colorful' },
  { id: 'book',       icon: '📖', ar: 'كتاب', en: 'Book', yes: 'school paper square read', maybe: 'home write colorful' },
  { id: 'notebook',   icon: '📒', ar: 'كشكول', en: 'Notebook', yes: 'school paper write square', maybe: 'white home colorful' },
  { id: 'ball',       icon: '⚽', ar: 'كورة', en: 'Ball', yes: 'toy sport round', maybe: 'white black home school street colorful' },
  { id: 'teddy',      icon: '🧸', ar: 'دبدوب', en: 'Teddy bear', yes: 'brown toy cloth soft', maybe: 'home' },
  { id: 'kite',       icon: '🪁', ar: 'طيارة ورق', en: 'Kite', yes: 'flies toy paper sky colorful', maybe: 'summer wood cloth breaks' },
  { id: 'balloon',    icon: '🎈', ar: 'بالونة', en: 'Balloon', yes: 'toy round breaks colorful', maybe: 'flies red pink sky ramadan noise soft' },
  { id: 'guitar',     icon: '🎸', ar: 'جيتار', en: 'Guitar', yes: 'music wood noise', maybe: 'brown long', no: 'arab' },
  { id: 'oud',        icon: '🪕', ar: 'عود', en: 'Oud', yes: 'arab music wood noise', maybe: 'egypt brown' },
  { id: 'drum',       icon: '🥁', ar: 'طبلة', en: 'Drum (tabla)', yes: 'arab music noise', maybe: 'egypt ramadan round' },
  /* ---------- on the road ---------- */
  { id: 'car',        icon: '🚗', ar: 'عربية', en: 'Car', yes: 'big vehicle engine wheels metal noise street', maybe: 'light travel listen', no: 'passengers' },
  { id: 'bicycle',    icon: '🚲', ar: 'عجلة', en: 'Bicycle', yes: 'vehicle wheels metal street twowheels', maybe: 'sit toy sport noise', no: 'big engine' },
  { id: 'bus',        icon: '🚌', ar: 'أتوبيس', en: 'Bus', yes: 'big vehicle engine passengers wheels metal noise street fare standing', maybe: 'school square long travel' },
  { id: 'train',      icon: '🚆', ar: 'قطر', en: 'Train', yes: 'big vehicle engine passengers wheels metal noise fare travel', maybe: 'electric long cargo standing' },
  { id: 'plane',      icon: '✈️', ar: 'طيارة', en: 'Aeroplane', yes: 'flies big vehicle engine passengers metal sky noise fare travel', maybe: 'white wheels cargo' },
  { id: 'boat',       icon: '⛵', ar: 'مركب', en: 'Boat', yes: 'big vehicle wet', maybe: 'white engine passengers wood cargo fare travel' },
  /* ---------- clothes ---------- */
  { id: 'shoe',       icon: '👞', ar: 'جزمة', en: 'Shoe', yes: 'home wear', maybe: 'black brown street' },
  { id: 'shirt',      icon: '👕', ar: 'قميص', en: 'Shirt', yes: 'buttons wear cloth', maybe: 'white home school soft colorful' },
  { id: 'glasses',    icon: '👓', ar: 'نضارة', en: 'Glasses', yes: 'wear glass breaks', maybe: 'small black pocket metal' },
  { id: 'cap',        icon: '🧢', ar: 'كاب', en: 'Cap', yes: 'wear cloth', maybe: 'summer sport soft colorful' },
  /* ---------- nature and places ---------- */
  { id: 'sun',        icon: '☀️', ar: 'الشمس', en: 'The Sun', yes: 'big yellow nature sky light hot round' },
  { id: 'moon',       icon: '🌙', ar: 'القمر', en: 'The Moon', yes: 'big nature sky light round', maybe: 'white gray ramadan time' },
  { id: 'star',       icon: '⭐', ar: 'نجمة في السما', en: 'A star', yes: 'big nature sky light', maybe: 'yellow white' },
  { id: 'cloud',      icon: '☁️', ar: 'سحابة', en: 'Cloud', yes: 'big white nature sky wet rainy', maybe: 'gray soft' },
  { id: 'tree',       icon: '🌳', ar: 'شجرة', en: 'Tree', yes: 'big green nature plant', maybe: 'brown wood street long' },
  { id: 'rose',       icon: '🌹', ar: 'وردة', en: 'Rose', yes: 'red nature plant smell', maybe: 'small green pink sharp soft colorful' },
  { id: 'cactus',     icon: '🌵', ar: 'صبّارة', en: 'Cactus', yes: 'green nature plant', maybe: 'small home sharp' },
  { id: 'sea',        icon: '🌊', ar: 'البحر', en: 'The sea', yes: 'big blue summer nature place wet', maybe: 'liquid noise' },
  { id: 'nile',       icon: '🏞️', ar: 'النيل', en: 'The Nile', yes: 'egypt arab big nature place wet long', maybe: 'blue liquid' },
  { id: 'pyramids',   icon: '🔺', ar: 'الأهرامات', en: 'The Pyramids', yes: 'egypt arab big place', maybe: 'yellow brown', no: 'nature' },
  { id: 'school_p',   icon: '🏫', ar: 'مدرسة', en: 'School', yes: 'big school place', maybe: 'street square' },
  { id: 'fire',       icon: '🔥', ar: 'نار', en: 'Fire', yes: 'light hot flame', maybe: 'big red yellow orange kitchen nature noise' },
  { id: 'ice',        icon: '🧊', ar: 'تلج', en: 'Ice', yes: 'white cold wet', maybe: 'small summer home nature breaks square' },
  /* ---------- added 9 Oct 2026: fruit and vegetables ---------- */
  { id: 'guava',      icon: '🍐', ar: 'جوافة', en: 'Guava', yes: 'green edible fruit sweet nature smell seeds', maybe: 'yellow drink round' },
  { id: 'pomegranate', icon: '🍎', ar: 'رمان', en: 'Pomegranate', yes: 'red edible fruit sweet nature round peel seeds', maybe: 'pink drink' },
  { id: 'fig',        icon: '🫐', ar: 'تين', en: 'Fig', yes: 'small edible summer fruit sweet nature soft seeds', maybe: 'green brown peel' },
  { id: 'apricot',    icon: '🍑', ar: 'مشمش', en: 'Apricot', yes: 'small orange edible summer fruit sweet nature', maybe: 'round soft' },
  { id: 'lemon',      icon: '🍋', ar: 'لمونة', en: 'Lemon', yes: 'small yellow edible fruit kitchen nature', maybe: 'green drink home round smell', no: 'sweet' },
  { id: 'cantaloupe', icon: '🍈', ar: 'كانتالوب', en: 'Cantaloupe', yes: 'orange edible summer fruit sweet nature round peel seeds', maybe: 'yellow cold smell' },
  { id: 'tangerine',  icon: '🍊', ar: 'يوسفي', en: 'Tangerine', yes: 'orange edible fruit sweet nature round peel small', maybe: 'smell rainy' },
  { id: 'coconut',    icon: '🥥', ar: 'جوز هند', en: 'Coconut', yes: 'brown edible fruit nature round', maybe: 'white drink sweet peel', no: 'small' },
  { id: 'pricklypear', icon: '🌵', ar: 'تين شوكي', en: 'Prickly pear', yes: 'edible summer fruit sweet nature street peel seeds', maybe: 'green orange sharp' },
  { id: 'cucumber',   icon: '🥒', ar: 'خيارة', en: 'Cucumber', yes: 'green edible veg kitchen nature long', maybe: 'breakfast cold peel seeds' },
  { id: 'eggplant',   icon: '🍆', ar: 'بدنجان', en: 'Aubergine', yes: 'edible veg kitchen nature', maybe: 'black breakfast dish peel long seeds fried' },
  { id: 'garlic',     icon: '🧄', ar: 'توم', en: 'Garlic', yes: 'small white edible veg kitchen nature peel', maybe: 'home round' },
  { id: 'okra',       icon: '🫛', ar: 'بامية', en: 'Okra', yes: 'small green edible veg nature seeds', maybe: 'dish kitchen long' },
  { id: 'corn',       icon: '🌽', ar: 'درة', en: 'Corn', yes: 'yellow edible veg nature street long', maybe: 'summer hot peel' },
  { id: 'sweetpotato', icon: '🍠', ar: 'بطاطا', en: 'Sweet potato', yes: 'edible veg sweet nature hot street rainy', maybe: 'egypt arab brown orange dish peel long soft smell' },
  { id: 'mint',       icon: '🌿', ar: 'نعناع', en: 'Mint', yes: 'small green edible nature plant smell leaves', maybe: 'drink veg kitchen' },
  { id: 'olives',     icon: '🫒', ar: 'زيتون', en: 'Olives', yes: 'small green edible breakfast nature', maybe: 'black kitchen round' },
  { id: 'peanuts',    icon: '🥜', ar: 'سوداني', en: 'Peanuts', yes: 'small brown edible peel', maybe: 'nature street' },
  { id: 'lupini',     icon: '🟡', ar: 'ترمس', en: 'Lupini beans', yes: 'egypt arab small yellow edible street peel', maybe: 'round' },
  /* ---------- dishes, sweets and drinks ---------- */
  { id: 'rice',       icon: '🍚', ar: 'رز', en: 'Rice', yes: 'small white edible dish kitchen home', maybe: 'hot' },
  { id: 'mahshi',     icon: '🫑', ar: 'محشي', en: 'Mahshi (stuffed vegetables)', yes: 'egypt arab edible dish hot stuffed', maybe: 'green meat_t long leaves' },
  { id: 'fatta',      icon: '🍲', ar: 'فتة', en: 'Fatta', yes: 'egypt arab edible dish ramadan hot meat_t', maybe: 'white smell' },
  { id: 'feteer',     icon: '🥧', ar: 'فطير مشلتت', en: 'Feteer meshaltet', yes: 'egypt arab edible dish round', maybe: 'breakfast sweet hot soft stuffed' },
  { id: 'hawawshi',   icon: '🥙', ar: 'حواوشي', en: 'Hawawshi', yes: 'egypt arab edible dish hot street meat_t stuffed', maybe: 'brown round' },
  { id: 'shawarma',   icon: '🌯', ar: 'شاورما', en: 'Shawarma', yes: 'arab edible dish hot street meat_t', maybe: 'long smell stuffed' },
  { id: 'kofta',      icon: '🍢', ar: 'كفتة', en: 'Kofta', yes: 'brown edible dish hot meat_t', maybe: 'egypt arab long smell' },
  { id: 'feseekh',    icon: '🐟', ar: 'فسيخ', en: 'Feseekh (salted fish)', yes: 'egypt arab edible', maybe: 'gray dish wet peel' },
  { id: 'basbousa',   icon: '🍰', ar: 'بسبوسة', en: 'Basbousa', yes: 'egypt arab edible sweet dish', maybe: 'yellow brown ramadan square soft' },
  { id: 'qatayef',    icon: '🥟', ar: 'قطايف', en: 'Qatayef', yes: 'arab edible sweet dish ramadan round stuffed fried', maybe: 'egypt brown soft' },
  { id: 'omali',      icon: '🥣', ar: 'أم علي', en: 'Om Ali', yes: 'egypt arab edible sweet dish hot', maybe: 'white soft' },
  { id: 'ricepudding', icon: '🍮', ar: 'رز بلبن', en: 'Rice pudding', yes: 'white edible sweet dish cold', maybe: 'egypt arab soft' },
  { id: 'cake',       icon: '🎂', ar: 'تورتة', en: 'Birthday cake', yes: 'edible sweet dish soft', maybe: 'white round smell colorful' },
  { id: 'biscuit',    icon: '🍪', ar: 'بسكوت', en: 'Biscuit', yes: 'small edible sweet breaks', maybe: 'yellow brown breakfast pocket ramadan round square stuffed' },
  { id: 'honey',      icon: '🍯', ar: 'عسل نحل', en: 'Honey', yes: 'yellow edible sweet', maybe: 'orange breakfast kitchen nature liquid' },
  { id: 'molasses',   icon: '🫙', ar: 'عسل إسود', en: 'Black molasses', yes: 'black edible breakfast sweet', maybe: 'egypt arab brown liquid' },
  { id: 'halawa',     icon: '🥮', ar: 'حلاوة طحينية', en: 'Halawa', yes: 'edible breakfast sweet', maybe: 'egypt arab white brown' },
  { id: 'sugar',      icon: '🍬', ar: 'سكر', en: 'Sugar', yes: 'small white edible sweet kitchen home' },
  { id: 'popcorn',    icon: '🍿', ar: 'فشار', en: 'Popcorn', yes: 'small white edible', maybe: 'yellow sweet dish hot smell' },
  { id: 'chips',      icon: '🥔', ar: 'شيبسي', en: 'Crisps', yes: 'small yellow edible breaks fried' },
  { id: 'lollipop',   icon: '🍭', ar: 'مصاصة', en: 'Lollipop', yes: 'small edible sweet pocket round colorful', maybe: 'red pink' },
  { id: 'cottoncandy', icon: '🍥', ar: 'غزل البنات', en: 'Candy floss', yes: 'pink edible sweet soft', maybe: 'white street colorful' },
  { id: 'yogurt',     icon: '🥛', ar: 'زبادي', en: 'Yoghurt', yes: 'white edible kitchen cold', maybe: 'breakfast liquid soft' },
  { id: 'coffee',     icon: '☕', ar: 'قهوة', en: 'Coffee', yes: 'brown drink kitchen hot liquid smell', maybe: 'arab black breakfast home' },
  { id: 'hibiscus',   icon: '🌺', ar: 'كركديه', en: 'Hibiscus drink (karkade)', yes: 'egypt arab red drink sweet liquid', maybe: 'summer ramadan hot cold leaves' },
  { id: 'sobia',      icon: '🥛', ar: 'سوبيا', en: 'Sobia', yes: 'egypt arab white drink sweet ramadan cold liquid', maybe: 'summer' },
  { id: 'qamareldin', icon: '🧃', ar: 'قمر الدين', en: 'Apricot drink (qamar el-din)', yes: 'orange drink sweet ramadan liquid', maybe: 'egypt arab cold' },
  { id: 'tamarind',   icon: '🥤', ar: 'تمر هندي', en: 'Tamarind drink', yes: 'brown drink sweet ramadan cold liquid', maybe: 'arab summer' },
  { id: 'soda',       icon: '🥫', ar: 'حاجة ساقعة (مشروب غازي)', en: 'Fizzy drink', yes: 'drink sweet cold liquid', maybe: 'black summer' },
  { id: 'sahlab',     icon: '🍵', ar: 'سحلب', en: 'Sahlab', yes: 'white drink sweet hot liquid rainy', maybe: 'arab edible' },
  /* ---------- around the house ---------- */
  { id: 'washer',     icon: '🫧', ar: 'غسالة', en: 'Washing machine', yes: 'electric engine home buttons noise clean wet container square', maybe: 'white bathroom metal' },
  { id: 'cooker',     icon: '🍳', ar: 'بوتاجاز', en: 'Cooker (stove)', yes: 'kitchen home metal hot flame', maybe: 'big white buttons container square', no: 'electric' },
  { id: 'microwave',  icon: '♨️', ar: 'ميكروويف', en: 'Microwave', yes: 'electric kitchen buttons hot container square', maybe: 'white screen home metal glass noise' },
  { id: 'aircon',     icon: '❄️', ar: 'تكييف', en: 'Air conditioner', yes: 'white summer electric engine cold byremote', maybe: 'big home buttons metal noise square long bedroom' },
  { id: 'iron',       icon: '🧺', ar: 'مكواة', en: 'Iron', yes: 'electric home handtool metal hot', maybe: 'clean' },
  { id: 'vacuum',     icon: '🧹', ar: 'مكنسة كهربا', en: 'Vacuum cleaner', yes: 'electric engine noise clean', maybe: 'wheels home buttons handtool long' },
  { id: 'kettle',     icon: '🫖', ar: 'كاتل (غلاية مية)', en: 'Electric kettle', yes: 'electric kitchen hot container holdsdrink', maybe: 'home buttons metal noise wet' },
  { id: 'blender',    icon: '🍹', ar: 'خلاط', en: 'Blender', yes: 'electric engine kitchen buttons sharp noise container', maybe: 'home glass holdsdrink' },
  { id: 'remote',     icon: '🎛️', ar: 'ريموت', en: 'Remote control', yes: 'electric home buttons square', maybe: 'small black pocket handtool talk long byremote' },
  { id: 'sofa',       icon: '🛋️', ar: 'كنبة', en: 'Sofa', yes: 'big home sit furniture cloth soft', maybe: 'wood square long' },
  { id: 'wardrobe',   icon: '🚪', ar: 'دولاب', en: 'Wardrobe', yes: 'big home furniture wood container square bedroom', maybe: 'brown' },
  { id: 'carpet',     icon: '🟥', ar: 'سجادة', en: 'Carpet', yes: 'home sit cloth square soft floor', maybe: 'big red furniture colorful bedroom' },
  { id: 'curtain',    icon: '🪟', ar: 'ستارة', en: 'Curtain', yes: 'home cloth', maybe: 'big square long soft colorful bedroom' },
  { id: 'blanket',    icon: '🛏️', ar: 'بطانية', en: 'Blanket', yes: 'home cloth hot soft bedroom', maybe: 'sit square colorful rainy' },
  { id: 'towel',      icon: '🧖', ar: 'فوطة', en: 'Towel', yes: 'home bathroom cloth clean wet soft', maybe: 'white kitchen square colorful' },
  { id: 'toothpaste', icon: '🪥', ar: 'معجون سنان', en: 'Toothpaste', yes: 'home bathroom clean', maybe: 'small white liquid long smell' },
  { id: 'shampoo',    icon: '🧴', ar: 'شامبو', en: 'Shampoo', yes: 'home bathroom liquid clean wet smell', maybe: 'container' },
  { id: 'pot',        icon: '🍲', ar: 'حلّة', en: 'Cooking pot', yes: 'kitchen home metal container', maybe: 'gray hot round' },
  { id: 'plate',      icon: '🍽️', ar: 'طبق', en: 'Plate', yes: 'kitchen home round breaks', maybe: 'white glass container' },
  { id: 'kanaka',     icon: '☕', ar: 'كنكة', en: 'Coffee pot (kanaka)', yes: 'kitchen metal container holdsdrink', maybe: 'egypt arab small home hot' },
  { id: 'landline',   icon: '☎️', ar: 'تليفون أرضي', en: 'Landline telephone', yes: 'electric buttons noise talk', maybe: 'home square' },
  { id: 'radio',      icon: '📻', ar: 'راديو', en: 'Radio', yes: 'electric buttons noise listen', maybe: 'home talk square' },
  { id: 'headphones', icon: '🎧', ar: 'سماعات', en: 'Headphones', yes: 'electric noise wear listen', maybe: 'small black home pocket buttons' },
  { id: 'battery',    icon: '🔋', ar: 'بطارية', en: 'Battery', yes: 'small electric pocket metal', maybe: 'home long' },
  { id: 'tablet',     icon: '📲', ar: 'تابلت', en: 'Tablet', yes: 'electric screen talk square internet touch', maybe: 'black buttons school glass write light breaks read listen', no: 'pocket' },
  { id: 'console',    icon: '🎮', ar: 'بلايستيشن', en: 'Games console', yes: 'electric buttons toy japan_g', maybe: 'black screen home noise square internet byremote appgame vgame onconsole online oldgame' },
  { id: 'hammer',     icon: '🔨', ar: 'شاكوش', en: 'Hammer', yes: 'handtool metal noise', maybe: 'gray wood long' },
  { id: 'saw',        icon: '🪚', ar: 'منشار', en: 'Saw', yes: 'handtool metal sharp noise', maybe: 'gray wood long' },
  { id: 'perfume',    icon: '🌸', ar: 'برفان', en: 'Perfume', yes: 'glass liquid smell', maybe: 'small home bathroom pocket wear breaks container bedroom' },
  { id: 'ring',       icon: '💍', ar: 'خاتم', en: 'Ring', yes: 'small pocket wear metal round', maybe: 'yellow' },
  { id: 'newspaper',  icon: '🗞️', ar: 'جرنال', en: 'Newspaper', yes: 'paper square read', maybe: 'white black write street' },
  /* ---------- school ---------- */
  { id: 'pen',        icon: '🖊️', ar: 'قلم جاف', en: 'Ballpoint pen', yes: 'pocket school handtool write long', maybe: 'small blue home' },
  { id: 'schoolbag',  icon: '🎒', ar: 'شنطة المدرسة', en: 'School bag', yes: 'school container', maybe: 'wear cloth square colorful' },
  { id: 'blackboard', icon: '🟩', ar: 'سبورة', en: 'Blackboard', yes: 'big school write square', maybe: 'green black' },
  { id: 'chalk',      icon: '🖍️', ar: 'طباشير', en: 'Chalk', yes: 'small white pocket school write breaks', maybe: 'handtool long' },
  { id: 'calculator', icon: '🧮', ar: 'آلة حاسبة', en: 'Calculator', yes: 'electric screen buttons school square', maybe: 'small pocket' },
  /* ---------- clothes ---------- */
  { id: 'jacket',     icon: '🧥', ar: 'جاكيت', en: 'Jacket', yes: 'wear cloth hot rainy', maybe: 'home buttons soft' },
  { id: 'galabeya',   icon: '🥻', ar: 'جلابية', en: 'Galabeya', yes: 'egypt arab wear cloth', maybe: 'white home buttons long soft' },
  { id: 'tarboosh',   icon: '🎩', ar: 'طربوش', en: 'Tarboosh (fez)', yes: 'egypt arab red wear', maybe: 'cloth round' },
  { id: 'sunglasses', icon: '🕶️', ar: 'نضارة شمس', en: 'Sunglasses', yes: 'black summer wear glass breaks', maybe: 'pocket' },
  /* ---------- on the road, in the air, at sea ---------- */
  { id: 'motorbike',  icon: '🏍️', ar: 'موتوسيكل', en: 'Motorbike', yes: 'vehicle engine wheels metal noise street twowheels', maybe: 'big sit' },
  { id: 'tuktuk',     icon: '🛺', ar: 'توك توك', en: 'Tuk-tuk', yes: 'big vehicle engine wheels metal noise street fare', maybe: 'egypt arab colorful' },
  { id: 'microbus',   icon: '🚐', ar: 'ميكروباص', en: 'Microbus', yes: 'big vehicle engine passengers wheels metal noise street fare travel', maybe: 'egypt arab white square' },
  { id: 'metro',      icon: '🚇', ar: 'مترو', en: 'Metro (underground)', yes: 'big electric vehicle engine passengers wheels metal noise long fare standing' },
  { id: 'ship',       icon: '🚢', ar: 'سفينة', en: 'Ship', yes: 'big vehicle engine passengers metal wet travel', maybe: 'white noise cargo fare' },
  { id: 'helicopter', icon: '🚁', ar: 'هليكوبتر', en: 'Helicopter', yes: 'flies big vehicle engine metal sky noise', maybe: 'travel' },
  { id: 'truck',      icon: '🚛', ar: 'تريلا', en: 'Lorry', yes: 'big vehicle engine wheels metal noise street cargo', maybe: 'square long' },
  { id: 'ambulance',  icon: '🚑', ar: 'عربية إسعاف', en: 'Ambulance', yes: 'big white vehicle engine wheels metal noise street siren', maybe: 'red light square' },
  { id: 'firetruck',  icon: '🚒', ar: 'عربية مطافي', en: 'Fire engine', yes: 'big red vehicle engine wheels metal noise street siren', maybe: 'light wet long' },
  { id: 'carriage',   icon: '🐎', ar: 'حنطور', en: 'Horse carriage', yes: 'big vehicle wheels street fare', maybe: 'egypt arab black brown metal wood noise colorful', no: 'engine' },
  { id: 'felucca',    icon: '⛵', ar: 'فلوكة', en: 'Felucca', yes: 'egypt arab big white vehicle wood wet fare', maybe: 'passengers cloth cargo', no: 'engine' },
  { id: 'rocket',     icon: '🚀', ar: 'صاروخ', en: 'Space rocket', yes: 'flies big vehicle engine metal sky noise long', maybe: 'white flame' },
  { id: 'trafficlight', icon: '🚦', ar: 'إشارة مرور', en: 'Traffic light', yes: 'big electric light street colorful', maybe: 'red yellow green metal square long' },
  { id: 'streetlamp', icon: '🏮', ar: 'عمود نور', en: 'Street lamp', yes: 'big electric metal light street long', maybe: 'gray glass' },
  /* ---------- sport, toys and music ---------- */
  { id: 'racket',     icon: '🎾', ar: 'مضرب تنس', en: 'Tennis racket', yes: 'handtool sport', maybe: 'metal round long' },
  { id: 'basketball', icon: '🏀', ar: 'كورة سلة', en: 'Basketball', yes: 'orange sport round', maybe: 'toy' },
  { id: 'trophy',     icon: '🏆', ar: 'كاس البطولة', en: 'Trophy (cup)', yes: 'yellow sport metal', maybe: 'container' },
  { id: 'chessboard', icon: '♟️', ar: 'شطرنج', en: 'Chess set', yes: 'square white black puzzle tablegame', maybe: 'toy sport wood' },
  { id: 'dice',       icon: '🎲', ar: 'زهر الطاولة', en: 'Dice', yes: 'small white pocket square', maybe: 'black toy tablegame' },
  { id: 'backgammon', icon: '🎲', ar: 'طاولة (الزهر)', en: 'Backgammon', yes: 'wood square tablegame', maybe: 'egypt arab brown toy noise puzzle' },
  { id: 'cards',      icon: '🃏', ar: 'كوتشينة', en: 'Playing cards', yes: 'small pocket paper square cardgame tablegame', maybe: 'toy colorful puzzle' },
  { id: 'marbles',    icon: '🔮', ar: 'بلي', en: 'Marbles', yes: 'small pocket toy glass round colorful' },
  { id: 'piano',      icon: '🎹', ar: 'بيانو', en: 'Piano', yes: 'big music noise', maybe: 'white black furniture wood' },
  { id: 'trumpet',    icon: '🎺', ar: 'ترومبيت', en: 'Trumpet', yes: 'yellow music metal noise', maybe: 'long' },
  /* ---------- places ---------- */
  { id: 'beach',      icon: '🏖️', ar: 'البلاج', en: 'The beach', yes: 'big summer nature place wet', maybe: 'yellow hot' },
  { id: 'desert_p',   icon: '🏜️', ar: 'الصحرا', en: 'The desert', yes: 'big yellow nature place hot', maybe: 'brown' },
  { id: 'mountain',   icon: '⛰️', ar: 'جبل', en: 'Mountain', yes: 'big nature place', maybe: 'brown gray' },
  { id: 'stadium',    icon: '🏟️', ar: 'إستاد', en: 'Stadium', yes: 'big sport place', maybe: 'green noise' },
  { id: 'khankhalili', icon: '🛍️', ar: 'خان الخليلي', en: 'Khan el-Khalili', yes: 'egypt arab big place street', maybe: 'noise smell colorful' },
  { id: 'suezcanal',  icon: '🚢', ar: 'قناة السويس', en: 'The Suez Canal', yes: 'egypt arab big place wet long', maybe: 'blue', no: 'nature' },
  { id: 'eiffel',     icon: '🗼', ar: 'برج إيفل', en: 'The Eiffel Tower', yes: 'big metal place', maybe: 'brown long' },
  { id: 'burjkhalifa', icon: '🏙️', ar: 'برج خليفة', en: 'Burj Khalifa', yes: 'arab big glass place long', maybe: 'metal' },
  { id: 'liberty',    icon: '🗽', ar: 'تمثال الحرية', en: 'The Statue of Liberty', yes: 'big green metal', maybe: 'place' },
  /* ---------- nature ---------- */
  { id: 'rain',       icon: '🌧️', ar: 'مطر', en: 'Rain', yes: 'nature sky wet rainy', maybe: 'cold liquid noise' },
  { id: 'lightning',  icon: '⚡', ar: 'برق', en: 'Lightning', yes: 'nature sky light rainy', maybe: 'big yellow electric hot noise long' },
  { id: 'volcano',    icon: '🌋', ar: 'بركان', en: 'Volcano', yes: 'big nature hot place', maybe: 'red orange light noise flame' },
  { id: 'jasmine_f',  icon: '🌼', ar: 'فل', en: 'Jasmine', yes: 'small white nature plant smell' },
  { id: 'sunflower',  icon: '🌻', ar: 'عبّاد الشمس', en: 'Sunflower', yes: 'yellow nature plant seeds', maybe: 'big round' },
  { id: 'gold',       icon: '🪙', ar: 'دهب', en: 'Gold', yes: 'yellow metal nature', maybe: 'small wear' },
  { id: 'earth',      icon: '🌍', ar: 'الكرة الأرضية', en: 'The Earth', yes: 'big blue nature round', maybe: 'green sky colorful' },
  { id: 'mars',       icon: '🔴', ar: 'كوكب المريخ', en: 'Planet Mars', yes: 'big red nature sky round', maybe: 'place' },
  { id: 'island',     icon: '🏝️', ar: 'جزيرة', en: 'Island', yes: 'big nature place wet', maybe: 'green' },
  { id: 'waterfall',  icon: '💦', ar: 'شلّال', en: 'Waterfall', yes: 'big nature noise wet', maybe: 'blue place liquid' },
  { id: 'forest',     icon: '🌲', ar: 'غابة', en: 'Forest', yes: 'big green nature place', maybe: 'plant' },
  /* ---------- a few more ---------- */
  { id: 'burger',     icon: '🍔', ar: 'برجر', en: 'Burger', yes: 'brown edible dish hot round meat_t', maybe: 'street stuffed' },
  { id: 'soup',       icon: '🥣', ar: 'شوربة', en: 'Soup', yes: 'edible dish hot liquid', maybe: 'drink ramadan meat_t smell rainy' },
  { id: 'plum',       icon: '🫐', ar: 'برقوق', en: 'Plum', yes: 'small edible summer fruit sweet nature round soft', maybe: 'red' },
  { id: 'suitcase',   icon: '🧳', ar: 'شنطة سفر', en: 'Suitcase', yes: 'wheels container square', maybe: 'black home cloth twowheels travel' },
  { id: 'waterheater', icon: '🚿', ar: 'سخّان', en: 'Water heater', yes: 'electric bathroom hot wet', maybe: 'white home metal clean container' },
  { id: 'sewing',     icon: '🧵', ar: 'ماكينة خياطة', en: 'Sewing machine', yes: 'electric metal noise', maybe: 'engine home buttons sharp' },
  { id: 'flashlight', icon: '🔦', ar: 'كشّاف', en: 'Torch (flashlight)', yes: 'electric buttons handtool light', maybe: 'small home pocket long' },
  { id: 'ramadandeco', icon: '🎊', ar: 'زينة رمضان', en: 'Ramadan decorations', yes: 'ramadan street colorful long', maybe: 'egypt arab electric home paper cloth light' },
  { id: 'pool',       icon: '🏊', ar: 'حمّام سباحة', en: 'Swimming pool', yes: 'big blue summer place wet', maybe: 'sport square' },
  { id: 'bigben',     icon: '🕰️', ar: 'ساعة بيج بن', en: 'Big Ben', yes: 'big place noise time long', maybe: 'brown' },
  { id: 'petra',      icon: '🏜️', ar: 'البتراء', en: 'Petra', yes: 'arab big place', maybe: 'pink' },
  { id: 'tajmahal',   icon: '🕌', ar: 'تاج محل', en: 'The Taj Mahal', yes: 'big white place', maybe: 'round' },
  { id: 'tram',       icon: '🚋', ar: 'ترام', en: 'Tram', yes: 'big electric vehicle engine passengers wheels metal street fare standing', maybe: 'noise long' },
  { id: 'submarine',  icon: '🌊', ar: 'غوّاصة', en: 'Submarine', yes: 'big vehicle engine metal wet', maybe: 'gray passengers long' },
  { id: 'tractor',    icon: '🚜', ar: 'جرّار', en: 'Tractor', yes: 'big vehicle engine wheels metal noise cargo' },
  { id: 'hotballoon', icon: '🎈', ar: 'منطاد', en: 'Hot-air balloon', yes: 'flies big vehicle cloth sky colorful', maybe: 'passengers round fare flame' },
]};

const ORACLE_JOBS = { kind: 'j', list: [
  { id: 'doctor',     icon: '🩺', ar: 'دكتور', en: 'Doctor', yes: 'hospital rescue study night_j', maybe: 'uniform gov_j' },
  { id: 'nurse',      icon: '💉', ar: 'ممرضة', en: 'Nurse', yes: 'uniform hospital rescue night_j', maybe: 'gov_j stands_j' },
  { id: 'dentist',    icon: '🦷', ar: 'دكتور أسنان', en: 'Dentist', yes: 'hospital study', maybe: 'uniform stands_j', no: 'night_j rescue' },
  { id: 'vet',        icon: '🐾', ar: 'دكتور بيطري', en: 'Vet', yes: 'hospital study animals_j', maybe: 'uniform shop_j' },
  { id: 'teacher',    icon: '🧑‍🏫', ar: 'مدرّس', en: 'Teacher', yes: 'teach kids_j voice_j', maybe: 'study words_j gov_j stands_j' },
  { id: 'engineer',   icon: '👷', ar: 'مهندس', en: 'Engineer', yes: 'study build', maybe: 'outdoors desk power_j boss_j gov_j' },
  { id: 'pilot',      icon: '👨‍✈️', ar: 'طيّار', en: 'Pilot', yes: 'flies uniform drives night_j travel_j', maybe: 'study boss_j' },
  { id: 'astronaut',  icon: '👩‍🚀', ar: 'رائد فضاء', en: 'Astronaut', yes: 'flies uniform study danger_j', maybe: 'drives night_j travel_j lab_j gov_j' },
  { id: 'police',     icon: '👮', ar: 'ظابط شرطة', en: 'Police officer', yes: 'uniform outdoors rescue law night_j army_j danger_j gov_j', maybe: 'drives boss_j stands_j' },
  { id: 'firefighter', icon: '🧑‍🚒', ar: 'رجل مطافي', en: 'Firefighter', yes: 'wet uniform outdoors rescue fire_j night_j danger_j gov_j', maybe: 'drives army_j' },
  { id: 'chef',       icon: '🧑‍🍳', ar: 'شيف (طبّاخ)', en: 'Chef', yes: 'uniform food_j fire_j stands_j', maybe: 'hands night_j stage_j boss_j', no: 'sells' },
  { id: 'baker',      icon: '🥖', ar: 'فرّان', en: 'Baker', yes: 'hands food_j sells fire_j shop_j', maybe: 'night_j stands_j' },
  { id: 'butcher',    icon: '🥩', ar: 'جزّار', en: 'Butcher', yes: 'food_j animals_j sells shop_j scale_j stands_j', maybe: 'hands' },
  { id: 'farmer',     icon: '🧑‍🌾', ar: 'فلّاح', en: 'Farmer', yes: 'outdoors animals_j plants_j', maybe: 'wet hands food_j sells' },
  { id: 'fisherman',  icon: '🎣', ar: 'صيّاد سمك', en: 'Fisherman', yes: 'wet outdoors food_j sea_j', maybe: 'animals_j sells night_j danger_j' },
  { id: 'captain',    icon: '⚓', ar: 'قبطان مركب', en: 'Ship captain', yes: 'wet uniform drives sea_j travel_j boss_j', maybe: 'outdoors night_j' },
  { id: 'carpenter',  icon: '🪚', ar: 'نجّار', en: 'Carpenter', yes: 'hands build shop_j', maybe: 'house_j' },
  { id: 'plumber',    icon: '🔧', ar: 'سبّاك', en: 'Plumber', yes: 'wet hands build house_j', maybe: 'shop_j' },
  { id: 'electrician', icon: '⚡', ar: 'كهربائي', en: 'Electrician', yes: 'hands build power_j house_j', maybe: 'shop_j danger_j' },
  { id: 'mechanic',   icon: '🔩', ar: 'ميكانيكي', en: 'Mechanic', yes: 'hands build cars_j shop_j' },
  { id: 'driver',     icon: '🚕', ar: 'سوّاق', en: 'Driver', yes: 'outdoors drives cars_j travel_j', maybe: 'night_j' },
  { id: 'lawyer',     icon: '⚖️', ar: 'محامي', en: 'Lawyer', yes: 'desk study law voice_j', maybe: 'words_j' },
  { id: 'accountant', icon: '🧾', ar: 'محاسب', en: 'Accountant', yes: 'desk money_j', maybe: 'study power_j' },
  { id: 'programmer', icon: '👩‍💻', ar: 'مبرمج', en: 'Programmer', yes: 'desk power_j', maybe: 'study night_j' },
  { id: 'barber',     icon: '💈', ar: 'حلّاق', en: 'Barber', yes: 'hands looks_j shop_j stands_j' },
  { id: 'photographer', icon: '📸', ar: 'مصوّر', en: 'Photographer', yes: 'outdoors art_j', maybe: 'power_j shop_j travel_j film_j' },
  { id: 'artist',     icon: '🎨', ar: 'رسّام', en: 'Painter (artist)', yes: 'art_j hands' },
  { id: 'postman',    icon: '📮', ar: 'بوسطجي', en: 'Postman', yes: 'uniform outdoors gov_j', maybe: 'drives' },
  { id: 'waiter',     icon: '🍽️', ar: 'جرسون', en: 'Waiter', yes: 'uniform food_j stands_j', maybe: 'night_j' },
  { id: 'gardener',   icon: '🌷', ar: 'جنايني', en: 'Gardener', yes: 'outdoors hands plants_j', maybe: 'wet house_j' },
  /* ---------- added 9 Oct 2026: everyday Egyptian jobs and the classic ones ---------- */
  { id: 'ironer',     icon: '👔', ar: 'مكوجي', en: 'Ironing man (makwagi)', yes: 'hands shop_j clothes_j stands_j', maybe: 'fire_j looks_j clean_j' },
  { id: 'doorman',    icon: '🏢', ar: 'بوّاب', en: 'Doorman (bawab)', yes: 'outdoors night_j', maybe: 'rescue house_j army_j' },
  { id: 'tailor',     icon: '🧵', ar: 'ترزي (خيّاط)', en: 'Tailor', yes: 'hands looks_j shop_j clothes_j', maybe: 'art_j build' },
  { id: 'shoemaker',  icon: '👞', ar: 'جزمجي', en: 'Shoemaker', yes: 'hands build shop_j clothes_j', maybe: 'sells' },
  { id: 'builder',    icon: '🧱', ar: 'عامل بناء (بنّا)', en: 'Builder (mason)', yes: 'outdoors hands build stands_j', maybe: 'danger_j' },
  { id: 'housepainter', icon: '🖌️', ar: 'نقّاش', en: 'House painter', yes: 'hands build house_j stands_j', maybe: 'outdoors art_j' },
  { id: 'blacksmith', icon: '⚒️', ar: 'حدّاد', en: 'Blacksmith', yes: 'hands build fire_j shop_j' },
  { id: 'pharmacist', icon: '💊', ar: 'صيدلي', en: 'Pharmacist', yes: 'study sells shop_j', maybe: 'uniform hospital night_j lab_j scale_j stands_j' },
  { id: 'grocer',     icon: '🛒', ar: 'بقّال', en: 'Grocer', yes: 'food_j sells shop_j scale_j', maybe: 'money_j night_j stands_j' },
  { id: 'fulseller',  icon: '🫘', ar: 'بيّاع فول', en: 'Ful seller', yes: 'outdoors food_j sells fire_j cart_j stands_j', maybe: 'shop_j' },
  { id: 'erksous',    icon: '🥤', ar: 'بيّاع عرقسوس', en: 'Licorice-drink seller', yes: 'outdoors food_j sells uniform', maybe: 'cart_j music_j stands_j' },
  { id: 'cashier',    icon: '🧮', ar: 'كاشير', en: 'Cashier', yes: 'money_j shop_j', maybe: 'desk sells stands_j' },
  { id: 'presenter',  icon: '🎙️', ar: 'مذيع', en: 'TV presenter', yes: 'stage_j words_j voice_j', maybe: 'desk night_j' },
  { id: 'translator', icon: '🌐', ar: 'مترجم', en: 'Translator', yes: 'desk words_j', maybe: 'study travel_j voice_j' },
  { id: 'actor_j',    icon: '🎭', ar: 'ممثل', en: 'Actor', yes: 'art_j stage_j voice_j film_j', maybe: 'night_j music_j' },
  { id: 'singer_j',   icon: '🎤', ar: 'مطرب', en: 'Singer', yes: 'art_j stage_j music_j voice_j', maybe: 'night_j' },
  { id: 'musician',   icon: '🎻', ar: 'عازف', en: 'Musician', yes: 'art_j stage_j music_j', maybe: 'hands night_j film_j' },
  { id: 'footballer_j', icon: '⚽', ar: 'لاعب كورة', en: 'Footballer', yes: 'uniform outdoors sport_j', maybe: 'stage_j travel_j' },
  { id: 'coach_j',    icon: '📋', ar: 'مدرّب كورة', en: 'Football coach', yes: 'outdoors sport_j boss_j', maybe: 'uniform teach stage_j travel_j voice_j' },
  { id: 'stewardess', icon: '🛫', ar: 'مضيفة طيران', en: 'Flight attendant', yes: 'flies uniform food_j night_j travel_j' },
  { id: 'traindriver', icon: '🚆', ar: 'سوّاق قطر', en: 'Train driver', yes: 'drives night_j travel_j gov_j', maybe: 'uniform' },
  { id: 'streetcleaner', icon: '🧹', ar: 'عامل نضافة', en: 'Street cleaner', yes: 'uniform outdoors clean_j gov_j' },
  { id: 'shepherd',   icon: '🐑', ar: 'راعي غنم', en: 'Shepherd', yes: 'outdoors animals_j', maybe: 'food_j' },
  { id: 'nanny',      icon: '🍼', ar: 'دادة (جليسة أطفال)', en: 'Nanny', yes: 'kids_j house_j' },
  { id: 'professor',  icon: '🎓', ar: 'أستاذ جامعة', en: 'University professor', yes: 'teach study voice_j', maybe: 'desk words_j lab_j gov_j' },
  { id: 'scientist',  icon: '🔬', ar: 'عالِم', en: 'Scientist', yes: 'study lab_j', maybe: 'uniform teach desk gov_j scale_j' },
  { id: 'paperseller', icon: '📰', ar: 'بيّاع جرايد', en: 'Newspaper seller', yes: 'outdoors sells', maybe: 'shop_j words_j' },
  { id: 'jeweller',   icon: '💍', ar: 'جواهرجي', en: 'Jeweller', yes: 'sells shop_j scale_j', maybe: 'hands art_j looks_j money_j' },
  { id: 'phonefixer', icon: '📱', ar: 'مصلّح موبايلات', en: 'Phone repairer', yes: 'hands build power_j shop_j', maybe: 'sells' },
  { id: 'trafficcop', icon: '🚦', ar: 'عسكري مرور', en: 'Traffic policeman', yes: 'uniform outdoors cars_j army_j gov_j stands_j', maybe: 'rescue law night_j' },
  { id: 'petrolman',  icon: '⛽', ar: 'عامل بنزينة', en: 'Petrol station attendant', yes: 'uniform outdoors sells cars_j stands_j', maybe: 'money_j night_j' },
  { id: 'fashion',    icon: '👗', ar: 'مصمّم أزياء', en: 'Fashion designer', yes: 'art_j looks_j clothes_j', maybe: 'desk' },
  { id: 'lifeguard',  icon: '🛟', ar: 'منقذ (على البحر)', en: 'Lifeguard', yes: 'wet outdoors rescue sea_j', maybe: 'uniform sport_j danger_j' },
  { id: 'florist',    icon: '💐', ar: 'بيّاع ورد', en: 'Florist', yes: 'sells shop_j plants_j', maybe: 'art_j' },
  { id: 'clown',      icon: '🤡', ar: 'مهرّج', en: 'Clown', yes: 'kids_j stage_j voice_j', maybe: 'outdoors art_j' },
  { id: 'icecreamman', icon: '🍦', ar: 'بيّاع آيس كريم', en: 'Ice-cream seller', yes: 'outdoors food_j sells cart_j', maybe: 'kids_j stands_j' },
  { id: 'potter',     icon: '🏺', ar: 'فخراني', en: 'Potter', yes: 'hands art_j fire_j', maybe: 'sells build shop_j' },
  { id: 'tourguide',  icon: '🗺️', ar: 'مرشد سياحي', en: 'Tour guide', yes: 'outdoors words_j travel_j voice_j', maybe: 'study' },
  { id: 'delivery',   icon: '🛵', ar: 'دليفري', en: 'Delivery rider', yes: 'outdoors drives house_j', maybe: 'uniform food_j cars_j night_j' },
  { id: 'mesaharati', icon: '🪘', ar: 'مسحّراتي', en: 'Mesaharati (the Ramadan drummer)', yes: 'outdoors night_j music_j voice_j', maybe: 'art_j' },
  { id: 'ahwagi',     icon: '☕', ar: 'قهوجي', en: 'Café waiter (ahwagi)', yes: 'food_j fire_j night_j shop_j stands_j', maybe: 'sells' },
  { id: 'sayes',      icon: '🅿️', ar: 'سايس', en: 'Parking attendant', yes: 'outdoors cars_j stands_j', maybe: 'drives money_j night_j' },
  { id: 'archaeologist', icon: '🏺', ar: 'عالم آثار', en: 'Archaeologist', yes: 'outdoors study', maybe: 'teach travel_j lab_j gov_j' },
  { id: 'paramedic',  icon: '🚑', ar: 'مسعف', en: 'Paramedic', yes: 'uniform outdoors rescue night_j gov_j', maybe: 'hospital drives danger_j' },
  { id: 'designer',   icon: '🖥️', ar: 'مصمّم جرافيك', en: 'Graphic designer', yes: 'art_j desk power_j' },
  { id: 'conductor',  icon: '🎫', ar: 'كمسري', en: 'Bus conductor', yes: 'money_j travel_j', maybe: 'uniform outdoors cars_j voice_j gov_j' },
  { id: 'fishmonger', icon: '🐟', ar: 'بيّاع سمك', en: 'Fishmonger', yes: 'wet food_j sells shop_j scale_j stands_j', maybe: 'outdoors animals_j sea_j' },
  { id: 'arbagi',     icon: '🐎', ar: 'عربجي (سوّاق حنطور)', en: 'Carriage driver', yes: 'outdoors drives animals_j travel_j' },
  { id: 'sailor',     icon: '⛵', ar: 'بحّار', en: 'Sailor', yes: 'wet uniform sea_j travel_j', maybe: 'outdoors drives night_j danger_j' },
  { id: 'shoeshiner', icon: '🥾', ar: 'ماسح جزم', en: 'Shoeshiner', yes: 'outdoors clothes_j clean_j', maybe: 'hands looks_j' },
  { id: 'carwasher',  icon: '🚿', ar: 'غسّال عربيات', en: 'Car washer', yes: 'wet outdoors cars_j clean_j stands_j', maybe: 'hands' },
  { id: 'garbageman', icon: '🗑️', ar: 'زبّال', en: 'Rubbish collector', yes: 'outdoors clean_j house_j', maybe: 'uniform drives' },
  { id: 'zookeeper',  icon: '🦁', ar: 'حارس جنينة الحيوانات', en: 'Zookeeper', yes: 'uniform outdoors animals_j', maybe: 'danger_j gov_j' },
  { id: 'factory',    icon: '🏭', ar: 'عامل في مصنع', en: 'Factory worker', yes: 'uniform hands build', maybe: 'fire_j night_j stands_j' },
  { id: 'peteacher',  icon: '🤸', ar: 'مدرّس ألعاب', en: 'PE teacher', yes: 'teach outdoors kids_j sport_j voice_j', maybe: 'uniform gov_j' },
  { id: 'clothseller', icon: '🛍️', ar: 'بيّاع هدوم', en: 'Clothes seller', yes: 'sells shop_j clothes_j', maybe: 'looks_j stands_j' },
  { id: 'boatman',    icon: '🛶', ar: 'مراكبي', en: 'Boatman', yes: 'wet outdoors drives sea_j travel_j' },
  { id: 'pediatrician', icon: '👶', ar: 'دكتور أطفال', en: 'Paediatrician', yes: 'hospital rescue study kids_j', maybe: 'uniform night_j' },
  { id: 'beekeeper',  icon: '🐝', ar: 'نحّال', en: 'Beekeeper', yes: 'outdoors food_j animals_j uniform', maybe: 'hands sells plants_j danger_j' },
  { id: 'liontamer',  icon: '🎪', ar: 'مدرّب أسود في السيرك', en: 'Circus lion tamer', yes: 'animals_j stage_j danger_j', maybe: 'kids_j' },
  { id: 'calligrapher', icon: '🖋️', ar: 'خطّاط', en: 'Calligrapher', yes: 'hands art_j words_j', maybe: 'desk shop_j' },
]};
