/* العرّاف: famous people (kind 'p'). Egyptian and Arab first, then the world-famous; only
   facts that don't change (where they are from, what they did, what they won, when they were
   born) - never whether they are alive or still playing. No politicians of our time, nothing
   divisive. One line each: id, icon (what they are known for, shown on a drawn silhouette -
   never a photo), ar, en, and the question ids (OracleQuestions.js) that are true (yes),
   partly (maybe) and firmly not (no). A question about people in none of the three reads as
   «غالباً لأ». notes/games/oracle.md, "Writing entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_PEOPLE = { kind: 'p', list: [
  /* ---------- football ---------- */
  { id: 'salah',       icon: '⚽', ar: 'محمد صلاح', en: 'Mohamed Salah', yes: 'egypt england striker', no: 'ahly zamalek worldcup afcon' },
  { id: 'aboutrika',   icon: '⚽', ar: 'محمد أبو تريكة', en: 'Mohamed Aboutrika', yes: 'egypt ahly afcon', no: 'zamalek england' },
  { id: 'hossamhassan', icon: '⚽', ar: 'حسام حسن', en: 'Hossam Hassan', yes: 'egypt ahly zamalek striker afcon coach' },
  { id: 'hadary',      icon: '🧤', ar: 'عصام الحضري', en: 'Essam El-Hadary', yes: 'egypt ahly keeper afcon', maybe: 'zamalek' },
  { id: 'khatib',      icon: '⚽', ar: 'محمود الخطيب', en: 'Mahmoud El Khatib', yes: 'egypt ahly striker afcon', no: 'zamalek' },
  { id: 'shikabala',   icon: '⚽', ar: 'شيكابالا', en: 'Shikabala', yes: 'egypt zamalek', no: 'ahly' },
  { id: 'ahmedhassan', icon: '⚽', ar: 'أحمد حسن', en: 'Ahmed Hassan', yes: 'egypt ahly zamalek afcon', no: 'striker' },
  { id: 'elneny',      icon: '⚽', ar: 'محمد النني', en: 'Mohamed Elneny', yes: 'egypt england', no: 'ahly zamalek striker' },
  { id: 'messi',       icon: '⚽', ar: 'ليونيل ميسي', en: 'Lionel Messi', yes: 'latam spain worldcup ballon striker' },
  { id: 'ronaldo',     icon: '⚽', ar: 'كريستيانو رونالدو', en: 'Cristiano Ronaldo', yes: 'europe england spain ballon striker', no: 'worldcup' },
  { id: 'zidane',      icon: '⚽', ar: 'زين الدين زيدان', en: 'Zinedine Zidane', yes: 'europe spain worldcup ballon coach', maybe: 'maghreb' },
  { id: 'maradona',    icon: '⚽', ar: 'دييجو مارادونا', en: 'Diego Maradona', yes: 'latam spain worldcup coach', maybe: 'striker' },
  { id: 'pele',        icon: '⚽', ar: 'بيليه', en: 'Pelé', yes: 'latam worldcup striker born1950' },
  { id: 'mahrez',      icon: '⚽', ar: 'رياض محرز', en: 'Riyad Mahrez', yes: 'maghreb england afcon' },
  { id: 'hakimi',      icon: '⚽', ar: 'أشرف حكيمي', en: 'Achraf Hakimi', yes: 'maghreb spain', no: 'striker' },
  { id: 'mane',        icon: '⚽', ar: 'ساديو ماني', en: 'Sadio Mané', yes: 'africa england afcon striker' },
  /* ---------- other sports ---------- */
  { id: 'muhammadali', icon: '🥊', ar: 'محمد علي كلاي', en: 'Muhammad Ali', yes: 'usa fighter othersport olympic born1950' },
  { id: 'bolt',        icon: '🏃', ar: 'يوسين بولت', en: 'Usain Bolt', yes: 'othersport olympic' },
  { id: 'jordan',      icon: '🏀', ar: 'مايكل جوردان', en: 'Michael Jordan', yes: 'usa othersport olympic' },
  { id: 'karamgaber',  icon: '🤼', ar: 'كرم جابر', en: 'Karam Gaber', yes: 'egypt othersport olympic fighter' },
  /* ---------- actors ---------- */
  { id: 'adelimam',    icon: '🎭', ar: 'عادل إمام', en: 'Adel Imam', yes: 'egypt actor comedy theater born1950', maybe: 'series bw', no: 'born1930' },
  { id: 'ahmedzaki',   icon: '🎬', ar: 'أحمد زكي', en: 'Ahmed Zaki', yes: 'egypt actor born1950', no: 'comedy' },
  { id: 'omarsharif',  icon: '🎬', ar: 'عمر الشريف', en: 'Omar Sharif', yes: 'egypt actor hollywood bw born1950' },
  { id: 'ismailyassin', icon: '😂', ar: 'إسماعيل ياسين', en: 'Ismail Yassin', yes: 'egypt actor comedy bw born1930', maybe: 'theater singer' },
  { id: 'fouad',       icon: '🎭', ar: 'فؤاد المهندس', en: 'Fouad El-Mohandes', yes: 'egypt actor comedy theater bw born1930 series fawazeer' },
  { id: 'fareedshawqi', icon: '🎬', ar: 'فريد شوقي', en: 'Farid Shawqi', yes: 'egypt actor bw born1930 action' },
  { id: 'henedy',      icon: '😄', ar: 'محمد هنيدي', en: 'Mohamed Henedy', yes: 'egypt actor comedy', maybe: 'theater' },
  { id: 'helmy',       icon: '😄', ar: 'أحمد حلمي', en: 'Ahmed Helmy', yes: 'egypt actor comedy tvhost', no: 'theater' },
  { id: 'fakharany',   icon: '🎭', ar: 'يحيى الفخراني', en: 'Yehia El-Fakharany', yes: 'egypt actor series theater born1950' },
  { id: 'sakka',       icon: '🎬', ar: 'أحمد السقا', en: 'Ahmed El Sakka', yes: 'egypt actor action', no: 'comedy' },
  { id: 'faten',       icon: '🎬', ar: 'فاتن حمامة', en: 'Faten Hamama', yes: 'female egypt actor bw born1950' },
  { id: 'soad',        icon: '🎬', ar: 'سعاد حسني', en: 'Soad Hosny', yes: 'female egypt actor bw born1950 singer' },
  { id: 'sherihan',    icon: '💃', ar: 'شريهان', en: 'Sherihan', yes: 'female egypt actor fawazeer', maybe: 'series singer theater' },
  { id: 'yousra',      icon: '🎬', ar: 'يسرا', en: 'Yousra', yes: 'female egypt actor series' },
  { id: 'chaplin',     icon: '🎩', ar: 'شارلي شابلن', en: 'Charlie Chaplin', yes: 'europe actor comedy bw hollywood born1930' },
  { id: 'brucelee',    icon: '🥋', ar: 'بروس لي', en: 'Bruce Lee', yes: 'asia actor action fighter hollywood born1950' },
  { id: 'jackiechan',  icon: '🥋', ar: 'جاكي شان', en: 'Jackie Chan', yes: 'asia actor action fighter hollywood', maybe: 'comedy' },
  /* ---------- singers and musicians ---------- */
  { id: 'umkulthum',   icon: '🎤', ar: 'أم كلثوم', en: 'Umm Kulthum', yes: 'female egypt singer born1930 bw', maybe: 'actor' },
  { id: 'abdelhalim',  icon: '🎤', ar: 'عبد الحليم حافظ', en: 'Abdel Halim Hafez', yes: 'egypt singer actor bw born1930' },
  { id: 'abdelwahab',  icon: '🎼', ar: 'محمد عبد الوهاب', en: 'Mohamed Abdel Wahab', yes: 'egypt singer composer bw born1930', maybe: 'actor' },
  { id: 'fareedatrash', icon: '🎼', ar: 'فريد الأطرش', en: 'Farid al-Atrash', yes: 'levant singer composer actor bw born1930', maybe: 'egypt' },
  { id: 'sayeddarwish', icon: '🎼', ar: 'سيد درويش', en: 'Sayed Darwish', yes: 'egypt composer singer born1930', no: 'bw actor' },
  { id: 'fairuz',      icon: '🎤', ar: 'فيروز', en: 'Fairuz', yes: 'female levant singer born1950' },
  { id: 'warda',       icon: '🎤', ar: 'وردة الجزائرية', en: 'Warda', yes: 'female maghreb singer born1950', maybe: 'egypt actor' },
  { id: 'amrdiab',     icon: '🎤', ar: 'عمرو دياب', en: 'Amr Diab', yes: 'egypt singer', maybe: 'composer' },
  { id: 'mounir',      icon: '🎤', ar: 'محمد منير', en: 'Mohamed Mounir', yes: 'south singer', maybe: 'actor' },
  { id: 'tamer',       icon: '🎤', ar: 'تامر حسني', en: 'Tamer Hosny', yes: 'egypt singer actor', maybe: 'composer comedy' },
  { id: 'sherine',     icon: '🎤', ar: 'شيرين عبد الوهاب', en: 'Sherine', yes: 'female egypt singer' },
  { id: 'nancy',       icon: '🎤', ar: 'نانسي عجرم', en: 'Nancy Ajram', yes: 'female levant singer' },
  { id: 'kazem',       icon: '🎤', ar: 'كاظم الساهر', en: 'Kadim Al Sahir', yes: 'gulf singer composer' },
  { id: 'mj',          icon: '🕺', ar: 'مايكل جاكسون', en: 'Michael Jackson', yes: 'usa singer' },
  { id: 'mozart',      icon: '🎹', ar: 'موتسارت', en: 'Mozart', yes: 'europe composer before1800' },
  /* ---------- history ---------- */
  { id: 'ramses',      icon: '👑', ar: 'رمسيس التاني', en: 'Ramesses II', yes: 'egypt pharaoh ruler warrior' },
  { id: 'tut',         icon: '👑', ar: 'توت عنخ آمون', en: 'Tutankhamun', yes: 'egypt pharaoh ruler', no: 'warrior' },
  { id: 'nefertiti',   icon: '👑', ar: 'نفرتيتي', en: 'Nefertiti', yes: 'female egypt pharaoh ruler' },
  { id: 'cleopatra',   icon: '👑', ar: 'كليوباترا', en: 'Cleopatra', yes: 'female ruler bc', maybe: 'egypt' },
  { id: 'alexander',   icon: '⚔️', ar: 'الإسكندر الأكبر', en: 'Alexander the Great', yes: 'europe bc ruler warrior' },
  { id: 'saladin',     icon: '⚔️', ar: 'صلاح الدين الأيوبي', en: 'Saladin', yes: 'before1800 ruler warrior', maybe: 'arab egypt' },
  { id: 'napoleon',    icon: '⚔️', ar: 'نابليون بونابرت', en: 'Napoleon', yes: 'europe before1800 ruler warrior' },
  { id: 'mutanabbi',   icon: '📜', ar: 'المتنبي', en: 'Al-Mutanabbi', yes: 'gulf poet before1800' },
  { id: 'ibnsina',     icon: '⚕️', ar: 'ابن سينا', en: 'Avicenna', yes: 'before1800 science medic', maybe: 'writer arab' },
  { id: 'khwarizmi',   icon: '🧮', ar: 'الخوارزمي', en: 'Al-Khwarizmi', yes: 'before1800 science', maybe: 'arab' },
  { id: 'ibnbattuta',  icon: '🧭', ar: 'ابن بطوطة', en: 'Ibn Battuta', yes: 'maghreb before1800 explorer', maybe: 'writer' },
  { id: 'davinci',     icon: '🎨', ar: 'ليوناردو دافنشي', en: 'Leonardo da Vinci', yes: 'europe painter science before1800' },
  { id: 'shakespeare', icon: '✍️', ar: 'شكسبير', en: 'Shakespeare', yes: 'europe writer poet before1800' },
  { id: 'newton',      icon: '🍎', ar: 'إسحاق نيوتن', en: 'Isaac Newton', yes: 'europe science before1800' },
  /* ---------- science, letters, the arts ---------- */
  { id: 'zewail',      icon: '🔬', ar: 'أحمد زويل', en: 'Ahmed Zewail', yes: 'egypt science nobel', maybe: 'usa' },
  { id: 'mahfouz',     icon: '✍️', ar: 'نجيب محفوظ', en: 'Naguib Mahfouz', yes: 'egypt writer nobel born1930' },
  { id: 'tahahussein', icon: '✍️', ar: 'طه حسين', en: 'Taha Hussein', yes: 'egypt writer blind born1930' },
  { id: 'shawqi',      icon: '📜', ar: 'أحمد شوقي', en: 'Ahmed Shawqi', yes: 'egypt poet born1930' },
  { id: 'magdiyacoub', icon: '🫀', ar: 'مجدي يعقوب', en: 'Magdi Yacoub', yes: 'egypt medic born1950', maybe: 'science' },
  { id: 'einstein',    icon: '🧠', ar: 'أينشتاين', en: 'Albert Einstein', yes: 'europe science nobel born1930', maybe: 'usa' },
  { id: 'curie',       icon: '⚛️', ar: 'ماري كوري', en: 'Marie Curie', yes: 'female europe science nobel born1930' },
  { id: 'edison',      icon: '💡', ar: 'توماس إديسون', en: 'Thomas Edison', yes: 'usa science born1930' },
  { id: 'armstrong',   icon: '🚀', ar: 'نيل أرمسترونج', en: 'Neil Armstrong', yes: 'usa explorer born1950' },
  { id: 'picasso',     icon: '🎨', ar: 'بيكاسو', en: 'Pablo Picasso', yes: 'europe painter born1930' },
]};
