/* العرّاف (The Oracle): the questions it can ask. Page only (its chunk, tools/lazy-split.mjs);
   the engine is Oracle.js, the entries OraclePeople.js, OracleCharacters.js, OracleAnimals.js,
   OracleThings.js. How to write an entry: notes/games/oracle.md, "Writing entries".

   Each question:
     id     a short name the entries use in their yes / no / maybe lists (never change one).
     kinds  the kinds it is asked about, one letter each: p a famous person, c a character
            (cartoon, film, tale, game), a an animal, t a thing (food, object, place, nature),
            j a job. For an entry of any other kind the answer is a firm «لأ».
     auto   (optional) the answer every entry of a kind has without saying it: 'p:y c:n' -
            an entry's own lists still win.
     implies (optional) the ids an entry with this trait has too ('ahly' implies 'football').
   The wording is about things that don't change: never «لسه عايش؟» or «لسه بيلعب؟». */
const ORACLE_QUESTIONS = [
  /* ---------- what kind of thing it is (asked like any other question, never picked first) ---------- */
  { id: 'human',   kinds: 'pcatj', auto: 'p:y a:n t:n j:y', ar: 'هو إنسان؟', en: 'Is it a human?' },
  { id: 'real',    kinds: 'pcatj', auto: 'p:y c:n a:n t:n j:n', ar: 'شخص حقيقي مشهور؟', en: 'A real, famous person?' },
  { id: 'fiction', kinds: 'pcatj', auto: 'p:n c:y a:n t:n j:n', ar: 'شخصية من كارتون أو فيلم أو حكاية؟', en: 'A character from a cartoon, film or tale?' },
  { id: 'animal',  kinds: 'pcatj', auto: 'p:n a:y t:n j:n', ar: 'حيوان (أو طير أو سمكة أو حشرة)؟', en: 'An animal (or a bird, a fish, an insect)?' },
  { id: 'job',     kinds: 'pcatj', auto: 'p:n c:n a:n t:n j:y', ar: 'شغلانة (مهنة)؟', en: 'A job?' },
  { id: 'object',  kinds: 'pcatj', auto: 'p:n a:n t:y j:n', ar: 'حاجة، مش إنسان ولا حيوان؟', en: 'A thing, not a person or an animal?' },

  /* ---------- people (and some characters) ---------- */
  { id: 'female',  kinds: 'pc', ar: 'ست أو بنت؟', en: 'A woman or a girl?' },
  { id: 'egypt',   kinds: 'pct', implies: ['arab'], ar: 'مصري؟', en: 'Egyptian?' },
  { id: 'arab',    kinds: 'pct', ar: 'عربي؟', en: 'Arab?' },
  { id: 'levant',  kinds: 'p', implies: ['arab'], ar: 'من لبنان أو سوريا أو فلسطين أو الأردن؟', en: 'From Lebanon, Syria, Palestine or Jordan?' },
  { id: 'gulf',    kinds: 'p', implies: ['arab'], ar: 'من الخليج أو العراق؟', en: 'From the Gulf or Iraq?' },
  { id: 'maghreb', kinds: 'p', implies: ['arab'], ar: 'من المغرب أو الجزائر أو تونس؟', en: 'From Morocco, Algeria or Tunisia?' },
  { id: 'south',   kinds: 'p', implies: ['egypt'], ar: 'من الصعيد أو النوبة؟', en: 'From Upper Egypt or Nubia?' },
  { id: 'europe',  kinds: 'p', ar: 'أوروبي؟', en: 'European?' },
  { id: 'usa',     kinds: 'p', ar: 'من أمريكا (الولايات المتحدة)؟', en: 'From the United States?' },
  { id: 'latam',   kinds: 'p', ar: 'من أمريكا الجنوبية؟', en: 'From South America?' },
  { id: 'africa',  kinds: 'p', ar: 'من بلد أفريقي مش عربي؟', en: 'From an African country that is not Arab?' },
  { id: 'asia',    kinds: 'p', ar: 'من شرق آسيا (زي الصين واليابان)؟', en: 'From East Asia (China, Japan…)?' },
  { id: 'before1800', kinds: 'p', ar: 'عاش قبل سنة 1800؟', en: 'Lived before the year 1800?' },
  { id: 'bc',      kinds: 'p', implies: ['before1800'], ar: 'عاش من أكتر من ألفين سنة؟', en: 'Lived more than two thousand years ago?' },
  { id: 'pharaoh', kinds: 'p', implies: ['bc'], ar: 'من أيام الفراعنة؟', en: 'From the time of the pharaohs?' },
  { id: 'born1930', kinds: 'p', implies: ['born1950'], ar: 'اتولد قبل سنة 1930؟', en: 'Born before 1930?' },
  { id: 'born1950', kinds: 'p', ar: 'اتولد قبل سنة 1950؟', en: 'Born before 1950?' },
  { id: 'ruler',   kinds: 'pc', ar: 'ملك أو ملكة أو حاكم؟', en: 'A king, a queen or a ruler?' },
  { id: 'warrior', kinds: 'pc', ar: 'قائد حروب أو فارس؟', en: 'A war leader or a warrior?' },
  { id: 'actor',   kinds: 'p', ar: 'ممثل؟', en: 'An actor?' },
  { id: 'comedy',  kinds: 'pc', ar: 'اشتهر بالكوميديا؟', en: 'Known for comedy?' },
  { id: 'bw',      kinds: 'p', ar: 'مثّل في أفلام أبيض وإسود؟', en: 'Acted in black-and-white films?' },
  { id: 'theater', kinds: 'p', ar: 'اشتهر بالمسرح؟', en: 'Known for the stage (theatre)?' },
  { id: 'action',  kinds: 'p', ar: 'اشتهر بأفلام الأكشن؟', en: 'Known for action films?' },
  { id: 'hollywood', kinds: 'p', ar: 'مثّل في أفلام هوليوود؟', en: 'Acted in Hollywood films?' },
  { id: 'series',  kinds: 'p', ar: 'اشتهر بمسلسلات التلفزيون؟', en: 'Known for TV series?' },
  { id: 'fawazeer', kinds: 'pc', ar: 'اشتهر بفوازير رمضان؟', en: 'Known for the Ramadan riddle shows (fawazeer)?' },
  { id: 'tvhost',  kinds: 'p', ar: 'قدّم برامج تلفزيون؟', en: 'Presented TV shows?' },
  { id: 'singer',  kinds: 'p', ar: 'مطرب أو مغنّي؟', en: 'A singer?' },
  { id: 'composer', kinds: 'p', ar: 'ملحّن أو موسيقار؟', en: 'A composer or a musician?' },
  { id: 'athlete', kinds: 'pc', ar: 'رياضي؟', en: 'An athlete?' },
  { id: 'football', kinds: 'pc', implies: ['athlete'], ar: 'لاعب كورة؟', en: 'A footballer?' },
  { id: 'ahly',    kinds: 'p', implies: ['football'], ar: 'لعب في الأهلي؟', en: 'Played for Al Ahly?' },
  { id: 'zamalek', kinds: 'p', implies: ['football'], ar: 'لعب في الزمالك؟', en: 'Played for Zamalek?' },
  { id: 'england', kinds: 'p', implies: ['football'], ar: 'لعب في الدوري الإنجليزي؟', en: 'Played in the English league?' },
  { id: 'spain',   kinds: 'p', implies: ['football'], ar: 'لعب في الدوري الإسباني؟', en: 'Played in the Spanish league?' },
  { id: 'keeper',  kinds: 'p', implies: ['football'], ar: 'حارس مرمى؟', en: 'A goalkeeper?' },
  { id: 'striker', kinds: 'p', implies: ['football'], ar: 'مهاجم؟', en: 'A striker?' },
  { id: 'worldcup', kinds: 'p', implies: ['football'], ar: 'كسب كاس العالم؟', en: 'Won the World Cup?' },
  { id: 'afcon',   kinds: 'p', implies: ['football'], ar: 'كسب كاس أمم أفريقيا؟', en: 'Won the Africa Cup of Nations?' },
  { id: 'ballon',  kinds: 'p', implies: ['football'], ar: 'خد الكورة الدهبية؟', en: "Won the Ballon d'Or?" },
  { id: 'coach',   kinds: 'p', ar: 'اشتغل مدرّب كورة؟', en: 'Worked as a football coach?' },
  { id: 'othersport', kinds: 'p', implies: ['athlete'], ar: 'بيلعب رياضة غير الكورة؟', en: 'Plays a sport other than football?' },
  { id: 'fighter', kinds: 'pc', ar: 'ملاكم أو بيلعب رياضة قتال؟', en: 'A boxer or a fighter?' },
  { id: 'olympic', kinds: 'p', ar: 'خد ميدالية أولمبية؟', en: 'Won an Olympic medal?' },
  { id: 'writer',  kinds: 'p', ar: 'كاتب أو شاعر؟', en: 'A writer or a poet?' },
  { id: 'poet',    kinds: 'p', implies: ['writer'], ar: 'شاعر؟', en: 'A poet?' },
  { id: 'science', kinds: 'p', ar: 'عالِم أو مخترع؟', en: 'A scientist or an inventor?' },
  { id: 'medic',   kinds: 'p', ar: 'دكتور (طبيب)؟', en: 'A doctor (of medicine)?' },
  { id: 'nobel',   kinds: 'p', ar: 'خد جايزة نوبل؟', en: 'Won a Nobel Prize?' },
  { id: 'painter', kinds: 'p', ar: 'رسّام؟', en: 'A painter?' },
  { id: 'explorer', kinds: 'pc', ar: 'رحّالة أو مستكشف أو راح الفضاء؟', en: 'A traveller, an explorer or an astronaut?' },
  { id: 'blind',   kinds: 'p', ar: 'كان كفيف؟', en: 'Was blind?' },

  /* ---------- characters ---------- */
  { id: 'cartoon', kinds: 'c', ar: 'كارتون (رسوم متحركة)؟', en: 'A cartoon (animated)?' },
  { id: 'disney',  kinds: 'c', ar: 'من أفلام ديزني؟', en: 'From a Disney film?' },
  { id: 'anime',   kinds: 'c', ar: 'من كارتون ياباني (أنمي)؟', en: 'From a Japanese cartoon (anime)?' },
  { id: 'liveaction', kinds: 'c', ar: 'بيمثّله ممثل حقيقي؟', en: 'Played by a real actor?' },
  { id: 'hero',    kinds: 'c', ar: 'سوبر هيرو؟', en: 'A superhero?' },
  { id: 'powers',  kinds: 'c', ar: 'عنده قوى خارقة أو بيعمل سحر؟', en: 'Has superpowers or does magic?' },
  { id: 'villain', kinds: 'c', ar: 'شرير؟', en: 'A villain?' },
  { id: 'princess', kinds: 'c', implies: ['female'], ar: 'أميرة؟', en: 'A princess?' },
  { id: 'tale',    kinds: 'c', ar: 'من حكاية قديمة أو ألف ليلة وليلة؟', en: 'From an old tale or the Arabian Nights?' },
  { id: 'kidshow', kinds: 'c', ar: 'من برنامج أو مسلسل للأطفال؟', en: 'From a show for children?' },
  { id: 'videogame', kinds: 'c', ar: 'من لعبة فيديو؟', en: 'From a video game?' },
  { id: 'child',   kinds: 'c', ar: 'طفل أو صغير في السن؟', en: 'A child?' },
  { id: 'mask',    kinds: 'c', ar: 'لابس قناع؟', en: 'Wears a mask?' },
  { id: 'hat',     kinds: 'c', ar: 'لابس طاقية أو قبعة؟', en: 'Wears a cap or a hat?' },
  { id: 'robot',   kinds: 'c', ar: 'روبوت أو آلة أو عربية؟', en: 'A robot, a machine or a car?' },
  { id: 'detective', kinds: 'c', ar: 'محقق بيحل ألغاز؟', en: 'A detective who solves mysteries?' },
  { id: 'group',   kinds: 'c', ar: 'جزء من مجموعة شبه بعض (زي السنافر)؟', en: 'One of a group who look alike (like the Smurfs)?' },
  { id: 'duo',     kinds: 'c', ar: 'دايماً معاه صاحبه أو اتنين مع بعض؟', en: 'Always with a partner, or a pair?' },
  /* added with the characters of phase 2 (9 Oct 2026): every character was gone over for each */
  { id: 'glasses', kinds: 'c', ar: 'لابس نضارة؟', en: 'Wears glasses?' },
  { id: 'beard',   kinds: 'c', ar: 'ليه دقن أو شنب؟', en: 'Has a beard or a moustache?' },
  { id: 'weapon',  kinds: 'c', ar: 'بيشيل سيف أو سلاح؟', en: 'Carries a sword or a weapon?' },
  { id: 'cape',    kinds: 'c', ar: 'لابس كاب (عباية طويلة على ضهره)؟', en: 'Wears a cape?' },
  { id: 'old',     kinds: 'c', ar: 'عجوز أو كبير في السن؟', en: 'Old?' },
  { id: 'cat',     kinds: 'c', implies: ['mammal'], ar: 'قطة أو من عيلة القطط (أسد، نمر)؟', en: 'A cat, or of the cat family (a lion, a tiger)?' },
  { id: 'dog',     kinds: 'c', implies: ['mammal'], ar: 'كلب؟', en: 'A dog?' },
  { id: 'mouse',   kinds: 'c', implies: ['mammal'], ar: 'فار؟', en: 'A mouse or a rat?' },
  { id: 'series_c', kinds: 'c', ar: 'من مسلسل (كارتون أو تمثيل)، مش فيلم؟', en: 'From a series (cartoon or acted), not a film?' },
  { id: 'classic', kinds: 'c', ar: 'ظهر أول مرة قبل سنة 2000؟', en: 'First appeared before the year 2000?' },
  { id: 'ramadan_c', kinds: 'c', ar: 'اتعرض في رمضان؟', en: 'Shown in Ramadan?' },
  { id: 'alien',   kinds: 'c', ar: 'جاي من الفضاء أو من كوكب تاني؟', en: 'From space or another planet?' },

  /* ---------- animals (and animal characters) ---------- */
  { id: 'mammal',  kinds: 'ac', ar: 'بيرضّع صغاره (من الثدييات)؟', en: 'Feeds its young milk (a mammal)?' },
  { id: 'bird',    kinds: 'ac', ar: 'طير؟', en: 'A bird?' },
  { id: 'fish',    kinds: 'ac', ar: 'سمكة؟', en: 'A fish?' },
  { id: 'reptile', kinds: 'ac', ar: 'زاحف (تعبان أو سحلية أو تمساح أو سلحفاة)؟', en: 'A reptile (snake, lizard, crocodile, turtle)?' },
  { id: 'insect',  kinds: 'ac', ar: 'حشرة أو عنكبوت؟', en: 'An insect or a spider?' },
  { id: 'colony',  kinds: 'a', ar: 'عايش في جماعة كبيرة؟', en: 'Lives in a big group (a colony, a flock)?' },
  { id: 'water',   kinds: 'ac', ar: 'عايش في المية؟', en: 'Lives in water?' },
  { id: 'pet',     kinds: 'a', ar: 'بيتربّى في البيت؟', en: 'Kept as a pet?' },
  { id: 'farm',    kinds: 'a', ar: 'من حيوانات المزرعة أو الغيط؟', en: 'A farm animal?' },
  { id: 'wild',    kinds: 'a', ar: 'عايش في الغابة أو البرية؟', en: 'Lives in the wild?' },
  { id: 'meat',    kinds: 'a', ar: 'بياكل لحمة (مفترس)؟', en: 'Eats meat (a hunter)?' },
  { id: 'plants',  kinds: 'a', ar: 'بياكل عشب أو نباتات؟', en: 'Eats grass or plants?' },
  { id: 'africa_a', kinds: 'a', ar: 'عايش في أفريقيا؟', en: 'Lives in Africa?' },
  { id: 'desert',  kinds: 'a', ar: 'عايش في الصحرا؟', en: 'Lives in the desert?' },
  { id: 'snow',    kinds: 'a', ar: 'عايش في مكان كله تلج؟', en: 'Lives where there is ice and snow?' },
  { id: 'inegypt', kinds: 'a', ar: 'بتشوفه في مصر عادي؟', en: 'Commonly seen in Egypt?' },
  { id: 'legs4',   kinds: 'ac', ar: 'بيمشي على أربع رجلين؟', en: 'Walks on four legs?' },
  { id: 'nolegs',  kinds: 'a', ar: 'ملوش رجلين خالص؟', en: 'Has no legs at all?' },
  { id: 'stripes', kinds: 'ac', ar: 'جسمه مخطّط؟', en: 'Has stripes?' },
  { id: 'spots',   kinds: 'ac', ar: 'جسمه منقّط (عليه بقع)؟', en: 'Has spots?' },
  { id: 'horns',   kinds: 'a', ar: 'ليه قرون؟', en: 'Has horns?' },
  { id: 'longneck', kinds: 'a', ar: 'رقبته طويلة؟', en: 'Has a long neck?' },
  { id: 'shell',   kinds: 'ac', ar: 'ليه قوقعة أو درع؟', en: 'Has a shell?' },
  { id: 'fur',     kinds: 'a', ar: 'جسمه عليه فرو أو صوف؟', en: 'Has fur or wool?' },
  { id: 'tail',    kinds: 'ac', ar: 'ليه ديل طويل؟', en: 'Has a long tail?' },
  { id: 'bigears', kinds: 'ac', ar: 'ودانه كبيرة؟', en: 'Has big ears?' },
  { id: 'gives',   kinds: 'a', ar: 'بيدّينا حاجة غير لحمه (لبن، بيض، صوف، عسل)؟', en: 'Gives us something besides meat (milk, eggs, wool, honey)?' },
  { id: 'ride',    kinds: 'a', ar: 'الناس بتركبه؟', en: 'Do people ride it?' },
  { id: 'climb',   kinds: 'a', ar: 'بيطلع على الشجر؟', en: 'Climbs trees?' },
  { id: 'jump',    kinds: 'a', ar: 'بينطّ كتير؟', en: 'Jumps a lot?' },
  { id: 'night',   kinds: 'a', ar: 'بيصحى بالليل وينام بالنهار؟', en: 'Awake at night, asleep by day?' },
  { id: 'sting',   kinds: 'a', ar: 'سام أو بيلدغ أو بيقرص؟', en: 'Poisonous, or does it sting or bite?' },
  { id: 'danger',  kinds: 'a', ar: 'خطير على الإنسان؟', en: 'Dangerous to people?' },
  { id: 'extinct', kinds: 'a', ar: 'انقرض؟', en: 'Extinct?' },
  { id: 'fast',    kinds: 'a', ar: 'سريع جداً؟', en: 'Very fast?' },
  { id: 'slow',    kinds: 'a', ar: 'بطيء جداً؟', en: 'Very slow?' },

  /* ---------- shared: flying, size, colour ---------- */
  { id: 'flies',   kinds: 'catj', ar: 'بيطير؟', en: 'Does it fly?' },
  { id: 'big',     kinds: 'cat', ar: 'أكبر من الإنسان؟', en: 'Bigger than a person?' },
  { id: 'small',   kinds: 'at', ar: 'أصغر من كف الإيد؟', en: 'Smaller than your hand?' },
  { id: 'red',     kinds: 'cat', ar: 'لونه أحمر؟', en: 'Is it red?' },
  { id: 'yellow',  kinds: 'cat', ar: 'لونه أصفر؟', en: 'Is it yellow?' },
  { id: 'green',   kinds: 'cat', ar: 'لونه أخضر؟', en: 'Is it green?' },
  { id: 'blue',    kinds: 'cat', ar: 'لونه أزرق؟', en: 'Is it blue?' },
  { id: 'white',   kinds: 'cat', ar: 'لونه أبيض؟', en: 'Is it white?' },
  { id: 'black',   kinds: 'cat', ar: 'لونه أسود؟', en: 'Is it black?' },
  { id: 'brown',   kinds: 'cat', ar: 'لونه بنّي؟', en: 'Is it brown?' },
  { id: 'orange',  kinds: 'cat', ar: 'لونه برتقاني؟', en: 'Is it orange?' },
  { id: 'gray',    kinds: 'cat', ar: 'لونه رمادي؟', en: 'Is it grey?' },
  { id: 'pink',    kinds: 'cat', ar: 'لونه بمبي (وردي)؟', en: 'Is it pink?' },

  /* ---------- things ---------- */
  { id: 'edible',  kinds: 'at', ar: 'بيتاكل؟', en: 'Do we eat it?' },
  { id: 'breakfast', kinds: 't', ar: 'بيتاكل على الفطار؟', en: 'Eaten at breakfast?' },
  { id: 'summer',  kinds: 't', ar: 'بنستناه في الصيف؟', en: 'Something we wait for in summer?' },
  { id: 'drink',   kinds: 't', ar: 'بيتشرب؟', en: 'Do we drink it?' },
  { id: 'fruit',   kinds: 't', implies: ['edible'], ar: 'فاكهة؟', en: 'A fruit?' },
  { id: 'veg',     kinds: 't', implies: ['edible'], ar: 'خضار؟', en: 'A vegetable?' },
  { id: 'sweet',   kinds: 't', ar: 'طعمه مسكّر؟', en: 'Tastes sweet?' },
  { id: 'dish',    kinds: 't', implies: ['edible'], ar: 'أكلة بتتطبخ أو بتتعمل في المطبخ؟', en: 'A dish that is cooked or made?' },
  { id: 'electric', kinds: 't', ar: 'بيشتغل بالكهربا أو بالبطارية؟', en: 'Runs on electricity or a battery?' },
  { id: 'screen',  kinds: 't', implies: ['electric'], ar: 'ليه شاشة؟', en: 'Has a screen?' },
  { id: 'vehicle', kinds: 'tc', ar: 'وسيلة مواصلات؟', en: 'A vehicle?' },
  { id: 'engine',  kinds: 't', ar: 'ليه موتور؟', en: 'Has an engine?' },
  { id: 'passengers', kinds: 't', ar: 'بيركب فيه ناس كتير مع بعض؟', en: 'Carries many people at once?' },
  { id: 'wheels',  kinds: 'tc', ar: 'ليه عجل؟', en: 'Has wheels?' },
  { id: 'kitchen', kinds: 't', ar: 'بتلاقيه في المطبخ؟', en: 'Found in the kitchen?' },
  { id: 'home',    kinds: 't', ar: 'بتلاقيه في أي بيت؟', en: 'Found in every home?' },
  { id: 'bathroom', kinds: 't', ar: 'بتلاقيه في الحمّام؟', en: 'Found in the bathroom?' },
  { id: 'sit',     kinds: 't', ar: 'بنقعد عليه أو بننام عليه؟', en: 'Do we sit or sleep on it?' },
  { id: 'pocket',  kinds: 't', ar: 'يدخل في الجيب؟', en: 'Fits in a pocket?' },
  { id: 'buttons', kinds: 't', ar: 'ليه زراير؟', en: 'Has buttons?' },
  { id: 'school',  kinds: 't', ar: 'بنستعمله في المدرسة؟', en: 'Used at school?' },
  { id: 'wear',    kinds: 't', ar: 'بيتلبس؟', en: 'Do we wear it?' },
  { id: 'furniture', kinds: 't', ar: 'من العفش (أثاث)؟', en: 'A piece of furniture?' },
  { id: 'handtool', kinds: 't', ar: 'أداة بتمسكها في إيدك وتشتغل بيها؟', en: 'A tool you hold in your hand to use?' },
  { id: 'toy',     kinds: 'tc', ar: 'لعبة أطفال أو عروسة؟', en: 'A toy or a puppet?' },
  { id: 'sport',   kinds: 't', ar: 'بيتلعب بيه رياضة؟', en: 'Used to play a sport?' },
  { id: 'music',   kinds: 't', ar: 'آلة موسيقية؟', en: 'A musical instrument?' },
  { id: 'metal',   kinds: 't', ar: 'معمول من حديد أو معدن؟', en: 'Made of metal?' },
  { id: 'wood',    kinds: 't', ar: 'معمول من خشب؟', en: 'Made of wood?' },
  { id: 'paper',   kinds: 't', ar: 'معمول من ورق؟', en: 'Made of paper?' },
  { id: 'glass',   kinds: 't', ar: 'معمول من إزاز؟', en: 'Made of glass?' },
  { id: 'cloth',   kinds: 't', ar: 'معمول من قماش؟', en: 'Made of cloth?' },
  { id: 'nature',  kinds: 't', ar: 'من الطبيعة، محدّش صنعه؟', en: 'From nature, not made by people?' },
  { id: 'sky',     kinds: 't', ar: 'في السما؟', en: 'In the sky?' },
  { id: 'plant',   kinds: 't', ar: 'نبات أو شجرة أو ورد؟', en: 'A plant, a tree or a flower?' },
  { id: 'place',   kinds: 't', ar: 'مكان أو مبنى؟', en: 'A place or a building?' },
  { id: 'ramadan', kinds: 't', ar: 'له علاقة برمضان أو العيد؟', en: 'To do with Ramadan or Eid?' },
  { id: 'write',   kinds: 't', ar: 'بنكتب بيه أو عليه؟', en: 'Used to write with, or on?' },
  { id: 'sharp',   kinds: 't', ar: 'بيقطع (حادّ)؟', en: 'Does it cut (sharp)?' },
  { id: 'light',   kinds: 't', ar: 'بينوّر؟', en: 'Does it give light?' },
  { id: 'hot',     kinds: 't', ar: 'سخن أو بيسخّن؟', en: 'Hot, or does it heat?' },
  { id: 'cold',    kinds: 't', ar: 'ساقع أو بيبرّد؟', en: 'Cold, or does it cool?' },
  { id: 'liquid',  kinds: 't', ar: 'سائل؟', en: 'A liquid?' },
  { id: 'round',   kinds: 't', ar: 'شكله مدوّر؟', en: 'Round?' },
  { id: 'breaks',  kinds: 't', ar: 'بيتكسر بسهولة؟', en: 'Breaks easily?' },
  { id: 'noise',   kinds: 't', ar: 'بيعمل صوت؟', en: 'Does it make a sound?' },
  { id: 'clean',   kinds: 't', ar: 'بنستعمله في النضافة أو الغسيل؟', en: 'Used for cleaning or washing?' },
  { id: 'talk',    kinds: 't', ar: 'بنكلّم بيه الناس أو بنتفرج عليه؟', en: 'Used to talk to people, or to watch?' },
  { id: 'time',    kinds: 't', ar: 'له علاقة بالوقت أو المواعيد؟', en: 'To do with time?' },
  { id: 'wet',     kinds: 'tj', ar: 'له علاقة بالمية أو البحر؟', en: 'To do with water or the sea?' },
  { id: 'container', kinds: 't', ar: 'بنحط فيه حاجات؟', en: 'Do we put things in it?' },
  { id: 'street',  kinds: 't', ar: 'بتلاقيه في الشارع؟', en: 'Found in the street?' },

  /* ---------- jobs ---------- */
  { id: 'uniform', kinds: 'j', ar: 'بيلبس يونيفورم أو زي معيّن؟', en: 'Wears a uniform?' },
  { id: 'hospital', kinds: 'j', ar: 'بيشتغل في مستشفى أو عيادة؟', en: 'Works in a hospital or a clinic?' },
  { id: 'teach',   kinds: 'j', ar: 'بيشتغل في مدرسة أو جامعة؟', en: 'Works in a school or a university?' },
  { id: 'outdoors', kinds: 'j', ar: 'شغله برّه في الشارع أو الهوا الطلق؟', en: 'Works outdoors?' },
  { id: 'drives',  kinds: 'j', ar: 'بيسوق (عربية أو طيارة أو مركب أو قطر)؟', en: 'Drives (a car, a plane, a boat, a train)?' },
  { id: 'hands',   kinds: 'j', ar: 'صنايعي، شغله بإيده؟', en: 'A craftsman, working with his hands?' },
  { id: 'food_j',  kinds: 'j', ar: 'شغله فيه أكل أو شرب؟', en: 'Works with food or drink?' },
  { id: 'rescue',  kinds: 'j', ar: 'بيحمي الناس أو بينقذهم؟', en: 'Protects or rescues people?' },
  { id: 'art_j',   kinds: 'j', ar: 'شغله فن (رسم، تصوير، موسيقى)؟', en: 'An artist (drawing, photos, music)?' },
  { id: 'desk',    kinds: 'j', ar: 'شغله على مكتب؟', en: 'Works at a desk?' },
  { id: 'study',   kinds: 'j', ar: 'بيدرس سنين كتير في الجامعة عشانه؟', en: 'Needs many years at university?' },
  { id: 'animals_j', kinds: 'j', ar: 'بيتعامل مع حيوانات؟', en: 'Works with animals?' },
  { id: 'sells',   kinds: 'j', ar: 'بيبيع حاجة؟', en: 'Sells something?' },
  { id: 'build',   kinds: 'j', ar: 'بيبني أو بيصلّح حاجات؟', en: 'Builds or repairs things?' },
  { id: 'law',     kinds: 'j', ar: 'له علاقة بالقانون أو المحاكم؟', en: 'To do with the law or the courts?' },
  { id: 'sea_j',   kinds: 'j', ar: 'شغله في البحر أو على مركب؟', en: 'Works at sea or on a boat?' },
  { id: 'fire_j',  kinds: 'j', ar: 'شغله جنب النار أو الفرن؟', en: 'Works near fire or an oven?' },
  { id: 'cars_j',  kinds: 'j', ar: 'شغله في العربيات؟', en: 'Works with cars?' },
  { id: 'power_j', kinds: 'j', ar: 'شغله في الكهربا أو الكمبيوتر؟', en: 'Works with electricity or computers?' },
  { id: 'looks_j', kinds: 'j', ar: 'بيهتم بشكل الناس (شعر، لبس)؟', en: 'Takes care of how people look (hair, clothes)?' },
  { id: 'money_j', kinds: 'j', ar: 'شغله في الفلوس والحسابات؟', en: 'Works with money and accounts?' },
  { id: 'kids_j',  kinds: 'j', ar: 'بيتعامل مع أطفال كتير؟', en: 'Works with a lot of children?' },
  { id: 'night_j', kinds: 'j', ar: 'ممكن يشتغل طول الليل؟', en: 'Can work all night?' },
];
