/* العرّاف: things (kind 't': food, objects, places, nature) and jobs (kind 'j'). One line each:
   id, icon, ar, en, and the question ids (OracleQuestions.js) that are true (yes), partly or
   "most would say probably" (maybe), and firmly not, where a player might think otherwise (no).
   A question about the entry's kind in none of the three reads as «غالباً لأ».
   notes/games/oracle.md, "Writing entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_THINGS = { kind: 't', list: [
  /* ---------- food and drink ---------- */
  { id: 'apple',      icon: '🍎', ar: 'تفاحة', en: 'Apple', yes: 'fruit sweet red round', maybe: 'green kitchen', no: 'plant' },
  { id: 'banana',     icon: '🍌', ar: 'موزة', en: 'Banana', yes: 'fruit sweet yellow peel', no: 'round' },
  { id: 'orange',     icon: '🍊', ar: 'برتقانة', en: 'Orange', yes: 'fruit sweet orange round peel', maybe: 'drink' },
  { id: 'watermelon', icon: '🍉', ar: 'بطيخة', en: 'Watermelon', yes: 'fruit sweet green red round summer', maybe: 'big peel' },
  { id: 'mango',      icon: '🥭', ar: 'مانجا', en: 'Mango', yes: 'fruit sweet yellow summer peel', maybe: 'orange green egypt drink' },
  { id: 'grapes',     icon: '🍇', ar: 'عنب', en: 'Grapes', yes: 'fruit sweet small', maybe: 'green round' },
  { id: 'strawberry', icon: '🍓', ar: 'فراولة', en: 'Strawberry', yes: 'fruit sweet red small' },
  { id: 'dates',      icon: '🌴', ar: 'بلح', en: 'Dates', yes: 'fruit sweet ramadan brown small', maybe: 'egypt' },
  { id: 'tomato',     icon: '🍅', ar: 'طماطم', en: 'Tomato', yes: 'veg red round kitchen' },
  { id: 'potato',     icon: '🥔', ar: 'بطاطس', en: 'Potato', yes: 'veg brown kitchen peel', maybe: 'round' },
  { id: 'onion',      icon: '🧅', ar: 'بصلة', en: 'Onion', yes: 'veg kitchen round peel', maybe: 'white' },
  { id: 'carrot',     icon: '🥕', ar: 'جزرة', en: 'Carrot', yes: 'veg orange', maybe: 'kitchen peel' },
  { id: 'molokhia',   icon: '🥬', ar: 'ملوخية', en: 'Molokhia', yes: 'dish green egypt hot liquid', maybe: 'veg meat_t' },
  { id: 'koshary',    icon: '🍝', ar: 'كشري', en: 'Koshary', yes: 'dish egypt hot street' },
  { id: 'ful',        icon: '🫘', ar: 'فول', en: 'Ful medames', yes: 'dish egypt brown hot breakfast', maybe: 'ramadan street' },
  { id: 'taameya',    icon: '🧆', ar: 'طعمية', en: 'Taameya', yes: 'dish egypt hot breakfast round small', maybe: 'green brown street' },
  { id: 'bread',      icon: '🍞', ar: 'عيش', en: 'Bread', yes: 'edible home kitchen breakfast', maybe: 'round brown hot' },
  { id: 'cheese',     icon: '🧀', ar: 'جبنة', en: 'Cheese', yes: 'edible white kitchen breakfast', maybe: 'yellow' },
  { id: 'egg',        icon: '🥚', ar: 'بيضة', en: 'Egg', yes: 'edible breaks kitchen small breakfast', maybe: 'white round peel' },
  { id: 'pizza',      icon: '🍕', ar: 'بيتزا', en: 'Pizza', yes: 'dish round hot', maybe: 'meat_t' },
  { id: 'konafa',     icon: '🍯', ar: 'كنافة', en: 'Konafa', yes: 'dish sweet ramadan', maybe: 'orange hot' },
  { id: 'kahk',       icon: '🍪', ar: 'كحك العيد', en: 'Eid cookies (kahk)', yes: 'dish sweet ramadan round small', maybe: 'white egypt' },
  { id: 'chocolate',  icon: '🍫', ar: 'شوكولاتة', en: 'Chocolate', yes: 'edible sweet brown' },
  { id: 'icecream',   icon: '🍦', ar: 'آيس كريم', en: 'Ice cream', yes: 'edible sweet cold summer', maybe: 'white' },
  { id: 'water',      icon: '💧', ar: 'مية', en: 'Water', yes: 'drink liquid nature home wet', maybe: 'cold' },
  { id: 'milk',       icon: '🥛', ar: 'لبن', en: 'Milk', yes: 'drink liquid white', maybe: 'cold home breakfast' },
  { id: 'tea',        icon: '🫖', ar: 'شاي', en: 'Tea', yes: 'drink liquid hot home', maybe: 'kitchen brown breakfast' },
  { id: 'sugarcane',  icon: '🥤', ar: 'عصير قصب', en: 'Sugarcane juice', yes: 'drink liquid sweet egypt summer', maybe: 'cold green street' },
  /* ---------- around the house ---------- */
  { id: 'phone',      icon: '📱', ar: 'موبايل', en: 'Mobile phone', yes: 'electric screen talk home pocket', maybe: 'small black buttons', no: 'big' },
  { id: 'tv',         icon: '📺', ar: 'تلفزيون', en: 'Television', yes: 'electric screen talk home', maybe: 'black big', no: 'small pocket' },
  { id: 'computer',   icon: '💻', ar: 'كمبيوتر', en: 'Computer', yes: 'electric screen buttons', maybe: 'home school talk', no: 'pocket' },
  { id: 'fridge',     icon: '🧊', ar: 'تلاجة', en: 'Fridge', yes: 'electric kitchen cold big home container', maybe: 'white' },
  { id: 'fan',        icon: '🌀', ar: 'مروحة', en: 'Fan', yes: 'electric cold home noise summer', maybe: 'round buttons engine' },
  { id: 'lamp',       icon: '💡', ar: 'لمبة', en: 'Light bulb', yes: 'electric light glass breaks home', maybe: 'round small' },
  { id: 'clock',      icon: '⏰', ar: 'ساعة حيطة', en: 'Wall clock', yes: 'time round home', maybe: 'electric noise' },
  { id: 'watch',      icon: '⌚', ar: 'ساعة إيد', en: 'Wristwatch', yes: 'time wear small', maybe: 'metal round electric' },
  { id: 'lantern',    icon: '🏮', ar: 'فانوس رمضان', en: 'Ramadan lantern', yes: 'ramadan light', maybe: 'toy egypt metal glass electric noise' },
  { id: 'chair',      icon: '🪑', ar: 'كرسي', en: 'Chair', yes: 'furniture home sit', maybe: 'wood school' },
  { id: 'bed',        icon: '🛏️', ar: 'سرير', en: 'Bed', yes: 'furniture home big sit', maybe: 'wood' },
  { id: 'table',      icon: '🪵', ar: 'ترابيزة', en: 'Table', yes: 'furniture home wood', maybe: 'kitchen' },
  { id: 'door',       icon: '🚪', ar: 'باب', en: 'Door', yes: 'home wood', maybe: 'big' },
  { id: 'key',        icon: '🔑', ar: 'مفتاح', en: 'Key', yes: 'metal small home pocket', maybe: 'handtool' },
  { id: 'mirror',     icon: '🪞', ar: 'مراية', en: 'Mirror', yes: 'glass breaks home', maybe: 'round bathroom' },
  { id: 'pillow',     icon: '🛌', ar: 'مخدّة', en: 'Pillow', yes: 'cloth home sit', maybe: 'white' },
  { id: 'soap',       icon: '🧼', ar: 'صابونة', en: 'Soap', yes: 'clean home wet bathroom', maybe: 'small white' },
  { id: 'toothbrush', icon: '🪥', ar: 'فرشة سنان', en: 'Toothbrush', yes: 'clean home handtool bathroom', maybe: 'small wet' },
  { id: 'broom',      icon: '🧹', ar: 'مقشّة', en: 'Broom', yes: 'clean home handtool', maybe: 'wood' },
  { id: 'cup',        icon: '🥛', ar: 'كوباية', en: 'Glass (to drink)', yes: 'kitchen glass breaks container', maybe: 'small' },
  { id: 'spoon',      icon: '🥄', ar: 'معلقة', en: 'Spoon', yes: 'kitchen metal handtool', maybe: 'small' },
  { id: 'knife',      icon: '🔪', ar: 'سكينة', en: 'Knife', yes: 'sharp kitchen metal handtool' },
  { id: 'scissors',   icon: '✂️', ar: 'مقص', en: 'Scissors', yes: 'sharp handtool metal', maybe: 'school' },
  { id: 'umbrella',   icon: '☂️', ar: 'شمسية', en: 'Umbrella', yes: 'cloth wet', maybe: 'black street' },
  { id: 'money',      icon: '💵', ar: 'فلوس', en: 'Money', yes: 'paper home pocket', maybe: 'green small' },
  { id: 'camera',     icon: '📷', ar: 'كاميرا', en: 'Camera', yes: 'electric black buttons', maybe: 'screen small' },
  /* ---------- school, play and music ---------- */
  { id: 'pencil',     icon: '✏️', ar: 'قلم رصاص', en: 'Pencil', yes: 'write school wood handtool', maybe: 'yellow small pocket' },
  { id: 'book',       icon: '📖', ar: 'كتاب', en: 'Book', yes: 'paper school', maybe: 'home' },
  { id: 'notebook',   icon: '📒', ar: 'كشكول', en: 'Notebook', yes: 'paper school write' },
  { id: 'ball',       icon: '⚽', ar: 'كورة', en: 'Ball', yes: 'sport round toy', maybe: 'white black street' },
  { id: 'teddy',      icon: '🧸', ar: 'دبدوب', en: 'Teddy bear', yes: 'toy cloth', maybe: 'brown home' },
  { id: 'kite',       icon: '🪁', ar: 'طيارة ورق', en: 'Kite', yes: 'toy flies sky', maybe: 'paper' },
  { id: 'balloon',    icon: '🎈', ar: 'بالونة', en: 'Balloon', yes: 'toy round breaks', maybe: 'red flies' },
  { id: 'guitar',     icon: '🎸', ar: 'جيتار', en: 'Guitar', yes: 'music wood noise', no: 'arab' },
  { id: 'oud',        icon: '🪕', ar: 'عود', en: 'Oud', yes: 'music wood noise arab', maybe: 'egypt brown' },
  { id: 'drum',       icon: '🥁', ar: 'طبلة', en: 'Drum (tabla)', yes: 'music noise', maybe: 'round egypt' },
  /* ---------- on the road ---------- */
  { id: 'car',        icon: '🚗', ar: 'عربية', en: 'Car', yes: 'vehicle wheels metal street engine', maybe: 'big', no: 'passengers' },
  { id: 'bicycle',    icon: '🚲', ar: 'عجلة', en: 'Bicycle', yes: 'vehicle wheels metal street', maybe: 'sport toy', no: 'big engine' },
  { id: 'bus',        icon: '🚌', ar: 'أتوبيس', en: 'Bus', yes: 'vehicle wheels big street metal engine passengers', maybe: 'school' },
  { id: 'train',      icon: '🚆', ar: 'قطر', en: 'Train', yes: 'vehicle wheels big metal noise engine passengers', maybe: 'electric' },
  { id: 'plane',      icon: '✈️', ar: 'طيارة', en: 'Aeroplane', yes: 'vehicle flies sky big metal noise engine passengers', maybe: 'white' },
  { id: 'boat',       icon: '⛵', ar: 'مركب', en: 'Boat', yes: 'vehicle wet big', maybe: 'wood white engine passengers' },
  /* ---------- clothes ---------- */
  { id: 'shoe',       icon: '👞', ar: 'جزمة', en: 'Shoe', yes: 'wear home', maybe: 'black brown' },
  { id: 'shirt',      icon: '👕', ar: 'قميص', en: 'Shirt', yes: 'wear cloth buttons' },
  { id: 'glasses',    icon: '👓', ar: 'نضارة', en: 'Glasses', yes: 'wear glass breaks', maybe: 'small' },
  { id: 'cap',        icon: '🧢', ar: 'كاب', en: 'Cap', yes: 'wear cloth', maybe: 'sport' },
  /* ---------- nature and places ---------- */
  { id: 'sun',        icon: '☀️', ar: 'الشمس', en: 'The Sun', yes: 'nature sky hot light yellow round big' },
  { id: 'moon',       icon: '🌙', ar: 'القمر', en: 'The Moon', yes: 'nature sky light round', maybe: 'white ramadan big' },
  { id: 'star',       icon: '⭐', ar: 'نجمة في السما', en: 'A star', yes: 'nature sky light', maybe: 'yellow white' },
  { id: 'cloud',      icon: '☁️', ar: 'سحابة', en: 'Cloud', yes: 'nature sky white wet', maybe: 'gray big' },
  { id: 'tree',       icon: '🌳', ar: 'شجرة', en: 'Tree', yes: 'plant nature green big', maybe: 'wood street' },
  { id: 'rose',       icon: '🌹', ar: 'وردة', en: 'Rose', yes: 'plant nature red', maybe: 'pink small' },
  { id: 'cactus',     icon: '🌵', ar: 'صبّارة', en: 'Cactus', yes: 'plant nature green', maybe: 'sharp' },
  { id: 'sea',        icon: '🌊', ar: 'البحر', en: 'The sea', yes: 'nature wet blue big place', maybe: 'liquid summer' },
  { id: 'nile',       icon: '🏞️', ar: 'النيل', en: 'The Nile', yes: 'nature egypt wet big place', maybe: 'blue liquid' },
  { id: 'pyramids',   icon: '🔺', ar: 'الأهرامات', en: 'The Pyramids', yes: 'place egypt big', maybe: 'yellow brown', no: 'nature' },
  { id: 'school_p',   icon: '🏫', ar: 'مدرسة', en: 'School', yes: 'place big school', maybe: 'street' },
  { id: 'fire',       icon: '🔥', ar: 'نار', en: 'Fire', yes: 'hot light', maybe: 'nature red orange' },
  { id: 'ice',        icon: '🧊', ar: 'تلج', en: 'Ice', yes: 'cold wet white', maybe: 'nature breaks' },
  /* ---------- added 9 Oct 2026: fruit and vegetables ---------- */
  { id: 'guava',      icon: '🍐', ar: 'جوافة', en: 'Guava', yes: 'fruit sweet green', maybe: 'yellow round drink' },
  { id: 'pomegranate', icon: '🍎', ar: 'رمان', en: 'Pomegranate', yes: 'fruit sweet red round peel', maybe: 'drink' },
  { id: 'fig',        icon: '🫐', ar: 'تين', en: 'Fig', yes: 'fruit sweet summer small', maybe: 'green brown peel' },
  { id: 'apricot',    icon: '🍑', ar: 'مشمش', en: 'Apricot', yes: 'fruit sweet orange summer small', maybe: 'round' },
  { id: 'lemon',      icon: '🍋', ar: 'لمونة', en: 'Lemon', yes: 'fruit yellow kitchen', maybe: 'green round small drink', no: 'sweet' },
  { id: 'cantaloupe', icon: '🍈', ar: 'كانتالوب', en: 'Cantaloupe', yes: 'fruit sweet orange round summer peel', maybe: 'yellow' },
  { id: 'tangerine',  icon: '🍊', ar: 'يوسفي', en: 'Tangerine', yes: 'fruit sweet orange round small peel' },
  { id: 'coconut',    icon: '🥥', ar: 'جوز هند', en: 'Coconut', yes: 'fruit brown round white', maybe: 'sweet drink peel', no: 'small' },
  { id: 'pricklypear', icon: '🌵', ar: 'تين شوكي', en: 'Prickly pear', yes: 'fruit sweet summer street sharp peel', maybe: 'orange green' },
  { id: 'cucumber',   icon: '🥒', ar: 'خيارة', en: 'Cucumber', yes: 'veg green kitchen', maybe: 'cold peel' },
  { id: 'eggplant',   icon: '🍆', ar: 'بدنجان', en: 'Aubergine', yes: 'veg kitchen', maybe: 'black dish peel' },
  { id: 'garlic',     icon: '🧄', ar: 'توم', en: 'Garlic', yes: 'veg white kitchen small peel', maybe: 'round' },
  { id: 'okra',       icon: '🫛', ar: 'بامية', en: 'Okra', yes: 'veg green small', maybe: 'dish kitchen' },
  { id: 'corn',       icon: '🌽', ar: 'درة', en: 'Corn', yes: 'veg yellow', maybe: 'street hot summer' },
  { id: 'sweetpotato', icon: '🍠', ar: 'بطاطا', en: 'Sweet potato', yes: 'veg sweet hot street', maybe: 'brown orange peel' },
  { id: 'mint',       icon: '🌿', ar: 'نعناع', en: 'Mint', yes: 'plant green edible', maybe: 'drink kitchen nature' },
  { id: 'olives',     icon: '🫒', ar: 'زيتون', en: 'Olives', yes: 'edible green small breakfast', maybe: 'black round' },
  { id: 'peanuts',    icon: '🥜', ar: 'سوداني', en: 'Peanuts', yes: 'edible brown small peel', maybe: 'street' },
  { id: 'lupini',     icon: '🟡', ar: 'ترمس', en: 'Lupini beans', yes: 'edible yellow small peel', maybe: 'street round' },
  /* ---------- dishes, sweets and drinks ---------- */
  { id: 'rice',       icon: '🍚', ar: 'رز', en: 'Rice', yes: 'dish white kitchen home', maybe: 'hot small' },
  { id: 'mahshi',     icon: '🫑', ar: 'محشي', en: 'Mahshi (stuffed vegetables)', yes: 'dish egypt hot', maybe: 'green meat_t' },
  { id: 'fatta',      icon: '🍲', ar: 'فتة', en: 'Fatta', yes: 'dish egypt hot ramadan meat_t', maybe: 'white' },
  { id: 'feteer',     icon: '🥧', ar: 'فطير مشلتت', en: 'Feteer meshaltet', yes: 'dish egypt round', maybe: 'breakfast hot sweet' },
  { id: 'hawawshi',   icon: '🥙', ar: 'حواوشي', en: 'Hawawshi', yes: 'dish egypt hot street meat_t', maybe: 'round brown' },
  { id: 'shawarma',   icon: '🌯', ar: 'شاورما', en: 'Shawarma', yes: 'dish hot street meat_t', maybe: 'arab' },
  { id: 'kofta',      icon: '🍢', ar: 'كفتة', en: 'Kofta', yes: 'dish hot brown meat_t', maybe: 'egypt' },
  { id: 'feseekh',    icon: '🐟', ar: 'فسيخ', en: 'Feseekh (salted fish)', yes: 'edible egypt', maybe: 'gray' },
  { id: 'basbousa',   icon: '🍰', ar: 'بسبوسة', en: 'Basbousa', yes: 'dish sweet egypt', maybe: 'yellow brown ramadan' },
  { id: 'qatayef',    icon: '🥟', ar: 'قطايف', en: 'Qatayef', yes: 'dish sweet ramadan round', maybe: 'brown' },
  { id: 'omali',      icon: '🥣', ar: 'أم علي', en: 'Om Ali', yes: 'dish sweet egypt hot', maybe: 'white' },
  { id: 'ricepudding', icon: '🍮', ar: 'رز بلبن', en: 'Rice pudding', yes: 'dish sweet white cold', maybe: 'egypt' },
  { id: 'cake',       icon: '🎂', ar: 'تورتة', en: 'Birthday cake', yes: 'dish sweet', maybe: 'round white' },
  { id: 'biscuit',    icon: '🍪', ar: 'بسكوت', en: 'Biscuit', yes: 'edible sweet small', maybe: 'brown breakfast' },
  { id: 'honey',      icon: '🍯', ar: 'عسل نحل', en: 'Honey', yes: 'edible sweet yellow', maybe: 'liquid orange breakfast' },
  { id: 'molasses',   icon: '🫙', ar: 'عسل إسود', en: 'Black molasses', yes: 'edible sweet black breakfast', maybe: 'liquid egypt' },
  { id: 'halawa',     icon: '🥮', ar: 'حلاوة طحينية', en: 'Halawa', yes: 'edible sweet breakfast', maybe: 'white brown egypt' },
  { id: 'sugar',      icon: '🍬', ar: 'سكر', en: 'Sugar', yes: 'edible sweet white kitchen home' },
  { id: 'popcorn',    icon: '🍿', ar: 'فشار', en: 'Popcorn', yes: 'edible white', maybe: 'yellow hot small' },
  { id: 'chips',      icon: '🥔', ar: 'شيبسي', en: 'Crisps', yes: 'edible yellow', maybe: 'small' },
  { id: 'lollipop',   icon: '🍭', ar: 'مصاصة', en: 'Lollipop', yes: 'edible sweet small round', maybe: 'red' },
  { id: 'cottoncandy', icon: '🍥', ar: 'غزل البنات', en: 'Candy floss', yes: 'edible sweet pink', maybe: 'street white' },
  { id: 'yogurt',     icon: '🥛', ar: 'زبادي', en: 'Yoghurt', yes: 'edible white cold', maybe: 'breakfast kitchen' },
  { id: 'coffee',     icon: '☕', ar: 'قهوة', en: 'Coffee', yes: 'drink liquid hot brown', maybe: 'black breakfast arab' },
  { id: 'hibiscus',   icon: '🌺', ar: 'كركديه', en: 'Hibiscus drink (karkade)', yes: 'drink liquid red sweet', maybe: 'cold hot egypt ramadan' },
  { id: 'sobia',      icon: '🥛', ar: 'سوبيا', en: 'Sobia', yes: 'drink liquid white sweet cold ramadan', maybe: 'egypt' },
  { id: 'qamareldin', icon: '🧃', ar: 'قمر الدين', en: 'Apricot drink (qamar el-din)', yes: 'drink liquid orange sweet ramadan', maybe: 'cold' },
  { id: 'tamarind',   icon: '🥤', ar: 'تمر هندي', en: 'Tamarind drink', yes: 'drink liquid brown sweet ramadan cold' },
  { id: 'soda',       icon: '🥫', ar: 'حاجة ساقعة (مشروب غازي)', en: 'Fizzy drink', yes: 'drink liquid cold sweet', maybe: 'black summer' },
  { id: 'sahlab',     icon: '🍵', ar: 'سحلب', en: 'Sahlab', yes: 'drink liquid hot white sweet' },
  /* ---------- around the house ---------- */
  { id: 'washer',     icon: '🫧', ar: 'غسالة', en: 'Washing machine', yes: 'electric clean home noise container wet buttons', maybe: 'white bathroom' },
  { id: 'cooker',     icon: '🍳', ar: 'بوتاجاز', en: 'Cooker (stove)', yes: 'kitchen hot home metal', maybe: 'big white buttons', no: 'electric' },
  { id: 'microwave',  icon: '♨️', ar: 'ميكروويف', en: 'Microwave', yes: 'electric kitchen hot buttons container', maybe: 'white noise' },
  { id: 'aircon',     icon: '❄️', ar: 'تكييف', en: 'Air conditioner', yes: 'electric cold summer white', maybe: 'noise home' },
  { id: 'iron',       icon: '🧺', ar: 'مكواة', en: 'Iron', yes: 'electric hot handtool metal home', maybe: 'clean' },
  { id: 'vacuum',     icon: '🧹', ar: 'مكنسة كهربا', en: 'Vacuum cleaner', yes: 'electric clean noise', maybe: 'home handtool' },
  { id: 'kettle',     icon: '🫖', ar: 'كاتل (غلاية مية)', en: 'Electric kettle', yes: 'electric hot kitchen container', maybe: 'metal noise' },
  { id: 'blender',    icon: '🍹', ar: 'خلاط', en: 'Blender', yes: 'electric kitchen noise sharp container', maybe: 'glass buttons' },
  { id: 'remote',     icon: '🎛️', ar: 'ريموت', en: 'Remote control', yes: 'buttons electric home', maybe: 'black small talk' },
  { id: 'sofa',       icon: '🛋️', ar: 'كنبة', en: 'Sofa', yes: 'furniture sit home big cloth' },
  { id: 'wardrobe',   icon: '🚪', ar: 'دولاب', en: 'Wardrobe', yes: 'furniture home big wood container' },
  { id: 'carpet',     icon: '🟥', ar: 'سجادة', en: 'Carpet', yes: 'home cloth sit big', maybe: 'red' },
  { id: 'curtain',    icon: '🪟', ar: 'ستارة', en: 'Curtain', yes: 'cloth home' },
  { id: 'blanket',    icon: '🛏️', ar: 'بطانية', en: 'Blanket', yes: 'cloth home hot' },
  { id: 'towel',      icon: '🧖', ar: 'فوطة', en: 'Towel', yes: 'cloth clean bathroom home', maybe: 'wet' },
  { id: 'toothpaste', icon: '🪥', ar: 'معجون سنان', en: 'Toothpaste', yes: 'clean bathroom home', maybe: 'white small' },
  { id: 'shampoo',    icon: '🧴', ar: 'شامبو', en: 'Shampoo', yes: 'clean bathroom liquid wet', maybe: 'home container' },
  { id: 'pot',        icon: '🍲', ar: 'حلّة', en: 'Cooking pot', yes: 'kitchen metal container home', maybe: 'hot round' },
  { id: 'plate',      icon: '🍽️', ar: 'طبق', en: 'Plate', yes: 'kitchen breaks round home', maybe: 'white glass' },
  { id: 'kanaka',     icon: '☕', ar: 'كنكة', en: 'Coffee pot (kanaka)', yes: 'kitchen metal container', maybe: 'hot egypt small' },
  { id: 'landline',   icon: '☎️', ar: 'تليفون أرضي', en: 'Landline telephone', yes: 'electric talk buttons noise', maybe: 'home' },
  { id: 'radio',      icon: '📻', ar: 'راديو', en: 'Radio', yes: 'electric noise buttons', maybe: 'home' },
  { id: 'headphones', icon: '🎧', ar: 'سماعات', en: 'Headphones', yes: 'electric noise wear', maybe: 'small black' },
  { id: 'battery',    icon: '🔋', ar: 'بطارية', en: 'Battery', yes: 'electric small metal', maybe: 'pocket' },
  { id: 'tablet',     icon: '📲', ar: 'تابلت', en: 'Tablet', yes: 'electric screen talk', maybe: 'school black', no: 'pocket' },
  { id: 'console',    icon: '🎮', ar: 'بلايستيشن', en: 'Games console', yes: 'electric toy buttons', maybe: 'black home' },
  { id: 'hammer',     icon: '🔨', ar: 'شاكوش', en: 'Hammer', yes: 'handtool metal noise', maybe: 'wood' },
  { id: 'saw',        icon: '🪚', ar: 'منشار', en: 'Saw', yes: 'handtool sharp metal noise', maybe: 'wood' },
  { id: 'perfume',    icon: '🌸', ar: 'برفان', en: 'Perfume', yes: 'liquid glass', maybe: 'small breaks container' },
  { id: 'ring',       icon: '💍', ar: 'خاتم', en: 'Ring', yes: 'wear small metal round', maybe: 'yellow' },
  { id: 'newspaper',  icon: '🗞️', ar: 'جرنال', en: 'Newspaper', yes: 'paper write', maybe: 'black white street' },
  /* ---------- school ---------- */
  { id: 'pen',        icon: '🖊️', ar: 'قلم جاف', en: 'Ballpoint pen', yes: 'write school handtool pocket', maybe: 'blue small' },
  { id: 'schoolbag',  icon: '🎒', ar: 'شنطة المدرسة', en: 'School bag', yes: 'school container wear', maybe: 'cloth' },
  { id: 'blackboard', icon: '🟩', ar: 'سبورة', en: 'Blackboard', yes: 'school write big', maybe: 'black green' },
  { id: 'chalk',      icon: '🖍️', ar: 'طباشير', en: 'Chalk', yes: 'write school white small breaks' },
  { id: 'calculator', icon: '🧮', ar: 'آلة حاسبة', en: 'Calculator', yes: 'screen buttons school small', maybe: 'pocket' },
  /* ---------- clothes ---------- */
  { id: 'jacket',     icon: '🧥', ar: 'جاكيت', en: 'Jacket', yes: 'wear cloth hot', maybe: 'buttons' },
  { id: 'galabeya',   icon: '🥻', ar: 'جلابية', en: 'Galabeya', yes: 'wear cloth egypt', maybe: 'white' },
  { id: 'tarboosh',   icon: '🎩', ar: 'طربوش', en: 'Tarboosh (fez)', yes: 'wear red egypt', maybe: 'round' },
  { id: 'sunglasses', icon: '🕶️', ar: 'نضارة شمس', en: 'Sunglasses', yes: 'wear glass black summer', maybe: 'breaks' },
  /* ---------- on the road, in the air, at sea ---------- */
  { id: 'motorbike',  icon: '🏍️', ar: 'موتوسيكل', en: 'Motorbike', yes: 'vehicle wheels engine metal street noise' },
  { id: 'tuktuk',     icon: '🛺', ar: 'توك توك', en: 'Tuk-tuk', yes: 'vehicle wheels engine street noise', maybe: 'egypt' },
  { id: 'microbus',   icon: '🚐', ar: 'ميكروباص', en: 'Microbus', yes: 'vehicle wheels engine street passengers metal', maybe: 'white egypt' },
  { id: 'metro',      icon: '🚇', ar: 'مترو', en: 'Metro (underground)', yes: 'vehicle wheels electric passengers metal big noise' },
  { id: 'ship',       icon: '🚢', ar: 'سفينة', en: 'Ship', yes: 'vehicle wet big passengers metal engine', maybe: 'white' },
  { id: 'helicopter', icon: '🚁', ar: 'هليكوبتر', en: 'Helicopter', yes: 'vehicle flies sky noise engine metal big' },
  { id: 'truck',      icon: '🚛', ar: 'تريلا', en: 'Lorry', yes: 'vehicle wheels engine big street metal noise' },
  { id: 'ambulance',  icon: '🚑', ar: 'عربية إسعاف', en: 'Ambulance', yes: 'vehicle wheels engine street noise light', maybe: 'white red' },
  { id: 'firetruck',  icon: '🚒', ar: 'عربية مطافي', en: 'Fire engine', yes: 'vehicle wheels engine street noise red big', maybe: 'wet' },
  { id: 'carriage',   icon: '🐎', ar: 'حنطور', en: 'Horse carriage', yes: 'vehicle wheels street', maybe: 'egypt wood black', no: 'engine' },
  { id: 'felucca',    icon: '⛵', ar: 'فلوكة', en: 'Felucca', yes: 'vehicle wet wood egypt white', no: 'engine' },
  { id: 'rocket',     icon: '🚀', ar: 'صاروخ', en: 'Space rocket', yes: 'vehicle flies sky engine big noise', maybe: 'white' },
  { id: 'trafficlight', icon: '🚦', ar: 'إشارة مرور', en: 'Traffic light', yes: 'street light electric red green yellow', maybe: 'metal' },
  { id: 'streetlamp', icon: '🏮', ar: 'عمود نور', en: 'Street lamp', yes: 'street light electric metal', maybe: 'big' },
  /* ---------- sport, toys and music ---------- */
  { id: 'racket',     icon: '🎾', ar: 'مضرب تنس', en: 'Tennis racket', yes: 'sport handtool' },
  { id: 'basketball', icon: '🏀', ar: 'كورة سلة', en: 'Basketball', yes: 'sport round orange', maybe: 'toy' },
  { id: 'trophy',     icon: '🏆', ar: 'كاس البطولة', en: 'Trophy (cup)', yes: 'sport metal yellow', maybe: 'container' },
  { id: 'chessboard', icon: '♟️', ar: 'شطرنج', en: 'Chess set', yes: 'toy black white', maybe: 'wood sport' },
  { id: 'dice',       icon: '🎲', ar: 'زهر الطاولة', en: 'Dice', yes: 'toy small white', maybe: 'black' },
  { id: 'backgammon', icon: '🎲', ar: 'طاولة (الزهر)', en: 'Backgammon', yes: 'toy wood', maybe: 'egypt arab noise' },
  { id: 'cards',      icon: '🃏', ar: 'كوتشينة', en: 'Playing cards', yes: 'paper toy pocket' },
  { id: 'marbles',    icon: '🔮', ar: 'بلي', en: 'Marbles', yes: 'toy small round glass' },
  { id: 'piano',      icon: '🎹', ar: 'بيانو', en: 'Piano', yes: 'music big noise', maybe: 'wood black white furniture' },
  { id: 'trumpet',    icon: '🎺', ar: 'ترومبيت', en: 'Trumpet', yes: 'music metal noise yellow' },
  /* ---------- places ---------- */
  { id: 'beach',      icon: '🏖️', ar: 'البلاج', en: 'The beach', yes: 'place summer wet', maybe: 'nature yellow hot' },
  { id: 'desert_p',   icon: '🏜️', ar: 'الصحرا', en: 'The desert', yes: 'nature place big yellow hot' },
  { id: 'mountain',   icon: '⛰️', ar: 'جبل', en: 'Mountain', yes: 'nature big place', maybe: 'brown gray' },
  { id: 'stadium',    icon: '🏟️', ar: 'إستاد', en: 'Stadium', yes: 'place big sport', maybe: 'green noise' },
  { id: 'khankhalili', icon: '🛍️', ar: 'خان الخليلي', en: 'Khan el-Khalili', yes: 'place egypt street', maybe: 'noise' },
  { id: 'suezcanal',  icon: '🚢', ar: 'قناة السويس', en: 'The Suez Canal', yes: 'place egypt wet big', maybe: 'blue', no: 'nature' },
  { id: 'eiffel',     icon: '🗼', ar: 'برج إيفل', en: 'The Eiffel Tower', yes: 'place big metal', maybe: 'brown' },
  { id: 'burjkhalifa', icon: '🏙️', ar: 'برج خليفة', en: 'Burj Khalifa', yes: 'place big arab glass' },
  { id: 'liberty',    icon: '🗽', ar: 'تمثال الحرية', en: 'The Statue of Liberty', yes: 'place big green metal' },
  /* ---------- nature ---------- */
  { id: 'rain',       icon: '🌧️', ar: 'مطر', en: 'Rain', yes: 'nature sky wet', maybe: 'liquid cold noise' },
  { id: 'lightning',  icon: '⚡', ar: 'برق', en: 'Lightning', yes: 'nature sky light noise', maybe: 'electric' },
  { id: 'volcano',    icon: '🌋', ar: 'بركان', en: 'Volcano', yes: 'nature big hot', maybe: 'red place light' },
  { id: 'jasmine_f',  icon: '🌼', ar: 'فل', en: 'Jasmine', yes: 'plant nature white small' },
  { id: 'sunflower',  icon: '🌻', ar: 'عبّاد الشمس', en: 'Sunflower', yes: 'plant nature yellow', maybe: 'big' },
  { id: 'gold',       icon: '🪙', ar: 'دهب', en: 'Gold', yes: 'metal yellow nature', maybe: 'wear small' },
  { id: 'earth',      icon: '🌍', ar: 'الكرة الأرضية', en: 'The Earth', yes: 'nature round big blue', maybe: 'green sky' },
  { id: 'mars',       icon: '🔴', ar: 'كوكب المريخ', en: 'Planet Mars', yes: 'nature sky red round big' },
  { id: 'island',     icon: '🏝️', ar: 'جزيرة', en: 'Island', yes: 'nature place wet big', maybe: 'green' },
  { id: 'waterfall',  icon: '💦', ar: 'شلّال', en: 'Waterfall', yes: 'nature wet noise', maybe: 'big place' },
  { id: 'forest',     icon: '🌲', ar: 'غابة', en: 'Forest', yes: 'nature place green big', maybe: 'plant' },
  /* ---------- a few more ---------- */
  { id: 'burger',     icon: '🍔', ar: 'برجر', en: 'Burger', yes: 'dish hot meat_t round brown', maybe: 'street' },
  { id: 'soup',       icon: '🥣', ar: 'شوربة', en: 'Soup', yes: 'dish hot liquid', maybe: 'ramadan meat_t' },
  { id: 'plum',       icon: '🫐', ar: 'برقوق', en: 'Plum', yes: 'fruit sweet summer small round', maybe: 'red' },
  { id: 'suitcase',   icon: '🧳', ar: 'شنطة سفر', en: 'Suitcase', yes: 'container wheels', maybe: 'black' },
  { id: 'waterheater', icon: '🚿', ar: 'سخّان', en: 'Water heater', yes: 'electric hot bathroom', maybe: 'container white' },
  { id: 'sewing',     icon: '🧵', ar: 'ماكينة خياطة', en: 'Sewing machine', yes: 'electric noise metal', maybe: 'sharp home' },
  { id: 'flashlight', icon: '🔦', ar: 'كشّاف', en: 'Torch (flashlight)', yes: 'electric light handtool', maybe: 'pocket small' },
  { id: 'ramadandeco', icon: '🎊', ar: 'زينة رمضان', en: 'Ramadan decorations', yes: 'ramadan paper', maybe: 'street light' },
  { id: 'pool',       icon: '🏊', ar: 'حمّام سباحة', en: 'Swimming pool', yes: 'place wet summer blue', maybe: 'sport' },
  { id: 'bigben',     icon: '🕰️', ar: 'ساعة بيج بن', en: 'Big Ben', yes: 'place big time' },
  { id: 'petra',      icon: '🏜️', ar: 'البتراء', en: 'Petra', yes: 'place big arab', maybe: 'pink' },
  { id: 'tajmahal',   icon: '🕌', ar: 'تاج محل', en: 'The Taj Mahal', yes: 'place big white' },
  { id: 'tram',       icon: '🚋', ar: 'ترام', en: 'Tram', yes: 'vehicle wheels electric passengers metal street', maybe: 'big noise' },
  { id: 'submarine',  icon: '🌊', ar: 'غوّاصة', en: 'Submarine', yes: 'vehicle wet big metal engine' },
  { id: 'tractor',    icon: '🚜', ar: 'جرّار', en: 'Tractor', yes: 'vehicle wheels engine big noise', maybe: 'metal' },
  { id: 'hotballoon', icon: '🎈', ar: 'منطاد', en: 'Hot-air balloon', yes: 'vehicle flies sky big cloth', maybe: 'passengers' },
]};

const ORACLE_JOBS = { kind: 'j', list: [
  { id: 'doctor',     icon: '🩺', ar: 'دكتور', en: 'Doctor', yes: 'hospital study rescue night_j', maybe: 'uniform' },
  { id: 'nurse',      icon: '💉', ar: 'ممرضة', en: 'Nurse', yes: 'hospital uniform', maybe: 'night_j rescue' },
  { id: 'dentist',    icon: '🦷', ar: 'دكتور أسنان', en: 'Dentist', yes: 'hospital study', maybe: 'uniform', no: 'night_j rescue' },
  { id: 'vet',        icon: '🐾', ar: 'دكتور بيطري', en: 'Vet', yes: 'animals_j study', maybe: 'hospital shop_j' },
  { id: 'teacher',    icon: '🧑‍🏫', ar: 'مدرّس', en: 'Teacher', yes: 'teach kids_j', maybe: 'study' },
  { id: 'engineer',   icon: '👷', ar: 'مهندس', en: 'Engineer', yes: 'study build', maybe: 'desk power_j outdoors' },
  { id: 'pilot',      icon: '👨‍✈️', ar: 'طيّار', en: 'Pilot', yes: 'drives flies uniform night_j travel_j', maybe: 'study' },
  { id: 'astronaut',  icon: '👩‍🚀', ar: 'رائد فضاء', en: 'Astronaut', yes: 'flies uniform study', maybe: 'drives travel_j lab_j' },
  { id: 'police',     icon: '👮', ar: 'ظابط شرطة', en: 'Police officer', yes: 'uniform rescue outdoors night_j army_j', maybe: 'drives law' },
  { id: 'firefighter', icon: '🧑‍🚒', ar: 'رجل مطافي', en: 'Firefighter', yes: 'uniform rescue outdoors night_j wet fire_j', maybe: 'drives army_j' },
  { id: 'chef',       icon: '🧑‍🍳', ar: 'شيف (طبّاخ)', en: 'Chef', yes: 'food_j fire_j', maybe: 'hands uniform night_j stage_j', no: 'sells' },
  { id: 'baker',      icon: '🥖', ar: 'فرّان', en: 'Baker', yes: 'food_j hands fire_j sells shop_j', maybe: 'night_j' },
  { id: 'butcher',    icon: '🥩', ar: 'جزّار', en: 'Butcher', yes: 'food_j sells shop_j animals_j', maybe: 'hands' },
  { id: 'farmer',     icon: '🧑‍🌾', ar: 'فلّاح', en: 'Farmer', yes: 'outdoors animals_j plants_j', maybe: 'food_j hands wet' },
  { id: 'fisherman',  icon: '🎣', ar: 'صيّاد سمك', en: 'Fisherman', yes: 'sea_j outdoors wet', maybe: 'food_j animals_j sells' },
  { id: 'captain',    icon: '⚓', ar: 'قبطان مركب', en: 'Ship captain', yes: 'sea_j drives uniform wet travel_j', maybe: 'outdoors' },
  { id: 'carpenter',  icon: '🪚', ar: 'نجّار', en: 'Carpenter', yes: 'hands build shop_j', maybe: 'house_j' },
  { id: 'plumber',    icon: '🔧', ar: 'سبّاك', en: 'Plumber', yes: 'hands build wet house_j' },
  { id: 'electrician', icon: '⚡', ar: 'كهربائي', en: 'Electrician', yes: 'hands build power_j house_j' },
  { id: 'mechanic',   icon: '🔩', ar: 'ميكانيكي', en: 'Mechanic', yes: 'hands build cars_j shop_j' },
  { id: 'driver',     icon: '🚕', ar: 'سوّاق', en: 'Driver', yes: 'drives cars_j outdoors travel_j', maybe: 'night_j' },
  { id: 'lawyer',     icon: '⚖️', ar: 'محامي', en: 'Lawyer', yes: 'law desk study', maybe: 'words_j' },
  { id: 'accountant', icon: '🧾', ar: 'محاسب', en: 'Accountant', yes: 'money_j desk', maybe: 'study power_j' },
  { id: 'programmer', icon: '👩‍💻', ar: 'مبرمج', en: 'Programmer', yes: 'power_j desk', maybe: 'study night_j' },
  { id: 'barber',     icon: '💈', ar: 'حلّاق', en: 'Barber', yes: 'looks_j hands shop_j' },
  { id: 'photographer', icon: '📸', ar: 'مصوّر', en: 'Photographer', yes: 'art_j outdoors', maybe: 'power_j travel_j' },
  { id: 'artist',     icon: '🎨', ar: 'رسّام', en: 'Painter (artist)', yes: 'art_j hands' },
  { id: 'postman',    icon: '📮', ar: 'بوسطجي', en: 'Postman', yes: 'outdoors uniform', maybe: 'drives' },
  { id: 'waiter',     icon: '🍽️', ar: 'جرسون', en: 'Waiter', yes: 'food_j uniform', maybe: 'night_j' },
  { id: 'gardener',   icon: '🌷', ar: 'جنايني', en: 'Gardener', yes: 'outdoors hands plants_j', maybe: 'wet house_j' },
  /* ---------- added 9 Oct 2026: everyday Egyptian jobs and the classic ones ---------- */
  { id: 'ironer',     icon: '👔', ar: 'مكوجي', en: 'Ironing man (makwagi)', yes: 'shop_j hands clothes_j', maybe: 'fire_j' },
  { id: 'doorman',    icon: '🏢', ar: 'بوّاب', en: 'Doorman (bawab)', yes: 'night_j outdoors', maybe: 'house_j' },
  { id: 'tailor',     icon: '🧵', ar: 'ترزي (خيّاط)', en: 'Tailor', yes: 'hands clothes_j shop_j looks_j' },
  { id: 'shoemaker',  icon: '👞', ar: 'جزمجي', en: 'Shoemaker', yes: 'hands clothes_j shop_j build', maybe: 'sells' },
  { id: 'builder',    icon: '🧱', ar: 'عامل بناء (بنّا)', en: 'Builder (mason)', yes: 'hands build outdoors' },
  { id: 'housepainter', icon: '🖌️', ar: 'نقّاش', en: 'House painter', yes: 'hands build house_j', maybe: 'art_j' },
  { id: 'blacksmith', icon: '⚒️', ar: 'حدّاد', en: 'Blacksmith', yes: 'hands build fire_j shop_j' },
  { id: 'pharmacist', icon: '💊', ar: 'صيدلي', en: 'Pharmacist', yes: 'study sells shop_j', maybe: 'hospital night_j lab_j' },
  { id: 'grocer',     icon: '🛒', ar: 'بقّال', en: 'Grocer', yes: 'sells food_j shop_j', maybe: 'night_j money_j' },
  { id: 'fulseller',  icon: '🫘', ar: 'بيّاع فول', en: 'Ful seller', yes: 'sells food_j cart_j outdoors fire_j' },
  { id: 'erksous',    icon: '🥤', ar: 'بيّاع عرقسوس', en: 'Licorice-drink seller', yes: 'sells food_j outdoors', maybe: 'music_j' },
  { id: 'cashier',    icon: '🧮', ar: 'كاشير', en: 'Cashier', yes: 'money_j shop_j', maybe: 'sells desk' },
  { id: 'presenter',  icon: '🎙️', ar: 'مذيع', en: 'TV presenter', yes: 'stage_j words_j', maybe: 'night_j' },
  { id: 'translator', icon: '🌐', ar: 'مترجم', en: 'Translator', yes: 'words_j desk', maybe: 'study travel_j' },
  { id: 'actor_j',    icon: '🎭', ar: 'ممثل', en: 'Actor', yes: 'art_j stage_j', maybe: 'night_j' },
  { id: 'singer_j',   icon: '🎤', ar: 'مطرب', en: 'Singer', yes: 'art_j stage_j music_j', maybe: 'night_j' },
  { id: 'musician',   icon: '🎻', ar: 'عازف', en: 'Musician', yes: 'art_j music_j hands', maybe: 'stage_j night_j' },
  { id: 'footballer_j', icon: '⚽', ar: 'لاعب كورة', en: 'Footballer', yes: 'sport_j outdoors uniform', maybe: 'stage_j travel_j' },
  { id: 'coach_j',    icon: '📋', ar: 'مدرّب كورة', en: 'Football coach', yes: 'sport_j outdoors', maybe: 'teach travel_j' },
  { id: 'stewardess', icon: '🛫', ar: 'مضيفة طيران', en: 'Flight attendant', yes: 'flies uniform travel_j food_j', maybe: 'night_j' },
  { id: 'traindriver', icon: '🚆', ar: 'سوّاق قطر', en: 'Train driver', yes: 'drives travel_j night_j', maybe: 'uniform' },
  { id: 'streetcleaner', icon: '🧹', ar: 'عامل نضافة', en: 'Street cleaner', yes: 'clean_j outdoors uniform' },
  { id: 'shepherd',   icon: '🐑', ar: 'راعي غنم', en: 'Shepherd', yes: 'animals_j outdoors' },
  { id: 'nanny',      icon: '🍼', ar: 'دادة (جليسة أطفال)', en: 'Nanny', yes: 'kids_j house_j' },
  { id: 'professor',  icon: '🎓', ar: 'أستاذ جامعة', en: 'University professor', yes: 'teach study', maybe: 'desk words_j lab_j' },
  { id: 'scientist',  icon: '🔬', ar: 'عالِم', en: 'Scientist', yes: 'study lab_j', maybe: 'desk' },
  { id: 'paperseller', icon: '📰', ar: 'بيّاع جرايد', en: 'Newspaper seller', yes: 'sells outdoors', maybe: 'words_j' },
  { id: 'jeweller',   icon: '💍', ar: 'جواهرجي', en: 'Jeweller', yes: 'sells shop_j looks_j', maybe: 'hands money_j' },
  { id: 'phonefixer', icon: '📱', ar: 'مصلّح موبايلات', en: 'Phone repairer', yes: 'power_j build hands shop_j', maybe: 'sells' },
  { id: 'trafficcop', icon: '🚦', ar: 'عسكري مرور', en: 'Traffic policeman', yes: 'army_j uniform outdoors cars_j', maybe: 'law' },
  { id: 'petrolman',  icon: '⛽', ar: 'عامل بنزينة', en: 'Petrol station attendant', yes: 'cars_j outdoors uniform sells', maybe: 'night_j' },
  { id: 'fashion',    icon: '👗', ar: 'مصمّم أزياء', en: 'Fashion designer', yes: 'art_j clothes_j looks_j', maybe: 'desk' },
  { id: 'lifeguard',  icon: '🛟', ar: 'منقذ (على البحر)', en: 'Lifeguard', yes: 'rescue wet outdoors sea_j', maybe: 'sport_j uniform' },
  { id: 'florist',    icon: '💐', ar: 'بيّاع ورد', en: 'Florist', yes: 'sells plants_j shop_j', maybe: 'art_j' },
  { id: 'clown',      icon: '🤡', ar: 'مهرّج', en: 'Clown', yes: 'stage_j kids_j', maybe: 'art_j' },
  { id: 'icecreamman', icon: '🍦', ar: 'بيّاع آيس كريم', en: 'Ice-cream seller', yes: 'sells food_j outdoors cart_j', maybe: 'kids_j' },
  { id: 'potter',     icon: '🏺', ar: 'فخراني', en: 'Potter', yes: 'hands art_j fire_j', maybe: 'shop_j sells' },
  { id: 'tourguide',  icon: '🗺️', ar: 'مرشد سياحي', en: 'Tour guide', yes: 'travel_j words_j outdoors', maybe: 'study' },
  { id: 'delivery',   icon: '🛵', ar: 'دليفري', en: 'Delivery rider', yes: 'drives outdoors', maybe: 'food_j night_j' },
  { id: 'mesaharati', icon: '🪘', ar: 'مسحّراتي', en: 'Mesaharati (the Ramadan drummer)', yes: 'night_j outdoors music_j' },
  { id: 'ahwagi',     icon: '☕', ar: 'قهوجي', en: 'Café waiter (ahwagi)', yes: 'food_j shop_j night_j fire_j', maybe: 'sells' },
  { id: 'sayes',      icon: '🅿️', ar: 'سايس', en: 'Parking attendant', yes: 'cars_j outdoors', maybe: 'night_j money_j' },
  { id: 'archaeologist', icon: '🏺', ar: 'عالم آثار', en: 'Archaeologist', yes: 'study outdoors', maybe: 'travel_j' },
  { id: 'paramedic',  icon: '🚑', ar: 'مسعف', en: 'Paramedic', yes: 'rescue uniform night_j outdoors', maybe: 'drives hospital' },
  { id: 'designer',   icon: '🖥️', ar: 'مصمّم جرافيك', en: 'Graphic designer', yes: 'art_j power_j desk' },
  { id: 'conductor',  icon: '🎫', ar: 'كمسري', en: 'Bus conductor', yes: 'money_j travel_j', maybe: 'uniform' },
  { id: 'fishmonger', icon: '🐟', ar: 'بيّاع سمك', en: 'Fishmonger', yes: 'sells food_j wet', maybe: 'shop_j animals_j sea_j' },
  { id: 'arbagi',     icon: '🐎', ar: 'عربجي (سوّاق حنطور)', en: 'Carriage driver', yes: 'drives animals_j outdoors travel_j' },
  { id: 'sailor',     icon: '⛵', ar: 'بحّار', en: 'Sailor', yes: 'sea_j wet travel_j', maybe: 'uniform outdoors' },
  { id: 'shoeshiner', icon: '🥾', ar: 'ماسح جزم', en: 'Shoeshiner', yes: 'clothes_j outdoors clean_j', maybe: 'hands' },
  { id: 'carwasher',  icon: '🚿', ar: 'غسّال عربيات', en: 'Car washer', yes: 'cars_j clean_j wet', maybe: 'outdoors' },
  { id: 'garbageman', icon: '🗑️', ar: 'زبّال', en: 'Rubbish collector', yes: 'clean_j outdoors', maybe: 'drives' },
  { id: 'zookeeper',  icon: '🦁', ar: 'حارس جنينة الحيوانات', en: 'Zookeeper', yes: 'animals_j outdoors uniform' },
  { id: 'factory',    icon: '🏭', ar: 'عامل في مصنع', en: 'Factory worker', yes: 'hands build uniform', maybe: 'night_j' },
  { id: 'peteacher',  icon: '🤸', ar: 'مدرّس ألعاب', en: 'PE teacher', yes: 'teach sport_j kids_j outdoors' },
  { id: 'clothseller', icon: '🛍️', ar: 'بيّاع هدوم', en: 'Clothes seller', yes: 'sells clothes_j shop_j', maybe: 'looks_j' },
  { id: 'boatman',    icon: '🛶', ar: 'مراكبي', en: 'Boatman', yes: 'drives sea_j wet travel_j outdoors' },
  { id: 'pediatrician', icon: '👶', ar: 'دكتور أطفال', en: 'Paediatrician', yes: 'hospital study kids_j' },
  { id: 'beekeeper',  icon: '🐝', ar: 'نحّال', en: 'Beekeeper', yes: 'animals_j outdoors food_j', maybe: 'sells' },
  { id: 'liontamer',  icon: '🎪', ar: 'مدرّب أسود في السيرك', en: 'Circus lion tamer', yes: 'animals_j stage_j', maybe: 'kids_j' },
  { id: 'calligrapher', icon: '🖋️', ar: 'خطّاط', en: 'Calligrapher', yes: 'art_j hands words_j' },
]};
