/* العرّاف: animals (kind 'a'). One line each: id, icon, ar, en, and the question ids
   (OracleQuestions.js) that are true of it (yes), partly or "most would say probably" (maybe),
   and firmly not, where a player might think otherwise (no). A question about animals that
   is in none of the three reads as «غالباً لأ». notes/games/oracle.md, "Writing entries";
   check with `cd tools && npm run check:oracle`. */
const ORACLE_ANIMALS = { kind: 'a', list: [
  { id: 'lion',      icon: '🦁', ar: 'أسد', en: 'Lion', yes: 'mammal wild meat africa_a legs4 fur tail danger fast', maybe: 'colony night asia_a big yellow brown' },
  { id: 'tiger',     icon: '🐯', ar: 'نمر', en: 'Tiger', yes: 'mammal wild meat legs4 stripes fur tail danger fast asia_a orange', maybe: 'night big black', no: 'africa_a' },
  { id: 'cheetah',   icon: '🐆', ar: 'فهد', en: 'Cheetah', yes: 'mammal wild meat africa_a legs4 spots fur tail fast yellow', maybe: 'danger' },
  { id: 'wolf',      icon: '🐺', ar: 'ديب', en: 'Wolf', yes: 'mammal wild meat legs4 fur tail night danger gray', maybe: 'colony snow fast asia_a america_a' },
  { id: 'fox',       icon: '🦊', ar: 'تعلب', en: 'Fox', yes: 'mammal wild meat legs4 fur tail night orange', maybe: 'desert inegypt asia_a america_a red brown' },
  { id: 'bear',      icon: '🐻', ar: 'دبّ', en: 'Bear', yes: 'mammal wild meat plants legs4 fur climb danger big brown', maybe: 'snow asia_a america_a black' },
  { id: 'polarbear', icon: '🐻‍❄️', ar: 'دبّ قطبي', en: 'Polar bear', yes: 'mammal wild meat snow legs4 fur danger big white', maybe: 'water sea_a america_a' },
  { id: 'elephant',  icon: '🐘', ar: 'فيل', en: 'Elephant', yes: 'mammal colony wild plants africa_a legs4 bigears ride tusks_a asia_a big gray', maybe: 'danger' },
  { id: 'giraffe',   icon: '🦒', ar: 'زرافة', en: 'Giraffe', yes: 'mammal wild plants africa_a legs4 spots longneck big yellow', maybe: 'horns fur tail brown' },
  { id: 'rhino',     icon: '🦏', ar: 'وحيد القرن', en: 'Rhino', yes: 'mammal wild plants africa_a legs4 horns danger big gray', maybe: 'asia_a' },
  { id: 'hippo',     icon: '🦛', ar: 'فرس النهر', en: 'Hippo', yes: 'mammal water wild plants africa_a legs4 danger big gray', maybe: 'night tusks_a' },
  { id: 'zebra',     icon: '🦓', ar: 'حمار وحشي', en: 'Zebra', yes: 'mammal colony wild plants africa_a legs4 stripes tail fast white black', maybe: 'fur big' },
  { id: 'camel',     icon: '🐪', ar: 'جمل', en: 'Camel', yes: 'mammal plants africa_a desert inegypt legs4 longneck fur gives ride big brown edible', maybe: 'farm wild tail asia_a yellow' },
  { id: 'horse',     icon: '🐴', ar: 'حصان', en: 'Horse', yes: 'mammal farm plants inegypt legs4 tail ride fast big', maybe: 'colony fur jump white black brown' },
  { id: 'donkey',    icon: '🫏', ar: 'حمار', en: 'Donkey', yes: 'mammal farm plants inegypt legs4 tail bigears ride gray', maybe: 'fur slow brown', no: 'fast' },
  { id: 'cow',       icon: '🐄', ar: 'بقرة', en: 'Cow', yes: 'mammal farm plants inegypt legs4 horns tail gives big edible', maybe: 'colony spots fur white brown' },
  { id: 'buffalo',   icon: '🐃', ar: 'جاموسة', en: 'Water buffalo', yes: 'mammal farm plants inegypt legs4 horns gives big black edible', maybe: 'water tail ride asia_a', no: 'white spots' },
  { id: 'sheep',     icon: '🐑', ar: 'خروف', en: 'Sheep', yes: 'mammal colony farm plants inegypt legs4 fur gives white edible', maybe: 'horns tail' },
  { id: 'goat',      icon: '🐐', ar: 'معزة', en: 'Goat', yes: 'mammal farm plants inegypt legs4 horns fur gives jump edible', maybe: 'colony pet bigears climb white black brown' },
  { id: 'dog',       icon: '🐕', ar: 'كلب', en: 'Dog', yes: 'mammal pet meat inegypt legs4 fur tail', maybe: 'farm spots danger fast white black brown' },
  { id: 'cat',       icon: '🐈', ar: 'قطة', en: 'Cat', yes: 'mammal pet meat inegypt legs4 fur tail climb jump', maybe: 'farm stripes night white black orange gray' },
  { id: 'rabbit',    icon: '🐇', ar: 'أرنب', en: 'Rabbit', yes: 'mammal pet farm plants inegypt legs4 fur bigears jump edible', maybe: 'wild gives fast white brown gray' },
  { id: 'mouse',     icon: '🐭', ar: 'فار', en: 'Mouse', yes: 'mammal inegypt legs4 fur tail night small gray', maybe: 'pet wild plants bigears white brown' },
  { id: 'squirrel',  icon: '🐿️', ar: 'سنجاب', en: 'Squirrel', yes: 'mammal wild plants legs4 fur tail climb jump brown', maybe: 'america_a small orange gray' },
  { id: 'monkey',    icon: '🐒', ar: 'قرد', en: 'Monkey', yes: 'mammal wild plants fur tail climb jump brown', maybe: 'colony africa_a legs4 insects_a asia_a america_a' },
  { id: 'gorilla',   icon: '🦍', ar: 'غوريلا', en: 'Gorilla', yes: 'mammal wild plants africa_a fur climb big black', maybe: 'colony legs4 danger', no: 'tail' },
  { id: 'panda',     icon: '🐼', ar: 'باندا', en: 'Panda', yes: 'mammal wild plants legs4 fur climb asia_a white black', maybe: 'slow big' },
  { id: 'kangaroo',  icon: '🦘', ar: 'كنغر', en: 'Kangaroo', yes: 'mammal wild plants fur tail jump fast australia_a brown', maybe: 'big', no: 'legs4' },
  { id: 'koala',     icon: '🐨', ar: 'كوالا', en: 'Koala', yes: 'mammal wild plants fur bigears climb slow australia_a gray', maybe: 'legs4 night' },
  { id: 'bat',       icon: '🦇', ar: 'خفاش', en: 'Bat', yes: 'mammal colony wild fur night flies black', maybe: 'plants inegypt bigears insects_a small' },
  { id: 'hedgehog',  icon: '🦔', ar: 'قنفد', en: 'Hedgehog', yes: 'mammal wild legs4 night insects_a brown', maybe: 'inegypt shell fur small' },
  { id: 'dolphin',   icon: '🐬', ar: 'دولفين', en: 'Dolphin', yes: 'mammal water wild meat nolegs jump fast sea_a gray', maybe: 'colony big blue', no: 'fish' },
  { id: 'whale',     icon: '🐋', ar: 'حوت', en: 'Whale', yes: 'mammal water wild nolegs sea_a big blue', maybe: 'meat snow gray', no: 'fish' },
  { id: 'shark',     icon: '🦈', ar: 'سمكة قرش', en: 'Shark', yes: 'fish water wild meat nolegs danger fast sea_a big gray', maybe: 'eggs_a blue white edible' },
  { id: 'octopus',   icon: '🐙', ar: 'أخطبوط', en: 'Octopus', yes: 'water wild meat eggs_a sea_a', maybe: 'sting red orange pink edible' },
  { id: 'goldfish',  icon: '🐠', ar: 'سمكة زينة', en: 'Goldfish', yes: 'fish water pet nolegs eggs_a small orange', maybe: 'inegypt yellow', no: 'sea_a' },
  { id: 'fish',      icon: '🐟', ar: 'سمكة بلطي', en: 'Tilapia', yes: 'fish water inegypt nolegs eggs_a gray edible', maybe: 'farm plants', no: 'sea_a' },
  { id: 'turtle',    icon: '🐢', ar: 'سلحفاة', en: 'Turtle', yes: 'reptile pet plants legs4 shell slow eggs_a green', maybe: 'water wild inegypt sea_a brown' },
  { id: 'crocodile', icon: '🐊', ar: 'تمساح', en: 'Crocodile', yes: 'reptile water wild meat africa_a legs4 tail danger eggs_a big green', maybe: 'inegypt shell asia_a america_a australia_a' },
  { id: 'snake',     icon: '🐍', ar: 'تعبان', en: 'Snake', yes: 'reptile wild meat nolegs sting danger eggs_a', maybe: 'desert inegypt tail climb green black brown' },
  { id: 'lizard',    icon: '🦎', ar: 'سحلية', en: 'Lizard', yes: 'reptile wild inegypt legs4 tail eggs_a insects_a', maybe: 'desert climb small green brown' },
  { id: 'chameleon', icon: '🦎', ar: 'حرباية', en: 'Chameleon', yes: 'reptile wild africa_a legs4 tail climb slow eggs_a insects_a green', maybe: 'small' },
  { id: 'frog',      icon: '🐸', ar: 'ضفدعة', en: 'Frog', yes: 'water wild inegypt jump eggs_a insects_a green', maybe: 'meat legs4 night small', no: 'reptile fish' },
  { id: 'eagle',     icon: '🦅', ar: 'نسر', en: 'Eagle', yes: 'bird wild meat eggs_a flies brown', maybe: 'danger fast america_a' },
  { id: 'owl',       icon: '🦉', ar: 'بومة', en: 'Owl', yes: 'bird wild meat night eggs_a flies brown', maybe: 'inegypt white gray' },
  { id: 'crow',      icon: '🐦‍⬛', ar: 'غراب', en: 'Crow', yes: 'bird inegypt eggs_a flies black', maybe: 'colony wild meat insects_a gray' },
  { id: 'parrot',    icon: '🦜', ar: 'ببغان', en: 'Parrot', yes: 'bird pet wild plants eggs_a flies green', maybe: 'africa_a inegypt climb america_a australia_a red yellow blue' },
  { id: 'pigeon',    icon: '🕊️', ar: 'حمامة', en: 'Pigeon', yes: 'bird colony pet inegypt eggs_a flies gray edible', maybe: 'farm plants fast white' },
  { id: 'sparrow',   icon: '🐦', ar: 'عصفورة', en: 'Sparrow', yes: 'bird inegypt eggs_a flies small brown', maybe: 'colony pet wild plants insects_a' },
  { id: 'duck',      icon: '🦆', ar: 'بطّة', en: 'Duck', yes: 'bird water farm inegypt gives eggs_a edible', maybe: 'colony pet plants flies white brown', no: 'longneck' },
  { id: 'chicken',   icon: '🐔', ar: 'فرخة', en: 'Chicken', yes: 'bird farm inegypt gives eggs_a edible', maybe: 'colony pet plants insects_a white brown', no: 'flies' },
  { id: 'rooster',   icon: '🐓', ar: 'ديك', en: 'Rooster', yes: 'bird farm inegypt edible', maybe: 'pet tail red', no: 'flies gives eggs_a' },
  { id: 'turkey',    icon: '🦃', ar: 'ديك رومي', en: 'Turkey', yes: 'bird farm eggs_a brown edible', maybe: 'wild plants inegypt gives america_a', no: 'flies' },
  { id: 'peacock',   icon: '🦚', ar: 'طاووس', en: 'Peacock', yes: 'bird tail eggs_a asia_a green blue', maybe: 'wild longneck flies' },
  { id: 'ostrich',   icon: '🐦', ar: 'نعامة', en: 'Ostrich', yes: 'bird wild africa_a longneck fast eggs_a big', maybe: 'plants desert gives ride black edible', no: 'flies legs4' },
  { id: 'penguin',   icon: '🐧', ar: 'بطريق', en: 'Penguin', yes: 'bird colony water wild snow eggs_a sea_a white black', maybe: 'meat', no: 'flies' },
  { id: 'flamingo',  icon: '🦩', ar: 'بشروش (فلامنجو)', en: 'Flamingo', yes: 'bird colony water wild longneck eggs_a flies pink', maybe: 'africa_a' },
  { id: 'bee',       icon: '🐝', ar: 'نحلة', en: 'Bee', yes: 'insect colony inegypt stripes gives sting flies small yellow black', maybe: 'farm wild plants eggs_a' },
  { id: 'ant',       icon: '🐜', ar: 'نملة', en: 'Ant', yes: 'insect colony inegypt sting small black', maybe: 'wild climb eggs_a insects_a red' },
  { id: 'butterfly', icon: '🦋', ar: 'فراشة', en: 'Butterfly', yes: 'insect eggs_a flies small', maybe: 'wild plants inegypt yellow blue orange' },
  { id: 'fly',       icon: '🪰', ar: 'دبّانة', en: 'Fly', yes: 'insect inegypt eggs_a flies small black', maybe: 'colony fast' },
  { id: 'mosquito',  icon: '🦟', ar: 'ناموسة', en: 'Mosquito', yes: 'insect inegypt night sting eggs_a flies small', maybe: 'colony' },
  { id: 'spider',    icon: '🕷️', ar: 'عنكبوت', en: 'Spider', yes: 'insect inegypt sting eggs_a insects_a small black', maybe: 'wild meat danger' },
  { id: 'scorpion',  icon: '🦂', ar: 'عقربة', en: 'Scorpion', yes: 'insect wild desert tail night sting danger insects_a small', maybe: 'meat africa_a inegypt yellow black', no: 'eggs_a' },
  { id: 'cockroach', icon: '🪳', ar: 'صرصار', en: 'Cockroach', yes: 'insect inegypt night fast eggs_a small brown', maybe: 'flies black' },
  { id: 'snail',     icon: '🐌', ar: 'حلزونة', en: 'Snail', yes: 'plants nolegs shell slow eggs_a small', maybe: 'water inegypt horns brown edible' },
  { id: 'shrimp',    icon: '🦐', ar: 'جمبري', en: 'Shrimp', yes: 'water eggs_a sea_a small edible', maybe: 'inegypt shell red orange pink' },
  { id: 'crab',      icon: '🦀', ar: 'كابوريا', en: 'Crab', yes: 'water shell sting eggs_a sea_a edible', maybe: 'wild inegypt small red' },
  { id: 'jellyfish', icon: '🪼', ar: 'قنديل البحر', en: 'Jellyfish', yes: 'water nolegs sting sea_a', maybe: 'colony wild danger slow blue white pink' },
  { id: 'starfish',  icon: '⭐', ar: 'نجمة البحر', en: 'Starfish', yes: 'water slow sea_a', maybe: 'wild nolegs eggs_a small red orange pink' },
  { id: 'dinosaur',  icon: '🦖', ar: 'ديناصور', en: 'Dinosaur', yes: 'wild tail danger extinct eggs_a big', maybe: 'reptile meat plants legs4 horns longneck flies green' },
  { id: 'seal',      icon: '🦭', ar: 'فقمة', en: 'Seal', yes: 'mammal colony water wild meat snow sea_a gray', maybe: 'nolegs fur big black brown' },

  /* ---------- 9 Oct 2026, the second writer: mammals ---------- */
  { id: 'hyena',       icon: '🐾', ar: 'ضبع', en: 'Hyena', yes: 'mammal wild meat africa_a legs4 spots fur night danger', maybe: 'colony stripes tail yellow brown gray' },
  { id: 'leopard',     icon: '🐆', ar: 'نمر مرقّط', en: 'Leopard', yes: 'mammal wild meat africa_a legs4 spots fur tail climb danger fast yellow', maybe: 'night asia_a' },
  { id: 'jaguar',      icon: '🐆', ar: 'جاجوار', en: 'Jaguar', yes: 'mammal wild meat legs4 spots fur tail danger america_a yellow', maybe: 'water climb night fast', no: 'africa_a' },
  { id: 'panther',     icon: '🐈‍⬛', ar: 'بانثر (النمر الأسود)', en: 'Black leopard (panther)', yes: 'mammal wild meat legs4 fur tail climb danger black', maybe: 'africa_a spots night fast asia_a america_a' },
  { id: 'deer',        icon: '🦌', ar: 'أيّل', en: 'Deer', yes: 'mammal wild plants legs4 horns fur jump fast brown', maybe: 'colony snow spots asia_a america_a edible' },
  { id: 'gazelle',     icon: '🦌', ar: 'غزالة', en: 'Gazelle', yes: 'mammal colony wild plants africa_a desert legs4 horns jump fast', maybe: 'inegypt fur asia_a yellow white brown' },
  { id: 'reindeer',    icon: '🦌', ar: 'رنّة', en: 'Reindeer', yes: 'mammal colony plants snow legs4 horns fur brown', maybe: 'farm wild gives ride asia_a america_a big white' },
  { id: 'moose',       icon: '🫎', ar: 'موظ', en: 'Moose', yes: 'mammal wild plants legs4 horns fur america_a big brown', maybe: 'water snow' },
  { id: 'chimpanzee',  icon: '🐒', ar: 'شمبانزي', en: 'Chimpanzee', yes: 'mammal wild plants africa_a fur climb black', maybe: 'colony meat legs4 danger insects_a', no: 'tail' },
  { id: 'orangutan',   icon: '🦧', ar: 'إنسان الغاب', en: 'Orangutan', yes: 'mammal wild plants fur climb asia_a orange', maybe: 'legs4 big brown', no: 'tail' },
  { id: 'baboon',      icon: '🐒', ar: 'بابون', en: 'Baboon', yes: 'mammal colony wild plants africa_a legs4 fur', maybe: 'meat tail climb danger brown gray' },
  { id: 'lemur',       icon: '🐒', ar: 'ليمور', en: 'Lemur', yes: 'mammal wild plants africa_a fur tail climb jump gray', maybe: 'colony legs4 stripes night white black' },
  { id: 'sloth',       icon: '🦥', ar: 'حيوان الكسلان', en: 'Sloth', yes: 'mammal wild plants fur climb slow america_a', maybe: 'legs4 brown gray' },
  { id: 'anteater',    icon: '🐾', ar: 'آكل النمل', en: 'Anteater', yes: 'mammal wild legs4 fur tail insects_a america_a', maybe: 'stripes slow big brown gray' },
  { id: 'armadillo',   icon: '🐾', ar: 'أرماديلو', en: 'Armadillo', yes: 'mammal wild legs4 shell insects_a america_a', maybe: 'tail night brown gray' },
  { id: 'raccoon',     icon: '🦝', ar: 'راكون', en: 'Raccoon', yes: 'mammal wild legs4 fur tail climb night america_a gray', maybe: 'meat plants stripes black' },
  { id: 'skunk',       icon: '🦨', ar: 'ظربان', en: 'Skunk', yes: 'mammal wild legs4 stripes fur tail night america_a white black', maybe: 'meat insects_a' },
  { id: 'beaver',      icon: '🦫', ar: 'قندس', en: 'Beaver', yes: 'mammal water wild plants legs4 fur america_a brown', maybe: 'tail' },
  { id: 'otter',       icon: '🦦', ar: 'قضاعة (تعلب المية)', en: 'Otter', yes: 'mammal water wild meat legs4 fur tail brown', maybe: 'sea_a' },
  { id: 'meerkat',     icon: '🐾', ar: 'سرقاط (ميركات)', en: 'Meerkat', yes: 'mammal colony wild africa_a desert legs4 fur tail insects_a', maybe: 'meat yellow brown' },
  { id: 'mongoose',    icon: '🐾', ar: 'نمس', en: 'Mongoose', yes: 'mammal wild meat africa_a legs4 fur tail insects_a', maybe: 'colony inegypt fast asia_a brown gray' },
  { id: 'weasel',      icon: '🐾', ar: 'عرسة', en: 'Weasel', yes: 'mammal wild meat inegypt legs4 fur tail fast brown', maybe: 'africa_a night' },
  { id: 'jerboa',      icon: '🐭', ar: 'جربوع', en: 'Jerboa', yes: 'mammal wild africa_a desert fur tail bigears jump night', maybe: 'plants inegypt insects_a small yellow' },
  { id: 'porcupine',   icon: '🦔', ar: 'شيهم (النيص)', en: 'Porcupine', yes: 'mammal wild plants legs4 night', maybe: 'africa_a fur america_a black brown' },
  { id: 'hamster',     icon: '🐹', ar: 'هامستر', en: 'Hamster', yes: 'mammal pet plants legs4 fur night', maybe: 'inegypt small white brown orange' },
  { id: 'rat',         icon: '🐀', ar: 'جرذ (فار كبير)', en: 'Rat', yes: 'mammal inegypt legs4 fur tail night gray', maybe: 'colony danger black brown', no: 'small' },
  { id: 'boar',        icon: '🐗', ar: 'خنزير بري', en: 'Wild boar', yes: 'mammal wild legs4 fur danger tusks_a brown', maybe: 'meat plants night asia_a black' },
  { id: 'bison',       icon: '🦬', ar: 'بيسون (الجاموس الأمريكي)', en: 'Bison', yes: 'mammal colony wild plants legs4 horns fur america_a big brown', maybe: 'snow tail danger' },
  { id: 'llama',       icon: '🦙', ar: 'لاما', en: 'Llama', yes: 'mammal plants legs4 longneck fur gives america_a', maybe: 'colony farm wild ride big white brown' },
  { id: 'mule',        icon: '🫏', ar: 'بغل', en: 'Mule', yes: 'mammal farm plants inegypt legs4 tail bigears ride big brown', maybe: 'fur gray' },
  { id: 'bull',        icon: '🐂', ar: 'تور', en: 'Bull', yes: 'mammal farm plants inegypt legs4 horns tail big edible', maybe: 'fur ride danger black brown', no: 'gives' },
  { id: 'oryx',        icon: '🦌', ar: 'مها', en: 'Oryx', yes: 'mammal wild plants desert legs4 horns asia_a white', maybe: 'colony africa_a fur fast' },
  { id: 'ibex',        icon: '🐐', ar: 'وعل', en: 'Ibex', yes: 'mammal wild plants legs4 horns fur jump brown', maybe: 'africa_a desert snow inegypt asia_a', no: 'farm' },
  { id: 'fennec',      icon: '🦊', ar: 'فنك (تعلب الصحرا)', en: 'Fennec fox', yes: 'mammal wild meat africa_a desert legs4 fur tail bigears night', maybe: 'inegypt insects_a yellow' },
  { id: 'arcticfox',   icon: '🦊', ar: 'تعلب قطبي', en: 'Arctic fox', yes: 'mammal wild meat snow legs4 fur tail white', maybe: 'gray' },
  { id: 'jackal',      icon: '🐺', ar: 'ابن آوى', en: 'Jackal', yes: 'mammal wild meat africa_a legs4 fur tail night', maybe: 'desert inegypt asia_a yellow brown' },
  { id: 'platypus',    icon: '🐾', ar: 'خلد الماء (بلاتيبوس)', en: 'Platypus', yes: 'mammal water wild legs4 fur eggs_a australia_a brown', maybe: 'tail sting' },
  { id: 'walrus',      icon: '🦭', ar: 'فظ', en: 'Walrus', yes: 'mammal colony water wild snow sea_a tusks_a big brown', maybe: 'meat nolegs fur', no: 'fish' },
  { id: 'sealion',     icon: '🦭', ar: 'أسد البحر', en: 'Sea lion', yes: 'mammal colony water wild meat sea_a brown', maybe: 'fur jump america_a big black', no: 'fish' },
  { id: 'orca',        icon: '🐋', ar: 'حوت قاتل (أوركا)', en: 'Killer whale (orca)', yes: 'mammal water wild meat nolegs danger fast sea_a big white black', maybe: 'colony snow', no: 'fish' },

  /* ---------- birds ---------- */
  { id: 'falcon',      icon: '🦅', ar: 'صقر', en: 'Falcon', yes: 'bird wild meat fast eggs_a flies', maybe: 'pet desert inegypt danger asia_a brown gray', no: 'big' },
  { id: 'blackkite',   icon: '🦅', ar: 'حدّاية', en: 'Black kite', yes: 'bird wild meat inegypt eggs_a flies brown', maybe: 'black' },
  { id: 'hoopoe',      icon: '🐦', ar: 'هدهد', en: 'Hoopoe', yes: 'bird inegypt stripes eggs_a insects_a flies', maybe: 'wild brown orange' },
  { id: 'swan',        icon: '🦢', ar: 'بجعة', en: 'Swan', yes: 'bird water longneck eggs_a flies white', maybe: 'wild plants' },
  { id: 'pelican',     icon: '🐦', ar: 'بليكان (أبو جراب)', en: 'Pelican', yes: 'bird colony water wild meat longneck eggs_a flies white', maybe: 'africa_a sea_a' },
  { id: 'goose',       icon: '🪿', ar: 'وزّة', en: 'Goose', yes: 'bird water farm inegypt longneck gives eggs_a white edible', maybe: 'colony pet plants flies' },
  { id: 'canary',      icon: '🐤', ar: 'كناري', en: 'Canary', yes: 'bird pet eggs_a flies small yellow', maybe: 'plants inegypt' },
  { id: 'lovebird',    icon: '🦜', ar: 'عصفور الحب', en: 'Lovebird', yes: 'bird pet eggs_a flies small green', maybe: 'plants inegypt red yellow blue orange' },
  { id: 'quail',       icon: '🐦', ar: 'سمّان', en: 'Quail', yes: 'bird wild inegypt gives eggs_a flies brown edible', maybe: 'colony farm plants spots small' },
  { id: 'seagull',     icon: '🐦', ar: 'نورس', en: 'Seagull', yes: 'bird water wild eggs_a sea_a flies white', maybe: 'colony meat inegypt gray' },
  { id: 'egret',       icon: '🐦', ar: 'أبو قردان', en: 'Cattle egret', yes: 'bird farm inegypt longneck eggs_a insects_a flies white', maybe: 'colony water wild africa_a' },
  { id: 'stork',       icon: '🐦', ar: 'لقلق', en: 'Stork', yes: 'bird wild longneck eggs_a flies white black', maybe: 'colony water meat africa_a' },
  { id: 'hummingbird', icon: '🐦', ar: 'طائر الطنّان', en: 'Hummingbird', yes: 'bird wild fast eggs_a america_a flies small', maybe: 'plants green blue' },
  { id: 'woodpecker',  icon: '🐦', ar: 'نقّار الخشب', en: 'Woodpecker', yes: 'bird wild climb eggs_a insects_a flies', maybe: 'red white black' },
  { id: 'toucan',      icon: '🐦', ar: 'طوقان', en: 'Toucan', yes: 'bird wild eggs_a america_a flies black', maybe: 'plants yellow orange' },
  { id: 'swallow',     icon: '🐦', ar: 'سنونو', en: 'Swallow', yes: 'bird fast eggs_a insects_a flies', maybe: 'colony wild inegypt tail small white black' },
  { id: 'chick',       icon: '🐥', ar: 'كتكوت', en: 'Chick', yes: 'bird farm inegypt small yellow', maybe: 'pet fur edible', no: 'flies eggs_a' },
  { id: 'dodo',        icon: '🦤', ar: 'طائر الدودو', en: 'Dodo', yes: 'bird wild extinct eggs_a gray', maybe: 'brown', no: 'flies' },

  /* ---------- the sea and the river ---------- */
  { id: 'squid',       icon: '🦑', ar: 'سبيط (كاليماري)', en: 'Squid', yes: 'water wild eggs_a sea_a edible', maybe: 'meat nolegs white pink' },
  { id: 'seahorse',    icon: '🐠', ar: 'حصان البحر', en: 'Seahorse', yes: 'water nolegs tail slow eggs_a sea_a small', maybe: 'fish wild yellow orange', no: 'legs4 mammal' },
  { id: 'clownfish',   icon: '🐠', ar: 'سمكة المهرّج', en: 'Clownfish', yes: 'fish water nolegs stripes eggs_a sea_a small white orange', maybe: 'pet wild' },
  { id: 'swordfish',   icon: '🐟', ar: 'سمكة أبو سيف', en: 'Swordfish', yes: 'fish water wild meat nolegs fast eggs_a sea_a big edible', maybe: 'blue gray' },
  { id: 'sardine',     icon: '🐟', ar: 'سردين', en: 'Sardine', yes: 'fish colony water nolegs eggs_a sea_a edible', maybe: 'wild inegypt small gray' },
  { id: 'tuna',        icon: '🐟', ar: 'تونة', en: 'Tuna', yes: 'fish colony water nolegs fast eggs_a sea_a edible', maybe: 'wild meat big blue gray' },
  { id: 'mullet',      icon: '🐟', ar: 'بوري', en: 'Mullet', yes: 'fish water inegypt nolegs eggs_a sea_a gray edible', maybe: 'colony' },
  { id: 'catfish',     icon: '🐟', ar: 'قرموط', en: 'Catfish', yes: 'fish water inegypt nolegs eggs_a black edible', maybe: 'meat brown gray', no: 'sea_a' },
  { id: 'piranha',     icon: '🐟', ar: 'بيرانا', en: 'Piranha', yes: 'fish colony water wild meat nolegs danger eggs_a america_a', maybe: 'small red gray' },
  { id: 'flyingfish',  icon: '🐟', ar: 'السمكة الطايرة', en: 'Flying fish', yes: 'fish water nolegs fast eggs_a sea_a', maybe: 'jump flies blue' },
  { id: 'eel',         icon: '🐟', ar: 'تعبان البحر (حنكليس)', en: 'Eel', yes: 'fish water nolegs tail eggs_a', maybe: 'wild meat sea_a black gray edible' },
  { id: 'stingray',    icon: '🐟', ar: 'سمكة الراي', en: 'Stingray', yes: 'fish water nolegs tail sting sea_a', maybe: 'wild danger brown gray' },
  { id: 'pufferfish',  icon: '🐡', ar: 'سمكة أبو نفخة', en: 'Pufferfish', yes: 'fish water nolegs sting eggs_a sea_a', maybe: 'wild spots danger small yellow' },
  { id: 'urchin',      icon: '🦔', ar: 'قنفد البحر', en: 'Sea urchin', yes: 'water sting slow eggs_a sea_a', maybe: 'wild nolegs shell small black edible' },
  { id: 'lobster',     icon: '🦞', ar: 'استاكوزا', en: 'Lobster', yes: 'water shell tail sting eggs_a sea_a edible', maybe: 'wild red' },
  { id: 'oyster',      icon: '🦪', ar: 'محار', en: 'Oyster', yes: 'colony water nolegs shell gives slow eggs_a sea_a edible', maybe: 'small white gray', no: 'legs4' },
  { id: 'clam',        icon: '🐚', ar: 'جندوفلي', en: 'Clam', yes: 'water nolegs shell slow sea_a small edible', maybe: 'inegypt eggs_a white' },
  { id: 'seaturtle',   icon: '🐢', ar: 'سلحفاة بحرية', en: 'Sea turtle', yes: 'reptile water wild shell eggs_a sea_a', maybe: 'plants slow big green brown' },

  /* ---------- reptiles and amphibians ---------- */
  { id: 'cobra',       icon: '🐍', ar: 'كوبرا', en: 'Cobra', yes: 'reptile wild meat africa_a nolegs sting danger eggs_a asia_a', maybe: 'desert inegypt yellow black brown' },
  { id: 'viper',       icon: '🐍', ar: 'الحية أم قرون', en: 'Horned viper', yes: 'reptile wild meat africa_a desert nolegs horns sting danger eggs_a', maybe: 'inegypt night yellow brown' },
  { id: 'python',      icon: '🐍', ar: 'أصلة (بايثون)', en: 'Python', yes: 'reptile wild meat nolegs danger eggs_a big', maybe: 'water africa_a spots climb sting asia_a green brown' },
  { id: 'anaconda',    icon: '🐍', ar: 'أناكوندا', en: 'Anaconda', yes: 'reptile water wild meat nolegs danger america_a big', maybe: 'spots sting green', no: 'eggs_a' },
  { id: 'gecko',       icon: '🦎', ar: 'برص', en: 'Gecko', yes: 'reptile inegypt legs4 tail climb night eggs_a insects_a small', maybe: 'wild sting white gray' },
  { id: 'iguana',      icon: '🦎', ar: 'إجوانا', en: 'Iguana', yes: 'reptile wild plants legs4 tail eggs_a america_a green', maybe: 'pet climb' },
  { id: 'komodo',      icon: '🦎', ar: 'تنين كومودو', en: 'Komodo dragon', yes: 'reptile wild meat legs4 tail danger eggs_a asia_a big', maybe: 'sting brown gray' },
  { id: 'monitor',     icon: '🦎', ar: 'ورل', en: 'Monitor lizard', yes: 'reptile wild meat africa_a desert legs4 tail eggs_a', maybe: 'water inegypt asia_a brown' },
  { id: 'dabb',        icon: '🦎', ar: 'ضب', en: 'Spiny-tailed lizard (dabb)', yes: 'reptile wild plants africa_a desert legs4 tail eggs_a', maybe: 'inegypt asia_a yellow brown' },
  { id: 'salamander',  icon: '🦎', ar: 'سمندل', en: 'Salamander', yes: 'water wild legs4 tail eggs_a', maybe: 'spots insects_a small yellow black', no: 'reptile fish' },
  { id: 'tadpole',     icon: '🐸', ar: 'أبو دنيبة', en: 'Tadpole', yes: 'water plants inegypt tail small black', maybe: 'wild nolegs', no: 'fish reptile eggs_a' },

  /* ---------- insects, spiders and small creatures ---------- */
  { id: 'beetle',      icon: '🪲', ar: 'خنفسة', en: 'Beetle', yes: 'insect inegypt shell eggs_a small black', maybe: 'wild flies brown' },
  { id: 'ladybird',    icon: '🐞', ar: 'دعسوقة', en: 'Ladybird', yes: 'insect spots eggs_a insects_a flies small red', maybe: 'wild inegypt shell black' },
  { id: 'locust',      icon: '🦗', ar: 'جرادة', en: 'Locust', yes: 'insect colony plants jump eggs_a flies small', maybe: 'wild africa_a desert inegypt yellow green brown' },
  { id: 'cricket',     icon: '🦗', ar: 'صرصار الليل', en: 'Cricket', yes: 'insect jump night eggs_a small', maybe: 'wild plants inegypt flies black brown' },
  { id: 'mantis',      icon: '🦗', ar: 'فرس النبي', en: 'Praying mantis', yes: 'insect meat eggs_a insects_a small green', maybe: 'wild flies brown' },
  { id: 'dragonfly',   icon: '🪰', ar: 'يعسوب', en: 'Dragonfly', yes: 'insect fast eggs_a insects_a flies small', maybe: 'water wild meat inegypt green blue' },
  { id: 'wasp',        icon: '🐝', ar: 'دبّور', en: 'Wasp', yes: 'insect inegypt stripes sting eggs_a flies small yellow black', maybe: 'colony meat danger insects_a', no: 'gives' },
  { id: 'termite',     icon: '🐜', ar: 'نمل أبيض (أرضة)', en: 'Termite', yes: 'insect colony eggs_a small white', maybe: 'plants inegypt flies' },
  { id: 'moth',        icon: '🦋', ar: 'فراشة الليل (عتّة)', en: 'Moth', yes: 'insect night eggs_a flies small', maybe: 'inegypt white brown gray' },
  { id: 'silkworm',    icon: '🐛', ar: 'دودة القز', en: 'Silkworm', yes: 'insect plants gives eggs_a small white', maybe: 'farm nolegs slow asia_a' },
  { id: 'flea',        icon: '🪲', ar: 'برغوت', en: 'Flea', yes: 'insect jump sting eggs_a small black', maybe: 'inegypt brown' },
  { id: 'bedbug',      icon: '🪲', ar: 'بقّة', en: 'Bedbug', yes: 'insect night sting eggs_a small brown', maybe: 'inegypt red' },
  { id: 'tarantula',   icon: '🕷️', ar: 'رتيلاء', en: 'Tarantula', yes: 'insect wild sting danger eggs_a insects_a', maybe: 'meat fur night america_a small black brown' },
  { id: 'centipede',   icon: '🐛', ar: 'أم أربعة وأربعين', en: 'Centipede', yes: 'insect inegypt sting fast eggs_a insects_a', maybe: 'wild meat night small brown', no: 'legs4 nolegs' },
  { id: 'worm',        icon: '🪱', ar: 'دودة', en: 'Earthworm', yes: 'inegypt nolegs slow', maybe: 'eggs_a small brown pink', no: 'insect reptile' },
  { id: 'leech',       icon: '🪱', ar: 'علقة', en: 'Leech', yes: 'water nolegs sting small', maybe: 'inegypt eggs_a black brown', no: 'insect fish' },

  /* ---------- dinosaurs and animals gone ---------- */
  { id: 'triceratops', icon: '🦕', ar: 'ترايسيراتوبس', en: 'Triceratops', yes: 'wild plants legs4 horns tail extinct eggs_a big', maybe: 'reptile danger green brown gray' },
  { id: 'brachiosaurus', icon: '🦕', ar: 'براكيوصور', en: 'Brachiosaurus', yes: 'wild plants legs4 longneck tail extinct eggs_a big', maybe: 'reptile green gray', no: 'danger meat' },
  { id: 'stegosaurus', icon: '🦕', ar: 'ستيجوصور', en: 'Stegosaurus', yes: 'wild plants legs4 tail extinct eggs_a big', maybe: 'reptile shell green', no: 'longneck meat' },
  { id: 'pterodactyl', icon: '🪽', ar: 'تيروداكتيل (الديناصور الطاير)', en: 'Pterodactyl', yes: 'wild meat extinct eggs_a flies', maybe: 'reptile tail big brown', no: 'bird' },
  { id: 'mammoth',     icon: '🦣', ar: 'ماموث', en: 'Mammoth', yes: 'mammal wild plants snow legs4 fur extinct tusks_a big brown', maybe: 'colony bigears' },
  { id: 'sabertooth',  icon: '🐯', ar: 'نمر أبو أسنان سيف', en: 'Saber-toothed cat', yes: 'mammal wild meat legs4 fur danger extinct tusks_a', maybe: 'snow big yellow brown' },
  { id: 'megalodon',   icon: '🦈', ar: 'ميجالودون (القرش العملاق)', en: 'Megalodon', yes: 'fish water meat nolegs danger extinct sea_a big', maybe: 'wild gray' },
]};
