/* العرّاف: characters from cartoons, films, tales and games (kind 'c'). One line each: id, icon,
   ar, en, and the question ids (OracleQuestions.js) that are true (yes), partly (maybe) and
   firmly not (no). Every character says whether it is human (in yes, maybe or no). A question
   about characters in none of the three reads as «غالباً لأ». notes/games/oracle.md, "Writing
   entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_CHARACTERS = { kind: 'c', list: [
  { id: 'mickey',     icon: '🐭', ar: 'ميكي ماوس', en: 'Mickey Mouse', yes: 'animal mammal cartoon disney black bigears tail', maybe: 'red duo', no: 'human' },
  { id: 'minnie',     icon: '🎀', ar: 'ميني ماوس', en: 'Minnie Mouse', yes: 'animal mammal cartoon disney female bigears black', maybe: 'pink red duo', no: 'human' },
  { id: 'donald',     icon: '🦆', ar: 'بطوط', en: 'Donald Duck', yes: 'animal bird cartoon disney white hat', maybe: 'blue', no: 'human' },
  { id: 'tom',        icon: '🐱', ar: 'توم (توم وجيري)', en: 'Tom (Tom and Jerry)', yes: 'animal mammal cartoon gray tail duo', maybe: 'legs4', no: 'human disney' },
  { id: 'jerry',      icon: '🐭', ar: 'جيري (توم وجيري)', en: 'Jerry (Tom and Jerry)', yes: 'animal mammal cartoon brown duo tail', maybe: 'bigears', no: 'human disney' },
  { id: 'spongebob',  icon: '🧽', ar: 'سبونج بوب', en: 'SpongeBob', yes: 'cartoon yellow water kidshow', maybe: 'animal duo', no: 'human' },
  { id: 'patrick',    icon: '⭐', ar: 'بسيط (صاحب سبونج بوب)', en: 'Patrick Star', yes: 'cartoon pink water kidshow', maybe: 'animal duo', no: 'human' },
  { id: 'bugsbunny',  icon: '🐰', ar: 'باجز باني', en: 'Bugs Bunny', yes: 'animal mammal cartoon gray bigears', maybe: 'white', no: 'human disney' },
  { id: 'popeye',     icon: '⚓', ar: 'باباي', en: 'Popeye', yes: 'human cartoon hat', maybe: 'powers fighter' },
  { id: 'pinkpanther', icon: '🐆', ar: 'النمر الوردي', en: 'The Pink Panther', yes: 'animal cartoon pink tail', maybe: 'mammal', no: 'human' },
  { id: 'garfield',   icon: '🐱', ar: 'جارفيلد', en: 'Garfield', yes: 'animal mammal cartoon orange stripes tail', maybe: 'legs4', no: 'human' },
  { id: 'scooby',     icon: '🐶', ar: 'سكوبي دو', en: 'Scooby-Doo', yes: 'animal mammal cartoon brown spots detective legs4 tail', maybe: 'group', no: 'human' },
  { id: 'simba',      icon: '🦁', ar: 'سيمبا (الأسد الملك)', en: 'Simba (The Lion King)', yes: 'animal mammal cartoon disney ruler legs4 tail', maybe: 'yellow child', no: 'human' },
  { id: 'aladdin',    icon: '🪔', ar: 'علاء الدين', en: 'Aladdin', yes: 'human cartoon disney tale arab', maybe: 'flies liveaction hat' },
  { id: 'genie',      icon: '🧞', ar: 'جني المصباح', en: 'The Genie of the lamp', yes: 'cartoon disney tale powers blue flies', maybe: 'human big arab' },
  { id: 'jasmine',    icon: '👸', ar: 'الأميرة ياسمين', en: 'Princess Jasmine', yes: 'human female princess cartoon disney tale arab', maybe: 'liveaction' },
  { id: 'cinderella', icon: '👠', ar: 'سندريلا', en: 'Cinderella', yes: 'human female princess cartoon disney tale blue' },
  { id: 'snowwhite',  icon: '🍎', ar: 'سنو وايت', en: 'Snow White', yes: 'human female princess cartoon disney tale', maybe: 'group', no: 'blue' },
  { id: 'elsa',       icon: '❄️', ar: 'إلسا (فروزن)', en: 'Elsa (Frozen)', yes: 'human female cartoon disney ruler powers blue', maybe: 'princess white' },
  { id: 'ariel',      icon: '🧜‍♀️', ar: 'عروسة البحر (آرييل)', en: 'Ariel (The Little Mermaid)', yes: 'female princess cartoon disney water', maybe: 'human fish red tale tail' },
  { id: 'pooh',       icon: '🍯', ar: 'ويني الدبدوب', en: 'Winnie the Pooh', yes: 'animal mammal cartoon disney yellow', maybe: 'toy kidshow', no: 'human' },
  { id: 'shrek',      icon: '👹', ar: 'شريك', en: 'Shrek', yes: 'cartoon green big', no: 'human villain disney' },
  { id: 'woody',      icon: '🤠', ar: 'وودي (حكاية لعبة)', en: 'Woody (Toy Story)', yes: 'cartoon disney toy hat', maybe: 'human duo brown' },
  { id: 'buzz',       icon: '🚀', ar: 'باز يطير (حكاية لعبة)', en: 'Buzz Lightyear', yes: 'cartoon disney toy', maybe: 'flies white green robot duo', no: 'human' },
  { id: 'nemo',       icon: '🐠', ar: 'نيمو', en: 'Nemo', yes: 'animal fish water cartoon disney orange white stripes child', no: 'human' },
  { id: 'mcqueen',    icon: '🏎️', ar: 'ماكوين (عربيات)', en: 'Lightning McQueen (Cars)', yes: 'cartoon disney robot vehicle wheels red', no: 'human animal' },
  { id: 'mario',      icon: '🍄', ar: 'ماريو', en: 'Mario', yes: 'human videogame hat red', maybe: 'cartoon blue' },
  { id: 'sonic',      icon: '🦔', ar: 'سونيك', en: 'Sonic', yes: 'animal videogame blue', maybe: 'mammal cartoon', no: 'human' },
  { id: 'pikachu',    icon: '⚡', ar: 'بيكاتشو', en: 'Pikachu', yes: 'animal anime cartoon yellow powers', maybe: 'videogame tail mammal', no: 'human' },
  { id: 'pacman',     icon: '🟡', ar: 'باك مان', en: 'Pac-Man', yes: 'videogame yellow', maybe: 'cartoon', no: 'human animal' },
  { id: 'majed',      icon: '⚽', ar: 'كابتن ماجد', en: 'Captain Majed (Tsubasa)', yes: 'human anime cartoon football', maybe: 'child kidshow' },
  { id: 'grendizer',  icon: '🤖', ar: 'جريندايزر', en: 'Grendizer', yes: 'anime cartoon robot flies big warrior', maybe: 'hero powers', no: 'human animal' },
  { id: 'conan',      icon: '🔎', ar: 'المحقق كونان', en: 'Detective Conan', yes: 'human anime cartoon detective child', maybe: 'kidshow' },
  { id: 'smurf',      icon: '🍄', ar: 'سنفور (السنافر)', en: 'A Smurf', yes: 'cartoon blue group hat', maybe: 'white kidshow', no: 'animal human' },
  { id: 'superman',   icon: '🦸', ar: 'سوبرمان', en: 'Superman', yes: 'human hero powers flies blue red', maybe: 'liveaction cartoon' },
  { id: 'batman',     icon: '🦇', ar: 'باتمان', en: 'Batman', yes: 'human hero mask black', maybe: 'liveaction cartoon', no: 'powers' },
  { id: 'spiderman',  icon: '🕷️', ar: 'سبايدر مان', en: 'Spider-Man', yes: 'human hero powers mask red blue', maybe: 'liveaction cartoon' },
  { id: 'hulk',       icon: '💪', ar: 'هالك', en: 'Hulk', yes: 'human hero powers green big', maybe: 'liveaction' },
  { id: 'ironman',    icon: '🦾', ar: 'أيرون مان', en: 'Iron Man', yes: 'human hero flies red liveaction', maybe: 'yellow mask robot' },
  { id: 'harrypotter', icon: '🪄', ar: 'هاري بوتر', en: 'Harry Potter', yes: 'human liveaction powers', maybe: 'child flies' },
  { id: 'sherlock',   icon: '🔍', ar: 'شيرلوك هولمز', en: 'Sherlock Holmes', yes: 'human detective liveaction', maybe: 'hat duo' },
  { id: 'pinocchio',  icon: '🤥', ar: 'بينوكيو', en: 'Pinocchio', yes: 'toy tale child', maybe: 'cartoon disney human' },
  { id: 'peterpan',   icon: '🧚', ar: 'بيتر بان', en: 'Peter Pan', yes: 'human child flies', maybe: 'cartoon disney tale green hat' },
  { id: 'tarzan',     icon: '🌴', ar: 'طرزان', en: 'Tarzan', yes: 'human cartoon disney', maybe: 'tale liveaction' },
  { id: 'mrbean',     icon: '🤓', ar: 'مستر بين', en: 'Mr. Bean', yes: 'human liveaction comedy', maybe: 'cartoon' },
  { id: 'bakkar',     icon: '🐐', ar: 'بكار', en: 'Bakkar', yes: 'human egypt cartoon child kidshow', maybe: 'duo' },
  { id: 'boogie',     icon: '🧸', ar: 'بوجي وطمطم', en: 'Boogie and Tamtam', yes: 'egypt kidshow duo toy', maybe: 'animal', no: 'human cartoon' },
  { id: 'alibaba',    icon: '💰', ar: 'علي بابا', en: 'Ali Baba', yes: 'human tale arab', maybe: 'cartoon' },
  { id: 'sindbad',    icon: '⛵', ar: 'سندباد', en: 'Sinbad', yes: 'human tale arab explorer', maybe: 'water cartoon' },
  { id: 'shahrazad',  icon: '📜', ar: 'شهرزاد', en: 'Scheherazade', yes: 'human female tale arab', maybe: 'ruler' },
  { id: 'goha',       icon: '🫏', ar: 'جحا', en: 'Goha', yes: 'human tale arab comedy', maybe: 'egypt hat' },
  { id: 'fattouta',   icon: '🟢', ar: 'فطوطة', en: 'Fattouta', yes: 'human egypt liveaction comedy fawazeer', maybe: 'kidshow' },
  { id: 'lembi',      icon: '😄', ar: 'اللمبي', en: 'El Lembi', yes: 'human egypt liveaction comedy', no: 'kidshow fawazeer' },
  { id: 'turtles',    icon: '🐢', ar: 'سلاحف النينجا', en: 'The Ninja Turtles', yes: 'animal reptile shell green group mask cartoon hero', maybe: 'warrior fighter', no: 'human' },
  { id: 'peppa',      icon: '🐷', ar: 'ببا بيج', en: 'Peppa Pig', yes: 'animal mammal cartoon kidshow pink female child', no: 'human' },
  { id: 'dora',       icon: '🎒', ar: 'دورا', en: 'Dora', yes: 'human female cartoon kidshow child' },
  { id: 'masha',      icon: '👧', ar: 'ماشا والدب', en: 'Masha and the Bear', yes: 'human female cartoon kidshow child duo' },
  { id: 'minions',    icon: '🍌', ar: 'المينيونز', en: 'The Minions', yes: 'cartoon yellow group', maybe: 'blue', no: 'human animal' },
  { id: 'doraemon',   icon: '🔔', ar: 'دورايمون', en: 'Doraemon', yes: 'anime cartoon robot blue', maybe: 'animal powers kidshow', no: 'human' },
  { id: 'tweety',     icon: '🐤', ar: 'تويتي', en: 'Tweety', yes: 'animal bird cartoon yellow flies', maybe: 'child', no: 'human' },
  { id: 'olaf',       icon: '⛄', ar: 'أولاف (فروزن)', en: 'Olaf (Frozen)', yes: 'cartoon disney white', no: 'human animal' },
  { id: 'po',         icon: '🐼', ar: 'بو (كونج فو باندا)', en: 'Po (Kung Fu Panda)', yes: 'animal mammal cartoon fighter black white', maybe: 'warrior big', no: 'human' },
  { id: 'heidi',      icon: '⛰️', ar: 'هايدي', en: 'Heidi', yes: 'human female cartoon anime child', maybe: 'kidshow' },
  { id: 'jafar',      icon: '🐍', ar: 'جعفر (علاء الدين)', en: 'Jafar (Aladdin)', yes: 'human villain cartoon disney tale arab powers', maybe: 'hat' },
  { id: 'scar',       icon: '🦁', ar: 'سكار (الأسد الملك)', en: 'Scar (The Lion King)', yes: 'animal mammal villain cartoon disney legs4 tail', maybe: 'brown ruler', no: 'human' },
  { id: 'joker',      icon: '🃏', ar: 'الجوكر', en: 'The Joker', yes: 'human villain', maybe: 'liveaction cartoon green' },
  { id: 'gargamel',   icon: '🧙', ar: 'شرشبيل (السنافر)', en: 'Gargamel (The Smurfs)', yes: 'human villain cartoon powers', maybe: 'kidshow black' },
  { id: 'hook',       icon: '🪝', ar: 'كابتن هوك', en: 'Captain Hook', yes: 'human villain hat', maybe: 'cartoon disney red water' },
  { id: 'dumbo',      icon: '🐘', ar: 'دامبو', en: 'Dumbo', yes: 'animal mammal cartoon disney flies bigears gray', maybe: 'child big', no: 'human' },
]};
