/* العرّاف: characters from cartoons, films, tales and games (kind 'c'). One line each: id, icon,
   ar, en, and the question ids (OracleQuestions.js) that are true (yes), partly (maybe) and
   firmly not (no). Every character says whether it is human (in yes, maybe or no). A question
   about characters in none of the three reads as «غالباً لأ». notes/games/oracle.md, "Writing
   entries"; check with `cd tools && npm run check:oracle`. */
const ORACLE_CHARACTERS = { kind: 'c', list: [
  { id: 'mickey',     icon: '🐭', ar: 'ميكي ماوس', en: 'Mickey Mouse', yes: 'cartoon disney mouse classic mammal tail bigears black animal', maybe: 'kidshow duo series_c red', no: 'human' },
  { id: 'minnie',     icon: '🎀', ar: 'ميني ماوس', en: 'Minnie Mouse', yes: 'female cartoon disney mouse classic mammal tail bigears black animal', maybe: 'kidshow duo series_c spots red pink', no: 'human' },
  { id: 'donald',     icon: '🦆', ar: 'بطوط', en: 'Donald Duck', yes: 'cartoon disney hat classic bird white animal', maybe: 'comedy kidshow series_c flies blue', no: 'human' },
  { id: 'tom',        icon: '🐱', ar: 'توم (توم وجيري)', en: 'Tom (Tom and Jerry)', yes: 'cartoon kidshow duo cat series_c classic mammal tail gray animal', maybe: 'comedy legs4 blue', no: 'human disney' },
  { id: 'jerry',      icon: '🐭', ar: 'جيري (توم وجيري)', en: 'Jerry (Tom and Jerry)', yes: 'cartoon kidshow duo mouse series_c classic mammal tail brown animal', maybe: 'comedy bigears', no: 'human disney' },
  { id: 'spongebob',  icon: '🧽', ar: 'سبونج بوب', en: 'SpongeBob', yes: 'cartoon kidshow duo series_c classic water yellow', maybe: 'comedy animal object', no: 'human' },
  { id: 'patrick',    icon: '⭐', ar: 'بسيط (صاحب سبونج بوب)', en: 'Patrick Star', yes: 'comedy cartoon kidshow duo series_c classic water pink animal', no: 'human' },
  { id: 'bugsbunny',  icon: '🐰', ar: 'باجز باني', en: 'Bugs Bunny', yes: 'cartoon classic mammal bigears gray animal', maybe: 'comedy kidshow series_c white', no: 'human' },
  { id: 'popeye',     icon: '⚓', ar: 'باباي', en: 'Popeye', yes: 'cartoon hat classic human', maybe: 'fighter liveaction hero powers kidshow series_c water' },
  { id: 'pinkpanther', icon: '🐆', ar: 'النمر الوردي', en: 'The Pink Panther', yes: 'comedy cartoon cat classic mammal tail pink animal', maybe: 'kidshow series_c', no: 'human' },
  { id: 'garfield',   icon: '🐱', ar: 'جارفيلد', en: 'Garfield', yes: 'cartoon cat classic mammal stripes tail orange animal', maybe: 'comedy kidshow duo series_c legs4 yellow', no: 'human' },
  { id: 'scooby',     icon: '🐶', ar: 'سكوبي دو', en: 'Scooby-Doo', yes: 'cartoon kidshow detective duo dog series_c classic mammal legs4 spots tail brown animal', maybe: 'comedy liveaction', no: 'human' },
  { id: 'simba',      icon: '🦁', ar: 'سيمبا (الأسد الملك)', en: 'Simba (The Lion King)', yes: 'ruler cartoon disney cat classic mammal legs4 tail animal', maybe: 'child big yellow', no: 'human series_c' },
  { id: 'aladdin',    icon: '🪔', ar: 'علاء الدين', en: 'Aladdin', yes: 'arab cartoon disney tale classic human', maybe: 'liveaction powers hat weapon flies' },
  { id: 'genie',      icon: '🧞', ar: 'جني المصباح', en: 'The Genie of the lamp', yes: 'cartoon disney powers tale beard classic flies blue', maybe: 'arab comedy liveaction big human' },
  { id: 'jasmine',    icon: '👸', ar: 'الأميرة ياسمين', en: 'Princess Jasmine', yes: 'female arab cartoon disney princess tale classic human', maybe: 'liveaction blue' },
  { id: 'cinderella', icon: '👠', ar: 'سندريلا', en: 'Cinderella', yes: 'female cartoon disney princess tale classic blue human', maybe: 'liveaction' },
  { id: 'snowwhite',  icon: '🍎', ar: 'سنو وايت', en: 'Snow White', yes: 'female cartoon disney princess tale classic human', maybe: 'liveaction cape yellow blue' },
  { id: 'elsa',       icon: '❄️', ar: 'إلسا (فروزن)', en: 'Elsa (Frozen)', yes: 'female ruler cartoon disney powers blue human', maybe: 'princess duo cape white', no: 'classic series_c' },
  { id: 'ariel',      icon: '🧜‍♀️', ar: 'عروسة البحر (آرييل)', en: 'Ariel (The Little Mermaid)', yes: 'female cartoon disney princess tale classic water tail', maybe: 'liveaction fish red green human animal' },
  { id: 'pooh',       icon: '🍯', ar: 'ويني الدبدوب', en: 'Winnie the Pooh', yes: 'cartoon disney classic mammal yellow animal', maybe: 'kidshow red toy', no: 'human' },
  { id: 'shrek',      icon: '👹', ar: 'شريك', en: 'Shrek', yes: 'cartoon duo big green', maybe: 'comedy classic bigears human', no: 'villain disney' },
  { id: 'woody',      icon: '🤠', ar: 'وودي (حكاية لعبة)', en: 'Woody (Toy Story)', yes: 'cartoon disney hat duo classic toy object', maybe: 'yellow brown human' },
  { id: 'buzz',       icon: '🚀', ar: 'باز يطير (حكاية لعبة)', en: 'Buzz Lightyear', yes: 'cartoon disney duo classic toy object', maybe: 'explorer robot alien flies green white', no: 'human' },
  { id: 'nemo',       icon: '🐠', ar: 'نيمو', en: 'Nemo', yes: 'cartoon disney child fish water stripes orange animal', maybe: 'duo white', no: 'human classic' },
  { id: 'mcqueen',    icon: '🏎️', ar: 'ماكوين (عربيات)', en: 'Lightning McQueen (Cars)', yes: 'cartoon disney robot duo big red vehicle wheels object', maybe: 'athlete', no: 'human animal classic' },
  { id: 'mario',      icon: '🍄', ar: 'ماريو', en: 'Mario', yes: 'videogame hat duo beard classic red human', maybe: 'cartoon powers blue' },
  { id: 'sonic',      icon: '🦔', ar: 'سونيك', en: 'Sonic', yes: 'videogame classic mammal blue animal', maybe: 'cartoon powers', no: 'human' },
  { id: 'pikachu',    icon: '⚡', ar: 'بيكاتشو', en: 'Pikachu', yes: 'cartoon anime powers kidshow duo series_c classic tail bigears yellow animal', maybe: 'videogame mammal legs4', no: 'human' },
  { id: 'pacman',     icon: '🟡', ar: 'باك مان', en: 'Pac-Man', yes: 'videogame classic yellow', maybe: 'cartoon object', no: 'human animal' },
  { id: 'majed',      icon: '⚽', ar: 'كابتن ماجد', en: 'Captain Majed (Tsubasa)', yes: 'athlete football cartoon anime kidshow series_c classic human', maybe: 'child' },
  { id: 'grendizer',  icon: '🤖', ar: 'جريندايزر', en: 'Grendizer', yes: 'warrior cartoon anime kidshow robot series_c classic alien flies big object', maybe: 'hero powers weapon', no: 'human animal' },
  { id: 'conan',      icon: '🔎', ar: 'المحقق كونان', en: 'Detective Conan', yes: 'cartoon anime kidshow child detective glasses series_c classic human' },
  { id: 'smurf',      icon: '🍄', ar: 'سنفور (السنافر)', en: 'A Smurf', yes: 'cartoon kidshow hat group series_c classic blue', maybe: 'white human', no: 'animal' },
  { id: 'superman',   icon: '🦸', ar: 'سوبرمان', en: 'Superman', yes: 'liveaction hero powers cape classic alien flies red blue', maybe: 'cartoon glasses human' },
  { id: 'batman',     icon: '🦇', ar: 'باتمان', en: 'Batman', yes: 'liveaction hero mask cape classic black human', maybe: 'fighter cartoon detective duo', no: 'powers' },
  { id: 'spiderman',  icon: '🕷️', ar: 'سبايدر مان', en: 'Spider-Man', yes: 'liveaction hero powers mask classic red blue human', maybe: 'cartoon disney insect flies', no: 'cape' },
  { id: 'hulk',       icon: '💪', ar: 'هالك', en: 'Hulk', yes: 'liveaction hero powers classic big green human', maybe: 'fighter cartoon disney' },
  { id: 'ironman',    icon: '🦾', ar: 'أيرون مان', en: 'Iron Man', yes: 'liveaction hero beard flies red human', maybe: 'disney powers mask robot classic shell yellow' },
  { id: 'harrypotter', icon: '🪄', ar: 'هاري بوتر', en: 'Harry Potter', yes: 'liveaction powers glasses human', maybe: 'child duo cape classic flies' },
  { id: 'sherlock',   icon: '🔍', ar: 'شيرلوك هولمز', en: 'Sherlock Holmes', yes: 'liveaction hat detective duo classic human', maybe: 'tale series_c' },
  { id: 'pinocchio',  icon: '🤥', ar: 'بينوكيو', en: 'Pinocchio', yes: 'cartoon disney tale child hat classic toy', maybe: 'anime liveaction human object' },
  { id: 'peterpan',   icon: '🧚', ar: 'بيتر بان', en: 'Peter Pan', yes: 'cartoon disney powers child hat classic flies green human', maybe: 'liveaction tale weapon' },
  { id: 'tarzan',     icon: '🌴', ar: 'طرزان', en: 'Tarzan', yes: 'cartoon disney classic human', maybe: 'liveaction tale' },
  { id: 'mrbean',     icon: '🤓', ar: 'مستر بين', en: 'Mr. Bean', yes: 'comedy liveaction series_c classic human', maybe: 'cartoon' },
  { id: 'bakkar',     icon: '🐐', ar: 'بكار', en: 'Bakkar', yes: 'egypt arab cartoon kidshow child duo series_c classic ramadan_c human' },
  { id: 'boogie',     icon: '🧸', ar: 'بوجي وطمطم', en: 'Boogie and Tamtam', yes: 'egypt arab kidshow duo series_c classic ramadan_c toy', maybe: 'female comedy child human object', no: 'cartoon' },
  { id: 'alibaba',    icon: '💰', ar: 'علي بابا', en: 'Ali Baba', yes: 'arab tale classic human', maybe: 'cartoon liveaction beard' },
  { id: 'sindbad',    icon: '⛵', ar: 'سندباد', en: 'Sinbad', yes: 'arab explorer tale classic human', maybe: 'cartoon anime liveaction hat beard weapon water' },
  { id: 'shahrazad',  icon: '📜', ar: 'شهرزاد', en: 'Scheherazade', yes: 'female arab tale classic human', maybe: 'ruler liveaction duo' },
  { id: 'goha',       icon: '🫏', ar: 'جحا', en: 'Goha', yes: 'arab comedy tale beard classic human', maybe: 'egypt liveaction hat old' },
  { id: 'fattouta',   icon: '🟢', ar: 'فطوطة', en: 'Fattouta', yes: 'egypt arab comedy fawazeer liveaction series_c classic ramadan_c human', maybe: 'kidshow' },
  { id: 'lembi',      icon: '😄', ar: 'اللمبي', en: 'El Lembi', yes: 'egypt arab comedy liveaction human', no: 'kidshow fawazeer classic series_c' },
  { id: 'turtles',    icon: '🐢', ar: 'سلاحف النينجا', en: 'The Ninja Turtles', yes: 'fighter cartoon hero kidshow mask group weapon series_c classic reptile shell green animal', maybe: 'warrior', no: 'human' },
  { id: 'peppa',      icon: '🐷', ar: 'ببا بيج', en: 'Peppa Pig', yes: 'female cartoon kidshow child series_c mammal pink animal', no: 'human classic' },
  { id: 'dora',       icon: '🎒', ar: 'دورا', en: 'Dora', yes: 'female explorer cartoon kidshow child series_c human', no: 'classic' },
  { id: 'masha',      icon: '👧', ar: 'ماشا والدب', en: 'Masha and the Bear', yes: 'female cartoon kidshow child duo series_c', maybe: 'mammal brown human animal', no: 'classic' },
  { id: 'minions',    icon: '🍌', ar: 'المينيونز', en: 'The Minions', yes: 'comedy cartoon group glasses yellow', maybe: 'blue', no: 'human animal classic' },
  { id: 'doraemon',   icon: '🔔', ar: 'دورايمون', en: 'Doraemon', yes: 'cartoon anime kidshow robot series_c classic blue', maybe: 'powers cat mammal tail flies white animal object', no: 'human' },
  { id: 'tweety',     icon: '🐤', ar: 'تويتي', en: 'Tweety', yes: 'cartoon duo classic bird flies yellow animal', maybe: 'comedy kidshow child series_c', no: 'human' },
  { id: 'olaf',       icon: '⛄', ar: 'أولاف (فروزن)', en: 'Olaf (Frozen)', yes: 'cartoon disney white', maybe: 'comedy object', no: 'human animal classic' },
  { id: 'po',         icon: '🐼', ar: 'بو (كونج فو باندا)', en: 'Po (Kung Fu Panda)', yes: 'fighter cartoon mammal white black animal', maybe: 'warrior comedy powers big', no: 'human classic' },
  { id: 'heidi',      icon: '⛰️', ar: 'هايدي', en: 'Heidi', yes: 'female cartoon anime kidshow child series_c classic human', maybe: 'tale' },
  { id: 'jafar',      icon: '🐍', ar: 'جعفر (علاء الدين)', en: 'Jafar (Aladdin)', yes: 'arab cartoon disney powers villain tale beard classic human', maybe: 'ruler hat cape old black' },
  { id: 'scar',       icon: '🦁', ar: 'سكار (الأسد الملك)', en: 'Scar (The Lion King)', yes: 'cartoon disney villain cat classic mammal legs4 tail animal', maybe: 'ruler big black brown', no: 'human' },
  { id: 'joker',      icon: '🃏', ar: 'الجوكر', en: 'The Joker', yes: 'liveaction villain classic human', maybe: 'cartoon green' },
  { id: 'gargamel',   icon: '🧙', ar: 'شرشبيل (السنافر)', en: 'Gargamel (The Smurfs)', yes: 'cartoon powers villain kidshow series_c classic human', maybe: 'old black' },
  { id: 'hook',       icon: '🪝', ar: 'كابتن هوك', en: 'Captain Hook', yes: 'disney villain hat beard weapon classic human', maybe: 'cartoon liveaction tale water red' },
  { id: 'dumbo',      icon: '🐘', ar: 'دامبو', en: 'Dumbo', yes: 'cartoon disney child classic mammal legs4 bigears flies gray animal', maybe: 'big', no: 'human' },

  /* ---------- phase 2 (9 Oct 2026): Egyptian and Arab, Ramadan, films and series ---------- */
  { id: 'zaza',       icon: '🥬', ar: 'ظاظا وجرجير', en: 'Zaza and Gargir', yes: 'egypt arab kidshow duo series_c', maybe: 'comedy cartoon classic ramadan_c toy human' },
  { id: 'rashida',    icon: '🐐', ar: 'رشيدة (معزة بكار)', en: "Rashida (Bakkar's goat)", yes: 'female egypt arab cartoon kidshow duo series_c classic ramadan_c mammal legs4 animal', no: 'human' },
  { id: 'wanis',      icon: '👨‍👩‍👧', ar: 'ونيس (يوميات ونيس)', en: 'Wanis (The Diaries of Wanis)', yes: 'egypt arab comedy liveaction series_c classic ramadan_c human', maybe: 'old', no: 'cartoon villain kidshow' },
  { id: 'kabeer',     icon: '👳', ar: 'الكبير أوي', en: 'El Kabeer Awi', yes: 'egypt arab comedy liveaction beard series_c ramadan_c human', maybe: 'ruler', no: 'classic cartoon' },
  { id: 'ramadanmabrouk', icon: '📚', ar: 'رمضان مبروك أبو العلمين حمودة', en: 'Ramadan Mabrouk Abul-Alamein Hamouda', yes: 'egypt arab comedy liveaction beard human', no: 'series_c classic cartoon' },
  { id: 'sisayed',    icon: '🎩', ar: 'سي السيد', en: 'Si El-Sayed', yes: 'egypt arab liveaction hat beard classic human', maybe: 'old series_c', no: 'comedy cartoon' },
  { id: 'sheikhhosny', icon: '🕶️', ar: 'الشيخ حسني (الكيت كات)', en: 'Sheikh Hosny (Kit Kat)', yes: 'egypt arab liveaction glasses classic human', maybe: 'comedy beard old', no: 'series_c cartoon' },
  { id: 'sonbol',     icon: '🎒', ar: 'سنبل', en: 'Sonbol', yes: 'egypt arab comedy liveaction series_c classic human', maybe: 'ramadan_c', no: 'cartoon' },
  { id: 'amofouad',   icon: '👴', ar: 'عمو فؤاد', en: 'Uncle Fouad', yes: 'egypt arab comedy liveaction kidshow series_c classic ramadan_c human', maybe: 'fawazeer glasses old', no: 'cartoon' },
  { id: 'adham',      icon: '🔫', ar: 'أدهم صبري (رجل المستحيل)', en: 'Adham Sabri (The Man of the Impossible)', yes: 'egypt arab fighter weapon classic human', maybe: 'hero mask detective', no: 'liveaction cartoon comedy' },
  { id: 'baqlaz',     icon: '🧸', ar: 'بقلظ (ماما نجوى)', en: 'Baqlaz', yes: 'egypt arab comedy kidshow duo series_c classic toy', maybe: 'ramadan_c object', no: 'cartoon human' },
  { id: 'shaterhassan', icon: '🗡️', ar: 'الشاطر حسن', en: 'Clever Hassan', yes: 'egypt arab tale classic human', maybe: 'cartoon child', no: 'female liveaction villain' },
  { id: 'ghoula',     icon: '👹', ar: 'أمنا الغولة', en: 'The Ogress (Ommena el-Ghoula)', yes: 'female egypt arab powers villain tale classic', maybe: 'old big human' },
  { id: 'shahryar',   icon: '👑', ar: 'شهريار', en: 'Shahryar', yes: 'arab ruler tale beard classic human', maybe: 'liveaction villain duo cape' },
  { id: 'fortythieves', icon: '🗝️', ar: 'الأربعين حرامي', en: 'The Forty Thieves', yes: 'arab villain tale group beard weapon classic human', maybe: 'liveaction' },
  { id: 'kalila',     icon: '🦊', ar: 'كليلة ودمنة', en: 'Kalila and Dimna', yes: 'arab tale duo classic mammal legs4 tail animal', maybe: 'villain kidshow dog series_c brown', no: 'human' },

  /* ---------- anime known in Egypt ---------- */
  { id: 'adnanconan', icon: '🏝️', ar: 'عدنان (عدنان ولينا)', en: 'Adnan (Future Boy Conan)', yes: 'cartoon anime kidshow child duo series_c classic human', maybe: 'water' },
  { id: 'lanaconan',  icon: '🌸', ar: 'لينا (عدنان ولينا)', en: 'Lana (Future Boy Conan)', yes: 'female cartoon anime kidshow child duo series_c classic human' },
  { id: 'remianime',  icon: '🎻', ar: 'ريمي', en: "Remi (Nobody's Boy)", yes: 'cartoon anime kidshow child hat series_c classic human', maybe: 'explorer tale' },
  { id: 'tigermask',  icon: '🐯', ar: 'النمر المقنع', en: 'Tiger Mask', yes: 'athlete fighter cartoon anime kidshow mask series_c classic human', maybe: 'hero' },
  { id: 'nils',       icon: '🪿', ar: 'نيلز', en: 'Nils Holgersson', yes: 'cartoon anime kidshow child hat series_c classic flies human', maybe: 'explorer tale duo' },
  { id: 'mayabee',    icon: '🐝', ar: 'زينة النحلة', en: 'Maya the Bee', yes: 'female cartoon anime kidshow series_c classic insect stripes flies yellow black animal', no: 'human' },
  { id: 'bellesebastian', icon: '🐕', ar: 'بيل وسبستيان', en: 'Belle and Sebastian', yes: 'cartoon anime kidshow child duo dog series_c classic mammal white', maybe: 'female legs4 big human animal' },
  { id: 'mazinger',   icon: '🦾', ar: 'مازنجر', en: 'Mazinger Z', yes: 'warrior cartoon anime kidshow robot series_c classic big black object', maybe: 'hero powers weapon flies blue gray', no: 'human animal alien' },
  { id: 'goku',       icon: '🐉', ar: 'جوكو (دراجون بول)', en: 'Goku (Dragon Ball)', yes: 'fighter cartoon anime powers series_c classic alien flies', maybe: 'warrior athlete hero kidshow child tail orange human' },
  { id: 'naruto',     icon: '🍥', ar: 'ناروتو', en: 'Naruto', yes: 'fighter cartoon anime powers series_c orange human', maybe: 'warrior kidshow child weapon classic yellow' },
  { id: 'luffy',      icon: '👒', ar: 'لوفي (ون بيس)', en: 'Luffy (One Piece)', yes: 'cartoon anime powers hat series_c classic human', maybe: 'fighter explorer kidshow water red' },
  { id: 'ashketchum', icon: '🧢', ar: 'آش (بوكيمون)', en: 'Ash (Pokémon)', yes: 'cartoon anime kidshow child hat duo series_c classic human', maybe: 'videogame' },
  { id: 'sailormoon', icon: '🌙', ar: 'سيلور مون', en: 'Sailor Moon', yes: 'female cartoon anime hero powers kidshow series_c classic human', maybe: 'princess child group' },

  /* ---------- Disney and Pixar ---------- */
  { id: 'goofy',      icon: '🐕', ar: 'جوفي', en: 'Goofy', yes: 'comedy cartoon disney hat dog classic mammal animal', maybe: 'kidshow series_c bigears', no: 'human' },
  { id: 'plutodog',   icon: '🦴', ar: 'بلوتو (كلب ميكي)', en: "Pluto (Mickey's dog)", yes: 'cartoon disney dog classic mammal legs4 tail yellow animal', maybe: 'kidshow series_c orange', no: 'human' },
  { id: 'daisyduck',  icon: '🦆', ar: 'ديزي (صاحبة بطوط)', en: 'Daisy Duck', yes: 'female cartoon disney classic bird white animal', maybe: 'kidshow duo series_c pink', no: 'human' },
  { id: 'belle',      icon: '🌹', ar: 'بيل (الجميلة والوحش)', en: 'Belle (Beauty and the Beast)', yes: 'female cartoon disney tale classic yellow human', maybe: 'liveaction princess duo blue' },
  { id: 'thebeast',   icon: '🥀', ar: 'الوحش (الجميلة والوحش)', en: 'The Beast (Beauty and the Beast)', yes: 'cartoon disney tale classic big brown', maybe: 'ruler liveaction duo human' },
  { id: 'sleepingbeauty', icon: '💤', ar: 'الأميرة النائمة', en: 'Sleeping Beauty (Aurora)', yes: 'female cartoon disney princess tale classic pink human', maybe: 'liveaction blue', no: 'series_c powers' },
  { id: 'rapunzel',   icon: '👱‍♀️', ar: 'رابونزل', en: 'Rapunzel (Tangled)', yes: 'female cartoon disney powers princess tale human', maybe: 'classic pink' },
  { id: 'moana',      icon: '🌊', ar: 'موانا', en: 'Moana', yes: 'female cartoon disney human', maybe: 'ruler explorer princess child water', no: 'classic' },
  { id: 'mulan',      icon: '⚔️', ar: 'مولان', en: 'Mulan', yes: 'female warrior cartoon disney weapon classic human', maybe: 'fighter liveaction princess tale' },
  { id: 'pocahontas', icon: '🍃', ar: 'بوكاهونتس', en: 'Pocahontas', yes: 'female cartoon disney classic human', maybe: 'princess brown' },
  { id: 'maleficent', icon: '🖤', ar: 'ماليفسنت (الساحرة الشريرة)', en: 'Maleficent', yes: 'female cartoon disney powers villain classic black', maybe: 'liveaction tale cape flies green human' },
  { id: 'ursula',     icon: '🐙', ar: 'أورسولا (عروسة البحر)', en: 'Ursula (The Little Mermaid)', yes: 'female cartoon disney powers villain classic water big', maybe: 'human' },
  { id: 'cruella',    icon: '🧥', ar: 'كرويلا', en: 'Cruella de Vil', yes: 'female cartoon disney villain classic human', maybe: 'liveaction white black' },
  { id: 'dalmatians', icon: '🐶', ar: 'الـ101 كلب دلماسي', en: '101 Dalmatians', yes: 'cartoon disney group dog classic mammal legs4 spots tail white black animal', maybe: 'liveaction', no: 'human' },
  { id: 'stitch',     icon: '👽', ar: 'ستيتش', en: 'Stitch', yes: 'cartoon disney duo alien bigears blue', maybe: 'powers legs4 animal', no: 'human classic' },
  { id: 'bambi',      icon: '🦌', ar: 'بامبي', en: 'Bambi', yes: 'cartoon disney child classic mammal legs4 spots brown animal', maybe: 'bigears', no: 'human' },
  { id: 'mowgli',     icon: '🌿', ar: 'ماوكلي', en: 'Mowgli (The Jungle Book)', yes: 'cartoon disney child classic human', maybe: 'anime liveaction tale duo' },
  { id: 'baloo',      icon: '🐻', ar: 'بالو (كتاب الأدغال)', en: 'Baloo (The Jungle Book)', yes: 'cartoon disney classic mammal big gray animal', maybe: 'comedy tale duo legs4', no: 'human' },
  { id: 'sherekhan',  icon: '🐅', ar: 'شير خان', en: 'Shere Khan', yes: 'cartoon disney villain cat classic mammal legs4 stripes tail orange animal', maybe: 'tale big', no: 'human' },
  { id: 'timon',      icon: '🦦', ar: 'تيمون', en: 'Timon (The Lion King)', yes: 'comedy cartoon disney duo classic mammal tail animal', maybe: 'brown', no: 'human' },
  { id: 'pumbaa',     icon: '🐗', ar: 'بومبا', en: 'Pumbaa (The Lion King)', yes: 'comedy cartoon disney duo classic mammal legs4 brown animal', maybe: 'big', no: 'human' },
  { id: 'mufasa',     icon: '🦁', ar: 'موفاسا', en: 'Mufasa (The Lion King)', yes: 'ruler cartoon disney cat classic mammal legs4 tail big animal', maybe: 'yellow brown', no: 'human' },
  { id: 'walle',      icon: '🤖', ar: 'وول-إي', en: 'WALL-E', yes: 'cartoon disney robot object', maybe: 'explorer yellow brown wheels', no: 'human animal classic' },
  { id: 'sulley',     icon: '👾', ar: 'سولي (شركة المرعبين)', en: 'Sulley (Monsters, Inc.)', yes: 'cartoon disney duo spots tail big blue', maybe: 'animal', no: 'human classic' },
  { id: 'mikewazowski', icon: '👁️', ar: 'مايك (شركة المرعبين)', en: 'Mike Wazowski (Monsters, Inc.)', yes: 'comedy cartoon disney duo green', maybe: 'animal', no: 'human classic' },
  { id: 'dory',       icon: '🐟', ar: 'دوري', en: 'Dory', yes: 'female cartoon disney fish water blue animal', maybe: 'comedy duo stripes yellow', no: 'human classic' },
  { id: 'remy',       icon: '🐀', ar: 'الفار ريمي (راتاتوي)', en: 'Remy (Ratatouille)', yes: 'cartoon disney mouse mammal tail gray animal', maybe: 'legs4 bigears', no: 'human classic' },
  { id: 'incredible', icon: '💥', ar: 'مستر إنكريديبل (الخارقون)', en: 'Mr. Incredible (The Incredibles)', yes: 'cartoon disney hero powers mask red human', maybe: 'big', no: 'classic' },
  { id: 'mater',      icon: '🛻', ar: 'ماتر (عربيات)', en: 'Mater (Cars)', yes: 'comedy cartoon disney robot duo big brown vehicle wheels object', no: 'human animal classic' },
  { id: 'jessie',     icon: '🤠', ar: 'جيسي (حكاية لعبة)', en: 'Jessie (Toy Story)', yes: 'female cartoon disney hat classic toy object', maybe: 'duo red human' },
  { id: 'tinkerbell', icon: '🧚‍♀️', ar: 'تينكربل', en: 'Tinker Bell', yes: 'female cartoon disney powers classic flies green', maybe: 'tale human' },
  { id: 'jacksparrow', icon: '🏴‍☠️', ar: 'جاك سبارو', en: 'Jack Sparrow', yes: 'disney liveaction hat beard weapon human', maybe: 'comedy water', no: 'cartoon classic' },
  { id: 'marypoppins', icon: '☂️', ar: 'ماري بوبينز', en: 'Mary Poppins', yes: 'female disney liveaction powers hat classic flies human', maybe: 'cartoon' },
  { id: 'merida',     icon: '🏹', ar: 'ميريدا (الشجاعة)', en: 'Merida (Brave)', yes: 'female cartoon disney princess weapon human', maybe: 'warrior child red orange', no: 'classic' },
  { id: 'herculesdisney', icon: '💪', ar: 'هرقل', en: 'Hercules', yes: 'cartoon disney powers classic human', maybe: 'warrior fighter liveaction hero tale weapon' },
  { id: 'baymax',     icon: '🤍', ar: 'بايماكس', en: 'Baymax', yes: 'cartoon disney hero robot flies big white object', no: 'human animal classic' },
  { id: 'judyhopps',  icon: '🐰', ar: 'جودي (زوتوبيا)', en: 'Judy Hopps (Zootopia)', yes: 'female cartoon disney detective mammal bigears gray animal', no: 'human classic' },
  { id: 'carlup',     icon: '🎈', ar: 'كارل (فوق)', en: 'Carl (Up)', yes: 'cartoon disney glasses old human', maybe: 'explorer duo flies', no: 'classic' },
  { id: 'chipdale',   icon: '🐿️', ar: 'تشيب وديل', en: "Chip 'n Dale", yes: 'cartoon disney duo classic mammal stripes tail brown animal', maybe: 'kidshow group series_c', no: 'human' },
  { id: 'dwarfs',     icon: '⛏️', ar: 'الأقزام السبعة', en: 'The Seven Dwarfs', yes: 'cartoon disney tale hat group beard old classic human', maybe: 'comedy' },
  { id: 'alice',      icon: '🐇', ar: 'أليس في بلاد العجائب', en: 'Alice in Wonderland', yes: 'female cartoon disney tale child classic blue human', maybe: 'explorer anime liveaction' },
  { id: 'annafrozen', icon: '❄️', ar: 'آنا (فروزن)', en: 'Anna (Frozen)', yes: 'female cartoon disney princess duo human', no: 'classic powers' },
  { id: 'nephews',    icon: '🐥', ar: 'سوسو ولولو وتوتو', en: 'Huey, Dewey and Louie', yes: 'cartoon disney child hat group series_c classic bird animal', maybe: 'kidshow', no: 'human' },
  { id: 'scrooge',    icon: '💰', ar: 'عم دهب', en: 'Scrooge McDuck', yes: 'cartoon disney hat glasses old series_c classic bird animal', maybe: 'kidshow beard', no: 'human' },

  /* ---------- Looney Tunes and other cartoons ---------- */
  { id: 'daffy',      icon: '🦆', ar: 'دافي داك', en: 'Daffy Duck', yes: 'comedy cartoon classic bird black animal', maybe: 'kidshow series_c flies', no: 'human disney' },
  { id: 'sylvester',  icon: '🐈‍⬛', ar: 'سيلفستر (قط تويتي)', en: 'Sylvester', yes: 'cartoon duo cat classic mammal tail white black animal', maybe: 'comedy villain kidshow series_c', no: 'human disney' },
  { id: 'roadrunner', icon: '🐦', ar: 'رود رنر', en: 'Road Runner', yes: 'cartoon duo classic bird blue animal', maybe: 'kidshow series_c', no: 'human disney flies' },
  { id: 'coyote',     icon: '🐺', ar: 'ويلي كايوتي (رود رنر)', en: 'Wile E. Coyote', yes: 'cartoon duo classic mammal tail brown animal', maybe: 'comedy villain kidshow weapon series_c', no: 'human disney dog' },
  { id: 'speedy',     icon: '🐭', ar: 'سبيدي جونزاليس', en: 'Speedy Gonzales', yes: 'cartoon hat mouse classic mammal tail animal', maybe: 'comedy kidshow series_c bigears white', no: 'human disney' },
  { id: 'porky',      icon: '🐷', ar: 'بوركي بيج', en: 'Porky Pig', yes: 'cartoon classic mammal pink animal', maybe: 'comedy kidshow series_c', no: 'human disney' },
  { id: 'taz',        icon: '🌪️', ar: 'تاز', en: 'Taz (the Tasmanian Devil)', yes: 'cartoon classic mammal brown animal', maybe: 'comedy villain kidshow series_c', no: 'human disney' },
  { id: 'woodywoodpecker', icon: '🐦', ar: 'نقار الخشب وودي', en: 'Woody Woodpecker', yes: 'comedy cartoon classic bird flies red blue animal', maybe: 'kidshow series_c', no: 'human disney' },
  { id: 'snoopy',     icon: '🐶', ar: 'سنوبي', en: 'Snoopy', yes: 'cartoon dog classic mammal white black animal', maybe: 'kidshow duo series_c legs4 flies', no: 'human disney' },
  { id: 'odie',       icon: '🐕', ar: 'أودي (كلب جارفيلد)', en: "Odie (Garfield's dog)", yes: 'cartoon duo dog classic mammal legs4 bigears yellow animal', maybe: 'kidshow tail', no: 'human disney' },
  { id: 'spikedog',   icon: '🐕', ar: 'سبايك (كلب توم وجيري)', en: 'Spike (Tom and Jerry)', yes: 'cartoon kidshow dog series_c classic mammal gray animal', maybe: 'legs4 big', no: 'human disney' },
  { id: 'casper',     icon: '👻', ar: 'كاسبر', en: 'Casper', yes: 'cartoon powers child classic flies white', maybe: 'liveaction kidshow series_c human' },
  { id: 'tintin',     icon: '📰', ar: 'تان تان', en: 'Tintin', yes: 'explorer cartoon detective duo classic human', maybe: 'kidshow series_c' },
  { id: 'asterix',    icon: '🪖', ar: 'أستريكس', en: 'Asterix', yes: 'warrior cartoon powers hat duo beard weapon classic human', maybe: 'comedy fighter liveaction kidshow' },
  { id: 'obelix',     icon: '🪨', ar: 'أوبليكس', en: 'Obelix', yes: 'warrior cartoon powers duo beard classic stripes human', maybe: 'comedy fighter liveaction kidshow big' },
  { id: 'luckyluke',  icon: '🤠', ar: 'لاكي لوك', en: 'Lucky Luke', yes: 'cartoon hat weapon classic human', maybe: 'kidshow duo series_c yellow' },
  { id: 'homersimpson', icon: '🍩', ar: 'هومر سيمبسون', en: 'Homer Simpson', yes: 'comedy cartoon series_c classic yellow human', maybe: 'beard' },
  { id: 'bartsimpson', icon: '🛹', ar: 'بارت سيمبسون', en: 'Bart Simpson', yes: 'comedy cartoon child series_c classic yellow human' },
  { id: 'fredflintstone', icon: '🦴', ar: 'فريد فلينستون', en: 'Fred Flintstone', yes: 'comedy cartoon series_c classic human', maybe: 'kidshow duo orange' },
  { id: 'squidward',  icon: '🦑', ar: 'شفيق (سبونج بوب)', en: 'Squidward (SpongeBob)', yes: 'cartoon kidshow series_c classic water animal', maybe: 'comedy green blue', no: 'human' },
  { id: 'krabs',      icon: '🦀', ar: 'السيد سلطع (سبونج بوب)', en: 'Mr. Krabs (SpongeBob)', yes: 'cartoon kidshow series_c classic water shell red animal', no: 'human' },
  { id: 'planktonsb', icon: '🦠', ar: 'بلانكتون (سبونج بوب)', en: 'Plankton (SpongeBob)', yes: 'cartoon villain kidshow series_c classic water green', maybe: 'animal', no: 'human' },
  { id: 'oggy',       icon: '🐈', ar: 'أوجي (أوجي والصراصير)', en: 'Oggy (Oggy and the Cockroaches)', yes: 'comedy cartoon kidshow cat series_c classic mammal tail blue animal', maybe: 'duo', no: 'human disney' },
  { id: 'oggyroaches', icon: '🪳', ar: 'الصراصير (أوجي والصراصير)', en: 'The Cockroaches (Oggy)', yes: 'comedy cartoon villain kidshow group series_c classic insect animal', maybe: 'black', no: 'human' },
  { id: 'shaunsheep', icon: '🐑', ar: 'شون الخروف', en: 'Shaun the Sheep', yes: 'cartoon kidshow series_c mammal white animal', maybe: 'classic legs4 black', no: 'human' },
  { id: 'thomastrain', icon: '🚂', ar: 'توماس (القطر)', en: 'Thomas the Tank Engine', yes: 'kidshow robot series_c classic big blue vehicle wheels object', maybe: 'cartoon', no: 'human animal' },
  { id: 'pingu',      icon: '🐧', ar: 'بينجو', en: 'Pingu', yes: 'cartoon kidshow child series_c classic bird white black animal', no: 'human flies' },
  { id: 'bobbuilder', icon: '👷', ar: 'بوب البنّا', en: 'Bob the Builder', yes: 'human cartoon kidshow hat series_c classic', maybe: 'yellow' },
  { id: 'ben10',      icon: '⌚', ar: 'بن تن', en: 'Ben 10', yes: 'cartoon hero powers kidshow child series_c green human', maybe: 'fighter alien stripes flies', no: 'classic' },
  { id: 'barbie',     icon: '💗', ar: 'باربي', en: 'Barbie', yes: 'female classic pink toy', maybe: 'cartoon liveaction princess human object' },
  { id: 'powerpuff',  icon: '💥', ar: 'فتيات القوة', en: 'The Powerpuff Girls', yes: 'female cartoon hero powers kidshow child group series_c classic flies', maybe: 'pink human' },
  { id: 'hellokitty', icon: '🎀', ar: 'هيلو كيتي', en: 'Hello Kitty', yes: 'female cartoon cat classic mammal white animal', maybe: 'anime kidshow series_c pink toy', no: 'human' },
  { id: 'miraculousladybug', icon: '🐞', ar: 'ليدي باج (ميراكولوس)', en: 'Ladybug (Miraculous)', yes: 'female cartoon hero powers kidshow mask series_c spots red human', maybe: 'black', no: 'classic' },

  /* ---------- superheroes ---------- */
  { id: 'wonderwoman', icon: '🦸‍♀️', ar: 'وندر وومان', en: 'Wonder Woman', yes: 'female warrior liveaction hero powers weapon classic human', maybe: 'cartoon shell flies red blue' },
  { id: 'captainamerica', icon: '🛡️', ar: 'كابتن أمريكا', en: 'Captain America', yes: 'warrior liveaction hero classic shell red blue human', maybe: 'cartoon disney powers mask weapon white' },
  { id: 'thor',       icon: '🔨', ar: 'ثور', en: 'Thor', yes: 'warrior liveaction hero powers beard weapon cape classic flies', maybe: 'ruler disney tale alien red human' },
  { id: 'blackpanther', icon: '🐾', ar: 'بلاك بانثر', en: 'Black Panther', yes: 'ruler liveaction hero mask black human', maybe: 'warrior disney powers beard classic' },
  { id: 'theflash',   icon: '⚡', ar: 'فلاش', en: 'The Flash', yes: 'liveaction hero powers mask red human', maybe: 'cartoon classic yellow' },
  { id: 'aquaman',    icon: '🔱', ar: 'أكوامان', en: 'Aquaman', yes: 'liveaction hero powers beard weapon water human', maybe: 'ruler warrior classic' },
  { id: 'wolverine',  icon: '🐺', ar: 'وولفرين', en: 'Wolverine', yes: 'liveaction hero powers beard human', maybe: 'fighter cartoon mask weapon classic yellow' },
  { id: 'drstrange',  icon: '🌀', ar: 'دكتور سترينج', en: 'Doctor Strange', yes: 'liveaction hero powers beard cape flies human', maybe: 'disney classic red' },
  { id: 'thanos',     icon: '🧤', ar: 'ثانوس', en: 'Thanos', yes: 'liveaction powers villain alien big', maybe: 'disney classic', no: 'human' },
  { id: 'optimus',    icon: '🚛', ar: 'أوبتيموس برايم (المتحولون)', en: 'Optimus Prime (Transformers)', yes: 'warrior robot classic alien big red blue vehicle wheels object', maybe: 'cartoon liveaction hero weapon', no: 'human' },
  { id: 'bumblebeecar', icon: '🚗', ar: 'بامبلبي (المتحولون)', en: 'Bumblebee (Transformers)', yes: 'robot classic alien big yellow vehicle wheels object', maybe: 'warrior cartoon liveaction hero stripes black', no: 'human animal' },

  /* ---------- video games ---------- */
  { id: 'luigi',      icon: '🍄', ar: 'لويجي', en: 'Luigi', yes: 'videogame hat duo beard classic green human', maybe: 'cartoon blue' },
  { id: 'princesspeach', icon: '👑', ar: 'الأميرة بيتش', en: 'Princess Peach', yes: 'female princess videogame classic pink human', maybe: 'ruler cartoon' },
  { id: 'bowser',     icon: '🐲', ar: 'باوزر', en: 'Bowser', yes: 'ruler villain videogame classic shell big', maybe: 'cartoon reptile tail green animal', no: 'human' },
  { id: 'yoshi',      icon: '🦖', ar: 'يوشي', en: 'Yoshi', yes: 'videogame classic green animal', maybe: 'cartoon reptile tail', no: 'human' },
  { id: 'zeldalink',  icon: '🗡️', ar: 'لينك (زيلدا)', en: 'Link (Zelda)', yes: 'warrior videogame hat weapon classic green human', maybe: 'shell' },
  { id: 'donkeykong', icon: '🦍', ar: 'دونكي كونج', en: 'Donkey Kong', yes: 'videogame classic mammal big brown animal', maybe: 'cartoon', no: 'human' },
  { id: 'laracroft',  icon: '🏺', ar: 'لارا كروفت', en: 'Lara Croft', yes: 'female explorer liveaction videogame weapon classic human' },
  { id: 'minecraftsteve', icon: '⛏️', ar: 'ستيف (ماينكرافت)', en: 'Steve (Minecraft)', yes: 'videogame blue human', maybe: 'weapon', no: 'classic' },
  { id: 'creeper',    icon: '💣', ar: 'كريبر (ماينكرافت)', en: 'Creeper (Minecraft)', yes: 'villain videogame green', maybe: 'object', no: 'human animal classic' },
  { id: 'angrybird',  icon: '🐦', ar: 'العصفور الغضبان (أنجري بيردز)', en: 'Red (Angry Birds)', yes: 'videogame bird red animal', maybe: 'cartoon flies', no: 'human classic' },
  { id: 'crashbandicoot', icon: '🦊', ar: 'كراش بانديكوت', en: 'Crash Bandicoot', yes: 'videogame classic mammal orange animal', no: 'human' },
  { id: 'ryu',        icon: '🥋', ar: 'ريو (ستريت فايتر)', en: 'Ryu (Street Fighter)', yes: 'fighter videogame classic white human', maybe: 'warrior athlete' },
  { id: 'talkingtom', icon: '😺', ar: 'توم المتكلّم', en: 'Talking Tom', yes: 'videogame cat mammal tail gray animal', maybe: 'comedy cartoon kidshow series_c', no: 'human classic' },

  /* ---------- fairy tales and storybooks ---------- */
  { id: 'redhood',    icon: '🧺', ar: 'ليلى والذئب (ليلى)', en: 'Little Red Riding Hood', yes: 'female tale child cape classic red human', maybe: 'cartoon liveaction hat' },
  { id: 'bigbadwolf', icon: '🐺', ar: 'الذئب (ليلى والذئب)', en: 'The Big Bad Wolf', yes: 'villain tale classic mammal gray animal', maybe: 'cartoon legs4 tail', no: 'human dog' },
  { id: 'threepigs',  icon: '🐖', ar: 'التلات خنازير الصغيرين', en: 'The Three Little Pigs', yes: 'tale group classic mammal pink animal', maybe: 'cartoon disney', no: 'human' },
  { id: 'puss',       icon: '🐈', ar: 'القط ذو الحذاء', en: 'Puss in Boots', yes: 'cartoon tale hat weapon cat classic mammal tail orange animal', no: 'human disney' },
  { id: 'uglyduckling', icon: '🦢', ar: 'البطة القبيحة', en: 'The Ugly Duckling', yes: 'tale child classic bird animal', maybe: 'cartoon water flies white gray', no: 'human' },
  { id: 'gulliver',   icon: '🏝️', ar: 'جاليفر', en: 'Gulliver', yes: 'explorer tale classic human', maybe: 'cartoon liveaction big' },
  { id: 'robinhood',  icon: '🏹', ar: 'روبن هود', en: 'Robin Hood', yes: 'tale hat weapon classic green human', maybe: 'warrior cartoon disney anime liveaction hero beard' },
  { id: 'donquixote', icon: '🛡️', ar: 'دون كيشوت', en: 'Don Quixote', yes: 'warrior tale duo beard weapon old classic human', maybe: 'comedy liveaction hat shell' },

  /* ---------- films ---------- */
  { id: 'jamesbond',  icon: '🔫', ar: 'جيمس بوند', en: 'James Bond', yes: 'liveaction weapon classic human', maybe: 'detective', no: 'powers cartoon villain' },
  { id: 'indianajones', icon: '🤠', ar: 'إنديانا جونز', en: 'Indiana Jones', yes: 'explorer liveaction hat weapon classic human', maybe: 'beard' },
  { id: 'darthvader', icon: '⚫', ar: 'دارث فيدر', en: 'Darth Vader', yes: 'liveaction powers villain mask weapon cape classic black human', maybe: 'warrior disney robot alien shell' },
  { id: 'yoda',       icon: '🟢', ar: 'يودا', en: 'Yoda', yes: 'powers weapon old classic bigears green', maybe: 'warrior disney liveaction alien', no: 'human' },
  { id: 'gandalf',    icon: '🧙‍♂️', ar: 'جاندالف', en: 'Gandalf', yes: 'liveaction powers hat beard old gray human', maybe: 'warrior weapon cape classic white' },
  { id: 'kingkong',   icon: '🦍', ar: 'كينج كونج', en: 'King Kong', yes: 'classic mammal big black animal', maybe: 'liveaction legs4 brown', no: 'human' },
  { id: 'godzilla',   icon: '🦖', ar: 'جودزيلا', en: 'Godzilla', yes: 'classic reptile tail big', maybe: 'liveaction powers villain green gray animal', no: 'human' },
  { id: 'etalien',    icon: '👽', ar: 'إي تي', en: 'E.T.', yes: 'classic alien brown', maybe: 'liveaction powers child flies', no: 'human' },
  { id: 'zorro',      icon: '🎭', ar: 'زورو', en: 'Zorro', yes: 'liveaction mask hat beard weapon cape classic black human', maybe: 'warrior hero' },
  { id: 'rockybalboa', icon: '🥊', ar: 'روكي', en: 'Rocky Balboa', yes: 'athlete fighter liveaction classic human' },
  { id: 'paddington', icon: '🐻', ar: 'بادينجتون', en: 'Paddington Bear', yes: 'hat classic mammal brown animal', maybe: 'liveaction', no: 'human' },
  { id: 'gru',        icon: '🦹', ar: 'جرو (أنا الشرير)', en: 'Gru (Despicable Me)', yes: 'cartoon human', maybe: 'comedy villain duo weapon black gray', no: 'classic disney' },
  { id: 'kevinhomealone', icon: '🏠', ar: 'كيفين (وحدي في البيت)', en: 'Kevin (Home Alone)', yes: 'comedy liveaction child classic human' },
  { id: 'alexlion',   icon: '🦁', ar: 'أليكس الأسد (مدغشقر)', en: 'Alex the Lion (Madagascar)', yes: 'comedy cartoon cat mammal legs4 tail big animal', maybe: 'ruler yellow orange', no: 'human disney classic' },
  { id: 'sidiceage',  icon: '🦥', ar: 'سيد (العصر الجليدي)', en: 'Sid (Ice Age)', yes: 'comedy cartoon mammal animal', maybe: 'duo green brown gray', no: 'human disney classic' },
  { id: 'mannymammoth', icon: '🦣', ar: 'ماني الماموث (العصر الجليدي)', en: 'Manny the Mammoth (Ice Age)', yes: 'cartoon mammal legs4 big brown animal', maybe: 'duo', no: 'human disney classic bigears flies' },
  { id: 'toothless',  icon: '🐉', ar: 'توثلس (روّض تنينك)', en: 'Toothless (How to Train Your Dragon)', yes: 'cartoon duo legs4 tail flies big black', maybe: 'reptile animal', no: 'human classic disney' },
  { id: 'shrekdonkey', icon: '🫏', ar: 'الحمار (صاحب شريك)', en: "Donkey (Shrek's friend)", yes: 'comedy cartoon duo mammal legs4 bigears gray animal', maybe: 'tail', no: 'human disney classic' },
  { id: 'fiona',      icon: '👸', ar: 'الأميرة فيونا (شريك)', en: 'Princess Fiona (Shrek)', yes: 'female cartoon princess green', maybe: 'duo human', no: 'disney classic' },
  { id: 'hermione',   icon: '📖', ar: 'هيرميوني (هاري بوتر)', en: 'Hermione (Harry Potter)', yes: 'female liveaction powers human', maybe: 'child duo classic flies' },
  { id: 'voldemort',  icon: '🐍', ar: 'فولدمورت (هاري بوتر)', en: 'Voldemort (Harry Potter)', yes: 'liveaction powers villain human', maybe: 'classic flies white black' },
  { id: 'dumbledore', icon: '🧙', ar: 'دمبلدور (هاري بوتر)', en: 'Dumbledore (Harry Potter)', yes: 'liveaction powers hat glasses beard old human', maybe: 'classic white' },
]};
