/* العرّاف: animals (kind 'a'). One line each: id, icon, ar, en, and the question ids
   (OracleQuestions.js) that are true of it (yes), partly or "most would say probably" (maybe),
   and firmly not, where a player might think otherwise (no). A question about animals that
   is in none of the three reads as «غالباً لأ». notes/games/oracle.md, "Writing entries";
   check with `cd tools && npm run check:oracle`. */
const ORACLE_ANIMALS = { kind: 'a', list: [
  { id: 'lion',      icon: '🦁', ar: 'أسد', en: 'Lion', yes: 'mammal wild meat africa_a legs4 fur tail danger fast', maybe: 'big yellow brown asia_a' },
  { id: 'tiger',     icon: '🐯', ar: 'نمر', en: 'Tiger', yes: 'mammal wild meat legs4 fur tail stripes danger fast orange asia_a', maybe: 'big black', no: 'africa_a' },
  { id: 'cheetah',   icon: '🐆', ar: 'فهد', en: 'Cheetah', yes: 'mammal wild meat africa_a legs4 fur tail spots fast yellow', maybe: 'danger' },
  { id: 'wolf',      icon: '🐺', ar: 'ديب', en: 'Wolf', yes: 'mammal wild meat legs4 fur tail night gray danger', maybe: 'snow asia_a america_a' },
  { id: 'fox',       icon: '🦊', ar: 'تعلب', en: 'Fox', yes: 'mammal wild meat legs4 fur tail orange night', maybe: 'inegypt desert asia_a america_a' },
  { id: 'bear',      icon: '🐻', ar: 'دبّ', en: 'Bear', yes: 'mammal wild meat plants legs4 fur big danger brown climb', maybe: 'snow asia_a america_a' },
  { id: 'polarbear', icon: '🐻‍❄️', ar: 'دبّ قطبي', en: 'Polar bear', yes: 'mammal wild meat legs4 fur big danger white snow', maybe: 'water sea_a america_a' },
  { id: 'elephant',  icon: '🐘', ar: 'فيل', en: 'Elephant', yes: 'mammal wild plants africa_a legs4 big bigears gray asia_a tusks_a', maybe: 'ride danger' },
  { id: 'giraffe',   icon: '🦒', ar: 'زرافة', en: 'Giraffe', yes: 'mammal wild plants africa_a legs4 longneck spots big yellow', maybe: 'brown' },
  { id: 'rhino',     icon: '🦏', ar: 'وحيد القرن', en: 'Rhino', yes: 'mammal wild plants africa_a legs4 horns big gray danger', maybe: 'asia_a' },
  { id: 'hippo',     icon: '🦛', ar: 'فرس النهر', en: 'Hippo', yes: 'mammal wild plants africa_a legs4 big gray water danger', maybe: 'tusks_a' },
  { id: 'zebra',     icon: '🦓', ar: 'حمار وحشي', en: 'Zebra', yes: 'mammal wild plants africa_a legs4 stripes fast white black tail' },
  { id: 'camel',     icon: '🐪', ar: 'جمل', en: 'Camel', yes: 'mammal plants desert legs4 ride inegypt longneck brown gives', maybe: 'africa_a farm big yellow edible asia_a' },
  { id: 'horse',     icon: '🐴', ar: 'حصان', en: 'Horse', yes: 'mammal plants legs4 ride fast tail farm inegypt', maybe: 'brown big white black' },
  { id: 'donkey',    icon: '🫏', ar: 'حمار', en: 'Donkey', yes: 'mammal plants legs4 ride farm inegypt gray bigears', maybe: 'brown slow', no: 'fast' },
  { id: 'cow',       icon: '🐄', ar: 'بقرة', en: 'Cow', yes: 'mammal plants legs4 farm horns gives edible inegypt', maybe: 'white brown big spots' },
  { id: 'buffalo',   icon: '🐃', ar: 'جاموسة', en: 'Water buffalo', yes: 'mammal plants legs4 farm horns gives edible inegypt black', maybe: 'big water asia_a', no: 'white spots' },
  { id: 'sheep',     icon: '🐑', ar: 'خروف', en: 'Sheep', yes: 'mammal plants legs4 farm fur gives edible inegypt white', maybe: 'horns' },
  { id: 'goat',      icon: '🐐', ar: 'معزة', en: 'Goat', yes: 'mammal plants legs4 farm horns gives edible inegypt jump', maybe: 'black brown white climb' },
  { id: 'dog',       icon: '🐕', ar: 'كلب', en: 'Dog', yes: 'mammal pet legs4 fur tail inegypt meat', maybe: 'brown black white fast danger' },
  { id: 'cat',       icon: '🐈', ar: 'قطة', en: 'Cat', yes: 'mammal pet legs4 fur tail inegypt meat climb jump', maybe: 'night' },
  { id: 'rabbit',    icon: '🐇', ar: 'أرنب', en: 'Rabbit', yes: 'mammal pet plants legs4 fur bigears jump inegypt edible farm', maybe: 'white fast' },
  { id: 'mouse',     icon: '🐭', ar: 'فار', en: 'Mouse', yes: 'mammal small legs4 tail fur inegypt gray night', maybe: 'pet' },
  { id: 'squirrel',  icon: '🐿️', ar: 'سنجاب', en: 'Squirrel', yes: 'mammal wild plants legs4 climb fur tail brown jump', maybe: 'small orange america_a' },
  { id: 'monkey',    icon: '🐒', ar: 'قرد', en: 'Monkey', yes: 'mammal wild plants climb tail jump brown', maybe: 'africa_a fur asia_a america_a insects_a' },
  { id: 'gorilla',   icon: '🦍', ar: 'غوريلا', en: 'Gorilla', yes: 'mammal wild plants africa_a fur black big climb', maybe: 'danger', no: 'tail' },
  { id: 'panda',     icon: '🐼', ar: 'باندا', en: 'Panda', yes: 'mammal wild plants legs4 fur white black climb asia_a', maybe: 'big slow' },
  { id: 'kangaroo',  icon: '🦘', ar: 'كنغر', en: 'Kangaroo', yes: 'mammal wild plants jump tail fast brown australia_a', maybe: 'big', no: 'legs4' },
  { id: 'koala',     icon: '🐨', ar: 'كوالا', en: 'Koala', yes: 'mammal wild plants climb fur gray slow bigears australia_a' },
  { id: 'bat',       icon: '🦇', ar: 'خفاش', en: 'Bat', yes: 'mammal flies night black wild', maybe: 'small inegypt insects_a' },
  { id: 'hedgehog',  icon: '🦔', ar: 'قنفد', en: 'Hedgehog', yes: 'mammal wild small night brown legs4 insects_a', maybe: 'inegypt shell' },
  { id: 'dolphin',   icon: '🐬', ar: 'دولفين', en: 'Dolphin', yes: 'mammal water gray fast wild meat nolegs sea_a', maybe: 'big blue', no: 'fish' },
  { id: 'whale',     icon: '🐋', ar: 'حوت', en: 'Whale', yes: 'mammal water big blue wild nolegs sea_a', maybe: 'gray', no: 'fish' },
  { id: 'shark',     icon: '🦈', ar: 'سمكة قرش', en: 'Shark', yes: 'fish water meat danger big gray fast wild nolegs sea_a', maybe: 'blue eggs_a' },
  { id: 'octopus',   icon: '🐙', ar: 'أخطبوط', en: 'Octopus', yes: 'water wild meat sea_a eggs_a', maybe: 'red pink orange sting' },
  { id: 'goldfish',  icon: '🐠', ar: 'سمكة زينة', en: 'Goldfish', yes: 'fish water pet small orange nolegs eggs_a', maybe: 'yellow', no: 'sea_a' },
  { id: 'fish',      icon: '🐟', ar: 'سمكة بلطي', en: 'Tilapia', yes: 'fish water edible nolegs inegypt gray eggs_a', no: 'sea_a' },
  { id: 'turtle',    icon: '🐢', ar: 'سلحفاة', en: 'Turtle', yes: 'reptile shell slow legs4 pet plants green eggs_a', maybe: 'water brown sea_a' },
  { id: 'crocodile', icon: '🐊', ar: 'تمساح', en: 'Crocodile', yes: 'reptile water meat danger green tail legs4 wild big africa_a eggs_a', maybe: 'inegypt asia_a america_a' },
  { id: 'snake',     icon: '🐍', ar: 'تعبان', en: 'Snake', yes: 'reptile nolegs sting danger meat wild', maybe: 'desert inegypt green black tail eggs_a' },
  { id: 'lizard',    icon: '🦎', ar: 'سحلية', en: 'Lizard', yes: 'reptile legs4 tail inegypt eggs_a insects_a', maybe: 'small green desert brown' },
  { id: 'chameleon', icon: '🦎', ar: 'حرباية', en: 'Chameleon', yes: 'reptile green tail legs4 slow climb eggs_a insects_a', maybe: 'small' },
  { id: 'frog',      icon: '🐸', ar: 'ضفدعة', en: 'Frog', yes: 'water jump green inegypt eggs_a insects_a', maybe: 'small meat', no: 'reptile fish' },
  { id: 'eagle',     icon: '🦅', ar: 'نسر', en: 'Eagle', yes: 'bird flies meat wild brown eggs_a', maybe: 'big danger fast' },
  { id: 'owl',       icon: '🦉', ar: 'بومة', en: 'Owl', yes: 'bird flies night meat wild brown eggs_a', maybe: 'white' },
  { id: 'crow',      icon: '🐦‍⬛', ar: 'غراب', en: 'Crow', yes: 'bird flies black inegypt eggs_a', maybe: 'gray meat insects_a colony' },
  { id: 'parrot',    icon: '🦜', ar: 'ببغان', en: 'Parrot', yes: 'bird flies pet green eggs_a', maybe: 'red yellow blue america_a' },
  { id: 'pigeon',    icon: '🕊️', ar: 'حمامة', en: 'Pigeon', yes: 'bird flies inegypt edible gray eggs_a', maybe: 'white farm pet' },
  { id: 'sparrow',   icon: '🐦', ar: 'عصفورة', en: 'Sparrow', yes: 'bird flies small inegypt brown eggs_a', maybe: 'pet insects_a' },
  { id: 'duck',      icon: '🦆', ar: 'بطّة', en: 'Duck', yes: 'bird water farm edible inegypt eggs_a', maybe: 'flies white gives', no: 'longneck' },
  { id: 'chicken',   icon: '🐔', ar: 'فرخة', en: 'Chicken', yes: 'bird farm edible gives inegypt eggs_a', maybe: 'white brown', no: 'flies' },
  { id: 'rooster',   icon: '🐓', ar: 'ديك', en: 'Rooster', yes: 'bird farm inegypt', maybe: 'red edible', no: 'flies gives eggs_a' },
  { id: 'turkey',    icon: '🦃', ar: 'ديك رومي', en: 'Turkey', yes: 'bird farm edible brown eggs_a', maybe: 'inegypt big america_a', no: 'flies' },
  { id: 'peacock',   icon: '🦚', ar: 'طاووس', en: 'Peacock', yes: 'bird blue green tail asia_a', maybe: 'flies eggs_a' },
  { id: 'ostrich',   icon: '🐦', ar: 'نعامة', en: 'Ostrich', yes: 'bird africa_a fast longneck big wild eggs_a', maybe: 'desert black', no: 'flies legs4' },
  { id: 'penguin',   icon: '🐧', ar: 'بطريق', en: 'Penguin', yes: 'bird snow water black white wild colony eggs_a sea_a', no: 'flies' },
  { id: 'flamingo',  icon: '🦩', ar: 'بشروش (فلامنجو)', en: 'Flamingo', yes: 'bird pink water longneck flies colony eggs_a', maybe: 'wild' },
  { id: 'bee',       icon: '🐝', ar: 'نحلة', en: 'Bee', yes: 'insect flies sting small gives yellow black stripes inegypt colony', maybe: 'eggs_a' },
  { id: 'ant',       icon: '🐜', ar: 'نملة', en: 'Ant', yes: 'insect small black inegypt colony', maybe: 'sting red eggs_a insects_a' },
  { id: 'butterfly', icon: '🦋', ar: 'فراشة', en: 'Butterfly', yes: 'insect flies small eggs_a', maybe: 'inegypt' },
  { id: 'fly',       icon: '🪰', ar: 'دبّانة', en: 'Fly', yes: 'insect flies small black inegypt eggs_a' },
  { id: 'mosquito',  icon: '🦟', ar: 'ناموسة', en: 'Mosquito', yes: 'insect flies small sting night inegypt eggs_a' },
  { id: 'spider',    icon: '🕷️', ar: 'عنكبوت', en: 'Spider', yes: 'insect small black eggs_a insects_a', maybe: 'sting inegypt' },
  { id: 'scorpion',  icon: '🦂', ar: 'عقربة', en: 'Scorpion', yes: 'sting danger desert insects_a', maybe: 'insect tail black yellow small inegypt', no: 'eggs_a' },
  { id: 'cockroach', icon: '🪳', ar: 'صرصار', en: 'Cockroach', yes: 'insect small brown inegypt night fast eggs_a', maybe: 'flies' },
  { id: 'snail',     icon: '🐌', ar: 'حلزونة', en: 'Snail', yes: 'shell slow small eggs_a', maybe: 'water' },
  { id: 'shrimp',    icon: '🦐', ar: 'جمبري', en: 'Shrimp', yes: 'water edible small eggs_a sea_a', maybe: 'pink orange' },
  { id: 'crab',      icon: '🦀', ar: 'كابوريا', en: 'Crab', yes: 'water shell edible eggs_a sea_a', maybe: 'red sting small' },
  { id: 'jellyfish', icon: '🪼', ar: 'قنديل البحر', en: 'Jellyfish', yes: 'water sting nolegs sea_a', maybe: 'white pink blue' },
  { id: 'starfish',  icon: '⭐', ar: 'نجمة البحر', en: 'Starfish', yes: 'water slow sea_a', maybe: 'small orange pink eggs_a' },
  { id: 'dinosaur',  icon: '🦖', ar: 'ديناصور', en: 'Dinosaur', yes: 'extinct big danger tail wild eggs_a', maybe: 'reptile green meat' },
  { id: 'seal',      icon: '🦭', ar: 'فقمة', en: 'Seal', yes: 'mammal water snow gray meat wild sea_a', maybe: 'black' },

  /* ---------- 9 Oct 2026, the second writer: mammals ---------- */
  { id: 'hyena',       icon: '🐾', ar: 'ضبع', en: 'Hyena', yes: 'mammal wild meat africa_a legs4 fur spots night danger', maybe: 'brown yellow gray colony' },
  { id: 'leopard',     icon: '🐆', ar: 'نمر مرقّط', en: 'Leopard', yes: 'mammal wild meat africa_a legs4 fur tail spots climb danger fast yellow', maybe: 'asia_a night' },
  { id: 'jaguar',      icon: '🐆', ar: 'جاجوار', en: 'Jaguar', yes: 'mammal wild meat america_a legs4 fur tail spots danger yellow', maybe: 'water climb night', no: 'africa_a' },
  { id: 'panther',     icon: '🐈‍⬛', ar: 'بانثر (النمر الأسود)', en: 'Black leopard (panther)', yes: 'mammal wild meat legs4 fur tail black climb danger', maybe: 'night fast asia_a africa_a america_a' },
  { id: 'deer',        icon: '🦌', ar: 'أيّل', en: 'Deer', yes: 'mammal wild plants legs4 fur horns brown fast jump', maybe: 'spots snow asia_a america_a' },
  { id: 'gazelle',     icon: '🦌', ar: 'غزالة', en: 'Gazelle', yes: 'mammal wild plants legs4 horns fast jump africa_a desert', maybe: 'brown yellow white inegypt asia_a' },
  { id: 'reindeer',    icon: '🦌', ar: 'رنّة', en: 'Reindeer', yes: 'mammal plants legs4 fur horns snow brown', maybe: 'ride gives farm wild white' },
  { id: 'moose',       icon: '🫎', ar: 'موظ', en: 'Moose', yes: 'mammal wild plants legs4 fur horns big brown america_a', maybe: 'snow water' },
  { id: 'chimpanzee',  icon: '🐒', ar: 'شمبانزي', en: 'Chimpanzee', yes: 'mammal wild plants africa_a fur black climb', maybe: 'meat insects_a danger', no: 'tail' },
  { id: 'orangutan',   icon: '🦧', ar: 'إنسان الغاب', en: 'Orangutan', yes: 'mammal wild plants asia_a fur orange climb', maybe: 'big brown', no: 'tail' },
  { id: 'baboon',      icon: '🐒', ar: 'بابون', en: 'Baboon', yes: 'mammal wild africa_a fur legs4 plants colony', maybe: 'meat brown gray danger tail' },
  { id: 'lemur',       icon: '🐒', ar: 'ليمور', en: 'Lemur', yes: 'mammal wild plants climb tail jump africa_a fur gray', maybe: 'stripes black white night' },
  { id: 'sloth',       icon: '🦥', ar: 'حيوان الكسلان', en: 'Sloth', yes: 'mammal wild plants climb slow fur america_a', maybe: 'brown gray' },
  { id: 'anteater',    icon: '🐾', ar: 'آكل النمل', en: 'Anteater', yes: 'mammal wild legs4 fur tail insects_a america_a', maybe: 'brown gray big slow' },
  { id: 'armadillo',   icon: '🐾', ar: 'أرماديلو', en: 'Armadillo', yes: 'mammal wild shell legs4 america_a insects_a', maybe: 'gray brown night' },
  { id: 'raccoon',     icon: '🦝', ar: 'راكون', en: 'Raccoon', yes: 'mammal wild legs4 fur tail night gray climb america_a', maybe: 'meat plants stripes black' },
  { id: 'skunk',       icon: '🦨', ar: 'ظربان', en: 'Skunk', yes: 'mammal wild legs4 fur tail black white stripes night america_a', maybe: 'insects_a' },
  { id: 'beaver',      icon: '🦫', ar: 'قندس', en: 'Beaver', yes: 'mammal wild plants water legs4 fur brown', maybe: 'america_a tail' },
  { id: 'otter',       icon: '🦦', ar: 'قضاعة (تعلب المية)', en: 'Otter', yes: 'mammal wild meat water legs4 fur tail brown', maybe: 'sea_a' },
  { id: 'meerkat',     icon: '🐾', ar: 'سرقاط (ميركات)', en: 'Meerkat', yes: 'mammal wild africa_a desert legs4 fur tail colony insects_a', maybe: 'brown yellow meat' },
  { id: 'mongoose',    icon: '🐾', ar: 'نمس', en: 'Mongoose', yes: 'mammal wild meat africa_a legs4 fur tail insects_a', maybe: 'inegypt brown gray fast asia_a' },
  { id: 'weasel',      icon: '🐾', ar: 'عرسة', en: 'Weasel', yes: 'mammal wild meat legs4 fur tail fast inegypt brown', maybe: 'night africa_a' },
  { id: 'jerboa',      icon: '🐭', ar: 'جربوع', en: 'Jerboa', yes: 'mammal wild desert jump tail night bigears', maybe: 'small plants africa_a inegypt yellow insects_a' },
  { id: 'porcupine',   icon: '🦔', ar: 'شيهم (النيص)', en: 'Porcupine', yes: 'mammal wild plants legs4 night', maybe: 'brown black africa_a' },
  { id: 'hamster',     icon: '🐹', ar: 'هامستر', en: 'Hamster', yes: 'mammal pet plants legs4 fur night', maybe: 'small brown orange white' },
  { id: 'rat',         icon: '🐀', ar: 'جرذ (فار كبير)', en: 'Rat', yes: 'mammal legs4 tail fur inegypt gray night', maybe: 'black brown danger', no: 'small' },
  { id: 'boar',        icon: '🐗', ar: 'خنزير بري', en: 'Wild boar', yes: 'mammal wild legs4 fur tusks_a brown danger', maybe: 'black plants meat asia_a night' },
  { id: 'bison',       icon: '🦬', ar: 'بيسون (الجاموس الأمريكي)', en: 'Bison', yes: 'mammal wild plants legs4 fur horns big brown america_a colony', maybe: 'snow danger' },
  { id: 'llama',       icon: '🦙', ar: 'لاما', en: 'Llama', yes: 'mammal plants legs4 fur longneck america_a gives', maybe: 'farm white brown ride' },
  { id: 'mule',        icon: '🫏', ar: 'بغل', en: 'Mule', yes: 'mammal plants legs4 farm ride inegypt brown tail', maybe: 'big bigears gray' },
  { id: 'bull',        icon: '🐂', ar: 'تور', en: 'Bull', yes: 'mammal plants legs4 farm horns edible inegypt', maybe: 'danger black brown big', no: 'gives' },
  { id: 'oryx',        icon: '🦌', ar: 'مها', en: 'Oryx', yes: 'mammal wild plants legs4 horns desert white asia_a', maybe: 'africa_a fast' },
  { id: 'ibex',        icon: '🐐', ar: 'وعل', en: 'Ibex', yes: 'mammal wild plants legs4 horns jump brown', maybe: 'desert inegypt fur snow asia_a', no: 'farm' },
  { id: 'fennec',      icon: '🦊', ar: 'فنك (تعلب الصحرا)', en: 'Fennec fox', yes: 'mammal wild meat desert africa_a legs4 fur tail bigears night', maybe: 'yellow inegypt insects_a' },
  { id: 'arcticfox',   icon: '🦊', ar: 'تعلب قطبي', en: 'Arctic fox', yes: 'mammal wild meat legs4 fur tail snow white', maybe: 'gray' },
  { id: 'jackal',      icon: '🐺', ar: 'ابن آوى', en: 'Jackal', yes: 'mammal wild meat africa_a legs4 fur tail night', maybe: 'inegypt yellow brown desert asia_a' },
  { id: 'platypus',    icon: '🐾', ar: 'خلد الماء (بلاتيبوس)', en: 'Platypus', yes: 'mammal water eggs_a australia_a fur brown wild', maybe: 'sting tail' },
  { id: 'walrus',      icon: '🦭', ar: 'فظ', en: 'Walrus', yes: 'mammal water sea_a snow big brown tusks_a wild', maybe: 'fur meat', no: 'fish' },
  { id: 'sealion',     icon: '🦭', ar: 'أسد البحر', en: 'Sea lion', yes: 'mammal water sea_a wild meat brown', maybe: 'colony jump black', no: 'fish' },
  { id: 'orca',        icon: '🐋', ar: 'حوت قاتل (أوركا)', en: 'Killer whale (orca)', yes: 'mammal water sea_a big black white meat danger fast wild nolegs', no: 'fish' },

  /* ---------- birds ---------- */
  { id: 'falcon',      icon: '🦅', ar: 'صقر', en: 'Falcon', yes: 'bird flies meat wild fast eggs_a', maybe: 'gray desert pet inegypt danger', no: 'big' },
  { id: 'blackkite',   icon: '🦅', ar: 'حدّاية', en: 'Black kite', yes: 'bird flies meat brown inegypt wild eggs_a', maybe: 'black' },
  { id: 'hoopoe',      icon: '🐦', ar: 'هدهد', en: 'Hoopoe', yes: 'bird flies inegypt stripes insects_a eggs_a', maybe: 'orange brown small' },
  { id: 'swan',        icon: '🦢', ar: 'بجعة', en: 'Swan', yes: 'bird water white longneck flies eggs_a', maybe: 'wild big' },
  { id: 'pelican',     icon: '🐦', ar: 'بليكان (أبو جراب)', en: 'Pelican', yes: 'bird water flies white meat colony eggs_a longneck', maybe: 'big wild sea_a' },
  { id: 'goose',       icon: '🪿', ar: 'وزّة', en: 'Goose', yes: 'bird water farm edible inegypt white eggs_a gives longneck', maybe: 'flies' },
  { id: 'canary',      icon: '🐤', ar: 'كناري', en: 'Canary', yes: 'bird flies pet small yellow eggs_a' },
  { id: 'lovebird',    icon: '🦜', ar: 'عصفور الحب', en: 'Lovebird', yes: 'bird flies pet small green eggs_a', maybe: 'red yellow orange' },
  { id: 'quail',       icon: '🐦', ar: 'سمّان', en: 'Quail', yes: 'bird flies edible brown inegypt eggs_a', maybe: 'small spots gives wild farm' },
  { id: 'seagull',     icon: '🐦', ar: 'نورس', en: 'Seagull', yes: 'bird flies water sea_a white wild eggs_a', maybe: 'gray colony meat' },
  { id: 'egret',       icon: '🐦', ar: 'أبو قردان', en: 'Cattle egret', yes: 'bird flies white inegypt longneck insects_a eggs_a', maybe: 'farm water colony' },
  { id: 'stork',       icon: '🐦', ar: 'لقلق', en: 'Stork', yes: 'bird flies white black longneck eggs_a', maybe: 'big water wild meat' },
  { id: 'hummingbird', icon: '🐦', ar: 'طائر الطنّان', en: 'Hummingbird', yes: 'bird flies small fast america_a eggs_a', maybe: 'green blue' },
  { id: 'woodpecker',  icon: '🐦', ar: 'نقّار الخشب', en: 'Woodpecker', yes: 'bird flies wild climb insects_a eggs_a', maybe: 'red black white' },
  { id: 'toucan',      icon: '🐦', ar: 'طوقان', en: 'Toucan', yes: 'bird flies wild black america_a eggs_a', maybe: 'orange yellow plants' },
  { id: 'swallow',     icon: '🐦', ar: 'سنونو', en: 'Swallow', yes: 'bird flies fast insects_a eggs_a', maybe: 'small black white inegypt' },
  { id: 'chick',       icon: '🐥', ar: 'كتكوت', en: 'Chick', yes: 'bird farm small yellow inegypt', maybe: 'pet edible', no: 'flies eggs_a' },
  { id: 'dodo',        icon: '🦤', ar: 'طائر الدودو', en: 'Dodo', yes: 'bird extinct gray eggs_a', maybe: 'big', no: 'flies' },

  /* ---------- the sea and the river ---------- */
  { id: 'squid',       icon: '🦑', ar: 'سبيط (كاليماري)', en: 'Squid', yes: 'water sea_a edible wild', maybe: 'white pink eggs_a meat' },
  { id: 'seahorse',    icon: '🐠', ar: 'حصان البحر', en: 'Seahorse', yes: 'water sea_a small tail eggs_a slow', maybe: 'fish yellow orange', no: 'legs4 mammal' },
  { id: 'clownfish',   icon: '🐠', ar: 'سمكة المهرّج', en: 'Clownfish', yes: 'fish water sea_a small orange white stripes eggs_a nolegs', maybe: 'pet' },
  { id: 'swordfish',   icon: '🐟', ar: 'سمكة أبو سيف', en: 'Swordfish', yes: 'fish water sea_a big fast nolegs eggs_a wild', maybe: 'gray blue edible meat' },
  { id: 'sardine',     icon: '🐟', ar: 'سردين', en: 'Sardine', yes: 'fish water sea_a edible colony nolegs eggs_a', maybe: 'small inegypt gray' },
  { id: 'tuna',        icon: '🐟', ar: 'تونة', en: 'Tuna', yes: 'fish water sea_a edible fast nolegs eggs_a colony', maybe: 'big blue gray wild' },
  { id: 'mullet',      icon: '🐟', ar: 'بوري', en: 'Mullet', yes: 'fish water sea_a edible inegypt gray nolegs eggs_a' },
  { id: 'catfish',     icon: '🐟', ar: 'قرموط', en: 'Catfish', yes: 'fish water edible inegypt nolegs black eggs_a', maybe: 'gray brown', no: 'sea_a' },
  { id: 'piranha',     icon: '🐟', ar: 'بيرانا', en: 'Piranha', yes: 'fish water meat danger america_a nolegs eggs_a colony', maybe: 'small red gray' },
  { id: 'flyingfish',  icon: '🐟', ar: 'السمكة الطايرة', en: 'Flying fish', yes: 'fish water sea_a nolegs eggs_a fast', maybe: 'flies blue small' },
  { id: 'eel',         icon: '🐟', ar: 'تعبان البحر (حنكليس)', en: 'Eel', yes: 'fish water nolegs tail eggs_a', maybe: 'sea_a edible black gray' },
  { id: 'stingray',    icon: '🐟', ar: 'سمكة الراي', en: 'Stingray', yes: 'fish water sea_a sting tail nolegs', maybe: 'gray brown danger' },
  { id: 'pufferfish',  icon: '🐡', ar: 'سمكة أبو نفخة', en: 'Pufferfish', yes: 'fish water sea_a sting nolegs eggs_a', maybe: 'small yellow spots danger' },
  { id: 'urchin',      icon: '🦔', ar: 'قنفد البحر', en: 'Sea urchin', yes: 'water sea_a slow sting eggs_a', maybe: 'black small edible' },
  { id: 'lobster',     icon: '🦞', ar: 'استاكوزا', en: 'Lobster', yes: 'water sea_a shell edible tail eggs_a', maybe: 'red sting' },
  { id: 'oyster',      icon: '🦪', ar: 'محار', en: 'Oyster', yes: 'water sea_a shell edible gives slow eggs_a colony', maybe: 'gray small white', no: 'legs4' },
  { id: 'clam',        icon: '🐚', ar: 'جندوفلي', en: 'Clam', yes: 'water sea_a shell edible small slow', maybe: 'inegypt eggs_a white' },
  { id: 'seaturtle',   icon: '🐢', ar: 'سلحفاة بحرية', en: 'Sea turtle', yes: 'reptile water sea_a shell eggs_a wild', maybe: 'green big brown plants' },

  /* ---------- reptiles and amphibians ---------- */
  { id: 'cobra',       icon: '🐍', ar: 'كوبرا', en: 'Cobra', yes: 'reptile nolegs sting danger meat wild africa_a asia_a eggs_a', maybe: 'inegypt desert brown black yellow' },
  { id: 'viper',       icon: '🐍', ar: 'الحية أم قرون', en: 'Horned viper', yes: 'reptile nolegs sting danger desert horns africa_a eggs_a', maybe: 'inegypt yellow brown night' },
  { id: 'python',      icon: '🐍', ar: 'أصلة (بايثون)', en: 'Python', yes: 'reptile nolegs big meat danger wild eggs_a', maybe: 'climb water spots brown asia_a africa_a' },
  { id: 'anaconda',    icon: '🐍', ar: 'أناكوندا', en: 'Anaconda', yes: 'reptile nolegs big meat danger wild water america_a', maybe: 'green spots', no: 'eggs_a' },
  { id: 'gecko',       icon: '🦎', ar: 'برص', en: 'Gecko', yes: 'reptile legs4 tail small inegypt climb night insects_a eggs_a', maybe: 'gray white' },
  { id: 'iguana',      icon: '🦎', ar: 'إجوانا', en: 'Iguana', yes: 'reptile legs4 tail green plants america_a eggs_a', maybe: 'climb pet' },
  { id: 'komodo',      icon: '🦎', ar: 'تنين كومودو', en: 'Komodo dragon', yes: 'reptile legs4 tail big meat danger asia_a wild eggs_a', maybe: 'gray brown sting' },
  { id: 'monitor',     icon: '🦎', ar: 'ورل', en: 'Monitor lizard', yes: 'reptile legs4 tail meat wild africa_a eggs_a', maybe: 'inegypt water desert big brown asia_a' },
  { id: 'dabb',        icon: '🦎', ar: 'ضب', en: 'Spiny-tailed lizard (dabb)', yes: 'reptile legs4 tail desert plants eggs_a', maybe: 'asia_a africa_a inegypt yellow brown' },
  { id: 'salamander',  icon: '🦎', ar: 'سمندل', en: 'Salamander', yes: 'legs4 tail water eggs_a', maybe: 'black yellow spots small', no: 'reptile fish' },
  { id: 'tadpole',     icon: '🐸', ar: 'أبو دنيبة', en: 'Tadpole', yes: 'water small tail black inegypt plants', maybe: 'nolegs', no: 'fish reptile eggs_a' },

  /* ---------- insects, spiders and small creatures ---------- */
  { id: 'beetle',      icon: '🪲', ar: 'خنفسة', en: 'Beetle', yes: 'insect small black inegypt eggs_a shell', maybe: 'flies brown' },
  { id: 'ladybird',    icon: '🐞', ar: 'دعسوقة', en: 'Ladybird', yes: 'insect flies small red spots eggs_a insects_a', maybe: 'black shell' },
  { id: 'locust',      icon: '🦗', ar: 'جرادة', en: 'Locust', yes: 'insect flies jump plants colony eggs_a', maybe: 'green brown yellow inegypt small' },
  { id: 'cricket',     icon: '🦗', ar: 'صرصار الليل', en: 'Cricket', yes: 'insect jump night small eggs_a', maybe: 'brown black inegypt flies plants' },
  { id: 'mantis',      icon: '🦗', ar: 'فرس النبي', en: 'Praying mantis', yes: 'insect green insects_a meat eggs_a', maybe: 'small flies brown' },
  { id: 'dragonfly',   icon: '🪰', ar: 'يعسوب', en: 'Dragonfly', yes: 'insect flies fast insects_a eggs_a', maybe: 'water small green blue' },
  { id: 'wasp',        icon: '🐝', ar: 'دبّور', en: 'Wasp', yes: 'insect flies sting small yellow black stripes inegypt eggs_a', maybe: 'danger colony meat', no: 'gives' },
  { id: 'termite',     icon: '🐜', ar: 'نمل أبيض (أرضة)', en: 'Termite', yes: 'insect small white colony eggs_a', maybe: 'plants inegypt' },
  { id: 'moth',        icon: '🦋', ar: 'فراشة الليل (عتّة)', en: 'Moth', yes: 'insect flies night small eggs_a', maybe: 'brown gray white inegypt' },
  { id: 'silkworm',    icon: '🐛', ar: 'دودة القز', en: 'Silkworm', yes: 'insect gives small white plants eggs_a', maybe: 'farm slow' },
  { id: 'flea',        icon: '🪲', ar: 'برغوت', en: 'Flea', yes: 'insect small jump sting black eggs_a', maybe: 'brown inegypt' },
  { id: 'bedbug',      icon: '🪲', ar: 'بقّة', en: 'Bedbug', yes: 'insect small sting night brown eggs_a', maybe: 'inegypt red' },
  { id: 'tarantula',   icon: '🕷️', ar: 'رتيلاء', en: 'Tarantula', yes: 'insect fur sting danger eggs_a', maybe: 'black brown america_a meat insects_a' },
  { id: 'centipede',   icon: '🐛', ar: 'أم أربعة وأربعين', en: 'Centipede', yes: 'sting inegypt eggs_a fast', maybe: 'insect brown small meat night insects_a', no: 'legs4 nolegs' },
  { id: 'worm',        icon: '🪱', ar: 'دودة', en: 'Earthworm', yes: 'nolegs inegypt slow', maybe: 'small pink brown eggs_a', no: 'insect reptile' },
  { id: 'leech',       icon: '🪱', ar: 'علقة', en: 'Leech', yes: 'water nolegs small sting', maybe: 'black brown inegypt eggs_a', no: 'insect fish' },

  /* ---------- dinosaurs and animals gone ---------- */
  { id: 'triceratops', icon: '🦕', ar: 'ترايسيراتوبس', en: 'Triceratops', yes: 'extinct big horns plants legs4 tail eggs_a', maybe: 'reptile green gray brown' },
  { id: 'brachiosaurus', icon: '🦕', ar: 'براكيوصور', en: 'Brachiosaurus', yes: 'extinct big longneck plants legs4 tail eggs_a', maybe: 'reptile green gray', no: 'danger meat' },
  { id: 'stegosaurus', icon: '🦕', ar: 'ستيجوصور', en: 'Stegosaurus', yes: 'extinct big plants legs4 tail eggs_a', maybe: 'reptile green shell', no: 'longneck meat' },
  { id: 'pterodactyl', icon: '🪽', ar: 'تيروداكتيل (الديناصور الطاير)', en: 'Pterodactyl', yes: 'extinct flies meat eggs_a', maybe: 'reptile big brown tail', no: 'bird' },
  { id: 'mammoth',     icon: '🦣', ar: 'ماموث', en: 'Mammoth', yes: 'extinct mammal plants legs4 fur big snow tusks_a brown', maybe: 'bigears' },
  { id: 'sabertooth',  icon: '🐯', ar: 'نمر أبو أسنان سيف', en: 'Saber-toothed cat', yes: 'extinct mammal meat legs4 fur danger tusks_a', maybe: 'snow big brown yellow' },
  { id: 'megalodon',   icon: '🦈', ar: 'ميجالودون (القرش العملاق)', en: 'Megalodon', yes: 'extinct fish water sea_a big meat danger nolegs', maybe: 'gray' },
]};
