/* العرّاف (The Oracle): the questions it can ask. Page only (its chunk, tools/lazy-split.mjs);
   the engine is Oracle.js, the entries OraclePeople.js, OracleCharacters.js, OracleAnimals.js,
   OracleThings.js. How to write an entry: notes/games/oracle.md, "Writing entries".

   Each question:
     id     a short name the entries use in their yes / no / maybe lists (never change one).
     kinds  the kinds it is asked about, one letter each: p a famous person, c a character
            (cartoon, film, tale, game), a an animal, t a thing (food, object, place, nature),
            j a job, l a place (a country or a city). For an entry of any other kind the answer is a firm «لأ».
     auto   (optional) the answer every entry of a kind has without saying it: 'p:y c:n l:m' (m: maybe) -
            an entry's own lists still win.
     implies (optional) the ids an entry with this trait has too ('ahly' implies 'football').
     firm   (optional) true: what the thing IS (its kind, a woman, Egyptian, an actor...). Its data
            must be complete - an entry of its kinds not marked yes or maybe is a no - and an
            answer to it is nearly final: the oracle never guesses an entry it rules out.
   The wording is about things that don't change: never «لسه عايش؟» or «لسه بيلعب؟». */
const ORACLE_QUESTIONS = [
  /* ---------- what kind of thing it is (asked like any other question, never picked first) ---------- */
  { id: 'human',   firm: true, kinds: 'pcatjl', auto: 'p:y a:n t:n j:y l:n', ar: 'هو إنسان؟', en: 'Is it a human?' },
  { id: 'real',    firm: true, kinds: 'pcatjl', auto: 'p:y c:n a:n t:n j:n l:n', ar: 'شخص حقيقي مشهور؟', en: 'A real, famous person?' },
  { id: 'fiction', firm: true, kinds: 'pcatjl', auto: 'p:n c:y a:n t:n j:n l:n', ar: 'شخصية من كارتون أو فيلم أو حكاية؟', en: 'A character from a cartoon, film or tale?' },
  { id: 'animal',  firm: true, kinds: 'pcatjl', auto: 'p:n a:y t:n j:n l:n', ar: 'حيوان (أو طير أو سمكة أو حشرة)؟', en: 'An animal (or a bird, a fish, an insect)?' },
  { id: 'job',     firm: true, kinds: 'pcatjl', auto: 'p:n c:n a:n t:n j:y l:n', ar: 'شغلانة (مهنة)؟', en: 'A job?' },
  { id: 'object',  firm: true, kinds: 'pcatjl', auto: 'p:n a:n t:y j:n l:m', ar: 'حاجة، مش إنسان ولا حيوان؟', en: 'A thing, not a person or an animal?' },
  { id: 'countrycity', firm: true, kinds: 'pcatjl', auto: 'p:n c:n a:n t:n j:n l:y', ar: 'بلد أو مدينة؟', en: 'A country or a city?' },

  /* ---------- places: countries and cities (10 Oct 2026, OraclePlaces.js) ---------- */

  /* ---------- people (and some characters) ---------- */
  { id: 'female',  firm: true, kinds: 'pc', ar: 'ست أو بنت؟', en: 'A woman or a girl?' },
  { id: 'egypt',   firm: true, kinds: 'pct', implies: ['arab'], ar: 'مصري؟', en: 'Egyptian?' },
  { id: 'arab',    kinds: 'pct', ar: 'عربي؟', en: 'Arab?' },
  { id: 'levant',  kinds: 'p', implies: ['arab'], ar: 'من لبنان أو سوريا أو فلسطين أو الأردن؟', en: 'From Lebanon, Syria, Palestine or Jordan?' },
  { id: 'gulf',    kinds: 'p', implies: ['arab'], ar: 'من الخليج أو العراق؟', en: 'From the Gulf or Iraq?' },
  { id: 'maghreb', kinds: 'p', implies: ['arab'], ar: 'من المغرب أو الجزائر أو تونس؟', en: 'From Morocco, Algeria or Tunisia?' },
  { id: 'south',   kinds: 'p', implies: ['egypt'], ar: 'من الصعيد أو النوبة؟', en: 'From Upper Egypt or Nubia?' },
  { id: 'europe',  kinds: 'p', ar: 'أوروبي؟', en: 'European?' },
  { id: 'usa',     kinds: 'p', ar: 'من أمريكا (الولايات المتحدة)؟', en: 'From the United States?' },
  { id: 'latam',   kinds: 'p', ar: 'من أمريكا الجنوبية؟', en: 'From South America?' },
  { id: 'africa',  kinds: 'p', ar: 'من بلد أفريقي مش عربي؟', en: 'From an African country that is not Arab?' },
  { id: 'asia',    kinds: 'p', ar: 'من شرق آسيا (زي الصين واليابان)؟', en: 'From East Asia (China, Japan…)?' },
  { id: 'before1800', kinds: 'p', implies: ['born1930'], ar: 'عاش قبل سنة 1800؟', en: 'Lived before the year 1800?' },
  { id: 'bc',      kinds: 'p', implies: ['before1500'], ar: 'عاش من أكتر من ألفين سنة؟', en: 'Lived more than two thousand years ago?' },
  { id: 'pharaoh', kinds: 'p', implies: ['bc1000'], ar: 'من أيام الفراعنة؟', en: 'From the time of the pharaohs?' },
  { id: 'born1930', kinds: 'p', implies: ['born1950'], ar: 'اتولد قبل سنة 1930؟', en: 'Born before 1930?' },
  { id: 'born1950', kinds: 'p', implies: ['born1970'], ar: 'اتولد قبل سنة 1950؟', en: 'Born before 1950?' },
  { id: 'ruler',   kinds: 'pc', ar: 'ملك أو ملكة أو حاكم؟', en: 'A king, a queen or a ruler?' },
  { id: 'warrior', kinds: 'pc', ar: 'قائد حروب أو فارس؟', en: 'A war leader or a warrior?' },
  { id: 'actor',   firm: true, kinds: 'p', ar: 'ممثل؟', en: 'An actor?' },
  { id: 'comedy',  kinds: 'pc', ar: 'اشتهر بالكوميديا؟', en: 'Known for comedy?' },
  { id: 'bw',      kinds: 'p', ar: 'مثّل في أفلام أبيض وإسود؟', en: 'Acted in black-and-white films?' },
  { id: 'theater', kinds: 'p', ar: 'اشتهر بالمسرح؟', en: 'Known for the stage (theatre)?' },
  { id: 'action',  kinds: 'p', ar: 'اشتهر بأفلام الأكشن؟', en: 'Known for action films?' },
  { id: 'hollywood', kinds: 'p', ar: 'مثّل في أفلام هوليوود؟', en: 'Acted in Hollywood films?' },
  { id: 'series',  kinds: 'p', ar: 'اشتهر بمسلسلات التلفزيون؟', en: 'Known for TV series?' },
  { id: 'fawazeer', kinds: 'pc', ar: 'اشتهر بفوازير رمضان؟', en: 'Known for the Ramadan riddle shows (fawazeer)?' },
  { id: 'tvhost',  kinds: 'p', ar: 'قدّم برامج تلفزيون؟', en: 'Presented TV shows?' },
  { id: 'singer',  firm: true, kinds: 'p', ar: 'مطرب أو مغنّي؟', en: 'A singer?' },
  { id: 'composer', kinds: 'p', ar: 'ملحّن أو موسيقار؟', en: 'A composer or a musician?' },
  { id: 'athlete', firm: true, kinds: 'pc', ar: 'رياضي؟', en: 'An athlete?' },
  { id: 'football', firm: true, kinds: 'pc', implies: ['athlete'], ar: 'لاعب كورة؟', en: 'A footballer?' },
  { id: 'ahly',    kinds: 'p', implies: ['football'], ar: 'لعب في الأهلي؟', en: 'Played for Al Ahly?' },
  { id: 'zamalek', kinds: 'p', implies: ['football'], ar: 'لعب في الزمالك؟', en: 'Played for Zamalek?' },
  { id: 'england', kinds: 'p', implies: ['football'], ar: 'لعب في الدوري الإنجليزي؟', en: 'Played in the English league?' },
  { id: 'spain',   kinds: 'p', implies: ['football'], ar: 'لعب في الدوري الإسباني؟', en: 'Played in the Spanish league?' },
  { id: 'keeper',  kinds: 'p', implies: ['football'], ar: 'حارس مرمى؟', en: 'A goalkeeper?' },
  { id: 'striker', kinds: 'p', implies: ['football'], ar: 'مهاجم؟', en: 'A striker?' },
  { id: 'worldcup', kinds: 'p', implies: ['football'], ar: 'كسب كاس العالم؟', en: 'Won the World Cup?' },
  { id: 'afcon',   kinds: 'p', implies: ['football'], ar: 'كسب كاس أمم أفريقيا؟', en: 'Won the Africa Cup of Nations?' },
  { id: 'ballon',  kinds: 'p', implies: ['football'], ar: 'خد الكورة الدهبية؟', en: "Won the Ballon d'Or?" },
  { id: 'coach',   kinds: 'p', ar: 'اشتغل مدرّب كورة؟', en: 'Worked as a football coach?' },
  { id: 'othersport', kinds: 'p', implies: ['athlete'], ar: 'بيلعب رياضة غير الكورة؟', en: 'Plays a sport other than football?' },
  { id: 'fighter', kinds: 'pc', ar: 'ملاكم أو بيلعب رياضة قتال؟', en: 'A boxer or a fighter?' },
  { id: 'olympic', kinds: 'p', ar: 'خد ميدالية أولمبية؟', en: 'Won an Olympic medal?' },
  { id: 'writer',  kinds: 'p', ar: 'كاتب أو شاعر؟', en: 'A writer or a poet?' },
  { id: 'poet',    kinds: 'p', implies: ['writer'], ar: 'شاعر؟', en: 'A poet?' },
  { id: 'science', kinds: 'p', ar: 'عالِم أو مخترع؟', en: 'A scientist or an inventor?' },
  { id: 'medic',   kinds: 'p', ar: 'دكتور (طبيب)؟', en: 'A doctor (of medicine)?' },
  { id: 'nobel',   kinds: 'p', ar: 'خد جايزة نوبل؟', en: 'Won a Nobel Prize?' },
  { id: 'painter', kinds: 'p', ar: 'رسّام؟', en: 'A painter?' },
  { id: 'explorer', kinds: 'pc', ar: 'رحّالة أو مستكشف أو راح الفضاء؟', en: 'A traveller, an explorer or an astronaut?' },
  { id: 'blind',   kinds: 'p', ar: 'كان كفيف؟', en: 'Was blind?' },
  /* people, added with the second batch of entries (9 Oct 2026): the generation, the films' trades,
     what a ruler built, two countries, the football positions and leagues, and the other sports */
  { id: 'born1970', kinds: 'p', implies: ['born1975'], ar: 'اتولد قبل سنة 1970؟', en: 'Born before 1970?' },
  { id: 'director', kinds: 'p', ar: 'اشتغل مخرج (أفلام أو مسلسلات أو مسرح)؟', en: 'Worked as a director (film, TV or stage)?' },
  { id: 'villainroles', kinds: 'p', ar: 'اشتهر بأدوار الشرير؟', en: 'Known for playing villains?' },
  { id: 'oscar',   kinds: 'p', ar: 'خد جايزة الأوسكار؟', en: 'Won an Oscar?' },
  { id: 'built',   kinds: 'p', ar: 'بنى (أو صمّم) هرم أو معبد أو مبنى مشهور؟', en: 'Built (or designed) a famous pyramid, temple or building?' },
  { id: 'uk',      kinds: 'p', implies: ['europe'], ar: 'من بريطانيا (إنجلترا)؟', en: 'From Britain (England)?' },
  { id: 'france',  kinds: 'p', implies: ['europe'], ar: 'من فرنسا؟', en: 'From France?' },
  { id: 'italy',   kinds: 'p', implies: ['football'], ar: 'لعب في الدوري الإيطالي؟', en: 'Played in the Italian league?' },
  { id: 'defender', kinds: 'p', implies: ['football'], ar: 'مدافع (في الكورة)؟', en: 'A defender (in football)?' },
  { id: 'tennis',  kinds: 'p', implies: ['othersport'], ar: 'بيلعب تنس؟', en: 'A tennis player?' },
  { id: 'squash',  kinds: 'p', implies: ['othersport'], ar: 'بيلعب إسكواش؟', en: 'A squash player?' },
  { id: 'runner',  kinds: 'p', implies: ['othersport'], ar: 'عدّاء أو بطل ألعاب قوى؟', en: 'A runner, or in track and field?' },
  { id: 'swimmer', kinds: 'p', implies: ['othersport'], ar: 'سبّاح؟', en: 'A swimmer?' },
  { id: 'lifter',  kinds: 'p', implies: ['othersport'], ar: 'بطل رفع أثقال؟', en: 'A weightlifter?' },
  { id: 'basket',  kinds: 'p', implies: ['othersport'], ar: 'بيلعب كورة سلة؟', en: 'A basketball player?' },
  /* people, added 9 Oct 2026 to tell apart pairs the full review left alike: the generation in finer steps
     (each implies the next: bc1000 → bc → before1500 → before1800, born1970 → born1975 → born1980),
     the midfield, dancing, mathematics. Every person of the kind was gone over for each. */
  { id: 'bc1000',  kinds: 'p', implies: ['bc'], ar: 'عاش من أكتر من تلات آلاف سنة؟', en: 'Lived more than three thousand years ago?' },
  { id: 'before1500', kinds: 'p', implies: ['before1800'], ar: 'عاش قبل سنة 1500؟', en: 'Lived before the year 1500?' },
  { id: 'born1975', kinds: 'p', implies: ['born1980'], ar: 'اتولد قبل سنة 1975؟', en: 'Born before 1975?' },
  { id: 'born1980', kinds: 'p', implies: ['born1990'], ar: 'اتولد قبل سنة 1980؟', en: 'Born before 1980?' },
  { id: 'midfield', kinds: 'p', implies: ['football'], ar: 'لاعب وسط (في الكورة)؟', en: 'A midfielder (in football)?' },
  { id: 'dance',   kinds: 'p', ar: 'اشتهر بالرقص أو الاستعراض؟', en: 'Known for dancing or musical shows?' },
  { id: 'math',    kinds: 'p', ar: 'اشتهر بالرياضيات (الحساب والجبر والهندسة)؟', en: 'Known for mathematics?' },

  /* ---------- content creators: YouTubers, TikTokers, gamers (10 Oct 2026, OracleCreators.js) ---------- */

  /* ---------- the newer stars (10 Oct 2026) ---------- */
  /* the birth chain goes on (born1980 → born1990 → born2000), every person marked; the German league, the racing
     drivers, a famous father or mother: every person of the kind was gone over for each */
  { id: 'born1990', kinds: 'p', implies: ['born2000'], ar: 'اتولد قبل سنة 1990؟', en: 'Born before 1990?' },
  { id: 'born2000', kinds: 'p', ar: 'اتولد قبل سنة 2000؟', en: 'Born before 2000?' },
  { id: 'germany', kinds: 'p', implies: ['football'], ar: 'لعب في الدوري الألماني؟', en: 'Played in the German league?' },
  { id: 'racer',   kinds: 'p', implies: ['othersport'], ar: 'سوّاق سباق عربيات؟', en: 'A racing driver?' },
  { id: 'famousparent', kinds: 'p', ar: 'أبوه أو أمه مشهورين كمان؟', en: 'Is his or her father or mother famous too?' },

  /* ---------- characters ---------- */
  { id: 'cartoon', firm: true, kinds: 'c', ar: 'كارتون (رسوم متحركة)؟', en: 'A cartoon (animated)?' },
  { id: 'disney',  kinds: 'c', ar: 'من أفلام ديزني؟', en: 'From a Disney film?' },
  { id: 'anime',   kinds: 'c', ar: 'من كارتون ياباني (أنمي)؟', en: 'From a Japanese cartoon (anime)?' },
  { id: 'liveaction', kinds: 'c', ar: 'بيمثّله ممثل حقيقي؟', en: 'Played by a real actor?' },
  { id: 'hero',    kinds: 'c', ar: 'سوبر هيرو؟', en: 'A superhero?' },
  { id: 'powers',  kinds: 'c', ar: 'عنده قوى خارقة أو بيعمل سحر؟', en: 'Has superpowers or does magic?' },
  { id: 'villain', kinds: 'c', ar: 'شرير؟', en: 'A villain?' },
  { id: 'princess', kinds: 'c', implies: ['female'], ar: 'أميرة؟', en: 'A princess?' },
  { id: 'tale',    kinds: 'c', ar: 'من حكاية قديمة أو ألف ليلة وليلة؟', en: 'From an old tale or the Arabian Nights?' },
  { id: 'kidshow', kinds: 'c', ar: 'من برنامج أو مسلسل للأطفال؟', en: 'From a show for children?' },
  { id: 'videogame', kinds: 'c', ar: 'من لعبة فيديو؟', en: 'From a video game?' },
  { id: 'child',   kinds: 'c', ar: 'طفل أو صغير في السن؟', en: 'A child?' },
  { id: 'mask',    kinds: 'c', ar: 'لابس قناع؟', en: 'Wears a mask?' },
  { id: 'hat',     kinds: 'c', ar: 'لابس طاقية أو قبعة؟', en: 'Wears a cap or a hat?' },
  { id: 'robot',   kinds: 'c', ar: 'روبوت أو آلة أو عربية؟', en: 'A robot, a machine or a car?' },
  { id: 'detective', kinds: 'c', ar: 'محقق بيحل ألغاز؟', en: 'A detective who solves mysteries?' },
  { id: 'group',   kinds: 'c', ar: 'جزء من مجموعة شبه بعض (زي السنافر)؟', en: 'One of a group who look alike (like the Smurfs)?' },
  { id: 'duo',     kinds: 'c', ar: 'دايماً معاه صاحبه أو اتنين مع بعض؟', en: 'Always with a partner, or a pair?' },
  /* added with the characters of phase 2 (9 Oct 2026): every character was gone over for each */
  { id: 'glasses', kinds: 'c', ar: 'لابس نضارة؟', en: 'Wears glasses?' },
  { id: 'beard',   kinds: 'c', ar: 'ليه دقن أو شنب؟', en: 'Has a beard or a moustache?' },
  { id: 'weapon',  kinds: 'c', ar: 'بيشيل سيف أو سلاح؟', en: 'Carries a sword or a weapon?' },
  { id: 'cape',    kinds: 'c', ar: 'لابس كاب (عباية طويلة على ضهره)؟', en: 'Wears a cape?' },
  { id: 'old',     kinds: 'c', ar: 'عجوز أو كبير في السن؟', en: 'Old?' },
  { id: 'cat',     kinds: 'c', implies: ['mammal'], ar: 'قطة أو من عيلة القطط (أسد، نمر)؟', en: 'A cat, or of the cat family (a lion, a tiger)?' },
  { id: 'dog',     kinds: 'c', implies: ['mammal'], ar: 'كلب؟', en: 'A dog?' },
  { id: 'mouse',   kinds: 'c', implies: ['mammal'], ar: 'فار؟', en: 'A mouse or a rat?' },
  { id: 'series_c', kinds: 'c', ar: 'من مسلسل (كارتون أو تمثيل)، مش فيلم؟', en: 'From a series (cartoon or acted), not a film?' },
  { id: 'classic', kinds: 'c', ar: 'ظهر أول مرة قبل سنة 2000؟', en: 'First appeared before the year 2000?' },
  { id: 'ramadan_c', kinds: 'c', ar: 'اتعرض في رمضان؟', en: 'Shown in Ramadan?' },
  { id: 'alien',   kinds: 'c', ar: 'جاي من الفضاء أو من كوكب تاني؟', en: 'From space or another planet?' },
  /* added 9 Oct 2026 (pairs the full review left alike); every character was gone over for each */
  { id: 'parent',  kinds: 'c', ar: 'عنده عيال في الحكاية؟', en: 'Has children in the story?' },
  { id: 'stepmother', kinds: 'c', ar: 'عندها مرات أب شريرة؟', en: 'Has a wicked stepmother?' },

  /* ---------- animals (and animal characters) ---------- */
  { id: 'mammal',  kinds: 'ac', ar: 'بيرضّع صغاره (من الثدييات)؟', en: 'Feeds its young milk (a mammal)?' },
  { id: 'bird',    kinds: 'ac', ar: 'طير؟', en: 'A bird?' },
  { id: 'fish',    kinds: 'ac', ar: 'سمكة؟', en: 'A fish?' },
  { id: 'reptile', kinds: 'ac', ar: 'زاحف (تعبان أو سحلية أو تمساح أو سلحفاة)؟', en: 'A reptile (snake, lizard, crocodile, turtle)?' },
  { id: 'insect',  kinds: 'ac', ar: 'حشرة أو عنكبوت؟', en: 'An insect or a spider?' },
  { id: 'colony',  kinds: 'a', ar: 'عايش في جماعة كبيرة؟', en: 'Lives in a big group (a colony, a flock)?' },
  { id: 'water',   kinds: 'ac', ar: 'عايش في المية؟', en: 'Lives in water?' },
  { id: 'pet',     kinds: 'a', ar: 'بيتربّى في البيت؟', en: 'Kept as a pet?' },
  { id: 'farm',    kinds: 'a', ar: 'من حيوانات المزرعة أو الغيط؟', en: 'A farm animal?' },
  { id: 'wild',    kinds: 'a', ar: 'عايش في الغابة أو البرية؟', en: 'Lives in the wild?' },
  { id: 'meat',    kinds: 'a', ar: 'بياكل لحمة (مفترس)؟', en: 'Eats meat (a hunter)?' },
  { id: 'plants',  kinds: 'a', ar: 'بياكل عشب أو نباتات؟', en: 'Eats grass or plants?' },
  { id: 'africa_a', kinds: 'a', ar: 'عايش في أفريقيا؟', en: 'Lives in Africa?' },
  { id: 'desert',  kinds: 'a', ar: 'عايش في الصحرا؟', en: 'Lives in the desert?' },
  { id: 'snow',    kinds: 'a', ar: 'عايش في مكان كله تلج؟', en: 'Lives where there is ice and snow?' },
  { id: 'inegypt', kinds: 'a', ar: 'بتشوفه في مصر عادي؟', en: 'Commonly seen in Egypt?' },
  { id: 'legs4',   kinds: 'ac', ar: 'بيمشي على أربع رجلين؟', en: 'Walks on four legs?' },
  { id: 'nolegs',  kinds: 'a', ar: 'ملوش رجلين خالص؟', en: 'Has no legs at all?' },
  { id: 'stripes', kinds: 'ac', ar: 'جسمه مخطّط؟', en: 'Has stripes?' },
  { id: 'spots',   kinds: 'ac', ar: 'جسمه منقّط (عليه بقع)؟', en: 'Has spots?' },
  { id: 'horns',   kinds: 'a', ar: 'ليه قرون؟', en: 'Has horns?' },
  { id: 'longneck', kinds: 'a', ar: 'رقبته طويلة؟', en: 'Has a long neck?' },
  { id: 'shell',   kinds: 'ac', ar: 'ليه قوقعة أو درع؟', en: 'Has a shell?' },
  { id: 'fur',     kinds: 'a', ar: 'جسمه عليه فرو أو صوف؟', en: 'Has fur or wool?' },
  { id: 'tail',    kinds: 'ac', ar: 'ليه ديل طويل؟', en: 'Has a long tail?' },
  { id: 'bigears', kinds: 'ac', ar: 'ودانه كبيرة؟', en: 'Has big ears?' },
  { id: 'gives',   kinds: 'a', ar: 'بيدّينا حاجة غير لحمه (لبن، بيض، صوف، عسل)؟', en: 'Gives us something besides meat (milk, eggs, wool, honey)?' },
  { id: 'ride',    kinds: 'a', ar: 'الناس بتركبه؟', en: 'Do people ride it?' },
  { id: 'climb',   kinds: 'a', ar: 'بيطلع على الشجر؟', en: 'Climbs trees?' },
  { id: 'jump',    kinds: 'a', ar: 'بينطّ كتير؟', en: 'Jumps a lot?' },
  { id: 'night',   kinds: 'a', ar: 'بيصحى بالليل وينام بالنهار؟', en: 'Awake at night, asleep by day?' },
  { id: 'sting',   kinds: 'a', ar: 'سام أو بيلدغ أو بيقرص؟', en: 'Poisonous, or does it sting or bite?' },
  { id: 'danger',  kinds: 'a', ar: 'خطير على الإنسان؟', en: 'Dangerous to people?' },
  { id: 'extinct', kinds: 'a', ar: 'انقرض؟', en: 'Extinct?' },
  { id: 'fast',    kinds: 'a', ar: 'سريع جداً؟', en: 'Very fast?' },
  { id: 'slow',    kinds: 'a', ar: 'بطيء جداً؟', en: 'Very slow?' },
  { id: 'eggs_a',  kinds: 'a', ar: 'بيبيض؟', en: 'Does it lay eggs?' },
  { id: 'sea_a',   kinds: 'a', ar: 'عايش في البحر؟', en: 'Lives in the sea?' },
  { id: 'insects_a', kinds: 'a', ar: 'بياكل حشرات؟', en: 'Eats insects?' },
  { id: 'tusks_a', kinds: 'a', ar: 'ليه أنياب كبيرة طالعة برّه بُقّه؟', en: 'Has big tusks?' },
  { id: 'asia_a',  kinds: 'a', ar: 'عايش في آسيا (زي الهند والصين)؟', en: 'Lives in Asia (India, China…)?' },
  { id: 'america_a', kinds: 'a', ar: 'عايش في أمريكا (الشمالية أو الجنوبية)؟', en: 'Lives in the Americas?' },
  { id: 'australia_a', kinds: 'a', ar: 'عايش في أستراليا؟', en: 'Lives in Australia?' },
  /* added 9 Oct 2026 (pairs the full review left alike); every animal was gone over for each */
  { id: 'pulls',   kinds: 'a', ar: 'بيشدّ عربية أو ساقية أو زحّافة؟', en: 'Pulls a cart, a water wheel or a sled?' },
  { id: 'fantail', kinds: 'a', ar: 'بيفرد ديله زي المروحة؟', en: 'Spreads its tail like a fan?' },

  /* ---------- shared: flying, size, colour ---------- */
  { id: 'flies',   kinds: 'catj', ar: 'بيطير؟', en: 'Does it fly?' },
  { id: 'big',     kinds: 'cat', ar: 'أكبر من الإنسان؟', en: 'Bigger than a person?' },
  { id: 'small',   kinds: 'at', ar: 'أصغر من كف الإيد؟', en: 'Smaller than your hand?' },
  { id: 'red',     kinds: 'cat', ar: 'لونه أحمر؟', en: 'Is it red?' },
  { id: 'yellow',  kinds: 'cat', ar: 'لونه أصفر؟', en: 'Is it yellow?' },
  { id: 'green',   kinds: 'cat', ar: 'لونه أخضر؟', en: 'Is it green?' },
  { id: 'blue',    kinds: 'cat', ar: 'لونه أزرق؟', en: 'Is it blue?' },
  { id: 'white',   kinds: 'cat', ar: 'لونه أبيض؟', en: 'Is it white?' },
  { id: 'black',   kinds: 'cat', ar: 'لونه أسود؟', en: 'Is it black?' },
  { id: 'brown',   kinds: 'cat', ar: 'لونه بنّي؟', en: 'Is it brown?' },
  { id: 'orange',  kinds: 'cat', ar: 'لونه برتقاني؟', en: 'Is it orange?' },
  { id: 'gray',    kinds: 'cat', ar: 'لونه رمادي؟', en: 'Is it grey?' },
  { id: 'pink',    kinds: 'cat', ar: 'لونه بمبي (وردي)؟', en: 'Is it pink?' },

  /* ---------- things ---------- */
  { id: 'edible',  kinds: 'at', ar: 'بيتاكل؟', en: 'Do we eat it?' },
  { id: 'breakfast', kinds: 't', ar: 'بيتاكل على الفطار؟', en: 'Eaten at breakfast?' },
  { id: 'summer',  kinds: 't', ar: 'بنستناه في الصيف؟', en: 'Something we wait for in summer?' },
  { id: 'drink',   kinds: 't', ar: 'بيتشرب؟', en: 'Do we drink it?' },
  { id: 'fruit',   kinds: 't', implies: ['edible'], ar: 'فاكهة؟', en: 'A fruit?' },
  { id: 'veg',     kinds: 't', implies: ['edible'], ar: 'خضار؟', en: 'A vegetable?' },
  { id: 'sweet',   kinds: 't', ar: 'طعمه مسكّر؟', en: 'Tastes sweet?' },
  { id: 'dish',    kinds: 't', implies: ['edible'], ar: 'أكلة بتتطبخ أو بتتعمل في المطبخ؟', en: 'A dish that is cooked or made?' },
  { id: 'electric', kinds: 't', ar: 'بيشتغل بالكهربا أو بالبطارية؟', en: 'Runs on electricity or a battery?' },
  { id: 'screen',  kinds: 't', implies: ['electric'], ar: 'ليه شاشة؟', en: 'Has a screen?' },
  { id: 'vehicle', kinds: 'tc', ar: 'وسيلة مواصلات؟', en: 'A vehicle?' },
  { id: 'engine',  kinds: 't', ar: 'ليه موتور؟', en: 'Has an engine?' },
  { id: 'passengers', kinds: 't', ar: 'بيركب فيه ناس كتير مع بعض؟', en: 'Carries many people at once?' },
  { id: 'wheels',  kinds: 'tc', ar: 'ليه عجل؟', en: 'Has wheels?' },
  { id: 'kitchen', kinds: 't', ar: 'بتلاقيه في المطبخ؟', en: 'Found in the kitchen?' },
  { id: 'home',    kinds: 't', ar: 'بتلاقيه في أي بيت؟', en: 'Found in every home?' },
  { id: 'bathroom', kinds: 't', ar: 'بتلاقيه في الحمّام؟', en: 'Found in the bathroom?' },
  { id: 'sit',     kinds: 't', ar: 'بنقعد عليه أو بننام عليه؟', en: 'Do we sit or sleep on it?' },
  { id: 'pocket',  kinds: 't', ar: 'يدخل في الجيب؟', en: 'Fits in a pocket?' },
  { id: 'buttons', kinds: 't', ar: 'ليه زراير؟', en: 'Has buttons?' },
  { id: 'school',  kinds: 't', ar: 'بنستعمله في المدرسة؟', en: 'Used at school?' },
  { id: 'wear',    kinds: 't', ar: 'بيتلبس؟', en: 'Do we wear it?' },
  { id: 'furniture', kinds: 't', ar: 'من العفش (أثاث)؟', en: 'A piece of furniture?' },
  { id: 'handtool', kinds: 't', ar: 'أداة بتمسكها في إيدك وتشتغل بيها؟', en: 'A tool you hold in your hand to use?' },
  { id: 'toy',     kinds: 'tc', ar: 'لعبة أطفال أو عروسة؟', en: 'A toy or a puppet?' },
  { id: 'sport',   kinds: 't', ar: 'بيتلعب بيه رياضة؟', en: 'Used to play a sport?' },
  { id: 'music',   kinds: 't', ar: 'آلة موسيقية؟', en: 'A musical instrument?' },
  { id: 'metal',   kinds: 't', ar: 'معمول من حديد أو معدن؟', en: 'Made of metal?' },
  { id: 'wood',    kinds: 't', ar: 'معمول من خشب؟', en: 'Made of wood?' },
  { id: 'paper',   kinds: 't', ar: 'معمول من ورق؟', en: 'Made of paper?' },
  { id: 'glass',   kinds: 't', ar: 'معمول من إزاز؟', en: 'Made of glass?' },
  { id: 'cloth',   kinds: 't', ar: 'معمول من قماش؟', en: 'Made of cloth?' },
  { id: 'nature',  kinds: 't', ar: 'من الطبيعة، محدّش صنعه؟', en: 'From nature, not made by people?' },
  { id: 'sky',     kinds: 't', ar: 'في السما؟', en: 'In the sky?' },
  { id: 'plant',   kinds: 't', ar: 'نبات أو شجرة أو ورد؟', en: 'A plant, a tree or a flower?' },
  { id: 'place',   kinds: 'tl', auto: 'l:y', ar: 'مكان أو مبنى؟', en: 'A place or a building?' },
  { id: 'ramadan', kinds: 't', ar: 'له علاقة برمضان أو العيد؟', en: 'To do with Ramadan or Eid?' },
  { id: 'write',   kinds: 't', ar: 'بنكتب بيه أو عليه؟', en: 'Used to write with, or on?' },
  { id: 'sharp',   kinds: 't', ar: 'بيقطع (حادّ)؟', en: 'Does it cut (sharp)?' },
  { id: 'light',   kinds: 't', ar: 'بينوّر؟', en: 'Does it give light?' },
  { id: 'hot',     kinds: 't', ar: 'سخن أو بيسخّن؟', en: 'Hot, or does it heat?' },
  { id: 'cold',    kinds: 't', ar: 'ساقع أو بيبرّد؟', en: 'Cold, or does it cool?' },
  { id: 'liquid',  kinds: 't', ar: 'سائل؟', en: 'A liquid?' },
  { id: 'round',   kinds: 't', ar: 'شكله مدوّر؟', en: 'Round?' },
  { id: 'breaks',  kinds: 't', ar: 'بيتكسر بسهولة؟', en: 'Breaks easily?' },
  { id: 'noise',   kinds: 't', ar: 'بيعمل صوت؟', en: 'Does it make a sound?' },
  { id: 'clean',   kinds: 't', ar: 'بنستعمله في النضافة أو الغسيل؟', en: 'Used for cleaning or washing?' },
  { id: 'talk',    kinds: 't', ar: 'بنكلّم بيه الناس أو بنتفرج عليه؟', en: 'Used to talk to people, or to watch?' },
  { id: 'time',    kinds: 't', ar: 'له علاقة بالوقت أو المواعيد؟', en: 'To do with time?' },
  { id: 'wet',     kinds: 'tj', ar: 'له علاقة بالمية أو البحر؟', en: 'To do with water or the sea?' },
  { id: 'container', kinds: 't', ar: 'بنحط فيه حاجات؟', en: 'Do we put things in it?' },
  { id: 'street',  kinds: 't', ar: 'بتلاقيه في الشارع؟', en: 'Found in the street?' },
  { id: 'peel',    kinds: 't', ar: 'بنقشّره قبل ما ناكله؟', en: 'Do we peel it before eating it?' },
  { id: 'meat_t',  kinds: 't', ar: 'فيه لحمة أو فراخ؟', en: 'Has meat or chicken in it?' },
  /* things, added 9 Oct 2026 (the third pass): its shape, its feel, its smell, its colours -
     things that answered «لأ» to every generic question used to look alike */
  { id: 'square',  kinds: 't', ar: 'شكله مربع أو مستطيل؟', en: 'Square or rectangular?' },
  { id: 'long',    kinds: 't', ar: 'شكله طويل ورفيع؟', en: 'Long and thin?' },
  { id: 'soft',    kinds: 't', ar: 'طري لما تلمسه؟', en: 'Soft to the touch?' },
  { id: 'smell',   kinds: 't', ar: 'ريحته حلوة؟', en: 'Does it smell nice?' },
  { id: 'colorful', kinds: 't', ar: 'ألوانه كتير؟', en: 'Many colours?' },
  /* things, added 9 Oct 2026 (pairs the full review left alike: the vehicles, the screens, the house, the
     sweets): every thing was gone over for each - a yes where a family would say yes, a maybe where it depends */
  { id: 'twowheels', kinds: 't', ar: 'ليه عجلتين بس؟', en: 'Has just two wheels?' },
  { id: 'cargo',   kinds: 't', ar: 'بيشيل بضاعة أو حمولة تقيلة؟', en: 'Carries goods or heavy loads?' },
  { id: 'fare',    kinds: 't', ar: 'بتدفع أجرة عشان تركبه؟', en: 'Do you pay a fare to ride it?' },
  { id: 'siren',   kinds: 't', ar: 'ليه سارينة؟', en: 'Has a siren?' },
  { id: 'standing', kinds: 't', ar: 'الناس بتركب فيه واقفة؟', en: 'Do people ride it standing up?' },
  { id: 'travel',  kinds: 't', ar: 'بنسافر بيه من مدينة لمدينة؟', en: 'Do we travel in it from city to city?' },
  { id: 'floor',   kinds: 't', ar: 'بيتفرش على الأرض؟', en: 'Spread on the floor?' },
  { id: 'bedroom', kinds: 't', ar: 'بتلاقيه في أوضة النوم؟', en: 'Found in the bedroom?' },
  { id: 'read',    kinds: 't', ar: 'بنقرا فيه؟', en: 'Do we read it?' },
  { id: 'internet', kinds: 't', ar: 'بيدخل على الإنترنت؟', en: 'Goes on the internet?' },
  { id: 'byremote', kinds: 't', ar: 'بيشتغل بريموت كنترول؟', en: 'Worked with a remote control?' },
  { id: 'touch',   kinds: 't', ar: 'بتلمس شاشته عشان تستعمله؟', en: 'Do you touch its screen to use it?' },
  { id: 'listen',  kinds: 't', ar: 'بنسمع منه أغاني أو أخبار؟', en: 'Do we listen to songs or the news on it?' },
  { id: 'seeds',   kinds: 't', ar: 'جواه بذور كتير؟', en: 'Lots of seeds inside?' },
  { id: 'stuffed', kinds: 't', ar: 'جواه حشو؟', en: 'Has a filling inside?' },
  { id: 'fried',   kinds: 't', ar: 'بيتقلي في الزيت؟', en: 'Fried in oil?' },
  { id: 'leaves',  kinds: 't', ar: 'معمول من ورق نبات (أو هو ورق نبات)؟', en: 'Made of leaves (or is it leaves)?' },
  { id: 'flame',   kinds: 't', ar: 'فيه نار (لهب)؟', en: 'Has a flame?' },
  { id: 'holdsdrink', kinds: 't', ar: 'بنحط فيه حاجة نشربها؟', en: 'Holds something we drink?' },
  { id: 'rainy',   kinds: 't', ar: 'له علاقة بالمطر أو الشتا؟', en: 'To do with rain or winter?' },

  /* ---------- games and apps (10 Oct 2026, OracleApps.js) ---------- */

  /* ---------- jobs ---------- */
  { id: 'uniform', kinds: 'j', ar: 'بيلبس يونيفورم أو زي معيّن؟', en: 'Wears a uniform?' },
  { id: 'hospital', kinds: 'j', ar: 'بيشتغل في مستشفى أو عيادة؟', en: 'Works in a hospital or a clinic?' },
  { id: 'teach',   kinds: 'j', ar: 'بيشتغل في مدرسة أو جامعة؟', en: 'Works in a school or a university?' },
  { id: 'outdoors', kinds: 'j', ar: 'شغله برّه في الشارع أو الهوا الطلق؟', en: 'Works outdoors?' },
  { id: 'drives',  kinds: 'j', ar: 'بيسوق (عربية أو طيارة أو مركب أو قطر)؟', en: 'Drives (a car, a plane, a boat, a train)?' },
  { id: 'hands',   kinds: 'j', ar: 'صنايعي، شغله بإيده؟', en: 'A craftsman, working with his hands?' },
  { id: 'food_j',  kinds: 'j', ar: 'شغله فيه أكل أو شرب؟', en: 'Works with food or drink?' },
  { id: 'rescue',  kinds: 'j', ar: 'بيحمي الناس أو بينقذهم؟', en: 'Protects or rescues people?' },
  { id: 'art_j',   kinds: 'j', ar: 'شغله فن (رسم، تصوير، موسيقى)؟', en: 'An artist (drawing, photos, music)?' },
  { id: 'desk',    kinds: 'j', ar: 'شغله على مكتب؟', en: 'Works at a desk?' },
  { id: 'study',   kinds: 'j', ar: 'بيدرس سنين كتير في الجامعة عشانه؟', en: 'Needs many years at university?' },
  { id: 'animals_j', kinds: 'j', ar: 'بيتعامل مع حيوانات؟', en: 'Works with animals?' },
  { id: 'sells',   kinds: 'j', ar: 'بيبيع حاجة؟', en: 'Sells something?' },
  { id: 'build',   kinds: 'j', ar: 'بيبني أو بيصلّح حاجات؟', en: 'Builds or repairs things?' },
  { id: 'law',     kinds: 'j', ar: 'له علاقة بالقانون أو المحاكم؟', en: 'To do with the law or the courts?' },
  { id: 'sea_j',   kinds: 'j', ar: 'شغله في البحر أو على مركب؟', en: 'Works at sea or on a boat?' },
  { id: 'fire_j',  kinds: 'j', ar: 'شغله جنب النار أو الفرن؟', en: 'Works near fire or an oven?' },
  { id: 'cars_j',  kinds: 'j', ar: 'شغله في العربيات؟', en: 'Works with cars?' },
  { id: 'power_j', kinds: 'j', ar: 'شغله في الكهربا أو الكمبيوتر؟', en: 'Works with electricity or computers?' },
  { id: 'looks_j', kinds: 'j', ar: 'بيهتم بشكل الناس (شعر، لبس)؟', en: 'Takes care of how people look (hair, clothes)?' },
  { id: 'money_j', kinds: 'j', ar: 'شغله في الفلوس والحسابات؟', en: 'Works with money and accounts?' },
  { id: 'kids_j',  kinds: 'j', ar: 'بيتعامل مع أطفال كتير؟', en: 'Works with a lot of children?' },
  { id: 'night_j', kinds: 'j', ar: 'ممكن يشتغل طول الليل؟', en: 'Can work all night?' },
  { id: 'shop_j',  kinds: 'j', ar: 'بيشتغل في محل أو ورشة؟', en: 'Works in a shop or a workshop?' },
  { id: 'house_j', kinds: 'j', ar: 'بيجيلك البيت عشان يشتغل؟', en: 'Comes to your home to work?' },
  { id: 'stage_j', kinds: 'j', ar: 'بيظهر في التلفزيون أو على المسرح؟', en: 'Appears on TV or on stage?' },
  { id: 'sport_j', kinds: 'j', ar: 'شغله في الرياضة؟', en: 'Works in sport?' },
  { id: 'army_j',  kinds: 'j', ar: 'من الجيش أو الشرطة أو الأمن؟', en: 'In the army, the police or security?' },
  { id: 'words_j', kinds: 'j', ar: 'شغله في الكتابة أو الأخبار أو اللغات؟', en: 'Works with writing, news or languages?' },
  { id: 'clothes_j', kinds: 'j', ar: 'شغله في اللبس أو القماش أو الجزم؟', en: 'Works with clothes, cloth or shoes?' },
  { id: 'travel_j', kinds: 'j', ar: 'شغله بيسفّره أو بينقل الناس من مكان لمكان؟', en: 'Travels, or takes people from place to place?' },
  { id: 'plants_j', kinds: 'j', ar: 'شغله في الزرع أو الورد؟', en: 'Works with plants or flowers?' },
  { id: 'clean_j', kinds: 'j', ar: 'شغله في النضافة؟', en: 'Works at cleaning?' },
  { id: 'cart_j',  kinds: 'j', ar: 'بيبيع على عربية في الشارع؟', en: 'Sells from a cart in the street?' },
  { id: 'lab_j',   kinds: 'j', ar: 'بيشتغل في معمل؟', en: 'Works in a laboratory?' },
  { id: 'music_j', kinds: 'j', ar: 'شغله في المزيكا أو الغُنا؟', en: 'Works with music or singing?' },
  /* added 9 Oct 2026 (pairs the full review left alike); every job was gone over for each */
  { id: 'voice_j', kinds: 'j', ar: 'شغله إنه يتكلم أو يغني قدّام ناس؟', en: 'Talks or sings in front of people for work?' },
  { id: 'film_j',  kinds: 'j', ar: 'بيشتغل في الأفلام أو المسلسلات؟', en: 'Works in films or TV series?' },
  { id: 'boss_j',  kinds: 'j', ar: 'هو الريّس اللي بيدّي الأوامر في الشغل؟', en: 'The boss who gives the orders at work?' },
  { id: 'danger_j', kinds: 'j', ar: 'شغله فيه خطر على حياته؟', en: 'Dangerous work, a risk to his life?' },
  { id: 'gov_j',   kinds: 'j', ar: 'موظف حكومة؟', en: 'A government employee?' },
  { id: 'scale_j', kinds: 'j', ar: 'بيوزن حاجات بالميزان؟', en: 'Weighs things on a scale?' },
  { id: 'stands_j', kinds: 'j', ar: 'بيشتغل واقف طول اليوم؟', en: 'Works standing all day?' },
];
