/* ============================================================================
   الموقع السري — the places, each with the jobs found there.
   ----------------------------------------------------------------------------
   Shared by the page (inlined by tools/build-*.mjs) and the rooms server
   (bundled by rooms-worker/build.mjs). The list of place names is public in
   the game - it is what the spy guesses from - only which one is in play is
   secret.
   ========================================================================= */
const SPYFALL_DB = {
  ar: [
    {"location": "قلعة تاريخية 🏰", "roles": ["حارس برج", "ملك", "مؤرخ سياحي", "مرشد", "طاهي قلعة", "زائر متحمس", "حارس خندق"]},
    {"location": "محطة إطفاء 🚒", "roles": ["قائد فرقة إطفاء", "سائق سيارة إطفاء", "مسعف", "متدرب", "ضابط اتصالات", "منقذ محاصرين", "فني خراطيم"]},
    {"location": "منتجع تزلج ⛷️", "roles": ["مدرب تزلج", "مشغل تلفريك", "سائح مستمتع", "منقذ جليد", "عامل صيانة زلاجات", "طبيب كسور", "صاحب كوخ"]},
    {"location": "محطة نووية ☢️", "roles": ["مهندس مفاعل", "خبير أمان إشعاعي", "مدير محطة", "حارس أمني", "فني تبريد", "عالم فيزياء", "عامل صيانة"]},
    {"location": "منصة نفط 🛢️", "roles": ["حفار بترول", "قبطان مروحية نقل", "مهندس منصة", "طباخ المنصة", "غطاس أعماق", "فني ميكانيك", "ضابط بيئة"]},
    {"location": "استوديو تلفزيون 📺", "roles": ["مذيع أخبار", "مخرج بث", "مصور كاميرا", "ضيف برنامج", "مهندس صوت", "أخصائي مكياج", "معد برامج"]},
    {"location": "قاعة محكمة ⚖️", "roles": ["قاضي", "محامي دفاع", "مدعي عام", "متهم", "شاهد إثبات", "حاجب محكمة", "أمين سر"]},
    {"location": "مخبز وحلواني 🥐", "roles": ["خباز بلدي", "شيف حلويات", "كاشير", "عامل عجانة", "زبون جائع", "عامل توصيل", "مسؤول تزيين كيك"]},
    {"location": "تفتيش أمن المطار 🛂", "roles": ["ضابط جمارك", "مفتش حقائب", "مسافر متأخر", "دليل كلاب بوليسية", "مسؤول أشعة", "مشرف صالة", "راكب مضطرب"]},
    {"location": "حوض أسماك عملاق 🐠", "roles": ["غواص إطعام أسماك", "طبيب أحياء بحرية", "مرشد أطفال", "بائع تذاكر", "عامل نظافة أحواض", "مصور تحت الماء", "زائر مبهور"]},
    {"location": "صالة ألعاب جيم 🏋️", "roles": ["مدرب كمال أجسام", "متدرب جديد", "موظف استقبال", "بائع بروتين", "أخصائي علاج طبيعي", "لاعب محترف", "عامل نظافة"]},
    {"location": "ورشة تصليح سيارات 🔧", "roles": ["ميكانيكي", "كهربائي سيارات", "سمكري ودهان", "زبون قلق", "محاسب ورشة", "صاحب الورشة", "سائق ونش"]},
    {"location": "دار أوبرا 🎭", "roles": ["مغني تينور", "مايسترو أوركسترا", "عازف كمان", "مشاهد في البلكون", "مصمم أزياء", "قاطع تذاكر", "مهندس إضاءة"]},
    {"location": "ميناء سفن بضائع ⚓", "roles": ["سائق رافعة عملاقة", "قبطان قاطرة", "موظف جمارك", "بحار أجنبي", "حارس بوابة الميناء", "تاجر مستورد", "مفتش حاويات"]},
    {"location": "مزرعة ريفية 🚜", "roles": ["مزارع صاحب الأرض", "حلاب أبقار", "سائق جرار", "طبيب بيطري", "جامع ثمار", "حارس مزرعة", "زائر من المدينة"]},
    {"location": "مكتبة عامة 📖", "roles": ["أمين مكتبة", "باحث دكتوراه", "طالب يذاكر", "قارئ روايات", "عامل أرشيف", "موظف استعارة", "كاتب يبحث عن إلهام"]},
    {"location": "معمل أبحاث أدوية 🧪", "roles": ["عالم كيمياء حيوية", "باحث أدوية", "فني مختبر", "مدير أبحاث", "خبير جينات", "مساعد تجارب", "مسؤول سلامة حيوية"]},
    {"location": "قصر رئاسي 🏛️", "roles": ["حارس شرف", "مستشار رئاسي", "سكرتير خاص", "صحفي معتمد", "رئيس التشريفات", "طاهي القصر", "دبلوماسي أجنبي"]},
    {"location": "مركز تسوق ضخم 🛍️", "roles": ["حارس أمن المول", "متسوق مهووس", "بائع عطور", "عامل كشك مثلجات", "عامل نظافة", "طفل ضائع", "مدير أمن المول"]},
    {"location": "محطة أتوبيسات 🚌", "roles": ["سائق حافلة", "كمسرى", "مسافر غافي", "بائع مناديل", "ناظر محطة", "حمال شنط", "راكب ينتظر خطه"]},
    {"location": "سفينة شحن في عاصفة 🌊", "roles": ["قبطان مستنفر", "رئيس بحارة", "ضابط ملاحة", "فني محركات", "طاهي متأرجح", "مساعد بحار خائف", "ضابط رادار"]},
    {"location": "موقع أثري تحت الحفر ⛏️", "roles": ["عالم آثار رئيسي", "منقب تراب", "مصور نقوش", "مرمم فخار", "حارس الموقع", "طالب بعثة", "أستاذ تاريخ"]},
    {"location": "مهرجان طعام شوارع 🌮", "roles": ["بياع كبدة", "زبون يجرب كل شيء", "ناقد سوشيال ميديا", "عامل تنظيف طاولات", "منظم مهرجان", "بائع مشروبات مثلجة", "عازف جيتار متجول"]},
    { location: "طائرة ✈️", roles: ["طيار", "مضيفة", "مسافر درجة أولى", "راكب خائف", "مارشال جوي", "ميكانيكي طيران", "مساعد طيار"] },
    { location: "سفينة سياحية 🚢", roles: ["قبطان", "نادل بوفيه", "مسافر ثري", "منقذ مسبح", "موسيقي", "طباخ سفينة", "موظف استقبال"] },
    { location: "مستشفى 🏥", roles: ["طبيب جراح", "ممرضة", "مريض", "طبيب تخدير", "زائر", "موظف استقبال", "صيدلي مشفى"] },
    { location: "بنك 🏦", roles: ["مدير فرع", "صراف", "حارس أمن", "عميل", "محاسب", "سارق متنكر", "خبير قروض"] },
    { location: "محطة فضاء 🚀", roles: ["رائد فضاء", "قائد مهمة", "عالم أحياء", "مهندس ميكانيكي", "سائح فضاء", "أخصائي اتصالات", "طبيب فضاء"] },
    { location: "سوبرماركت 🛒", roles: ["كاشير", "زبون", "موظف رص بضائع", "مدير فرع", "حارس أمن", "جزار", "بائع خضار"] },
    { location: "سينما 🍿", roles: ["قاطع تذاكر", "زائر مع فشار", "عامل نظافة", "مشغل العرض", "مدير صالة", "صانع فشار", "متفرج متأخر"] },
    { location: "فندق 🏨", roles: ["موظف استقبال", "حامل حقائب", "نزيل", "عاملة نظافة", "طاهي", "مدير الفندق", "حارس أمن"] },
    { location: "سفينة قراصنة 🏴‍☠️", roles: ["قبطان قرصان", "بحار مدفعي", "أسير", "مراقب الصاري", "طباخ قراصنة", "قرصان خائن", "ملاح"] },
    { location: "قسم شرطة 🚓", roles: ["ضابط تحقيق", "محامي", "شرطي دورية", "سجين", "شاهد", "كاتب بلاغات", "خبير بصمات"] },
    { location: "مطعم فاخر 🍽️", roles: ["شيف تنفيذي", "جرسون", "زبون ناقد", "ناقد طعام", "جلي صحون", "مدير مطعم", "شيف حلويات"] },
    { location: "مدرسة 🏫", roles: ["معلم رياضيات", "طالب مشاغب", "مدير مدرسة", "حارس أمن", "أمين مكتبة", "طالب متفوق", "أخصائي اجتماعي"] },
    { location: "غواصة 🌊", roles: ["قبطان غواصة", "مسؤول سونار", "مهندس توربينات", "بحار", "طباخ", "ضابط أسلحة", "طبيب"] },
    { location: "قاعدة عسكرية 🎖️", roles: ["جنرال", "جندي حراسة", "قناص", "مدرب لياقة", "طبيب ميداني", "مسؤول مخزن أسلحة", "طيار حربي"] },
    { location: "شاطئ 🏖️", roles: ["منقذ", "مصطاف", "بائع مثلجات", "راكب أمواج", "غواص", "بائع شمسيات", "طفل يبني قصر رمل"] },
    { location: "حديقة حيوان 🦁", roles: ["حارس أقفاص", "طبيب بيطري", "زائر مع أطفاله", "بائع تذاكر", "مرشد سياحي", "مصور", "خبير تغذية"] },
    { location: "متحف 🏛️", roles: ["مرشد سياحي", "أمين متحف", "حارس أمن", "زائر أجنبي", "مؤرخ", "خبير ترميم", "طالب فنون"] },
    { location: "سيرك 🎪", roles: ["لاعب خفة", "مهرج", "مروض أسود", "لاعب بهلوان", "بائع تذاكر", "منسق موسيقى", "متفرج متحمس"] },
    { location: "سبا ومنتجع 💆", roles: ["أخصائي مساج", "نزيل مسترخي", "موظف استقبال", "مدرب ساونا", "خبير عناية بشرة", "عامل نظافة", "مدرب يوجا"] },
    { location: "محطة قطار 🚆", roles: ["سائق قطار", "كمسرى", "مسافر في عجلة", "عامل شحن", "حارس محطة", "بائع جرائد", "مشغل تحويلات"] },
    { location: "جامعة 🎓", roles: ["أستاذ دكتور", "معيد", "طالب سنة أولى", "عميد الكلية", "طالب دراسات عليا", "أمين مكتبة", "موظف شؤون طلاب"] },
    { location: "حفل زفاف 👰", roles: ["عريس", "عروس", "مصور فوتوغرافي", "دي جي", "والد العروس", "نادل قاعة", "ضيف غير مدعو"] },
    { location: "ملاهي 🎡", roles: ["مشغل قطار الموت", "زائر خائف", "بائع غزل بنات", "منظم طوابير", "فني صيانة", "طفل متحمس", "مصور"] },
    { location: "مخيم صحراوي ⛺", roles: ["مرشد بدوي", "سائح مغامر", "طباخ نار", "سواق جيب", "مراقب نجوم", "مسافر تائه", "مسعف"] },
    { location: "معرض فنون 🎨", roles: ["فنان تشكيلي", "جامع لوحات ثري", "ناقد فني", "زائر حائر", "حارس أمن المعرض", "مصور صحفي", "مشتري في مزاد"] },
    {"location": "ميكروباص 🚐", "roles": ["سواق", "تباع", "راكب نايم", "راكبة معاها شنط", "طالب جامعة", "راجل بيتكلم في التليفون", "واحد بيدور على فكة"]},
    {"location": "قهوة بلدي ☕", "roles": ["صاحب القهوة", "القهوجي", "لاعب طاولة", "مشجع كورة", "واحد بيقرا الجرنال", "بياع مناديل", "زبون دايم"]},
    {"location": "عيادة أسنان 🦷", "roles": ["دكتور أسنان", "مساعدة الدكتور", "طفل خايف", "أم الطفل", "موظفة استقبال", "مريض بتقويم", "فني تركيبات"]},
    {"location": "صالون حلاقة 💈", "roles": ["حلاق", "صبي الحلاق", "عريس بيجهز", "طفل أول حلاقة", "زبون مستعجل", "واحد مستني دوره", "بياع برفانات"]},
    {"location": "استاد كرة قدم 🏟️", "roles": ["لاعب", "مدرب", "حكم", "مشجع متعصب", "معلق", "مصور", "بياع فشار"]},
    {"location": "مترو الأنفاق 🚇", "roles": ["سائق المترو", "موظف شباك التذاكر", "راكب واقف", "طالب رايح الجامعة", "أمن المحطة", "بياع متجول", "سائح تايه"]},
    {"location": "رحلة سفاري في الصحراء 🐪", "roles": ["مرشد بدوي", "سائق جيب", "سائح", "راكب جمل", "طباخ المخيم", "مصور", "حارس المخيم"]},
    {"location": "محل ألعاب فيديو 🎮", "roles": ["صاحب المحل", "لاعب محترف", "طفل بيلعب لأول مرة", "فني صيانة", "زبون بيتعصب لما يخسر", "صاحبه بيشجعه", "بياع مشروبات"]},
    {"location": "مصنع شوكولاتة 🍫", "roles": ["مدير المصنع", "عامل خط الإنتاج", "متذوق شوكولاتة", "مهندس صيانة", "سائق توزيع", "زائر في جولة", "مسؤول الجودة"]},
    {"location": "أكوا بارك 🌊", "roles": ["منقذ", "طفل على الزحليقة", "أب بيصور", "بياع آيس كريم", "موظف التذاكر", "عامل نظافة", "مراهق بيتحدى صحابه"]},
    {"location": "موقع تصوير فيلم 🎬", "roles": ["مخرج", "البطل", "دوبلير", "مصور", "ماكيير", "كومبارس", "مساعد مخرج"]},
    {"location": "محطة بنزين ⛽", "roles": ["عامل البنزين", "كاشير", "سواق تاكسي", "سواق نقل", "عامل غسيل العربيات", "سواق تايه بيسأل على الطريق", "مدير المحطة"]},
    {"location": "فلوكة في النيل ⛵", "roles": ["ريس الفلوكة", "بحار", "عريس وعروسة", "سائح", "مصور", "عازف عود", "راكب خايف من المية"]},
    {"location": "معرض الكتاب 📚", "roles": ["كاتب بيوقع كتابه", "ناشر", "طالب بيدور على خصم", "منظم المعرض", "طفل بيدور على قصص", "بياع كتب قديمة", "صحفي"]},
    {"location": "مدينة ملاهي مائية للأطفال 🐠", "roles": ["مدرب سباحة", "طفل خايف", "أم قاعدة تراقب", "منقذ", "بياع عصير", "عامل صيانة", "منشط حفلات"]},

    {"location": "محطة أرصاد جوية 🌦️", "roles": ["عالم أرصاد", "مذيع النشرة الجوية", "فني أجهزة", "متدرب", "مصور سحب", "مدير المحطة", "تلميذ في زيارة"]},
    {"location": "مصنع عربيات 🏭", "roles": ["مهندس", "عامل خط إنتاج", "مراقب جودة", "سواق اختبار", "مشغل روبوت اللحام", "مدير المصنع", "مستثمر زائر"]},
    {"location": "مزرعة نحل 🐝", "roles": ["نحال", "بائع عسل", "زائر خايف من النحل", "باحث حشرات", "مصور طبيعة", "صاحب المزرعة", "طفل في رحلة مدرسية"]},
    {"location": "حضانة أطفال 🧸", "roles": ["مدرسة الحضانة", "طفل بيعيط", "أم مستعجلة", "طباخة", "سواق باص الحضانة", "مديرة الحضانة", "ممرضة"]},
    {"location": "معرض سيارات 🚗", "roles": ["بائع سيارات", "زبون بيفاصل", "ميكانيكي", "مدير المعرض", "موظف تقسيط", "مصور إعلانات", "عامل تلميع"]},
    {"location": "محل ورد 💐", "roles": ["بائع ورد", "عريس بيشتري بوكيه", "منسق زهور", "عامل توصيل", "طالب بيشتري هدية", "مورد ورد", "صاحب المحل"]},
    {"location": "معسكر كشافة ⛺", "roles": ["قائد الكشافة", "كشاف صغير", "طباخ المعسكر", "منقذ", "مسؤول الإسعافات", "عازف جيتار", "ولي أمر في زيارة"]},
    {"location": "سوق خضار شعبي 🥕", "roles": ["فكهاني", "خضري", "ست بتفاصل", "شيال", "بياع ليمون", "صاحب الميزان", "طفل بيساعد أبوه"]},
    {"location": "مركز شباب ⚽", "roles": ["مدرب كورة", "لاعب ناشئ", "عامل المركز", "مدير المركز", "مدرب تنس طاولة", "متطوع", "ولي أمر"]},
    {"location": "استوديو تسجيل أغاني 🎙️", "roles": ["مطرب", "مهندس صوت", "ملحن", "عازف", "مدير أعمال", "مخرج كليبات", "معجب عايز صورة"]},
    {"location": "مغسلة عربيات 🧽", "roles": ["عامل غسيل", "كاشير", "زبون مستعجل", "مدير المغسلة", "عامل تلميع", "سواق تاكسي", "بياع مناديل"]},
    {"location": "أتوبيس رحلة مدرسية 🚌", "roles": ["سواق الأتوبيس", "مدرس مشرف", "تلميذ شقي", "تلميذ نايم", "مرشد سياحي", "ممرضة الرحلة", "تلميذ دايخ"]},
    {"location": "معبد الكرنك 🏛️", "roles": ["مرشد سياحي", "سائح", "عالم آثار", "حارس المعبد", "بائع تماثيل", "مصور", "طالب آثار"]},
    {"location": "قطر النوم لأسوان 🚆", "roles": ["كمسري", "مضيف العربة", "سائح", "عيلة مسافرة", "طباخ عربة الأكل", "سواق القطر", "راكب بيشخر"]},
    {"location": "استوديو رسوم متحركة 🎨", "roles": ["رسام", "مخرج", "مؤدي أصوات", "مبرمج مؤثرات", "كاتب القصة", "منتج", "متدرب"]},
    {"location": "مصنع لعب أطفال 🪀", "roles": ["مصمم ألعاب", "عامل تغليف", "مختبر أمان", "مدير المصنع", "طفل بيجرب اللعب", "سواق شاحنة", "مسؤول تسويق"]},
    {"location": "قاعة امتحانات 📝", "roles": ["مراقب", "طالب متوتر", "طالب نسي القلم", "ناظر المدرسة", "موزع الورق", "عامل البوفيه", "ولي أمر مستني برا"]},
    {"location": "عيادة بيطرية 🐾", "roles": ["دكتور بيطري", "ممرض بيطري", "صاحب قطة", "صاحب كلب", "موظف استقبال", "بائع أكل حيوانات", "مربي عصافير"]},
    {"location": "صيدلية 💊", "roles": ["صيدلي", "مساعد صيدلي", "زبون عنده برد", "مندوب أدوية", "عامل دليفري", "أم معاها طفل", "دكتور معدي"]},
    {"location": "محل موبايلات 📱", "roles": ["بائع موبايلات", "فني صيانة", "زبون شاشته مكسورة", "مندوب شركة", "كاشير", "طالب بيشتري سماعة", "صاحب المحل"]},
    {"location": "مركز خدمة عملاء ☎️", "roles": ["موظف خدمة عملاء", "مشرف", "عميل غضبان", "فني", "متدرب جديد", "مدير الفرع", "عامل بوفيه"]},
    {"location": "مكتب بريد 📮", "roles": ["موظف الشباك", "ساعي البريد", "عجوز بيصرف المعاش", "شاب بيبعت طرد", "مدير المكتب", "حارس", "طالب بيشتري طوابع"]},
    {"location": "برج المراقبة في المطار 🛫", "roles": ["مراقب جوي", "طيار على اللاسلكي", "فني رادار", "مدير البرج", "متدرب", "مسؤول الأرصاد", "عامل صيانة"]},
    {"location": "مركز غطس 🤿", "roles": ["مدرب غطس", "غطاس مبتدئ", "ريس المركب", "مصور تحت المية", "عالم أحياء بحرية", "سائح", "عامل المعدات"]},
    {"location": "نهائي بطولة تنس 🎾", "roles": ["لاعب", "حكم الكرسي", "جامع الكور", "مدرب", "معلق", "مشجع", "مصور"]},
    {"location": "قرية نوبية 🏡", "roles": ["مرشد نوبي", "صاحب بيت ضيافة", "سائح", "صانع مشغولات", "مراكبي", "طفل نوبي", "طباخة"]},
    {"location": "مولد شعبي 🎠", "roles": ["بياع حمص", "صاحب المراجيح", "مغني شعبي", "بياع حلاوة المولد", "طفل تايه", "مصور", "زائر"]},
    {"location": "خان الخليلي 🏺", "roles": ["بائع تحف", "صانع نحاس", "سائح", "بائع بخور", "صاحب القهوة", "مرشد", "مصور"]},
    {"location": "مصنع عصير 🍊", "roles": ["عامل العصارات", "مراقب جودة", "سواق توزيع", "مورد برتقال", "مدير الإنتاج", "عامل تعبئة", "زائر"]},
    {"location": "غيط قمح وقت الحصاد 🌾", "roles": ["فلاح", "سواق الكومباين", "تاجر قمح", "طفل بيلعب", "طباخة في الغيط", "مهندس زراعي", "عامل تحميل"]},
    {"location": "حلبة سباق عربيات 🏎️", "roles": ["سواق سباق", "ميكانيكي الفريق", "مدير الفريق", "حكم السباق", "مشجع", "مذيع", "مصور"]},
    {"location": "ملعب جولف ⛳", "roles": ["لاعب جولف", "حامل المضارب", "مدرب", "عامل صيانة النجيلة", "موظف النادي", "متفرج", "مصور"]},
    {"location": "معرض تكنولوجيا 💻", "roles": ["مخترع", "مندوب شركة", "صحفي تكنولوجيا", "زائر", "مشغل روبوت", "منظم المعرض", "طالب هندسة"]},
    {"location": "مهرجان سينمائي 🎬", "roles": ["نجم سينما", "مخرج", "صحفي", "مصور السجادة الحمرا", "عضو لجنة التحكيم", "معجب", "منظم"]},
    {"location": "مسرح عرايس 🎭", "roles": ["محرك العرايس", "مؤدي أصوات", "طفل متفرج", "بائع التذاكر", "المؤلف", "فني إضاءة", "أم مع أولادها"]},
    {"location": "محطة إذاعة 📻", "roles": ["مذيع", "مهندس صوت", "ضيف", "معد البرنامج", "متصل على الهوا", "مدير المحطة", "مراسل"]},
    {"location": "مصنع نسيج 🧵", "roles": ["عامل النول", "مصمم أقمشة", "مراقب جودة", "مدير المصنع", "سواق", "عامل صباغة", "تاجر قماش"]},
    {"location": "صالة بولينج 🎳", "roles": ["موظف الجزم", "لاعب محترف", "عيلة بتلعب", "فني الماكينات", "كاشير", "بياع فشار", "صاحب عيد الميلاد"]},
    {"location": "أكاديمية طيران ✈️", "roles": ["طيار مدرب", "طالب طيران", "مهندس طيارات", "مسؤول جهاز المحاكاة", "مراقب جوي", "مدير الأكاديمية", "مضيف متدرب"]},
    {"location": "مركب صيد في عرض البحر 🎣", "roles": ["ريس المركب", "صياد", "صبي المركب", "طباخ المركب", "تاجر سمك", "ميكانيكي الموتور", "سائح مغامر"]},
    {"location": "استوديو يوتيوبر 🎥", "roles": ["يوتيوبر", "مصور", "مونتير", "ضيف مشهور", "مدير القناة", "متابع كسبان مسابقة", "فني إضاءة"]},
    {"location": "محمية طبيعية 🦩", "roles": ["حارس المحمية", "عالم طيور", "مرشد", "سائح", "مصور حياة برية", "طبيب بيطري", "متطوع"]},
    {"location": "ورشة فخار 🏺", "roles": ["صانع فخار", "عامل الفرن", "رسام الزخارف", "بائع", "سائح", "صبي بيتعلم", "صاحب الورشة"]},
    {"location": "ماراثون في المدينة 🏃", "roles": ["عداء", "منظم", "متطوع بيوزع مية", "مسعف", "مشجع", "مصور", "حكم خط النهاية"]},
    {"location": "مطعم سمك في إسكندرية 🦐", "roles": ["طباخ السمك", "جرسون", "صياد بيورد السمك", "زبون بيختار سمكته", "كاشير", "عازف في الشارع", "صاحب المطعم"]},
    {"location": "رحلة بالون طاير فوق الأقصر 🎈", "roles": ["طيار البالون", "مساعد الطيار", "سائح", "مصور", "عريسين في شهر العسل", "عامل أرضي", "مرشد"]}
  ],
  en: [
    {"location": "Medieval Castle 🏰", "roles": ["Tower Guard", "King", "Historical Guide", "Tourist", "Castle Cook", "Excited Visitor", "Moat Keeper"]},
    {"location": "Fire Station 🚒", "roles": ["Fire Chief", "Fire Truck Driver", "Paramedic", "Rookie Firefighter", "Dispatcher", "Rescue Specialist", "Hose Technician"]},
    {"location": "Ski Resort ⛷️", "roles": ["Ski Instructor", "Lift Operator", "Excited Tourist", "Ski Patrol", "Equipment Technician", "Orthopedic Doctor", "Chalet Owner"]},
    {"location": "Nuclear Power Plant ☢️", "roles": ["Reactor Engineer", "Radiation Safety Officer", "Plant Director", "Security Guard", "Cooling Tech", "Nuclear Physicist", "Maintenance Worker"]},
    {"location": "Offshore Oil Rig 🛢️", "roles": ["Roughneck Driller", "Helicopter Pilot", "Platform Engineer", "Rig Cook", "Deep Sea Diver", "Mechanic", "Safety Officer"]},
    {"location": "TV News Studio 📺", "roles": ["News Anchor", "Broadcast Director", "Camera Operator", "Interview Guest", "Audio Engineer", "Makeup Artist", "Producer"]},
    {"location": "Courtroom ⚖️", "roles": ["Judge", "Defense Attorney", "Prosecutor", "Defendant", "Key Witness", "Bailiff", "Court Reporter"]},
    {"location": "Bakery 🥐", "roles": ["Head Baker", "Pastry Chef", "Cashier", "Dough Mixer", "Hungry Customer", "Delivery Driver", "Cake Decorator"]},
    {"location": "Airport Security 🛂", "roles": ["Customs Officer", "Baggage Screener", "Late Traveler", "K9 Handler", "X-Ray Monitor", "Terminal Supervisor", "Nervous Passenger"]},
    {"location": "Giant Aquarium 🐠", "roles": ["Scuba Feeder", "Marine Biologist", "Tour Guide", "Ticket Agent", "Tank Cleaner", "Underwater Photographer", "Awed Visitor"]},
    {"location": "Fitness Gym 🏋️", "roles": ["Personal Trainer", "Gym Newbie", "Front Desk Clerk", "Protein Shake Maker", "Physical Therapist", "Bodybuilder", "Cleaner"]},
    {"location": "Auto Repair Garage 🔧", "roles": ["Lead Mechanic", "Auto Electrician", "Body Shop Painter", "Worried Car Owner", "Service Writer", "Shop Owner", "Tow Truck Driver"]},
    {"location": "Opera House 🎭", "roles": ["Tenor Singer", "Orchestra Conductor", "Violinist", "Balcony Patron", "Costume Designer", "Usher", "Lighting Technician"]},
    {"location": "Container Cargo Port ⚓", "roles": ["Gantry Crane Operator", "Tugboat Captain", "Customs Inspector", "Foreign Sailor", "Port Gate Guard", "Freight Forwarder", "Cargo Inspector"]},
    {"location": "Country Farm 🚜", "roles": ["Farm Owner", "Dairy Milker", "Tractor Driver", "Veterinarian", "Harvester", "Farmhand", "City Visitor"]},
    {"location": "Public Library 📖", "roles": ["Librarian", "PhD Researcher", "Studying Student", "Novel Reader", "Archivist", "Check-out Clerk", "Inspired Writer"]},
    {"location": "Pharma Research Lab 🧪", "roles": ["Biochemist", "Pharmacologist", "Lab Tech", "Research Director", "Geneticist", "Trial Assistant", "Bio-Safety Officer"]},
    {"location": "Presidential Palace 🏛️", "roles": ["Honor Guard", "Senior Advisor", "Chief of Staff", "Press Reporter", "Protocol Chief", "Palace Chef", "Foreign Ambassador"]},
    {"location": "Mega Shopping Mall 🛍️", "roles": ["Mall Security", "Shopaholic", "Perfume Salesperson", "Ice Cream Vendor", "Janitor", "Lost Child", "Loss Prevention Officer"]},
    {"location": "Bus Terminal 🚌", "roles": ["Bus Driver", "Ticket Inspector", "Sleeping Passenger", "Snack Vendor", "Station Master", "Luggage Porter", "Waiting Commuter"]},
    {"location": "Cargo Ship in Storm 🌊", "roles": ["Alert Captain", "Chief Mate", "Navigating Officer", "Engine Tech", "Dizzy Cook", "Panicking Deckhand", "Radar Operator"]},
    {"location": "Archaeological Dig Site ⛏️", "roles": ["Lead Archaeologist", "Excavation Worker", "Field Photographer", "Pottery Restorer", "Site Guard", "Grad Student", "Historian"]},
    {"location": "Street Food Festival 🌮", "roles": ["Liver Sandwich Seller", "Foodie Trying Everything", "Social Media Critic", "Table Busser", "Festival Organizer", "Cold Drinks Vendor", "Busker Guitarist"]},
    { location: "Airplane ✈️", roles: ["Pilot", "Flight Attendant", "First Class Passenger", "Nervous Flyer", "Air Marshal", "Mechanic", "Co-Pilot"] },
    { location: "Cruise Ship 🚢", roles: ["Captain", "Buffet Waiter", "Wealthy Traveler", "Lifeguard", "Musician", "Ship Cook", "Receptionist"] },
    { location: "Hospital 🏥", roles: ["Surgeon", "Nurse", "Patient", "Anesthesiologist", "Visitor", "Receptionist", "Pharmacist"] },
    { location: "Bank 🏦", roles: ["Branch Manager", "Teller", "Security Guard", "Customer", "Accountant", "Disguised Robber", "Loan Officer"] },
    { location: "Space Station 🚀", roles: ["Astronaut", "Mission Commander", "Biologist", "Flight Engineer", "Space Tourist", "Communications Officer", "Doctor"] },
    { location: "Supermarket 🛒", roles: ["Cashier", "Customer", "Stock Clerk", "Store Manager", "Security Guard", "Butcher", "Produce Seller"] },
    { location: "Cinema 🍿", roles: ["Ticket Taker", "Customer with Popcorn", "Janitor", "Projectionist", "Theater Manager", "Popcorn Maker", "Late Viewer"] },
    { location: "Hotel 🏨", roles: ["Front Desk Agent", "Bellhop", "Guest", "Housekeeper", "Chef", "General Manager", "Security Guard"] },
    { location: "Pirate Ship 🏴‍☠️", roles: ["Pirate Captain", "Cannoneer", "Captive", "Crow's Nest Lookout", "Cook", "Mutineer", "Navigator"] },
    { location: "Police Station 🚓", roles: ["Detective", "Lawyer", "Patrol Officer", "Prisoner", "Witness", "Desk Sergeant", "Forensics Expert"] },
    { location: "Fine Restaurant 🍽️", roles: ["Executive Chef", "Waiter", "Picky Diner", "Food Critic", "Dishwasher", "Host", "Pastry Chef"] },
    { location: "School 🏫", roles: ["Math Teacher", "Troublemaker Student", "Principal", "Security Guard", "Librarian", "Top Student", "Counselor"] },
    { location: "Submarine 🌊", roles: ["Captain", "Sonar Tech", "Turbine Engineer", "Sailor", "Cook", "Weapons Officer", "Medic"] },
    { location: "Military Base 🎖️", roles: ["General", "Guard Soldier", "Sniper", "Drill Instructor", "Field Medic", "Armory Chief", "Fighter Pilot"] },
    { location: "Beach 🏖️", roles: ["Lifeguard", "Sunbather", "Ice Cream Vendor", "Surfer", "Scuba Diver", "Umbrella Renter", "Sandcastle Kid"] },
    { location: "Zoo 🦁", roles: ["Zookeeper", "Veterinarian", "Visiting Parent", "Ticket Seller", "Tour Guide", "Photographer", "Nutritionist"] },
    { location: "Museum 🏛️", roles: ["Tour Guide", "Curator", "Security Guard", "Tourist", "Historian", "Art Restorer", "Art Student"] },
    { location: "Circus 🎪", roles: ["Magician", "Clown", "Lion Tamer", "Acrobat", "Ticket Seller", "Music Director", "Excited Fan"] },
    { location: "Spa Resort 💆", roles: ["Massage Therapist", "Relaxed Guest", "Receptionist", "Sauna Master", "Esthetician", "Cleaner", "Yoga Instructor"] },
    { location: "Train Station 🚆", roles: ["Train Driver", "Conductor", "Rushing Traveler", "Porter", "Station Guard", "Newsstand Clerk", "Dispatcher"] },
    { location: "University 🎓", roles: ["Professor", "Teaching Assistant", "Freshman", "Dean", "Grad Student", "Librarian", "Registrar"] },
    { location: "Wedding 👰", roles: ["Groom", "Bride", "Photographer", "DJ", "Father of the Bride", "Catering Waiter", "Wedding Crasher"] },
    { location: "Amusement Park 🎡", roles: ["Roller Coaster Operator", "Terrified Rider", "Cotton Candy Vendor", "Queue Manager", "Technician", "Excited Kid", "Photographer"] },
    { location: "Campsite ⛺", roles: ["Camp Guide", "Adventurous Tourist", "Campfire Cook", "Jeep Driver", "Stargazer", "Lost Camper", "Medic"] },
    { location: "Art Gallery 🎨", roles: ["Painter", "Wealthy Collector", "Art Critic", "Puzzled Tourist", "Gallery Guard", "Photojournalist", "Auction Bidder"] },
    {"location": "Minibus 🚐", "roles": ["Driver", "Fare Collector", "Sleeping Passenger", "Passenger with Shopping Bags", "University Student", "Man on the Phone", "Someone Looking for Change"]},
    {"location": "Local Café ☕", "roles": ["Café Owner", "Waiter", "Backgammon Player", "Football Fan", "Newspaper Reader", "Tissue Seller", "Regular Customer"]},
    {"location": "Dental Clinic 🦷", "roles": ["Dentist", "Dental Assistant", "Scared Child", "Worried Parent", "Receptionist", "Patient with Braces", "Lab Technician"]},
    {"location": "Barber Shop 💈", "roles": ["Barber", "Apprentice", "Groom Getting Ready", "Child at First Haircut", "Customer in a Hurry", "Man Waiting His Turn", "Cologne Seller"]},
    {"location": "Football Stadium 🏟️", "roles": ["Player", "Coach", "Referee", "Die-hard Fan", "Commentator", "Photographer", "Snack Seller"]},
    {"location": "Underground Metro 🚇", "roles": ["Train Driver", "Ticket Clerk", "Standing Passenger", "Student", "Station Security", "Street Vendor", "Lost Tourist"]},
    {"location": "Desert Safari 🐪", "roles": ["Bedouin Guide", "4x4 Driver", "Tourist", "Camel Rider", "Camp Cook", "Photographer", "Camp Guard"]},
    {"location": "Gaming Café 🎮", "roles": ["Owner", "Pro Gamer", "First-time Kid", "Technician", "Sore Loser", "Cheering Friend", "Drinks Seller"]},
    {"location": "Chocolate Factory 🍫", "roles": ["Factory Manager", "Line Worker", "Chocolate Taster", "Maintenance Engineer", "Delivery Driver", "Tour Visitor", "Quality Inspector"]},
    {"location": "Water Park 🌊", "roles": ["Lifeguard", "Kid on the Slide", "Dad Filming", "Ice Cream Seller", "Ticket Clerk", "Cleaner", "Daring Teenager"]},
    {"location": "Film Set 🎬", "roles": ["Director", "Lead Actor", "Stunt Double", "Camera Operator", "Makeup Artist", "Extra", "Assistant Director"]},
    {"location": "Petrol Station ⛽", "roles": ["Pump Attendant", "Cashier", "Taxi Driver", "Truck Driver", "Car Wash Worker", "Lost Driver Asking Directions", "Station Manager"]},
    {"location": "Nile Felucca ⛵", "roles": ["Felucca Captain", "Deckhand", "Newlyweds", "Tourist", "Photographer", "Oud Player", "Passenger Afraid of Water"]},
    {"location": "Book Fair 📚", "roles": ["Author Signing Books", "Publisher", "Student Hunting Discounts", "Fair Organizer", "Kid Looking for Stories", "Second-hand Book Seller", "Journalist"]},
    {"location": "Kids' Swimming Club 🐠", "roles": ["Swimming Coach", "Nervous Child", "Watching Parent", "Lifeguard", "Juice Seller", "Maintenance Worker", "Party Entertainer"]},

    {"location": "Weather Station 🌦️", "roles": ["Meteorologist", "TV Weather Presenter", "Equipment Technician", "Trainee", "Storm Photographer", "Station Director", "Visiting Schoolchild"]},
    {"location": "Car Factory 🏭", "roles": ["Engineer", "Assembly Line Worker", "Quality Inspector", "Test Driver", "Welding Robot Operator", "Factory Manager", "Visiting Investor"]},
    {"location": "Bee Farm 🐝", "roles": ["Beekeeper", "Honey Seller", "Visitor Scared of Bees", "Insect Researcher", "Nature Photographer", "Farm Owner", "Child on a School Trip"]},
    {"location": "Nursery School 🧸", "roles": ["Nursery Teacher", "Crying Toddler", "Rushing Parent", "Cook", "Nursery Bus Driver", "Head of Nursery", "School Nurse"]},
    {"location": "Car Showroom 🚗", "roles": ["Car Salesperson", "Haggling Customer", "Mechanic", "Showroom Manager", "Finance Officer", "Advert Photographer", "Car Polisher"]},
    {"location": "Flower Shop 💐", "roles": ["Florist", "Groom Buying a Bouquet", "Flower Arranger", "Delivery Driver", "Student Buying a Present", "Flower Supplier", "Shop Owner"]},
    {"location": "Scout Camp ⛺", "roles": ["Scout Leader", "Young Scout", "Camp Cook", "Lifeguard", "First Aider", "Guitar Player", "Visiting Parent"]},
    {"location": "Street Market 🥕", "roles": ["Fruit Seller", "Vegetable Seller", "Haggling Shopper", "Porter", "Lemon Seller", "Scales Keeper", "Child Helping a Parent"]},
    {"location": "Youth Centre ⚽", "roles": ["Football Coach", "Junior Player", "Caretaker", "Centre Director", "Table Tennis Coach", "Volunteer", "Parent"]},
    {"location": "Recording Studio 🎙️", "roles": ["Singer", "Sound Engineer", "Composer", "Session Musician", "Manager", "Music Video Director", "Fan Hoping for a Photo"]},
    {"location": "Car Wash 🧽", "roles": ["Washer", "Cashier", "Customer in a Hurry", "Car Wash Manager", "Polisher", "Taxi Driver", "Tissue Seller"]},
    {"location": "School Trip Coach 🚌", "roles": ["Coach Driver", "Supervising Teacher", "Naughty Pupil", "Sleeping Pupil", "Tour Guide", "Trip Nurse", "Travel-sick Pupil"]},
    {"location": "Karnak Temple 🏛️", "roles": ["Tour Guide", "Tourist", "Archaeologist", "Temple Guard", "Souvenir Seller", "Photographer", "Archaeology Student"]},
    {"location": "Sleeper Train to Aswan 🚆", "roles": ["Ticket Inspector", "Carriage Attendant", "Tourist", "Travelling Family", "Dining Car Cook", "Train Driver", "Snoring Passenger"]},
    {"location": "Animation Studio 🎨", "roles": ["Animator", "Director", "Voice Actor", "Effects Programmer", "Story Writer", "Producer", "Intern"]},
    {"location": "Toy Factory 🪀", "roles": ["Toy Designer", "Packer", "Safety Tester", "Factory Manager", "Child Toy Tester", "Lorry Driver", "Marketing Officer"]},
    {"location": "Exam Hall 📝", "roles": ["Invigilator", "Nervous Student", "Student Who Forgot a Pen", "Head Teacher", "Paper Distributor", "Tea Server", "Parent Waiting Outside"]},
    {"location": "Vet Clinic 🐾", "roles": ["Vet", "Veterinary Nurse", "Cat Owner", "Dog Owner", "Receptionist", "Pet Food Seller", "Bird Breeder"]},
    {"location": "Pharmacy 💊", "roles": ["Pharmacist", "Pharmacy Assistant", "Customer with a Cold", "Medical Rep", "Delivery Rider", "Parent with a Baby", "Passing Doctor"]},
    {"location": "Phone Shop 📱", "roles": ["Phone Salesperson", "Repair Technician", "Customer with a Cracked Screen", "Network Rep", "Cashier", "Student Buying Earphones", "Shop Owner"]},
    {"location": "Call Centre ☎️", "roles": ["Customer Service Agent", "Supervisor", "Angry Caller", "IT Technician", "New Trainee", "Branch Manager", "Tea Server"]},
    {"location": "Post Office 📮", "roles": ["Counter Clerk", "Postman", "Pensioner Collecting a Pension", "Young Man Sending a Parcel", "Postmaster", "Security Guard", "Student Buying Stamps"]},
    {"location": "Air Traffic Control Tower 🛫", "roles": ["Air Traffic Controller", "Pilot on the Radio", "Radar Technician", "Tower Chief", "Trainee Controller", "Weather Officer", "Maintenance Worker"]},
    {"location": "Diving Centre 🤿", "roles": ["Diving Instructor", "Beginner Diver", "Boat Captain", "Underwater Photographer", "Marine Biologist", "Tourist", "Equipment Worker"]},
    {"location": "Tennis Final 🎾", "roles": ["Player", "Umpire", "Ball Boy", "Coach", "Commentator", "Fan", "Photographer"]},
    {"location": "Nubian Village 🏡", "roles": ["Nubian Guide", "Guesthouse Owner", "Tourist", "Craftsperson", "Boatman", "Village Child", "Cook"]},
    {"location": "Folk Festival 🎠", "roles": ["Chickpea Seller", "Swing Ride Owner", "Folk Singer", "Festival Sweets Seller", "Lost Child", "Photographer", "Visitor"]},
    {"location": "Khan el-Khalili Bazaar 🏺", "roles": ["Antique Seller", "Coppersmith", "Tourist", "Incense Seller", "Café Owner", "Guide", "Photographer"]},
    {"location": "Juice Factory 🍊", "roles": ["Press Operator", "Quality Inspector", "Delivery Driver", "Orange Supplier", "Production Manager", "Bottling Worker", "Visitor"]},
    {"location": "Wheat Harvest 🌾", "roles": ["Farmer", "Combine Harvester Driver", "Grain Merchant", "Playing Child", "Field Cook", "Agricultural Engineer", "Loader"]},
    {"location": "Racing Circuit 🏎️", "roles": ["Racing Driver", "Team Mechanic", "Team Principal", "Race Steward", "Fan", "Presenter", "Photographer"]},
    {"location": "Golf Course ⛳", "roles": ["Golfer", "Caddie", "Coach", "Groundskeeper", "Club Staff", "Spectator", "Photographer"]},
    {"location": "Tech Expo 💻", "roles": ["Inventor", "Company Rep", "Tech Journalist", "Visitor", "Robot Operator", "Organiser", "Engineering Student"]},
    {"location": "Film Festival 🎬", "roles": ["Film Star", "Director", "Journalist", "Red Carpet Photographer", "Jury Member", "Fan", "Organiser"]},
    {"location": "Puppet Theatre 🎭", "roles": ["Puppeteer", "Voice Artist", "Child in the Audience", "Ticket Seller", "Writer", "Lighting Technician", "Parent with Children"]},
    {"location": "Radio Station 📻", "roles": ["Radio Presenter", "Sound Engineer", "Guest", "Producer", "Caller on Air", "Station Manager", "Reporter"]},
    {"location": "Textile Mill 🧵", "roles": ["Loom Operator", "Fabric Designer", "Quality Inspector", "Mill Manager", "Driver", "Dye Worker", "Cloth Merchant"]},
    {"location": "Bowling Alley 🎳", "roles": ["Shoe Desk Attendant", "Pro Bowler", "Family Playing", "Lane Mechanic", "Cashier", "Popcorn Seller", "Birthday Child"]},
    {"location": "Flight School ✈️", "roles": ["Flight Instructor", "Student Pilot", "Aircraft Engineer", "Simulator Operator", "Air Traffic Controller", "Academy Director", "Trainee Cabin Crew"]},
    {"location": "Fishing Boat at Sea 🎣", "roles": ["Skipper", "Fisherman", "Deckhand", "Ship's Cook", "Fish Trader", "Engine Mechanic", "Adventurous Tourist"]},
    {"location": "YouTuber's Studio 🎥", "roles": ["YouTuber", "Camera Operator", "Video Editor", "Celebrity Guest", "Channel Manager", "Fan Who Won a Contest", "Lighting Technician"]},
    {"location": "Nature Reserve 🦩", "roles": ["Ranger", "Ornithologist", "Guide", "Tourist", "Wildlife Photographer", "Vet", "Volunteer"]},
    {"location": "Pottery Workshop 🏺", "roles": ["Potter", "Kiln Worker", "Pattern Painter", "Seller", "Tourist", "Apprentice", "Workshop Owner"]},
    {"location": "City Marathon 🏃", "roles": ["Runner", "Organiser", "Water Station Volunteer", "Paramedic", "Supporter", "Photographer", "Finish Line Judge"]},
    {"location": "Seafood Restaurant in Alexandria 🦐", "roles": ["Fish Cook", "Waiter", "Fisherman Delivering Fish", "Customer Choosing a Fish", "Cashier", "Street Musician", "Owner"]},
    {"location": "Hot-Air Balloon over Luxor 🎈", "roles": ["Balloon Pilot", "Pilot's Assistant", "Tourist", "Photographer", "Honeymoon Couple", "Ground Crew", "Guide"]}
  ]
};
