/* ============================================================================
   فوازير إيموجي — a film, a proverb, a dish or a place, told in emoji.
   ----------------------------------------------------------------------------
   Shared by the page (inlined by tools/build-*.mjs) and the rooms server
   (bundled by rooms-worker/build.mjs): on one phone the answer is revealed
   by a tap, in a room it stays on the server until the riddle closes.

   Each riddle: e (the emoji), a (the answer), alt (other spellings or names
   that count), c (its kind). Answers are compared through normaliseClue, so
   أ/ا, ة/ه, "ال" and spaces don't matter - alt is for genuinely different
   names (فروزن / ملكة الثلج), not spellings. Only things that don't date:
   classics, proverbs, dishes, places.
   ========================================================================= */
const EMOJI_RIDDLES = {
  ar: [
    // --- أفلام ومسلسلات مصرية ---
    { e: '🍯⚫', a: 'عسل أسود', c: 'أفلام ومسلسلات مصرية' },
    { e: '🐘🔵', a: 'الفيل الأزرق', c: 'أفلام ومسلسلات مصرية' },
    { e: '🏫👨‍🏫', a: 'الناظر', c: 'أفلام ومسلسلات مصرية' },
    { e: '💡🕺', a: 'اللمبي', c: 'أفلام ومسلسلات مصرية' },
    { e: '🧑🇳🇱', a: 'همام في أمستردام', alt: ['همام فى امستردام'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🌙🌙🌙', a: 'سهر الليالي', c: 'أفلام ومسلسلات مصرية' },
    { e: '🏢🏙️', a: 'عمارة يعقوبيان', c: 'أفلام ومسلسلات مصرية' },
    { e: '🏝️🌊', a: 'الجزيرة', c: 'أفلام ومسلسلات مصرية' },
    { e: '👵😱', a: 'تيتة رهيبة', c: 'أفلام ومسلسلات مصرية' },
    { e: '🧕🎓🇺🇸', a: 'صعيدي في الجامعة الأمريكية', alt: ['صعيدى فى الجامعة الامريكية'], c: 'أفلام ومسلسلات مصرية' },
    { e: '💣🍢', a: 'الإرهاب والكباب', c: 'أفلام ومسلسلات مصرية' },
    { e: '🎩🚪🧹', a: 'البيه البواب', c: 'أفلام ومسلسلات مصرية' },
    { e: '☀️🐴🏜️', a: 'شمس الزناتي', alt: ['شمس الزناتى'], c: 'أفلام ومسلسلات مصرية' },
    { e: '⚪🥊🔪', a: 'إبراهيم الأبيض', c: 'أفلام ومسلسلات مصرية' },
    { e: '🌍⚔️3️⃣', a: 'الحرب العالمية الثالثة', c: 'أفلام ومسلسلات مصرية' },
    { e: '🐟🥛🌴', a: 'سمك لبن تمر هندي', alt: ['سمك لبن تمر هندى'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🏫😈📚', a: 'مدرسة المشاغبين', c: 'أفلام ومسلسلات مصرية' },
    { e: '👀🙈', a: 'شاهد ماشافش حاجة', alt: ['شاهد ما شافش حاجة'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🦁🐱🐱🐱🐱', a: 'أسد وأربع قطط', alt: ['اسد و اربع قطط'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🥷🐕🐕', a: 'اللص والكلاب', c: 'أفلام ومسلسلات مصرية' },
    { e: '🇨🇳🥋🇪🇬', a: 'زكي شان', alt: ['زكى شان'], c: 'أفلام ومسلسلات مصرية' },
    { e: '👮⛺🪖', a: 'عسكر في المعسكر', alt: ['عسكر فى المعسكر'], c: 'أفلام ومسلسلات مصرية' },
    { e: '👬👨‍👦', a: 'أولاد العم', c: 'أفلام ومسلسلات مصرية' },
    { e: '👕❌🍔⚖️', a: 'إكس لارج', alt: ['اكس لارج', 'xl'], c: 'أفلام ومسلسلات مصرية' },
    { e: '💰📜🏺', a: 'الكنز', c: 'أفلام ومسلسلات مصرية' },
    { e: '🐝🏠🔫', a: 'الخلية', c: 'أفلام ومسلسلات مصرية' },
    { e: '👦👦👦💵', a: 'ولاد رزق', alt: ['اولاد رزق'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🛣️🪖🇪🇬', a: 'الممر', c: 'أفلام ومسلسلات مصرية' },
    { e: '🗡️🧞🇪🇬', a: 'كيرة والجن', alt: ['كيره والجن'], c: 'أفلام ومسلسلات مصرية' },
    { e: '7️⃣❤️', a: 'هيبتا', c: 'أفلام ومسلسلات مصرية' },
    { e: '🏖️😎🕶️', a: 'صايع بحر', c: 'أفلام ومسلسلات مصرية' },
    { e: '👨‍⚖️💔👰', a: 'محامي خلع', alt: ['محامى خلع'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🤵👮💍', a: 'عريس من جهة أمنية', c: 'أفلام ومسلسلات مصرية' },
    { e: '🎓👮📚', a: 'الباشا تلميذ', c: 'أفلام ومسلسلات مصرية' },
    { e: '🌍🦁🐘🐒', a: 'أفريكانو', c: 'أفلام ومسلسلات مصرية' },
    { e: '🫘🇨🇳', a: 'فول الصين العظيم', c: 'أفلام ومسلسلات مصرية' },
    { e: '🐦👉😤', a: 'طير إنت', alt: ['طير انت'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🚫🔙🚫🏳️', a: 'لا تراجع ولا استسلام', c: 'أفلام ومسلسلات مصرية' },
    { e: '👦👦👦⏳', a: 'سمير وشهير وبهير', c: 'أفلام ومسلسلات مصرية' },
    { e: '👮‍♂️👩‍💼💑', a: 'تيمور وشفيقة', alt: ['تيمور و شفيقة'], c: 'أفلام ومسلسلات مصرية' },
    { e: '3️⃣👨👨👨', a: 'كده رضا', c: 'أفلام ومسلسلات مصرية' },
    { e: '🙏🔔😵', a: 'آسف على الإزعاج', c: 'أفلام ومسلسلات مصرية' },
    { e: '💍🎊💵', a: 'الفرح', c: 'أفلام ومسلسلات مصرية' },
    { e: '🎩🌾👨', a: 'الكبير أوي', alt: ['الكبير اوى'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🌙🏮🍽️', a: 'رمضان كريم', c: 'أفلام ومسلسلات مصرية' },
    { e: '🌃🏘️🎩', a: 'ليالي الحلمية', alt: ['ليالى الحلمية'], c: 'أفلام ومسلسلات مصرية' },
    { e: '🕵️🇪🇬🇮🇱', a: 'رأفت الهجان', c: 'أفلام ومسلسلات مصرية' },
    { e: '✅🪖', a: 'الاختيار', c: 'أفلام ومسلسلات مصرية' },
    { e: '🍎🔬💥', a: 'لعبة نيوتن', c: 'أفلام ومسلسلات مصرية' },
    { e: '📔👨‍👩‍👧‍👦', a: 'يوميات ونيس', c: 'أفلام ومسلسلات مصرية' },
    { e: '🎩🐇✨', a: 'الساحر', c: 'أفلام ومسلسلات مصرية' },
    { e: '🌱🚜🇪🇬', a: 'الأرض', c: 'أفلام ومسلسلات مصرية' },

    // --- أفلام أجنبية ---
    { e: '🚢🧊💔', a: 'تايتانيك', alt: ['titanic', 'تيتانيك'], c: 'أفلام أجنبية' },
    { e: '⚡👓🧙‍♂️', a: 'هاري بوتر', alt: ['harry potter', 'هارى بوتر'], c: 'أفلام أجنبية' },
    { e: '🏠👦🎄🥷', a: 'وحدي في المنزل', alt: ['home alone', 'هوم الون', 'وحيدا في المنزل'], c: 'أفلام أجنبية' },
    { e: '🦈🏖️😱', a: 'الفك المفترس', alt: ['jaws', 'جوز'], c: 'أفلام أجنبية' },
    { e: '🏴‍☠️⚓🌊', a: 'قراصنة الكاريبي', alt: ['pirates of the caribbean', 'بايرتس اوف ذا كاريبيان'], c: 'أفلام أجنبية' },
    { e: '🔵👽🌳', a: 'أفاتار', alt: ['avatar'], c: 'أفلام أجنبية' },
    { e: '🦖🌴🚙', a: 'حديقة الديناصورات', alt: ['jurassic park', 'جوراسيك بارك'], c: 'أفلام أجنبية' },
    { e: '🕶️💣🏃', a: 'مهمة مستحيلة', alt: ['mission impossible', 'ميشن امبوسيبل'], c: 'أفلام أجنبية' },
    { e: '🚗💨😡', a: 'سريع وغاضب', alt: ['fast and furious', 'فاست اند فيوريس', 'فاست اند فيورس'], c: 'أفلام أجنبية' },
    { e: '🥊🇺🇸🏃', a: 'روكي', alt: ['rocky', 'روكى'], c: 'أفلام أجنبية' },
    { e: '🕷️🧑🕸️', a: 'سبايدرمان', alt: ['spider man', 'spiderman', 'الرجل العنكبوت'], c: 'أفلام أجنبية' },
    { e: '🦇🧑🌃', a: 'باتمان', alt: ['batman', 'الرجل الوطواط'], c: 'أفلام أجنبية' },
    { e: '🦸‍♂️🔵🔴💪', a: 'سوبرمان', alt: ['superman'], c: 'أفلام أجنبية' },
    { e: '🤖❤️🦾', a: 'الرجل الحديدي', alt: ['iron man', 'ايرون مان', 'أيرون مان'], c: 'أفلام أجنبية' },
    { e: '🔨⚡🇳🇴', a: 'ثور', alt: ['thor'], c: 'أفلام أجنبية' },
    { e: '🐍💍🧙‍♂️🌋', a: 'سيد الخواتم', alt: ['lord of the rings', 'لورد اوف ذا رينجز'], c: 'أفلام أجنبية' },
    { e: '🤖🚗🔄', a: 'ترانسفورمرز', alt: ['transformers', 'المتحولون'], c: 'أفلام أجنبية' },
    { e: '👽📞🏠', a: 'إي تي', alt: ['e.t.', 'et', 'اي تي'], c: 'أفلام أجنبية' },
    { e: '🦍🏙️🗽', a: 'كينج كونج', alt: ['king kong', 'كينغ كونغ'], c: 'أفلام أجنبية' },
    { e: '💚💪😡', a: 'هالك', alt: ['hulk', 'الرجل الأخضر'], c: 'أفلام أجنبية' },
    { e: '🛡️⭐🇺🇸', a: 'كابتن أمريكا', alt: ['captain america', 'كابتن امريكا'], c: 'أفلام أجنبية' },
    { e: '🏍️🍕🥋🐢', a: 'سلاحف النينجا', alt: ['ninja turtles', 'teenage mutant ninja turtles'], c: 'أفلام أجنبية' },
    { e: '🎩🐭🇺🇸👋', a: 'ميكي ماوس', alt: ['mickey mouse'], c: 'أفلام أجنبية' },
    { e: '🧑‍🚀🌌🚀🪐', a: 'إنترستيلر', alt: ['interstellar', 'بين النجوم'], c: 'أفلام أجنبية' },
    { e: '🍫🏭🎩', a: 'تشارلي ومصنع الشوكولاتة', alt: ['charlie and the chocolate factory', 'ويلي وونكا', 'شارلي ومصنع الشوكولاتة'], c: 'أفلام أجنبية' },

    // --- أفلام كرتون ---
    { e: '🦁👑🌅', a: 'الأسد الملك', alt: ['the lion king', 'ذا لايون كينج', 'lion king'], c: 'أفلام كرتون' },
    { e: '❄️👸⛄', a: 'فروزن', alt: ['frozen', 'ملكة الثلج'], c: 'أفلام كرتون' },
    { e: '🔍🐠🌊', a: 'البحث عن نيمو', alt: ['finding nemo', 'نيمو'], c: 'أفلام كرتون' },
    { e: '🧸🤠📖', a: 'حكاية لعبة', alt: ['toy story', 'توي ستوري', 'توى ستورى'], c: 'أفلام كرتون' },
    { e: '🚗🏁⚡', a: 'سيارات', alt: ['cars', 'كارز'], c: 'أفلام كرتون' },
    { e: '🎈🎈🏠👴', a: 'فوق', alt: ['up', 'اب'], c: 'أفلام كرتون' },
    { e: '🐀👨‍🍳🇫🇷', a: 'راتاتوي', alt: ['ratatouille', 'راتاتوى'], c: 'أفلام كرتون' },
    { e: '❄️⚪👸🍎', a: 'بياض الثلج', alt: ['snow white', 'سنو وايت', 'بيضاء الثلج'], c: 'أفلام كرتون' },
    { e: '👠🎃🕛', a: 'سندريلا', alt: ['cinderella'], c: 'أفلام كرتون' },
    { e: '🧞‍♂️🪔🧕', a: 'علاء الدين', alt: ['aladdin', 'علاء الدين والمصباح السحري'], c: 'أفلام كرتون' },
    { e: '🌊⛵🐔🌺', a: 'موانا', alt: ['moana'], c: 'أفلام كرتون' },
    { e: '💀🎸🇲🇽', a: 'كوكو', alt: ['coco'], c: 'أفلام كرتون' },
    { e: '😀😢😡😱🤢', a: 'قلبا وقالبا', alt: ['inside out', 'انسايد اوت', 'قلبًا وقالبًا'], c: 'أفلام كرتون' },
    { e: '🐼🥋🍜', a: 'كونغ فو باندا', alt: ['kung fu panda', 'كونج فو باندا'], c: 'أفلام كرتون' },
    { e: '👹💚🐴', a: 'شريك', alt: ['shrek', 'شرك'], c: 'أفلام كرتون' },
    { e: '🦊🐰🏙️👮', a: 'زوتوبيا', alt: ['zootopia'], c: 'أفلام كرتون' },
    { e: '🦁🦓🦒🦛🏝️', a: 'مدغشقر', alt: ['madagascar'], c: 'أفلام كرتون' },
    { e: '🧊🦣🐿️🌰', a: 'العصر الجليدي', alt: ['ice age', 'ايس ايدج', 'العصر الجليدى'], c: 'أفلام كرتون' },
    { e: '💛👓🍌', a: 'المينيونز', alt: ['minions', 'أنا الحقير', 'despicable me', 'مينيونز'], c: 'أفلام كرتون' },
    { e: '🌴📖🐯🐻👦', a: 'كتاب الأدغال', alt: ['the jungle book', 'jungle book', 'ماوكلي', 'كتاب الغابة'], c: 'أفلام كرتون' },
    { e: '🌹👸🐗🕯️', a: 'الجميلة والوحش', alt: ['beauty and the beast'], c: 'أفلام كرتون' },
    { e: '🌴🦍👦', a: 'طرزان', alt: ['tarzan'], c: 'أفلام كرتون' },
    { e: '👃🪵🧚', a: 'بينوكيو', alt: ['pinocchio'], c: 'أفلام كرتون' },
    { e: '🧜‍♀️🐠🦀', a: 'الحورية الصغيرة', alt: ['the little mermaid', 'حورية البحر', 'ارييل', 'آريل'], c: 'أفلام كرتون' },
    { e: '🐱🐭🏠', a: 'توم وجيري', alt: ['tom and jerry', 'توم و جيري', 'توم وجيرى'], c: 'أفلام كرتون' },
    { e: '🧽🍍🌊', a: 'سبونج بوب', alt: ['spongebob', 'سبونش بوب'], c: 'أفلام كرتون' },
    { e: '🔍👓👦🔬', a: 'المحقق كونان', alt: ['detective conan', 'كونان'], c: 'أفلام كرتون' },
    { e: '⚡🐭🔴⚪', a: 'بوكيمون', alt: ['pokemon', 'بيكاتشو'], c: 'أفلام كرتون' },
    { e: '🎒🗺️👧🐒', a: 'دورا', alt: ['dora', 'dora the explorer'], c: 'أفلام كرتون' },
    { e: '🧑⌚👽', a: 'بن تن', alt: ['ben 10', 'ben ten', 'بن 10'], c: 'أفلام كرتون' },
    { e: '⚽👦🏆🇯🇵', a: 'كابتن ماجد', alt: ['captain majid', 'كابتن تسوباسا'], c: 'أفلام كرتون' },
    { e: '🏎️🌵🐦💨', a: 'الطريق السريع', alt: ['road runner', 'رود رانر', 'المتسابق'], c: 'أفلام كرتون' },
    { e: '🐰🥕🤠', a: 'باغز باني', alt: ['bugs bunny', 'بجز باني', 'الأرنب باغز'], c: 'أفلام كرتون' },
    { e: '🐦🐦👵🐱', a: 'تويتي', alt: ['tweety', 'تويتى'], c: 'أفلام كرتون' },
    { e: '🐉👦🇯🇵💥', a: 'دراغون بول', alt: ['dragon ball', 'دراجون بول'], c: 'أفلام كرتون' },
    { e: '🍩👨🟡🇺🇸', a: 'عائلة سمبسون', alt: ['the simpsons', 'simpsons', 'سيمبسون', 'ذا سمبسونز'], c: 'أفلام كرتون' },

    // --- أمثال ---
    { e: '🐒👁️👩🦌', a: 'القرد في عين أمه غزال', alt: ['القرد فى عين امه غزال'], c: 'أمثال' },
    { e: '🐦🐦🐦🤝', a: 'الطيور على أشكالها تقع', c: 'أمثال' },
    { e: '🐒💰👀', a: 'يا واخد القرد على ماله', alt: ['ياواخد القرد على ماله'], c: 'أمثال' },
    { e: '🧑‍🤝‍🧑➡️🏠', a: 'الجار قبل الدار', c: 'أمثال' },
    { e: '🤕✋🤫', a: 'اللي على راسه بطحة يحسس عليها', alt: ['اللى على راسه بطحة يحسس عليها'], c: 'أمثال' },
    { e: '⏮️💀', a: 'اللي فات مات', alt: ['اللى فات مات'], c: 'أمثال' },
    { e: '🦢🐣🏊', a: 'ابن الوز عوام', c: 'أمثال' },
    { e: '😌🔑🚪', a: 'الصبر مفتاح الفرج', c: 'أمثال' },
    { e: '🍞➡️👨‍🍳', a: 'ادي العيش لخبازه', alt: ['ادى العيش لخبازه', 'اعطي العيش لخبازه'], c: 'أمثال' },
    { e: '🚪💨🛑😌', a: 'الباب اللي يجيلك منه الريح سده واستريح', alt: ['الباب اللى يجيلك منه الريح سده و استريح'], c: 'أمثال' },
    { e: '👊😭🏃😠', a: 'ضربني وبكى وسبقني واشتكى', alt: ['ضربنى وبكى وسبقنى واشتكى', 'ضربني وبكى سبقني واشتكى'], c: 'أمثال' },
    { e: '🧱👂👂', a: 'الحيطان ليها ودان', alt: ['الحيطان لها ودان'], c: 'أمثال' },
    { e: '🚶🎵😈', a: 'ابعد عن الشر وغنيله', alt: ['ابعد عن الشر و غنيله'], c: 'أمثال' },
    { e: '🪙⚪📅⚫', a: 'القرش الأبيض ينفع في اليوم الأسود', alt: ['القرش الابيض ينفع فى اليوم الاسود'], c: 'أمثال' },
    { e: '🛏️📏🦵', a: 'على قد لحافك مد رجليك', alt: ['على اد لحافك مد رجليك', 'على قد لحافك'], c: 'أمثال' },
    { e: '😋💭🍞🏪', a: 'الجعان يحلم بسوق العيش', alt: ['الجعان بيحلم بسوق العيش'], c: 'أمثال' },
    { e: '🎺🏘️🙉', a: 'زمار الحي ما يطربش', alt: ['زمار الحي ميطربش', 'زمار الحي ما بيطربش'], c: 'أمثال' },
    { e: '☀️🥅🙈', a: 'الشمس ما تتغطاش بغربال', alt: ['الشمس متتغطاش بغربال'], c: 'أمثال' },
    { e: '🐦✋🔟🌳', a: 'عصفور في اليد ولا عشرة على الشجرة', alt: ['عصفور فى اليد ولا عشرة على الشجرة', 'عصفور في اليد خير من عشرة على الشجرة'], c: 'أمثال' },
    { e: '🧵🤥📏', a: 'حبل الكدب قصير', alt: ['حبل الكذب قصير'], c: 'أمثال' },
    { e: '🚫❤️', a: 'كل ممنوع مرغوب', c: 'أمثال' },
    { e: '🐱🚶🐭🎉', a: 'إن غاب القط العب يا فار', alt: ['ان غاب القط العب يا فار', 'غاب القط العب يا فار'], c: 'أمثال' },
    { e: '🎒🐍🧙', a: 'ياما في الجراب يا حاوي', alt: ['ياما فى الجراب يا حاوى'], c: 'أمثال' },
    { e: '💵🚶🥷', a: 'المال السايب يعلم السرقة', c: 'أمثال' },
    { e: '🧼🧼🧼', a: 'كله عند العرب صابون', c: 'أمثال' },
    { e: '✉️👀📬', a: 'الجواب بيبان من عنوانه', alt: ['الجواب بيبان من عنوانه'], c: 'أمثال' },
    { e: '👗💍👰', a: 'لبس البوصة تبقى عروسة', c: 'أمثال' },
    { e: '😄🌍😄', a: 'اضحك للدنيا تضحكلك', alt: ['اضحك للدنيا تضحك لك'], c: 'أمثال' },
    { e: '🌸➡️🌸', a: 'كل شيخ وله طريقة', alt: ['كل شيخ وليه طريقة'], c: 'أمثال' },
    { e: '👁️🚫🤨', a: 'العين ما تعلاش عن الحاجب', alt: ['العين متعلاش عن الحاجب'], c: 'أمثال' },
    { e: '🚶➡️😕👿', a: 'امشي عدل يحتار عدوك فيك', alt: ['امشى عدل يحتار عدوك فيك'], c: 'أمثال' },
    { e: '🤲🙂🔙', a: 'الجود من الموجود', c: 'أمثال' },
    { e: '🐫👀🐫', a: 'الجمل ما يشوفش عوجة رقبته', alt: ['الجمل ميشوفش عوجة رقبته', 'الجمل ما يشوفش عوجت رقبته'], c: 'أمثال' },
    { e: '🍲🥄👀🔥', a: 'اللي ايده في المية مش زي اللي ايده في النار', alt: ['اللى ايده فى المية مش زى اللى ايده فى النار'], c: 'أمثال' },
    { e: '🥚📅🐔⏭️', a: 'بيضة النهاردة ولا فرخة بكرة', alt: ['بيضة النهارده ولا فرخة بكره', 'بيضة النهاردة أحسن من فرخة بكرة'], c: 'أمثال' },

    // --- أكلات ---
    { e: '🍝🍚🧅🍅🫘', a: 'كشري', alt: ['كشرى', 'كوشري'], c: 'أكلات' },
    { e: '🌿🐔🍚', a: 'ملوخية', alt: ['ملوخية بالفراخ'], c: 'أكلات' },
    { e: '🫘🍞🌅', a: 'فول', alt: ['فول مدمس', 'فول وطعمية'], c: 'أكلات' },
    { e: '🟢🧆🍞', a: 'طعمية', alt: ['فلافل'], c: 'أكلات' },
    { e: '🍢🔥🥩', a: 'كباب', alt: ['كباب وكفتة'], c: 'أكلات' },
    { e: '🥙🌯🍗', a: 'شاورما', alt: ['شاورمة'], c: 'أكلات' },
    { e: '🧀🍯🧵', a: 'كنافة', alt: ['كنافة بالجبنة', 'كنافه'], c: 'أكلات' },
    { e: '👩🍮🥛', a: 'أم علي', alt: ['ام على'], c: 'أكلات' },
    { e: '🟨🍯🥥', a: 'بسبوسة', alt: ['بسبوسه'], c: 'أكلات' },
    { e: '🐟🍚🧅🍋', a: 'صيادية', alt: ['صيادية سمك', 'سمك صيادية'], c: 'أكلات' },
    { e: '🍆🍅🧄', a: 'مسقعة', alt: ['مسقعه', 'مسأعة'], c: 'أكلات' },
    { e: '🍃🍚🍋', a: 'محشي ورق عنب', alt: ['ورق عنب', 'محشى ورق عنب'], c: 'أكلات' },
    { e: '🍞🍚🥩🍅🧄', a: 'فتة', alt: ['فته'], c: 'أكلات' },
    { e: '🍳🥩🌶️', a: 'بيض بالبسطرمة', alt: ['بسطرمة بالبيض'], c: 'أكلات' },
    { e: '🥞🧈🍯', a: 'فطير مشلتت', alt: ['فطير', 'فطيرة'], c: 'أكلات' },
    { e: '🍕🇮🇹🧀', a: 'بيتزا', alt: ['بيتزا'], c: 'أكلات' },
    { e: '🍔🍟🥤', a: 'برجر', alt: ['برغر', 'هامبرجر', 'همبرجر'], c: 'أكلات' },
    { e: '🍣🇯🇵🐟', a: 'سوشي', alt: ['سوشى'], c: 'أكلات' },
    { e: '🥐🇫🇷☕', a: 'كرواسون', alt: ['كرواسان'], c: 'أكلات' },
    { e: '🌮🇲🇽🌶️', a: 'تاكو', alt: ['تاكوس'], c: 'أكلات' },
    { e: '🐦🍚🥜', a: 'حمام محشي', alt: ['حمام', 'حمام محشى'], c: 'أكلات' },
    { e: '🍝🧀🥛🔥', a: 'مكرونة بشاميل', alt: ['مكرونة بالبشاميل', 'مكرونه بشاميل'], c: 'أكلات' },
    { e: '🍚🥛🍮❄️', a: 'رز بلبن', alt: ['ارز باللبن', 'رز باللبن', 'أرز بلبن'], c: 'أكلات' },
    { e: '🍠🔥🚲', a: 'بطاطا', alt: ['بطاطا مشوية'], c: 'أكلات' },
    { e: '🌽🔥🏖️', a: 'ذرة مشوي', alt: ['دره مشوى', 'ذرة مشوية', 'دره'], c: 'أكلات' },

    // --- بلاد ومدن ---
    { e: '🗼🥐🇫🇷', a: 'باريس', alt: ['paris'], c: 'بلاد ومدن' },
    { e: '🗽🍎🏙️', a: 'نيويورك', alt: ['new york'], c: 'بلاد ومدن' },
    { e: '🔺🔺🔺🐪🐫', a: 'الجيزة', alt: ['الاهرامات', 'الهرم', 'giza'], c: 'بلاد ومدن' },
    { e: '⚓📚🌊🐟', a: 'الإسكندرية', alt: ['اسكندرية', 'alexandria'], c: 'بلاد ومدن' },
    { e: '🕋🕌🙏', a: 'مكة', alt: ['مكة المكرمة', 'mecca'], c: 'بلاد ومدن' },
    { e: '🎡👑☕🇬🇧', a: 'لندن', alt: ['london'], c: 'بلاد ومدن' },
    { e: '🍕🏛️⛲🇮🇹', a: 'روما', alt: ['rome', 'روما'], c: 'بلاد ومدن' },
    { e: '🏔️🧀⌚🍫', a: 'سويسرا', alt: ['switzerland'], c: 'بلاد ومدن' },
    { e: '🐨🦘🏄', a: 'أستراليا', alt: ['australia', 'استراليا'], c: 'بلاد ومدن' },
    { e: '🍁🏒❄️', a: 'كندا', alt: ['canada'], c: 'بلاد ومدن' },
    { e: '🗻🍣🌸', a: 'اليابان', alt: ['japan'], c: 'بلاد ومدن' },
    { e: '🐼🥢🏯🐉', a: 'الصين', alt: ['china'], c: 'بلاد ومدن' },
    { e: '🌷🚲🧀', a: 'هولندا', alt: ['netherlands', 'holland'], c: 'بلاد ومدن' },
    { e: '🌵🌮🎉', a: 'المكسيك', alt: ['mexico'], c: 'بلاد ومدن' },
    { e: '🐧🧊❄️', a: 'القطب الجنوبي', alt: ['انتاركتيكا', 'antarctica', 'القطب الجنوبى'], c: 'بلاد ومدن' },
    { e: '⚽🏖️🎭🇧🇷', a: 'البرازيل', alt: ['brazil'], c: 'بلاد ومدن' },
    { e: '🏰🐭🎢', a: 'ديزني لاند', alt: ['disneyland', 'ديزنى لاند', 'ديزني'], c: 'بلاد ومدن' },
    { e: '🏙️🕌🌉🇹🇷', a: 'إسطنبول', alt: ['istanbul', 'اسطنبول', 'استانبول'], c: 'بلاد ومدن' },
    { e: '🏙️🏗️🌴🇦🇪', a: 'دبي', alt: ['dubai', 'دبى'], c: 'بلاد ومدن' },
    { e: '🏛️🇬🇷🫒', a: 'أثينا', alt: ['athens', 'اثينا', 'اليونان'], c: 'بلاد ومدن' },
    { e: '🌉🚋🌁', a: 'سان فرانسيسكو', alt: ['san francisco'], c: 'بلاد ومدن' },
    { e: '🐘🕌🌶️', a: 'الهند', alt: ['india'], c: 'بلاد ومدن' },
    { e: '🏜️🐪🌴🔥🇪🇬', a: 'أسوان', alt: ['aswan', 'اسوان'], c: 'بلاد ومدن' },
    { e: '🤿🐠⛵🌞', a: 'شرم الشيخ', alt: ['sharm el sheikh', 'شرم'], c: 'بلاد ومدن' },
    { e: '⛵🕌🌊🏛️', a: 'الأقصر', alt: ['luxor', 'الاقصر'], c: 'بلاد ومدن' }
  ],

  en: [
    // --- Movies ---
    { e: '🚢🧊💔', a: 'Titanic', c: 'Movies' },
    { e: '⚡👓🧙‍♂️', a: 'Harry Potter', c: 'Movies' },
    { e: '🏠👦🎄🥷', a: 'Home Alone', c: 'Movies' },
    { e: '🦈🏖️😱', a: 'Jaws', c: 'Movies' },
    { e: '🏴‍☠️⚓🌊', a: 'Pirates of the Caribbean', alt: ['pirates of the carribean'], c: 'Movies' },
    { e: '🔵👽🌳', a: 'Avatar', c: 'Movies' },
    { e: '🦖🌴🚙', a: 'Jurassic Park', alt: ['jurassic world'], c: 'Movies' },
    { e: '🕶️💣🏃', a: 'Mission Impossible', c: 'Movies' },
    { e: '🚗💨😡', a: 'Fast and Furious', alt: ['fast & furious', 'the fast and the furious'], c: 'Movies' },
    { e: '🥊🇺🇸🏃', a: 'Rocky', c: 'Movies' },
    { e: '🕷️🧑🕸️', a: 'Spider-Man', alt: ['spiderman', 'spider man'], c: 'Movies' },
    { e: '🦇🧑🌃', a: 'Batman', c: 'Movies' },
    { e: '🦸‍♂️🔵🔴💪', a: 'Superman', c: 'Movies' },
    { e: '🤖❤️🦾', a: 'Iron Man', alt: ['ironman'], c: 'Movies' },
    { e: '🔨⚡🇳🇴', a: 'Thor', c: 'Movies' },
    { e: '💍🧙‍♂️🌋', a: 'The Lord of the Rings', alt: ['lord of the rings'], c: 'Movies' },
    { e: '🤖🚗🔄', a: 'Transformers', c: 'Movies' },
    { e: '👽📞🏠', a: 'E.T.', alt: ['et', 'e t', 'e.t'], c: 'Movies' },
    { e: '🦍🏙️🗽', a: 'King Kong', c: 'Movies' },
    { e: '🛡️⭐🇺🇸', a: 'Captain America', c: 'Movies' },
    { e: '🍕🥋🐢', a: 'Ninja Turtles', alt: ['teenage mutant ninja turtles', 'tmnt'], c: 'Movies' },
    { e: '🧑‍🚀🌌🚀🪐', a: 'Interstellar', c: 'Movies' },
    { e: '🦁🐯🐻🚣🌊', a: 'Life of Pi', c: 'Movies' },
    { e: '🌪️🏠👧🐕🌈', a: 'The Wizard of Oz', alt: ['wizard of oz'], c: 'Movies' },
    { e: '🧑🏃🍫🪶', a: 'Forrest Gump', c: 'Movies' },
    { e: '🍫🏭🎩', a: 'Charlie and the Chocolate Factory', alt: ['willy wonka', 'charlie and the chocolate factory'], c: 'Movies' },
    { e: '🐝🎬👩', a: 'Bee Movie', c: 'Movies' },
    { e: '🌧️🕺☂️', a: 'Singing in the Rain', alt: ["singin' in the rain", 'singin in the rain'], c: 'Movies' },
    { e: '🔫🍸🇬🇧', a: 'James Bond', alt: ['007', 'bond'], c: 'Movies' },
    { e: '🏃‍♂️⌛🚗⚡', a: 'Back to the Future', c: 'Movies' },
    { e: '👻🚫🔫🚐', a: 'Ghostbusters', c: 'Movies' },
    { e: '🐕🌨️🛷', a: 'Eight Below', alt: ['8 below'], c: 'Movies' },
    { e: '👑🎤🇬🇧🗣️', a: "The King's Speech", alt: ['kings speech'], c: 'Movies' },
    { e: '🎩🎪🦁🎶', a: 'The Greatest Showman', alt: ['greatest showman'], c: 'Movies' },
    { e: '🎹🌃💃🕺', a: 'La La Land', alt: ['lalaland'], c: 'Movies' },

    // --- Animated films ---
    { e: '🦁👑🌅', a: 'The Lion King', alt: ['lion king'], c: 'Animated films' },
    { e: '❄️👸⛄', a: 'Frozen', c: 'Animated films' },
    { e: '🔍🐠🌊', a: 'Finding Nemo', alt: ['nemo'], c: 'Animated films' },
    { e: '🧸🤠📖', a: 'Toy Story', c: 'Animated films' },
    { e: '🚗🏁⚡', a: 'Cars', c: 'Animated films' },
    { e: '🎈🎈🏠👴', a: 'Up', c: 'Animated films' },
    { e: '🐀👨‍🍳🇫🇷', a: 'Ratatouille', c: 'Animated films' },
    { e: '❄️⚪👸🍎', a: 'Snow White', alt: ['snow white and the seven dwarfs'], c: 'Animated films' },
    { e: '👠🎃🕛', a: 'Cinderella', c: 'Animated films' },
    { e: '🧞‍♂️🪔🧕', a: 'Aladdin', c: 'Animated films' },
    { e: '🌊⛵🐔🌺', a: 'Moana', c: 'Animated films' },
    { e: '💀🎸🇲🇽', a: 'Coco', c: 'Animated films' },
    { e: '😀😢😡😱🤢', a: 'Inside Out', c: 'Animated films' },
    { e: '🐼🥋🍜', a: 'Kung Fu Panda', c: 'Animated films' },
    { e: '👹💚🐴', a: 'Shrek', c: 'Animated films' },
    { e: '🦊🐰🏙️👮', a: 'Zootopia', alt: ['zootropolis'], c: 'Animated films' },
    { e: '🦁🦓🦒🦛🏝️', a: 'Madagascar', c: 'Animated films' },
    { e: '🧊🦣🐿️🌰', a: 'Ice Age', c: 'Animated films' },
    { e: '💛👓🍌', a: 'Minions', alt: ['despicable me'], c: 'Animated films' },
    { e: '🌴📖🐯🐻👦', a: 'The Jungle Book', alt: ['jungle book'], c: 'Animated films' },
    { e: '🌹👸🐗🕯️', a: 'Beauty and the Beast', c: 'Animated films' },
    { e: '🌴🦍👦', a: 'Tarzan', c: 'Animated films' },
    { e: '👃🪵🧚', a: 'Pinocchio', c: 'Animated films' },
    { e: '🧜‍♀️🐠🦀', a: 'The Little Mermaid', alt: ['little mermaid', 'ariel'], c: 'Animated films' },
    { e: '🐉👦🐲🏝️', a: 'How to Train Your Dragon', c: 'Animated films' },
    { e: '🐘👂✈️🎪', a: 'Dumbo', c: 'Animated films' },
    { e: '🦌🌲🐰', a: 'Bambi', c: 'Animated films' },
    { e: '🐕🐕🍝🌙', a: 'Lady and the Tramp', c: 'Animated films' },
    { e: '🐱🐭🏠', a: 'Tom and Jerry', alt: ['tom & jerry'], c: 'Animated films' },
    { e: '🧽🍍🌊', a: 'SpongeBob', alt: ['spongebob squarepants', 'sponge bob'], c: 'Animated films' },
    { e: '⚡🐭🔴⚪', a: 'Pokemon', alt: ['pokémon', 'pikachu'], c: 'Animated films' },
    { e: '🍩👨🟡🇺🇸', a: 'The Simpsons', alt: ['simpsons'], c: 'Animated films' },
    { e: '🐰🥕🤠', a: 'Bugs Bunny', alt: ['looney tunes'], c: 'Animated films' },

    // --- Idioms ---
    { e: '🍰', a: 'Piece of cake', alt: ['a piece of cake'], c: 'Idioms' },
    { e: '🌧️🐱🐶', a: 'Raining cats and dogs', alt: ["it's raining cats and dogs", 'its raining cats and dogs'], c: 'Idioms' },
    { e: '🫘🗣️', a: 'Spill the beans', c: 'Idioms' },
    { e: '❄️🦶', a: 'Cold feet', alt: ['get cold feet', 'to get cold feet'], c: 'Idioms' },
    { e: '⬇️🌦️🤒', a: 'Under the weather', alt: ['feeling under the weather'], c: 'Idioms' },
    { e: '1️⃣🔵🌙', a: 'Once in a blue moon', c: 'Idioms' },
    { e: '🌅🐦🪱', a: 'The early bird catches the worm', alt: ['early bird catches the worm', 'early bird gets the worm', 'the early bird gets the worm'], c: 'Idioms' },
    { e: '🐦🐦🪨', a: 'Kill two birds with one stone', alt: ['two birds one stone', 'two birds with one stone'], c: 'Idioms' },
    { e: '🎁🎭', a: 'A blessing in disguise', alt: ['blessing in disguise'], c: 'Idioms' },
    { e: '🐷✈️', a: 'When pigs fly', c: 'Idioms' },
    { e: '🐱👜', a: 'Let the cat out of the bag', alt: ['cat out of the bag'], c: 'Idioms' },
    { e: '🎾👉🏟️', a: 'The ball is in your court', alt: ['ball is in your court', 'ball in your court'], c: 'Idioms' },
    { e: '💰💪🦵', a: 'Costs an arm and a leg', alt: ['an arm and a leg', 'arm and a leg', 'cost an arm and a leg'], c: 'Idioms' },
    { e: '🐘🛋️', a: 'The elephant in the room', alt: ['elephant in the room'], c: 'Idioms' },
    { e: '🍏📅👨‍⚕️🚫', a: 'An apple a day keeps the doctor away', alt: ['apple a day keeps the doctor away'], c: 'Idioms' },
    { e: '⏰💵', a: 'Time is money', c: 'Idioms' },
    { e: '🧊💔', a: 'Break the ice', alt: ['breaking the ice'], c: 'Idioms' },
    { e: '🛏️🌹🚫', a: 'No bed of roses', alt: ['not a bed of roses', 'bed of roses'], c: 'Idioms' },
    { e: '🐟🌊➕', a: 'Plenty of fish in the sea', alt: ['there are plenty of fish in the sea', 'more fish in the sea'], c: 'Idioms' },
    { e: '🔥🍳➡️🔥', a: 'Out of the frying pan into the fire', alt: ['out of the frying pan and into the fire', 'frying pan into the fire'], c: 'Idioms' },
    { e: '🤐🦷🦷', a: 'Bite your tongue', alt: ['bite my tongue'], c: 'Idioms' },
    { e: '🐦🐦🪶🤝', a: 'Birds of a feather flock together', alt: ['birds of a feather'], c: 'Idioms' },

    // --- Food ---
    { e: '🍕🇮🇹🧀', a: 'Pizza', c: 'Food' },
    { e: '🍔🍟🥤', a: 'Burger', alt: ['hamburger', 'cheeseburger'], c: 'Food' },
    { e: '🍣🇯🇵🐟', a: 'Sushi', c: 'Food' },
    { e: '🥐🇫🇷☕', a: 'Croissant', c: 'Food' },
    { e: '🌮🇲🇽🌶️', a: 'Tacos', alt: ['taco'], c: 'Food' },
    { e: '🐟🍟🇬🇧', a: 'Fish and chips', alt: ['fish & chips'], c: 'Food' },
    { e: '🌭🇺🇸⚾', a: 'Hot dog', alt: ['hotdog'], c: 'Food' },
    { e: '🥞🍁🧈', a: 'Pancakes', alt: ['pancake'], c: 'Food' },
    { e: '🍝🍅🇮🇹', a: 'Spaghetti', alt: ['pasta', 'spaghetti bolognese'], c: 'Food' },
    { e: '🧆🥙🌿', a: 'Falafel', c: 'Food' },
    { e: '🥙🌯🍗', a: 'Shawarma', alt: ['shawerma'], c: 'Food' },
    { e: '🍚🐔🍛', a: 'Chicken curry', alt: ['curry'], c: 'Food' },
    { e: '🥛🍪🌙', a: 'Milk and cookies', alt: ['cookies and milk'], c: 'Food' },
    { e: '🍦🍒🍫', a: 'Ice cream sundae', alt: ['sundae', 'ice cream'], c: 'Food' },

    // --- Places ---
    { e: '🗼🥐🇫🇷', a: 'Paris', c: 'Places' },
    { e: '🗽🍎🏙️', a: 'New York', alt: ['new york city', 'nyc'], c: 'Places' },
    { e: '🔺🔺🔺🐪', a: 'Giza', alt: ['the pyramids', 'pyramids', 'pyramids of giza'], c: 'Places' },
    { e: '⚓📚🌊🐟', a: 'Alexandria', c: 'Places' },
    { e: '🎡👑☕🇬🇧', a: 'London', c: 'Places' },
    { e: '🍕🏛️⛲🇮🇹', a: 'Rome', c: 'Places' },
    { e: '🏔️🧀⌚🍫', a: 'Switzerland', c: 'Places' },
    { e: '🐨🦘🏄', a: 'Australia', c: 'Places' },
    { e: '🍁🏒❄️', a: 'Canada', c: 'Places' },
    { e: '🗻🍣🌸', a: 'Japan', c: 'Places' },
    { e: '🐼🥢🏯🐉', a: 'China', c: 'Places' },
    { e: '🌷🚲🧀', a: 'The Netherlands', alt: ['netherlands', 'holland'], c: 'Places' },
    { e: '🌵🌮🎉', a: 'Mexico', c: 'Places' },
    { e: '🐧🧊❄️', a: 'Antarctica', alt: ['the south pole', 'south pole'], c: 'Places' },
    { e: '⚽🏖️🎭🇧🇷', a: 'Brazil', c: 'Places' },
    { e: '🏰🐭🎢', a: 'Disneyland', alt: ['disney land', 'disney world', 'disney'], c: 'Places' },
    { e: '🏙️🕌🌉🇹🇷', a: 'Istanbul', c: 'Places' },
    { e: '🏙️🏗️🌴🇦🇪', a: 'Dubai', c: 'Places' },
    { e: '🏛️🇬🇷🫒', a: 'Athens', alt: ['greece'], c: 'Places' },
    { e: '🌉🚋🌁', a: 'San Francisco', c: 'Places' },
    { e: '🐘🕌🌶️', a: 'India', c: 'Places' },
    { e: '🤿🐠⛵🌞', a: 'Sharm El Sheikh', alt: ['sharm', 'sharm el-sheikh'], c: 'Places' },
    { e: '🎰🌃🎲', a: 'Las Vegas', alt: ['vegas'], c: 'Places' },
    { e: '🗿🏝️', a: 'Easter Island', c: 'Places' }
  ]
};
