/* ============================================================================
   PARTY GAME CONTENT
   ----------------------------------------------------------------------------
   Server-side because some of it has to be: a Fibbage question's real answer
   must not reach a client until the votes are in. The rest lives here too so
   every room game draws its content from one place.

   Written for the app's audience — Egyptian/Levantine Arabic as it's actually
   spoken, with an English set that stands on its own rather than being a
   translation.
   ========================================================================= */

/* --- لو خيروك -------------------------------------------------------------
   Two options, both defensible. A pair only works if the room can genuinely
   split on it; anything with an obvious answer is dead weight.
   -------------------------------------------------------------------------- */
const WOULD_YOU_RATHER = {
  ar: [
    ['تعرف ميعاد موتك', 'تعرف طريقة موتك'],
    ['تقدر تطير', 'تبقى خفي'],
    ['تعيش من غير موسيقى', 'تعيش من غير أفلام'],
    ['تاكل نفس الأكلة كل يوم', 'ما تاكلش أكلتك المفضلة تاني'],
    ['تنسى كل ذكرياتك', 'ما تقدرش تعمل ذكريات جديدة'],
    ['تبقى غني ووحيد', 'فقير ومحاط بأصحابك'],
    ['تقرأ أفكار الناس', 'الناس تقرأ أفكارك'],
    ['ترجع 10 سنين لورا', 'تروح 10 سنين قدام'],
    ['تعيش في الصحرا', 'تعيش في القطب'],
    ['تفقد الموبايل شهر', 'تفقد النت شهر'],
    ['تشتغل شغل بتحبه بمرتب قليل', 'شغل بتكرهه بمرتب عالي'],
    ['تبقى مشهور جداً', 'تبقى مجهول تماماً'],
    ['ما تنامش تاني', 'ما تاكلش تاني'],
    ['كل الناس تقول عليك الحقيقة دايماً', 'محدش يقولك الحقيقة أبداً'],
    ['تتكلم كل اللغات', 'تعزف كل الآلات'],
    ['تسافر الفضاء', 'تنزل قاع المحيط'],
    ['تعيش من غير تكييف في الصيف', 'من غير دفاية في الشتا'],
    ['تاكل حلو بس', 'تاكل مالح بس'],
    ['تشتغل 4 أيام 12 ساعة', 'تشتغل 6 أيام 6 ساعات'],
    ['تفقد حاسة الشم', 'تفقد حاسة التذوق'],
    ['يبقى عندك وقت كتير وفلوس قليلة', 'فلوس كتير ووقت قليل'],
    ['تعيش في مدينة زحمة', 'تعيش في قرية بعيدة'],
    ['تبقى دايماً متأخر 10 دقايق', 'دايماً بدري ساعة'],
    ['تنسى أسماء الناس', 'تنسى وشوشهم'],
    ['ما تسمعش موسيقى تاني', 'ما تشوفش البحر تاني'],
    ['تاخد إجازة سنة من غير مرتب', 'تشتغل السنة دي بضعف المرتب'],
    ['تعرف كل حاجة عن الماضي', 'تعرف حاجة واحدة عن المستقبل'],
    ['تبقى أذكى واحد في الأوضة', 'أظرف واحد في الأوضة'],
    ['تاكل من غير ما تشبع', 'تشرب من غير ما ترتوي'],
    ['كل حاجة تشتريها تبقى غالية الضعف', 'ما تشتريش حاجة جديدة أبداً'],
    ['تعيش من غير مرايات', 'تعيش من غير صور'],
    ['تقدر تتكلم مع الحيوانات', 'تتكلم كل لغات البشر'],
    ['تكون بطل في فيلم رعب', 'بطل في فيلم كوميدي'],
    ['يبقى عندك ذاكرة مثالية', 'تقدر تنسى أي حاجة تحب تنساها'],
    ['تمشي على رجلك ساعة كل يوم', 'تقعد في زحمة ساعة كل يوم'],
    ['ما تشوفش أصحابك سنة', 'تشوفهم كل يوم بالإجبار'],
    ['تبقى دايماً حران شوية', 'دايماً بردان شوية'],
    ['تنام 4 ساعات وتصحى نشيط', 'تنام 10 ساعات وتفضل تعبان'],
    ['كل الناس تعرف سرك الوحيد', 'ما تعرفش أسرار حد تاني أبداً'],
    ['تعيش حياتك بالترتيب العكسي', 'تعيش نفس اليوم 100 مرة'],
    ['تختار أكلك بس محدش يختار معاك', 'الناس تختارلك بس تاكلوا سوا'],
    ['تفقد كل صورك القديمة', 'تفقد كل رسايلك القديمة'],
    ['تبقى أطول واحد في العيلة', 'أقصر واحد'],
    ['تشتغل مع أعز أصحابك', 'تشتغل لوحدك من البيت'],
    ['تعرف تطبخ أي حاجة', 'تعرف تصلح أي حاجة'],
    ['الشتا يبقى 9 شهور', 'الصيف يبقى 9 شهور'],
    ['تقعد ساعتين تسمع حد يشتكي', 'تشتكي ساعتين ومحدش سامع'],
    ['ما تستخدمش سوشيال ميديا تاني', 'ما تشوفش تليفزيون تاني'],
    ['تبقى مسؤول عن كل حاجة', 'ما يبقاش ليك رأي في أي حاجة'],
    ['تعيش من غير قهوة', 'تعيش من غير شاي'],
    ['تسافر بالزمن 100 سنة في المستقبل', 'تسافر بالزمن 100 سنة في الماضي'],
    ['تعيش في بيت أحلامك لوحدك', 'تعيش في بيت عادي مع أحسن صحابك'],
    ['ما تضطرش تنام أبداً بدون تعب', 'ما تضطرش تشتغل أبداً وتاخد نفس فلوسك'],
    ['تتحكم في الطقس', 'تتحكم في الوقت'],
    ['تعرف كل لغة في العالم بطلاقة', 'تعرف تعزف كل آلة موسيقية باحتراف'],
    ['تاكل وجبتك المفضلة كل يوم', 'كل يوم تجرّب أكلة جديدة بالحظ'],
    ['تبقى أسرع إنسان على الأرض', 'تبقى أقوى إنسان على الأرض'],
    ['تتنفس تحت المية', 'تقدر تطير في الهوا'],
    ['تعيش في عالم كرتوني يوم', 'تعيش في عالم لعبة فيديو يوم'],
    ['تنسى كل الأفلام اللي شوفتها وتعيدها', 'تقرأ كل الكتب اللي هتنزل في مستقبلك'],
    ['تقعد شهر من غير سكر', 'تقعد شهر من غير شاي وقهوة'],
    ['يبقى عندك زرار يعيد آخر 10 دقايق', 'يبقى عندك زرار يقفز 10 دقايق قدام'],
    ['تقدر تتكلم مع النباتات', 'تقدر تتكلم مع الأجهزة الإلكترونية'],
    ['تعيش على جزيرة استوائية', 'تعيش في كوخ في جبال ثلجية'],
    ['تحضر كل حفلات الفنانين المفضلين ببلاش', 'تسافر كل بلاد العالم طيران مجاني'],
    ['تعرف مين بيتكلم عليك في غيابك', 'تعرف مين بيحبك في السر'],
    ['تفقد القدرة على الغضب تماماً', 'تفقد القدرة على الحزن تماماً'],
    ['تبقى مشهور ومحبوب من كل الناس', 'تبقى غني جداً ومحدش يعرفك'],
    ['تاكل من غير ما تزيد في الوزن', 'تنام 3 ساعات بس كل يوم وتصحى فايق'],
    ['تعيش بدون تكييف طول الصيف', 'تعيش بدون إنترنت طول الشتا'],
    ['تتكلم بصوت عالي دايماً', 'تتكلم بهمس بس ومحدش يسمعك بسهولة'],
    ['تقدر تخفي نفسك متى ما تحب', 'تقدر تمر من الحيطان متى ما تحب'],
    ['ما تسمعش غير أغاني قديمة', 'ما تسمعش غير أغاني جديدة'],
    ['تحل كل ألغاز الكون', 'تعيش حياة هادية وسعيدة بدون أسئلة'],
    ['تخسر كل متابعينك في السوشيال ميديا', 'تخسر كل رسايلك وصورك القديمة'],
    ['تكون دايماً لابس بدلة رسمية', 'تكون دايماً لابس بيجامة البيت'],
    ['تسافر القمر وترجع', 'تنزل لأعمق نقطة في المحيط'],
    ['يكون عندك روبوت يطبخ وينظف', 'يكون عندك سيارة تسوق لوحدها في أي مكان'],
    ['تصحى كل يوم بدري بنشاط', 'تسهر براحتك وتصحى متأخر بدون منبه'],
    ['تعرف حقيقة كل شائعة في العالم', 'تعرف مستقبل شخص واحد بالتفصيل']
  ],
  en: [
    ['Know when you die', 'Know how you die'],
    ['Be able to fly', 'Be invisible'],
    ['Live without music', 'Live without films'],
    ['Eat the same meal daily', 'Never eat your favourite again'],
    ['Forget every memory', 'Never make a new one'],
    ['Be rich and alone', 'Broke and surrounded by friends'],
    ['Read minds', 'Have yours read'],
    ['Go back ten years', 'Skip forward ten years'],
    ['Live in a desert', 'Live in the arctic'],
    ['Lose your phone for a month', 'Lose the internet for a month'],
    ['A job you love, badly paid', 'A job you hate, paid well'],
    ['Be very famous', 'Be completely anonymous'],
    ['Never sleep again', 'Never eat again'],
    ['Everyone always tells you the truth', 'Nobody ever does'],
    ['Speak every language', 'Play every instrument'],
    ['Travel to space', 'Explore the deep ocean'],
    ['No air conditioning in summer', 'No heating in winter'],
    ['Only sweet food', 'Only savoury food'],
    ['Four 12-hour days', 'Six 6-hour days'],
    ['Lose your sense of smell', 'Lose your sense of taste'],
    ['Lots of time, little money', 'Lots of money, no time'],
    ['Live in a crowded city', 'Live in a remote village'],
    ['Always ten minutes late', 'Always an hour early'],
    ['Forget names', 'Forget faces'],
    ['Never hear music again', 'Never see the sea again'],
    ['A year off unpaid', 'This year at double pay'],
    ['Know everything about the past', 'One fact about the future'],
    ['Be the smartest in the room', 'Be the funniest in the room'],
    ['Eat without ever feeling full', 'Drink without ever feeling quenched'],
    ['Everything costs double', 'Never buy anything new again'],
    ['Live without mirrors', 'Live without photographs'],
    ['Talk to animals', 'Speak every human language'],
    ['Star in a horror film', 'Star in a comedy'],
    ['Have perfect memory', 'Be able to forget at will'],
    ['Walk an hour every day', 'Sit in traffic an hour every day'],
    ['Not see your friends for a year', 'Be forced to see them daily'],
    ['Always slightly too hot', 'Always slightly too cold'],
    ['Sleep 4 hours and feel great', 'Sleep 10 and feel awful'],
    ['Everyone knows your one secret', 'You never learn anyone else\'s'],
    ['Live your life in reverse', 'Repeat the same day 100 times'],
    ['Always pick the food, always eat alone', 'Never pick, always eat together'],
    ['Lose every old photo', 'Lose every old message'],
    ['Be the tallest in the family', 'Be the shortest'],
    ['Work with your best friend', 'Work alone from home'],
    ['Be able to cook anything', 'Be able to fix anything'],
    ['Nine months of winter', 'Nine months of summer'],
    ['Listen to someone complain for two hours', 'Complain for two hours to nobody'],
    ['Never use social media again', 'Never watch television again'],
    ['Be responsible for everything', 'Have a say in nothing'],
    ['Live without coffee', 'Live without tea'],
    ['Travel 100 years into the future', 'Travel 100 years into the past'],
    ['Live in your dream mansion alone', 'Live in a modest house with your best friends'],
    ['Never need to sleep without feeling tired', 'Never need to work and receive your current salary'],
    ['Control the weather', 'Control time'],
    ['Speak every language fluently', 'Master every musical instrument'],
    ['Eat your favourite meal every day', 'Eat a random mystery dish every day'],
    ['Be the fastest runner on Earth', 'Be the strongest person on Earth'],
    ['Breathe underwater', 'Fly in the sky'],
    ['Spend a day inside a cartoon', 'Spend a day inside a video game'],
    ['Forget every film you loved and rewatch them', 'Read every book before it is published'],
    ['Go one month with zero sugar', 'Go one month with no coffee or tea'],
    ['Have a button to rewind 10 minutes', 'Have a button to skip 10 minutes forward'],
    ['Be able to communicate with plants', 'Be able to communicate with electronic devices'],
    ['Live on a warm tropical island', 'Live in a cozy snowy mountain cabin'],
    ['Free tickets to every concert forever', 'Free flights anywhere in the world forever'],
    ['Know what people say about you behind your back', 'Know who secretly has a crush on you'],
    ['Never feel anger again', 'Never feel sadness again'],
    ['Be world-famous and universally loved', 'Be extremely wealthy in total anonymity'],
    ['Eat whatever you want without gaining weight', 'Feel completely refreshed on 3 hours of sleep'],
    ['Spend summer with no air conditioning', 'Spend winter with no internet'],
    ['Always speak in a loud boom', 'Always speak in a quiet whisper'],
    ['Be able to turn invisible at will', 'Be able to walk through walls at will'],
    ['Only listen to songs from before you were born', 'Only listen to songs released this year'],
    ['Solve every cosmic mystery', 'Live a simple, blissful life without existential doubts'],
    ['Lose your entire social media history', 'Lose every private message you ever sent'],
    ['Always wear a formal three-piece suit', 'Always wear comfortable flannel pyjamas'],
    ['Visit the Moon and return safely', 'Explore the bottom of the Mariana Trench'],
    ['Have a personal chef and cleaner robot', 'Have a fully autonomous flying car'],
    ['Wake up bursting with energy at 5 AM', 'Stay up all night and sleep in without guilt'],
    ['Know the truth behind every conspiracy', 'Know the exact life story of your soulmate']
  ]
};

/* --- مين أكثر واحد -------------------------------------------------------
   The options are the players themselves, so these only need to be prompts
   the room will argue about.
   -------------------------------------------------------------------------- */
const MOST_LIKELY_TO = {
  ar: [
    'مين أكثر واحد ممكن ينسى عيد ميلاد صاحبه؟',
    'مين أكثر واحد ممكن يتأخر على أي ميعاد؟',
    'مين أكثر واحد ممكن يضيع في مدينة يعرفها؟',
    'مين أكثر واحد ممكن يبقى مشهور على النت؟',
    'مين أكثر واحد ممكن يسيب الشغل ويسافر؟',
    'مين أكثر واحد ممكن يشتري حاجة مش محتاجها؟',
    'مين أكثر واحد ممكن ينام في السينما؟',
    'مين أكثر واحد ممكن يكسب مسابقة أكل؟',
    'مين أكثر واحد ممكن ينسى موبايله في مكان؟',
    'مين أكثر واحد ممكن يتخانق على حاجة تافهة؟',
    'مين أكثر واحد ممكن يبقى رئيس شركة؟',
    'مين أكثر واحد ممكن يعيط في فيلم؟',
    'مين أكثر واحد ممكن يقول نكتة بايخة؟',
    'مين أكثر واحد ممكن يرد على رسالة بعد أسبوع؟',
    'مين أكثر واحد ممكن يوصل الأول في أي رحلة؟',
    'مين أكثر واحد ممكن يعمل حادثة بالعربية؟',
    'مين أكثر واحد ممكن يتعلم لغة جديدة السنة دي؟',
    'مين أكثر واحد ممكن ينسى اسم حد قابله لسه؟',
    'مين أكثر واحد ممكن يطلب نفس الأكل كل مرة؟',
    'مين أكثر واحد ممكن يجيب أعلى فاتورة موبايل؟',
    'مين أكثر واحد ممكن يقعد على السرير اليوم كله؟',
    'مين أكثر واحد ممكن يساعد غريب في الشارع؟',
    'مين أكثر واحد ممكن يخسر في لعبة ويزعل؟',
    'مين أكثر واحد ممكن يعمل حفلة من غير سبب؟',
    'مين أكثر واحد ممكن يفتكر تفاصيل من سنين؟',
    'مين أكثر واحد ممكن يشتري نفس الهدوم بلونين؟',
    'مين أكثر واحد ممكن يتوه في مطار؟',
    'مين أكثر واحد ممكن يبقى آخر واحد يمشي من أي قعدة؟',
    'مين أكثر واحد ممكن ياخد سيلفي في مكان غريب؟',
    'مين أكثر واحد ممكن يصحى بدري في إجازته؟',
    'مين أكثر واحد ممكن يقنعك تعمل حاجة مجنونة؟',
    'مين أكثر واحد ممكن يقرأ الشروط والأحكام؟',
    'مين أكثر واحد ممكن يفضل يتكلم لو محدش سامع؟',
    'مين أكثر واحد ممكن يبقى عنده 5 خطط للإجازة؟',
    'مين أكثر واحد ممكن يخبي إنه اتفرج على المسلسل من غيرنا؟',
    'مين أكثر واحد ممكن يفتكر إنه على حق دايماً؟',
    'مين أكثر واحد ممكن يدفع الحساب من غير ما حد يشوف؟',
    'مين أكثر واحد ممكن يتعصب من صوت الأكل؟',
    'مين أكثر واحد ممكن يبقى عنده نبات مات من قلة المياه؟',
    'مين أكثر واحد ممكن يغني بصوت عالي في العربية؟',
    'مين أكثر واحد ممكن ينسى هو كان داخل الأوضة ليه؟',
    'مين أكثر واحد ممكن يضحك في موقف مش مناسب خالص؟',
    'مين أكثر واحد ممكن يطلب دليفري وهو أصلاً في المطبخ؟',
    'مين أكثر واحد ممكن يفضل سهران للصبح بيتفرج على فيديوهات تافهة؟',
    'مين أكثر واحد ممكن يبدأ مشروع جديد ويتحمس له أسبوع وبعدين ينساه؟',
    'مين أكثر واحد ممكن يضيع تذكرته وهو واقف في الطابور؟',
    'مين أكثر واحد ممكن يقنعك تشتري حاجة أنت مش طايقها؟',
    'مين أكثر واحد ممكن يتفرج على فيلم رعب ويقعد خايف أسبوع؟',
    'مين أكثر واحد ممكن ينسى هو ركن عربيته فين؟',
    'مين أكثر واحد ممكن يفصل شحن موبايله في أهم لحظة؟',
    'مين أكثر واحد ممكن يغني بصوت عالي وهو حاطط السماعات ومش حاسس؟',
    'مين أكثر واحد ممكن يطلب شاي في عز الحر؟',
    'مين أكثر واحد ممكن ينام في المواصلات ويفوّت محطته؟',
    'مين أكثر واحد ممكن يشتري هدوم وميلبسهاش خالص؟',
    'مين أكثر واحد ممكن يقلب البيت كله عشان يدور على نظارته وهي على وشه؟',
    'مين أكثر واحد ممكن يكسب مليون جنيه ويصرفهم في شهر؟',
    'مين أكثر واحد ممكن يتصل بيك بالغلط وهو سايب الموبايل في جيبه؟',
    'مين أكثر واحد ممكن يطبخ أكلة غريبة ويصر إنها تحفة؟',
    'مين أكثر واحد ممكن يسافر بشنطة صغيرة جداً مفيهاش غير تيشرت؟',
    'مين أكثر واحد ممكن يبكي من الفرحة في فرح حد ميعرفوش؟',
    'مين أكثر واحد ممكن يحفظ نمر التليفونات في دماغه؟',
    'مين أكثر واحد ممكن يقعد يتكلم مع قطة في الشارع؟',
    'مين أكثر واحد ممكن يلعب لعبة ويزعل بجد لو خسر؟',
    'مين أكثر واحد ممكن يعمل مقلب في صحابه ويندم عليه؟',
    'مين أكثر واحد ممكن يشتري جهاز رياضي ويستخدمه شماعة للهدوم؟',
    'مين أكثر واحد ممكن يصحى من النوم يسأل هو احنا في سنة كام؟',
    'مين أكثر واحد ممكن يجاوب بثقة على سؤال وهو ميعرفش إجابته؟',
    'مين أكثر واحد ممكن يضيع في مول تجاري؟',
    'مين أكثر واحد ممكن ينسى يقفل باب الشقة بالمفتاح؟',
    'مين أكثر واحد ممكن يعزم الناس كلها على حسابه في لحظة كرم مفاجئة؟'
  ],
  en: [
    'Who is most likely to forget a friend\'s birthday?',
    'Who is most likely to be late to everything?',
    'Who is most likely to get lost in their own city?',
    'Who is most likely to go viral?',
    'Who is most likely to quit their job and travel?',
    'Who is most likely to buy something they don\'t need?',
    'Who is most likely to fall asleep at the cinema?',
    'Who is most likely to win an eating contest?',
    'Who is most likely to leave their phone somewhere?',
    'Who is most likely to argue about something trivial?',
    'Who is most likely to run a company one day?',
    'Who is most likely to cry at a film?',
    'Who is most likely to tell a terrible joke?',
    'Who is most likely to reply a week later?',
    'Who is most likely to arrive first, every time?',
    'Who is most likely to reverse into a bollard?',
    'Who is most likely to learn a language this year?',
    'Who is most likely to forget a name instantly?',
    'Who is most likely to order the exact same thing every time?',
    'Who is most likely to have the highest phone bill?',
    'Who is most likely to stay in bed all day?',
    'Who is most likely to help a stranger in the street?',
    'Who is most likely to sulk after losing a game?',
    'Who is most likely to throw a party for no reason?',
    'Who is most likely to remember something from years ago?',
    'Who is most likely to buy the same shirt in two colours?',
    'Who is most likely to get lost in an airport?',
    'Who is most likely to be the last to leave?',
    'Who is most likely to take a selfie somewhere odd?',
    'Who is most likely to wake up early on holiday?',
    'Who is most likely to talk you into something reckless?',
    'Who is most likely to actually read the terms and conditions?',
    'Who is most likely to keep talking when nobody is listening?',
    'Who is most likely to have five plans for one holiday?',
    'Who is most likely to secretly watch ahead in a series?',
    'Who is most likely to be certain they\'re right?',
    'Who is most likely to pay the bill without telling anyone?',
    'Who is most likely to be annoyed by chewing?',
    'Who is most likely to kill a houseplant?',
    'Who is most likely to sing loudly in the car?',
    'Who is most likely to walk into a room and forget why they entered?',
    'Who is most likely to laugh at the absolute worst possible moment?',
    'Who is most likely to order takeaway while standing right in the kitchen?',
    'Who is most likely to stay up until 4 AM watching useless internet rabbit holes?',
    'Who is most likely to start an ambitious new hobby and abandon it in a week?',
    'Who is most likely to lose their boarding pass while standing in the queue?',
    'Who is most likely to talk you into buying something you do not even want?',
    'Who is most likely to watch a horror film and sleep with the lights on for a week?',
    'Who is most likely to wander an entire car park looking for their car?',
    'Who is most likely to have their phone battery die at the worst possible instant?',
    'Who is most likely to sing terribly at top volume with noise-cancelling headphones on?',
    'Who is most likely to drink a scalding hot cup of tea in a heatwave?',
    'Who is most likely to fall asleep on public transit and miss their stop completely?',
    'Who is most likely to buy new clothes and keep the tags on in the wardrobe for a year?',
    'Who is most likely to search the entire flat for glasses that are sitting on their head?',
    'Who is most likely to win the lottery and spend every penny in six months?',
    'Who is most likely to pocket-dial someone and leave a mysterious five-minute voicemail?',
    'Who is most likely to invent a bizarre recipe and insist it belongs in a restaurant?',
    'Who is most likely to go on a fortnight holiday with just a tiny backpack?',
    'Who is most likely to cry happy tears at a stranger\'s wedding?',
    'Who is most likely to memorise obscure trivia nobody asked for?',
    'Who is most likely to have a full conversation with a stray cat on the street?',
    'Who is most likely to get genuinely competitive over a casual party game?',
    'Who is most likely to pull an elaborate prank and immediately feel guilty about it?',
    'Who is most likely to buy expensive exercise gear and use it as a clothes rail?',
    'Who is most likely to wake from an afternoon nap completely disoriented?',
    'Who is most likely to answer a trivia question with total confidence and be entirely wrong?',
    'Who is most likely to get lost inside a shopping centre?',
    'Who is most likely to forget to lock the front door?',
    'Who is most likely to spontaneously pay for everyone\'s dinner on a whim?'
  ]
};

/* --- فيبج -----------------------------------------------------------------
   A real, slightly surprising fact. The answer must be short enough that
   somebody could plausibly have invented it — that is the whole game.
   -------------------------------------------------------------------------- */
const FIBBAGE = {
  ar: [
    { q: 'أطول اسم لمدينة في العالم فيه ___ حرف.', a: '168' },
    { q: 'قلب الجمبري موجود في ___ بتاعه.', a: 'راسه' },
    { q: 'العسل ما بيبوظش أبداً لأن فيه نسبة ___ قليلة جداً.', a: 'مياه' },
    { q: 'الأخطبوط عنده ___ قلوب.', a: 'ثلاثة' },
    { q: 'أقصر حرب في التاريخ استمرت ___ دقيقة.', a: '38' },
    { q: 'الموزة من الناحية النباتية بتتصنف على إنها ___.', a: 'توت' },
    { q: 'الزرافة بتنام حوالي ___ ساعة في اليوم.', a: 'نص' },
    { q: 'أسنان القرش بتتغير طول عمره وممكن يغير ___ سنة.', a: '30 ألف' },
    { q: 'برج إيفل بيطول في الصيف حوالي ___ سنتيمتر.', a: '15' },
    { q: 'النملة تقدر تشيل ___ ضعف وزنها.', a: '50' },
    { q: 'في اليابان في فندق شغال من سنة ___.', a: '705' },
    { q: 'الفراولة مش توت، هي فعلياً من عيلة ___.', a: 'الورد' },
    { q: 'صوت البطة ما بيعملش ___ حسب الأسطورة المشهورة.', a: 'صدى' },
    { q: 'الإنسان بيفقد حوالي ___ شعرة في اليوم بشكل طبيعي.', a: '100' },
    { q: 'أثقل حيوان على الأرض هو ___ الأزرق.', a: 'الحوت' },
    { q: 'في مصر القديمة كانوا بيحلقوا ___ حداد على القطة.', a: 'حواجبهم' },
    { q: 'الكلب بيعرق من ___ بتاعه.', a: 'رجليه' },
    { q: 'البطاطس كانت أول خضار يتزرع في ___.', a: 'الفضاء' },
    { q: 'الفيل هو الحيوان الوحيد اللي ما يقدرش ___.', a: 'ينط' },
    { q: 'قوس قزح الكامل شكله ___ مش قوس.', a: 'دايرة' },
    { q: 'أسرع عضلة في جسم الإنسان موجودة في ___.', a: 'العين' },
    { q: 'الجمل عنده ___ صفوف من الرموش.', a: 'ثلاثة' },
    { q: 'أطول فترة صحيان مسجلة لإنسان حوالي ___ يوم.', a: '11' },
    { q: 'الببغاء ممكن يعيش لحد ___ سنة.', a: '80' },
    { q: 'كوكب ___ بيلف حوالين نفسه أسرع من أي كوكب تاني.', a: 'المشتري' },
    { q: 'الجبنة أكتر أكلة بتتسرق في ___ العالم.', a: 'محلات' },
    { q: 'الدماغ بتستهلك حوالي ___ في المية من طاقة الجسم.', a: '20' },
    { q: 'أول منتج اتقرا بالباركود كان ___.', a: 'علبة لبان' },
    { q: 'البحر الميت اسمه كده لأن ما فيهوش ___.', a: 'كائنات' },
    { q: 'القطط ما بتحسش بطعم ___.', a: 'الحلاوة' },
    { q: 'أطول نبات بينمو في اليوم هو ___.', a: 'الخيزران' },
    { q: 'الفقاعة في الشمبانيا ممكن توصل لـ ___ فقاعة.', a: 'مليون' },
    { q: 'أثقل سحابة ممكن توزن زي ___ فيل.', a: '100' },
    { q: 'العطسة بتطلع بسرعة حوالي ___ كيلومتر في الساعة.', a: '160' },
    { q: 'أطول جسر مشاة معلق في العالم في دولة ___.', a: 'التشيك' },
    { q: 'الكنغر ما يقدرش يمشي لـ ___.', a: 'ورا' },
    { q: 'لسان الحوت الأزرق ممكن يوزن قد وزن ___.', a: 'فيل' },
    { q: 'الحصان ما يقدرش يتنفس غير من ___.', a: 'مناخيره' },
    { q: 'حيوان الكوالا بينام حوالي ___ ساعة في اليوم.', a: '20' },
    { q: 'أول لعبة فيديو في التاريخ اتعملت سنة ___.', a: '1958' },
    { q: 'الذهب الخالص صالح للأكل بدون أي ___.', a: 'ضرر' },
    { q: 'عين النعامة أكبر من ___ بتاعها.', a: 'مخها' },
    { q: 'الولاعة اختُرعت قبل ___ بسنين.', a: 'الكبريت' },
    { q: 'التفاح بيعوم على وش المية لأن ربع حجمه ___.', a: 'هواء' },
    { q: 'دم جراد البحر لونه ___.', a: 'أزرق' },
    { q: 'في سويسرا غير قانوني تمتلك ___ غينيا واحد بس.', a: 'خنزير' },
    { q: 'كوكب الزهرة هو الكوكب الوحيد اللي بيلف مع عقارب ___.', a: 'الساعة' },
    { q: 'صوت الحوت الأزرق بيتسمع تحت المية لمسافة ___ كيلومتر.', a: '800' },
    { q: 'حيوان الكسلان بيحتاج ___ عشان يهضم وجبة واحدة.', a: 'أسبوعين' },
    { q: 'الجمبري بيعمل بمخالبه فرقعة توصل لحرارة تقارب حرارة ___.', a: 'الشمس' },
    { q: 'الإنسان بينتج في حياته لعاب يكفي لملء ___ حمام سباحة.', a: 'اثنين' },
    { q: 'في سنة 2008 منحت النرويج بطريق رتبة ___ في الجيش.', a: 'فارس' },
    { q: 'جبال الألب بتكبر كل سنة حوالي ___ ملليمتر.', a: 'واحد' },
    { q: 'النجوم في الكون أكتر من حبات ___ على كل شواطئ الأرض.', a: 'الرمل' },
    { q: 'عين الحرباء تقدر تبص في اتجاهين ___ في نفس الوقت.', a: 'مختلفين' },
    { q: 'النعامة تقدر تجري بسرعة توصل لـ ___ كيلومتر في الساعة.', a: '70' },
    { q: 'أقدم شجرة حية على الأرض عمرها أكتر من ___ سنة.', a: '4800' },
    { q: 'كوكب نبتون لونه أزرق بسبب وجود غاز ___.', a: 'الميثان' },
    { q: 'ثعالب الماء بتمسك ___ بعض وهي نايمة عشان ما تبعدش.', a: 'أيادي' },
    { q: 'الفراشة بتتذوق أكلها عن طريق ___ بتوعها.', a: 'رجليها' }
  ],
  en: [
    { q: 'The longest place name in the world has ___ letters.', a: '85' },
    { q: 'A shrimp\'s heart is located in its ___.', a: 'head' },
    { q: 'Honey never spoils because it contains almost no ___.', a: 'water' },
    { q: 'An octopus has ___ hearts.', a: 'three' },
    { q: 'The shortest war in history lasted ___ minutes.', a: '38' },
    { q: 'Botanically, a banana is classified as a ___.', a: 'berry' },
    { q: 'A giraffe sleeps roughly ___ hours a day.', a: 'two' },
    { q: 'A shark can get through around ___ teeth in a lifetime.', a: '30,000' },
    { q: 'The Eiffel Tower grows about ___ cm taller in summer.', a: '15' },
    { q: 'An ant can carry ___ times its own body weight.', a: '50' },
    { q: 'The oldest hotel still operating opened in the year ___.', a: '705' },
    { q: 'Strawberries are not berries — they belong to the ___ family.', a: 'rose' },
    { q: 'A group of flamingos is called a ___.', a: 'flamboyance' },
    { q: 'A person loses roughly ___ hairs a day, normally.', a: '100' },
    { q: 'The heaviest animal on earth is the ___ whale.', a: 'blue' },
    { q: 'In ancient Egypt, people shaved their ___ to mourn a cat.', a: 'eyebrows' },
    { q: 'Dogs sweat through their ___.', a: 'paws' },
    { q: 'The first vegetable grown in space was the ___.', a: 'potato' },
    { q: 'The elephant is the only mammal that cannot ___.', a: 'jump' },
    { q: 'A complete rainbow is actually a ___, not an arc.', a: 'circle' },
    { q: 'The fastest muscle in the human body is in the ___.', a: 'eye' },
    { q: 'A camel has ___ rows of eyelashes.', a: 'three' },
    { q: 'The longest recorded time without sleep is about ___ days.', a: '11' },
    { q: 'A parrot can live up to ___ years.', a: '80' },
    { q: 'The planet that spins fastest on its axis is ___.', a: 'Jupiter' },
    { q: 'The most shoplifted food in the world is ___.', a: 'cheese' },
    { q: 'The brain uses around ___ percent of the body\'s energy.', a: '20' },
    { q: 'The first product ever scanned by barcode was a packet of ___.', a: 'chewing gum' },
    { q: 'Cats cannot taste ___.', a: 'sweetness' },
    { q: 'The fastest-growing plant on earth is ___.', a: 'bamboo' },
    { q: 'A bottle of champagne can hold up to ___ bubbles.', a: 'a million' },
    { q: 'A single cloud can weigh about as much as ___ elephants.', a: '100' },
    { q: 'A sneeze leaves the body at around ___ km/h.', a: '160' },
    { q: 'Wombat droppings are famously ___ shaped.', a: 'cube' },
    { q: 'The world\'s longest pedestrian suspension bridge is in ___.', a: 'Czechia' },
    { q: 'Kangaroos are physically unable to walk ___.', a: 'backwards' },
    { q: 'A blue whale\'s tongue can weigh as much as an ___.', a: 'elephant' },
    { q: 'Horses can only breathe through their ___.', a: 'nose' },
    { q: 'Koalas can sleep up to ___ hours in a single day.', a: '20' },
    { q: 'The modern cigarette lighter was invented before the ___.', a: 'match' },
    { q: 'An ostrich\'s eye is notably larger than its ___.', a: 'brain' },
    { q: 'Apples float in water because 25 percent of their volume is ___.', a: 'air' },
    { q: 'Lobsters naturally possess ___ coloured blood.', a: 'blue' },
    { q: 'In Switzerland, it is illegal to own only one single ___ pig.', a: 'guinea' },
    { q: 'Venus is the only planet in the solar system that spins ___.', a: 'clockwise' },
    { q: 'A blue whale call can travel underwater across ___ km.', a: '800' },
    { q: 'It takes a sloth roughly ___ weeks to digest a meal.', a: 'two' },
    { q: 'Snapping shrimp claws create a bubble as hot as the surface of the ___.', a: 'sun' },
    { q: 'A human mouth produces enough saliva to fill two whole ___.', a: 'swimming pools' },
    { q: 'In 2008, the king of Norway formally knighted a ___.', a: 'penguin' },
    { q: 'The European Alps rise roughly one ___ higher every year.', a: 'millimetre' },
    { q: 'There are more stars in the observable universe than grains of ___ on earth.', a: 'sand' },
    { q: 'Chameleon eyes can swivel in two completely different ___ at once.', a: 'directions' },
    { q: 'An adult ostrich can sprint at top speeds up to ___ km/h.', a: '70' },
    { q: 'The oldest known living tree on Earth is over ___ years old.', a: '4,800' },
    { q: 'Neptune appears bright blue due to traces of ___ in its clouds.', a: 'methane' },
    { q: 'Sea otters hold ___ while asleep so they do not drift away.', a: 'hands' },
    { q: 'Butterflies taste their potential food using their ___.', a: 'feet' },
    { q: 'A woodpecker wraps its unusually long tongue completely around its ___.', a: 'skull' },
    { q: 'Sloths can hold their breath underwater longer than ___.', a: 'dolphins' }
  ]
};

/* --- ارسم وخمّن -----------------------------------------------------------
   Draw & Guess needs words you can actually put on a canvas. The Codenames
   list was reused at first, but it deliberately contains abstractions —
   وقت، حلم، ذكرى، صوت، سر — which are unguessable from a drawing. These are
   concrete and visually distinct from each other.
   -------------------------------------------------------------------------- */
const DRAW_WORDS = {
  ar: [
    // حيوانات
    'أسد', 'فيل', 'زرافة', 'قرد', 'قطة', 'كلب', 'حصان', 'جمل',
    'سمكة', 'أخطبوط', 'سلحفاة', 'ثعبان', 'نحلة', 'فراشة', 'بطريق', 'دجاجة',
    'بومة', 'حوت', 'دلفين', 'عقرب', 'أرنب', 'خروف', 'بقرة', 'تمساح',
    // أكل
    'بيتزا', 'برجر', 'موزة', 'تفاحة', 'بطيخة', 'عنب', 'آيس كريم', 'كعكة',
    'بيضة', 'سمكة مشوية', 'فنجان قهوة', 'كوب شاي', 'رغيف عيش', 'جبنة', 'عنقود موز', 'شاورما',
    // أشياء البيت
    'باب', 'شباك', 'كرسي', 'ترابيزة', 'سرير', 'مفتاح', 'ساعة', 'مرآة',
    'شمعة', 'لمبة', 'مقص', 'مكنسة', 'سلم', 'مظلة', 'نظارة', 'حقيبة',
    'مفتاح نور', 'ثلاجة', 'تليفون', 'كمبيوتر', 'كاميرا', 'مروحة', 'جرس', 'قفل',
    // مواصلات
    'سيارة', 'أتوبيس', 'قطار', 'طيارة', 'صاروخ', 'مركب', 'دراجة', 'موتوسيكل',
    'غواصة', 'بالون', 'طيارة ورق', 'تاكسي',
    // أماكن ومباني
    'بيت', 'مدرسة', 'مستشفى', 'برج', 'جسر', 'قلعة', 'خيمة', 'كنيسة',
    'مسجد', 'هرم', 'منارة', 'ملعب',
    // طبيعة
    'شمس', 'قمر', 'نجمة', 'سحابة', 'مطر', 'شجرة', 'وردة', 'جبل',
    'بحر', 'نار', 'قوس قزح', 'بركان', 'صبار', 'ورقة شجر', 'ثلج', 'موجة',
    // جسم ووش
    'عين', 'يد', 'قدم', 'قلب', 'أنف', 'ودن', 'سن', 'عضلات',
    // أدوات ورياضة
    'كرة', 'مضرب', 'قوس ونشاب', 'سيف', 'درع', 'مطرقة', 'منشار', 'مسمار',
    'صنارة', 'مفك', 'ميزان', 'سلة', 'كوب', 'طبق', 'ملعقة', 'شوكة',
    'سكينة', 'إبريق', 'زجاجة', 'مفتاح إنجليزي',
    // موسيقى وترفيه
    'جيتار', 'بيانو', 'طبلة', 'كمان', 'ناي', 'ميكروفون', 'تليفزيون', 'نرد',
    // ناس وملابس
    'قميص', 'بنطلون', 'حذاء', 'قبعة', 'خاتم', 'تاج', 'روبوت', 'شبح',
    'ملك', 'طيار', 'طبيب', 'حرامي', 'عروسة', 'ساحر', 'مهرج', 'رجل ثلج',
    // متنوع بصري
    'مفتاح كنز', 'خريطة', 'بوصلة', 'تلسكوب', 'مظروف', 'هدية', 'بالونة', 'تورتة عيد ميلاد',
    'سلسلة', 'شبكة', 'حبل', 'سهم', 'قنبلة', 'صندوق', 'مقعد', 'كوب آيس كريم',
    'خاتم ألماس', 'حذاء رياضي', 'تاج ملكي', 'نظارة شمس', 'شنطة سفر', 'ساعة يد', 'فستان سهرة', 'بدلة رسمية',
    'سماعات رأس', 'مروحة سقف', 'تكييف', 'مكواة', 'غسالة ملابس', 'شاحن موبايل', 'ماوس كمبيوتر', 'لابتوب',
    'فلاشة ميموري', 'ريموت كنترول', 'فرشاة أسنان', 'صابونة', 'فوطة حمام', 'شواية فحم', 'طاسة بيض', 'براد شاي',
    'عصير مانجو', 'كانز صودا', 'كوباية قهوة', 'طبق مكرونة', 'ساندوتش كفتة', 'قطعة بيتزا', 'فراولة', 'أناناس',
    'ليمونة', 'ذرة مشوي', 'حبة طماطم', 'جزرة', 'قرن فلفل', 'سفينة فضاء', 'عربية إسعاف', 'سيارة مطافئ',
    'جرار زراعي', 'كوبري معلق', 'محطة قطار', 'مخزن بضائع', 'خيمة تخييم', 'فانوس رمضان', 'كشاف يدوي', 'شمسية مطر',
    'شمعة مضيئة', 'لوحة رسم', 'تمثال حجري', 'ميدالية ذهبية', 'كأس بطولة', 'صفارة حكم', 'طاولة بلياردو', 'مضرب تنس',
    'عش عصفور', 'ريشة طائر', 'خلية نحل', 'صدفة بحر', 'نجم بحر', 'قنديل بحر', 'زحليقة أطفال', 'أرجوحة ملاهي'
  ],
  en: [
    'Lion', 'Elephant', 'Giraffe', 'Monkey', 'Cat', 'Dog', 'Horse', 'Camel',
    'Fish', 'Octopus', 'Turtle', 'Snake', 'Bee', 'Butterfly', 'Penguin', 'Chicken',
    'Owl', 'Whale', 'Dolphin', 'Scorpion', 'Rabbit', 'Sheep', 'Cow', 'Crocodile',
    'Pizza', 'Burger', 'Banana', 'Apple', 'Watermelon', 'Grapes', 'Ice cream', 'Cake',
    'Egg', 'Coffee cup', 'Teapot', 'Bread', 'Cheese', 'Doughnut', 'Lollipop', 'Popcorn',
    'Door', 'Window', 'Chair', 'Table', 'Bed', 'Key', 'Clock', 'Mirror',
    'Candle', 'Lamp', 'Scissors', 'Broom', 'Ladder', 'Umbrella', 'Glasses', 'Bag',
    'Switch', 'Fridge', 'Phone', 'Computer', 'Camera', 'Fan', 'Bell', 'Padlock',
    'Car', 'Bus', 'Train', 'Plane', 'Rocket', 'Boat', 'Bicycle', 'Motorcycle',
    'Submarine', 'Balloon', 'Kite', 'Taxi',
    'House', 'School', 'Hospital', 'Tower', 'Bridge', 'Castle', 'Tent', 'Church',
    'Pyramid', 'Lighthouse', 'Stadium', 'Windmill',
    'Sun', 'Moon', 'Star', 'Cloud', 'Rain', 'Tree', 'Rose', 'Mountain',
    'Sea', 'Fire', 'Rainbow', 'Volcano', 'Cactus', 'Leaf', 'Snowflake', 'Wave',
    'Eye', 'Hand', 'Foot', 'Heart', 'Nose', 'Ear', 'Tooth', 'Skull',
    'Ball', 'Racket', 'Bow and arrow', 'Sword', 'Shield', 'Hammer', 'Saw', 'Nail',
    'Fishing rod', 'Screwdriver', 'Scales', 'Basket', 'Cup', 'Plate', 'Spoon', 'Fork',
    'Knife', 'Kettle', 'Bottle', 'Wrench',
    'Guitar', 'Piano', 'Drum', 'Violin', 'Flute', 'Microphone', 'Television', 'Dice',
    'Shirt', 'Trousers', 'Shoe', 'Hat', 'Ring', 'Crown', 'Robot', 'Ghost',
    'King', 'Pilot', 'Doctor', 'Thief', 'Bride', 'Wizard', 'Clown', 'Snowman',
    'Treasure chest', 'Map', 'Compass', 'Telescope', 'Envelope', 'Gift', 'Birthday cake', 'Anchor',
    'Chain', 'Net', 'Rope', 'Arrow', 'Bomb', 'Box', 'Bench', 'Trophy',
    'Diamond ring', 'Sneakers', 'Royal crown', 'Sunglasses', 'Suitcase', 'Wristwatch', 'Party dress', 'Tuxedo',
    'Headphones', 'Ceiling fan', 'Air conditioner', 'Clothes iron', 'Washing machine', 'Phone charger', 'Computer mouse', 'Laptop',
    'Flash drive', 'Remote control', 'Toothbrush', 'Bar of soap', 'Bath towel', 'Barbecue grill', 'Frying pan', 'Thermos',
    'Mango juice', 'Soda can', 'Mug of coffee', 'Pasta bowl', 'Hot dog', 'Slice of pizza', 'Strawberry', 'Pineapple',
    'Lemon', 'Corn on the cob', 'Tomato', 'Carrot', 'Chilli pepper', 'Spaceship', 'Ambulance', 'Fire truck',
    'Tractor', 'Suspension bridge', 'Train station', 'Warehouse', 'Camping tent', 'Lantern', 'Flashlight', 'Rain umbrella',
    'Lit candle', 'Canvas painting', 'Stone statue', 'Gold medal', 'Trophy cup', 'Referee whistle', 'Pool table', 'Tennis racket',
    'Bird nest', 'Bird feather', 'Beehive', 'Seashell', 'Starfish', 'Jellyfish', 'Playground slide', 'Park swing'
  ]
};
