/* ============================================================================
   PARTY GAME CONTENT
   ----------------------------------------------------------------------------
   Server-side because some of it has to be: a Fibbage question's real answer
   must not reach a client until the votes are in. The rest lives here too so
   every room game draws its content from one place.

   Written for the app's audience — Egyptian/Levantine Arabic as it's actually
   spoken, with an English set that stands on its own rather than being a
   translation.
   ========================================================================= */

/* --- لو خيروك -------------------------------------------------------------
   Two options, both defensible. A pair only works if the room can genuinely
   split on it; anything with an obvious answer is dead weight.
   -------------------------------------------------------------------------- */
const WOULD_YOU_RATHER = {
  ar: [
    ['تعرف ميعاد موتك', 'تعرف طريقة موتك'],
    ['تقدر تطير', 'تبقى خفي'],
    ['تعيش من غير موسيقى', 'تعيش من غير أفلام'],
    ['تاكل نفس الأكلة كل يوم', 'ما تاكلش أكلتك المفضلة تاني'],
    ['تنسى كل ذكرياتك', 'ما تقدرش تعمل ذكريات جديدة'],
    ['تبقى غني ووحيد', 'فقير ومحاط بأصحابك'],
    ['تقرأ أفكار الناس', 'الناس تقرأ أفكارك'],
    ['ترجع 10 سنين لورا', 'تروح 10 سنين قدام'],
    ['تعيش في الصحرا', 'تعيش في القطب'],
    ['تفقد الموبايل شهر', 'تفقد النت شهر'],
    ['تشتغل شغل بتحبه بمرتب قليل', 'شغل بتكرهه بمرتب عالي'],
    ['تبقى مشهور جداً', 'تبقى مجهول تماماً'],
    ['ما تنامش تاني', 'ما تاكلش تاني'],
    ['كل الناس تقول عليك الحقيقة دايماً', 'محدش يقولك الحقيقة أبداً'],
    ['تتكلم كل اللغات', 'تعزف كل الآلات'],
    ['تسافر الفضاء', 'تنزل قاع المحيط'],
    ['تعيش من غير تكييف في الصيف', 'من غير دفاية في الشتا'],
    ['تاكل حلو بس', 'تاكل مالح بس'],
    ['تشتغل 4 أيام 12 ساعة', 'تشتغل 6 أيام 6 ساعات'],
    ['تفقد حاسة الشم', 'تفقد حاسة التذوق'],
    ['يبقى عندك وقت كتير وفلوس قليلة', 'فلوس كتير ووقت قليل'],
    ['تعيش في مدينة زحمة', 'تعيش في قرية بعيدة'],
    ['تبقى دايماً متأخر 10 دقايق', 'دايماً بدري ساعة'],
    ['تنسى أسماء الناس', 'تنسى وشوشهم'],
    ['ما تسمعش موسيقى تاني', 'ما تشوفش البحر تاني'],
    ['تاخد إجازة سنة من غير مرتب', 'تشتغل السنة دي بضعف المرتب'],
    ['تعرف كل حاجة عن الماضي', 'تعرف حاجة واحدة عن المستقبل'],
    ['تبقى أذكى واحد في الأوضة', 'أظرف واحد في الأوضة'],
    ['تاكل من غير ما تشبع', 'تشرب من غير ما ترتوي'],
    ['كل حاجة تشتريها تبقى غالية الضعف', 'ما تشتريش حاجة جديدة أبداً'],
    ['تعيش من غير مرايات', 'تعيش من غير صور'],
    ['تقدر تتكلم مع الحيوانات', 'تتكلم كل لغات البشر'],
    ['تكون بطل في فيلم رعب', 'بطل في فيلم كوميدي'],
    ['يبقى عندك ذاكرة مثالية', 'تقدر تنسى أي حاجة تحب تنساها'],
    ['تمشي على رجلك ساعة كل يوم', 'تقعد في زحمة ساعة كل يوم'],
    ['ما تشوفش أصحابك سنة', 'تشوفهم كل يوم بالإجبار'],
    ['تبقى دايماً حران شوية', 'دايماً بردان شوية'],
    ['تنام 4 ساعات وتصحى نشيط', 'تنام 10 ساعات وتفضل تعبان'],
    ['كل الناس تعرف سرك الوحيد', 'ما تعرفش أسرار حد تاني أبداً'],
    ['تعيش حياتك بالترتيب العكسي', 'تعيش نفس اليوم 100 مرة'],
    ['تختار أكلك بس محدش يختار معاك', 'الناس تختارلك بس تاكلوا سوا'],
    ['تفقد كل صورك القديمة', 'تفقد كل رسايلك القديمة'],
    ['تبقى أطول واحد في العيلة', 'أقصر واحد'],
    ['تشتغل مع أعز أصحابك', 'تشتغل لوحدك من البيت'],
    ['تعرف تطبخ أي حاجة', 'تعرف تصلح أي حاجة'],
    ['الشتا يبقى 9 شهور', 'الصيف يبقى 9 شهور'],
    ['تقعد ساعتين تسمع حد يشتكي', 'تشتكي ساعتين ومحدش سامع'],
    ['ما تستخدمش سوشيال ميديا تاني', 'ما تشوفش تليفزيون تاني'],
    ['تبقى مسؤول عن كل حاجة', 'ما يبقاش ليك رأي في أي حاجة'],
    ['تعيش من غير قهوة', 'تعيش من غير شاي'],
    ['تسافر بالزمن 100 سنة في المستقبل', 'تسافر بالزمن 100 سنة في الماضي'],
    ['تعيش في بيت أحلامك لوحدك', 'تعيش في بيت عادي مع أحسن صحابك'],
    ['ما تضطرش تنام أبداً بدون تعب', 'ما تضطرش تشتغل أبداً وتاخد نفس فلوسك'],
    ['تتحكم في الطقس', 'تتحكم في الوقت'],
    ['تعرف كل لغة في العالم بطلاقة', 'تعرف تعزف كل آلة موسيقية باحتراف'],
    ['تاكل وجبتك المفضلة كل يوم', 'كل يوم تجرّب أكلة جديدة بالحظ'],
    ['تبقى أسرع إنسان على الأرض', 'تبقى أقوى إنسان على الأرض'],
    ['تتنفس تحت المية', 'تقدر تطير في الهوا'],
    ['تعيش في عالم كرتوني يوم', 'تعيش في عالم لعبة فيديو يوم'],
    ['تنسى كل الأفلام اللي شوفتها وتعيدها', 'تقرأ كل الكتب اللي هتنزل في مستقبلك'],
    ['تقعد شهر من غير سكر', 'تقعد شهر من غير شاي وقهوة'],
    ['يبقى عندك زرار يعيد آخر 10 دقايق', 'يبقى عندك زرار يقفز 10 دقايق قدام'],
    ['تقدر تتكلم مع النباتات', 'تقدر تتكلم مع الأجهزة الإلكترونية'],
    ['تعيش على جزيرة استوائية', 'تعيش في كوخ في جبال ثلجية'],
    ['تحضر كل حفلات الفنانين المفضلين ببلاش', 'تسافر كل بلاد العالم طيران مجاني'],
    ['تعرف مين بيتكلم عليك في غيابك', 'تعرف مين بيحبك في السر'],
    ['تفقد القدرة على الغضب تماماً', 'تفقد القدرة على الحزن تماماً'],
    ['تبقى مشهور ومحبوب من كل الناس', 'تبقى غني جداً ومحدش يعرفك'],
    ['تاكل من غير ما تزيد في الوزن', 'تنام 3 ساعات بس كل يوم وتصحى فايق'],
    ['تعيش بدون تكييف طول الصيف', 'تعيش بدون إنترنت طول الشتا'],
    ['تتكلم بصوت عالي دايماً', 'تتكلم بهمس بس ومحدش يسمعك بسهولة'],
    ['تقدر تخفي نفسك متى ما تحب', 'تقدر تمر من الحيطان متى ما تحب'],
    ['ما تسمعش غير أغاني قديمة', 'ما تسمعش غير أغاني جديدة'],
    ['تحل كل ألغاز الكون', 'تعيش حياة هادية وسعيدة بدون أسئلة'],
    ['تخسر كل متابعينك في السوشيال ميديا', 'تخسر كل رسايلك وصورك القديمة'],
    ['تكون دايماً لابس بدلة رسمية', 'تكون دايماً لابس بيجامة البيت'],
    ['تسافر القمر وترجع', 'تنزل لأعمق نقطة في المحيط'],
    ['يكون عندك روبوت يطبخ وينظف', 'يكون عندك سيارة تسوق لوحدها في أي مكان'],
    ['تصحى كل يوم بدري بنشاط', 'تسهر براحتك وتصحى متأخر بدون منبه'],
    ['تعرف حقيقة كل شائعة في العالم', 'تعرف مستقبل شخص واحد بالتفصيل']
  ],
  en: [
    ['Know when you die', 'Know how you die'],
    ['Be able to fly', 'Be invisible'],
    ['Live without music', 'Live without films'],
    ['Eat the same meal daily', 'Never eat your favourite again'],
    ['Forget every memory', 'Never make a new one'],
    ['Be rich and alone', 'Broke and surrounded by friends'],
    ['Read minds', 'Have yours read'],
    ['Go back ten years', 'Skip forward ten years'],
    ['Live in a desert', 'Live in the arctic'],
    ['Lose your phone for a month', 'Lose the internet for a month'],
    ['A job you love, badly paid', 'A job you hate, paid well'],
    ['Be very famous', 'Be completely anonymous'],
    ['Never sleep again', 'Never eat again'],
    ['Everyone always tells you the truth', 'Nobody ever does'],
    ['Speak every language', 'Play every instrument'],
    ['Travel to space', 'Explore the deep ocean'],
    ['No air conditioning in summer', 'No heating in winter'],
    ['Only sweet food', 'Only savoury food'],
    ['Four 12-hour days', 'Six 6-hour days'],
    ['Lose your sense of smell', 'Lose your sense of taste'],
    ['Lots of time, little money', 'Lots of money, no time'],
    ['Live in a crowded city', 'Live in a remote village'],
    ['Always ten minutes late', 'Always an hour early'],
    ['Forget names', 'Forget faces'],
    ['Never hear music again', 'Never see the sea again'],
    ['A year off unpaid', 'This year at double pay'],
    ['Know everything about the past', 'One fact about the future'],
    ['Be the smartest in the room', 'Be the funniest in the room'],
    ['Eat without ever feeling full', 'Drink without ever feeling quenched'],
    ['Everything costs double', 'Never buy anything new again'],
    ['Live without mirrors', 'Live without photographs'],
    ['Talk to animals', 'Speak every human language'],
    ['Star in a horror film', 'Star in a comedy'],
    ['Have perfect memory', 'Be able to forget at will'],
    ['Walk an hour every day', 'Sit in traffic an hour every day'],
    ['Not see your friends for a year', 'Be forced to see them daily'],
    ['Always slightly too hot', 'Always slightly too cold'],
    ['Sleep 4 hours and feel great', 'Sleep 10 and feel awful'],
    ['Everyone knows your one secret', 'You never learn anyone else\'s'],
    ['Live your life in reverse', 'Repeat the same day 100 times'],
    ['Always pick the food, always eat alone', 'Never pick, always eat together'],
    ['Lose every old photo', 'Lose every old message'],
    ['Be the tallest in the family', 'Be the shortest'],
    ['Work with your best friend', 'Work alone from home'],
    ['Be able to cook anything', 'Be able to fix anything'],
    ['Nine months of winter', 'Nine months of summer'],
    ['Listen to someone complain for two hours', 'Complain for two hours to nobody'],
    ['Never use social media again', 'Never watch television again'],
    ['Be responsible for everything', 'Have a say in nothing'],
    ['Live without coffee', 'Live without tea'],
    ['Travel 100 years into the future', 'Travel 100 years into the past'],
    ['Live in your dream mansion alone', 'Live in a modest house with your best friends'],
    ['Never need to sleep without feeling tired', 'Never need to work and receive your current salary'],
    ['Control the weather', 'Control time'],
    ['Speak every language fluently', 'Master every musical instrument'],
    ['Eat your favourite meal every day', 'Eat a random mystery dish every day'],
    ['Be the fastest runner on Earth', 'Be the strongest person on Earth'],
    ['Breathe underwater', 'Fly in the sky'],
    ['Spend a day inside a cartoon', 'Spend a day inside a video game'],
    ['Forget every film you loved and rewatch them', 'Read every book before it is published'],
    ['Go one month with zero sugar', 'Go one month with no coffee or tea'],
    ['Have a button to rewind 10 minutes', 'Have a button to skip 10 minutes forward'],
    ['Be able to communicate with plants', 'Be able to communicate with electronic devices'],
    ['Live on a warm tropical island', 'Live in a cozy snowy mountain cabin'],
    ['Free tickets to every concert forever', 'Free flights anywhere in the world forever'],
    ['Know what people say about you behind your back', 'Know who secretly has a crush on you'],
    ['Never feel anger again', 'Never feel sadness again'],
    ['Be world-famous and universally loved', 'Be extremely wealthy in total anonymity'],
    ['Eat whatever you want without gaining weight', 'Feel completely refreshed on 3 hours of sleep'],
    ['Spend summer with no air conditioning', 'Spend winter with no internet'],
    ['Always speak in a loud boom', 'Always speak in a quiet whisper'],
    ['Be able to turn invisible at will', 'Be able to walk through walls at will'],
    ['Only listen to songs from before you were born', 'Only listen to songs released this year'],
    ['Solve every cosmic mystery', 'Live a simple, blissful life without existential doubts'],
    ['Lose your entire social media history', 'Lose every private message you ever sent'],
    ['Always wear a formal three-piece suit', 'Always wear comfortable flannel pyjamas'],
    ['Visit the Moon and return safely', 'Explore the bottom of the Mariana Trench'],
    ['Have a personal chef and cleaner robot', 'Have a fully autonomous flying car'],
    ['Wake up bursting with energy at 5 AM', 'Stay up all night and sleep in without guilt'],
    ['Know the truth behind every conspiracy', 'Know the exact life story of your soulmate']
  ]
};

/* --- مين أكثر واحد -------------------------------------------------------
   The options are the players themselves, so these only need to be prompts
   the room will argue about.
   -------------------------------------------------------------------------- */
const MOST_LIKELY_TO = {
  ar: [
    'مين أكثر واحد ممكن ينسى عيد ميلاد صاحبه؟',
    'مين أكثر واحد ممكن يتأخر على أي ميعاد؟',
    'مين أكثر واحد ممكن يضيع في مدينة يعرفها؟',
    'مين أكثر واحد ممكن يبقى مشهور على النت؟',
    'مين أكثر واحد ممكن يسيب الشغل ويسافر؟',
    'مين أكثر واحد ممكن يشتري حاجة مش محتاجها؟',
    'مين أكثر واحد ممكن ينام في السينما؟',
    'مين أكثر واحد ممكن يكسب مسابقة أكل؟',
    'مين أكثر واحد ممكن ينسى موبايله في مكان؟',
    'مين أكثر واحد ممكن يتخانق على حاجة تافهة؟',
    'مين أكثر واحد ممكن يبقى رئيس شركة؟',
    'مين أكثر واحد ممكن يعيط في فيلم؟',
    'مين أكثر واحد ممكن يقول نكتة بايخة؟',
    'مين أكثر واحد ممكن يرد على رسالة بعد أسبوع؟',
    'مين أكثر واحد ممكن يوصل الأول في أي رحلة؟',
    'مين أكثر واحد ممكن يعمل حادثة بالعربية؟',
    'مين أكثر واحد ممكن يتعلم لغة جديدة السنة دي؟',
    'مين أكثر واحد ممكن ينسى اسم حد قابله لسه؟',
    'مين أكثر واحد ممكن يطلب نفس الأكل كل مرة؟',
    'مين أكثر واحد ممكن يجيب أعلى فاتورة موبايل؟',
    'مين أكثر واحد ممكن يقعد على السرير اليوم كله؟',
    'مين أكثر واحد ممكن يساعد غريب في الشارع؟',
    'مين أكثر واحد ممكن يخسر في لعبة ويزعل؟',
    'مين أكثر واحد ممكن يعمل حفلة من غير سبب؟',
    'مين أكثر واحد ممكن يفتكر تفاصيل من سنين؟',
    'مين أكثر واحد ممكن يشتري نفس الهدوم بلونين؟',
    'مين أكثر واحد ممكن يتوه في مطار؟',
    'مين أكثر واحد ممكن يبقى آخر واحد يمشي من أي قعدة؟',
    'مين أكثر واحد ممكن ياخد سيلفي في مكان غريب؟',
    'مين أكثر واحد ممكن يصحى بدري في إجازته؟',
    'مين أكثر واحد ممكن يقنعك تعمل حاجة مجنونة؟',
    'مين أكثر واحد ممكن يقرأ الشروط والأحكام؟',
    'مين أكثر واحد ممكن يفضل يتكلم لو محدش سامع؟',
    'مين أكثر واحد ممكن يبقى عنده 5 خطط للإجازة؟',
    'مين أكثر واحد ممكن يخبي إنه اتفرج على المسلسل من غيرنا؟',
    'مين أكثر واحد ممكن يفتكر إنه على حق دايماً؟',
    'مين أكثر واحد ممكن يدفع الحساب من غير ما حد يشوف؟',
    'مين أكثر واحد ممكن يتعصب من صوت الأكل؟',
    'مين أكثر واحد ممكن يبقى عنده نبات مات من قلة المياه؟',
    'مين أكثر واحد ممكن يغني بصوت عالي في العربية؟',
    'مين أكثر واحد ممكن ينسى هو كان داخل الأوضة ليه؟',
    'مين أكثر واحد ممكن يضحك في موقف مش مناسب خالص؟',
    'مين أكثر واحد ممكن يطلب دليفري وهو أصلاً في المطبخ؟',
    'مين أكثر واحد ممكن يفضل سهران للصبح بيتفرج على فيديوهات تافهة؟',
    'مين أكثر واحد ممكن يبدأ مشروع جديد ويتحمس له أسبوع وبعدين ينساه؟',
    'مين أكثر واحد ممكن يضيع تذكرته وهو واقف في الطابور؟',
    'مين أكثر واحد ممكن يقنعك تشتري حاجة أنت مش طايقها؟',
    'مين أكثر واحد ممكن يتفرج على فيلم رعب ويقعد خايف أسبوع؟',
    'مين أكثر واحد ممكن ينسى هو ركن عربيته فين؟',
    'مين أكثر واحد ممكن يفصل شحن موبايله في أهم لحظة؟',
    'مين أكثر واحد ممكن يغني بصوت عالي وهو حاطط السماعات ومش حاسس؟',
    'مين أكثر واحد ممكن يطلب شاي في عز الحر؟',
    'مين أكثر واحد ممكن ينام في المواصلات ويفوّت محطته؟',
    'مين أكثر واحد ممكن يشتري هدوم وميلبسهاش خالص؟',
    'مين أكثر واحد ممكن يقلب البيت كله عشان يدور على نظارته وهي على وشه؟',
    'مين أكثر واحد ممكن يكسب مليون جنيه ويصرفهم في شهر؟',
    'مين أكثر واحد ممكن يتصل بيك بالغلط وهو سايب الموبايل في جيبه؟',
    'مين أكثر واحد ممكن يطبخ أكلة غريبة ويصر إنها تحفة؟',
    'مين أكثر واحد ممكن يسافر بشنطة صغيرة جداً مفيهاش غير تيشرت؟',
    'مين أكثر واحد ممكن يبكي من الفرحة في فرح حد ميعرفوش؟',
    'مين أكثر واحد ممكن يحفظ نمر التليفونات في دماغه؟',
    'مين أكثر واحد ممكن يقعد يتكلم مع قطة في الشارع؟',
    'مين أكثر واحد ممكن يلعب لعبة ويزعل بجد لو خسر؟',
    'مين أكثر واحد ممكن يعمل مقلب في صحابه ويندم عليه؟',
    'مين أكثر واحد ممكن يشتري جهاز رياضي ويستخدمه شماعة للهدوم؟',
    'مين أكثر واحد ممكن يصحى من النوم يسأل هو احنا في سنة كام؟',
    'مين أكثر واحد ممكن يجاوب بثقة على سؤال وهو ميعرفش إجابته؟',
    'مين أكثر واحد ممكن يضيع في مول تجاري؟',
    'مين أكثر واحد ممكن ينسى يقفل باب الشقة بالمفتاح؟',
    'مين أكثر واحد ممكن يعزم الناس كلها على حسابه في لحظة كرم مفاجئة؟'
  ],
  en: [
    'Who is most likely to forget a friend\'s birthday?',
    'Who is most likely to be late to everything?',
    'Who is most likely to get lost in their own city?',
    'Who is most likely to go viral?',
    'Who is most likely to quit their job and travel?',
    'Who is most likely to buy something they don\'t need?',
    'Who is most likely to fall asleep at the cinema?',
    'Who is most likely to win an eating contest?',
    'Who is most likely to leave their phone somewhere?',
    'Who is most likely to argue about something trivial?',
    'Who is most likely to run a company one day?',
    'Who is most likely to cry at a film?',
    'Who is most likely to tell a terrible joke?',
    'Who is most likely to reply a week later?',
    'Who is most likely to arrive first, every time?',
    'Who is most likely to reverse into a bollard?',
    'Who is most likely to learn a language this year?',
    'Who is most likely to forget a name instantly?',
    'Who is most likely to order the exact same thing every time?',
    'Who is most likely to have the highest phone bill?',
    'Who is most likely to stay in bed all day?',
    'Who is most likely to help a stranger in the street?',
    'Who is most likely to sulk after losing a game?',
    'Who is most likely to throw a party for no reason?',
    'Who is most likely to remember something from years ago?',
    'Who is most likely to buy the same shirt in two colours?',
    'Who is most likely to get lost in an airport?',
    'Who is most likely to be the last to leave?',
    'Who is most likely to take a selfie somewhere odd?',
    'Who is most likely to wake up early on holiday?',
    'Who is most likely to talk you into something reckless?',
    'Who is most likely to actually read the terms and conditions?',
    'Who is most likely to keep talking when nobody is listening?',
    'Who is most likely to have five plans for one holiday?',
    'Who is most likely to secretly watch ahead in a series?',
    'Who is most likely to be certain they\'re right?',
    'Who is most likely to pay the bill without telling anyone?',
    'Who is most likely to be annoyed by chewing?',
    'Who is most likely to kill a houseplant?',
    'Who is most likely to sing loudly in the car?',
    'Who is most likely to walk into a room and forget why they entered?',
    'Who is most likely to laugh at the absolute worst possible moment?',
    'Who is most likely to order takeaway while standing right in the kitchen?',
    'Who is most likely to stay up until 4 AM watching useless internet rabbit holes?',
    'Who is most likely to start an ambitious new hobby and abandon it in a week?',
    'Who is most likely to lose their boarding pass while standing in the queue?',
    'Who is most likely to talk you into buying something you do not even want?',
    'Who is most likely to watch a horror film and sleep with the lights on for a week?',
    'Who is most likely to wander an entire car park looking for their car?',
    'Who is most likely to have their phone battery die at the worst possible instant?',
    'Who is most likely to sing terribly at top volume with noise-cancelling headphones on?',
    'Who is most likely to drink a scalding hot cup of tea in a heatwave?',
    'Who is most likely to fall asleep on public transit and miss their stop completely?',
    'Who is most likely to buy new clothes and keep the tags on in the wardrobe for a year?',
    'Who is most likely to search the entire flat for glasses that are sitting on their head?',
    'Who is most likely to win the lottery and spend every penny in six months?',
    'Who is most likely to pocket-dial someone and leave a mysterious five-minute voicemail?',
    'Who is most likely to invent a bizarre recipe and insist it belongs in a restaurant?',
    'Who is most likely to go on a fortnight holiday with just a tiny backpack?',
    'Who is most likely to cry happy tears at a stranger\'s wedding?',
    'Who is most likely to memorise obscure trivia nobody asked for?',
    'Who is most likely to have a full conversation with a stray cat on the street?',
    'Who is most likely to get genuinely competitive over a casual party game?',
    'Who is most likely to pull an elaborate prank and immediately feel guilty about it?',
    'Who is most likely to buy expensive exercise gear and use it as a clothes rail?',
    'Who is most likely to wake from an afternoon nap completely disoriented?',
    'Who is most likely to answer a trivia question with total confidence and be entirely wrong?',
    'Who is most likely to get lost inside a shopping centre?',
    'Who is most likely to forget to lock the front door?',
    'Who is most likely to spontaneously pay for everyone\'s dinner on a whim?'
  ]
};

/* --- فيبج -----------------------------------------------------------------
   A real, slightly surprising fact. The answer must be short enough that
   somebody could plausibly have invented it — that is the whole game.
   -------------------------------------------------------------------------- */
const FIBBAGE = {
  ar: [
    { q: 'أطول اسم لمدينة في العالم فيه ___ حرف.', a: '168' },
    { q: 'قلب الجمبري موجود في ___ بتاعه.', a: 'راسه' },
    { q: 'العسل ما بيبوظش أبداً لأن فيه نسبة ___ قليلة جداً.', a: 'مياه' },
    { q: 'الأخطبوط عنده ___ قلوب.', a: 'ثلاثة' },
    { q: 'أقصر حرب في التاريخ استمرت ___ دقيقة.', a: '38' },
    { q: 'الموزة من الناحية النباتية بتتصنف على إنها ___.', a: 'توت' },
    { q: 'الزرافة بتنام حوالي ___ ساعة في اليوم.', a: 'نص' },
    { q: 'أسنان القرش بتتغير طول عمره وممكن يغير ___ سنة.', a: '30 ألف' },
    { q: 'برج إيفل بيطول في الصيف حوالي ___ سنتيمتر.', a: '15' },
    { q: 'النملة تقدر تشيل ___ ضعف وزنها.', a: '50' },
    { q: 'في اليابان في فندق شغال من سنة ___.', a: '705' },
    { q: 'الفراولة مش توت، هي فعلياً من عيلة ___.', a: 'الورد' },
    { q: 'صوت البطة ما بيعملش ___ حسب الأسطورة المشهورة.', a: 'صدى' },
    { q: 'الإنسان بيفقد حوالي ___ شعرة في اليوم بشكل طبيعي.', a: '100' },
    { q: 'أثقل حيوان على الأرض هو ___ الأزرق.', a: 'الحوت' },
    { q: 'في مصر القديمة كانوا بيحلقوا ___ حداد على القطة.', a: 'حواجبهم' },
    { q: 'الكلب بيعرق من ___ بتاعه.', a: 'رجليه' },
    { q: 'البطاطس كانت أول خضار يتزرع في ___.', a: 'الفضاء' },
    { q: 'الفيل هو الحيوان الوحيد اللي ما يقدرش ___.', a: 'ينط' },
    { q: 'قوس قزح الكامل شكله ___ مش قوس.', a: 'دايرة' },
    { q: 'أسرع عضلة في جسم الإنسان موجودة في ___.', a: 'العين' },
    { q: 'الجمل عنده ___ صفوف من الرموش.', a: 'ثلاثة' },
    { q: 'أطول فترة صحيان مسجلة لإنسان حوالي ___ يوم.', a: '11' },
    { q: 'الببغاء ممكن يعيش لحد ___ سنة.', a: '80' },
    { q: 'كوكب ___ بيلف حوالين نفسه أسرع من أي كوكب تاني.', a: 'المشتري' },
    { q: 'الجبنة أكتر أكلة بتتسرق في ___ العالم.', a: 'محلات' },
    { q: 'الدماغ بتستهلك حوالي ___ في المية من طاقة الجسم.', a: '20' },
    { q: 'أول منتج اتقرا بالباركود كان ___.', a: 'علبة لبان' },
    { q: 'البحر الميت اسمه كده لأن ما فيهوش ___.', a: 'كائنات' },
    { q: 'القطط ما بتحسش بطعم ___.', a: 'الحلاوة' },
    { q: 'أطول نبات بينمو في اليوم هو ___.', a: 'الخيزران' },
    { q: 'الفقاعة في الشمبانيا ممكن توصل لـ ___ فقاعة.', a: 'مليون' },
    { q: 'أثقل سحابة ممكن توزن زي ___ فيل.', a: '100' },
    { q: 'العطسة بتطلع بسرعة حوالي ___ كيلومتر في الساعة.', a: '160' },
    { q: 'أطول جسر مشاة معلق في العالم في دولة ___.', a: 'التشيك' },
    { q: 'الكنغر ما يقدرش يمشي لـ ___.', a: 'ورا' },
    { q: 'لسان الحوت الأزرق ممكن يوزن قد وزن ___.', a: 'فيل' },
    { q: 'الحصان ما يقدرش يتنفس غير من ___.', a: 'مناخيره' },
    { q: 'حيوان الكوالا بينام حوالي ___ ساعة في اليوم.', a: '20' },
    { q: 'أول لعبة فيديو في التاريخ اتعملت سنة ___.', a: '1958' },
    { q: 'الذهب الخالص صالح للأكل بدون أي ___.', a: 'ضرر' },
    { q: 'عين النعامة أكبر من ___ بتاعها.', a: 'مخها' },
    { q: 'الولاعة اختُرعت قبل ___ بسنين.', a: 'الكبريت' },
    { q: 'التفاح بيعوم على وش المية لأن ربع حجمه ___.', a: 'هواء' },
    { q: 'دم جراد البحر لونه ___.', a: 'أزرق' },
    { q: 'في سويسرا غير قانوني تمتلك ___ غينيا واحد بس.', a: 'خنزير' },
    { q: 'كوكب الزهرة هو الكوكب الوحيد اللي بيلف مع عقارب ___.', a: 'الساعة' },
    { q: 'صوت الحوت الأزرق بيتسمع تحت المية لمسافة ___ كيلومتر.', a: '800' },
    { q: 'حيوان الكسلان بيحتاج ___ عشان يهضم وجبة واحدة.', a: 'أسبوعين' },
    { q: 'الجمبري بيعمل بمخالبه فرقعة توصل لحرارة تقارب حرارة ___.', a: 'الشمس' },
    { q: 'الإنسان بينتج في حياته لعاب يكفي لملء ___ حمام سباحة.', a: 'اثنين' },
    { q: 'في سنة 2008 منحت النرويج بطريق رتبة ___ في الجيش.', a: 'فارس' },
    { q: 'جبال الألب بتكبر كل سنة حوالي ___ ملليمتر.', a: 'واحد' },
    { q: 'النجوم في الكون أكتر من حبات ___ على كل شواطئ الأرض.', a: 'الرمل' },
    { q: 'عين الحرباء تقدر تبص في اتجاهين ___ في نفس الوقت.', a: 'مختلفين' },
    { q: 'النعامة تقدر تجري بسرعة توصل لـ ___ كيلومتر في الساعة.', a: '70' },
    { q: 'أقدم شجرة حية على الأرض عمرها أكتر من ___ سنة.', a: '4800' },
    { q: 'كوكب نبتون لونه أزرق بسبب وجود غاز ___.', a: 'الميثان' },
    { q: 'ثعالب الماء بتمسك ___ بعض وهي نايمة عشان ما تبعدش.', a: 'أيادي' },
    { q: 'الفراشة بتتذوق أكلها عن طريق ___ بتوعها.', a: 'رجليها' }
  ],
  en: [
    { q: 'The longest place name in the world has ___ letters.', a: '85' },
    { q: 'A shrimp\'s heart is located in its ___.', a: 'head' },
    { q: 'Honey never spoils because it contains almost no ___.', a: 'water' },
    { q: 'An octopus has ___ hearts.', a: 'three' },
    { q: 'The shortest war in history lasted ___ minutes.', a: '38' },
    { q: 'Botanically, a banana is classified as a ___.', a: 'berry' },
    { q: 'A giraffe sleeps roughly ___ hours a day.', a: 'two' },
    { q: 'A shark can get through around ___ teeth in a lifetime.', a: '30,000' },
    { q: 'The Eiffel Tower grows about ___ cm taller in summer.', a: '15' },
    { q: 'An ant can carry ___ times its own body weight.', a: '50' },
    { q: 'The oldest hotel still operating opened in the year ___.', a: '705' },
    { q: 'Strawberries are not berries — they belong to the ___ family.', a: 'rose' },
    { q: 'A group of flamingos is called a ___.', a: 'flamboyance' },
    { q: 'A person loses roughly ___ hairs a day, normally.', a: '100' },
    { q: 'The heaviest animal on earth is the ___ whale.', a: 'blue' },
    { q: 'In ancient Egypt, people shaved their ___ to mourn a cat.', a: 'eyebrows' },
    { q: 'Dogs sweat through their ___.', a: 'paws' },
    { q: 'The first vegetable grown in space was the ___.', a: 'potato' },
    { q: 'The elephant is the only mammal that cannot ___.', a: 'jump' },
    { q: 'A complete rainbow is actually a ___, not an arc.', a: 'circle' },
    { q: 'The fastest muscle in the human body is in the ___.', a: 'eye' },
    { q: 'A camel has ___ rows of eyelashes.', a: 'three' },
    { q: 'The longest recorded time without sleep is about ___ days.', a: '11' },
    { q: 'A parrot can live up to ___ years.', a: '80' },
    { q: 'The planet that spins fastest on its axis is ___.', a: 'Jupiter' },
    { q: 'The most shoplifted food in the world is ___.', a: 'cheese' },
    { q: 'The brain uses around ___ percent of the body\'s energy.', a: '20' },
    { q: 'The first product ever scanned by barcode was a packet of ___.', a: 'chewing gum' },
    { q: 'Cats cannot taste ___.', a: 'sweetness' },
    { q: 'The fastest-growing plant on earth is ___.', a: 'bamboo' },
    { q: 'A bottle of champagne can hold up to ___ bubbles.', a: 'a million' },
    { q: 'A single cloud can weigh about as much as ___ elephants.', a: '100' },
    { q: 'A sneeze leaves the body at around ___ km/h.', a: '160' },
    { q: 'Wombat droppings are famously ___ shaped.', a: 'cube' },
    { q: 'The world\'s longest pedestrian suspension bridge is in ___.', a: 'Czechia' },
    { q: 'Kangaroos are physically unable to walk ___.', a: 'backwards' },
    { q: 'A blue whale\'s tongue can weigh as much as an ___.', a: 'elephant' },
    { q: 'Horses can only breathe through their ___.', a: 'nose' },
    { q: 'Koalas can sleep up to ___ hours in a single day.', a: '20' },
    { q: 'The modern cigarette lighter was invented before the ___.', a: 'match' },
    { q: 'An ostrich\'s eye is notably larger than its ___.', a: 'brain' },
    { q: 'Apples float in water because 25 percent of their volume is ___.', a: 'air' },
    { q: 'Lobsters naturally possess ___ coloured blood.', a: 'blue' },
    { q: 'In Switzerland, it is illegal to own only one single ___ pig.', a: 'guinea' },
    { q: 'Venus is the only planet in the solar system that spins ___.', a: 'clockwise' },
    { q: 'A blue whale call can travel underwater across ___ km.', a: '800' },
    { q: 'It takes a sloth roughly ___ weeks to digest a meal.', a: 'two' },
    { q: 'Snapping shrimp claws create a bubble as hot as the surface of the ___.', a: 'sun' },
    { q: 'A human mouth produces enough saliva to fill two whole ___.', a: 'swimming pools' },
    { q: 'In 2008, the king of Norway formally knighted a ___.', a: 'penguin' },
    { q: 'The European Alps rise roughly one ___ higher every year.', a: 'millimetre' },
    { q: 'There are more stars in the observable universe than grains of ___ on earth.', a: 'sand' },
    { q: 'Chameleon eyes can swivel in two completely different ___ at once.', a: 'directions' },
    { q: 'An adult ostrich can sprint at top speeds up to ___ km/h.', a: '70' },
    { q: 'The oldest known living tree on Earth is over ___ years old.', a: '4,800' },
    { q: 'Neptune appears bright blue due to traces of ___ in its clouds.', a: 'methane' },
    { q: 'Sea otters hold ___ while asleep so they do not drift away.', a: 'hands' },
    { q: 'Butterflies taste their potential food using their ___.', a: 'feet' },
    { q: 'A woodpecker wraps its unusually long tongue completely around its ___.', a: 'skull' },
    { q: 'Sloths can hold their breath underwater longer than ___.', a: 'dolphins' }
  ]
};

/* --- ارسم وخمّن -----------------------------------------------------------
   Draw & Guess needs words you can actually put on a canvas. The Codenames
   list was reused at first, but it deliberately contains abstractions —
   وقت، حلم، ذكرى، صوت، سر — which are unguessable from a drawing. These are
   concrete and visually distinct from each other.
   -------------------------------------------------------------------------- */
const DRAW_WORDS = {
  ar: [
    // حيوانات
    'أسد', 'فيل', 'زرافة', 'قرد', 'قطة', 'كلب', 'حصان', 'جمل',
    'سمكة', 'أخطبوط', 'سلحفاة', 'ثعبان', 'نحلة', 'فراشة', 'بطريق', 'دجاجة',
    'بومة', 'حوت', 'دلفين', 'عقرب', 'أرنب', 'خروف', 'بقرة', 'تمساح',
    // أكل
    'بيتزا', 'برجر', 'موزة', 'تفاحة', 'بطيخة', 'عنب', 'آيس كريم', 'كعكة',
    'بيضة', 'سمكة مشوية', 'فنجان قهوة', 'كوب شاي', 'رغيف عيش', 'جبنة', 'عنقود موز', 'شاورما',
    // أشياء البيت
    'باب', 'شباك', 'كرسي', 'ترابيزة', 'سرير', 'مفتاح', 'ساعة', 'مرآة',
    'شمعة', 'لمبة', 'مقص', 'مكنسة', 'سلم', 'مظلة', 'نظارة', 'حقيبة',
    'مفتاح نور', 'ثلاجة', 'تليفون', 'كمبيوتر', 'كاميرا', 'مروحة', 'جرس', 'قفل',
    // مواصلات
    'سيارة', 'أتوبيس', 'قطار', 'طيارة', 'صاروخ', 'مركب', 'دراجة', 'موتوسيكل',
    'غواصة', 'بالون', 'طيارة ورق', 'تاكسي',
    // أماكن ومباني
    'بيت', 'مدرسة', 'مستشفى', 'برج', 'جسر', 'قلعة', 'خيمة', 'كنيسة',
    'مسجد', 'هرم', 'منارة', 'ملعب',
    // طبيعة
    'شمس', 'قمر', 'نجمة', 'سحابة', 'مطر', 'شجرة', 'وردة', 'جبل',
    'بحر', 'نار', 'قوس قزح', 'بركان', 'صبار', 'ورقة شجر', 'ثلج', 'موجة',
    // جسم ووش
    'عين', 'يد', 'قدم', 'قلب', 'أنف', 'ودن', 'سن', 'عضلات',
    // أدوات ورياضة
    'كرة', 'مضرب', 'قوس ونشاب', 'سيف', 'درع', 'مطرقة', 'منشار', 'مسمار',
    'صنارة', 'مفك', 'ميزان', 'سلة', 'كوب', 'طبق', 'ملعقة', 'شوكة',
    'سكينة', 'إبريق', 'زجاجة', 'مفتاح إنجليزي',
    // موسيقى وترفيه
    'جيتار', 'بيانو', 'طبلة', 'كمان', 'ناي', 'ميكروفون', 'تليفزيون', 'نرد',
    // ناس وملابس
    'قميص', 'بنطلون', 'حذاء', 'قبعة', 'خاتم', 'تاج', 'روبوت', 'شبح',
    'ملك', 'طيار', 'طبيب', 'حرامي', 'عروسة', 'ساحر', 'مهرج', 'رجل ثلج',
    // متنوع بصري
    'مفتاح كنز', 'خريطة', 'بوصلة', 'تلسكوب', 'مظروف', 'هدية', 'بالونة', 'تورتة عيد ميلاد',
    'سلسلة', 'شبكة', 'حبل', 'سهم', 'قنبلة', 'صندوق', 'مقعد', 'كوب آيس كريم',
    'خاتم ألماس', 'حذاء رياضي', 'تاج ملكي', 'نظارة شمس', 'شنطة سفر', 'ساعة يد', 'فستان سهرة', 'بدلة رسمية',
    'سماعات رأس', 'مروحة سقف', 'تكييف', 'مكواة', 'غسالة ملابس', 'شاحن موبايل', 'ماوس كمبيوتر', 'لابتوب',
    'فلاشة ميموري', 'ريموت كنترول', 'فرشاة أسنان', 'صابونة', 'فوطة حمام', 'شواية فحم', 'طاسة بيض', 'براد شاي',
    'عصير مانجو', 'كانز صودا', 'كوباية قهوة', 'طبق مكرونة', 'ساندوتش كفتة', 'قطعة بيتزا', 'فراولة', 'أناناس',
    'ليمونة', 'ذرة مشوي', 'حبة طماطم', 'جزرة', 'قرن فلفل', 'سفينة فضاء', 'عربية إسعاف', 'سيارة مطافئ',
    'جرار زراعي', 'كوبري معلق', 'محطة قطار', 'مخزن بضائع', 'خيمة تخييم', 'فانوس رمضان', 'كشاف يدوي', 'شمسية مطر',
    'شمعة مضيئة', 'لوحة رسم', 'تمثال حجري', 'ميدالية ذهبية', 'كأس بطولة', 'صفارة حكم', 'طاولة بلياردو', 'مضرب تنس',
    'عش عصفور', 'ريشة طائر', 'خلية نحل', 'صدفة بحر', 'نجم بحر', 'قنديل بحر', 'زحليقة أطفال', 'أرجوحة ملاهي'
  ],
  en: [
    'Lion', 'Elephant', 'Giraffe', 'Monkey', 'Cat', 'Dog', 'Horse', 'Camel',
    'Fish', 'Octopus', 'Turtle', 'Snake', 'Bee', 'Butterfly', 'Penguin', 'Chicken',
    'Owl', 'Whale', 'Dolphin', 'Scorpion', 'Rabbit', 'Sheep', 'Cow', 'Crocodile',
    'Pizza', 'Burger', 'Banana', 'Apple', 'Watermelon', 'Grapes', 'Ice cream', 'Cake',
    'Egg', 'Coffee cup', 'Teapot', 'Bread', 'Cheese', 'Doughnut', 'Lollipop', 'Popcorn',
    'Door', 'Window', 'Chair', 'Table', 'Bed', 'Key', 'Clock', 'Mirror',
    'Candle', 'Lamp', 'Scissors', 'Broom', 'Ladder', 'Umbrella', 'Glasses', 'Bag',
    'Switch', 'Fridge', 'Phone', 'Computer', 'Camera', 'Fan', 'Bell', 'Padlock',
    'Car', 'Bus', 'Train', 'Plane', 'Rocket', 'Boat', 'Bicycle', 'Motorcycle',
    'Submarine', 'Balloon', 'Kite', 'Taxi',
    'House', 'School', 'Hospital', 'Tower', 'Bridge', 'Castle', 'Tent', 'Church',
    'Pyramid', 'Lighthouse', 'Stadium', 'Windmill',
    'Sun', 'Moon', 'Star', 'Cloud', 'Rain', 'Tree', 'Rose', 'Mountain',
    'Sea', 'Fire', 'Rainbow', 'Volcano', 'Cactus', 'Leaf', 'Snowflake', 'Wave',
    'Eye', 'Hand', 'Foot', 'Heart', 'Nose', 'Ear', 'Tooth', 'Skull',
    'Ball', 'Racket', 'Bow and arrow', 'Sword', 'Shield', 'Hammer', 'Saw', 'Nail',
    'Fishing rod', 'Screwdriver', 'Scales', 'Basket', 'Cup', 'Plate', 'Spoon', 'Fork',
    'Knife', 'Kettle', 'Bottle', 'Wrench',
    'Guitar', 'Piano', 'Drum', 'Violin', 'Flute', 'Microphone', 'Television', 'Dice',
    'Shirt', 'Trousers', 'Shoe', 'Hat', 'Ring', 'Crown', 'Robot', 'Ghost',
    'King', 'Pilot', 'Doctor', 'Thief', 'Bride', 'Wizard', 'Clown', 'Snowman',
    'Treasure chest', 'Map', 'Compass', 'Telescope', 'Envelope', 'Gift', 'Birthday cake', 'Anchor',
    'Chain', 'Net', 'Rope', 'Arrow', 'Bomb', 'Box', 'Bench', 'Trophy',
    'Diamond ring', 'Sneakers', 'Royal crown', 'Sunglasses', 'Suitcase', 'Wristwatch', 'Party dress', 'Tuxedo',
    'Headphones', 'Ceiling fan', 'Air conditioner', 'Clothes iron', 'Washing machine', 'Phone charger', 'Computer mouse', 'Laptop',
    'Flash drive', 'Remote control', 'Toothbrush', 'Bar of soap', 'Bath towel', 'Barbecue grill', 'Frying pan', 'Thermos',
    'Mango juice', 'Soda can', 'Mug of coffee', 'Pasta bowl', 'Hot dog', 'Slice of pizza', 'Strawberry', 'Pineapple',
    'Lemon', 'Corn on the cob', 'Tomato', 'Carrot', 'Chilli pepper', 'Spaceship', 'Ambulance', 'Fire truck',
    'Tractor', 'Suspension bridge', 'Train station', 'Warehouse', 'Camping tent', 'Lantern', 'Flashlight', 'Rain umbrella',
    'Lit candle', 'Canvas painting', 'Stone statue', 'Gold medal', 'Trophy cup', 'Referee whistle', 'Pool table', 'Tennis racket',
    'Bird nest', 'Bird feather', 'Beehive', 'Seashell', 'Starfish', 'Jellyfish', 'Playground slide', 'Park swing'
  ]
};


/* --- على نفس الموجة (WAVELENGTH) ------------------------------------------ */
const WAVELENGTH_PAIRS = {
  ar: [
    {"left": "بارد جداً ❄️", "right": "ساخن جداً 🔥"},
    {"left": "رخيص الثمن", "right": "باهظ الثمن للغاية 💎"},
    {"left": "ممل جداً 😴", "right": "ممتع ومثير 🤩"},
    {"left": "آمن تماماً", "right": "شديد الخطورة ⚠️"},
    {"left": "ناعم ورقيق", "right": "خشن وصلب"},
    {"left": "قديم وتاريخي", "right": "مستقبلي وحديث 🚀"},
    {"left": "ضعيف وهش", "right": "قوي وخارق 💪"},
    {"left": "عادة سيئة", "right": "عادة ممتازة ✨"},
    {"left": "سهل التعلم", "right": "شديد الصعوبة"},
    {"left": "عمل شرير 🦹", "right": "عمل بطولي 🦸"},
    {"left": "غير مفيد إطلاقاً", "right": "ضروري للحياة 🧬"},
    {"left": "وجبة خفيفة 🥗", "right": "وجبة دسمة وثقيلة 🍔"},
    {"left": "صوت هامس 🤫", "right": "صاخب ومزعج 📢"},
    {"left": "قوة خارقة تافهة", "right": "قوة خارقة أسطورية"},
    {"left": "فيلم حزين 😢", "right": "فيلم مبهج ومضحك 😂"},
    {"left": "وظيفة شاقة ومجهدة", "right": "وظيفة الأحلام 🌟"},
    {"left": "طبيعي 100%", "right": "صناعي تماماً"},
    {"left": "مريح للأعصاب", "right": "يوتر ويزعج"},
    {"left": "مهارة عادية", "right": "موهبة استثنائية"},
    {"left": "مبالغ في تقديره", "right": "مظلوم ويستحق أكثر"},
    {"left": "حيوان أليف مسالم 🐶", "right": "حيوان متوحش ومفترس 🦈"},
    {"left": "غير صحي 🍟", "right": "صحي ومغذي جداً 🥦"},
    {"left": "سري للغاية 🤫", "right": "يعرفه الجميع 🌍"},
    {"left": "بطيء كالسلاحف 🐢", "right": "سريع كالبرق ⚡"},
    {"left": "موضة قديمة عفى عليها الزمن", "right": "أحدث صيحة عصرية 🕶️"},
    {"left": "رائحته كريهة", "right": "رائحته زكية وعطرة 🌸"},
    {"left": "شخصية خيالية", "right": "شخصية واقعية"},
    {"left": "مكان كئيب ومظلم", "right": "مكان مشرق ومبهج 🏝️"},
    {"left": "اختراع بسيط", "right": "إنجاز علمي عظيم"},
    {"left": "رياضة فردية", "right": "رياضة جماعية"},
    {"left": "صاخب ومهرجان", "right": "هدوء وسكينة 🧘"},
    {"left": "سهل النسيان", "right": "لا يُنسى أبداً 🧠"},
    {"left": "موضة مؤقتة", "right": "كلاسيكي أصيل ⏳"},
    {"left": "صعب الهضم 🤢", "right": "لذيذ وخفيف 😋"},
    {"left": "غير موثوق به 🤥", "right": "صادق وأمين 🤝"},
    {"left": "مكروه جماهيرياً", "right": "محبوب من الجميع ❤️"},
    {"left": "شخص فوضوي 🌪️", "right": "منظم ودقيق جداً 📐"},
    {"left": "موهبة فطرية", "right": "تدريب شاق ومستمر 🏋️"},
    {"left": "مخيف ومرعب 👻", "right": "لطيف وبريء 🧸"},
    {"left": "أحمق وساذج 🤪", "right": "عبقري وديكتاتوري 🧠"},
    {"left": "متفائل دائماً ☀️", "right": "متشائم دائماً 🌧️"},
    {"left": "مريح للجلوس 🛋️", "right": "مؤلم للظهر 🪑"},
    {"left": "مضيعة للوقت ⌛", "right": "استثمار رائع للمستقبل 📈"},
    {"left": "مشهور بالشر 🦹", "right": "مشهور بالخير 🕊️"},
    {"left": "طعم حار جداً 🌶️", "right": "طعم حلو وسكري 🍯"},
    {"left": "كائن فضائي 👽", "right": "كائن أرضي أليف 🐱"},
    {"left": "عادي وبسيط", "right": "معقد ومركب 🧩"},
    {"left": "صوت نشاز 📢", "right": "صوت رخيم وعذب 🎶"},
    {"left": "رياضة هادئة ♟️", "right": "رياضة عنيفة ودموية 🥊"},
    {"left": "سيارة عائلية 🚐", "right": "سيارة سباق خارقة 🏎️"},
    {"left": "مدينة مزدحمة 🏙️", "right": "قرية ريفية هادئة 🌾"},
    {"left": "شخص بخيل 🪙", "right": "كريم ومبذر 💸"},
    {"left": "حجم مجهري 🔬", "right": "حجم عملاق وضخم 🌌"},
    {"left": "قصير الأجل ⏱️", "right": "أبدي وخالد ♾️"},
    {"left": "شتاء قارس 🥶", "right": "صيف حارق 🥵"},
    {"left": "فيلم وثائقي 📽️", "right": "فيلم خيال علمي 🛸"},
    {"left": "أكلة شعبية 🧆", "right": "وجبة ملكية فاخرة 👑"},
    {"left": "عمل روتيني 📄", "right": "مغامرة مثيرة 🧗"},
    {"left": "كائن غبي 🦤", "right": "حيوان ذكي وحربوق 🦊"},
    {"left": "نصيحة كارثية 💣", "right": "نصيحة ذهبية 🏆"},
    {"left": "سرعة سلحفاة 🐢", "right": "سرعة فهد 🐆"},
    {"left": "شخص بارد المشاعر 🧊", "right": "عاطفي وحساس جداً 🥺"},
    {"left": "خفيف كالريشة 🪶", "right": "ثقيل كالحديد 🪨"},
    {"left": "عمل فردي منعزل", "right": "عمل جماعي وتعاوني 🤝"},
    {"left": "شخص متسرع ⚡", "right": "صبور وهادئ البال ⏳"},
    {"left": "حيوان بري 🦓", "right": "حيوان منزلي 🐕"},
    {"left": "أغنية حزينة 🎻", "right": "أغنية راقصة ومبهجة 🕺"},
    {"left": "موقف محرج 🙈", "right": "موقف فخر واعتزاز 🎖️"},
    {"left": "تاريخ قديم 🏺", "right": "تكنولوجيا الغد 🤖"},
    {"left": "شخص عنيد 🐂", "right": "مرن ومتساهل 🌊"},
    {"left": "مكان فوضوي 🏚️", "right": "قصر فخم ومرتب 🏰"},
    {"left": "موهبة غير مفيدة", "right": "مهارة تنقذ الحياة 🩺"},
    {"left": "حلم وردي 🌈", "right": "كابوس مظلم 🧟"},
    {"left": "خطر داهم 🚨", "right": "سلام وأمان تام 🛡️"},
    {"left": "لعبة حظ بحت 🎲", "right": "لعبة ذكاء واستراتيجية ♟️"}
  ],
  en: [
    {"left": "Freezing Cold ❄️", "right": "Boiling Hot 🔥"},
    {"left": "Dirt Cheap", "right": "Priceless Luxury 💎"},
    {"left": "Extremely Boring 😴", "right": "Super Exciting 🤩"},
    {"left": "Completely Safe", "right": "Extremely Dangerous ⚠️"},
    {"left": "Soft & Smooth", "right": "Hard & Rough"},
    {"left": "Ancient History", "right": "Futuristic Sci-Fi 🚀"},
    {"left": "Fragile & Weak", "right": "Indestructible 💪"},
    {"left": "Terrible Habit", "right": "Life-Changing Habit ✨"},
    {"left": "Easy to Learn", "right": "Nearly Impossible to Master"},
    {"left": "Pure Villain 🦹", "right": "Pure Hero 🦸"},
    {"left": "Totally Useless", "right": "Essential for Survival 🧬"},
    {"left": "Light Snack 🥗", "right": "Heavy Feast 🍔"},
    {"left": "Whisper Quiet 🤫", "right": "Deafening Loud 📢"},
    {"left": "Lame Superpower", "right": "God-Tier Superpower"},
    {"left": "Depressing Movie 😢", "right": "Pure Joy Comedy 😂"},
    {"left": "Nightmare Job", "right": "Dream Job 🌟"},
    {"left": "100% Natural", "right": "100% Artificial"},
    {"left": "Super Relaxing", "right": "Stress-Inducing"},
    {"left": "Everyday Skill", "right": "Once-in-a-Generation Talent"},
    {"left": "Overrated", "right": "Severely Underrated"},
    {"left": "Harmless Pet 🐶", "right": "Terrifying Predator 🦈"},
    {"left": "Junk Food 🍟", "right": "Superfood 🥦"},
    {"left": "Top Secret 🤫", "right": "Common Knowledge 🌍"},
    {"left": "Slow as a Snail 🐢", "right": "Lightning Fast ⚡"},
    {"left": "Outdated & Cringe", "right": "Timeless & Cool 🕶️"},
    {"left": "Smells Awful", "right": "Smells Divine 🌸"},
    {"left": "Pure Fiction", "right": "100% Real History"},
    {"left": "Gloomy & Dark", "right": "Paradise Beach 🏝️"},
    {"left": "Trivial Gadget", "right": "Groundbreaking Invention"},
    {"left": "Solo Sport", "right": "Ultimate Team Sport"},
    {"left": "Loud & Chaotic 📢", "right": "Peaceful & Serene 🧘"},
    {"left": "Instantly Forgettable", "right": "Unforgettable Legend 🧠"},
    {"left": "Fleeting Fad", "right": "Timeless Classic ⏳"},
    {"left": "Hard to Digest 🤢", "right": "Delicious & Light 😋"},
    {"left": "Untrustworthy 🤥", "right": "Honest & Loyal 🤝"},
    {"left": "Universally Hated", "right": "Loved by Everyone ❤️"},
    {"left": "Chaotic Mess 🌪️", "right": "Obsessively Organized 📐"},
    {"left": "Pure Natural Talent", "right": "Relentless Hard Work 🏋️"},
    {"left": "Terrifying Monster 👻", "right": "Cute & Harmless 🧸"},
    {"left": "Silly & Dumb 🤪", "right": "Mastermind Genius 🧠"},
    {"left": "Eternal Optimist ☀️", "right": "Hopeless Pessimist 🌧️"},
    {"left": "Super Comfy 🛋️", "right": "Backache Inducing 🪑"},
    {"left": "Total Waste of Time ⌛", "right": "Life Investment 📈"},
    {"left": "Infamous Villain 🦹", "right": "Beloved Hero 🕊️"},
    {"left": "Spicy Inferno 🌶️", "right": "Sweet Honey 🍯"},
    {"left": "Alien Extraterrestrial 👽", "right": "Familiar Earthling 🐱"},
    {"left": "Simple & Plain", "right": "Intricate & Complex 🧩"},
    {"left": "Nails on Chalkboard 📢", "right": "Pure Musical Harmony 🎶"},
    {"left": "Gentle Hobby ♟️", "right": "Brutal Combat Sport 🥊"},
    {"left": "Family Minivan 🚐", "right": "Hypercar Speedster 🏎️"},
    {"left": "Crowded Megacity 🏙️", "right": "Tranquil Countryside 🌾"},
    {"left": "Total Cheapskate 🪙", "right": "Generous Spender 💸"},
    {"left": "Microscopic 🔬", "right": "Cosmic Scale 🌌"},
    {"left": "Temporary Fleeting ⏱️", "right": "Eternal Immortal ♾️"},
    {"left": "Freezing Blizzard 🥶", "right": "Scorching Heatwave 🥵"},
    {"left": "Dry Documentary 📽️", "right": "Wild Sci-Fi Odyssey 🛸"},
    {"left": "Street Snack 🧆", "right": "Royal Banquet 👑"},
    {"left": "Dull Routine 📄", "right": "Adrenaline Rush 🧗"},
    {"left": "Clueless Creature 🦤", "right": "Cunning Genius Animal 🦊"},
    {"left": "Worst Advice Ever 💣", "right": "Priceless Wisdom 🏆"},
    {"left": "Snail Pace 🐢", "right": "Cheetah Sprint 🐆"},
    {"left": "Cold as Ice 🧊", "right": "Super Emotional 🥺"},
    {"left": "Light as a Feather 🪶", "right": "Heavy as an Anvil 🪨"},
    {"left": "Solo Hermit Work", "right": "Total Team Synergy 🤝"},
    {"left": "Hot-headed & Impulsive ⚡", "right": "Zen & Patient ⏳"},
    {"left": "Wild Predator 🦓", "right": "Cuddly House Pet 🐕"},
    {"left": "Tearjerker Ballad 🎻", "right": "High-Energy Banger 🕺"},
    {"left": "Cringe & Awkward 🙈", "right": "Glorious & Proud 🎖️"},
    {"left": "Ancient Relic 🏺", "right": "Cyberpunk Future 🤖"},
    {"left": "Stubborn Mule 🐂", "right": "Easygoing & Adaptable 🌊"},
    {"left": "Dilapidated Shack 🏚️", "right": "Opulent Palace 🏰"},
    {"left": "Useless Party Trick", "right": "Life-Saving Skill 🩺"},
    {"left": "Sweet Dream 🌈", "right": "Terrifying Nightmare 🧟"},
    {"left": "Imminent Hazard 🚨", "right": "Total Safe Haven 🛡️"},
    {"left": "Pure Luck & Chance 🎲", "right": "Pure Tactical Mastery ♟️"}
  ]
};

/* --- مسابقة المعلومات (TRIVIA NIGHT) -------------------------------------- */
const TRIVIA_QUESTIONS = {
  ar: [
    {"q": "ما هو أكبر كوكب في المجموعة الشمسية؟", "choices": ["المريخ", "المشتري", "زحل", "نبتون"], "answer": 1},
    {"q": "ما هي عاصمة أستراليا؟", "choices": ["سيدني", "ملبورن", "كانبرا", "بيرث"], "answer": 2},
    {"q": "كم عدد قارات العالم؟", "choices": ["5", "6", "7", "8"], "answer": 2},
    {"q": "من هو الرسام الذي رسم لوحة الموناليزا؟", "choices": ["بيكاسو", "ليوناردو دي فينشي", "فان جوخ", "مايكل أنجلو"], "answer": 1},
    {"q": "ما هو أطول نهر في العالم؟", "choices": ["الأمازون", "النيل", "الدانوب", "الميسيسيبي"], "answer": 1},
    {"q": "ما هو العنصر الكيميائي الذي رمزه O؟", "choices": ["الذهب", "الأكسجين", "الفوسفور", "الحديد"], "answer": 1},
    {"q": "في أي عام تأسست شركة أبل؟", "choices": ["1976", "1984", "1991", "1998"], "answer": 0},
    {"q": "ما هي الدولة الأكثر فوزاً بكأس العالم لكرة القدم؟", "choices": ["ألمانيا", "إيطاليا", "البرازيل", "الأرجنتين"], "answer": 2},
    {"q": "كم عدد القلوب لدى الأخطبوط؟", "choices": ["1", "2", "3", "4"], "answer": 2},
    {"q": "ما هو الغاز الأكثر وجوداً في الغلاف الجوي للأرض؟", "choices": ["الأكسجين", "النيتروجين", "ثاني أكسيد الكربون", "الهيدروجين"], "answer": 1},
    {"q": "ما هي العملة الرسمية لليابان؟", "choices": ["اليوان", "الوون", "الين", "الدولار"], "answer": 2},
    {"q": "أين تقع أهرامات الجيزة؟", "choices": ["مصر", "المكسيك", "السودان", "بيرو"], "answer": 0},
    {"q": "كم دقيقة في 3 ساعات ونصف؟", "choices": ["180", "200", "210", "240"], "answer": 2},
    {"q": "ما هو المعدن السائل في درجة حرارة الغرفة؟", "choices": ["الزئبق", "الحديد", "الرصاص", "الألومنيوم"], "answer": 0},
    {"q": "من هو مؤلف سلسلة هاري بوتر؟", "choices": ["تولكين", "جيه كيه رولينج", "ستيفن كينج", "جورج مارتن"], "answer": 1},
    {"q": "ما هو الحيوان الأسرع على اليابسة؟", "choices": ["الفهد", "الأسد", "الحصان", "الغزال"], "answer": 0},
    {"q": "ما هي أكبر محيطات العالم مساحة؟", "choices": ["المحيط الأطلسي", "المحيط الهادي", "المحيط الهندي", "المحيط المتجمد"], "answer": 1},
    {"q": "ما هو أسرع عضو في جسم الإنسان حركة؟", "choices": ["القلب", "العين", "اللسان", "الأصابع"], "answer": 1},
    {"q": "كم عدد لاعبي فريق كرة السلة داخل الملعب؟", "choices": ["5", "6", "7", "11"], "answer": 0},
    {"q": "أي دولة تشتهر ببرج إيفل؟", "choices": ["إيطاليا", "فرنسا", "إسبانيا", "إنجلترا"], "answer": 1},
    {"q": "ما هو العضو المسؤول عن ضخ الدم في جسم الإنسان؟", "choices": ["الرئة", "الكبد", "القلب", "المعدة"], "answer": 2},
    {"q": "ما هي أصغر دولة في العالم من حيث المساحة؟", "choices": ["موناكو", "الفاتيكان", "سان مارينو", "ليختنشتاين"], "answer": 1},
    {"q": "من هو مكتشف الجاذبية الأرضية؟", "choices": ["أينشتاين", "نيوتن", "جاليليو", "تسلا"], "answer": 1},
    {"q": "ما هي زهرة اللوتس رمز شهير لأي حضارة قديمة؟", "choices": ["الحضارة الرومانية", "الحضارة الفرعونية", "الحضارة الإغريقية", "حضارة المايا"], "answer": 1},
    {"q": "كم عدد عظام جسم الإنسان البالغ تقريباً؟", "choices": ["156", "206", "256", "306"], "answer": 1},
    {"q": "ما هي عاصمة اليابان؟", "choices": ["طوكيو", "كيوتو", "أوساكا", "هيروشيما"], "answer": 0},
    {"q": "ما هو أكبر حيوان على وجه الأرض؟", "choices": ["الفيل الأفريقي", "الحوت الأزرق", "القرش الأبيض", "الزرافة"], "answer": 1},
    {"q": "كم عدد ألوان قوس قزح؟", "choices": ["5", "6", "7", "8"], "answer": 2},
    {"q": "في أي قارة تقع مصر؟", "choices": ["آسيا", "أوروبا", "أفريقيا", "أمريكا الجنوبية"], "answer": 2},
    {"q": "ما هو أسرع طائر في العالم؟", "choices": ["النسر الذهبي", "صقر الشاهين", "النعامة", "الباشق"], "answer": 1},
    {"q": "ما هو الرمز الكيميائي للذهب؟", "choices": ["Ag", "Au", "Fe", "Cu"], "answer": 1},
    {"q": "من اخترع المصباح الكهربائي العملي؟", "choices": ["توماس إديسون", "نيكولا تسلا", "ألكسندر بيل", "جراهام بيل"], "answer": 0},
    {"q": "ما هي عاصمة إيطاليا؟", "choices": ["ميلانو", "روما", "البندقية", "فلورنسا"], "answer": 1},
    {"q": "كم عدد أيام السنة الكبيسة؟", "choices": ["364", "365", "366", "367"], "answer": 2},
    {"q": "ما هو أكبر كائن حي يعيش على اليابسة؟", "choices": ["وحيد القرن", "الفيل الأفريقي", "الدب القطبي", "فرس النهر"], "answer": 1},
    {"q": "ما هي عاصمة إسبانيا؟", "choices": ["برشلونة", "مدريد", "إشبيلية", "فالنسيا"], "answer": 1},
    {"q": "ما هو الحيوان الذي يُلقب بسفينة الصحراء؟", "choices": ["الحصان", "الجمل", "الوعل", "الضبع"], "answer": 1},
    {"q": "من هو مؤلف ملحمة الإلياذة والأوديسة؟", "choices": ["أفلاطون", "هوميروس", "أرسطو", "سقراط"], "answer": 1},
    {"q": "ما هو أصغر كوكب في المجموعة الشمسية؟", "choices": ["عطارد", "المريخ", "الزهرة", "بلوتو"], "answer": 0},
    {"q": "ما هي عملة بريطانيا الرسمية؟", "choices": ["اليورو", "الجنيه الإسترليني", "الدولار", "الفرنك"], "answer": 1},
    {"q": "كم عدد صمامات قلب الإنسان؟", "choices": ["2", "3", "4", "5"], "answer": 2},
    {"q": "في أي مدينة يقع برج بيزا المائل؟", "choices": ["روما", "بيزا", "فلورنسا", "نابولي"], "answer": 1},
    {"q": "ما هو المعدن الأكثر وفرة في القشرة الأرضية؟", "choices": ["الحديد", "الألومنيوم", "النحاس", "الكالسيوم"], "answer": 1},
    {"q": "ما هو البحر الذي يفصل بين قارتي إفريقيا وأوروبا؟", "choices": ["البحر الأحمر", "البحر المتوسط", "بحر البلطيق", "بحر الشمال"], "answer": 1},
    {"q": "من هو مؤسس علم الجبر؟", "choices": ["ابن الهيثم", "الخوارزمي", "ابن سينا", "جابر بن حيان"], "answer": 1},
    {"q": "ما هو الطائر الذي لا يطير وتعد بيضته الأكبر حجماً؟", "choices": ["البطريق", "النعامة", "الكيوي", "الإيمو"], "answer": 1},
    {"q": "ما هي عاصمة روسيا؟", "choices": ["سان بطرسبرج", "موسكو", "كازان", "سوتشي"], "answer": 1},
    {"q": "كم ضلعاً للمثلث؟", "choices": ["2", "3", "4", "5"], "answer": 1},
    {"q": "ما هي أكبر جزيرة في العالم؟", "choices": ["مدغشقر", "جرينلاند", "بورنيو", "آيسلندا"], "answer": 1},
    {"q": "ما هو العضو الذي يمتص معظم العناصر الغذائية؟", "choices": ["المعدة", "الأمعاء الدقيقة", "القولون", "الكبد"], "answer": 1},
    {"q": "ما هو صوت الحصان؟", "choices": ["صهيل", "نهيق", "نباح", "خوار"], "answer": 0},
    {"q": "في أي قارة تقع البرازيل؟", "choices": ["أمريكا الشمالية", "أمريكا الجنوبية", "أفريقيا", "آسيا"], "answer": 1},
    {"q": "ما هي درجة غليان الماء المئوية عند مستوى سطح البحر؟", "choices": ["90", "100", "110", "120"], "answer": 1},
    {"q": "ما هي عاصمة كندا؟", "choices": ["تورونتو", "فانكوفر", "أوتاوا", "مونتريال"], "answer": 2},
    {"q": "من هو أول إنسان صعد إلى الفضاء؟", "choices": ["نيل أرمسترونج", "يوري جاجارين", "باز ألدرين", "جون جلين"], "answer": 1},
    {"q": "كم عدد أسنان الإنسان البالغ الطبيعية؟", "choices": ["28", "30", "32", "34"], "answer": 2},
    {"q": "ما هو الحيوان الذي يستطيع النوم وهو واقف؟", "choices": ["الحصان", "الكلب", "القط", "الدب"], "answer": 0},
    {"q": "ما هي عاصمة ألمانيا؟", "choices": ["ميونخ", "برلين", "فرانكفورت", "هامبورغ"], "answer": 1},
    {"q": "ما هي المادة التي تشكل قرن وحيد القرن؟", "choices": ["العظم", "الكيراتين", "العاج", "الغضروف"], "answer": 1},
    {"q": "أي كوكب يُعرف بالكوكب الأحمر؟", "choices": ["المشتري", "المريخ", "الزهرة", "عطارد"], "answer": 1},
    {"q": "ما هو أكبر خليج في العالم؟", "choices": ["خليج المكسيك", "خليج البنغال", "الخليج العربي", "خليج هودسون"], "answer": 1},
    {"q": "ما هي الدولة التي تمتلك أكبر عدد من الأهرامات في العالم؟", "choices": ["مصر", "المكسيك", "السودان", "بيرو"], "answer": 2},
    {"q": "ما هو صوت الأسد؟", "choices": ["فحيح", "زئير", "عواء", "مواء"], "answer": 1},
    {"q": "في أي عام سقط جدار برلين؟", "choices": ["1987", "1989", "1991", "1993"], "answer": 1},
    {"q": "ما هو الكائن البحري ذو ثمانية أذرع؟", "choices": ["الحبار", "الأخطبوط", "قنديل البحر", "نجم البحر"], "answer": 1},
    {"q": "كم عدد لاعبي فريق كرة القدم داخل الملعب؟", "choices": ["9", "10", "11", "12"], "answer": 2},
    {"q": "ما هي عاصمة الصين؟", "choices": ["شنغهاي", "بكين", "هونغ كونغ", "قوانغتشو"], "answer": 1},
    {"q": "ما هو أصلح نوع من الأشجار لإنتاج شراب القيقب؟", "choices": ["شجرة البلوط", "شجرة القيقب السكري", "شجرة الصنوبر", "شجرة الصفصاف"], "answer": 1},
    {"q": "ما هو أكبر عضو في جسم الإنسان؟", "choices": ["الكبد", "الجلد", "الرئتان", "الدماغ"], "answer": 1},
    {"q": "ما هي المدينة التي يُطلق عليها مدينة الضباب؟", "choices": ["باريس", "لندن", "نيويورك", "برلين"], "answer": 1},
    {"q": "ما هي أصغر قارة في العالم من حيث المساحة؟", "choices": ["أوروبا", "أستراليا", "أمريكا الجنوبية", "القارة القطبية"], "answer": 1},
    {"q": "ما هو الغاز الذي تمتصه النباتات أثناء البناء الضوئي؟", "choices": ["الأكسجين", "ثاني أكسيد الكربون", "النيتروجين", "الهيليوم"], "answer": 1},
    {"q": "كم عدد حلقات العلم الأولمبي؟", "choices": ["4", "5", "6", "7"], "answer": 1},
    {"q": "من هو مخترع الهاتف؟", "choices": ["توماس إديسون", "ألكسندر جراهام بيل", "تسلا", "ماركوني"], "answer": 1},
    {"q": "ما هي الدولة المصنفة كأكبر منتج للبن والقهوة في العالم؟", "choices": ["كولومبيا", "إثيوبيا", "البرازيل", "فيتنام"], "answer": 2},
    {"q": "ما هو أطول جبل في العالم فوق مستوى سطح البحر؟", "choices": ["كليمنجارو", "إفرست", "كيه 2", "مون بلان"], "answer": 1},
    {"q": "ما هو المعدن الرئيسي المستخدم في صناعة المغناطيس الدائم؟", "choices": ["النحاس", "الحديد", "الألومنيوم", "الذهب"], "answer": 1},
    {"q": "ما هي عاصمة المملكة العربية السعودية؟", "choices": ["جدة", "الرياض", "الدمام", "مكة المكرمة"], "answer": 1},
    {"q": "كم ثانية في الساعة الواحدة؟", "choices": ["1800", "2400", "3600", "4200"], "answer": 2},
    {"q": "من رسم لوحة العشاء الأخير الشهيرة؟", "choices": ["مايكل أنجلو", "ليوناردو دي فينشي", "رافاييل", "كارافاجيو"], "answer": 1},
    {"q": "ما هو الكوكب الأقرب للشمس؟", "choices": ["الزهرة", "عطارد", "الأرض", "المريخ"], "answer": 1},
    {"q": "ما هي عاصمة فرنسا؟", "choices": ["مارسيليا", "باريس", "ليون", "نيس"], "answer": 1},
    {"q": "ما هي أسرع سمكة في المحيطات؟", "choices": ["سمكة التونة", "سمكة الشراع", "سمكة القرش", "سمكة السيف"], "answer": 1},
    {"q": "في أي دولة تقع مدينة البتراء الأثرية؟", "choices": ["مصر", "الأردن", "العراق", "لبنان"], "answer": 1},
    {"q": "ما هو اسم صغير الكلب؟", "choices": ["جرو", "شبل", "مهر", "حمل"], "answer": 0},
    {"q": "ما هو الحيوان الذي لا يشرب الماء طوال حياته؟", "choices": ["الجمل", "فأر الكنغر", "الضب", "العقرب"], "answer": 1},
    {"q": "ما هي عاصمة تركيا؟", "choices": ["إسطنبول", "أنقرة", "إزمير", "أنطاليا"], "answer": 1},
    {"q": "ما هو الشيء الذي كلما زاد نقص؟", "choices": ["المال", "العمر", "الحفرة", "العلم"], "answer": 1},
    {"q": "ما هو العلم الذي يدرس طبقات الأرض والصخور؟", "choices": ["علم الأحياء", "علم الجيولوجيا", "علم الفلك", "علم الأرصاد"], "answer": 1},
    {"q": "كم عدد كواكب المجموعة الشمسية المعترف بها رسمياً؟", "choices": ["7", "8", "9", "10"], "answer": 1},
    {"q": "ما هو الرمز الكيميائي للحديد؟", "choices": ["Ir", "Fe", "In", "F"], "answer": 1},
    {"q": "ما هي عاصمة اليونان؟", "choices": ["أثينا", "سالونيك", "سبارتا", "كورنثوس"], "answer": 0},
    {"q": "من هو أول رئيس للولايات المتحدة الأمريكية؟", "choices": ["توماس جيفرسون", "جورج واشنطن", "أبراهام لينكولن", "جون آدامز"], "answer": 1},
    {"q": "ما هو صوت الضفدع؟", "choices": ["نقيق", "خرير", "هديل", "حفيف"], "answer": 0},
    {"q": "ما هي الدولة الأكثر سكاناً في قارة إفريقيا؟", "choices": ["مصر", "نيجيريا", "جنوب إفريقيا", "إثيوبيا"], "answer": 1},
    {"q": "ما هو الحيوان الملقب بملك الغابة؟", "choices": ["النمر", "الأسد", "الفهد", "الدب"], "answer": 1},
    {"q": "ما هي العملة الرسمية في دولة الكويت؟", "choices": ["الريال", "الدينار الكويتي", "الدرهم", "الجنيه"], "answer": 1},
    {"q": "ما هو الجهاز المستخدم لقياس الزلازل وهزات الأرض؟", "choices": ["البارومتر", "السيزموجراف", "الترمومتر", "الأنيمومتر"], "answer": 1},
    {"q": "ما هي عاصمة كوريا الجنوبية؟", "choices": ["بوسان", "سول", "إنتشون", "دايغو"], "answer": 1},
    {"q": "ما هو الجزء الملون في عين الإنسان؟", "choices": ["البؤبؤ", "القزحية", "الشبكية", "القرنية"], "answer": 1},
    {"q": "من هو مؤلف رواية البؤساء؟", "choices": ["فيكتور هوجو", "ألكسندر دوما", "تشارلز ديكنز", "ليو تولستوي"], "answer": 0},
    {"q": "كم عدد أوتار الجيتار الكلاسيكي القياسي؟", "choices": ["4", "5", "6", "7"], "answer": 2},
    {"q": "ما هي عاصمة الأرجنتين؟", "choices": ["قرطبة", "بوينس آيرس", "روزاريو", "ميندوزا"], "answer": 1},
    {"q": "ما هي أكبر صحراء حارة في العالم؟", "choices": ["صحراء جوبي", "الصحراء الكبرى", "صحراء كالهاري", "صحراء أتاكاما"], "answer": 1},
    {"q": "ما هو العنصر الكيميائي الأكثر وفرة في الكون؟", "choices": ["الهيليوم", "الهيدروجين", "الأكسجين", "الكربون"], "answer": 1},
    {"q": "ما هو الطائر الذي يرمز إلى السلام؟", "choices": ["النسر", "الحمامة", "البجعة", "الطاووس"], "answer": 1},
    {"q": "في أي مدينة أمريكية يقع تمثال الحرية؟", "choices": ["واشنطن", "نيويورك", "لوس أنجلوس", "شيكاغو"], "answer": 1},
    {"q": "ما هي مدة حمل أنثى الفيل تقريباً؟", "choices": ["9 أشهر", "12 شهراً", "22 شهراً", "28 شهراً"], "answer": 2},
    {"q": "ما هو المضاد الحيوي الأول الذي تم اكتشافه بواسطة ألكسندر فليمنج؟", "choices": ["الأموكسيسيلين", "البنسلين", "السيفالوسبورين", "التتراسيكلين"], "answer": 1},
    {"q": "ما هي عاصمة المغرب؟", "choices": ["الدار البيضاء", "الرباط", "مراكش", "طنجة"], "answer": 1},
    {"q": "كم عدد اللاعبين في فريق الكرة الطائرة داخل الملعب؟", "choices": ["5", "6", "7", "8"], "answer": 1},
    {"q": "ما هو اسم المسبار الذي هبط على المريخ عام 2021؟", "choices": ["كيوريوسيتي", "برسيفيرنس", "أبولو", "فوييجر"], "answer": 1},
    {"q": "ما هو أعلى شلال في العالم؟", "choices": ["شلالات نياجرا", "شلالات أنجل", "شلالات فيكتوريا", "شلالات إجوازو"], "answer": 1},
    {"q": "من كتب مسرحية روميو وجولييت الشهيرة؟", "choices": ["تشارلز ديكنز", "وليم شكسبير", "مارك توين", "أوسكار وايلد"], "answer": 1},
    {"q": "ما هي عاصمة هولندا؟", "choices": ["روتردام", "أمستردام", "لاهاي", "أوترخت"], "answer": 1},
    {"q": "ما هو الحيوان الذي يستطيع تغيير لونه للتمويه؟", "choices": ["الأرنب", "الحرباء", "التمساح", "الضفدع"], "answer": 1},
    {"q": "ما هي الوحدة الأساسية لقياس شدة التيار الكهربائي؟", "choices": ["الفولت", "الأمبير", "الأوم", "الواط"], "answer": 1},
    {"q": "في أي عام أقيمت أول دورة ألعاب أولمبية حديثة؟", "choices": ["1886", "1896", "1904", "1912"], "answer": 1},
    {"q": "ما هي عاصمة البرتغال؟", "choices": ["بورتو", "لشبونة", "براغا", "فارو"], "answer": 1},
    {"q": "ما هو المشروب الأكثر استهلاكاً في العالم بعد الماء؟", "choices": ["القهوة", "الشاي", "الحليب", "العصير"], "answer": 1},
    {"q": "ما هي عاصمة السويد؟", "choices": ["أوسلو", "ستوكهولم", "كوبنهاجن", "هلسنكي"], "answer": 1},
    {"q": "كم عدد صمامات الأمان في مفاعل تشيرنوبل؟", "choices": ["12", "24", "48", "96"], "answer": 1},
    {"q": "ما هو الكوكب الذي يمتلك حلقات مذهلة مشهورة تدور حوله؟", "choices": ["المشتري", "زحل", "أورانوس", "نبتون"], "answer": 1},
    {"q": "ما هي عاصمة دولة الإمارات العربية المتحدة؟", "choices": ["دبي", "أبوظبي", "الشارقة", "عجمان"], "answer": 1},
    {"q": "ما هو الحجر الكريم المكون من الكربون النقي بنسبة 100%؟", "choices": ["الزمرد", "الألماس", "الياقوت", "الفيروز"], "answer": 1},
    {"q": "ما هو أصغر طائر في العالم؟", "choices": ["العصفور الدوري", "طنان النحل", "السنونو", "الحسون"], "answer": 1},
    {"q": "في أي عام تم إطلاق أول قمر صناعي (سبوتنيك 1)؟", "choices": ["1947", "1957", "1969", "1975"], "answer": 1},
    {"q": "ما هي عاصمة النرويج؟", "choices": ["ستوكهولم", "أوسلو", "بيرغن", "تروندهايم"], "answer": 1},
    {"q": "ما هو أطول عظم في جسم الإنسان؟", "choices": ["عظم الساعد", "عظم الفخذ", "عظم الترقوة", "عظم الساق"], "answer": 1},
    {"q": "ما هي الدولة المشهورة بصناعة الساعات والشوكولاتة الفاخرة؟", "choices": ["بلجيكا", "سويسرا", "النمسا", "الدنمارك"], "answer": 1},
    {"q": "كم عدد كرات البلياردو في لعبة الثماني كرات القياسية؟", "choices": ["15", "16", "17", "21"], "answer": 1},
    {"q": "ما هي عاصمة النمسا؟", "choices": ["فيينا", "سالزبورغ", "إنسبروك", "غراتس"], "answer": 0},
    {"q": "ما هو نوع الطاقة المخزنة في بطارية السيارة؟", "choices": ["طاقة حركية", "طاقة كيميائية", "طاقة نووية", "طاقة شمسية"], "answer": 1},
    {"q": "ما هو الاسم الآخر لمدينة القسطنطينية التاريخية؟", "choices": ["أثينا", "إسطنبول", "الإسكندرية", "أنطاكية"], "answer": 1},
    {"q": "ما هو الحيوان الثديي الوحيد القادر على الطيران الحقيقي؟", "choices": ["السنجاب الطائر", "الخفاش", "الكولا", "الخلد"], "answer": 1},
    {"q": "ما هي عاصمة بلجيكا والاتحاد الأوروبي؟", "choices": ["أمستردام", "بروكسل", "ستراسبورغ", "لوكسمبورغ"], "answer": 1},
    {"q": "ما هي سرعة الضوء في الفراغ تقريباً بالكيلومتر في الثانية؟", "choices": ["150,000", "300,000", "450,000", "600,000"], "answer": 1},
    {"q": "كم عدد الأسابيع في السنة الميلادية الواحدة تقريباً؟", "choices": ["48", "50", "52", "54"], "answer": 2},
    {"q": "ما هي الدولة صاحبة أكبر مساحة جغرافية في العالم؟", "choices": ["كندا", "روسيا", "الصين", "الولايات المتحدة"], "answer": 1},
    {"q": "ما هو الغاز الشائع استخدامه لملء بالونات الحفلات لتطفو في الهواء؟", "choices": ["الهيدروجين", "الهيليوم", "النيتروجين", "الأرجون"], "answer": 1},
    {"q": "من هو العالم الذي صاغ النظرية النسبية الشهيرة؟", "choices": ["إسحاق نيوتن", "ألبرت أينشتاين", "نيلز بور", "ريتشارد فاينمان"], "answer": 1},
    {"q": "ما هي عاصمة المكسيك؟", "choices": ["كانكون", "مكسيكو سيتي", "غوادالاخارا", "مونتيري"], "answer": 1},
    {"q": "كم عدد مربعات رقعة الشطرنج الإجمالية؟", "choices": ["49", "64", "81", "100"], "answer": 1},
    {"q": "ما هي عاصمة البرازيل السياسية الرسمية؟", "choices": ["ريو دي جانيرو", "برازيليا", "ساو باولو", "سلفادور"], "answer": 1},
    {"q": "ما هو أكبر طائر جارح في العالم؟", "choices": ["العقاب الفلبيني", "كندور الأنديز", "النسر أبيض الذيل", "صقر الجير"], "answer": 1},
    {"q": "من اخترع الطباعة بالحروف المعدنية المتحركة في أوروبا؟", "choices": ["جاليليو", "يوهانس جوتنبرج", "ليوناردو دي فينشي", "كوبرنيكوس"], "answer": 1},
    {"q": "ما هي عاصمة الدنمارك؟", "choices": ["أوسلو", "كوبنهاجن", "ستوكهولم", "هلسنكي"], "answer": 1},
    {"q": "ما هو اسم أشهر سفينة غرقت في رحلتها الأولى عام 1912؟", "choices": ["بريتانيك", "تيتانيك", "لوسيتانيا", "كوين ماري"], "answer": 1},
    {"q": "ما هي أصغر عظمة في جسم الإنسان؟", "choices": ["المطرقة", "الركاب", "السندان", "الترقوة"], "answer": 1},
    {"q": "ما هي عاصمة أيرلندا؟", "choices": ["بلفاست", "دبلن", "كورك", "غالواي"], "answer": 1}
  ],
  en: [
    {"q": "Which planet is the largest in our Solar System?", "choices": ["Mars", "Jupiter", "Saturn", "Neptune"], "answer": 1},
    {"q": "What is the capital of Australia?", "choices": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": 2},
    {"q": "How many continents are there on Earth?", "choices": ["5", "6", "7", "8"], "answer": 2},
    {"q": "Who painted the Mona Lisa?", "choices": ["Pablo Picasso", "Leonardo da Vinci", "Vincent van Gogh", "Michelangelo"], "answer": 1},
    {"q": "What is the longest river in the world?", "choices": ["Amazon", "Nile", "Danube", "Mississippi"], "answer": 1},
    {"q": "What is the chemical symbol for Oxygen?", "choices": ["Ox", "O", "Og", "Om"], "answer": 1},
    {"q": "In what year was Apple Inc. founded?", "choices": ["1976", "1984", "1991", "1998"], "answer": 0},
    {"q": "Which country has won the most FIFA World Cups?", "choices": ["Germany", "Italy", "Brazil", "Argentina"], "answer": 2},
    {"q": "How many hearts does an octopus have?", "choices": ["1", "2", "3", "4"], "answer": 2},
    {"q": "Which gas is most abundant in Earth's atmosphere?", "choices": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "answer": 1},
    {"q": "What is the official currency of Japan?", "choices": ["Yuan", "Won", "Yen", "Dollar"], "answer": 2},
    {"q": "Where are the Great Pyramids of Giza located?", "choices": ["Egypt", "Mexico", "Sudan", "Peru"], "answer": 0},
    {"q": "How many minutes are in 3 and a half hours?", "choices": ["180", "200", "210", "240"], "answer": 2},
    {"q": "Which metal is liquid at room temperature?", "choices": ["Mercury", "Iron", "Lead", "Aluminum"], "answer": 0},
    {"q": "Who wrote the Harry Potter fantasy book series?", "choices": ["J.R.R. Tolkien", "J.K. Rowling", "Stephen King", "George R.R. Martin"], "answer": 1},
    {"q": "What is the fastest land animal in the world?", "choices": ["Cheetah", "Lion", "Horse", "Gazelle"], "answer": 0},
    {"q": "What is the largest ocean on planet Earth?", "choices": ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"], "answer": 1},
    {"q": "Which human muscle is the fastest to react?", "choices": ["Heart", "Eye muscle", "Tongue", "Biceps"], "answer": 1},
    {"q": "How many players are on the court per team in basketball?", "choices": ["5", "6", "7", "11"], "answer": 0},
    {"q": "In which country is the Eiffel Tower situated?", "choices": ["Italy", "France", "Spain", "England"], "answer": 1},
    {"q": "Which organ is responsible for pumping blood through the body?", "choices": ["Lungs", "Liver", "Heart", "Stomach"], "answer": 2},
    {"q": "What is the smallest country in the world by land area?", "choices": ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], "answer": 1},
    {"q": "Who famously formulated the universal law of gravitation?", "choices": ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], "answer": 1},
    {"q": "The lotus flower was a sacred symbol of which ancient civilization?", "choices": ["Roman", "Ancient Egyptian", "Greek", "Mayan"], "answer": 1},
    {"q": "How many bones are in the adult human skeleton?", "choices": ["156", "206", "256", "306"], "answer": 1},
    {"q": "What is the capital of Japan?", "choices": ["Tokyo", "Kyoto", "Osaka", "Hiroshima"], "answer": 0},
    {"q": "What is the largest living animal on Earth?", "choices": ["African Elephant", "Blue Whale", "Great White Shark", "Giraffe"], "answer": 1},
    {"q": "How many colors are in a traditional rainbow?", "choices": ["5", "6", "7", "8"], "answer": 2},
    {"q": "On which continent is Egypt located?", "choices": ["Asia", "Europe", "Africa", "South America"], "answer": 2},
    {"q": "What is the fastest diving bird in the world?", "choices": ["Golden Eagle", "Peregrine Falcon", "Ostrich", "Hawk"], "answer": 1},
    {"q": "What is the chemical symbol for Gold?", "choices": ["Ag", "Au", "Fe", "Cu"], "answer": 1},
    {"q": "Who invented the practical incandescent electric lightbulb?", "choices": ["Thomas Edison", "Nikola Tesla", "Alexander Bell", "James Watt"], "answer": 0},
    {"q": "What is the capital city of Italy?", "choices": ["Milan", "Rome", "Venice", "Florence"], "answer": 1},
    {"q": "How many days are in a leap year?", "choices": ["364", "365", "366", "367"], "answer": 2},
    {"q": "What is the largest land mammal on planet Earth?", "choices": ["Rhinoceros", "African Elephant", "Polar Bear", "Hippopotamus"], "answer": 1},
    {"q": "What is the capital city of Spain?", "choices": ["Barcelona", "Madrid", "Seville", "Valencia"], "answer": 1},
    {"q": "Which animal is famously known as the 'Ship of the Desert'?", "choices": ["Horse", "Camel", "Llama", "Hyena"], "answer": 1},
    {"q": "Who is credited with composing the ancient epic poems The Iliad and The Odyssey?", "choices": ["Plato", "Homer", "Aristotle", "Socrates"], "answer": 1},
    {"q": "What is the smallest planet in our Solar System?", "choices": ["Mercury", "Mars", "Venus", "Pluto"], "answer": 0},
    {"q": "What is the official currency of the United Kingdom?", "choices": ["Euro", "Pound Sterling", "Dollar", "Franc"], "answer": 1},
    {"q": "How many valves are there in the human heart?", "choices": ["2", "3", "4", "5"], "answer": 2},
    {"q": "In which Italian town is the Leaning Tower located?", "choices": ["Rome", "Pisa", "Florence", "Naples"], "answer": 1},
    {"q": "Which metal is the most abundant in the Earth's crust?", "choices": ["Iron", "Aluminum", "Copper", "Calcium"], "answer": 1},
    {"q": "Which sea separates the continents of Europe and Africa?", "choices": ["Red Sea", "Mediterranean Sea", "Baltic Sea", "North Sea"], "answer": 1},
    {"q": "Which medieval mathematician is regarded as the father of Algebra?", "choices": ["Al-Haytham", "Al-Khwarizmi", "Avicenna", "Jabir ibn Hayyan"], "answer": 1},
    {"q": "Which flightless bird lays the largest egg relative to bird species?", "choices": ["Penguin", "Ostrich", "Kiwi", "Emu"], "answer": 1},
    {"q": "What is the capital city of Russia?", "choices": ["Saint Petersburg", "Moscow", "Kazan", "Sochi"], "answer": 1},
    {"q": "How many sides does a geometric triangle have?", "choices": ["2", "3", "4", "5"], "answer": 1},
    {"q": "What is the largest island in the world by surface area?", "choices": ["Madagascar", "Greenland", "Borneo", "Iceland"], "answer": 1},
    {"q": "Which human digestive organ absorbs the vast majority of nutrients?", "choices": ["Stomach", "Small Intestine", "Colon", "Liver"], "answer": 1},
    {"q": "What sound does a horse produce?", "choices": ["Neigh", "Bray", "Bark", "Moo"], "answer": 0},
    {"q": "On which continent is Brazil situated?", "choices": ["North America", "South America", "Africa", "Asia"], "answer": 1},
    {"q": "What is the boiling point of water at sea level in Celsius?", "choices": ["90°C", "100°C", "110°C", "120°C"], "answer": 1},
    {"q": "What is the national capital of Canada?", "choices": ["Toronto", "Vancouver", "Ottawa", "Montreal"], "answer": 2},
    {"q": "Who was the first human being to journey into outer space?", "choices": ["Neil Armstrong", "Yuri Gagarin", "Buzz Aldrin", "John Glenn"], "answer": 1},
    {"q": "How many teeth does a typical adult human have (including wisdom)?", "choices": ["28", "30", "32", "34"], "answer": 2},
    {"q": "Which animal can famously sleep while standing upright on its feet?", "choices": ["Horse", "Dog", "Cat", "Bear"], "answer": 0},
    {"q": "What is the capital city of Germany?", "choices": ["Munich", "Berlin", "Frankfurt", "Hamburg"], "answer": 1},
    {"q": "Rhino horns are predominantly made of which biological protein substance?", "choices": ["Bone", "Keratin", "Ivory", "Cartilage"], "answer": 1},
    {"q": "Which astronomical planet is nicknamed 'The Red Planet'?", "choices": ["Jupiter", "Mars", "Venus", "Mercury"], "answer": 1},
    {"q": "What is the largest bay or gulf in the world by open area?", "choices": ["Gulf of Mexico", "Bay of Bengal", "Persian Gulf", "Hudson Bay"], "answer": 1},
    {"q": "Which country possesses the highest number of ancient pyramids in the world?", "choices": ["Egypt", "Mexico", "Sudan", "Peru"], "answer": 2},
    {"q": "What vocalization sound is the signature roar of a male lion?", "choices": ["Hiss", "Roar", "Howl", "Growl"], "answer": 1},
    {"q": "In which historic year did the Berlin Wall fall?", "choices": ["1987", "1989", "1991", "1993"], "answer": 1},
    {"q": "Which oceanic cephalopod creature has exactly eight arms?", "choices": ["Squid", "Octopus", "Jellyfish", "Starfish"], "answer": 1},
    {"q": "How many outfield plus goalkeeper players are on pitch per soccer team?", "choices": ["9", "10", "11", "12"], "answer": 2},
    {"q": "What is the capital city of the People's Republic of China?", "choices": ["Shanghai", "Beijing", "Hong Kong", "Guangzhou"], "answer": 1},
    {"q": "Which tree species is the primary source of sweet maple syrup?", "choices": ["Oak Tree", "Sugar Maple", "Pine Tree", "Willow Tree"], "answer": 1},
    {"q": "What is the largest internal or external organ of the human body?", "choices": ["Liver", "Skin", "Lungs", "Brain"], "answer": 1},
    {"q": "Which world capital is historic nicknamed 'The Big Smoke' / 'City of Fog'?", "choices": ["Paris", "London", "New York", "Berlin"], "answer": 1},
    {"q": "What is the smallest continent on Earth by total land area?", "choices": ["Europe", "Australia", "South America", "Antarctica"], "answer": 1},
    {"q": "Which atmospheric gas do green plants absorb during daytime photosynthesis?", "choices": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], "answer": 1},
    {"q": "How many interlocking rings make up the official Olympic symbol?", "choices": ["4", "5", "6", "7"], "answer": 1},
    {"q": "Who is credited with patenting the first practical acoustic telephone?", "choices": ["Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi"], "answer": 1},
    {"q": "Which nation is the world's leading grower and producer of raw coffee beans?", "choices": ["Colombia", "Ethiopia", "Brazil", "Vietnam"], "answer": 2},
    {"q": "What is the highest mountain peak on planet Earth above sea level?", "choices": ["Mount Kilimanjaro", "Mount Everest", "K2", "Mont Blanc"], "answer": 1},
    {"q": "Which ferromagnetic metal is primarily used to forge permanent magnets?", "choices": ["Copper", "Iron", "Aluminum", "Gold"], "answer": 1},
    {"q": "What is the capital city of the Kingdom of Saudi Arabia?", "choices": ["Jeddah", "Riyadh", "Dammam", "Mecca"], "answer": 1},
    {"q": "How many seconds are contained in one standard astronomical hour?", "choices": ["1,800", "2,400", "3,600", "4,200"], "answer": 2},
    {"q": "Who painted the iconic Renaissance mural masterpiece 'The Last Supper'?", "choices": ["Michelangelo", "Leonardo da Vinci", "Raphael", "Caravaggio"], "answer": 1},
    {"q": "Which planetary body orbits closest to our central Sun?", "choices": ["Venus", "Mercury", "Earth", "Mars"], "answer": 1},
    {"q": "What is the capital city of France?", "choices": ["Marseille", "Paris", "Lyon", "Nice"], "answer": 1},
    {"q": "Which magnificent ocean fish is recognized as the fastest swimmer in the sea?", "choices": ["Bluefin Tuna", "Sailfish", "Mako Shark", "Swordfish"], "answer": 1},
    {"q": "In which modern Middle Eastern country is the rose-red rock city of Petra located?", "choices": ["Egypt", "Jordan", "Iraq", "Lebanon"], "answer": 1},
    {"q": "What is the biological term for a baby dog?", "choices": ["Puppy", "Cub", "Foal", "Kitten"], "answer": 0},
    {"q": "Which desert animal can survive its entire lifespan without ever drinking liquid water?", "choices": ["Camel", "Kangaroo Rat", "Fennec Fox", "Scorpion"], "answer": 1},
    {"q": "What is the capital city of Turkey?", "choices": ["Istanbul", "Ankara", "Izmir", "Antalya"], "answer": 1},
    {"q": "What is the scientific study of planet Earth's physical structure and rocks?", "choices": ["Biology", "Geology", "Astronomy", "Meteorology"], "answer": 1},
    {"q": "How many recognized planets are officially in our Solar System?", "choices": ["7", "8", "9", "10"], "answer": 1},
    {"q": "What is the chemical symbol for metallic Iron on the periodic table?", "choices": ["Ir", "Fe", "In", "F"], "answer": 1},
    {"q": "What is the ancient and modern capital city of Greece?", "choices": ["Athens", "Thessaloniki", "Sparta", "Corinth"], "answer": 0},
    {"q": "Who served as the very first President of the United States?", "choices": ["Thomas Jefferson", "George Washington", "Abraham Lincoln", "John Adams"], "answer": 1},
    {"q": "What distinct sound do frogs emit in wetlands?", "choices": ["Croak", "Squeak", "Chirp", "Purr"], "answer": 0},
    {"q": "Which African sovereign state holds the largest human population?", "choices": ["Egypt", "Nigeria", "South Africa", "Ethiopia"], "answer": 1},
    {"q": "Which magnificent apex feline is traditionally hailed as 'King of the Jungle'?", "choices": ["Tiger", "Lion", "Leopard", "Jaguar"], "answer": 1},
    {"q": "What is the official currency denomination of Kuwait?", "choices": ["Riyal", "Kuwaiti Dinar", "Dirham", "Pound"], "answer": 1},
    {"q": "What scientific instrument records and measures seismic tremors and earthquakes?", "choices": ["Barometer", "Seismograph", "Thermometer", "Anemometer"], "answer": 1},
    {"q": "What is the capital city of South Korea?", "choices": ["Busan", "Seoul", "Incheon", "Daegu"], "answer": 1},
    {"q": "What is the colored circular diaphragm structure inside the human eye?", "choices": ["Pupil", "Iris", "Retina", "Cornea"], "answer": 1},
    {"q": "Who penned the legendary French literary novel 'Les Misérables'?", "choices": ["Victor Hugo", "Alexandre Dumas", "Charles Dickens", "Leo Tolstoy"], "answer": 0},
    {"q": "How many strings are found on a standard classical acoustic guitar?", "choices": ["4", "5", "6", "7"], "answer": 2},
    {"q": "What is the capital city of Argentina?", "choices": ["Cordoba", "Buenos Aires", "Rosario", "Mendoza"], "answer": 1},
    {"q": "What is the largest non-polar hot desert on Earth?", "choices": ["Gobi Desert", "Sahara Desert", "Kalahari Desert", "Atacama Desert"], "answer": 1},
    {"q": "Which chemical element is the most abundant throughout the known Universe?", "choices": ["Helium", "Hydrogen", "Oxygen", "Carbon"], "answer": 1},
    {"q": "Which gentle bird is widely embraced across cultures as a symbol of Peace?", "choices": ["Eagle", "Dove", "Swan", "Peacock"], "answer": 1},
    {"q": "In which American harbor island does the Statue of Liberty stand tall?", "choices": ["Washington Harbor", "New York Harbor", "Los Angeles", "Chicago"], "answer": 1},
    {"q": "What is the gestation period duration of a female African Elephant?", "choices": ["9 months", "12 months", "22 months", "28 months"], "answer": 2},
    {"q": "Which breakthrough antibiotic miracle drug was discovered by Alexander Fleming?", "choices": ["Amoxicillin", "Penicillin", "Cephalosporin", "Tetracycline"], "answer": 1},
    {"q": "What is the administrative capital city of Morocco?", "choices": ["Casablanca", "Rabat", "Marrakech", "Tangier"], "answer": 1},
    {"q": "How many players are on court per side in competitive indoor volleyball?", "choices": ["5", "6", "7", "8"], "answer": 1},
    {"q": "Which Mars exploration rover touched down in Jezero Crater in 2021?", "choices": ["Curiosity", "Perseverance", "Apollo", "Voyager"], "answer": 1},
    {"q": "What is the highest uninterrupted waterfall cascade in the world?", "choices": ["Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls"], "answer": 1},
    {"q": "Who authored the timeless dramatic tragedy 'Romeo and Juliet'?", "choices": ["Charles Dickens", "William Shakespeare", "Mark Twain", "Oscar Wilde"], "answer": 1},
    {"q": "What is the constitutional capital city of the Netherlands?", "choices": ["Rotterdam", "Amsterdam", "The Hague", "Utrecht"], "answer": 1},
    {"q": "Which lizard reptile is world-famous for changing skin pigmentation for camouflage?", "choices": ["Gecko", "Chameleon", "Iguana", "Komodo Dragon"], "answer": 1},
    {"q": "What is the SI unit of measurement for electric current intensity?", "choices": ["Volt", "Ampere", "Ohm", "Watt"], "answer": 1},
    {"q": "In which year were the first modern Olympic Games staged in Athens?", "choices": ["1886", "1896", "1904", "1912"], "answer": 1},
    {"q": "What is the coastal capital city of Portugal?", "choices": ["Porto", "Lisbon", "Braga", "Faro"], "answer": 1},
    {"q": "What is the second most widely consumed beverage in the world after fresh water?", "choices": ["Coffee", "Tea", "Milk", "Orange Juice"], "answer": 1},
    {"q": "What is the capital city of Sweden?", "choices": ["Oslo", "Stockholm", "Copenhagen", "Helsinki"], "answer": 1},
    {"q": "Which ringed gas giant planet boasts the most visually spectacular system of rings?", "choices": ["Jupiter", "Saturn", "Uranus", "Neptune"], "answer": 1},
    {"q": "What is the capital city of the United Arab Emirates?", "choices": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"], "answer": 1},
    {"q": "Which sparkling gemstone is composed of 100% pure crystallized carbon?", "choices": ["Emerald", "Diamond", "Ruby", "Sapphire"], "answer": 1},
    {"q": "What is the smallest living bird species known on planet Earth?", "choices": ["House Sparrow", "Bee Hummingbird", "Swallow", "Goldfinch"], "answer": 1},
    {"q": "In which year did the Soviet Union launch Sputnik 1 into orbit?", "choices": ["1947", "1957", "1969", "1975"], "answer": 1},
    {"q": "What is the capital city of Norway?", "choices": ["Stockholm", "Oslo", "Bergen", "Trondheim"], "answer": 1},
    {"q": "What is the longest and strongest bone in the human skeletal anatomy?", "choices": ["Humerus", "Femur (Thighbone)", "Clavicle", "Tibia"], "answer": 1},
    {"q": "Which European nation is globally renowned for luxury timepieces and alpine chocolate?", "choices": ["Belgium", "Switzerland", "Austria", "Denmark"], "answer": 1},
    {"q": "How many object balls plus cue ball are used in standard 8-ball pool?", "choices": ["15", "16", "17", "21"], "answer": 1},
    {"q": "What is the imperial capital city of Austria?", "choices": ["Vienna", "Salzburg", "Innsbruck", "Graz"], "answer": 0},
    {"q": "What form of potential energy is stored inside a vehicle's battery?", "choices": ["Kinetic Energy", "Chemical Energy", "Nuclear Energy", "Thermal Energy"], "answer": 1},
    {"q": "What is the historic Byzantine and Roman capital name of modern Istanbul?", "choices": ["Athens", "Constantinople", "Alexandria", "Antioch"], "answer": 1},
    {"q": "What is the only true mammal capable of powered, sustained flight?", "choices": ["Flying Squirrel", "Bat", "Sugar Glider", "Colugo"], "answer": 1},
    {"q": "What is the capital city of Belgium and headquarters of the European Union?", "choices": ["Amsterdam", "Brussels", "Strasbourg", "Luxembourg"], "answer": 1},
    {"q": "What is the approximate speed of light in vacuum in km per second?", "choices": ["150,000 km/s", "300,000 km/s", "450,000 km/s", "600,000 km/s"], "answer": 1},
    {"q": "How many weeks are contained in one solar calendar year?", "choices": ["48", "50", "52", "54"], "answer": 2},
    {"q": "Which country spans the largest geographic landmass on planet Earth?", "choices": ["Canada", "Russia", "China", "United States"], "answer": 1},
    {"q": "Which inert lighter-than-air gas is pumped into party balloons to make them float?", "choices": ["Hydrogen", "Helium", "Nitrogen", "Argon"], "answer": 1},
    {"q": "Which physicist formulated the ground-breaking General Theory of Relativity?", "choices": ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Richard Feynman"], "answer": 1},
    {"q": "What is the capital city of Mexico?", "choices": ["Cancun", "Mexico City", "Guadalajara", "Monterrey"], "answer": 1},
    {"q": "How many alternating light and dark squares comprise a chessboard?", "choices": ["49", "64", "81", "100"], "answer": 1},
    {"q": "What is the planned federal capital city of Brazil?", "choices": ["Rio de Janeiro", "Brasília", "São Paulo", "Salvador"], "answer": 1},
    {"q": "Which massive avian raptor is the largest flying bird of prey by weight and wingspan?", "choices": ["Philippine Eagle", "Andean Condor", "Harpy Eagle", "Gyrfalcon"], "answer": 1},
    {"q": "Who pioneered the movable type mechanical printing press in Renaissance Europe?", "choices": ["Galileo", "Johannes Gutenberg", "Leonardo da Vinci", "Copernicus"], "answer": 1},
    {"q": "What is the capital city of Denmark?", "choices": ["Oslo", "Copenhagen", "Stockholm", "Helsinki"], "answer": 1},
    {"q": "What was the tragic luxury passenger liner that struck an iceberg in April 1912?", "choices": ["Britannic", "Titanic", "Lusitania", "Queen Mary"], "answer": 1},
    {"q": "What is the smallest acoustic bone in the human middle ear?", "choices": ["Malleus", "Stapes (Stirrup)", "Incus", "Clavicle"], "answer": 1},
    {"q": "What is the capital city of the Republic of Ireland?", "choices": ["Belfast", "Dublin", "Cork", "Galway"], "answer": 1},
    {"q": "What is the capital city of New Zealand?", "choices": ["Auckland", "Wellington", "Christchurch", "Queenstown"], "answer": 1},
    {"q": "Which gas do humans inhale that is essential for cellular respiration?", "choices": ["Carbon Dioxide", "Oxygen", "Nitrogen", "Methane"], "answer": 1}
  ]
};
