/* ============================================================================
   كمّل المثل — proverbs with one word missing.
   ----------------------------------------------------------------------------
   Shared by the page (inlined by tools/build-*.mjs) and the rooms server
   (bundled by rooms-worker/build.mjs): on one phone the word is revealed by
   a tap, in a room it stays on the server until the round closes.

   Each entry: p (the proverb, with ___ where the word goes), a (the word),
   alt (other spellings or words that count). The word is compared through
   normaliseClue, so أ/ا, ة/ه, "ال" and spaces don't matter. Proverbs don't
   date, which is why this bank never needs looking after.
   ========================================================================= */
const PROVERBS = {
  ar: [
    { p: 'القرد في عين أمه ___', a: 'غزال' },
    { p: 'الطيور على أشكالها ___', a: 'تقع' },
    { p: 'يا واخد القرد على ماله، يروح المال ويفضل القرد على ___', a: 'حاله' },
    { p: 'الجار قبل ___', a: 'الدار' },
    { p: 'اللي على راسه بطحة ___ عليها', a: 'يحسس' },
    { p: 'اللي فات ___', a: 'مات' },
    { p: 'ابن الوز ___', a: 'عوام' },
    { p: 'الصبر مفتاح ___', a: 'الفرج' },
    { p: 'ادي العيش ___', a: 'لخبازه', alt: ['لخبازة', 'لخبازو'] },
    { p: 'الباب اللي يجيلك منه الريح ___ واستريح', a: 'سده' },
    { p: 'ضربني وبكى، سبقني و___', a: 'اشتكى' },
    { p: 'الحيطان ليها ___', a: 'ودان' },
    { p: 'ابعد عن الشر و___', a: 'غنيله', alt: ['غني له', 'غنى له'] },
    { p: 'القرش الأبيض ينفع في اليوم ___', a: 'الأسود', alt: ['الاسود'] },
    { p: 'الوقت ك___', a: 'السيف', alt: ['سيف'] },
    { p: 'العلم ___', a: 'نور' },
    { p: 'من جد ___', a: 'وجد' },
    { p: 'الشمس ما تتغطاش ب___', a: 'غربال' },
    { p: 'عصفور في اليد ولا عشرة على ___', a: 'الشجرة', alt: ['الشجره'] },
    { p: 'اللي يزرع الشوك ما يحصدش ___', a: 'ورد' },
    { p: 'كل ممنوع ___', a: 'مرغوب' },
    { p: 'إن غاب القط العب يا ___', a: 'فار', alt: ['فأر'] },
    { p: 'ياما في الجراب يا ___', a: 'حاوي', alt: ['حاوى'] },
    { p: 'المال السايب يعلم ___', a: 'السرقة', alt: ['السرقه'] },
    { p: 'كله عند العرب ___', a: 'صابون' },
    { p: 'الجواب بيبان من ___', a: 'عنوانه' },
    { p: 'لبس البوصة تبقى ___', a: 'عروسة', alt: ['عروسه'] },
    { p: 'اضحك للدنيا ___', a: 'تضحكلك', alt: ['تضحك لك'] },
    { p: 'كل شيخ وله ___', a: 'طريقة', alt: ['طريقه'] },
    { p: 'العين ما تعلاش عن ___', a: 'الحاجب' },
    { p: 'امشي عدل يحتار ___ فيك', a: 'عدوك' },
    { p: 'الجود من ___', a: 'الموجود' },
    { p: 'الجمل ما يشوفش عوجة ___', a: 'رقبته' },
    { p: 'اللي ايده في المية مش زي اللي ايده في ___', a: 'النار' },
    { p: 'اللي ما يعرفش يقول ___', a: 'عدس' },
    { p: 'يا بخت من بات ___ ولا بات ظالم', a: 'مظلوم' },
    { p: 'التكرار يعلم ___', a: 'الشطار' },
    { p: 'اللي اختشوا ___', a: 'ماتوا' },
    { p: 'دخول الحمام مش زي ___', a: 'خروجه', alt: ['الخروج منه'] },
    { p: 'يا ما تحت السواهي ___', a: 'دواهي', alt: ['دواهى'] },
    { p: 'اللي يحب النبي يزق ___', a: 'شوية', alt: ['شويه'] },
    { p: 'قالوا للحرامي احلف، قال جالك ___', a: 'الفرج' },
    { p: 'اللي بيته من إزاز ما يحدفش الناس ب___', a: 'الطوب', alt: ['طوب'] },
    { p: 'خير البر ___', a: 'عاجله' },
    { p: 'الغايب عذره ___', a: 'معاه', alt: ['معه'] },
    { p: 'يا فرحة ما ___', a: 'تمت' },
    { p: 'اسأل مجرب ولا تسأل ___', a: 'طبيب' },
    { p: 'حبيبك يبلع لك الزلط وعدوك يتمنى لك ___', a: 'الغلط' },
    { p: 'الطمع ___ ما جمع', a: 'يقل' },
    { p: 'اللي يعوزه البيت يحرم على ___', a: 'الجامع' },
    { p: 'إن كان لك عند الكلب حاجة قول له ___', a: 'يا سيدي', alt: ['يا سيدى', 'ياسيدي'] },
    { p: 'كل واحد على دينه الله ___', a: 'يعينه' },
    { p: 'ما تقولش فول لحد ما يبقى في ___', a: 'العدول' },
    { p: 'المية تكدب ___', a: 'الغطاس' },
    { p: 'الديك الفصيح من البيضة ___', a: 'يصيح' },
    { p: 'يا رايح كتر ___', a: 'ملايح' },
    { p: 'اللي فيه خير ما ___', a: 'يخيبش' },
    { p: 'يوم عسل ويوم ___', a: 'بصل' },
    { p: 'اللي ما يعرفش الصقر ___', a: 'يشويه' },
    { p: 'حط في بطنك بطيخة ___', a: 'صيفي', alt: ['صيفى'] },
    { p: 'تعددت الأسباب والموت ___', a: 'واحد' },
    { p: 'الحلو ما يكملش، ___ ما يستمرش', a: 'والوحش', alt: ['الوحش'] },
    { p: 'عمر الشقي ___', a: 'بقي', alt: ['بقى'] },
    { p: 'تحت ___ تحت الزرع', a: 'الطبيخ' },
    { p: 'اللي ما يشوفش من الغربال يبقى ___', a: 'أعمى', alt: ['اعمى'] },
    { p: 'اللي يعمل خير ___', a: 'يلاقيه' },
    { p: 'ما حدش بياخد من الدنيا ___', a: 'حاجة', alt: ['حاجه'] },
    { p: 'الغالي ثمنه ___', a: 'فيه' },
    { p: 'الفلوس تجيب ___', a: 'العروسة', alt: ['العروسه'] },
    { p: 'الدنيا زي الساقية، يوم فوق ويوم ___', a: 'تحت' },
    { p: 'يا واخد الديك على ماله يروح المال ويفضل الديك ___', a: 'بعرفه' },
    { p: 'أول الغيث ___', a: 'قطرة', alt: ['قطره'] },
    { p: 'الوقاية خير من ___', a: 'العلاج' },
    { p: 'الصديق وقت ___', a: 'الضيق' },
    { p: 'رب ضارة ___', a: 'نافعة', alt: ['نافعه'] },
    { p: 'خير الكلام ما قل و___', a: 'دل' },
    { p: 'لكل جواد ___', a: 'كبوة', alt: ['كبوه'] },
    { p: 'من شب على شيء ___ عليه', a: 'شاب' },
    { p: 'من طلب العلا سهر ___', a: 'الليالي', alt: ['الليالى'] },
    { p: 'إذا كان الكلام من فضة فالسكوت من ___', a: 'ذهب' },
    { p: 'لا تؤجل عمل اليوم إلى ___', a: 'الغد' },
    { p: 'الأقربون أولى ب___', a: 'المعروف' },
    { p: 'من حفر حفرة لأخيه ___ فيها', a: 'وقع' },
    { p: 'ليس كل ما يلمع ___', a: 'ذهبا', alt: ['ذهب', 'ذهباً'] },
    { p: 'الغاية تبرر ___', a: 'الوسيلة', alt: ['الوسيله'] },
    { p: 'من راقب الناس مات ___', a: 'هما', alt: ['هماً', 'همًا'] },
    { p: 'الحاجة أم ___', a: 'الاختراع' },
    { p: 'يد واحدة لا ___', a: 'تصفق' },
    { p: 'الاتحاد ___', a: 'قوة', alt: ['قوه'] },
    { p: 'من سار على الدرب ___', a: 'وصل' },
    { p: 'الكتاب يقرأ من ___', a: 'عنوانه' },
    { p: 'بيت المحلي يلعب ___', a: 'الطوب' },
    { p: 'إذا ابتليتم ف___', a: 'استتروا', alt: ['استتروا'] },
    { p: 'خالف ___', a: 'تعرف' },
    { p: 'الحب ___', a: 'أعمى', alt: ['اعمى'] },
    { p: 'اتق شر الحليم إذا ___', a: 'غضب' },
    { p: 'الضحك بلا سبب من قلة ___', a: 'الأدب', alt: ['الادب'] },
    { p: 'عند الامتحان يكرم المرء أو ___', a: 'يهان' },
    { p: 'من عاشر القوم أربعين يوما صار ___', a: 'منهم' },
    { p: 'الصيت ولا ___', a: 'الغنى' },
    { p: 'خذ الحكمة من أفواه ___', a: 'المجانين' },
    { p: 'من لا يعمل لا ___', a: 'يخطئ', alt: ['يخطي', 'يغلط'] },
    { p: 'إذا تم العقل نقص ___', a: 'الكلام' },
    { p: 'الجزاء من جنس ___', a: 'العمل' },
    { p: 'من قلة الخيل شدوا على الكلاب ___', a: 'سروج' },
    { p: 'يا مآمنة للرجال يا مآمنة للمية في ___', a: 'الغربال' },
    { p: 'اللي يتلسع من الشوربة ينفخ في ___', a: 'الزبادي', alt: ['الزبادى'] },
    { p: 'الكلاب تعوي والقافلة ___', a: 'تسير' },
    { p: 'من كثرة الطباخين ___ الطبخة', a: 'شاطت', alt: ['اتحرقت'] },
    { p: 'اللي ما يشتريش يتفرج والفرجة ___', a: 'ببلاش' },
    { p: 'يا مستعجل على الشرا بكرة ___', a: 'هتندم', alt: ['تندم'] },
    { p: 'اللي يخاف من العفريت ___', a: 'يطلعله', alt: ['يطلع له'] },
    { p: 'من أمن العقوبة أساء ___', a: 'الأدب', alt: ['الادب'] }
  ],

  en: [
    { p: 'A friend in need is a friend ___', a: 'indeed' },
    { p: 'Actions speak louder than ___', a: 'words' },
    { p: 'The early bird catches the ___', a: 'worm' },
    { p: 'Better late than ___', a: 'never' },
    { p: 'An apple a day keeps the ___ away', a: 'doctor' },
    { p: 'Practice makes ___', a: 'perfect' },
    { p: 'Honesty is the best ___', a: 'policy' },
    { p: 'Too many cooks spoil the ___', a: 'broth', alt: ['soup'] },
    { p: 'Every cloud has a silver ___', a: 'lining' },
    { p: "Don't count your chickens before they ___", a: 'hatch' },
    { p: 'Birds of a feather flock ___', a: 'together' },
    { p: 'A picture is worth a thousand ___', a: 'words' },
    { p: 'Beggars can\'t be ___', a: 'choosers' },
    { p: 'The grass is always greener on the other ___', a: 'side' },
    { p: 'When in Rome, do as the ___ do', a: 'Romans' },
    { p: 'You can\'t judge a book by its ___', a: 'cover' },
    { p: 'Where there\'s a will, there\'s a ___', a: 'way' },
    { p: 'The pen is mightier than the ___', a: 'sword' },
    { p: 'All that glitters is not ___', a: 'gold' },
    { p: 'Curiosity killed the ___', a: 'cat' },
    { p: 'A watched pot never ___', a: 'boils' },
    { p: 'Two heads are better than ___', a: 'one' },
    { p: 'Laughter is the best ___', a: 'medicine' },
    { p: 'Rome wasn\'t built in a ___', a: 'day' },
    { p: 'Time is ___', a: 'money' },
    { p: 'Blood is thicker than ___', a: 'water' },
    { p: 'The squeaky wheel gets the ___', a: 'grease', alt: ['oil'] },
    { p: 'Necessity is the mother of ___', a: 'invention' },
    { p: 'Slow and steady wins the ___', a: 'race' },
    { p: 'Look before you ___', a: 'leap' },
    { p: 'No pain, no ___', a: 'gain' },
    { p: 'Easy come, easy ___', a: 'go' },
    { p: 'Out of sight, out of ___', a: 'mind' },
    { p: 'The apple doesn\'t fall far from the ___', a: 'tree' },
    { p: 'You reap what you ___', a: 'sow' },
    { p: 'Many hands make light ___', a: 'work' },
    { p: 'A stitch in time saves ___', a: 'nine' },
    { p: 'Absence makes the heart grow ___', a: 'fonder' },
    { p: 'Fortune favours the ___', a: 'bold', alt: ['brave'] },
    { p: 'Good things come to those who ___', a: 'wait' },
    { p: 'Don\'t put all your eggs in one ___', a: 'basket' },
    { p: 'If it ain\'t broke, don\'t ___ it', a: 'fix' },
    { p: 'Money doesn\'t grow on ___', a: 'trees' },
    { p: 'There\'s no place like ___', a: 'home' },
    { p: 'Two wrongs don\'t make a ___', a: 'right' },
    { p: 'Every dog has its ___', a: 'day' },
    { p: 'Strike while the iron is ___', a: 'hot' },
    { p: 'People who live in glass houses shouldn\'t throw ___', a: 'stones' },
    { p: 'The best things in life are ___', a: 'free' },
    { p: 'Barking dogs seldom ___', a: 'bite' },
    { p: 'A rolling stone gathers no ___', a: 'moss' },
    { p: 'Don\'t bite the hand that ___ you', a: 'feeds' },
    { p: 'One man\'s trash is another man\'s ___', a: 'treasure' },
    { p: 'The customer is always ___', a: 'right' },
    { p: 'Half a loaf is better than ___', a: 'none', alt: ['no bread'] },
    { p: 'Knowledge is ___', a: 'power' },
    { p: 'You can lead a horse to water, but you can\'t make it ___', a: 'drink' },
    { p: 'Let sleeping dogs ___', a: 'lie' },
    { p: 'It takes two to ___', a: 'tango' },
    { p: 'The road to hell is paved with good ___', a: 'intentions' },
    { p: 'Don\'t cry over spilt ___', a: 'milk' },
    { p: 'Old habits die ___', a: 'hard' },
    { p: 'Still waters run ___', a: 'deep' },
    { p: 'A chain is only as strong as its weakest ___', a: 'link' },
    { p: 'Hope for the best, prepare for the ___', a: 'worst' },
    { p: 'The proof of the pudding is in the ___', a: 'eating' },
    { p: 'Variety is the spice of ___', a: 'life' },
    { p: 'First come, first ___', a: 'served' },
    { p: 'Great minds think ___', a: 'alike' },
    { p: 'Home is where the ___ is', a: 'heart' },
    { p: 'Cleanliness is next to ___', a: 'godliness' },
    { p: 'Love is ___', a: 'blind' },
    { p: 'Silence is ___', a: 'golden' }
  ]
};
