/* ============================================================================
   دندنها — the songs (1 Oct 2026)
   ----------------------------------------------------------------------------
   Egyptian songs only, family-clean: the classics (أم كلثوم، عبد الحليم، عبد
   الوهاب، فريد، شادية، وردة، نجاة…), the pop of the 90s to the 2010s (عمرو دياب،
   منير، أنغام، شيرين، تامر، حماقي…) and the mahraganat and the newest.

   Two sources of the official 30-second previews (the owner, 1 Oct 2026), both
   free with no key: Apple (https://itunes.apple.com/lookup?id=…) and Deezer
   (https://api.deezer.com/track/…). Every song is pinned to ONE of them -
   { src: 'itunes', id } or { src: 'deezer', id }, the ORIGINAL singer's
   recording with a preview (the singer's own page; covers, karaoke, belly-dance,
   remix and instrumental albums left out); Apple where it had the song, Deezer
   for what Apple was missing (الأطلال، ألف ليلة وليلة، حدوتة مصرية، البخت…) and
   much of the newest. `also` is a second pin to the same singer's recording on
   the other source, tried when the first fails. Only ids are kept: Deezer's
   preview addresses are signed and expire within hours (hdnea=exp=…), so the
   rooms server looks a song up each time it plays it (rooms-worker/src/songs.js)
   and streams it for one round's opaque address (/song/CODE/TOKEN), so no id,
   source, title or singer reaches a guesser's phone.

   Fields: src and id (the pin), also (the second pin, optional), t (the Arabic
   title), alt (other names the table calls it by - the famous line - judged like
   the title), s (the singer in Arabic), era ('classic' | 'pop' | 'new': the four
   choices come from the same era when they can), en (the English title, an
   answer too), se (the singer in English). A guess is judged by guessVerdict
   against t, alt and en; the singer alone is never an answer.

   Server-only (rooms-worker/build.mjs FILES): the page never needs the list.
   `npm run check` (tools/validate-content.js) checks it offline; `npm run
   check:songs` in tools/ asks both sources about every pin (--play: the
   previews themselves).
   ========================================================================= */
const HUM_SONGS = [
  { src: 'itunes', id: 1439420809, also: { src: 'deezer', id: 3624936022 }, t: 'إنت عمري', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Enta Omri', se: 'Umm Kulthum' },
  { src: 'itunes', id: 580569326, also: { src: 'deezer', id: 3623249332 }, t: 'هذه ليلتي', alt: ['هذه ليلتي وحلم حياتي'], s: 'أم كلثوم', era: 'classic', en: 'Hazihi Laylati', se: 'Umm Kulthum' },
  { src: 'itunes', id: 623239105, also: { src: 'deezer', id: 3623245712 }, t: 'سيرة الحب', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Seret El Hob', se: 'Umm Kulthum' },
  { src: 'itunes', id: 580612409, t: 'للصبر حدود', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Lel Sabr Hedoud', se: 'Umm Kulthum' },
  { src: 'itunes', id: 580601546, also: { src: 'deezer', id: 3623250992 }, t: 'أغدا ألقاك', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Aghadan Alqak', se: 'Umm Kulthum' },
  { src: 'itunes', id: 580581412, t: 'يا ظالمني', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Ya Zalemni', se: 'Umm Kulthum' },
  { src: 'itunes', id: 580569533, t: 'هو صحيح الهوى غلاب', alt: ['الهوى غلاب'], s: 'أم كلثوم', era: 'classic', en: 'Howa Sahih El Hawa Ghallab', se: 'Umm Kulthum' },
  { src: 'itunes', id: 580576453, t: 'لسه فاكر', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Lessa Faker', se: 'Umm Kulthum' },
  { src: 'itunes', id: 895453934, t: 'جددت حبك ليه', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Gaddedt Hobbak Leh', se: 'Umm Kulthum' },
  { src: 'itunes', id: 580587588, also: { src: 'deezer', id: 3210652111 }, t: 'على بلد المحبوب', alt: ['على بلد المحبوب وديني'], s: 'أم كلثوم', era: 'classic', en: 'Ala Balad El Mahboub', se: 'Umm Kulthum' },
  { src: 'itunes', id: 844361504, also: { src: 'deezer', id: 84204219 }, t: 'أهواك', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Ahwak', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 844361549, also: { src: 'deezer', id: 84204231 }, t: 'أنا لك على طول', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Ana Lak Ala Tool', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 844361546, also: { src: 'deezer', id: 84204227 }, t: 'توبة', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Tooba', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 842598469, also: { src: 'deezer', id: 84205961 }, t: 'الهوى هوايا', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'El Hawa Hawaya', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 843097061, t: 'أول مرة تحب يا قلبي', alt: ['أول مرة'], s: 'عبد الحليم حافظ', era: 'classic', en: 'Awel Marra Tehebb Ya Albi', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 843282982, also: { src: 'deezer', id: 84204245 }, t: 'بتلوموني ليه', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Betlomoni Leh', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 843034340, also: { src: 'deezer', id: 84204175 }, t: 'أسمر يا أسمراني', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Asmar Ya Asmarani', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 842688073, t: 'صافيني مرة', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Safeeni Marra', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 842534673, also: { src: 'deezer', id: 84205271 }, t: 'قارئة الفنجان', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Qare\'at El Fengan', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 843314763, t: 'سواح', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Sawwah', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 1809346868, also: { src: 'deezer', id: 3210657551 }, t: 'على قد الشوق', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Ala Ad El Shoq', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 843314761, t: 'جانا الهوى', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Gana El Hawa', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 844441064, also: { src: 'deezer', id: 84204257 }, t: 'في يوم في شهر في سنة', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Fi Youm Fi Shahr Fi Sana', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 843097060, also: { src: 'deezer', id: 84204283 }, t: 'خسارة', alt: ['خسارة خسارة'], s: 'عبد الحليم حافظ', era: 'classic', en: 'Khosara', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 843097059, also: { src: 'deezer', id: 3214028261 }, t: 'بحلم بيك', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Bahlam Beek', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 844374883, t: 'ضحك ولعب', alt: ['ضحك ولعب وجد وحب'], s: 'عبد الحليم حافظ', era: 'classic', en: 'Dehk We Le\'eb', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 1098028306, also: { src: 'deezer', id: 649359472 }, t: 'زي الهوا', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Zay El Hawa', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 206788355, t: 'حاول تفتكرني', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Hawel Teftekerni', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 778587235, t: 'موعود', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Maw\'oud', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 205230552, t: 'فاتت جنبنا', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Fatet Ganbena', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 839252946, t: 'مداح القمر', alt: [], s: 'عبد الحليم حافظ', era: 'classic', en: 'Maddah El Amar', se: 'Abdel Halim Hafez' },
  { src: 'itunes', id: 1593452284, also: { src: 'deezer', id: 84204117 }, t: 'يا مسافر وحدك', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'Ya Msafer Wahdak', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 846836788, also: { src: 'deezer', id: 84204517 }, t: 'عاشق الروح', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'Ashe\' El Rouh', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 1883637737, t: 'أحب عيشة الحرية', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'Aheb Eishet El Horreya', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 1528966907, t: 'يا وابور قولي', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'Ya Wabour Oolly', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 1528966365, also: { src: 'deezer', id: 1059993432 }, t: 'كل ده كان ليه', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'Kol Da Kan Leh', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 847608951, t: 'خايف أقول اللي في قلبي', alt: ['خايف أقول'], s: 'محمد عبد الوهاب', era: 'classic', en: 'Khayef A\'oul', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 1593452283, t: 'يا جارة الوادي', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'Ya Garat El Wadi', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 847982611, also: { src: 'deezer', id: 84205839 }, t: 'من غير ليه', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'Men Gheir Leh', se: 'Mohamed Abdel Wahab' },
  { src: 'itunes', id: 1097587292, also: { src: 'deezer', id: 648989102 }, t: 'الحياة حلوة', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'El Hayah Helwa', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 839509450, also: { src: 'deezer', id: 648988262 }, t: 'قلبي ومفتاحه', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Albi We Moftaho', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 1097587293, also: { src: 'deezer', id: 648989112 }, t: 'حبيب العمر', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Habib El Omr', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 1097430058, also: { src: 'deezer', id: 648987202 }, t: 'وياك', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Wayak', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 1097587289, also: { src: 'deezer', id: 648989072 }, t: 'يا زهرة في خيالي', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Ya Zahra Fi Khayali', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 839554944, also: { src: 'deezer', id: 685904252 }, t: 'زمان يا حب', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Zaman Ya Hob', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 1097572671, also: { src: 'deezer', id: 648986302 }, t: 'جميل جمال', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Gamil Gamal', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 1097430061, also: { src: 'deezer', id: 648987232 }, t: 'دقوا المزاهر', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Do\'o El Mazaher', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 839509452, also: { src: 'deezer', id: 648988272 }, t: 'عدت يا يوم مولدي', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Odt Ya Youm Mouldi', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 839598081, also: { src: 'deezer', id: 649522542 }, t: 'علشان ماليش غيرك', alt: [], s: 'فريد الأطرش', era: 'classic', en: 'Alashan Malish Gheirak', se: 'Farid Al Atrash' },
  { src: 'itunes', id: 206349963, also: { src: 'deezer', id: 84205607 }, t: 'يا حبيبتي يا مصر', alt: [], s: 'شادية', era: 'classic', en: 'Ya Habibti Ya Masr', se: 'Shadia' },
  { src: 'itunes', id: 458476349, t: 'إن راح منك يا عين', alt: [], s: 'شادية', era: 'classic', en: 'En Rah Mennak Ya Ein', se: 'Shadia' },
  { src: 'itunes', id: 458476646, also: { src: 'deezer', id: 3513089731 }, t: 'سيد الحبايب', alt: ['سيد الحبايب يا ضنايا'], s: 'شادية', era: 'classic', en: 'Seed El Habayeb', se: 'Shadia' },
  { src: 'itunes', id: 458476659, also: { src: 'deezer', id: 84204783 }, t: 'وحياة عينيك', alt: [], s: 'شادية', era: 'classic', en: 'We Hayat Einek', se: 'Shadia' },
  { src: 'itunes', id: 458476197, also: { src: 'deezer', id: 3056993951 }, t: 'قولوا لعين الشمس', alt: [], s: 'شادية', era: 'classic', en: 'Oulou Le Ein El Shams', se: 'Shadia' },
  { src: 'itunes', id: 458476135, t: 'آه يا أسمراني اللون', alt: ['أسمراني اللون'], s: 'شادية', era: 'classic', en: 'Ah Ya Asmarani El Loon', se: 'Shadia' },
  { src: 'itunes', id: 458476999, also: { src: 'deezer', id: 2542134921 }, t: 'يا دبلة الخطوبة', alt: ['دبلة الخطوبة'], s: 'شادية', era: 'classic', en: 'Ya Deblet El Khotouba', se: 'Shadia' },
  { src: 'itunes', id: 206349470, also: { src: 'deezer', id: 84205603 }, t: 'خدني معاك', alt: [], s: 'شادية', era: 'classic', en: 'Khodni Ma\'ak', se: 'Shadia' },
  { src: 'itunes', id: 458476948, t: 'شباكنا ستايره حرير', alt: [], s: 'شادية', era: 'classic', en: 'Shebbakna Satayro Harir', se: 'Shadia' },
  { src: 'itunes', id: 458476056, also: { src: 'deezer', id: 3455408471 }, t: 'مين قالك تسكن في حارتنا', alt: [], s: 'شادية', era: 'classic', en: 'Meen Allak Teskon Fi Haretna', se: 'Shadia' },
  { src: 'itunes', id: 458476472, also: { src: 'deezer', id: 622512972 }, t: 'ماما يا حلوة', alt: [], s: 'شادية', era: 'classic', en: 'Mama Ya Helwa', se: 'Shadia' },
  { src: 'itunes', id: 458476303, t: 'آلو آلو إحنا هنا', alt: [], s: 'شادية', era: 'classic', en: 'Alo Alo Ehna Hena', se: 'Shadia' },
  { src: 'itunes', id: 848874885, t: 'سونة يا سونة', alt: ['سونة'], s: 'شادية', era: 'classic', en: 'Sona Ya Sona', se: 'Shadia' },
  { src: 'itunes', id: 848826956, also: { src: 'deezer', id: 84204779 }, t: 'مصر اليوم في عيد', alt: [], s: 'شادية', era: 'classic', en: 'Masr El Youm Fi Eid', se: 'Shadia' },
  { src: 'itunes', id: 770101904, also: { src: 'deezer', id: 80713944 }, t: 'حرمت أحبك', alt: [], s: 'وردة', era: 'classic', en: 'Haramt Ahebbak', se: 'Warda' },
  { src: 'itunes', id: 254503728, also: { src: 'deezer', id: 3054130111 }, t: 'لولا الملامة', alt: [], s: 'وردة', era: 'classic', en: 'Lola El Malama', se: 'Warda' },
  { src: 'itunes', id: 849338016, t: 'وحشتوني', alt: [], s: 'وردة', era: 'classic', en: 'Wahashtouni', se: 'Warda' },
  { src: 'itunes', id: 770067887, also: { src: 'deezer', id: 80713888 }, t: 'بتونس بيك', alt: [], s: 'وردة', era: 'classic', en: 'Batwannes Beek', se: 'Warda' },
  { src: 'itunes', id: 1643944139, t: 'في يوم وليلة', alt: [], s: 'وردة', era: 'classic', en: 'Fi Youm We Leila', se: 'Warda' },
  { src: 'itunes', id: 849256124, t: 'العيون السود', alt: [], s: 'وردة', era: 'classic', en: 'El Oyoun El Soud', se: 'Warda' },
  { src: 'itunes', id: 1643943990, t: 'أكدب عليك', alt: [], s: 'وردة', era: 'classic', en: 'Akdeb Aleik', se: 'Warda' },
  { src: 'itunes', id: 849401892, also: { src: 'deezer', id: 84205321 }, t: 'طب وأنا مالي', alt: [], s: 'وردة', era: 'classic', en: 'Tab Wana Mali', se: 'Warda' },
  { src: 'itunes', id: 849401891, also: { src: 'deezer', id: 84205319 }, t: 'اشتروني', alt: [], s: 'وردة', era: 'classic', en: 'Eshtarouni', se: 'Warda' },
  { src: 'itunes', id: 459023486, also: { src: 'deezer', id: 84205741 }, t: 'أيظن', alt: [], s: 'نجاة', era: 'classic', en: 'Ayazonn', se: 'Nagat' },
  { src: 'itunes', id: 458971872, also: { src: 'deezer', id: 84205739 }, t: 'ساكن قصادي', alt: [], s: 'نجاة', era: 'classic', en: 'Saken Ousadi', se: 'Nagat' },
  { src: 'itunes', id: 459023488, t: 'أما براوة', alt: [], s: 'نجاة', era: 'classic', en: 'Amma Barawa', se: 'Nagat' },
  { src: 'itunes', id: 848324062, t: 'عيون القلب', alt: [], s: 'نجاة', era: 'classic', en: 'Oyoun El Alb', se: 'Nagat' },
  { src: 'itunes', id: 206229905, also: { src: 'deezer', id: 84205513 }, t: 'الطير المسافر', alt: [], s: 'نجاة', era: 'classic', en: 'El Teir El Mesafer', se: 'Nagat' },
  { src: 'itunes', id: 459023487, also: { src: 'deezer', id: 84205511 }, t: 'آه لو تعرف', alt: [], s: 'نجاة', era: 'classic', en: 'Ah Law Te\'raf', se: 'Nagat' },
  { src: 'itunes', id: 459023440, also: { src: 'deezer', id: 84204749 }, t: 'أنا بعشق البحر', alt: [], s: 'نجاة', era: 'classic', en: 'Ana Ba\'sha\' El Bahr', se: 'Nagat' },
  { src: 'itunes', id: 848515822, t: 'لا تكذبي', alt: [], s: 'نجاة', era: 'classic', en: 'La Takzebi', se: 'Nagat' },
  { src: 'itunes', id: 602154452, t: 'ماما زمانها جاية', alt: [], s: 'محمد فوزي', era: 'classic', en: 'Mama Zamanha Gaya', se: 'Mohamed Fawzi' },
  { src: 'itunes', id: 453168911, t: 'هاتوا الفوانيس يا ولاد', alt: ['هاتوا الفوانيس'], s: 'محمد فوزي', era: 'classic', en: 'Hatou El Fawanees Ya Wlad', se: 'Mohamed Fawzi' },
  { src: 'itunes', id: 1827291579, t: 'ذهب الليل', alt: ['ذهب الليل طلع الفجر'], s: 'محمد فوزي', era: 'classic', en: 'Zahab El Leil', se: 'Mohamed Fawzi' },
  { src: 'itunes', id: 602153709, t: 'مال القمر ماله', alt: [], s: 'محمد فوزي', era: 'classic', en: 'Mal El Amar Malo', se: 'Mohamed Fawzi' },
  { src: 'itunes', id: 846674984, also: { src: 'deezer', id: 84204233 }, t: 'ست الحبايب', alt: [], s: 'فايزة أحمد', era: 'classic', en: 'Sett El Habayeb', se: 'Fayza Ahmed' },
  { src: 'itunes', id: 836110819, t: 'يمه القمر عالباب', alt: ['القمر عالباب', 'يما القمر على الباب'], s: 'فايزة أحمد', era: 'classic', en: 'Yamma El Amar Al Bab', se: 'Fayza Ahmed' },
  { src: 'itunes', id: 836110821, also: { src: 'deezer', id: 81666612 }, t: 'أنا قلبي إليك ميال', alt: [], s: 'فايزة أحمد', era: 'classic', en: 'Ana Albi Eleik Mayyal', se: 'Fayza Ahmed' },
  { src: 'itunes', id: 846674988, also: { src: 'deezer', id: 84204241 }, t: 'تهجرني بحكاية', alt: [], s: 'فايزة أحمد', era: 'classic', en: 'Tehgorni Be Hekaya', se: 'Fayza Ahmed' },
  { src: 'itunes', id: 846674985, also: { src: 'deezer', id: 84204235 }, t: 'حمال الأسية', alt: [], s: 'فايزة أحمد', era: 'classic', en: 'Hammal El Asiya', se: 'Fayza Ahmed' },
  { src: 'itunes', id: 836110818, also: { src: 'deezer', id: 81666608 }, t: 'بيت العز', alt: ['بيت العز يا بيتنا'], s: 'فايزة أحمد', era: 'classic', en: 'Beit El Ezz', se: 'Fayza Ahmed' },
  { src: 'itunes', id: 871523386, also: { src: 'deezer', id: 84204273 }, t: 'طاير يا هوا', alt: [], s: 'محمد رشدي', era: 'classic', en: 'Tayer Ya Hawa', se: 'Mohamed Roshdy' },
  { src: 'itunes', id: 871523388, t: 'على الرملة', alt: [], s: 'محمد رشدي', era: 'classic', en: 'Ala El Ramla', se: 'Mohamed Roshdy' },
  { src: 'itunes', id: 844564461, t: 'متى أشوفك', alt: [], s: 'محمد رشدي', era: 'classic', en: 'Emta Ashoufak', se: 'Mohamed Roshdy' },
  { src: 'itunes', id: 1716552952, also: { src: 'deezer', id: 2830336792 }, t: 'قولوا لمأذون البلد', alt: [], s: 'محمد رشدي', era: 'classic', en: 'Oulou Le Ma\'zoun El Balad', se: 'Mohamed Roshdy' },
  { src: 'itunes', id: 561454748, t: 'يا حلو صبح', alt: ['يا حلو صبح يا حلو طل'], s: 'محمد قنديل', era: 'classic', en: 'Ya Helw Sabbah', se: 'Mohamed Kandil' },
  { src: 'itunes', id: 458895038, t: 'تلات سلامات', alt: [], s: 'محمد قنديل', era: 'classic', en: 'Talat Salamat', se: 'Mohamed Kandil' },
  { src: 'itunes', id: 458894998, t: 'جميل وأسمر', alt: [], s: 'محمد قنديل', era: 'classic', en: 'Gamil We Asmar', se: 'Mohamed Kandil' },
  { src: 'itunes', id: 899232989, t: 'ساكن في حي السيدة', alt: [], s: 'محمد عبد المطلب', era: 'classic', en: 'Saken Fi Hay El Sayeda', se: 'Mohamed Abdel Motaleb' },
  { src: 'itunes', id: 453168944, t: 'رمضان جانا', alt: [], s: 'محمد عبد المطلب', era: 'classic', en: 'Ramadan Gana', se: 'Mohamed Abdel Motaleb' },
  { src: 'itunes', id: 453168952, t: 'وحوي يا وحوي', alt: [], s: 'أحمد عبد القادر', era: 'classic', en: 'Wahawi Ya Wahawi', se: 'Ahmed Abdel Kader' },
  { src: 'itunes', id: 844174038, also: { src: 'deezer', id: 84205721 }, t: 'ردوا السلام', alt: [], s: 'عفاف راضي', era: 'classic', en: 'Roddo El Salam', se: 'Afaf Rady' },
  { src: 'itunes', id: 844174039, also: { src: 'deezer', id: 84205723 }, t: 'هوا يا هوا', alt: [], s: 'عفاف راضي', era: 'classic', en: 'Hawa Ya Hawa', se: 'Afaf Rady' },
  { src: 'itunes', id: 909128332, t: 'سالمة يا سلامة', alt: [], s: 'سيد درويش', era: 'classic', en: 'Salma Ya Salama', se: 'Sayed Darwish' },
  { src: 'itunes', id: 850287464, t: 'زحمة يا دنيا زحمة', alt: ['زحمة'], s: 'أحمد عدوية', era: 'classic', en: 'Zahma Ya Donya Zahma', se: 'Ahmed Adaweya' },
  { src: 'itunes', id: 850170525, t: 'سلامتها أم حسن', alt: [], s: 'أحمد عدوية', era: 'classic', en: 'Salametha Om Hassan', se: 'Ahmed Adaweya' },
  { src: 'itunes', id: 849758534, t: 'بنت السلطان', alt: [], s: 'أحمد عدوية', era: 'classic', en: 'Bent El Soltan', se: 'Ahmed Adaweya' },
  { src: 'itunes', id: 1182051692, t: 'كتاب حياتي يا عين', alt: ['كتاب حياتي'], s: 'حسن الأسمر', era: 'pop', en: 'Ketab Hayati Ya Ein', se: 'Hassan El Asmar' },
  { src: 'itunes', id: 835628001, also: { src: 'deezer', id: 81259056 }, t: 'لولاكي', alt: [], s: 'علي حميدة', era: 'pop', en: 'Lolaki', se: 'Ali Hemeida' },
  { src: 'itunes', id: 880940097, also: { src: 'deezer', id: 81102882 }, t: 'تملي معاك', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Tamally Maak', se: 'Amr Diab' },
  { src: 'itunes', id: 878251626, also: { src: 'deezer', id: 80714152 }, t: 'نور العين', alt: ['حبيبي يا نور العين'], s: 'عمرو دياب', era: 'pop', en: 'Nour El Ein', se: 'Amr Diab' },
  { src: 'itunes', id: 533091076, also: { src: 'deezer', id: 81102804 }, t: 'قمرين', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Amarein', se: 'Amr Diab' },
  { src: 'itunes', id: 880940096, also: { src: 'deezer', id: 81102880 }, t: 'العالم الله', alt: [], s: 'عمرو دياب', era: 'pop', en: 'El Alem Allah', se: 'Amr Diab' },
  { src: 'itunes', id: 534190619, also: { src: 'deezer', id: 80714222 }, t: 'أنا عايش', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Ana Ayesh', se: 'Amr Diab' },
  { src: 'itunes', id: 1599532140, t: 'قصاد عيني', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Osad Eini', se: 'Amr Diab' },
  { src: 'itunes', id: 533091079, also: { src: 'deezer', id: 81102810 }, t: 'بحبك أكتر', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Bahebbak Aktar', se: 'Amr Diab' },
  { src: 'itunes', id: 1599532428, t: 'ليلي نهاري', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Leily Nahari', se: 'Amr Diab' },
  { src: 'itunes', id: 534190616, also: { src: 'deezer', id: 80714220 }, t: 'علم قلبي', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Allem Albi', se: 'Amr Diab' },
  { src: 'itunes', id: 1675938075, also: { src: 'deezer', id: 2178341537 }, t: 'وغلاوتك', alt: [], s: 'عمرو دياب', era: 'pop', en: 'We Ghalawtak', se: 'Amr Diab' },
  { src: 'itunes', id: 1674027801, also: { src: 'deezer', id: 2163920947 }, t: 'ميال', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Mayyal', se: 'Amr Diab' },
  { src: 'itunes', id: 1599365493, t: 'الليلة', alt: [], s: 'عمرو دياب', era: 'pop', en: 'El Leila', se: 'Amr Diab' },
  { src: 'itunes', id: 1775965916, also: { src: 'deezer', id: 3060026231 }, t: 'يا أنا يا لا', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Ya Ana Ya La', se: 'Amr Diab' },
  { src: 'itunes', id: 1775884497, also: { src: 'deezer', id: 81103736 }, t: 'ولا على باله', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Wala Ala Balo', se: 'Amr Diab' },
  { src: 'itunes', id: 533091082, also: { src: 'deezer', id: 81102816 }, t: 'خليك فاكرني', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Khallik Fakerni', se: 'Amr Diab' },
  { src: 'itunes', id: 1437429171, also: { src: 'deezer', id: 3059980351 }, t: 'باين حبيت', alt: [], s: 'عمرو دياب', era: 'new', en: 'Bayen Habeit', se: 'Amr Diab' },
  { src: 'itunes', id: 1821737515, also: { src: 'deezer', id: 4112808521 }, t: 'شبابيك', alt: [], s: 'محمد منير', era: 'pop', en: 'Shababeek', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1821737050, also: { src: 'deezer', id: 699921652 }, t: 'الليلة يا سمرا', alt: [], s: 'محمد منير', era: 'pop', en: 'El Leila Ya Samra', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 254756431, also: { src: 'deezer', id: 138356989 }, t: 'شمندورة', alt: [], s: 'محمد منير', era: 'pop', en: 'Shamandoura', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1475675766, t: 'يا حمام', alt: [], s: 'محمد منير', era: 'pop', en: 'Ya Hamam', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1425466160, also: { src: 'deezer', id: 643165702 }, t: 'لو بطلنا نحلم نموت', alt: [], s: 'محمد منير', era: 'pop', en: 'Law Battalna Nehlam Nemout', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1821737045, also: { src: 'deezer', id: 4112808501 }, t: 'الكون كله بيدور', alt: [], s: 'محمد منير', era: 'pop', en: 'El Kon Kollo Beydour', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 557566901, t: 'قلبي مساكن شعبية', alt: [], s: 'محمد منير', era: 'pop', en: 'Albi Masaken Sha\'beya', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 282123303, also: { src: 'deezer', id: 80321200 }, t: 'يونس', alt: [], s: 'محمد منير', era: 'pop', en: 'Younes', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1524643242, also: { src: 'deezer', id: 950111172 }, t: 'حواديت', alt: [], s: 'محمد منير', era: 'pop', en: 'Hawadeet', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 557164617, t: 'في عشق البنات', alt: [], s: 'محمد منير', era: 'pop', en: 'Fi Eshq El Banat', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 557566898, t: 'سو يا سو', alt: [], s: 'محمد منير', era: 'pop', en: 'So Ya So', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1821726085, t: 'اتكلمي', alt: [], s: 'محمد منير', era: 'pop', en: 'Etkallemi', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1821726091, t: 'عقد الفل والياسمين', alt: [], s: 'محمد منير', era: 'pop', en: 'Eqd El Foll Wel Yasmeen', se: 'Mohamed Mounir' },
  { src: 'itunes', id: 1392501167, t: 'السلام عليكم', alt: [], s: 'حكيم', era: 'pop', en: 'El Salamu Aleikum', se: 'Hakim' },
  { src: 'itunes', id: 1129294980, t: 'ولا واحد ولا مية', alt: [], s: 'حكيم', era: 'pop', en: 'Wala Wahed Wala Meya', se: 'Hakim' },
  { src: 'itunes', id: 770937661, also: { src: 'deezer', id: 81102960 }, t: 'سيدي وصالك', alt: [], s: 'أنغام', era: 'pop', en: 'Sidi Wesalak', se: 'Angham' },
  { src: 'itunes', id: 773233792, also: { src: 'deezer', id: 81103266 }, t: 'عمري معاك', alt: [], s: 'أنغام', era: 'pop', en: 'Omri Ma\'ak', se: 'Angham' },
  { src: 'itunes', id: 1599359223, t: 'يا ريتك فاهمني', alt: [], s: 'أنغام', era: 'pop', en: 'Ya Retak Fahemni', se: 'Angham' },
  { src: 'itunes', id: 512464148, also: { src: 'deezer', id: 614044112 }, t: 'شنطة سفر', alt: [], s: 'أنغام', era: 'pop', en: 'Shanta Safar', se: 'Angham' },
  { src: 'itunes', id: 1759862080, also: { src: 'deezer', id: 2906666491 }, t: 'تيجي نسيب', alt: [], s: 'أنغام', era: 'new', en: 'Tigi Neseeb', se: 'Angham' },
  { src: 'itunes', id: 1599345377, t: 'أحلام بريئة', alt: [], s: 'أنغام', era: 'pop', en: 'Ahlam Bariea', se: 'Angham' },
  { src: 'itunes', id: 1599359220, t: 'حالة خاصة جدا', alt: [], s: 'أنغام', era: 'pop', en: 'Hala Khassa Gedan', se: 'Angham' },
  { src: 'itunes', id: 770937662, also: { src: 'deezer', id: 81102962 }, t: 'ليه سبتها', alt: [], s: 'أنغام', era: 'pop', en: 'Leh Sebtaha', se: 'Angham' },
  { src: 'itunes', id: 389579277, t: 'أنا عايشة حالة', alt: [], s: 'أنغام', era: 'pop', en: 'Ana Ayshah Hala', se: 'Angham' },
  { src: 'itunes', id: 557068371, t: 'آه يا ليل', alt: [], s: 'شيرين', era: 'pop', en: 'Ah Ya Leil', se: 'Sherine' },
  { src: 'itunes', id: 538287781, t: 'صبري قليل', alt: [], s: 'شيرين', era: 'pop', en: 'Sabri Alil', se: 'Sherine' },
  { src: 'itunes', id: 534964912, t: 'على بالي', alt: [], s: 'شيرين', era: 'pop', en: 'Ala Bali', se: 'Sherine' },
  { src: 'itunes', id: 1169039390, t: 'ما شربتش من نيلها', alt: [], s: 'شيرين', era: 'pop', en: 'Mashrebtesh Men Nilha', se: 'Sherine' },
  { src: 'itunes', id: 769936740, t: 'مشاعر', alt: [], s: 'شيرين', era: 'pop', en: 'Mashaer', se: 'Sherine' },
  { src: 'itunes', id: 538287788, t: 'جرح تاني', alt: [], s: 'شيرين', era: 'pop', en: 'Garh Tani', se: 'Sherine' },
  { src: 'itunes', id: 1440053111, also: { src: 'deezer', id: 573699462 }, t: 'كلام عينيه', alt: [], s: 'شيرين', era: 'pop', en: 'Kalam Eineih', se: 'Sherine' },
  { src: 'itunes', id: 538287785, t: 'بتوحشني', alt: [], s: 'شيرين', era: 'pop', en: 'Betewhashni', se: 'Sherine' },
  { src: 'itunes', id: 447035605, also: { src: 'deezer', id: 80322060 }, t: 'اللي جاي أحلى', alt: [], s: 'تامر حسني', era: 'pop', en: 'Elli Gai Ahla', se: 'Tamer Hosny' },
  { src: 'itunes', id: 534449395, t: 'كل مرة', alt: [], s: 'تامر حسني', era: 'pop', en: 'Kol Marra', se: 'Tamer Hosny' },
  { src: 'itunes', id: 534449396, t: 'نور عيني', alt: [], s: 'تامر حسني', era: 'pop', en: 'Nour Eini', se: 'Tamer Hosny' },
  { src: 'itunes', id: 534449367, t: 'بعيش', alt: [], s: 'تامر حسني', era: 'pop', en: 'Ba\'eesh', se: 'Tamer Hosny' },
  { src: 'itunes', id: 1731374726, t: 'ناسيني ليه', alt: [], s: 'تامر حسني', era: 'new', en: 'Naseeni Leh', se: 'Tamer Hosny' },
  { src: 'itunes', id: 534063966, t: 'كل سنة وانت طيب', alt: [], s: 'تامر حسني', era: 'pop', en: 'Kol Sana Wenta Tayeb', se: 'Tamer Hosny' },
  { src: 'itunes', id: 534449394, t: 'عيني بتحبك', alt: [], s: 'تامر حسني', era: 'pop', en: 'Eini Bethebbak', se: 'Tamer Hosny' },
  { src: 'itunes', id: 1731374973, t: 'عيش بشوقك', alt: [], s: 'تامر حسني', era: 'new', en: 'Eish Beshoak', se: 'Tamer Hosny' },
  { src: 'itunes', id: 1029486798, t: 'ما بلاش', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Ma Balash', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1450235133, t: 'قدام الناس', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Odam El Nas', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1450235132, t: 'يا ستار', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Ya Sattar', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1467668473, t: 'حاجة مستخبية', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Haga Mestakhabeya', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1467668518, t: 'من قلبي بغني', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Men Albi Baghanni', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1450234969, t: 'كل يوم من ده', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Kol Youm Men Dah', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1588264717, also: { src: 'deezer', id: 1509103822 }, t: 'ليلة العمر', alt: [], s: 'محمد حماقي', era: 'new', en: 'Leilet El Omr', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1138424338, also: { src: 'deezer', id: 2182016137 }, t: 'حبيبي ده', alt: ['ناري نارين'], s: 'هشام عباس', era: 'pop', en: 'Habibi Dah', se: 'Hisham Abbas' },
  { src: 'itunes', id: 1103923218, t: 'عينيها السود', alt: [], s: 'هشام عباس', era: 'pop', en: 'Eineiha El Soud', se: 'Hisham Abbas' },
  { src: 'itunes', id: 268192910, t: 'يا ليلة', alt: [], s: 'هشام عباس', era: 'pop', en: 'Ya Leila', se: 'Hisham Abbas' },
  { src: 'itunes', id: 837728882, also: { src: 'deezer', id: 81103156 }, t: 'منايا', alt: [], s: 'مصطفى قمر', era: 'pop', en: 'Monaya', se: 'Mostafa Amar' },
  { src: 'itunes', id: 371308435, also: { src: 'deezer', id: 80321864 }, t: 'ليلة من عمري', alt: [], s: 'مصطفى قمر', era: 'pop', en: 'Leila Men Omri', se: 'Mostafa Amar' },
  { src: 'itunes', id: 1599591389, t: 'السود عيونه', alt: [], s: 'مصطفى قمر', era: 'pop', en: 'El Soud Oyouno', se: 'Mostafa Amar' },
  { src: 'itunes', id: 1547113432, t: 'سحراني', alt: [], s: 'إيهاب توفيق', era: 'pop', en: 'Sahrani', se: 'Ehab Tawfik' },
  { src: 'itunes', id: 1547122750, t: 'الله عليك يا سيدي', alt: [], s: 'إيهاب توفيق', era: 'pop', en: 'Allah Aleik Ya Sidi', se: 'Ehab Tawfik' },
  { src: 'itunes', id: 1547123013, t: 'تترجى فيا', alt: [], s: 'إيهاب توفيق', era: 'pop', en: 'Tetragga Feyya', se: 'Ehab Tawfik' },
  { src: 'itunes', id: 1547113874, t: 'ملهمش في الطيب', alt: [], s: 'إيهاب توفيق', era: 'pop', en: 'Malhomsh Fel Tayeb', se: 'Ehab Tawfik' },
  { src: 'itunes', id: 1635747421, t: 'اللي بنى مصر', alt: [], s: 'علي الحجار', era: 'pop', en: 'Elli Bana Masr', se: 'Ali El Haggar' },
  { src: 'itunes', id: 558582408, t: 'الحب الحقيقي', alt: [], s: 'محمد فؤاد', era: 'pop', en: 'El Hob El Haqiqi', se: 'Mohamed Fouad' },
  { src: 'itunes', id: 558599987, t: 'حيران', alt: [], s: 'محمد فؤاد', era: 'pop', en: 'Hayran', se: 'Mohamed Fouad' },
  { src: 'itunes', id: 1546552578, t: 'علي الضحكاية', alt: [], s: 'هاني شاكر', era: 'pop', en: 'Ali El Dehkaya', se: 'Hany Shaker' },
  { src: 'itunes', id: 1104778171, t: 'كده برضه يا قمر', alt: [], s: 'هاني شاكر', era: 'pop', en: 'Keda Bardo Ya Amar', se: 'Hany Shaker' },
  { src: 'itunes', id: 1546561076, t: 'نسيانك صعب أكيد', alt: ['نسيانك صعب'], s: 'هاني شاكر', era: 'pop', en: 'Nesyanak Sa\'b', se: 'Hany Shaker' },
  { src: 'itunes', id: 1546554071, t: 'غلطة', alt: [], s: 'هاني شاكر', era: 'pop', en: 'Ghalta', se: 'Hany Shaker' },
  { src: 'itunes', id: 1546723922, t: 'الحلم الجميل', alt: [], s: 'هاني شاكر', era: 'pop', en: 'El Helm El Gamil', se: 'Hany Shaker' },
  { src: 'itunes', id: 271202937, also: { src: 'deezer', id: 81103242 }, t: 'بحبك يا غالي', alt: [], s: 'هاني شاكر', era: 'pop', en: 'Bahebbak Ya Ghali', se: 'Hany Shaker' },
  { src: 'itunes', id: 851754887, t: 'كوكب تاني', alt: [], s: 'مدحت صالح', era: 'pop', en: 'Kawkab Tani', se: 'Medhat Saleh' },
  { src: 'itunes', id: 556962231, t: 'قوم أقف', alt: [], s: 'بهاء سلطان', era: 'pop', en: 'Oum O\'af', se: 'Bahaa Sultan' },
  { src: 'itunes', id: 1633108057, also: { src: 'deezer', id: 1814239477 }, t: 'وسع وسع', alt: [], s: 'أحمد سعد', era: 'new', en: 'Wassa\' Wassa\'', se: 'Ahmed Saad' },
  { src: 'itunes', id: 1477743946, also: { src: 'deezer', id: 739734912 }, t: 'العب يلا', alt: [], s: 'أوكا وأورتيجا', era: 'new', en: 'El\'ab Yalla', se: 'Oka Wi Ortega' },
  { src: 'itunes', id: 1851321784, t: 'دورك جاي', alt: [], s: 'ويجز', era: 'new', en: 'Dorak Gai', se: 'Wegz' },
  { src: 'itunes', id: 1295177332, t: 'تلت دقات', alt: ['3 دقات'], s: 'أبو ويسرا', era: 'new', en: '3 Daqat', se: 'Abu & Yousra' },
  { src: 'itunes', id: 1439094113, t: 'رب الكون ميزنا بميزة', alt: [], s: 'حمو بيكا', era: 'new', en: 'Rab El Kon Mayezna Be Meeza', se: 'Hamo Bika' },
  { src: 'itunes', id: 1693797095, also: { src: 'deezer', id: 2337820375 }, t: 'هرمون السعادة', alt: [], s: 'تامر حسني', era: 'new', en: 'Hormone El Sa\'ada', se: 'Tamer Hosny' },
  { src: 'itunes', id: 1670387675, also: { src: 'deezer', id: 2139916097 }, t: 'أحلى حاجة فيكي', alt: [], s: 'محمد حماقي', era: 'new', en: 'Ahla Haga Feeki', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1775961629, also: { src: 'deezer', id: 3059980271 }, t: 'يتعلموا', alt: [], s: 'عمرو دياب', era: 'new', en: 'Yetallemo', se: 'Amr Diab' },
  { src: 'itunes', id: 1775963104, also: { src: 'deezer', id: 3059990061 }, t: 'سهران', alt: [], s: 'عمرو دياب', era: 'new', en: 'Sahran', se: 'Amr Diab' },
  { src: 'itunes', id: 1775936889, also: { src: 'deezer', id: 3059790031 }, t: 'يا أجمل عيون', alt: [], s: 'عمرو دياب', era: 'new', en: 'Ya Agmal Oyoun', se: 'Amr Diab' },
  { src: 'itunes', id: 1698514243, also: { src: 'deezer', id: 2375828355 }, t: 'لمون نعناع', alt: [], s: 'محمد حماقي', era: 'new', en: 'Lamoun Ne\'na\'', se: 'Mohamed Hamaki' },
  { src: 'deezer', id: 3623231212, t: 'الأطلال', alt: [], s: 'أم كلثوم', era: 'classic', en: 'El Atlal', se: 'Umm Kulthum' },
  { src: 'deezer', id: 3623246202, t: 'ألف ليلة وليلة', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Alf Leila We Leila', se: 'Umm Kulthum' },
  { src: 'deezer', id: 3623246002, t: 'أمل حياتي', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Amal Hayati', se: 'Umm Kulthum' },
  { src: 'deezer', id: 3623206102, t: 'دارت الأيام', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Daret El Ayam', se: 'Umm Kulthum' },
  { src: 'deezer', id: 3623229182, t: 'حب إيه', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Hobb Eh', se: 'Umm Kulthum' },
  { src: 'deezer', id: 3623249772, t: 'فات الميعاد', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Fat El Mi\'ad', se: 'Umm Kulthum' },
  { src: 'deezer', id: 3623246922, t: 'بعيد عنك', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Ba\'id Annak', se: 'Umm Kulthum' },
  { src: 'deezer', id: 3623249802, t: 'انساك', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Ansak', se: 'Umm Kulthum' },
  { src: 'deezer', id: 2753047881, t: 'فكروني', alt: [], s: 'أم كلثوم', era: 'classic', en: 'Fakkarouni', se: 'Umm Kulthum' },
  { src: 'deezer', id: 391645242, t: 'الجندول', alt: [], s: 'محمد عبد الوهاب', era: 'classic', en: 'El Gondol', se: 'Mohamed Abdel Wahab' },
  { src: 'deezer', id: 1136040552, t: 'حدوتة مصرية', alt: [], s: 'محمد منير', era: 'pop', en: 'Haddouta Masreya', se: 'Mohamed Mounir' },
  { src: 'deezer', id: 570357562, t: 'علي صوتك', alt: [], s: 'محمد منير', era: 'pop', en: 'Alli Soutak', se: 'Mohamed Mounir' },
  { src: 'deezer', id: 4112808531, t: 'شجر الليمون', alt: [], s: 'محمد منير', era: 'pop', en: 'Shagar El Lamoun', se: 'Mohamed Mounir' },
  { src: 'deezer', id: 3642668572, t: 'البخت', alt: [], s: 'ويجز', era: 'new', en: 'El Bakht', se: 'Wegz' },
  { src: 'deezer', id: 3644676912, t: 'باظت', alt: [], s: 'ويجز', era: 'new', en: 'Bazet', se: 'Wegz' },
  { src: 'deezer', id: 2324369265, t: 'اختياراتي', alt: [], s: 'أحمد سعد', era: 'new', en: 'Ekhtiyarati', se: 'Ahmed Saad' },
  { src: 'deezer', id: 1816626217, t: 'اليوم الحلو ده', alt: [], s: 'أحمد سعد', era: 'new', en: 'El Youm El Helw Dah', se: 'Ahmed Saad' },
  { src: 'deezer', id: 3239581241, t: 'سيد الناس', alt: [], s: 'أحمد سعد', era: 'new', en: 'Seed El Nas', se: 'Ahmed Saad' },
  { src: 'deezer', id: 3462254121, t: 'مكسرات', alt: [], s: 'أحمد سعد', era: 'new', en: 'Mekassarat', se: 'Ahmed Saad' },
  { src: 'deezer', id: 3439612741, t: 'خطفوني', alt: [], s: 'عمرو دياب', era: 'new', en: 'Khatafouni', se: 'Amr Diab & Jana' },
  { src: 'deezer', id: 3059990191, t: 'قدام مرايتها', alt: [], s: 'عمرو دياب', era: 'new', en: 'Oddam Merayetha', se: 'Amr Diab' },
  { src: 'deezer', id: 3059790071, t: 'معدي الناس', alt: [], s: 'عمرو دياب', era: 'new', en: 'Me\'addi El Nas', se: 'Amr Diab' },
  { src: 'deezer', id: 3894820861, t: 'يمكن خير', alt: [], s: 'رامي صبري', era: 'new', en: 'Yemken Kheir', se: 'Ramy Sabry' },
  { src: 'deezer', id: 2891437622, t: 'آه لو لعبت يا زهر', alt: ['آه لو لعبت'], s: 'أحمد شيبة', era: 'new', en: 'Ah Law Le\'ebt Ya Zahr', se: 'Ahmed Sheba' },
  { src: 'deezer', id: 1731706987, t: 'داري يا قلبي', alt: [], s: 'حمزة نمرة', era: 'new', en: 'Dari Ya Albi', se: 'Hamza Namira' },
  { src: 'deezer', id: 2553542532, t: 'أيام', alt: [], s: 'تامر عاشور', era: 'new', en: 'Ayam', se: 'Tamer Ashour' },
  { src: 'deezer', id: 2553542572, t: 'قولوا له سماح', alt: [], s: 'تامر عاشور', era: 'new', en: 'Oulouloh Samah', se: 'Tamer Ashour' },
  { src: 'deezer', id: 573699552, t: 'الوتر الحساس', alt: [], s: 'شيرين', era: 'new', en: 'El Watar El Hassas', se: 'Sherine' },
  { src: 'itunes', id: 1675937898, t: 'عودوني', alt: [], s: 'عمرو دياب', era: 'pop', en: 'Awedouni', se: 'Amr Diab' },
  { src: 'itunes', id: 1670388301, t: 'واحدة واحدة', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Wahda Wahda', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1670475279, t: 'حاجة مش طبيعية', alt: [], s: 'محمد حماقي', era: 'pop', en: 'Haga Mesh Tabe\'eya', se: 'Mohamed Hamaki' },
  { src: 'itunes', id: 1759861647, t: 'بقالك قلب', alt: [], s: 'أنغام', era: 'new', en: 'Ba\'alak Alb', se: 'Angham' },
  { src: 'itunes', id: 1599778056, t: 'عمري ابتدا', alt: [], s: 'تامر حسني', era: 'new', en: 'Omri Ebtada', se: 'Tamer Hosny' },
  { src: 'itunes', id: 1823382309, t: 'بتمنى أنساك', alt: [], s: 'شيرين', era: 'new', en: 'Batmanna Ansak', se: 'Sherine' }
];
