/* ============================================================================
   خمن الكلمة — WORDLE: the word lists and the keypad
   ----------------------------------------------------------------------------
   Shared by the page (inlined by tools/build-*.mjs: the one-phone game and a
   room's keyboard) and the rooms server (bundled by rooms-worker/build.mjs: a
   room's race deals from these lists, and a written word is checked against
   the keypad). Moved out of JS_Wordle.html on 23 Sep 2026 for the rooms, so
   the lists keep one copy (GEMINI.md, *Decided, and why*).

   WORDLE_DB: the words by language and by strict length (5 to 8).
   WORDLE_LAYOUTS: the keypad, which is also the alphabet a word may use - the
   Arabic one has a single alef, so أ إ آ are folded to ا when a word is dealt.
   ========================================================================= */
const WORDLE_DB = {
    ar: {
        5: [
            "بناية", "بنفسج", "تفاحة", "جامعة", "جزيرة", "حافلة", "حديقة", "حقيبة", "حيوان", "خريطة",
            "خزانة", "رسامة", "زجاجة", "ستارة", "سجادة", "سحابة", "سروال", "سفينة", "سيارة", "شاحنة",
            "صيدلي", "طائرة", "طاولة", "طبيعة", "طيارة", "عصفور", "عيادة", "فاكهة", "فستان", "قلادة",
            "كاتبة", "كنيسة", "لاعبة", "ليمون", "محفظة", "مدربة", "مدرسة", "مدينة", "مسبحة", "مطرقة",
            "مكتبة", "ملحمة", "ملعقة", "منارة", "منديل", "منشار", "مهندس", "ميزان", "نافذة", "نظارة",
            "طاووس", "تمساح", "زرافة", "دبابة", "صاروخ", "عمارة", "بوابة", "مركبة", "غواصة", "ميدان",
            "مصباح", "بطولة", "خاتمة", "رسالة", "صحيفة", "جريدة", "طماطم", "بطاطس", "ريحان", "قرنفل",
            "فلافل", "مغارة", "قبطان", "خوذات", "لوحات", "تمثيل",
            "سماعة", "ممحاة", "مسطرة", "كراسة", "سبورة", "شمسية",
            "ثلاجة", "غسالة", "مكنسة", "مروحة", "مكواة", "طابعة",
            "مفتاح", "حمامة", "دجاجة", "غزالة", "نعامة", "فراشة",
            "سنجاب", "جاموس", "بطريق", "دلفين", "ببغاء", "كناري",
            "مانجو", "بطيخة", "شمامة", "جوافة", "كمثرى", "رمانة",
            "زيتون", "خيارة", "سبانخ", "بامية", "شوربة", "فطيرة",
            "كنافة", "قطايف", "بيتزا", "نعناع", "زبادي", "بسكوت",
            "سينما", "صحراء", "بحيرة", "كوبري", "ميناء", "مزرعة",
            "ممرضة", "محامي", "معلمة", "مزارع", "مبرمج", "محاسب",
            "مسمار", "شاكوش", "كماشة", "سوستة", "سلسلة", "جاكيت",
            "فانوس", "راديو", "تلفاز", "حاسوب", "برواز", "رواية",
            "قصيدة", "بالون", "دراجة", "تاكسي", "عاصفة", "إعصار",
            "زلزال", "بركان", "سعادة", "صداقة", "شجاعة", "عدالة",
            "أمانة", "كرامة", "نظافة", "رياضة", "سباحة", "جائزة",
            "هزيمة", "عائلة", "طفولة", "حبيبة", "ملابس", "صحفية",
            "مذيعة", "أرانب", "أمواج", "زلازل", "عواصف", "كواكب",
            "مجرات", "سكينة", "أطباق", "فنجان", "إبريق", "مقلاة",
            "عصائر", "مشروب", "توابل", "كاتشب", "عرائس", "ألعاب",
            "ملاهي", "حدائق", "متاحف", "مطاعم", "فنادق", "مدارس",
            "جوائز", "هدايا", "محطات", "جمباز", "شطرنج", "برامج",
            "إذاعة", "حفلات", "رمضان", "إفطار", "عيدية", "أضحية",
            "رحلات", "سياحة", "مصايف", "عباءة", "ساعات", "أساور",
            "خواتم", "مكياج", "شامبو", "معجون", "فرشاة", "مناشف",
            "مخدات", "ستائر", "كراسي", "تكييف", "تذاكر", "جرائد",
            "مجلات", "ألغاز", "معابد", "أسوار", "أبراج", "كباري",
            "أنفاق", "شوارع", "زواحف", "حشرات", "عناكب", "ضفادع",
            "غربان", "حيتان", "أسماك", "مرجان", "قواقع", "علماء",
            "تجارب", "تاريخ", "فلسفة", "هندسة", "كشكول", "أقلام",
            "مساطر", "ألوان", "حقائب", "ملاعب", "كليات", "معاهد",
            "درجات", "نتيجة", "إجازة", "عطلات", "مطبات", "مسارح",
            "تشجيع", "كابتن", "سعرات",

            "باندا", "كوالا", "بابون", "راكون", "قضاعة", "ألبكة", "جربوع", "يمامة", "كتكوت", "بلشون",
            "طوقان", "كروان", "سنونو", "جمبري", "سردين", "سلمون", "كركند", "ثعبان", "كوبرا", "سحلية",
            "حرباء", "سمندل", "ذبابة", "صرصار", "جرادة", "يعسوب", "يراعة", "حلزون", "برغوث", "زنبور",
            "ماموث", "يوسفي", "برقوق", "ليتشي", "بوملي", "بطاطا", "لوبيا", "كزبرة", "جرجير", "مشروم",
            "خرشوف", "قلقاس", "مسقعة", "طعمية", "ممبار", "بصارة", "نودلز", "تبولة", "ناجتس", "كوارع",
            "غريبة", "تورتة", "جاتوه", "دونات", "مصاصة", "هريسة", "عسلية", "حمصية", "فولية", "بودنج",
            "لاتيه", "ينسون", "سوبيا", "سموذي", "حبهان", "خميرة", "طحينة", "شوفان", "فوتيه", "مرتبة",
            "ملاية", "دولاب", "مراية", "شماعة", "دفاية", "تلاجة", "فريزر", "جاروف", "ممسحة", "صينية",
            "معلقة", "مغرفة", "مصفاة", "مبشرة", "فتاحة", "عصارة", "غلاية", "توستر", "نشابة", "بانيو",
            "حنفية", "سيفون", "منشفة", "ولاعة", "كبريت", "ريموت", "رسيفر", "صندوق", "قزازة", "مبخرة",
            "حصالة", "شنيور", "إزميل", "كوريك", "خرطوم", "صنفرة", "عباية", "بلوزة", "بلوفر", "بالطو",
            "صديري", "مايوه", "كولون", "كوتشي", "طاقية", "كوفية", "أسورة", "خلخال", "مريلة", "طربوش",
            "جلباب", "براية", "مقلمة", "ماركر", "دباسة", "خرامة", "منقلة", "قاموس", "تابلت", "فلاشة",
            "راوتر", "سبيكر", "عربية", "سكوتر", "فلوكة", "منطاد", "تريلا", "حنطور", "زلاجة", "عبارة",
            "عاصمة", "حضانة", "محكمة", "سفارة", "وزارة", "بلدية", "مطافي", "مقابر", "بقالة", "جزارة",
            "كافيه", "شاليه", "منتجع", "استاد", "أوبرا", "جنينة", "حظيرة", "إسطبل", "مغسلة", "سايبر",
            "بدروم", "دكتور", "عسكري", "جرسون", "مترجم", "كاشير", "سمسار", "مخترع", "بيطري", "تجديف",
            "إبحار", "رماية", "زومبا", "قانون", "تشيلو", "جيتار", "بيانو", "درامز", "مزمار", "ربابة",
            "صاجات", "شبورة", "فيضان", "حواجب", "شفايف", "جمجمة", "شريان", "زايدة", "عضلات", "صنارة",
            "روبوت", "حرامي", "عروسة", "بوصلة", "مظروف", "برميل", "ساقية", "أميرة", "قرصان",
            "نينجا", "فرعون", "ساحرة", "شرنقة", "صبارة", "صفارة", "دبدوب", "دارتس", "زومبي", "عملاق",
            "ضفيرة", "مرساة", "صابون", "إسعاف", "جاسوس", "تذكرة", "بطاقة", "إسمنت", "بترول", "ياقوت",
            "صلصال", "أدغال", "مقبرة", "صالون", "حداية", "قنديل", "سندان", "مجرفة", "طنجرة", "شواية",
            "تمثال", "علامة", "شهادة", "توقيع", "عنوان", "عفريت", "رادار", "أغنية", "إيقاع",
            "جمهور", "تصفيق", "فيروس", "كثبان", "عنقود", "بستان", "فزاعة", "أرضية", "ألبوم", "كاكاو",
            "عطارد", "أوزون", "عنقاء", "بوسطة", "جمارك", "سرداب", "حورية", "ركنية", "إيميل",
            "فيديو", "سيلفي", "تطبيق", "كهربا", "كربون", "منشور", "مليون", "زاوية", "دايرة", "تجربة",
            "حقيقة", "ضريبة", "دولار", "كابوس", "تلميذ", "بردية", "جعران", "تنورة",
            
            
            "تابوت", "مضيفة", "نطاطة", "محارة", "لؤلؤة",
            "كمامة"
        ],
        6: [
            "أناناس", "برتقال", "بروتين", "بسكويت", "بقدونس", "بندقية", "تليفون", "سلطانة", "صابونة",
            "صيدلية", "فراولة", "كاميرا", "كهرباء", "محاسبة", "مستشار", "مستشفى", "مكتبات", "مكرونة",
            "ملوخية", "نافورة",
            "شاورما", "طاحونة", "غواصات", "زنجبيل", "قنصلية", "صناديق", "عصافير", "فراشات", "مفاتيح",
            "مهرجان", "مغامرة", "سفارات", "موسيقى", "طائرات", "سيارات", "حلويات", "إشاعات",
            "تضحيات", "امتحان",
            "جامعات", "تماثيل", "شبابيك", "براميل", "حافلات", "قاطرات", "دراجات", "شاحنات", "مهندسة", "صيادلة", "مزارعة", "مثلجات", "معجنات",
            "بطانية", "سلحفاة", "أخطبوط", "قرنبيط", "بسبوسة", "زلابية",
            "حواوشي", "سندوتش", "موبايل", "بطارية", "كرافتة", "بنطلون",
            "مروحية", "ملاكمة", "مصارعة", "مباراة", "ذكريات", "تلميذة",
            "ثلاجات", "غسالات", "كراسات", "مصابيح", "سماعات", "ممرضات",
            "معلمات", "زرافات", "بحيرات", "شلالات", "براكين", "صواريخ",
            "كوباية", "مشويات", "مكسرات", "بهارات", "فوانيس", "مراجيح",
            "بطاطين", "مطارات", "طيارات", "قطارات", "عربيات", "إسكواش",
            "بولينج", "دومينو", "أغنيات", "احتفال", "فساتين", "بناطيل",
            "جلابية", "نظارات", "ملايات", "سجاجيد", "دواليب", "دكاترة",
            "أساتذة", "تلاميذ", "مشاهير", "بطاقات", "كتيبات", "حكايات",
            "فوازير", "مفاجآت", "إنترنت", "رسومات", "فراعنة", "مومياء",
            "ميادين", "تماسيح", "ثعابين", "صراصير", "بطاريق", "دلافين",
            "حضارات", "اكتشاف", "اختراع", "كيمياء", "فيزياء", "كراريس",
            "سبورات", "طباشير", "واجبات", "شهادات", "إشارات", "جراجات",
            "مرشدين", "إجازات", "ممثلات", "مخرجين", "مطربين", "كواليس",
            "جماهير", "مشجعين", "هتافات", "بطولات", "مدربين", "لاعبين",
            "هدافين",

            "جاموسة", "هامستر", "غوريلا", "كوكاتو", "عندليب", "إغوانا", "ناموسة", "خنفساء", "دعسوقة", "عنكبوت",
            "رتيلاء", "بابايا", "قراصيا", "بروكلي", "شكشوكة", "صيادية", "برياني", "مقلوبة", "سمبوسة", "أومليت",
            "لانشون", "بسطرمة", "مهلبية", "بقلاوة", "سمسمية", "كركديه", "عرقسوس", "كوكتيل", "زعفران", "مستردة",
            "بلكونة", "تسريحة", "كسرولة", "مناديل", "شمعدان", "كرتونة", "برطمان", "زرادية", "صامولة", "مسامير",
            "تيشيرت", "بابيون", "بيجامة", "برنيطة", "إيشارب", "جوانتي", "أستيكة", "زمزمية", "لابتوب", "كيبورد",
            "أتوبيس", "تلفريك", "فكهاني", "كوافير", "بنزينة", "جنايني", "سكرتير", "بهلوان", "ساعاتي", "مبارزة",
            "فروسية", "كريكيت", "بيسبول", "باركور", "مناخير", "تلسكوب", "بالونة", "ليمونة", "توكتوك", "زحليقة",
            "مرجيحة", "مكعبات", "كرافات", "مستنقع", "مستودع", "ياسمين", "بازلاء",
            "أرجوحة", "فاتورة", "أسطورة", "سوداني", "حرباية", "برلمان", "بلوتوث", "مكالمة", "هاشتاج", "برنامج",
            "باسورد", "أكسجين", "معادلة", "باروكة", "مفاجأة", "مستقبل", "خيامية",
            
            
        ],
        7: [
            "أوكسجين", "اتصالات", "استخدام", "استخراج", "استراحة", "استعلام", "استقبال", "استيراد", "اكسسوار", "المنيوم",
            "بطاريات", "بلاستيك", "تلفزيون", "سندويتش", "فاصوليا", "فيتامين", "قرطاسية", "كمبيوتر", "مجوهرات", "معكرونة",
            "ميدالية", "ميزانية", "ميكانيك", "هامبرغر",
            "إلكترون", "باذنجان", "حيوانات", "صيدليات", "مخابرات", "معسكرات", "مقابلات", "تطبيقات", "إنجازات",
            "مواصلات", "مشروبات", "مأكولات", "معلومات", "إعلانات", "تعليمات", "تدريبات", "تنظيمات", "تجهيزات", "تركيبات", "توزيعات", "مسابقات", "مناسبات", "محادثات", "مناقشات", "محاضرات", "إحصائية", "استعداد", "استقرار", "استفادة", "استجابة",
            "ديناصور", "سكرتيرة", "مخبوزات", "مايونيز", "برتقالة", "ماكينات",
            "كرواسون", "تاكسيات", "كاراتيه", "بلياردو", "كوتشينة", "مسلسلات",
            "مسرحيات", "مغامرات", "برفانات", "ترابيزة", "أباجورة", "بوتاجاز",
            "كهربائي", "مطبوعات", "برمجيات", "كاميرات", "أهرامات", "نافورات",
            "بلكونات", "أسانسير", "مسافرين", "منتجعات", "شاليهات", "جمهورية",
            "استقلال", "مواطنين", "محافظات", "مسؤولية", "إنسانية", "مخترعين",
            "مختبرات", "رياضيات", "جغرافيا", "مجموعات", "مشروعات", "مصروفات",
            "موسيقار", "كوميديا", "استوديو", "ماراثون", "تمرينات", "رياضيين",
            "مشاهدين", "مغامرين", "استكشاف", "فيروسات", "بكتيريا", "منتخبات",
            "مباريات",

            "شمبانزي", "فلامنجو", "كابوريا", "أفوكادو", "كومكوات", "لازانيا", "ساندوتش", "براونيز", "سينابون", "نسكافيه",
            "إسبريسو", "فانيليا", "كوافيرة", "يوتيوبر", "جواهرجي", "أيروبكس", "ترومبيت", "ساكسفون", "ترومبون", "بسكويتة",
            "مانجاية", "تليسكوب", "مغناطيس", "باراشوت", "بالونات", "ترمومتر", "بارومتر", "مسحراتي",
            
            "أوتوبيس", "ابتسامة",
            "شاليموه"
        ],
        8: [
            "ابتكارات", "احتفالات", "اختراعات", "اشتراكية", "الكتروني", "اماراتية", "امبراطور", "انتخابات", "انجليزية", "بريطانيا",
            "ديكتاتور", "رأسمالية", "شوكولاتة", "فلسطينية", "ليبرالية", "مستحضرات", "مستشفيات", "مهرجانات", "نيتروجين",
            "إحصائيات", "استشارات", "اكتشافات", "امتحانات", "انتصارات", "جمهوريات",
            "مستودعات", "تليفونات", "دبلوماسي", "ميكانيكا", "تلسكوبات",
            "ميكروويف", "موتوسيكل", "أتوبيسات", "مونوبولي", "تليفزيون", "فيديوهات",
            "ميكانيكي", "كهربائية", "مستوصفات", "ميداليات", "سندوتشات", "اختبارات",
            "مستشارين", "تراجيديا", "ميكروفون", "أولمبياد", "مستكشفين", "ألومنيوم",
            "ميكروبات", "بروتينات",

            "استاكوزا", "أناكوندا", "كانتالوب", "يوستفندي", "كاليماري", "مارشميلو", "كابتشينو", "كومودينو", "يونيفورم", "بروجكتور",
            "ميكروباص", "هليكوبتر", "تايكوندو", "ترايثلون", "كونترباص", "كلارينيت", "أكورديون", "يونيكورن", "ليمونادة", "طماطماية",
            "باذنجانة", "استغماية", "هيدروجين"
        ]
    },
    en: {
        5: [
            "APPLE", "BEACH", "BLACK", "BREAD", "CHAIR", "EARTH", "HOUSE", "LIGHT", "MONEY", "MOUSE",
            "MUSIC", "NIGHT", "PHONE", "PLANT", "RIVER", "SOUND", "TABLE", "WATER", "WHITE", "WORLD",
            "TRAIN", "CLOUD", "HEART", "SMILE", "DREAM", "HORSE", "GREEN", "CANDY", "TIGER", "SUGAR",
            "PIANO", "CLOCK", "GHOST", "PARTY", "MAGIC", "SHARK", "QUEEN", "OCEAN", "BRAIN", "STORM",
            "RADIO", "LEMON", "GRAPE", "CHESS", "SPACE", "FLAME", "BRUSH", "KNIFE", "SWEET", "SPOON",
            "GLASS", "TOWER", "CROWN", "METAL", "SKILL", "WATCH", "BLOOD", "TRUCK", "BLIND", "PEACE",
            "ANGEL", "ARROW", "BACON", "BADGE", "BAKER", "BENCH",
            "BERRY", "BIRTH", "BLADE", "BLOOM", "BOARD", "BOOTS",
            "BRICK", "BRIDE", "BROOM", "BUNNY", "CABIN", "CAMEL",
            "CANOE", "CARGO", "CHAIN", "CHALK", "CHARM", "CHEEK",
            "CHILI", "CLIFF", "CLOWN", "COACH", "COAST", "COCOA",
            "CORAL", "COUCH", "CRANE", "CREAM", "CROWD", "CURRY",
            "DAISY", "DANCE", "DIARY", "DRESS", "DRINK", "DRUMS",
            "EAGLE", "ELBOW", "FAIRY", "FEAST", "FENCE", "FIELD",
            "FLOOR", "FLOUR", "FLUTE", "FROST", "FRUIT", "GIANT",
            "GLOBE", "GLOVE", "GRASS", "GUARD", "GUEST", "HONEY",
            "HOTEL", "JELLY", "JEWEL", "JUICE", "KOALA", "LASER",
            "LLAMA", "LUNCH", "MANGO", "MAPLE", "MEDAL", "MELON",
            "MODEL", "MOTOR", "NURSE", "OLIVE", "ONION", "OTTER",
            "PANDA", "PAINT", "PAPER", "PEACH", "PEARL", "PILOT",
            "PIZZA", "PLATE", "POLAR", "PUPPY", "QUILT", "RAVEN",
            "ROBOT", "ROYAL", "SALAD", "SAUCE", "SCARF", "SHEEP",
            "SHELF", "SHIRT", "SKATE", "SLIDE", "SNAKE", "SOLAR",
            "SPICE", "STEAM", "STICK", "STONE", "STOVE", "SWING",
            "SWORD", "TEETH", "THUMB", "TOAST", "TORCH", "TOWEL",
            "TRACK", "TULIP", "VIDEO", "WAGON", "WHALE", "WHEAT",
            "WHEEL", "WRIST", "YACHT", "ZEBRA",

            "HYENA", "RHINO", "HIPPO", "MOOSE", "BISON", "LEMUR", "SLOTH", "SKUNK", "GOOSE", "CHICK",
            "QUAIL", "HERON", "STORK", "ROBIN", "SQUID", "COBRA", "VIPER", "GECKO", "SNAIL", "GUAVA",
            "DATES", "BASIL", "THYME", "SUSHI", "KEBAB", "STEAK", "RAMEN", "KOFTA", "DONUT",
            "FUDGE", "LATTE", "MOCHA", "CUMIN", "YEAST", "PASTA", "BEANS", "FLASK", "LADLE", "SIEVE",
            "RAZOR", "CABLE", "SCREW", "DRILL", "SPADE", "JEANS", "SKIRT", "SOCKS", "SHOES", "APRON",
            "RULER", "STAMP", "ATLAS", "DRONE", "LORRY", "FERRY", "VILLA", "ALLEY", "COURT", "KIOSK",
            "OASIS", "STUDY", "JUDGE", "ACTOR", "DIVER", "MAYOR", "PADEL", "RUGBY",
            "CELLO", "BANJO", "FLOOD", "COMET", "MOUTH", "CHEST", "TUMMY", "WAIST", "ANKLE", "LUNGS",
            "LIVER", "SKULL", "SPINE", "PLANE", "TOOTH", "THIEF", "NINJA", "ALIEN", "MUMMY", "GENIE",
            "WITCH", "SMOKE", "BEARD", "BAGEL", "IGLOO", "DARTS", "PLAIT", "METRO", "SCALE", "STEEL",
            "SWAMP", "ANVIL", "MATCH", "LEVER", "GRILL", "SPEAR", "SIREN", "ARMOR", "FRAME", "ORGAN",
            "TOKEN", "AGENT", "BLOCK", "CHECK", "COMIC", "COVER", "CRASH", "CROSS", "CYCLE", "DRAFT",
            "DWARF", "FORCE", "GRACE", "MARCH", "MOUNT", "NOVEL", "OPERA", "PASTE", "PITCH", "POINT",
            "PRESS", "PUPIL", "ROUND", "SPELL", "SPIKE", "STAFF", "STATE", "TRUNK", "ATTIC", "PORCH",
            "STOOL", "DOUGH", "GRAVY", "SYRUP", "ORBIT", "SHELL", "ARENA", "CANAL", "MOTEL", "RANCH",
            "RUINS", "GUIDE", "JOKER", "MINER", "TROLL", "UNCLE", "SCORE", "SERVE", "THROW", "ALARM",
            "EMAIL", "METER", "MODEM", "PIXEL", "RADAR", "VIRUS", "KAYAK", "PURSE", "NOISE", "POWER",
            "PRIZE", "RUMOR", "STORY", "TRUTH",
            
            
            "PANTS", "TEARS", "SLEEP", "SALON", "STRAW", "TEDDY"
        ],
        6: [
            "ANIMAL", "BANANA", "CARROT", "COUSIN", "FAMILY", "FATHER", "FLOWER", "FRIEND", "GARDEN", "GARLIC",
            "MOTHER", "NATURE", "ORANGE", "PENCIL", "PEPPER", "PLANET", "POTATO", "SCHOOL", "SISTER", "TOMATO",
            "MONKEY", "BRIDGE", "CASTLE", "DOCTOR", "SUMMER", "WINTER", "SPRING", "BOTTLE", "BUTTER", "CIRCLE",
            "COFFEE", "DANGER", "DOLLAR", "DRAGON", "FOREST", "GUITAR", "ISLAND", "JUNGLE", "MARKET", "MIRROR",
            "PALACE", "POLICE", "PURPLE", "RABBIT", "ROCKET", "SILVER", "SPIDER", "TICKET", "TRAVEL", "WALLET",
            "WINDOW", "YELLOW", "CAMERA", "BUTTON", "CANDLE", "CHEESE", "DINNER", "ENGINE", "FLIGHT", "LEADER",
            "ANCHOR", "ARCADE", "ARTIST", "AUTUMN", "BAKERY", "BALLET",
            "BASKET", "BEAVER", "BLAZER", "BREEZE", "BUCKET", "CACTUS",
            "CANVAS", "CARPET", "CEREAL", "CHERRY", "CIRCUS", "CLOVER",
            "COMEDY", "COOKIE", "COPPER", "COTTON", "COYOTE", "CRAYON",
            "CRUISE", "DESERT", "DONKEY", "FALCON", "FINGER", "FOSSIL",
            "FRIDGE", "GALAXY", "GARAGE", "HAMMER", "HELMET", "HOCKEY",
            "INSECT", "JACKET", "JIGSAW", "KETTLE", "LADDER", "LAPTOP",
            "LIZARD", "LOCKER", "MAGNET", "MEADOW", "MITTEN", "MUFFIN",
            "NAPKIN", "NEEDLE", "OYSTER", "PARROT", "PEANUT", "PEBBLE",
            "PICNIC", "PILLOW", "PIRATE", "POCKET", "PUZZLE", "RACKET",
            "RAISIN", "RIBBON", "SADDLE", "SAFARI", "SALMON", "SCREEN",
            "SHOVEL", "SHOWER", "SLEEVE", "SOCCER", "SPONGE", "SQUASH",
            "STATUE", "STREET", "STRIPE", "SUNSET", "TABLET", "TEAPOT",
            "TENNIS", "TROPHY", "TUNNEL", "TURTLE", "VALLEY", "VIOLIN",
            "WALRUS", "WIZARD", "WALNUT", "ZIPPER",

            "JAGUAR", "BABOON", "BADGER", "WEASEL", "ALPACA", "KITTEN", "JERBOA", "FERRET", "PIGEON", "CANARY",
            "TURKEY", "HOOPOE", "TOUCAN", "MAGPIE", "SHRIMP", "MUSSEL", "PYTHON", "IGUANA", "BEETLE", "LOCUST",
            "HORNET", "GRAPES", "PAPAYA", "LYCHEE", "PRUNES", "RADISH", "TURNIP", "CELERY", "GINGER", "BURGER",
            "HUMMUS", "SAMOSA", "PAELLA", "QUICHE", "NACHOS", "TOFFEE", "TRIFLE", "ECLAIR",
            "SUNDAE", "TAHINI", "OLIVES", "BULGUR", "STAIRS", "HEATER", "COOKER", "GRATER", "JUICER", "TOILET",
            "LOOFAH", "PLIERS", "WRENCH", "CHISEL", "SICKLE", "SHORTS", "BLOUSE", "JUMPER", "HOODIE", "TIGHTS",
            "BEANIE", "GLOVES", "ANKLET", "BROOCH", "TURBAN", "RUBBER", "MARKER", "DRAWER", "FOLDER", "ROUTER",
            "DIGGER", "SLEDGE", "SQUARE", "CLINIC", "PRISON", "MOSQUE", "CHURCH", "TEMPLE", "CHALET", "RESORT",
            "CINEMA", "MUSEUM", "STABLE", "OFFICE", "LAWYER", "SAILOR", "FARMER", "DRIVER", "WAITER", "BARBER",
            "TAILOR", "SINGER", "WRITER", "TRADER", "PRIEST", "DIVING", "ROWING", "BOXING", "KARATE", "SKIING",
            "BRANCH", "METEOR", "TONGUE", "KIDNEY", "MUSCLE", "ARTERY", "SWITCH", "SHIELD", "SCALES", "TUXEDO",
            "ERASER", "BARREL", "SPHINX", "KNIGHT", "COCOON", "WAFFLE", "TEACUP", "ZOMBIE",
            "THREAD", "PLAYER", "SHADOW", "DOMINO", "SECRET", "MEMORY", "COLOUR", "NUMBER", "LETTER",
            "PARCEL", "SANDAL", "MARBLE", "STUDIO", "HARBOR", "PULLEY", "OPENER", "SAUCER",
            "MIRAGE", "BANNER", "CHEQUE", "CENTER", "CHANGE", "CHARGE", "DEGREE", "FIGURE",
            "GROUND", "STREAM", "STRIKE", "STRING", "VACUUM", "CLOSET", "HANGER", "NOODLE", "PICKLE",
            "YOGURT", "BAMBOO", "CANYON", "CRATER", "NEBULA", "POODLE", "BORDER", "CELLAR", "SUBWAY",
            "ARCHER", "AUTHOR", "BANDIT", "COWBOY", "HUNTER", "JESTER", "PRINCE", "SNEEZE", "LEAGUE", "PADDLE",
            "SPRINT", "UMPIRE", "VOLLEY", "GADGET", "HACKER", "SIGNAL", "SENSOR", "SERVER", "COLLAR", "BUBBLE",
            "CHANCE", "CHOICE", "ENERGY", "FUTURE", "LEGEND", "RIDDLE",
            
            
            "COFFIN"
        ],
        7: [
            "ACCOUNT", "ADDRESS", "BEDROOM", "CLOTHES", "CONTACT", "DRESSES", "EVENING", "FASHION", "GLASSES", "HOLIDAY",
            "JANUARY", "KITCHEN", "MORNING", "OCTOBER", "QUALITY", "SERVICE", "STUDENT", "SUPPORT", "TEACHER", "TUESDAY",
            "AIRPORT", "BALANCE", "CAPTAIN", "CHICKEN", "COLLEGE", "COUNTRY", "DIAMOND", "DOLPHIN", "FACTORY", "FEATHER",
            "FREEDOM", "JOURNEY", "JUSTICE", "KINGDOM", "LUGGAGE", "MACHINE", "MONSTER", "MYSTERY", "NETWORK", "PACKAGE",
            "PAINTER", "PICTURE", "PYRAMID", "SCENERY", "SCIENCE", "SILENCE", "STATION", "SUNRISE", "TRAFFIC", "WEATHER",
            "WEBSITE", "WELCOME", "BLANKET", "CONCERT", "DESSERT", "HEROINE", "LANTERN",
            "CABINET", "GLACIER", "HARVEST",
            "APRICOT", "BALLOON", "BANDAGE", "BATTERY", "BICYCLE", "BISCUIT",
            "CABBAGE", "CAMPING", "CARAVAN", "CARTOON", "CHIMNEY", "COCONUT",
            "COMPASS", "COSTUME", "CRICKET", "CRYSTAL", "CUPCAKE", "CURTAIN",
            "DENTIST", "EMERALD", "FIREMAN", "FORTUNE", "GALLERY", "GIRAFFE",
            "GORILLA", "GRAVITY", "HAMSTER", "HORIZON", "ICEBERG", "JOURNAL",
            "KETCHUP", "LEOPARD", "LIBRARY", "LOBSTER", "MAILBOX", "MANSION",
            "MAMMOTH", "MERMAID", "MINERAL", "MUSTARD", "NOODLES", "OCTOPUS",
            "OSTRICH", "PANTHER", "PARKING", "PELICAN", "PENGUIN", "PLUMBER",
            "POPCORN", "PRESENT", "PUMPKIN", "RAINBOW", "RECEIPT", "SAUSAGE",
            "SHAMPOO", "SHELTER", "SHERIFF", "SPINACH", "STADIUM", "SURGEON",
            "THUNDER", "TOASTER", "TORNADO", "TRACTOR", "TRUMPET", "UNICORN",
            "UNIFORM", "VAMPIRE", "VOLCANO", "WARRIOR", "WHISTLE", "BALCONY",
            "SWEATER", "WEEKEND", "THEATRE",

            "CHEETAH", "WALLABY", "GAZELLE", "BUFFALO", "RACCOON", "MEERKAT", "WARTHOG", "MANATEE", "SPARROW", "PEACOCK",
            "ROOSTER", "SEAGULL", "SWALLOW", "VULTURE", "SARDINE", "NARWHAL", "FIREFLY", "TERMITE", "AVOCADO", "RAISINS",
            "LETTUCE", "PARSLEY", "LASAGNE", "BURRITO", "BIRYANI", "FALAFEL", "WAFFLES", "RISOTTO", "FAJITAS",
            "BROWNIE", "BAKLAVA", "CUSTARD", "CARAMEL", "MACARON", "PUDDING", "SAFFRON", "PAPRIKA", "VINEGAR", "VANILLA",
            "PICKLES", "LENTILS", "YOGHURT", "PADLOCK", "FREEZER", "DUSTPAN", "BLENDER", "BATHTUB", "TISSUES", "LIGHTER",
            "MATCHES", "KEYRING", "CUSHION", "DOORMAT", "HAMMOCK", "SPANNER", "TOOLBOX", "PICKAXE", "CROWBAR", "PYJAMAS",
            "SANDALS", "MITTENS", "HANDBAG", "STAPLER", "MONITOR", "PRINTER", "CHARGER", "SPEAKER", "MINIBUS", "SCOOTER",
            "FELUCCA", "COTTAGE", "VILLAGE", "CAPITAL", "NURSERY", "EMBASSY", "FUNFAIR", "OBELISK", "SOLDIER", "BUILDER",
            "BUTCHER", "DOORMAN", "CLEANER", "POSTMAN", "CASHIER", "REFEREE", "ACROBAT", "SURFING", "SAILING", "RUNNING",
            "JAVELIN", "FENCING", "ARCHERY", "CYCLING", "BOWLING", "SNOOKER", "HURDLES", "PARKOUR", "UKULELE", "MARACAS",
            "STOMACH", "TONSILS", "SNOWMAN", "THERMOS", "BEEHIVE", "PHARAOH", "LADYBUG", "PRETZEL", "PAJAMAS",
            "CRAYONS", "POSTBOX", "MESSAGE", "EARRING", "PLASTIC", "LEATHER", "ECLIPSE", "JASMINE", "PITCHER",
            "BARRIER", "INVOICE", "PHOENIX", "CEILING", "PANCAKE", "BLOSSOM", "ACADEMY", "HIGHWAY",
            "THEATER", "ADMIRAL", "ATHLETE", "EMPEROR", "JUGGLER", "VILLAIN", "GRANDMA", "GRANDPA", "PENALTY", "ANTENNA",
            "CIRCUIT", "FORMULA", "SCANNER", "SLIPPER", "PROMISE",
            
            
            
        ],
        8: [
            "COMPUTER", "DATABASE", "DECEMBER", "FEBRUARY", "HARDWARE", "HOSPITAL", "INTERNET", "KEYBOARD", "LANGUAGE", "MEDICINE",
            "NOVEMBER", "PASSWORD", "PHARMACY", "QUESTION", "SATURDAY", "SECURITY", "SOFTWARE", "SOLUTION", "THURSDAY", "USERNAME",
            "AIRPLANE", "BACKPACK", "BASEBALL", "BIRTHDAY", "BUILDING", "CALENDAR", "CHAMPION", "DINOSAUR", "ELEPHANT", "ELEVATOR",
            "FIREWORK", "FOOTBALL", "HEADLINE", "MOUNTAIN", "NOTEBOOK", "PAINTING", "PASSPORT", "PLATFORM", "PRINCESS", "SANDWICH",
            "SKELETON", "SQUIRREL", "SUITCASE", "SUNSHINE", "SYMPHONY", "VACATION", "UMBRELLA", "WILDLIFE", "WORKSHOP", "TREASURE",
            "AQUARIUM", "ASTEROID", "BACKYARD", "BATHROOM", "BLUEBIRD", "BOOKCASE",
            "BRACELET", "CARNIVAL", "CEREMONY", "CUCUMBER", "CUPBOARD", "DAUGHTER",
            "DOORBELL", "DUMPLING", "EGGPLANT", "ENVELOPE", "EXERCISE", "FESTIVAL",
            "FLAMINGO", "GARDENER", "GRANDSON", "HEADACHE", "HEDGEHOG", "HOMEWORK",
            "KANGAROO", "LAVENDER", "LEMONADE", "LIPSTICK", "LOLLIPOP", "MACARONI",
            "MAGAZINE", "MARATHON", "MIDNIGHT", "MOSQUITO", "MUSHROOM", "NECKLACE",
            "OMELETTE", "PANCAKES", "PLAYROOM", "PORRIDGE", "POSTCARD", "RAINCOAT",
            "REINDEER", "SCISSORS", "SEAHORSE", "SHOULDER", "SIDEWALK", "SLIPPERS",
            "SNOWBALL", "STARFISH", "SURPRISE", "TEASPOON", "TOMORROW", "TORTOISE",
            "UNIVERSE", "WOODLAND",

            "ANTELOPE", "CHIPMUNK", "ANTEATER", "MONGOOSE", "PLATYPUS", "COCKATOO", "STINGRAY", "GOLDFISH", "ANACONDA", "LADYBIRD",
            "SCORPION", "SILKWORM", "BROCCOLI", "BEETROOT", "SHAWARMA", "MOUSSAKA", "TIRAMISU", "ESPRESSO",
            "SMOOTHIE", "CINNAMON", "CARDAMOM", "TURMERIC", "ARMCHAIR", "MATTRESS", "BEDSHEET", "WARDROBE", "SAUCEPAN", "COLANDER",
            "BATHROBE", "CHAINSAW", "TROUSERS", "SWIMSUIT", "TRAINERS", "EARRINGS", "TEXTBOOK", "LUNCHBOX", "CAMPSITE", "PAVEMENT",
            "CEMETERY", "WINDMILL", "FOUNTAIN", "BASEMENT", "ENGINEER", "SHEPHERD", "MECHANIC", "COMPOSER", "MUSICIAN", "SCULPTOR",
            "INVENTOR", "MAGICIAN", "YOUTUBER", "DIPLOMAT", "MINISTER", "OPTICIAN", "JEWELLER", "HANDBALL", "SWIMMING", "SHOOTING",
            "AEROBICS", "SKIPPING", "CLARINET", "TROMBONE", "BAGPIPES", "TRIANGLE", "RECORDER", "CRESCENT", "FOREHEAD", "EYEBROWS",
            "APPENDIX", "DOUGHNUT", "SNEAKERS", "SEASHELL", "CHERRIES", "SAILBOAT", "DUMBBELL", "DOMINOES", "MEATBALL", "ZUCCHINI",
            "CURTAINS", "CARRIAGE", "TRICYCLE", "LIFEBOAT", "CAMPFIRE", "BALLOONS", "STRAINER", "CROSSBOW", "CONTRACT",
            "ELECTRIC",
            
            "REPORTER", "DIRECTOR", "POPSICLE"
        ]
    }
};

const WORDLE_LAYOUTS = {
    en: ['QWERTYUIOP', 'ASDFGHJKL', 'ZXCVBNM'],
    ar: ['ضصثقفغعهخحجد', 'شسيبلاتنمكط', 'ئءؤرذىةوزظ']
};
