/* solve: the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].<id>, as everywhere. */
gameText({
  translations: {
    ar: {
      sv_lobby_mode: "الطريقة",
      sv_mode_setter: "واحد يحط",
      sv_mode_race: "سباق",
      sv_mode_quiz: "مسابقة",
      sv_lobby_rounds: "كام مرة؟",
      sv_lobby_clock: "الوقت",
      sv_clock_hint: "لما الوقت يخلص، اللي ماحلّهاش يتحسب ماعرفش.",
      sv_lobby_hint: "المضيف بيختار الطريقة والعدد والوقت.",
      sv_emoji_lobby_hint: "المضيف بيختار: واحد يكتب الفزورة، أو سباق على فوازير التطبيق، أو المسابقة.",
      sv_setter_hint_wordle: "واحد يكتب كلمة والباقي يخمّنها في شبكته على موبايله. اللي بيكتب بيتغير كل مرة، وبياخد 5 عن كل واحد ماعرفهاش.",
      sv_setter_hint_guessnum: "واحد يختار رقم والباقي يخمّنوه بأعلى وأقل، كل واحد على موبايله. اللي بيختار بيتغير كل مرة، وبياخد 5 عن كل واحد ماعرفوش.",
      sv_setter_hint_flags: "واحد يختار دولة والباقي يخمّنوها، كل واحد على موبايله. اللي بيختار بيتغير كل مرة، وبياخد 5 عن كل واحد ماعرفهاش.",
      sv_setter_hint_emoji: "واحد يكتب فزورة بالإيموجي والباقي يخمّنوها، كل واحد على موبايله. اللي بيكتب بيتغير كل مرة، وبياخد 5 عن كل واحد ماعرفهاش.",
      sv_race_hint_wordle: "التطبيق بيدّي الكل نفس الكلمة، واللي يحلّها الأول ياخد أكتر.",
      sv_race_hint_guessnum: "التطبيق بيختار رقم للكل، واللي يوصله الأول ياخد أكتر.",
      sv_race_hint_flags: "التطبيق بيختار دولة للكل، واللي يعرفها الأول ياخد أكتر.",
      sv_race_hint_emoji: "فوازير التطبيق للكل، وكل واحد بيخمّن على موبايله من غير ما حد يشوف تخميناته. الأسرع ياخد أكتر.",
      sv_wordle_len: "كام حرف؟",
      sv_wordle_len_hint: "كلمات السباق من كلمات اللعبة.",
      sv_num_range: "المدى",
      sv_num_range_hint: "الرقم من 1 للآخر، وكل واحد عنده محاولات على قد المدى.",
      sv_you_set_wordle: "دورك تكتب كلمة، والباقي هيخمّنوها",
      sv_you_set_guessnum: "دورك تختار رقم، والباقي هيخمّنوه",
      sv_you_set_flags: "دورك تختار دولة، والباقي هيخمّنوها",
      sv_you_set_emoji: "دورك تكتب فزورة بالإيموجي",
      sv_setting_wordle: "مستنيين كلمة {name}…",
      sv_setting_guessnum: "مستنيين رقم {name}…",
      sv_setting_flags: "مستنيين دولة {name}…",
      sv_setting_emoji: "مستنيين فزورة {name}…",
      sv_race_title_wordle: "كلمة من التطبيق",
      sv_race_title_guessnum: "رقم من التطبيق",
      sv_race_title_flags: "دولة من التطبيق",
      sv_race_title_emoji: "فزورة من التطبيق",
      sv_secret_of: "من {name}",
      sv_the_answer: "الإجابة",
      sv_your_secret: "اللي حطيته",
      sv_you_watch: "اتفرج مين هيحلّها.",
      sv_watching: "انت بتتفرج المرة دي",
      sv_you_won: "🎉 عرفتها!",
      sv_you_lost: "💀 خلصت محاولاتك",
      sv_state_won: "عرفها",
      sv_state_lost: "💀 ماعرفش",
      sv_tries: "{n} من {m}",
      sv_tries_short: "{n} محاولة",
      sv_setter_pts: "{name} (اللي حطها)",
      sv_skip_setter: "اللي بعده يحط",
      sv_show_secret: "ورّيني",
      sv_pick_random: "اختار لي",
      sv_guess_btn: "خمّن",
      sv_enter_key: "تحقق",
      sv_back_key: "امسح",
      sv_wordle_ph: "الكلمة",
      sv_wordle_set_hint: "كلمة من 5 لـ 8 حروف، حروف بس. الحروف مستخبية وانت بتكتب.",
      sv_wordle_bad_len: "الكلمة من 5 لـ 8 حروف.",
      sv_wordle_bad_letters: "حروف لغة واحدة بس، من غير أرقام ولا مسافات.",
      sv_wordle_short: "الكلمة {n} حروف",
      sv_send_word: "ابعت الكلمة",
      sv_num_set_range: "اختار رقم من 1 لـ {max}.",
      sv_num_ph: "الرقم",
      sv_num_bad: "رقم من 1 لـ {max}.",
      sv_send_number: "ابعت الرقم",
      sv_num_between: "الرقم بين",
      sv_num_start: "ابدأ خمّن!",
      sv_num_higher: "أعلى! ⬆️",
      sv_num_lower: "أقل! ⬇️",
      sv_num_right: "🎉 صح! الرقم {n}",
      sv_send_country: "ابعت الدولة",
      sv_emoji_kind: "نوعها",
      sv_ek_film: "فيلم",
      sv_ek_proverb: "مثل",
      sv_ek_dish: "أكلة",
      sv_ek_place: "مكان",
      sv_ek_thing: "حاجة",
      sv_emoji_answer_ph: "الإجابة",
      sv_emoji_clue_ph: "الفزورة بالإيموجي 🐘🔵",
      sv_emoji_set_hint: "الإجابة مستخبية وانت بتكتب. الفزورة إيموجي بس، من غير حروف.",
      sv_emoji_no_answer: "اكتب الإجابة.",
      sv_emoji_long: "الإجابة لحد 8 كلمات.",
      sv_emoji_no_clue: "اكتب الفزورة بالإيموجي.",
      sv_emoji_clue_long: "الفزورة طويلة، خليها أقصر.",
      sv_emoji_letters: "الفزورة إيموجي بس، من غير حروف ولا أرقام.",
      sv_emoji_spells: "الإيموجي بيتهجّى الإجابة، غيّرها.",
      sv_send_riddle: "ابعت الفزورة",
      flags_type: "اكتب اسم دولة…",
    },
    en: {
      sv_lobby_mode: "How",
      sv_mode_setter: "One sets",
      sv_mode_race: "Race",
      sv_mode_quiz: "Quiz",
      sv_lobby_rounds: "How many?",
      sv_lobby_clock: "Time",
      sv_clock_hint: "When time runs out, whoever hasn't got it hasn't.",
      sv_lobby_hint: "The host picks the way, how many and the time.",
      sv_emoji_lobby_hint: "The host picks: a player writes the riddle, a race on the app's riddles, or the quiz.",
      sv_setter_hint_wordle: "One writes a word and the others guess it in their own grid on their own phone. The writer changes each time and scores 5 for everyone who misses it.",
      sv_setter_hint_guessnum: "One picks a number and the others find it with higher and lower, each on their own phone. The picker changes each time and scores 5 for everyone who misses it.",
      sv_setter_hint_flags: "One picks a country and the others guess it, each on their own phone. The picker changes each time and scores 5 for everyone who misses it.",
      sv_setter_hint_emoji: "One writes an emoji riddle and the others guess it, each on their own phone. The writer changes each time and scores 5 for everyone who misses it.",
      sv_race_hint_wordle: "The app gives everyone the same word; the first to solve it scores most.",
      sv_race_hint_guessnum: "The app picks a number for everyone; the first to find it scores most.",
      sv_race_hint_flags: "The app picks a country for everyone; the first to find it scores most.",
      sv_race_hint_emoji: "The app's riddles for everyone, each guessing on their own phone where nobody sees their tries. The fastest scores most.",
      sv_wordle_len: "How many letters?",
      sv_wordle_len_hint: "The race's words come from the game's own lists.",
      sv_num_range: "Range",
      sv_num_range_hint: "From 1 up, and as many tries as the range needs.",
      sv_you_set_wordle: "Your turn to write a word for the others",
      sv_you_set_guessnum: "Your turn to pick a number for the others",
      sv_you_set_flags: "Your turn to pick a country for the others",
      sv_you_set_emoji: "Your turn to write an emoji riddle",
      sv_setting_wordle: "Waiting for {name}'s word…",
      sv_setting_guessnum: "Waiting for {name}'s number…",
      sv_setting_flags: "Waiting for {name}'s country…",
      sv_setting_emoji: "Waiting for {name}'s riddle…",
      sv_race_title_wordle: "The app's word",
      sv_race_title_guessnum: "The app's number",
      sv_race_title_flags: "The app's country",
      sv_race_title_emoji: "The app's riddle",
      sv_secret_of: "From {name}",
      sv_the_answer: "The answer",
      sv_your_secret: "What you set",
      sv_you_watch: "Watch who gets it.",
      sv_watching: "You're watching this one",
      sv_you_won: "🎉 Got it!",
      sv_you_lost: "💀 Out of tries",
      sv_state_won: "Got it",
      sv_state_lost: "💀 Missed",
      sv_tries: "{n} of {m}",
      sv_tries_short: "{n} tries",
      sv_setter_pts: "{name} (set it)",
      sv_skip_setter: "Next one sets",
      sv_show_secret: "Show it",
      sv_pick_random: "Pick for me",
      sv_guess_btn: "Guess",
      sv_enter_key: "Enter",
      sv_back_key: "Delete",
      sv_wordle_ph: "The word",
      sv_wordle_set_hint: "A word of 5 to 8 letters, letters only. It's hidden as you type.",
      sv_wordle_bad_len: "A word of 5 to 8 letters.",
      sv_wordle_bad_letters: "One alphabet only, no digits or spaces.",
      sv_wordle_short: "The word has {n} letters",
      sv_send_word: "Send the word",
      sv_num_set_range: "Pick a number from 1 to {max}.",
      sv_num_ph: "The number",
      sv_num_bad: "A number from 1 to {max}.",
      sv_send_number: "Send the number",
      sv_num_between: "It's between",
      sv_num_start: "Start guessing!",
      sv_num_higher: "Higher! ⬆️",
      sv_num_lower: "Lower! ⬇️",
      sv_num_right: "🎉 Right! It's {n}",
      sv_send_country: "Send the country",
      sv_emoji_kind: "What it is",
      sv_ek_film: "Film",
      sv_ek_proverb: "Saying",
      sv_ek_dish: "Dish",
      sv_ek_place: "Place",
      sv_ek_thing: "Thing",
      sv_emoji_answer_ph: "The answer",
      sv_emoji_clue_ph: "The riddle in emoji 🐘🔵",
      sv_emoji_set_hint: "The answer is hidden as you type. The riddle is emoji only, no letters.",
      sv_emoji_no_answer: "Write the answer.",
      sv_emoji_long: "An answer of up to 8 words.",
      sv_emoji_no_clue: "Write the riddle in emoji.",
      sv_emoji_clue_long: "The riddle is too long.",
      sv_emoji_letters: "Emoji only, no letters or digits.",
      sv_emoji_spells: "The emoji spell the answer out; change them.",
      sv_send_riddle: "Send the riddle",
      flags_type: "Type a country…",
    }
  }
});
