/* mission: the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].<id>, as everywhere. */
gameText({
  translations: {
    ar: {
      mission_door_on: "شغّالة جنب كل لعبة لحد ما تقفلها",
      mission_place: "المكان",
      mission_company: "الصحبة",
      mission_place_home: "البيت",
      mission_place_cafe: "كافيه",
      mission_place_out: "بره",
      mission_place_any: "أي حتة",
      mission_place_home_long: "في البيت",
      mission_place_cafe_long: "في كافيه أو مطعم",
      mission_place_out_long: "بره (رحلة، عربية، بحر)",
      mission_place_any_long: "في أي حتة (كلام بس)",
      mission_co_family: "العيلة",
      mission_co_family_sub: "هادية - تنفع قدّام تيتة",
      mission_co_friends: "الصحاب",
      mission_co_friends_sub: "مقالب أجرأ - برضه نضيفة",
      mission_examples: "من الملف ({n} مهمة تنفع للمكان والصحبة دول)",
      mission_opt_swap: "«غيّرها» مرة كل ١٠ دقايق",
      mission_opt_catch: "«كشفتك!» نقطة لو صح، ونقطة للمتّهم لو غلط",
      mission_start: "شغّلها 🕵️",
      mission_save: "احفظ",
      mission_turn_off: "اقفلها وشوف مين عمل في مين إيه",
      mission_turn_off_q: "نقفل المهمة السرية؟ القصة كلها هتظهر، وأشطر عميل سري.",
      mission_paused: "المهمة السرية واقفة لحد ما تبقوا ٣ على الأقل",
      mission_open_file: "افتح ملفك 📁",
      mission_settings: "الإعداد",
      mission_files_closed: "ملفات اتقفلت الليلة: {n}",
      mission_order: "أمر تكليف",
      mission_agent: "العميل: {name} · ملف {n}",
      mission_file_no: "ملف {n}",
      mission_target: "الهدف",
      mission_mission: "المهمة",
      mission_nobody_knows: "محدش يعرف غيرك",
      mission_hq: "القيادة ✍️",
      mission_done_stamp: "تمّت ✔",
      mission_waiting: "مستنيين {name} يوقّع…",
      mission_take_back: "اسحبه ↩",
      mission_secret: "سري للغاية",
      mission_to_agent: "إلى: العميل {name}",
      mission_hold: "دوس وامسك عشان تفتح - وسيبه يتقفل",
      mission_done_btn: "خلصت ✔",
      mission_swap_btn: "غيّرها ↻",
      mission_swap_wait: "بعد {t}",
      mission_catch_q: "شاكك إن حد بيشتغل عليك؟",
      mission_catch_btn: "كشفتك!",
      mission_catch_pick: "مين؟",
      mission_catch_confirm: "كشفتك يا {name}!",
      mission_catch_wait_no: "لأ، استنى",
      mission_catch_wait: "تقدر تكشف حد تاني بعد {t}",
      mission_state_ready: "امسك الملف عشان تقراه - ولما تخلّص المهمة دوس «خلصت»",
      mission_state_wait: "الملف راح للهدف يوقّع عليه…",
      mission_toast_won: "+١ 🎯 {name} أكّد! ملف جديد على مكتبك 📁",
      mission_toast_no: "{name} قال لأ - الملف لسه مفتوح، كمّل 😏",
      mission_toast_swapped: "اتغيّرت - ملف تاني على المكتب",
      mission_toast_caught_ok: "كشفتك! صح - {name} كان بيشتغل عليك · +١ ليك 👀",
      mission_toast_caught_no: "لأ… {name} بريء 😅 · +١ ليه",
      mission_toast_gift: "حد قالك «كشفتك!» غلط · +١ ليك 🎁",
      mission_ticker_gift: "حد اتّهم {b} غلط · +١ لـ{b} 🎁",
      mission_story_wrong: "{a} قال لـ{b} «كشفتك!» غلط · +١ لـ{b}",
      mission_he_she: "هو ⇄ هي",
      mission_he_she_aria: "غيّر كلام المهمة لولد أو لبنت",
      mission_form_flipped: "اتغيّر كلام المهمة - امسك الملف وشوفه",
      mission_toast_busted: "اتكشفت! {name} عرف إنك بتشتغل عليه · ملف جديد 🙈",
      mission_knock: "📁 ملف محتاج توقيعك - بص لوحدك",
      mission_memo: "مذكّرة · ليك انت بس",
      mission_secret_short: "سري",
      mission_ask_who: "ملف {name} كان مكتوب فيه:",
      mission_running: "كل واحد معاه ملف سري",
      mission_ask_q: "حصل معاك فعلًا؟",
      mission_yes: "نعم ✔",
      mission_no: "لأ ✘",
      mission_ticker_tab: "ملف اتقفل 📁",
      mission_ticker_done: "مهمة اتعملت!",
      mission_ticker_catch: "{a} كشف {b}! 🕵️",
      mission_board_title: "مهمات الليلة · مين قفل ملفات أكتر",
      mission_reveal_title: "مين عمل في مين إيه",
      mission_champ: "أشطر عميل سري",
      mission_champ_stamp: "بطل الليلة",
      mission_champ_line: "{n} ملفات اتقفلت",
      mission_champ_line_one: "ملف واحد اتقفل",
      mission_champ_never: "ولا مرة اتكشف",
      mission_no_champ: "محدش قفل ملف الليلة… السهرة الجاية!",
      mission_open_left: "{a} كان لسه بيحاول: {text}",
      mission_read_story: "اقرا القصة",
      mission_close_file: "قفل الملف",
      mission_ended: "الملف اتقفل",
      mission_reveal_wait: "المضيف يقفل الملف لما الكل يقرا",
      mission_help: "إزاي بتتلعب؟",
    },
    en: {
      mission_door_on: "On beside every game until you turn it off",
      mission_place: "The place",
      mission_company: "The company",
      mission_place_home: "Home",
      mission_place_cafe: "Café",
      mission_place_out: "Out",
      mission_place_any: "Anywhere",
      mission_place_home_long: "At home",
      mission_place_cafe_long: "At a café or a restaurant",
      mission_place_out_long: "Out (a trip, the car, the beach)",
      mission_place_any_long: "Anywhere (talking only)",
      mission_co_family: "Family",
      mission_co_family_sub: "Gentle - fine in front of grandma",
      mission_co_friends: "Friends",
      mission_co_friends_sub: "Cheekier pranks - still clean",
      mission_examples: "From the file ({n} missions fit this place and company)",
      mission_opt_swap: "«Change it» once every 10 minutes",
      mission_opt_catch: "«Caught you!» a point if right, a point to the accused if wrong",
      mission_start: "Turn it on 🕵️",
      mission_save: "Save",
      mission_turn_off: "Turn it off and see who did what to whom",
      mission_turn_off_q: "End the secret mission? The whole story comes out, and the best secret agent.",
      mission_paused: "The secret mission waits until there are at least 3 of you",
      mission_open_file: "Open your file 📁",
      mission_settings: "Settings",
      mission_files_closed: "Files closed tonight: {n}",
      mission_order: "Assignment",
      mission_agent: "Agent: {name} · file {n}",
      mission_file_no: "File {n}",
      mission_target: "The target",
      mission_mission: "The mission",
      mission_nobody_knows: "Nobody knows but you",
      mission_hq: "HQ ✍️",
      mission_done_stamp: "Done ✔",
      mission_waiting: "Waiting for {name} to sign…",
      mission_take_back: "Take it back ↩",
      mission_secret: "Top secret",
      mission_to_agent: "To: agent {name}",
      mission_hold: "Press and hold to open - let go to close",
      mission_done_btn: "Done ✔",
      mission_swap_btn: "Change it ↻",
      mission_swap_wait: "in {t}",
      mission_catch_q: "Think someone is working on you?",
      mission_catch_btn: "Caught you!",
      mission_catch_pick: "Who?",
      mission_catch_confirm: "Caught you, {name}!",
      mission_catch_wait_no: "No, wait",
      mission_catch_wait: "You can guess again in {t}",
      mission_state_ready: "Hold the file to read it - once it is done, press «Done»",
      mission_state_wait: "The file has gone to the target to sign…",
      mission_toast_won: "+1 🎯 {name} confirmed! A new file on your desk 📁",
      mission_toast_no: "{name} said no - the file is still open, keep at it 😏",
      mission_toast_swapped: "Changed - another file on the desk",
      mission_toast_caught_ok: "Caught! Right - {name} was working on you · +1 to you 👀",
      mission_toast_caught_no: "No… {name} is innocent 😅 · +1 to them",
      mission_toast_gift: "Someone wrongly said «Caught you!» to you · +1 for you 🎁",
      mission_ticker_gift: "{b} was wrongly accused · +1 to {b} 🎁",
      mission_story_wrong: "{a} wrongly told {b} «Caught you!» · +1 to {b}",
      mission_he_she: "he ⇄ she",
      mission_he_she_aria: "Switch the mission's Arabic wording to a boy or a girl",
      mission_form_flipped: "The mission's wording changed - hold the file to see it",
      mission_toast_busted: "Busted! {name} rumbled you · a new file 🙈",
      mission_knock: "📁 A file needs your signature - look on your own",
      mission_memo: "A memo · for you only",
      mission_secret_short: "Secret",
      mission_ask_who: "{name}'s file said:",
      mission_running: "Everyone has a secret file",
      mission_ask_q: "Did it really happen?",
      mission_yes: "Yes ✔",
      mission_no: "No ✘",
      mission_ticker_tab: "File closed 📁",
      mission_ticker_done: "Mission done!",
      mission_ticker_catch: "{a} rumbled {b}! 🕵️",
      mission_board_title: "Tonight's missions · who closed the most files",
      mission_reveal_title: "Who did what to whom",
      mission_champ: "The best secret agent",
      mission_champ_stamp: "Champion",
      mission_champ_line: "{n} files closed",
      mission_champ_line_one: "1 file closed",
      mission_champ_never: "never rumbled",
      mission_no_champ: "Nobody closed a file tonight… next time!",
      mission_open_left: "{a} was still trying: {text}",
      mission_read_story: "Read the story",
      mission_close_file: "Close the file",
      mission_ended: "The file is closed",
      mission_reveal_wait: "The host closes the file once everyone has read it",
      mission_help: "How does it work?",
    }
  },
  rules: {
    ar: {
      mission: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>مش لعبة من القايمة: <b>زرار في الغرفة</b>. المضيف يشغّل <b>🕵️ المهمة السرية</b> من الغرفة، يختار <b>المكان</b> (البيت، كافيه أو مطعم، بره، أي حتة) و<b>الصحبة</b> (العيلة أو الصحاب)، وتفضل شغّالة جنب كل لعبة لحد ما يقفلها.</li>
                <li>كل واحد معاه في السر <b>هدف</b> (حد تاني في الغرفة) و<b>مهمة</b>: «خلّي منى تقول كلمة بجد». الملف 📁 فوق في أي شاشة؛ <b>دوس وامسك</b> عشان تقراه، ولما تسيبه يتقفل.</li>
                <li>عملتها؟ دوس <b>«خلصت»</b>. موبايل الهدف يسأله في هدوء: «حصل معاك فعلًا؟». <b>نعم</b>: نقطة ليك وملف جديد بهدف جديد. <b>لأ</b>: ولا حاجة، كمّل في نفس المهمة. محدش بيخرج أبدًا.</li>
                <li>ساعات المهمة تبقى <b>«قول الكلمة»</b>: «خلّي منى تقول كلمة «زرافة»». كلمة من كلمات الرسم، تنفع في أي مكان ومع أي صحبة.</li>
                <li><b>«غيّرها»</b>: مهمة تانية لنفس الهدف، مرة كل ١٠ دقايق.</li>
                <li><b>«كشفتك!»</b>: لو شاكك إن حد بيشتغل عليك، اختار وشّه وأكّد بختم «كشفتك يا …!» («لأ، استنى» يرجّعك). صح: نقطة ليك وهو ياخد ملف جديد. غلط: اللي اتّهمته ياخد نقطة، وتستنى ٥ دقايق قبل ما تكشف حد تاني. اللي سألك «حصل؟» كشف نفسه بنفسه، مينفعش تكشفه، وتتحسب عليك غلط.</li>
                <li>اللي ييجي متأخر بياخد ملف على طول، واللي يمشي ملفه بيتقفل ومين كان بيشتغل عليه ياخد هدف جديد. أقل من ٣: المهمة تستنى.</li>
                <li>الشاشة عمرها ما بتعرض مهمة قبل ما تتعمل: بتعرض «ملف اتقفل!» لما مهمة تخلص، ولوحة فلّين بمين قفل ملفات أكتر.</li>
                <li>لما المضيف يقفلها: <b>مين عمل في مين إيه</b> صور وخيوط حمرا، و<b>أشطر عميل سري</b>، والترتيب بيتحسب في نقط الليلة مرة واحدة: ٥، ٣، ٢، و١ لأي حد لعب.</li>
            </ol>`,
    },
    en: {
      mission: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>Not a game from the list: <b>a switch on the room</b>. The host turns on <b>🕵️ The secret mission</b> in the room, picks the <b>place</b> (home, a café or restaurant, out, anywhere) and the <b>company</b> (family or friends), and it runs beside every game until the host turns it off.</li>
                <li>Everyone secretly has a <b>target</b> (someone else in the room) and a <b>mission</b>: "Get Mona to say seriously". The 📁 at the top of any screen opens your file; <b>press and hold</b> to read it, let go and it closes.</li>
                <li>Done it? Press <b>«Done»</b>. The target's phone quietly asks: "Did it really happen?". <b>Yes</b>: a point for you and a new file with a new target. <b>No</b>: nothing happens, keep at the same mission. Nobody is ever out.</li>
                <li>Sometimes the mission is <b>«Say the word»</b>: "Get Mona to say the word giraffe". A word from the drawing words, good for any place and any company.</li>
                <li><b>«Change it»</b>: another mission for the same target, once every 10 minutes.</li>
                <li><b>«Caught you!»</b>: if you think someone is working on you, tap their face and confirm with the «Caught you, …!» stamp («No, wait» takes it back). Right: a point for you and they get a new file. Wrong: the one you named gets a point, and you wait 5 minutes before guessing again. Someone who asked you "did it happen?" gave themselves away - that one can't be caught, and it counts as a wrong guess.</li>
                <li>Someone who comes late gets a file at once; someone who leaves drops out and whoever was working on them gets a new target. Fewer than 3: it waits.</li>
                <li>The big screen never shows a mission before it is done: it shows «File closed!» when one is, and a cork board of who closed the most files.</li>
                <li>When the host turns it off: <b>who did what to whom</b> as photos and red strings, <b>the best secret agent</b>, and the ranking counts on the night's board once: 5, 3, 2, and 1 for everyone else who played.</li>
            </ol>`,
    }
  }
});
