/* exact: the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].<id>, as everywhere. */
gameText({
  translations: {
    ar: {
      ex_lobby_hint: "كل مستوى أمر واحد للترابيزة كلها (بالظبط ٣ منكم يحطوا إيدهم، محدش يحط إيده، بالدور…). اقروه، وبعد العدّ نفّذوه من موبايلاتكم. غلطة واحدة وكوباية شاي بتتدلق، وعندكم ٣!",
      ex_level: "المستوى {n}",
      ex_best: "أحسن رقم: {n}",
      ex_lives: "{n} كوبايات شاي",
      ex_new: "أمر جديد!",
      ex_order: "الأمر",
      ex_now: "دلوقتي!",
      ex_arrow: "←",
      ex_wait_pad: "استنى الأمر…",
      ex_pad_lab: "حط إيدك",
      ex_pad_done: "خلص الوقت",
      ex_watching: "إنت بتتفرج دلوقتي… اللعبة الجاية معانا",
      ex_o_count: "بالظبط {n} منكم يحطوا إيدهم!",
      ex_o_count1: "واحد بس يحط إيده!",
      ex_o_none: "محدش يحط إيده!",
      ex_o_all: "كل الإيدين مع بعض… دلوقتي!",
      ex_o_taps: "كل واحد يخبط {n} خبطات بالظبط",
      ex_o_total: "الترابيزة كلها: {n} خبطة بالظبط",
      ex_o_hold: "بالظبط {n} يفضلوا حاطين إيدهم لحد الجرس",
      ex_o_seq: "بالدور!",
      ex_o_pulse: "النبضة بتلف على الترابيزة",
      ex_o_pick: "بس {group} يحطوا إيدهم",
      ex_o_pickcount: "بالظبط {n} من {group}",
      ex_o_mirror: "اعكسوا شاشاتكم!",
      ex_o_sum: "أرقامكم تجمع {n} بالظبط",
      ex_o_letgo: "حطوا إيديكم… وشيلوها على العداد",
      ex_o_release: "كله يحط إيده… وشيلوا واحد ورا التاني",
      ex_s_count: "واحد زيادة؟ ياخد تلطيشة 😂",
      ex_s_none: "ولا إيد… مهما حصل",
      ex_s_all: "في نفس اللحظة بالظبط",
      ex_s_taps: "مش أكتر ولا أقل",
      ex_s_total: "عدّوا مع بعض بصوت عالي",
      ex_s_hold: "والباقي يشيلوا إيدهم قبل الجرس",
      ex_s_pulse: "دوس لما توصلك، مش قبلها",
      ex_s_pick: "بص على شاشتك الأول",
      ex_s_pickcount: "والباقي ولا إيد",
      ex_s_mirror: "مكتوب «دوس»؟ متدوسش. مكتوب «متدوسش»؟ دوس!",
      ex_s_sum: "اتكلموا! كل إيد بتنزل برقمها",
      ex_s_letgo: "كل واحد يشيل إيده على رقمه",
      ex_s_release: "ولا إيدين يتشالوا مع بعض",
      ex_grp_c_g: "اللي شاشتهم خضرا",
      ex_grp_c_r: "اللي شاشتهم حمرا",
      ex_grp_sh_star: "اللي عندهم نجمة",
      ex_grp_sh_circle: "اللي عندهم دايرة",
      ex_grp_sh_triangle: "اللي عندهم مثلث",
      ex_grp_sh_square: "اللي عندهم مربع",
      ex_grp_odd: "اللي رقمهم فردي",
      ex_grp_even: "اللي رقمهم زوجي",
      ex_col_g: "خضرا",
      ex_col_r: "حمرا",
      ex_shape_star: "نجمة",
      ex_shape_circle: "دايرة",
      ex_shape_triangle: "مثلث",
      ex_shape_square: "مربع",
      ex_say_press: "دوس!",
      ex_say_stop: "متدوسش!",
      ex_my_lift: "رقمك",
      ex_pulse_you: "لسه {n} قبلك",
      ex_pulse_now: "دورك… دوس!",
      ex_put_down: "حطوا إيديكم!",
      ex_lift_on: "شيل إيدك على {n}",
      ex_lift_now: "شيل!",
      ex_release_now: "شيلوا واحد واحد",
      ex_bell: "🔔 الجرس!",
      ex_total_now: "{n} خبطة",
      ex_v_ok: "مظبوط!",
      ex_v_extra: "إيد زيادة!",
      ex_v_extra_n: "{n} إيدين زيادة!",
      ex_v_short: "ناقصة إيد!",
      ex_v_short_n: "ناقص {n} إيدين!",
      ex_v_stung: "قرصتكم النحلة!",
      ex_v_sync: "مش مع بعض!",
      ex_v_taps: "العدّ فلت!",
      ex_v_total: "{got} خبطة والمطلوب {want}",
      ex_v_order: "الدور اتلخبط!",
      ex_v_pulse: "النبضة فلتت!",
      ex_v_pick: "الشاشات اتلخبطت!",
      ex_v_sum: "المجموع {got} والمطلوب {want}",
      ex_v_letgo: "العداد فلت!",
      ex_v_release: "إيدين اتشالوا مع بعض!",
      ex_v_bad: "لأ!",
      ex_cap_extra: "إيد {name} زيادة… خدت تلطيشة وانسحبت 😂",
      ex_cap_missing: "إيد {name} ما نزلتش 🤷",
      ex_cap_wrong: "إيد {name} نزلت ومكانش دورها 😅",
      ex_cap_stung: "إيد {name} نزلت… والنحلة قرصتها 🐝😂",
      ex_cap_early: "إيد {name} سبقت 🏃",
      ex_cap_late: "إيد {name} اتأخرت 🐢",
      ex_cap_taps: "إيد {name} خبطت {n} مش {k}",
      ex_cap_together: "إيد {name} اتشالت مع غيرها 👯",
      ex_cap_order: "إيد {name} نزلت قبل دورها",
      ex_cap_short: "ناقص {n}… حد كان لازم ينزل إيده",
      ex_cap_short_sum: "ناقص {n} في المجموع",
      ex_cap_more: "و{n} كمان",
      ex_cap_ok: "نزل {food} على الترابيزة 😋",
      ex_cap_refill: "وكوباية شاي جديدة ☕",
      ex_b_ouch: "آه 😂",
      ex_b_ai: "آي!",
      ex_b_where: "كنت فين؟",
      ex_b_notyou: "مش إنت!",
      ex_b_early: "بدري!",
      ex_b_late: "اتأخرت!",
      ex_b_taps: "{n} مش {k}",
      ex_b_together: "مع بعض!",
      ex_b_order: "مش دورك!",
      ex_b_slap: "طخ!",
      ex_me_ok: "إيدك كانت تمام 👌",
      ex_me_fine: "إيدك كانت تمام… الغلطة من غيرك",
      ex_me_extra: "إيدك كانت الزيادة… خدت تلطيشة 😂",
      ex_me_missing: "إيدك ما نزلتش!",
      ex_me_wrong: "إيدك نزلت ومكانش دورها 😅",
      ex_me_stung: "النحلة قرصتك 🐝",
      ex_me_early: "سبقت شوية 🏃",
      ex_me_late: "اتأخرت شوية 🐢",
      ex_me_taps: "خبطت {n} مش {k}",
      ex_me_together: "شلت إيدك مع حد تاني 👯",
      ex_me_order: "نزلت قبل دورك",
      ex_food_0: "العيش",
      ex_food_1: "الفول",
      ex_food_2: "الطعمية",
      ex_food_3: "المخلل",
      ex_food_4: "البطيخ",
      ex_food_5: "الكحك",
      ex_food_6: "البلح",
      ex_food_7: "الكنافة",
      ex_next_in: "الأمر الجاي بعد {n}…",
      ex_next_level: "على المستوى {lvl} بعد {n}…",
      ex_next_now: "الأمر الجاي",
      ex_over: "الشاي خلص!",
      ex_over_title: "الترابيزة",
      ex_reached: "وصلتوا المستوى {n}",
      ex_cleared_lab: "أمر مظبوط",
      ex_best_now: "أحسن رقم للأوضة: {n}",
      ex_record: "رقم جديد للأوضة! 🏆",
      ex_clean: "أثبت إيد",
      ex_ring_won: "💍 إيد دهب!",
      ex_play_again: "العبوا تاني",
    },
    en: {
      ex_lobby_hint: "Each level is one order for the whole table (exactly 3 of you, nobody, in turn…). Read it, then do it on your phones after the countdown. One mistake spills a glass of tea, and you have 3!",
      ex_level: "Level {n}",
      ex_best: "Best: {n}",
      ex_lives: "{n} glasses of tea",
      ex_new: "New order!",
      ex_order: "The order",
      ex_now: "Now!",
      ex_arrow: "→",
      ex_wait_pad: "Wait for it…",
      ex_pad_lab: "Hand down",
      ex_pad_done: "Time's up",
      ex_watching: "You're watching - you're in next game",
      ex_o_count: "Exactly {n} of you: hands down!",
      ex_o_count1: "Just one hand down!",
      ex_o_none: "Nobody put a hand down!",
      ex_o_all: "All hands together… now!",
      ex_o_taps: "Everyone taps exactly {n} times",
      ex_o_total: "The whole table: exactly {n} taps",
      ex_o_hold: "Exactly {n} hands still down at the bell",
      ex_o_seq: "In turn!",
      ex_o_pulse: "The pulse goes round the table",
      ex_o_pick: "Only {group}: hands down",
      ex_o_pickcount: "Exactly {n} of {group}",
      ex_o_mirror: "Do the opposite of your screen!",
      ex_o_sum: "Your numbers add up to exactly {n}",
      ex_o_letgo: "Hands down… and lift on the counter",
      ex_o_release: "Everyone down… then lift one by one",
      ex_s_count: "One more? That hand gets a slap 😂",
      ex_s_none: "Not one hand - whatever happens",
      ex_s_all: "At exactly the same moment",
      ex_s_taps: "Not one more, not one less",
      ex_s_total: "Count out loud together",
      ex_s_hold: "Everyone else lifts before the bell",
      ex_s_pulse: "Press when it reaches you, not before",
      ex_s_pick: "Look at your screen first",
      ex_s_pickcount: "And no other hand",
      ex_s_mirror: "It says Press? Don't. It says Don't? Press!",
      ex_s_sum: "Talk! Each hand counts its number",
      ex_s_letgo: "Lift your hand on your own number",
      ex_s_release: "No two hands up at once",
      ex_grp_c_g: "the green screens",
      ex_grp_c_r: "the red screens",
      ex_grp_sh_star: "the stars",
      ex_grp_sh_circle: "the circles",
      ex_grp_sh_triangle: "the triangles",
      ex_grp_sh_square: "the squares",
      ex_grp_odd: "the odd numbers",
      ex_grp_even: "the even numbers",
      ex_col_g: "Green",
      ex_col_r: "Red",
      ex_shape_star: "Star",
      ex_shape_circle: "Circle",
      ex_shape_triangle: "Triangle",
      ex_shape_square: "Square",
      ex_say_press: "Press!",
      ex_say_stop: "Don't!",
      ex_my_lift: "your number",
      ex_pulse_you: "{n} before you",
      ex_pulse_now: "Your beat… press!",
      ex_put_down: "Hands down!",
      ex_lift_on: "Lift on {n}",
      ex_lift_now: "Lift!",
      ex_release_now: "Lift one by one",
      ex_bell: "🔔 The bell!",
      ex_total_now: "{n} taps",
      ex_v_ok: "Exact!",
      ex_v_extra: "One hand too many!",
      ex_v_extra_n: "{n} hands too many!",
      ex_v_short: "One hand short!",
      ex_v_short_n: "{n} hands short!",
      ex_v_stung: "The bee got you!",
      ex_v_sync: "Not together!",
      ex_v_taps: "The count slipped!",
      ex_v_total: "{got} taps, {want} wanted",
      ex_v_order: "Out of turn!",
      ex_v_pulse: "The pulse slipped!",
      ex_v_pick: "The screens got mixed up!",
      ex_v_sum: "It came to {got}, not {want}",
      ex_v_letgo: "The counter slipped!",
      ex_v_release: "Two hands lifted at once!",
      ex_v_bad: "No!",
      ex_cap_extra: "{name}'s hand was one too many… slapped away 😂",
      ex_cap_missing: "{name}'s hand never came down 🤷",
      ex_cap_wrong: "{name}'s hand came down when it shouldn't 😅",
      ex_cap_stung: "{name}'s hand came down… and the bee stung it 🐝😂",
      ex_cap_early: "{name}'s hand jumped the gun 🏃",
      ex_cap_late: "{name}'s hand was late 🐢",
      ex_cap_taps: "{name}'s hand tapped {n}, not {k}",
      ex_cap_together: "{name}'s hand lifted with another 👯",
      ex_cap_order: "{name}'s hand came down before its turn",
      ex_cap_short: "{n} short… someone had to put a hand down",
      ex_cap_short_sum: "{n} short of the sum",
      ex_cap_more: "and {n} more",
      ex_cap_ok: "{food} hits the table 😋",
      ex_cap_refill: "and a fresh glass of tea ☕",
      ex_b_ouch: "Ow 😂",
      ex_b_ai: "Ouch!",
      ex_b_where: "Where were you?",
      ex_b_notyou: "Not you!",
      ex_b_early: "Too soon!",
      ex_b_late: "Too late!",
      ex_b_taps: "{n}, not {k}",
      ex_b_together: "Together!",
      ex_b_order: "Not your turn!",
      ex_b_slap: "Slap!",
      ex_me_ok: "Your hand got it right 👌",
      ex_me_fine: "Your hand was fine… someone else slipped",
      ex_me_extra: "Yours was the extra hand… slapped 😂",
      ex_me_missing: "Your hand never came down!",
      ex_me_wrong: "Your hand came down when it shouldn't 😅",
      ex_me_stung: "The bee stung you 🐝",
      ex_me_early: "A little too soon 🏃",
      ex_me_late: "A little too late 🐢",
      ex_me_taps: "You tapped {n}, not {k}",
      ex_me_together: "You lifted with someone else 👯",
      ex_me_order: "You came down before your turn",
      ex_food_0: "Bread",
      ex_food_1: "Foul",
      ex_food_2: "Falafel",
      ex_food_3: "Pickles",
      ex_food_4: "Watermelon",
      ex_food_5: "Kahk",
      ex_food_6: "Dates",
      ex_food_7: "Kunafa",
      ex_next_in: "Next order in {n}…",
      ex_next_level: "On to level {lvl} in {n}…",
      ex_next_now: "Next order",
      ex_over: "The tea's all spilt!",
      ex_over_title: "The table",
      ex_reached: "You reached level {n}",
      ex_cleared_lab: "orders done exactly",
      ex_best_now: "The room's best: {n}",
      ex_record: "A new record for the room! 🏆",
      ex_clean: "Steadiest hands",
      ex_ring_won: "💍 Golden hand!",
      ex_play_again: "Play again",
    }
  },
  rules: {
    ar: {
      exact: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>كل واحد على موبايله، ومن 3 لـ12. كل مستوى <b>أمر واحد للترابيزة كلها</b>، زي «<b>بالظبط ٣ منكم يحطوا إيدهم!</b>».</li>
                <li>الأمر بيظهر لحظة تقروه، وبعد العدّ ٣… ٢… ١ <b>نفّذوه على الدايرة اللي في موبايلك</b>: دوس، أو اضغط وسيب، أو اخبط.</li>
                <li>الموبايل بيعرف بالظبط مين داس وإمتى، فمفيش غش: <b>كل الأوامر عن الموبايل بس</b> (كام إيد، التوقيت، الدور، اللون أو الرقم اللي على شاشتك).</li>
                <li>مظبوط؟ <b>مستوى جديد</b> وأكلة جديدة على الترابيزة. غلط؟ <b>كوباية شاي بتتدلق</b> والشاشة بتوري إيد مين كانت زيادة أو ناقصة (بضحك، مش بفضيحة). عندكم ٣ كوبايات، وكل ٥ مستويات كوباية جديدة.</li>
                <li>الشاي خلص؟ اللعبة خلصت، وأحسن مستوى بيتحفظ رقم للأوضة.</li>
            </ol>
            <details class="help-more"><summary>📜 الأوامر كلها</summary>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li><b>بالظبط كذا منكم</b>: العدد بالظبط؛ الإيد الزيادة (آخر واحدة نزلت) تاخد تلطيشة.</li>
                <li><b>محدش يحط إيده!</b> الفخ: الإيدين بتترعش فوق الترابيزة، واللي يدوس النحلة تقرصه.</li>
                <li><b>كل الإيدين مع بعض</b>: في نفس اللحظة؛ اللي سبق أو اتأخر بيبان.</li>
                <li><b>كل واحد يخبط كذا خبطة</b>، و<b>الترابيزة كلها كذا خبطة</b>: عدّوا بصوت عالي.</li>
                <li><b>بالظبط كذا يفضلوا حاطين إيدهم لحد الجرس</b>.</li>
                <li><b>بالدور</b>: الأسامي بالترتيب؛ و<b>النبضة</b>: بتلف على الترابيزة ودوس لما توصلك.</li>
                <li><b>بص على شاشتك</b>: لون أو شكل أو رقم سري على شاشتك إنت بس (بس الخضر، بالظبط اتنين من النجوم، الفردي…)، و<b>اعكسوا</b>: مكتوب «دوس» متدوسش.</li>
                <li><b>أرقامكم تجمع كذا</b>: كل واحد معاه رقم سري؛ اتكلموا واتفقوا مين ينزل.</li>
                <li><b>شيلوا على العداد</b>: كل واحد يشيل إيده لما العداد يوصل رقمه؛ و<b>واحد ورا التاني</b>: ولا إيدين يتشالوا مع بعض.</li>
                <li>الأوامر بتصعب مع المستوى: وقت أضيق، أرقام أكبر، وأمر جديد تقريبا كل مستوى.</li>
            </ul></details>
            <p class="help-sub">💍 الإيد الدهب</p>
            <p class="text-xs">الإيد اللي تصح 5 أوامر ورا بعض بيتحط في صباعها خاتم دهب على الترابيزة، ويقع أول ما تغلط. وهي لابساه بيتحسب لها +1 في «أثبت إيد» آخر السهرة: حافظ عليه!</p>
            <p class="help-sub">📺 على التلفزيون (اختياري)</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>الترابيزة كبيرة: الإيدين وهي بتنزل، الأمر، الكوبايات والأكل. من غير تلفزيون الترابيزة على كل موبايل، والصوت من موبايل المضيف.</li>
            </ul>`,
    },
    en: {
      exact: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>Everyone on their own phone, 3 to 12. Each level is <b>one order for the whole table</b>, like "<b>Exactly 3 of you: hands down!</b>".</li>
                <li>The order shows for a moment to read, then after 3… 2… 1 <b>do it on the round pad on your phone</b>: press, hold and let go, or tap.</li>
                <li>The phone knows exactly who pressed and when, so there's no cheating: <b>every order is about the phone</b> (how many hands, the timing, the turn, the colour or number on your own screen).</li>
                <li>Right? <b>A new level</b> and a new dish on the table. Wrong? <b>A glass of tea spills</b> and the screen shows whose hand was extra or missing (for laughs, not blame). You have 3 glasses, and every 5 levels refills one.</li>
                <li>Out of tea? The game ends, and the best level is kept as the room's record.</li>
            </ol>
            <details class="help-more"><summary>📜 Every order</summary>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li><b>Exactly N of you</b>: exactly that many; the extra hand (the last one down) gets a slap.</li>
                <li><b>Nobody put a hand down!</b> The trap: the hands tremble over the table, and a bee stings whoever presses.</li>
                <li><b>All hands together</b>: at the same moment; whoever is early or late shows.</li>
                <li><b>Everyone taps N times</b>, and <b>the whole table: N taps</b>: count out loud.</li>
                <li><b>Exactly N hands still down at the bell</b>.</li>
                <li><b>In turn</b>: the names in order; and <b>the pulse</b>: it goes round the table, press when it reaches you.</li>
                <li><b>Look at your screen</b>: a secret colour, shape or number on your own screen (only the greens, exactly two of the stars, the odd numbers…), and <b>do the opposite</b>: it says Press, don't.</li>
                <li><b>Your numbers add up to N</b>: each has a secret number; talk it over and agree who goes.</li>
                <li><b>Lift on the counter</b>: lift your hand when the counter reaches your number; and <b>one by one</b>: no two hands up at once.</li>
                <li>The orders get harder with the level: tighter timing, bigger numbers, and a new order almost every level.</li>
            </ul></details>
            <p class="help-sub">💍 The golden hand</p>
            <p class="text-xs">A hand right 5 orders in a row gets a gold ring on its finger on the table, and loses it at its first mistake. While it wears it, it counts +1 in «Steadiest hands» at the end of the night: protect it!</p>
            <p class="help-sub">📺 On the TV (optional)</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>The table big: the hands coming down, the order, the glasses and the food. With no TV the table is on every phone, and the sound on the host's phone.</li>
            </ul>`,
    }
  }
});
