/* ============================================================================
   الخزنة («صندوق جدّو») — the locks, the manual and the numbers (1 Oct 2026)
   ----------------------------------------------------------------------------
   Shared by the page (inlined, SHARED_LISTS) and the rooms server (bundled
   before RoomGames.js). Everything here is generated by the app from a seed -
   no content list: a game's manual (grandpa's notebook) from the game's seed,
   every safe from its own. The server keeps both seeds (room._vault); a phone
   is sent only what it may hold - a lock's look, or a page of the manual - and
   draws it with the helpers here. No DOM, nothing that runs at load. Every
   name starts with vault / VAULT_.

   The four locks (the owner's rules, 1 Oct 2026):
     wires    3-6 coloured wires; cut the one the notebook's rules for that
              count name («لو في سلكين أحمر اقطع آخر أحمر»).
     symbols  four (five later) strange symbols that can only be described;
              exactly one column of the notebook holds them all - press them in
              that column's order, top to bottom.
     dial     a dial shows a shape; the notebook turns it into a 3-number code
              (read backwards when the chest's number says so).
     lights   a lamp flashes a colour pattern; the notebook maps each colour to
              the button to press, and the map changes with the mistakes so far.
   ========================================================================= */
const VAULT_LOCKS = ['wires', 'symbols', 'dial', 'lights'];
const VAULT_LOCK_NAMES = {
  wires: ['الأسلاك', 'Wires'],
  symbols: ['الرموز', 'Symbols'],
  dial: ['القرص', 'The dial'],
  lights: ['النور', 'Lights']
};

// The numbers, in one place (decided while building, 1 Oct 2026).
const VAULT_MIN = 2;               // players to start: an opener and a reader
const VAULT_TEAM_MIN = 4;          // «فريقين»: two a side at least
const VAULT_MAX = 10;              // at the table; the rest watch
const VAULT_READY_MS = 5000;       // the safe's card before the clock starts
const VAULT_BETWEEN_MS = 6000;     // a safe's result before the next one comes by itself
const VAULT_STRIKES = 3;           // «٣ غلطات»: the third sets off the alarm
const VAULT_SPEEDUP = 0.25;        // each strike: the candle burns 25% faster (×1.25, ×1.5)
const VAULT_PENALTY_MS = 15000;    // «من الوقت»: the first mistake of a safe burns 15 s, the next 30, then 45…
/** «من الوقت»: what the n-th mistake of a safe burns (15 s, 30, 45…; the review of 1 Oct 2026: a flat 15 s made guessing cheaper than reading). */
const vaultPenaltyMs = (n) => VAULT_PENALTY_MS * Math.max(1, Math.floor(n) || 1);
const VAULT_SET_COUNTS = [3, 5, 7];
const VAULT_PTS_OPENER = 3;        // a safe opened, set of safes: the opener
const VAULT_PTS_READER = 2;        //   each reader on that side
const VAULT_PTS_CLEAN = 1;         //   everyone on that side, when it opened with no mistake
const VAULT_PTS_LOCK = 2;          // «الكل»: a lock opened, to its holder
const VAULT_PTS_LOCK_CLEAN = 1;    //   +1 when nobody made a mistake on that lock
const VAULT_PTS_FIRST = 1;         //   +1 for the first lock of the safe to open
const VAULT_PTS_PAGE = 1;          //   and 1 to whoever held its page

/**
 * A level: how many locks, how hard each, and the time. Endless levels count
 * up one a safe; a set of safes plays safe k at level k.
 *   locks   2 at level 1, 3 at level 2, all 4 from level 3 («الكل»: one per phone)
 *   wires   3-4 wires, then 3-5 from level 3, 4-6 from level 5
 *   syms    4 symbols, 5 from level 5
 *   lights  a pattern of 3, 4 from level 3, 5 from level 5
 *   ms      the candle: 2:30, 3:00, 3:30, then 15 s less a level, never under 2:00;
 *           «الكل» (every lock at once): 2:30, 10 s less a level, never under 1:15
 */
const vaultLevel = (level, way) => {
  const L = Math.max(1, Number(level) || 1);
  return {
    locks: L <= 1 ? 2 : L === 2 ? 3 : 4,
    wires: L <= 2 ? [3, 4] : L <= 4 ? [3, 5] : [4, 6],
    syms: L >= 5 ? 5 : 4,
    lights: L <= 2 ? 3 : L <= 4 ? 4 : 5,
    ms: way === 'all'
      ? Math.max(75000, 150000 - 10000 * (L - 1))
      : (L <= 1 ? 150000 : L === 2 ? 180000 : Math.max(120000, 210000 - 15000 * (L - 3)))
  };
};

/* --- the colours ------------------------------------------------------------- */
const VAULT_COLORS = { r: '#e5383b', b: '#2f6fd6', y: '#f6c945', w: '#f4f4f4', k: '#2b2b2b', g: '#2fbf62' };
const VAULT_COLOR_NAMES = {
  r: ['أحمر', 'red'], b: ['أزرق', 'blue'], y: ['أصفر', 'yellow'],
  w: ['أبيض', 'white'], k: ['أسود', 'black'], g: ['أخضر', 'green']
};
const VAULT_WIRE_COLORS = ['r', 'b', 'y', 'w', 'k'];
const VAULT_LIGHT_COLORS = ['r', 'b', 'g', 'y'];

/* --- the symbols: drawn, never letters, so they can only be described ----------
   Each is a path in a 40×40 box, drawn as a stroke («اللي شبه الشوكة»). */
const VAULT_SYMBOLS = {
  trident: 'M20 35V9M11 9v6q0 7 9 7q9 0 9-7V9',
  eye: 'M4 20Q20 5 36 20Q20 35 4 20ZM16 20a4 4 0 1 0 8 0a4 4 0 1 0-8 0',
  spiral: 'M20 20a2 2 0 1 1 2 2a5 5 0 0 1-5-5a8 8 0 0 1 8-8a11 11 0 0 1 11 11a14 14 0 0 1-14 14',
  hook: 'M25 5V25q0 9-8 9t-8-8M21 9h8',
  ladder: 'M13 5V35M27 5V35M13 12H27M13 20H27M13 28H27',
  crown: 'M7 31L8 11L15 19L20 8L25 19L32 11L33 31Z',
  keyhole: 'M20 6a7 7 0 0 1 4 12.7L27 34H13L16 18.7A7 7 0 0 1 20 6Z',
  moonstar: 'M24 6A14 14 0 1 0 33 28A11 11 0 0 1 24 6ZM31 9l1.2 3.2 3.3.2-2.6 2 1 3.3-2.9-1.9-2.9 1.9 1-3.3-2.6-2 3.3-.2Z',
  pyramid: 'M20 5L35 33H5ZM17 23a3 3 0 1 0 6 0a3 3 0 1 0-6 0',
  hourglass: 'M10 5H30L10 35H30Z',
  zigzag: 'M5 12L12 28L20 12L28 28L35 12',
  waves: 'M4 14q4-6 8 0t8 0t8 0t8 0M4 26q4-6 8 0t8 0t8 0t8 0',
  pierced: 'M6 20a14 14 0 1 0 28 0a14 14 0 1 0-28 0M20 3V37',
  lolly: 'M13 12a7 7 0 1 0 14 0a7 7 0 1 0-14 0M20 19V36M14 30H26',
  comb: 'M5 11H35M9 11V30M15 11V30M21 11V30M27 11V30M33 11V30',
  antenna: 'M20 36V15M20 15L9 5M20 15L31 5M13 25H27',
  bird: 'M4 18Q12 9 20 19Q28 9 36 18M20 19V28M15 33H25',
  fish: 'M7 20Q19 6 30 20Q19 34 7 20ZM30 20L37 12V28ZM14 18.5v.1',
  tent: 'M5 35L20 12L35 35ZM20 12V4L28 7L20 10',
  forked: 'M20 36V21M20 21L9 8M20 21L31 8M9 8H15M9 8V14M31 8H25M31 8V14',
  rings: 'M4 20a9 9 0 1 0 18 0a9 9 0 1 0-18 0M18 20a9 9 0 1 0 18 0a9 9 0 1 0-18 0',
  burst: 'M20 4V12M20 28V36M4 20H12M28 20H36M9 9L14 14M26 26L31 31M31 9L26 14M14 26L9 31',
  bowtie: 'M5 10L20 20L5 30ZM35 10L20 20L35 30Z',
  drop: 'M20 5Q31 20 20 31Q9 20 20 5ZM8 36H32',
  snake: 'M29 8Q13 4 13 13Q13 20 22 21Q31 22 28 30Q25 37 11 32',
  anchor: 'M20 9V35M9 25Q20 40 31 25M13 14H27M17 6.5a3 3 0 1 0 6 0a3 3 0 1 0-6 0',
  maze: 'M7 7H33V33H13V13H27V27H20',
  hbar: 'M5 20H35M5 11V29M35 11V29M20 14V26',
  frog: 'M7 27a13 8 0 1 0 26 0a13 8 0 1 0-26 0M9 15a4 4 0 1 0 8 0a4 4 0 1 0-8 0M23 15a4 4 0 1 0 8 0a4 4 0 1 0-8 0',
  umbrella: 'M5 20Q20 2 35 20ZM20 20V32Q20 36 15 35',
  pinwheel: 'M20 20V6Q28 6 28 14ZM20 20H34Q34 28 26 28ZM20 20V34Q12 34 12 26ZM20 20H6Q6 12 14 12Z',
  crossbox: 'M8 8H32V32H8ZM8 8L32 32'
};
const VAULT_SYMBOL_IDS = Object.keys(VAULT_SYMBOLS);
const VAULT_COLS = 6;              // the notebook's columns of symbols
const VAULT_COL_LEN = 7;           // symbols a column

/* --- the dial's shapes: these can be named («الشكل قلب») ------------------- */
const VAULT_SHAPES = {
  circle: { ar: 'دايرة', en: 'Circle', d: 'M5 20a15 15 0 1 0 30 0a15 15 0 1 0-30 0Z' },
  tri: { ar: 'مثلث', en: 'Triangle', d: 'M20 5L36 34H4Z' },
  square: { ar: 'مربع', en: 'Square', d: 'M6 6H34V34H6Z' },
  star: { ar: 'نجمة', en: 'Star', d: 'M20 3L24.9 14.2 37 15.3 27.8 23.3 30.5 35.2 20 29 9.5 35.2 12.2 23.3 3 15.3 15.1 14.2Z' },
  heart: { ar: 'قلب', en: 'Heart', d: 'M20 35C6 25 2 17 6 11C10 5 17 6 20 12C23 6 30 5 34 11C38 17 34 25 20 35Z' },
  moon: { ar: 'هلال', en: 'Crescent', d: 'M26 4A16 16 0 1 0 36 28A12 12 0 1 1 26 4Z' },
  diamond: { ar: 'معيّن', en: 'Diamond', d: 'M20 3L35 20L20 37L5 20Z' },
  hexagon: { ar: 'سداسي', en: 'Hexagon', d: 'M12 5H28L36 20L28 35H12L4 20Z' },
  plus: { ar: 'زائد', en: 'Plus', d: 'M15 4H25V15H36V25H25V36H15V25H4V15H15Z' }
};
const VAULT_SHAPE_IDS = Object.keys(VAULT_SHAPES);

/* --- the seeded generator ----------------------------------------------------- */
/** A seed: a whole number the server keeps. */
const vaultSeed = () => Math.floor(Math.random() * 2147483646) + 1;
/** mulberry32: the same seed, the same safe, on any machine. */
const vaultRng = (seed) => {
  let a = (Number(seed) >>> 0) || 1;
  return () => {
    a = (a + 0x6D2B79F5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};
const vaultInt = (rnd, n) => Math.floor(rnd() * n);
const vaultPick = (rnd, list) => list[vaultInt(rnd, list.length)];
const vaultShuffleR = (rnd, list) => {
  const out = list.slice();
  for (let i = out.length - 1; i > 0; i--) { const j = vaultInt(rnd, i + 1); const t = out[i]; out[i] = out[j]; out[j] = t; }
  return out;
};

/* --- the notebook (the manual), one per game ------------------------------------
   manual = {
     wires:   { 3: [rule…], 4: […], 5: […], 6: […] }   three rules and «غير كده» each
     symbols: [[ids × 7] × 6]                           the columns
     dial:    { codes: { shape: [d, d, d] }, twist: 'lastOdd' | 'firstEven' | 'sumBig' }
     lights:  [{ r, b, g, y } × 3]                      the map with no mistakes, after one, after two or more
   }
   A wire rule: { if: { t, c } | null, do: { t: 'pos', p } | { t: 'lastOf', c } | { t: 'firstOf', c } }
     if.t  'none' no c wire · 'last' the last wire is c · 'first' the first is c
           'many' more than one c · 'one' exactly one c */
const VAULT_WIRE_IFS = ['none', 'last', 'first', 'many', 'one'];

const vaultWireRules = (rnd, n) => {
  const rules = [];
  const used = {};
  vaultShuffleR(rnd, VAULT_WIRE_IFS).slice(0, 3).forEach((t) => {
    let c = vaultPick(rnd, VAULT_WIRE_COLORS);
    for (let k = 0; k < 6 && used[t + c]; k++) c = vaultPick(rnd, VAULT_WIRE_COLORS);
    used[t + c] = true;
    let act;
    if (t === 'many') act = rnd() < 0.6 ? { t: 'lastOf', c } : { t: 'pos', p: vaultInt(rnd, n) };
    else if (t === 'one') act = rnd() < 0.6 ? { t: 'firstOf', c } : { t: 'pos', p: vaultInt(rnd, n) };
    else if (t === 'last') act = rnd() < 0.5 ? { t: 'pos', p: n - 1 } : { t: 'pos', p: vaultInt(rnd, n - 1) };
    else act = { t: 'pos', p: vaultInt(rnd, n) };
    rules.push({ if: { t, c }, do: act });
  });
  rules.push({ if: null, do: { t: 'pos', p: vaultInt(rnd, n) } });
  return rules;
};

/** A derangement of the four light colours: no colour presses itself. */
const vaultLightRow = (rnd) => {
  for (;;) {
    const to = vaultShuffleR(rnd, VAULT_LIGHT_COLORS);
    if (to.every((c, i) => c !== VAULT_LIGHT_COLORS[i])) {
      const row = {};
      VAULT_LIGHT_COLORS.forEach((c, i) => { row[c] = to[i]; });
      return row;
    }
  }
};

const vaultManual = (seed) => {
  const rnd = vaultRng(seed);
  const wires = {};
  [3, 4, 5, 6].forEach((n) => { wires[n] = vaultWireRules(rnd, n); });
  const symbols = [];
  for (let c = 0; c < VAULT_COLS; c++) symbols.push(vaultShuffleR(rnd, VAULT_SYMBOL_IDS).slice(0, VAULT_COL_LEN));
  const codes = {};
  const taken = {};
  VAULT_SHAPE_IDS.forEach((sh) => {
    let code;
    do { code = [vaultInt(rnd, 10), vaultInt(rnd, 10), vaultInt(rnd, 10)]; } while (taken[code.join('')] || taken[code.slice().reverse().join('')] || code[0] === code[2]);
    taken[code.join('')] = true;
    codes[sh] = code;
  });
  const twist = vaultPick(rnd, ['lastOdd', 'firstEven', 'sumBig']);
  const lights = [];
  while (lights.length < 3) {
    const row = vaultLightRow(rnd);
    if (!lights.some((x) => VAULT_LIGHT_COLORS.every((c) => x[c] === row[c]))) lights.push(row);
  }
  return { wires, symbols, dial: { codes, twist }, lights };
};

/* --- the answers ---------------------------------------------------------------- */
const vaultWireIf = (cond, wires) => {
  if (!cond) return true;
  const n = wires.filter((x) => x === cond.c).length;
  if (cond.t === 'none') return n === 0;
  if (cond.t === 'many') return n > 1;
  if (cond.t === 'one') return n === 1;
  if (cond.t === 'last') return wires[wires.length - 1] === cond.c;
  if (cond.t === 'first') return wires[0] === cond.c;
  return false;
};
const vaultWireDo = (act, wires) => {
  if (act.t === 'lastOf') return wires.lastIndexOf(act.c);
  if (act.t === 'firstOf') return wires.indexOf(act.c);
  return Math.min(wires.length - 1, Math.max(0, act.p));
};
/** The wire to cut: the first rule for that count that applies (index from the top, 0-based). */
const vaultWireAnswer = (rules, wires) => {
  const list = (rules || {})[wires.length] || [];
  for (let k = 0; k < list.length; k++) {
    if (vaultWireIf(list[k].if, wires)) {
      const i = vaultWireDo(list[k].do, wires);
      if (i >= 0) return i;
    }
  }
  return wires.length - 1;
};

/** The one column holding every symbol shown, or -1. */
const vaultSymbolCol = (cols, shown) => {
  const hits = [];
  (cols || []).forEach((col, i) => { if (shown.every((x) => col.indexOf(x) !== -1)) hits.push(i); });
  return hits.length === 1 ? hits[0] : -1;
};
/** The order to press: the symbols shown, as their column lists them from the top. */
const vaultSymbolOrder = (cols, shown) => {
  const c = vaultSymbolCol(cols, shown);
  return c < 0 ? null : cols[c].filter((x) => shown.indexOf(x) !== -1);
};

/** Does the chest's number turn the code backwards? */
const vaultTwistOn = (twist, serial) => {
  const d = String(serial || '').split('').map(Number);
  if (!d.length) return false;
  if (twist === 'lastOdd') return d[d.length - 1] % 2 === 1;
  if (twist === 'firstEven') return d[0] % 2 === 0;
  if (twist === 'sumBig') return d.reduce((a, x) => a + x, 0) >= 20;
  return false;
};
const vaultDialCode = (dial, shape, serial) => {
  const code = ((dial || {}).codes || {})[shape];
  if (!code) return null;
  return vaultTwistOn(dial.twist, serial) ? code.slice().reverse() : code.slice();
};

/** The light rows: no mistakes, one, two or more. */
const vaultLightRowOf = (mistakes) => Math.min(2, Math.max(0, Number(mistakes) || 0));
/** The buttons to press for a flashed pattern, with this many mistakes so far. */
const vaultLightAnswer = (lights, seq, mistakes) => {
  const row = (lights || [])[vaultLightRowOf(mistakes)] || {};
  return seq.map((c) => row[c]);
};

/* --- a safe ---------------------------------------------------------------------
   safe = { seed, serial: '4827', locks: [{ k, look, sol }] }
     wires   look { wires: ['r', …] }        sol: the index to cut
     symbols look { syms: [ids, shuffled] }  sol: the ids in order
     dial    look { shape }                  sol: [d, d, d]
     lights  look { seq: ['r', …] }          sol: null (it depends on the mistakes at the time)
   `kinds` is the locks in the safe, in order; `L` a vaultLevel. */
const vaultMakeSafe = (seed, manual, kinds, L) => {
  const rnd = vaultRng(seed);
  let serial = String(1 + vaultInt(rnd, 9));
  for (let k = 0; k < 3; k++) serial += String(vaultInt(rnd, 10));
  const locks = kinds.map((k) => {
    if (k === 'wires') {
      const n = L.wires[0] + vaultInt(rnd, L.wires[1] - L.wires[0] + 1);
      let wires;
      do { wires = []; for (let i = 0; i < n; i++) wires.push(vaultPick(rnd, VAULT_WIRE_COLORS)); } while (wires.every((x) => x === wires[0]));
      return { k, look: { wires }, sol: vaultWireAnswer(manual.wires, wires) };
    }
    if (k === 'symbols') {
      for (let tries = 0; tries < 200; tries++) {
        const col = manual.symbols[vaultInt(rnd, manual.symbols.length)];
        const shown = vaultShuffleR(rnd, col).slice(0, L.syms);
        const order = vaultSymbolOrder(manual.symbols, shown);
        if (order) return { k, look: { syms: shown }, sol: order };
      }
      // Never in practice (six random columns of seven from 32 hardly share four); a sure one anyway.
      const col = manual.symbols[0].filter((x) => !manual.symbols.slice(1).some((c) => c.indexOf(x) !== -1));
      const shown = (col.length >= L.syms ? col : manual.symbols[0]).slice(0, L.syms);
      return { k, look: { syms: vaultShuffleR(rnd, shown) }, sol: manual.symbols[0].filter((x) => shown.indexOf(x) !== -1) };
    }
    if (k === 'dial') {
      const shape = vaultPick(rnd, VAULT_SHAPE_IDS);
      return { k, look: { shape }, sol: vaultDialCode(manual.dial, shape, serial) };
    }
    const seq = [];
    for (let i = 0; i < L.lights; i++) seq.push(vaultPick(rnd, VAULT_LIGHT_COLORS));
    return { k, look: { seq }, sol: null };
  });
  return { seed, serial, locks };
};

/* --- the notebook's pages ---------------------------------------------------------
   A page is a lock's part of the notebook: 'wires', or a half of it ('wires.1',
   'wires.2') when there are more readers than locks. A half of the wires holds
   3-4 wires or 5-6; of the symbols columns 1-3 or 4-6; of the dial the first
   five shapes or the last four (both with the twist); of the lights red and
   blue or green and yellow. */
const VAULT_HALVES = {
  wires: [[3, 4], [5, 6]],
  symbols: [[0, 1, 2], [3, 4, 5]],
  dial: [VAULT_SHAPE_IDS.slice(0, 5), VAULT_SHAPE_IDS.slice(5)],
  lights: [['r', 'b'], ['g', 'y']]
};
const vaultUnitKind = (u) => String(u || '').split('.')[0];
const vaultUnitPart = (u) => Number(String(u || '').split('.')[1]) || 0;

/** What a page holds, from the manual: what a reader's phone is sent. */
const vaultPageData = (manual, u) => {
  const k = vaultUnitKind(u);
  const part = vaultUnitPart(u);
  const half = part ? VAULT_HALVES[k][part - 1] : null;
  if (k === 'wires') {
    const rules = {};
    (half || [3, 4, 5, 6]).forEach((n) => { rules[n] = manual.wires[n]; });
    return { u, k, part, rules };
  }
  if (k === 'symbols') {
    return { u, k, part, cols: (half || [0, 1, 2, 3, 4, 5]).map((i) => ({ n: i + 1, syms: manual.symbols[i].slice() })) };
  }
  if (k === 'dial') {
    return { u, k, part, codes: (half || VAULT_SHAPE_IDS).map((sh) => ({ s: sh, c: manual.dial.codes[sh].slice() })), twist: manual.dial.twist };
  }
  const colors = half || VAULT_LIGHT_COLORS;
  return { u, k, part, colors: colors.slice(), rows: manual.lights.map((row) => colors.map((c) => row[c])) };
};

/** The pages of a safe for `readers` readers: whole pages, halved one lock at a time while readers outnumber them. */
const vaultUnits = (kinds, readers) => {
  const units = [];
  const uniq = kinds.filter((k, i) => kinds.indexOf(k) === i);
  uniq.forEach((k) => units.push(k));
  for (let i = 0; i < uniq.length && units.length < readers; i++) {
    const at = units.indexOf(uniq[i]);
    units.splice(at, 1, uniq[i] + '.1', uniq[i] + '.2');
  }
  return units;
};
/** Pages shared out to readers: contiguous groups while there are enough pages, else copies round. */
const vaultDealUnits = (units, readers) => {
  const out = readers.map(() => []);
  if (!readers.length) return out;
  if (units.length >= readers.length) {
    const base = Math.floor(units.length / readers.length);
    const extra = units.length % readers.length;
    let at = 0;
    readers.forEach((r, i) => { const n = base + (i < extra ? 1 : 0); out[i] = units.slice(at, at + n); at += n; });
  } else {
    readers.forEach((r, i) => { out[i] = [units[i % units.length]]; });
  }
  return out;
};
