/* vault: the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].<id>, as everywhere. */
gameText({
  translations: {
    ar: {
      vt_title: "صندوق جدّو",
      vt_level: "المستوى {n}",
      vt_safe_of: "الخزنة {n} من {m}",
      vt_chest_no: "صندوق رقم",
      vt_ask_chest: "اسأل اللي بيفتح: الصندوق رقمه كام؟",
      vt_lock_of: "القفل {n} من {m}",
      vt_open_lock: "اتفتح!",
      vt_prev: "القفل اللي قبله",
      vt_next: "القفل اللي بعده",
      vt_wire_hint: "دوس على السلك اللي هتقطعه",
      vt_wire_again: "دوس عليه تاني عشان تقطعه ✂",
      vt_wire_aria: "السلك {n}، {c}",
      vt_sym_aria: "رمز",
      vt_dial_up: "زوّد الرقم {n}",
      vt_dial_down: "قلّل الرقم {n}",
      vt_try: "لِف وافتح",
      vt_tab_lock: "قفلك",
      vt_tab_page: "نوتتك",
      vt_watching: "بتتفرج · تلعب في الجولة الجاية",
      vt_part: "(جزء {n})",
      vt_opener_is: "{name} بيفتح الصندوق",
      vt_tv_opens: "الصندوق على الشاشة",
      vt_tv_opens_short: "🔐 بيفتح الصندوق",
      vt_holds_lock: "{name}: قفل {lock}",
      vt_holds_page: "{name}: صفحة {page}",
      vt_speed: "الشمعة بتسيح أسرع ×{x}",
      vt_minus: "الغلطة الجاية بتحرق {s} ثانية",
      vt_swipe: "اسحب يمين وشمال بين الأقفال",
      vt_read_out: "اسأل اللي بيفتح يوصفلك، واقراله القاعدة",
      vt_lock_opened: "تِك! {lock} اتفتح",
      vt_mistake_n: "غلطة {n} من 3",
      vt_minus15: "غلطة! −{s} ثانية",
      vt_lost_alarm: "الإنذار ضرب! 🚨",
      vt_lost_time: "الشمعة خلصت! ⏰",
      vt_opened: "اتفتح الصندوق! 🎉",
      vt_team_won: "{team} فتح الأول!",
      vt_team_a: "الفريق الأحمر",
      vt_team_b: "الفريق الأزرق",
      vt_other_team: "{team}: {n}/{m}",
      vt_n_locks: "{n} أقفال",
      vt_starts_in: "الشمعة بتولّع بعد {n}",
      vt_next_in: "الخزنة الجاية بعد {n}",
      vt_end_in: "النتيجة بعد {n}",
      vt_next_now: "الخزنة الجاية دلوقتي",
      vt_take_over: "📱 خلّي موبايل يفتح",
      vt_take_over_confirm: "الخزنة هتتنقل من الشاشة لموبايل، ومش هترجع للشاشة اللعبة دي. أكيد؟",
      vt_over_set: "خلصت الخزن!",
      vt_over_left: "مفيش لاعيبة كفاية",
      vt_levels_cleared: "خزن فتحتوها",
      vt_new_best: "رقم جديد للأوضة!",
      vt_room_best: "أحسن رقم للأوضة: {n}",
      vt_again: "العب تاني",
      vt_wait_host: "مستنيين المضيف",
      vt_way: "طريقة اللعب",
      vt_way_one: "واحد بيفتح",
      vt_way_all: "الكل",
      vt_way_teams: "فريقين",
      vt_way_one_hint: "موبايل واحد عليه الصندوق، والباقيين كل واحد صفحة من نوتة جدّو. اللي بيفتح بيتغيّر كل خزنة.",
      vt_way_all_hint: "كل موبايل عليه قفل من الصندوق، وصفحة بتفتح قفل حد تاني. الكل بيتكلم مرة واحدة!",
      vt_way_teams_hint: "نفس الصندوق لفريقين، كل فريق بفاتح وقرّاية. أول فريق يفتحه ياخده.",
      vt_opener: "مين بيفتح الصندوق؟",
      vt_opener_phone: "موبايل (بالدور)",
      vt_opener_tv: "الشاشة",
      vt_mistakes: "الغلطات",
      vt_mis_strikes: "3 غلطات",
      vt_mis_time: "من الوقت",
      vt_mis_strikes_hint: "كل غلطة الشمعة بتسيح أسرع، والتالتة بتضرب الإنذار والخزنة تروح.",
      vt_mis_time_hint: "أول غلطة في الخزنة بتحرق 15 ثانية من الشمعة، والتانية 30، والتالتة 45… فاقروا كويس قبل ما تجرّبوا.",
      vt_win: "المكسب",
      vt_win_levels: "مستويات ملهاش آخر",
      vt_win_set: "عدد خزن بالنقط",
      vt_win_teams_note: "الفريقين بيلعبوا عدد خزن بالنقط.",
      vt_count: "كام خزنة؟",
      vt_tv_mistakes: "غلطات",
      vt_tv_next_pen: "الجاية −{s} ث",
      vt_tv_opened: "{name} فتح {lock} ✓",
      vt_tv_opened_tv: "{lock} اتفتح ✓",
      vt_tv_mistake: "غلطة في {lock} ✗",
      vt_why_title: "ليه كده؟ جدّو كان قايل:",
      vt_key_use: "افتحه بالمفتاح الاحتياطي ({n})",
      vt_keys_n: "{n} مفتاح احتياطي",
      vt_key_confirm: "تصرف المفتاح الاحتياطي على قفل {lock}؟ هيتفتح على طول، والمفتاح يروح.",
      vt_key_won: "🗝️ مفتاح احتياطي! تالت خزنة من غير غلط",
      vt_key_used: "🗝️ المفتاح الاحتياطي فتح {lock}",
      vt_key_name: "مفتاح احتياطي",
    },
    en: {
      vt_title: "Grandpa's chest",
      vt_level: "Level {n}",
      vt_safe_of: "Safe {n} of {m}",
      vt_chest_no: "Chest no.",
      vt_ask_chest: "Ask the opener: what's the chest number?",
      vt_lock_of: "Lock {n} of {m}",
      vt_open_lock: "Open!",
      vt_prev: "Previous lock",
      vt_next: "Next lock",
      vt_wire_hint: "Tap the wire you'll cut",
      vt_wire_again: "Tap it again to cut ✂",
      vt_wire_aria: "Wire {n}, {c}",
      vt_sym_aria: "Symbol",
      vt_dial_up: "Number {n} up",
      vt_dial_down: "Number {n} down",
      vt_try: "Turn and open",
      vt_tab_lock: "Your lock",
      vt_tab_page: "Your notebook",
      vt_watching: "Watching · you play next round",
      vt_part: "(part {n})",
      vt_opener_is: "{name} opens the chest",
      vt_tv_opens: "The chest is on the screen",
      vt_tv_opens_short: "🔐 opens the chest",
      vt_holds_lock: "{name}: the {lock} lock",
      vt_holds_page: "{name}: the {page} page",
      vt_speed: "The candle burns faster ×{x}",
      vt_minus: "The next mistake burns {s} seconds",
      vt_swipe: "Swipe between the locks",
      vt_read_out: "Ask the opener to describe it; read them the rule",
      vt_lock_opened: "Click! {lock} open",
      vt_mistake_n: "Mistake {n} of 3",
      vt_minus15: "Mistake! −{s} seconds",
      vt_lost_alarm: "The alarm went off! 🚨",
      vt_lost_time: "The candle burnt out! ⏰",
      vt_opened: "The chest is open! 🎉",
      vt_team_won: "{team} opened it first!",
      vt_team_a: "Red team",
      vt_team_b: "Blue team",
      vt_other_team: "{team}: {n}/{m}",
      vt_n_locks: "{n} locks",
      vt_starts_in: "The candle lights in {n}",
      vt_next_in: "Next safe in {n}",
      vt_end_in: "The results in {n}",
      vt_next_now: "Next safe now",
      vt_take_over: "📱 Let a phone open it",
      vt_take_over_confirm: "The safe moves from the screen to a phone, and won't go back to the screen this game. Sure?",
      vt_over_set: "That's every safe!",
      vt_over_left: "Not enough players",
      vt_levels_cleared: "safes opened",
      vt_new_best: "A new room record!",
      vt_room_best: "Room's best: {n}",
      vt_again: "Play again",
      vt_wait_host: "Waiting for the host",
      vt_way: "How to play",
      vt_way_one: "One opens",
      vt_way_all: "Everyone",
      vt_way_teams: "Two teams",
      vt_way_one_hint: "One phone has the chest; everyone else holds a page of grandpa's notebook. The opener changes every safe.",
      vt_way_all_hint: "Every phone has a lock of the chest, and a page that opens someone else's. Everyone talks at once!",
      vt_way_teams_hint: "The same chest for two teams, each with an opener and readers. The first team to open it takes it.",
      vt_opener: "Who opens the chest?",
      vt_opener_phone: "A phone (taking turns)",
      vt_opener_tv: "The screen",
      vt_mistakes: "Mistakes",
      vt_mis_strikes: "3 strikes",
      vt_mis_time: "Cost time",
      vt_mis_strikes_hint: "Every mistake makes the candle burn faster; the third sets off the alarm and the safe is lost.",
      vt_mis_time_hint: "A safe's first mistake burns 15 seconds off the candle, the second 30, the third 45… so read before you guess.",
      vt_win: "Winning",
      vt_win_levels: "Endless levels",
      vt_win_set: "A set of safes, for points",
      vt_win_teams_note: "Two teams play a set of safes, for points.",
      vt_count: "How many safes?",
      vt_tv_mistakes: "Mistakes",
      vt_tv_next_pen: "next −{s}s",
      vt_tv_opened: "{name} opened {lock} ✓",
      vt_tv_opened_tv: "{lock} open ✓",
      vt_tv_mistake: "Mistake on {lock} ✗",
      vt_why_title: "Why? Grandpa's notebook said:",
      vt_key_use: "Open it with the spare key ({n})",
      vt_keys_n: "{n} spare key(s)",
      vt_key_confirm: "Spend the spare key on the {lock} lock? It opens at once, and the key is gone.",
      vt_key_won: "🗝️ A spare key! A third safe with no mistake",
      vt_key_used: "🗝️ The spare key opened {lock}",
      vt_key_name: "Spare key",
    }
  },
  rules: {
    ar: {
      vault: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>كل واحد بموبايله. صندوق جدّو مقفول بأقفال (2 في الأول، لحد 4): <b>اللي شايف القفل مش معاه النوتة، واللي معاه النوتة مش شايف القفل</b>. اتكلموا!</li>
                <li>✂️ <b>الأسلاك</b>: اقطع سلك واحد حسب قواعد النوتة. 🔣 <b>الرموز</b>: دوس الرموز بترتيب العمود اللي فيه كلهم. 🎛️ <b>القرص</b>: الشكل ليه كود من 3 أرقام. 💡 <b>النور</b>: لكل لون بيرمش زرار في النوتة، والجدول بيتغيّر مع الغلطات.</li>
                <li>الوقت شمعة بتسيح. <b>3 غلطات</b>: كل غلطة الشمعة تسيح أسرع، والتالتة تضرب الإنذار والخزنة تروح. أو <b>من الوقت</b>: أول غلطة في الخزنة بتحرق 15 ثانية، والتانية 30، والتالتة 45… وبتبدأ من 15 تاني في الخزنة اللي بعدها.</li>
                <li>📱📖 <b>واحد بيفتح</b>: موبايل واحد (أو الشاشة، لو المضيف اختار) عليه الصندوق، وصفحات النوتة متقسّمة على الباقيين. اللي بيفتح بيتغيّر كل خزنة.</li>
                <li>📱📱 <b>الكل</b>: كل موبايل عليه قفل، وصفحة من النوتة بتفتح قفل حد تاني. الكل بيتكلم مرة واحدة.</li>
                <li>⚔️ <b>فريقين</b>: نفس الصندوق للفريقين، كل فريق بفاتح وقرّاية، وأول فريق يفتحه ياخده.</li>
                <li>🧐 <b>ليه كده؟</b> لما خزنة تخلص وفيها غلطة أو قفل ماتفتحش، الكارت بيقول على موبايل اللي بيفتح وعلى الشاشة القاعدة اللي كانت ماشية والحل الصح.</li>
                <li>🗝️ <b>المفتاح الاحتياطي</b>: كل تالت خزنة تتفتح من غير ولا غلطة بتكسبكم مفتاح نحاس يتعلّق على حبل الغسيل. اللي بيفتح يقدر يصرفه على أي قفل في خزنة بعد كده، فيتفتح على طول.</li>
            </ol>
            <p class="help-sub">🏆 المكسب</p>
            <p class="text-xs">مستويات ملهاش آخر (كل خزنة أصعب، والأوضة بتحفظ أحسن رقم)، أو 3 / 5 / 7 خزن بالنقط: اللي فتح الصندوق 3، كل واحد معاه النوتة 2، و+1 للكل لو اتفتح من غير ولا غلطة. في «الكل»: القفل اللي تفتحه 2 (+1 لو محدش غلط فيه، و+1 لو كان أول قفل يتفتح)، وصاحب صفحته 1.</p>
            <p class="help-sub">📺 التلفزيون</p>
            <p class="text-xs">السندرة: صفحات النوتة متعلّقة على حبل غسيل باسم كل واحد، والصندوق تحت بأقفاله والشمعة والغلطات، من غير ما يوري شكل أي قفل ولا الحل.</p>`,
    },
    en: {
      vault: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>Everyone on their own phone. Grandpa's chest is shut with padlocks (2 at first, up to 4): <b>whoever sees a lock doesn't have the notebook, and whoever has the notebook can't see the lock</b>. Talk!</li>
                <li>✂️ <b>Wires</b>: cut one wire, by the notebook's rules. 🔣 <b>Symbols</b>: press them in the order of the column that holds them all. 🎛️ <b>The dial</b>: its shape has a 3-number code. 💡 <b>Lights</b>: each colour that flashes has its button in the notebook, and the table changes with the mistakes.</li>
                <li>The time is a melting candle. <b>3 strikes</b>: every mistake makes it burn faster, and the third sets off the alarm and the safe is lost. Or <b>cost time</b>: a safe's first mistake burns 15 seconds, the second 30, the third 45… back to 15 at the next safe.</li>
                <li>📱📖 <b>One opens</b>: one phone (or the screen, if the host picks it) has the chest, and the notebook's pages are shared out among the rest. The opener changes every safe.</li>
                <li>📱📱 <b>Everyone</b>: every phone has a lock, and a page that opens someone else's. Everyone talks at once.</li>
                <li>⚔️ <b>Two teams</b>: the same chest for both, each team with an opener and readers; the first to open it takes it.</li>
                <li>🧐 <b>Why?</b> When a safe ends with a mistake or a lock left shut, the card on the opener's phone and the screen shows the rule that applied and the right answer.</li>
                <li>🗝️ <b>The spare key</b>: every third safe opened with no mistake earns a brass key, hung on the washing line. The opener can spend it on any lock of a later safe, and that lock opens at once.</li>
            </ol>
            <p class="help-sub">🏆 Winning</p>
            <p class="text-xs">Endless levels (each safe harder, the room keeps its best), or a set of 3 / 5 / 7 safes for points: the opener 3, each reader 2, and +1 for everyone when it opened with no mistake. In «Everyone»: a lock you open 2 (+1 if nobody slipped on it, +1 if it was the first to open), and whoever held its page 1.</p>
            <p class="help-sub">📺 The TV</p>
            <p class="text-xs">The attic: the notebook's pages hanging on a washing line with each holder's name, the chest below with its padlocks, the candle and the mistakes, never what a lock looks like or its answer.</p>`,
    }
  }
});
