/**
 * Builds generated/rules.js from the shared files at the project root, so the
 * game rules and word lists keep one copy: the room server bundles them from
 * here, and tools/validate-content.js checks the very same files.
 *
 * Wrangler runs this before every `wrangler dev` and `wrangler deploy` ([build]
 * in wrangler.toml). The output sits outside src/ on purpose: wrangler dev
 * re-runs the build when src/ changes, and writing into it would loop.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const FILES = ['SpyWords.js', 'CodenamesWords.js', 'PartyContent.js', 'TriviaQuestions.js', 'ChameleonWords.js', 'SpyfallPlaces.js', 'BombPrompts.js', 'EmojiRiddles.js', 'Proverbs.js', 'MonkeyWords.js', 'StopWords.js', 'SkrewCards.js', 'RoomGames.js'];
const EXPORTS = ['ROOM_GAME_IDS', 'applyRoomAction', 'roomDeadline', 'roomTimeout', 'withPromptMemory', 'normaliseClue', 'foldStopAnswer', 'stopAnswerFits', 'stopWordKnown', 'stopDictionary', 'roomEvent', 'chatFor', 'roomPlayerLeft', 'sameRoomName'];

const sources = await Promise.all(FILES.map(async (name) =>
  `// ---- ${name} ----\n` + await readFile(path.join(root, name), 'utf8')));

const PRELUDE = `// GENERATED by rooms-worker/build.mjs from ${FILES.join(', ')}.
// Do not edit: change those files and the next build refreshes this one.

// Code.js used to serve the spy words to the rules.
const getSpyData = () => SPY_WORDS;

// RoomGames.js remembers dealt prompts through Apps Script's Script Properties.
// Here that memory is the PromptMemory Durable Object: a room loads it before
// an action that deals, runs the rules against it, then saves what changed.
// Without it loaded, the rules fall back to the room's own memory.
let promptMemory = null;
const PropertiesService = {
  getScriptProperties() {
    const memory = promptMemory;
    if (!memory) throw new Error('prompt memory not loaded');
    return {
      getProperty: (key) => Object.prototype.hasOwnProperty.call(memory.values, key) ? memory.values[key] : null,
      setProperty: (key, value) => { memory.values[key] = String(value); memory.changed[key] = String(value); }
    };
  }
};

/** Runs \`run\` with \`memory\` ({ values, changed }) as the prompt history. */
const withPromptMemory = (memory, run) => {
  promptMemory = memory;
  try { return run(); } finally { promptMemory = null; }
};
`;

const out = PRELUDE + '\n' + sources.join('\n\n') + `\n\nexport { ${EXPORTS.join(', ')} };\n`;
await mkdir(path.join(here, 'generated'), { recursive: true });
await writeFile(path.join(here, 'generated', 'rules.js'), out, 'utf8');
console.log(`generated/rules.js built from ${FILES.join(', ')}`);
