/**
 * Builds generated/rules.js from the shared files at the project root, so the
 * game rules and word lists keep one copy: the room server bundles them from
 * here, and tools/validate-content.js checks the very same files.
 *
 * Wrangler runs this before every `wrangler dev` and `wrangler deploy` ([build]
 * in wrangler.toml). The output sits outside src/ on purpose: wrangler dev
 * re-runs the build when src/ changes, and writing into it would loop.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { rulesFingerprint } from './fingerprint.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const FILES = ['DisabledGames.js', 'Dice.js', 'GameIds.js', 'Packs.js', 'SpyWords.js', 'CodenamesWords.js', 'PartyContent.js', 'TriviaQuestions.js', 'ChameleonWords.js', 'SpyfallPlaces.js', 'BombPrompts.js', 'EmojiRiddles.js', 'Proverbs.js', 'MonkeyWords.js', 'StopWords.js', 'SkrewCards.js', 'TimelineEvents.js', 'UnoCards.js', 'DominoTiles.js', 'Connect4.js', 'DotsBoxes.js', 'TicTacToe.js', 'Battleship.js', 'Chess.js', 'Chess4.js', 'Ludo.js', 'Snakes.js', 'BankAlhaz.js', 'GuessWho.js', 'Witness.js', 'Dark.js', 'Hangman.js', 'MiniGolf.js', 'PlayingCards.js', 'Skull.js', 'Estimation.js', 'Wire.js', 'Vault.js', 'Hear.js', 'Bowling.js', 'WordleWords.js', 'Countries.js', 'SolveGames.js', 'SoloShared.js', 'ConnectionsWords.js', 'Sudoku.js', 'Queens.js', 'Tango.js', 'Nonogram.js', 'Mines.js', 'Strands.js', 'WordWheel.js', 'Pinpoint.js', 'QuizStreak.js', 'Crew.js', 'Songs.js', 'Missions.js', 'RoomGames.js', 'RoomUno.js', 'RoomDomino.js', 'RoomDuels.js', 'RoomBattleship.js', 'RoomChess.js', 'RoomChess4.js', 'RoomVoteChess.js', 'RoomHandBrain.js', 'RoomBughouse.js', 'RoomLudo.js', 'RoomSnakes.js', 'RoomBank.js', 'RoomGuessWho.js', 'RoomHangman.js', 'RoomMiniGolf.js', 'RoomDoubt.js', 'RoomOldMaid.js', 'RoomSkull.js', 'RoomEstimation.js', 'RoomBowling.js', 'RoomTournament.js', 'RoomSolve.js', 'RoomRace.js', 'RoomChairs.js', 'RoomBumper.js', 'RoomWire.js', 'RoomVault.js', 'RoomWitness.js', 'RoomExact.js', 'RoomDark.js', 'RoomBox.js', 'RoomHum.js', 'RoomHear.js', 'RoomProgram.js', 'RoomMission.js']
const EXPORTS = ['RULES_HASH', 'ROOM_GAME_IDS', 'applyRoomAction', 'roomDeadline', 'roomTimeout', 'roomTimeoutDeals', 'withPromptMemory', 'normaliseClue', 'guessVerdict', 'bankNightPoints', 'foldStopAnswer', 'stopAnswerFits', 'stopWordKnown', 'stopDictionary', 'stopLettersFor', 'roomEvent', 'chatFor', 'roomPlayerLeft', 'sameRoomName', 'roomForcedMove', 'ROOM_FORCED_DELAY_MS', 'tourBracket', 'bumperRelaying', 'darkRelaying', 'DISABLED_GAMES', 'APP_GAME_IDS', 'APP_REPORT_IDS', 'CREW_MAX_MEMBERS', 'CREW_MAX_NIGHTS', 'CREW_MAX_PACKS', 'CREW_NAME_MAX', 'CREW_MEMBER_NAME_MAX', 'CREW_CODE_RE', 'crewNewCode', 'crewCleanCode', 'crewFold', 'crewCleanName', 'crewCleanNight', 'crewView', 'crewFreezeChamps', 'crewNightInput', 'crewTable', 'crewTitles', 'crewRecords', 'crewMonthOf', 'crewDateOf', 'crewNightSummary', 'crewAddPackTo', 'crewRemovePackFrom', 'crewKeysMigrate', 'crewKeyRec', 'crewKeyIsManager', 'crewIssueKey', 'crewSetManager', 'crewPairMake', 'crewPairUse', 'CREW_KEYS_PER_MEMBER', 'CREW_PAIR_TRIES', 'PACK_TTL_MS', 'PACK_ALPHABET', 'PACK_CODE_LEN', 'PACK_CODE_RE', 'packClean', 'packCode', 'packHideAnswers', 'packAnswerOf', 'packCleanQuiz', 'roomHostChanged', 'nightProgramFinished', 'programPlaces', 'PROGRAM_PLACE_POINTS', 'HUM_SONGS', 'missionView', 'missionJoined', 'missionPlayerLeft', 'MISSION_SWAP_MS', 'MISSION_CATCH_WAIT_MS', 'MISSION_MIN_PEOPLE'];

const sources = await Promise.all(FILES.map(async (name) =>
  `// ---- ${name} ----\n` + await readFile(path.join(root, name), 'utf8')));

const PRELUDE = `// GENERATED by rooms-worker/build.mjs from ${FILES.join(', ')}.
// Do not edit: change those files and the next build refreshes this one.

// Code.js used to serve the spy words to the rules.
const getSpyData = () => SPY_WORDS;

// RoomGames.js remembers dealt prompts through Apps Script's Script Properties.
// Here that memory is the PromptMemory Durable Object: a room loads it before
// an action that deals, runs the rules against it, then saves what changed.
// Without it loaded, the rules fall back to the room's own memory.
let promptMemory = null;
const PropertiesService = {
  getScriptProperties() {
    const memory = promptMemory;
    if (!memory) throw new Error('prompt memory not loaded');
    return {
      getProperty: (key) => Object.prototype.hasOwnProperty.call(memory.values, key) ? memory.values[key] : null,
      setProperty: (key, value) => { memory.values[key] = String(value); memory.changed[key] = String(value); }
    };
  }
};

/** Runs \`run\` with \`memory\` ({ values, changed }) as the prompt history. */
const withPromptMemory = (memory, run) => {
  promptMemory = memory;
  try { return run(); } finally { promptMemory = null; }
};
`;

// What this bundle was built from (fingerprint.mjs): /health reports it and
// tools/check-live.mjs compares it with the folder's.
const RULES_HASH = await rulesFingerprint(FILES);
const out = PRELUDE + `\nconst RULES_HASH = ${JSON.stringify(RULES_HASH)};\n\n` + sources.join('\n\n') + `\n\nexport { ${EXPORTS.join(', ')} };\n`;
await mkdir(path.join(here, 'generated'), { recursive: true });
await writeFile(path.join(here, 'generated', 'rules.js'), out, 'utf8');
console.log(`generated/rules.js built from ${FILES.join(', ')}`);
