/**
 * قبل ولا بعد — the dated events the Timeline game deals from.
 *
 * Egyptian and Arab first, with famous world dates mixed in so the cards
 * spread across the centuries (the owner, 20 Sep 2026): inventions, famous
 * buildings, sport, Egyptian history and culture, space and everyday things.
 *
 * Every entry is { y, ar, en }: one year that is not in dispute, and the event
 * in both languages. **A date only goes in if it has one well-known answer.**
 * A game whose cards can be argued about is worse than a short bank - there is
 * no host to settle it, and the server's word is final. Nothing political or
 * divisive, nothing sad for its own sake, and no event whose name carries its
 * year (ثورة 1919 would give itself away).
 *
 * Two cards may share a year (the review of 1 Oct 2026): `timelineFits` in
 * RoomGames.js takes a card next to one of the same year on either side, so a
 * placement is never right and wrong at once. `tools/validate-content.js`
 * checks that every entry has all three fields and that no event is listed
 * twice.
 *
 * THIS FILE IS SERVER-ONLY. It is bundled into the Worker by
 * rooms-worker/build.mjs and is deliberately NOT inlined into the page by
 * tools/build-*.mjs: the years of the cards still in a hand are the whole
 * secret of the game, and shipping the answer key inside the app would hand
 * every player a lookup table. The phone is told a card's year only once the
 * table has seen it go down.
 */
const TIMELINE_EVENTS = [
  { y: 622,  ar: 'الهجرة النبوية وبداية التقويم الهجري',   en: 'The Hijra: the Islamic calendar begins' },
  { y: 969,  ar: 'تأسيس مدينة القاهرة',                    en: 'Cairo is founded' },
  { y: 1176, ar: 'صلاح الدين يبدأ بناء القلعة في القاهرة', en: 'Saladin begins building the Cairo Citadel' },
  { y: 1453, ar: 'العثمانيين يفتحوا القسطنطينية',          en: 'The Ottomans take Constantinople' },
  { y: 1492, ar: 'كولومبس يوصل لأمريكا',                   en: 'Columbus reaches the Americas' },
  { y: 1517, ar: 'العثمانيين يدخلوا مصر',                  en: 'The Ottomans take Egypt' },
  { y: 1522, ar: 'أول رحلة بحرية حوالين الأرض تخلص',       en: 'The first voyage around the world is completed' },
  { y: 1687, ar: 'نيوتن ينشر قوانين الحركة والجاذبية',     en: 'Newton publishes his laws of motion and gravity' },
  { y: 1769, ar: 'جيمس وات يسجّل اختراع آلته البخارية',    en: 'James Watt patents his steam engine' },
  { y: 1776, ar: 'إعلان استقلال أمريكا',                   en: 'The American Declaration of Independence' },
  { y: 1783, ar: 'أول ناس يطيروا في منطاد هوا سخن',        en: 'The first people fly in a hot-air balloon' },
  { y: 1789, ar: 'قيام الثورة الفرنسية',                    en: 'The French Revolution begins' },
  { y: 1796, ar: 'أول تطعيم ضد الجدري',                    en: 'The first smallpox vaccination' },
  { y: 1798, ar: 'الحملة الفرنسية توصل مصر',               en: "Napoleon's army lands in Egypt" },
  { y: 1799, ar: 'اكتشاف حجر رشيد',                        en: 'The Rosetta Stone is found' },
  { y: 1800, ar: 'فولتا يخترع أول بطارية',                 en: 'Volta invents the first battery' },
  { y: 1805, ar: 'محمد علي يحكم مصر',                      en: 'Muhammad Ali becomes ruler of Egypt' },
  { y: 1813, ar: 'اكتشاف معبد أبو سمبل تحت الرمل',         en: 'The temple of Abu Simbel is found under the sand' },
  { y: 1822, ar: 'شامبليون يفك رموز الهيروغليفي',          en: 'Champollion deciphers hieroglyphs' },
  { y: 1825, ar: 'أول قطر ركاب بالبخار في العالم',         en: "The world's first public steam railway opens" },
  { y: 1839, ar: 'الإعلان عن اختراع التصوير الفوتوغرافي',  en: 'Photography is announced to the world' },
  { y: 1840, ar: 'أول طابع بريد في العالم',                en: "The world's first postage stamp" },
  { y: 1844, ar: 'أول رسالة تلغراف بشفرة مورس',            en: 'The first Morse code telegraph message' },
  { y: 1859, ar: 'ساعة بيج بن تبدأ تشتغل',                 en: 'Big Ben starts keeping time' },
  { y: 1863, ar: 'أول مترو أنفاق في العالم يفتح في لندن',  en: "The world's first underground railway opens in London" },
  { y: 1866, ar: 'أول طابع بريد مصري',                     en: "Egypt's first postage stamp" },
  { y: 1869, ar: 'افتتاح قناة السويس',                     en: 'The Suez Canal opens' },
  { y: 1869, ar: 'افتتاح دار الأوبرا الخديوية في القاهرة', en: 'The Khedivial Opera House opens in Cairo' },
  { y: 1869, ar: 'مندلييف يعمل الجدول الدوري للعناصر',     en: 'Mendeleev publishes the periodic table' },
  { y: 1871, ar: 'أول عرض لأوبرا عايدة في القاهرة',        en: 'Aida is first performed, in Cairo' },
  { y: 1876, ar: 'اختراع التليفون',                        en: 'The telephone is invented' },
  { y: 1877, ar: 'أول بطولة ويمبلدون للتنس',               en: 'The first Wimbledon tennis championship' },
  { y: 1879, ar: 'إديسون يعمل لمبة بتنوّر ساعات طويلة',     en: "Edison's long-lasting light bulb" },
  { y: 1882, ar: 'الإنجليز يحتلوا مصر',                    en: 'Britain occupies Egypt' },
  { y: 1886, ar: 'كارل بنز يسجّل أول عربية بموتور بنزين',  en: 'Karl Benz patents the first petrol car' },
  { y: 1886, ar: 'اختراع الكوكاكولا',                      en: 'Coca-Cola is invented' },
  { y: 1886, ar: 'افتتاح تمثال الحرية في نيويورك',         en: 'The Statue of Liberty is unveiled in New York' },
  { y: 1889, ar: 'افتتاح برج إيفل',                        en: 'The Eiffel Tower opens' },
  { y: 1891, ar: 'اختراع كرة السلة',                       en: 'Basketball is invented' },
  { y: 1895, ar: 'أول عرض سينما في العالم',                en: 'The first film screening' },
  { y: 1895, ar: 'اكتشاف الأشعة السينية (أشعة إكس)',       en: 'X-rays are discovered' },
  { y: 1896, ar: 'أول أولمبياد حديثة',                     en: 'The first modern Olympic Games' },
  { y: 1901, ar: 'أول جوايز نوبل',                         en: 'The first Nobel Prizes' },
  { y: 1902, ar: 'افتتاح خزان أسوان القديم',               en: 'The old Aswan Dam opens' },
  { y: 1902, ar: 'افتتاح المتحف المصري في التحرير',        en: 'The Egyptian Museum in Tahrir opens' },
  { y: 1903, ar: 'أول طيران للأخوين رايت',                 en: "The Wright brothers' first flight" },
  { y: 1905, ar: 'أينشتاين ينشر النظرية النسبية الخاصة',   en: 'Einstein publishes special relativity' },
  { y: 1907, ar: 'تأسيس النادي الأهلي',                    en: 'Al Ahly club is founded' },
  { y: 1908, ar: 'تأسيس جامعة القاهرة (الجامعة الأهلية)',  en: 'Cairo University is founded' },
  { y: 1908, ar: 'أول عربية فورد موديل T',                 en: 'The first Ford Model T' },
  { y: 1911, ar: 'تأسيس نادي الزمالك',                     en: 'Zamalek club is founded' },
  { y: 1912, ar: 'غرق التيتانيك',                          en: 'The Titanic sinks' },
  { y: 1912, ar: 'اكتشاف تمثال نفرتيتي',                   en: 'The bust of Nefertiti is found' },
  { y: 1914, ar: 'بداية الحرب العالمية الأولى',            en: 'The First World War begins' },
  { y: 1914, ar: 'افتتاح قناة بنما',                       en: 'The Panama Canal opens' },
  { y: 1918, ar: 'نهاية الحرب العالمية الأولى',            en: 'The First World War ends' },
  { y: 1920, ar: 'طلعت حرب يأسس بنك مصر',                  en: 'Talaat Harb founds Banque Misr' },
  { y: 1922, ar: 'اكتشاف مقبرة توت عنخ آمون',              en: "Tutankhamun's tomb is discovered" },
  { y: 1927, ar: 'لندبرج يعدّي المحيط الأطلنطي بالطيارة لوحده', en: 'Lindbergh flies alone across the Atlantic' },
  { y: 1928, ar: 'اكتشاف البنسلين',                        en: 'Penicillin is discovered' },
  { y: 1928, ar: 'أول ظهور لميكي ماوس',                    en: 'Mickey Mouse first appears' },
  { y: 1928, ar: 'أول ميدالية دهب أولمبية لمصر',           en: "Egypt's first Olympic gold medal" },
  { y: 1930, ar: 'أول كأس عالم لكرة القدم',                en: 'The first football World Cup' },
  { y: 1931, ar: 'افتتاح مبنى إمباير ستيت في نيويورك',     en: 'The Empire State Building opens in New York' },
  { y: 1932, ar: 'تأسيس المملكة العربية السعودية',         en: 'Saudi Arabia is founded' },
  { y: 1932, ar: 'تأسيس مصر للطيران',                      en: 'EgyptAir is founded' },
  { y: 1934, ar: 'بداية الإذاعة المصرية',                  en: 'Egyptian radio begins broadcasting' },
  { y: 1934, ar: 'مصر أول منتخب عربي وأفريقي يلعب كأس العالم', en: 'Egypt become the first Arab and African team at a World Cup' },
  { y: 1935, ar: 'تأسيس ستوديو مصر',                       en: 'Studio Misr is founded' },
  { y: 1937, ar: 'افتتاح كوبري جولدن جيت في أمريكا',       en: 'The Golden Gate Bridge opens' },
  { y: 1937, ar: 'نزول فيلم ديزني «سنو وايت والأقزام السبعة»', en: "Disney's Snow White and the Seven Dwarfs comes out" },
  { y: 1938, ar: 'بيرو يسجّل اختراع القلم الجاف',          en: 'Bíró patents the ballpoint pen' },
  { y: 1939, ar: 'بداية الحرب العالمية التانية',           en: 'The Second World War begins' },
  { y: 1945, ar: 'نهاية الحرب العالمية التانية',           en: 'The Second World War ends' },
  { y: 1947, ar: 'أول طيارة تكسر حاجز الصوت',              en: 'A plane breaks the sound barrier for the first time' },
  { y: 1952, ar: 'ثورة يوليو',                             en: 'The July Revolution in Egypt' },
  { y: 1953, ar: 'أول طلوع لقمة إفرست',                    en: 'Everest is climbed for the first time' },
  { y: 1953, ar: 'اكتشاف شكل الـDNA',                      en: 'The shape of DNA is discovered' },
  { y: 1955, ar: 'افتتاح أول ديزني لاند',                  en: 'The first Disneyland opens' },
  { y: 1956, ar: 'تأميم قناة السويس',                      en: 'The Suez Canal is nationalised' },
  { y: 1957, ar: 'إطلاق أول قمر صناعي',                    en: 'The first satellite is launched' },
  { y: 1957, ar: 'مصر تكسب أول كأس أمم أفريقيا',           en: 'Egypt win the first Africa Cup of Nations' },
  { y: 1958, ar: 'البرازيل تكسب أول كأس عالم ليها',        en: 'Brazil win their first World Cup' },
  { y: 1958, ar: 'تسجيل مكعب الليجو بشكله اللي نعرفه',     en: 'The LEGO brick as we know it is patented' },
  { y: 1960, ar: 'بداية بناء السد العالي',                 en: 'Work on the Aswan High Dam begins' },
  { y: 1960, ar: 'بداية إرسال التليفزيون المصري',          en: 'Egyptian television begins broadcasting' },
  { y: 1961, ar: 'أول إنسان يطلع الفضاء',                  en: 'The first person in space' },
  { y: 1961, ar: 'افتتاح برج القاهرة',                     en: 'The Cairo Tower opens' },
  { y: 1963, ar: 'أول ست تطلع الفضاء',                     en: 'The first woman in space' },
  { y: 1964, ar: 'أم كلثوم تغني «إنت عمري» أول مرة',       en: 'Umm Kulthum first sings «Enta Omri»' },
  { y: 1964, ar: 'أول قطر طلقة في اليابان',                en: "Japan's first bullet train" },
  { y: 1966, ar: 'إنجلترا تكسب كأس العالم على أرضها',      en: 'England win the World Cup at home' },
  { y: 1968, ar: 'نقل معبد أبو سمبل لمكانه الجديد يخلص',   en: 'Abu Simbel is moved to its new, higher site' },
  { y: 1969, ar: 'أول إنسان على القمر',                    en: 'The first man on the Moon' },
  { y: 1969, ar: 'أول معرض القاهرة الدولي للكتاب',         en: 'The first Cairo International Book Fair' },
  { y: 1970, ar: 'وفاة جمال عبد الناصر',                   en: 'Gamal Abdel Nasser dies' },
  { y: 1970, ar: 'أول رحلة ركاب لطيارة الجامبو بوينج 747', en: 'The first Boeing 747 jumbo jet passenger flight' },
  { y: 1971, ar: 'تأسيس الإمارات',                         en: 'The United Arab Emirates is founded' },
  { y: 1971, ar: 'أول إيميل يتبعت',                        en: 'The first email is sent' },
  { y: 1973, ar: 'حرب أكتوبر',                             en: 'The October War' },
  { y: 1973, ar: 'أول مكالمة من موبايل',                   en: 'The first mobile phone call' },
  { y: 1973, ar: 'افتتاح دار أوبرا سيدني',                 en: 'The Sydney Opera House opens' },
  { y: 1974, ar: 'اختراع مكعب روبيك',                      en: "The Rubik's Cube is invented" },
  { y: 1975, ar: 'وفاة أم كلثوم',                          en: 'Umm Kulthum dies' },
  { y: 1975, ar: 'تأسيس مايكروسوفت',                       en: 'Microsoft is founded' },
  { y: 1975, ar: 'قناة السويس تفتح تاني للملاحة',          en: 'The Suez Canal reopens to ships' },
  { y: 1976, ar: 'تأسيس شركة أبل',                         en: 'Apple is founded' },
  { y: 1976, ar: 'أول مهرجان القاهرة السينمائي',           en: 'The first Cairo International Film Festival' },
  { y: 1976, ar: 'الكونكورد تبدأ رحلات الركاب',            en: 'Concorde begins passenger flights' },
  { y: 1977, ar: 'وفاة عبد الحليم حافظ',                   en: 'Abdel Halim Hafez dies' },
  { y: 1977, ar: 'أول فيلم «حرب النجوم»',                  en: 'The first Star Wars film' },
  { y: 1979, ar: 'أول ووكمان من سوني',                     en: "Sony's first Walkman" },
  { y: 1980, ar: 'نزول لعبة باك مان',                      en: 'Pac-Man comes out' },
  { y: 1981, ar: 'أول رحلة لمكوك الفضاء',                  en: 'The first Space Shuttle flight' },
  { y: 1984, ar: 'اختراع لعبة تتريس',                      en: 'Tetris is created' },
  { y: 1985, ar: 'نزول أول لعبة «سوبر ماريو»',             en: 'Super Mario Bros. comes out' },
  { y: 1986, ar: 'مارادونا يكسب كأس العالم مع الأرجنتين',  en: 'Maradona wins the World Cup with Argentina' },
  { y: 1987, ar: 'افتتاح أول خط مترو في القاهرة',          en: "Cairo's first metro line opens" },
  { y: 1988, ar: 'نجيب محفوظ يفوز بجايزة نوبل',            en: 'Naguib Mahfouz wins the Nobel Prize' },
  { y: 1988, ar: 'افتتاح دار الأوبرا المصرية الجديدة',     en: 'The new Cairo Opera House opens' },
  { y: 1989, ar: 'سقوط سور برلين',                         en: 'The Berlin Wall falls' },
  { y: 1990, ar: 'منتخب مصر يلعب كأس العالم في إيطاليا',   en: 'Egypt play the World Cup in Italy' },
  { y: 1990, ar: 'إطلاق تلسكوب هابل للفضاء',               en: 'The Hubble Space Telescope is launched' },
  { y: 1991, ar: 'أول موقع على الإنترنت',                  en: 'The first website goes online' },
  { y: 1992, ar: 'أول رسالة SMS',                          en: 'The first text message is sent' },
  { y: 1994, ar: 'افتتاح نفق المانش بين إنجلترا وفرنسا',   en: 'The Channel Tunnel opens' },
  { y: 1994, ar: 'نزول أول بلايستيشن',                     en: 'The first PlayStation comes out' },
  { y: 1995, ar: 'نزول «حكاية لعبة»، أول فيلم كرتون كله بالكمبيوتر', en: 'Toy Story, the first all-computer-animated film' },
  { y: 1996, ar: 'نزول أول ألعاب بوكيمون',                 en: 'The first Pokémon games come out' },
  { y: 1996, ar: 'ولادة النعجة دوللي',                     en: 'Dolly the sheep is born' },
  { y: 1996, ar: 'افتتاح الخط التاني لمترو القاهرة',       en: "Cairo metro's second line opens" },
  { y: 1997, ar: 'نزول أول كتاب هاري بوتر',                en: 'The first Harry Potter book comes out' },
  { y: 1998, ar: 'تأسيس جوجل',                             en: 'Google is founded' },
  { y: 1998, ar: 'مصر تكسب أمم أفريقيا في بوركينا فاسو',   en: 'Egypt win the Africa Cup of Nations in Burkina Faso' },
  { y: 1999, ar: 'أحمد زويل يفوز بجايزة نوبل',             en: 'Ahmed Zewail wins the Nobel Prize' },
  { y: 2001, ar: 'إطلاق ويكيبيديا',                        en: 'Wikipedia launches' },
  { y: 2002, ar: 'افتتاح مكتبة الإسكندرية الجديدة',        en: 'The new Library of Alexandria opens' },
  { y: 2003, ar: 'آخر رحلة للكونكورد',                     en: "Concorde's last flight" },
  { y: 2004, ar: 'إطلاق فيسبوك',                           en: 'Facebook launches' },
  { y: 2004, ar: 'كرم جابر ياخد دهب الأولمبياد في أثينا',  en: 'Karam Gaber wins Olympic gold in Athens' },
  { y: 2005, ar: 'إطلاق يوتيوب',                           en: 'YouTube launches' },
  { y: 2006, ar: 'مصر تكسب أول أمم أفريقيا من التلاتة اللي ورا بعض', en: 'Egypt win the first of three Africa Cups of Nations in a row' },
  { y: 2006, ar: 'بلوتو يبطّل يتحسب كوكب',                 en: 'Pluto stops being counted as a planet' },
  { y: 2006, ar: 'إطلاق تويتر',                            en: 'Twitter launches' },
  { y: 2007, ar: 'أول آيفون',                              en: 'The first iPhone' },
  { y: 2008, ar: 'مصر تكسب أمم أفريقيا في غانا',           en: 'Egypt win the Africa Cup of Nations in Ghana' },
  { y: 2009, ar: 'إطلاق واتساب',                           en: 'WhatsApp launches' },
  { y: 2010, ar: 'مصر تكسب أمم أفريقيا تالت مرة ورا بعض',  en: 'Egypt win a third Africa Cup of Nations in a row' },
  { y: 2010, ar: 'افتتاح برج خليفة في دبي',                en: 'The Burj Khalifa opens in Dubai' },
  { y: 2010, ar: 'أول كأس عالم في أفريقيا',                en: 'The first World Cup in Africa' },
  { y: 2010, ar: 'إطلاق إنستجرام',                         en: 'Instagram launches' },
  { y: 2010, ar: 'أول آيباد',                              en: 'The first iPad' },
  { y: 2011, ar: 'ثورة يناير',                             en: 'The January Revolution in Egypt' },
  { y: 2012, ar: 'المسبار كيوريوسيتي ينزل على المريخ',     en: 'The Curiosity rover lands on Mars' },
  { y: 2015, ar: 'افتتاح قناة السويس الجديدة',             en: 'The New Suez Canal opens' },
  { y: 2017, ar: 'محمد صلاح ينضم لليفربول',                en: 'Mohamed Salah joins Liverpool' },
  { y: 2018, ar: 'منتخب مصر يلعب كأس العالم في روسيا',     en: 'Egypt play the World Cup in Russia' },
  { y: 2019, ar: 'أول أمم أفريقيا بـ24 منتخب، في مصر',      en: 'The first 24-team Africa Cup of Nations, in Egypt' },
  { y: 2019, ar: 'أول صورة لثقب أسود',                     en: 'The first picture of a black hole' },
  { y: 2021, ar: 'موكب المومياوات الملكية',                en: "The Pharaohs' Golden Parade" },
  { y: 2021, ar: 'إطلاق تلسكوب جيمس ويب',                  en: 'The James Webb Space Telescope is launched' },
  { y: 2022, ar: 'أول كأس عالم في بلد عربي (قطر)',          en: 'The first World Cup in an Arab country (Qatar)' },
  { y: 2022, ar: 'إطلاق شات جي بي تي',                     en: 'ChatGPT launches' }
];
