/* quizmaker: the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].<id>, as everywhere. */
gameText({
  translations: {
    ar: {
      qm_mine: "مسابقاتك",
      qm_new: "＋ مسابقة جديدة",
      qm_empty: "لسه معندكش مسابقات. اكتب أول واحدة: سؤال، أربع إجابات، وعلّم الصح.",
      qm_open_code_label: "عندك كود مسابقة؟",
      qm_open_code_hint: "اللي عمل المسابقة يبعتلك الكود، وتفتحها وتلعبوها.",
      qm_count: "أسئلة: {n}",
      qm_code: "الكود {c}",
      qm_unsaved: "لسه ما خدتش كود",
      qm_changed: "فيه تعديلات لسه متحفظتش",
      qm_saved_local: "💾 محفوظة على الموبايل",
      qm_opened: "من كود",
      qm_opened_ok: "اتفتحت: {t}",
      qm_words_opened: "اتفتحت كلمات: {t}",
      qm_title_ph: "اسم المسابقة",
      qm_q: "سؤال {n}",
      qm_editing: "بتعدّله دلوقتي",
      qm_q_ph: "اكتب السؤال",
      qm_choice_ph: "إجابة {l}",
      qm_tick: "علّم الإجابة الصح",
      qm_tick_hint: "دوس ✓ جنب الإجابة الصح.",
      qm_emoji: "إيموجي",
      qm_no_emoji: "من غير إيموجي",
      qm_dup: "نسخة",
      qm_sec_add: "قسم من هنا",
      qm_sec_ph: "اسم القسم: أفلام، أسئلة عن جدو…",
      qm_sec_remove: "شيل القسم",
      qm_del: "امسح",
      qm_done: "تمام",
      qm_up: "لفوق",
      qm_down: "لتحت",
      qm_drag: "اسحب عشان ترتّب",
      qm_add: "＋ سؤال جديد",
      qm_saving: "بنحفظ…",
      qm_row_missing: "⚠️ ناقص",
      qm_del_confirm: "تمسح السؤال ده؟",
      qm_last_edit: "آخر تعديل {when}",
      qm_just_now: "دلوقتي",
      qm_mins_ago: "من {n} دقيقة",
      qm_hours_ago: "من {n} ساعة",
      qm_days_ago: "من {n} يوم",
      qm_delete_quiz: "امسح المسابقة من الموبايل",
      qm_delete_quiz_confirm: "تمسح «{t}» من الموبايل ده؟ الكود هيفضل شغال عند اللي معاهم.",
      qm_copy_mine: "اعمل نسخة ليا",
      qm_answers_hidden: "الإجابات مع اللي كتب المسابقة: كل إجابة بتبان وسؤالها بيتلعب.",
      qm_sheet_ready: "{t} جاهزة 🎉",
      qm_sheet_code_hint: "ده كود المسابقة؛ أي حد يقدر يفتحها بيه.",
      qm_sheet_no_code: "لسه ما خدتش كود: لوحة الفرق شغالة من الموبايل ده، والغرفة والجرس بعد «احفظ».",
      qm_share: "ابعت الكود",
      qm_share_text: "تعالوا نلعب مسابقتي «{t}» على عشرى جيمينج. الكود: {c}",
      qm_way_room: "غرفة",
      qm_way_room_d: "كل واحد بيجاوب من موبايله",
      qm_way_board: "لوحة الفرق",
      qm_way_board_d: "فريقين على شاشة واحدة، وإنت المذيع",
      qm_way_buzzer: "الجرس",
      qm_way_buzzer_d: "إنت بتقرا، واللي يضغط الأول يجاوب",
      qm_src_unsaved: "(احفظها الأول)",
      pk_err_title: "اكتب اسم",
      pk_err_no_questions: "اكتب سؤال واحد على الأقل",
      pk_err_too_many: "60 سؤال بالكتير",
      pk_err_q_empty: "السؤال {n} فاضي",
      pk_err_choices_four: "السؤال {n} محتاج 4 إجابات",
      pk_err_choice_empty: "في إجابة فاضية في السؤال {n}",
      pk_err_choices_same: "في إجابتين زي بعض في السؤال {n}",
      pk_err_no_right: "علّم الإجابة الصح في السؤال {n}",
      pk_err_few_words: "محتاجين 6 كلمات على الأقل",
      pk_err_too_many_words: "300 كلمة بالكتير",
      pk_err_not_found: "مش لاقيين حاجة بالكود ده",
      pk_err_denied: "دي مش بتاعتك عشان تعدّلها: اعمل نسخة ليك",
      pk_err_offline: "مش متصل بالنت: اتحفظت على الموبايل، وخد الكود لما النت يرجع",
      pk_err_busy: "استنى شوية وجرّب تاني",
      pk_err_server: "حصلت مشكلة، جرّب تاني",
      pk_err_kind: "حصلت مشكلة، جرّب تاني",
      pk_err_too_big: "كبيرة أوي",
      wp_title_label: "اسم الكلمات",
      wp_title_ph: "مثلاً: عيلة عشري",
      wp_add_label: "ضيف كلمة، اسم، أو قفشة",
      wp_add_ph: "خالو حسن، الكنبة، مصيف 2019…",
      wp_add: "ضيف",
      wp_hint: "تقدر تلصق كلمات كتير مرة واحدة: كل واحدة في سطر، أو بينهم فاصلة.",
      wp_count: "كلمات: {n} من 300",
      wp_empty: "اكتب أول كلمة فوق 👆",
      wp_where: "بتظهر فئة «✍️ {t}» في الجاسوس، الحرباء، بدون كلام، على راسك، من أنا؟ وارسم وخمّن (الحرباء محتاجة 16 كلمة).",
      wp_open_label: "عندك كود كلمات العيلة؟",
      wp_readonly: "دي كلمات من الكود {c}: بتلعبوا بيها، والتعديل عند اللي عملها.",
      wp_copy_mine: "اعمل نسخة ليا",
      wp_remove: "امسح الكلمات من الموبايل",
      wp_remove_confirm: "تمسح الكلمات من الموبايل ده؟ الكود هيفضل شغال عند اللي معاهم.",
      wp_replace_confirm: "عندك كلمات تانية على الموبايل. نبدّلها بالكلمات دي؟ (اللي معاها كود ترجع بيه)",
      wp_sheet_ready: "{t} جاهزة 🎉",
      wp_sheet_hint: "ابعت الكود للعيلة: اللي يفتحه يلاقي الكلمات فئة في ألعاب الكلام.",
      wp_share_text: "كلمات العيلة «{t}» على عشرى جيمينج. افتح الأدوات ← كلماتنا والكود: {c}",
      wp_room_label: "الكلمات",
      wp_room_app: "كلمات التطبيق",
      wp_room_unsaved: "«كلماتنا» تتلعب في الغرفة بعد ما تاخد كود",
      crew_pack_on_phone: "على موبايلك",
      qm_from_crew: "من الشلة: {name}",
    },
    en: {
      qm_mine: "Your quizzes",
      qm_new: "＋ New quiz",
      qm_empty: "No quizzes yet. Write the first: a question, four answers, tick the right one.",
      qm_open_code_label: "Got a quiz code?",
      qm_open_code_hint: "Whoever made the quiz sends you its code; open it and play.",
      qm_count: "Questions: {n}",
      qm_code: "Code {c}",
      qm_unsaved: "No code yet",
      qm_changed: "Changes not saved yet",
      qm_saved_local: "💾 Kept on this phone",
      qm_opened: "From a code",
      qm_opened_ok: "Opened: {t}",
      qm_words_opened: "Words opened: {t}",
      qm_title_ph: "The quiz's name",
      qm_q: "Question {n}",
      qm_editing: "Editing now",
      qm_q_ph: "Write the question",
      qm_choice_ph: "Answer {l}",
      qm_tick: "Tick the right answer",
      qm_tick_hint: "Tap ✓ beside the right answer.",
      qm_emoji: "Emoji",
      qm_no_emoji: "No emoji",
      qm_dup: "Copy",
      qm_sec_add: "Section from here",
      qm_sec_ph: "Section name: Films, About Grandpa…",
      qm_sec_remove: "Remove the section",
      qm_del: "Delete",
      qm_done: "Done",
      qm_up: "Up",
      qm_down: "Down",
      qm_drag: "Drag to reorder",
      qm_add: "＋ New question",
      qm_saving: "Saving…",
      qm_row_missing: "⚠️ Unfinished",
      qm_del_confirm: "Delete this question?",
      qm_last_edit: "edited {when}",
      qm_just_now: "just now",
      qm_mins_ago: "{n} min ago",
      qm_hours_ago: "{n} h ago",
      qm_days_ago: "{n} days ago",
      qm_delete_quiz: "Delete the quiz from this phone",
      qm_delete_quiz_confirm: "Delete «{t}» from this phone? The code keeps working for whoever has it.",
      qm_copy_mine: "Make my own copy",
      qm_answers_hidden: "The answers stay with whoever wrote it: each shows as its question is played.",
      qm_sheet_ready: "{t} is ready 🎉",
      qm_sheet_code_hint: "This is the quiz's code: anyone can open it with it.",
      qm_sheet_no_code: "No code yet: the team board plays from this phone; a room and the buzzer after «Save».",
      qm_share: "Send the code",
      qm_share_text: "Let's play my quiz «{t}» on Ashry Gaming. The code: {c}",
      qm_way_room: "A room",
      qm_way_room_d: "Everyone answers on their own phone",
      qm_way_board: "Team board",
      qm_way_board_d: "Two teams on one screen, you host",
      qm_way_buzzer: "The buzzer",
      qm_way_buzzer_d: "You read it, the first to buzz answers",
      qm_src_unsaved: "(save it first)",
      pk_err_title: "Write a name",
      pk_err_no_questions: "Write at least one question",
      pk_err_too_many: "60 questions at most",
      pk_err_q_empty: "Question {n} is empty",
      pk_err_choices_four: "Question {n} needs 4 answers",
      pk_err_choice_empty: "An answer is empty in question {n}",
      pk_err_choices_same: "Two answers are the same in question {n}",
      pk_err_no_right: "Tick the right answer in question {n}",
      pk_err_few_words: "At least 6 words",
      pk_err_too_many_words: "300 words at most",
      pk_err_not_found: "Nothing found with that code",
      pk_err_denied: "This isn't yours to change: make your own copy",
      pk_err_offline: "Not online: kept on this phone; get the code when you're back online",
      pk_err_busy: "Wait a moment and try again",
      pk_err_server: "Something went wrong, try again",
      pk_err_kind: "Something went wrong, try again",
      pk_err_too_big: "Too big",
      wp_title_label: "The words' name",
      wp_title_ph: "e.g. The Ashry family",
      wp_add_label: "Add a word, a name or an inside joke",
      wp_add_ph: "Uncle Hassan, the sofa, summer 2019…",
      wp_add: "Add",
      wp_hint: "You can paste many at once: one a line, or with commas between them.",
      wp_count: "Words: {n} of 300",
      wp_empty: "Write the first word above 👆",
      wp_where: "Shows as the category «✍️ {t}» in Imposter, Chameleon, Charades, Heads Up, Who Am I? and Draw & Guess (Chameleon needs 16 words).",
      wp_open_label: "Got the family words' code?",
      wp_readonly: "These words come from code {c}: you play with them; changes are for whoever made them.",
      wp_copy_mine: "Make my own copy",
      wp_remove: "Delete the words from this phone",
      wp_remove_confirm: "Delete the words from this phone? The code keeps working for whoever has it.",
      wp_replace_confirm: "This phone has other words. Swap them for these? (Ones with a code can be opened again with it.)",
      wp_sheet_ready: "{t} is ready 🎉",
      wp_sheet_hint: "Send the code to the family: whoever opens it finds the words as a category in the word games.",
      wp_share_text: "The family words «{t}» on Ashry Gaming. Open Tools → Our words, and the code: {c}",
      wp_room_label: "The words",
      wp_room_app: "The app's words",
      wp_room_unsaved: "«Our words» plays in a room once it has a code",
      crew_pack_on_phone: "On your phone",
      qm_from_crew: "From the crew: {name}",
    }
  },
  rules: {
    ar: {
      quizmaker: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>من <b>الأدوات ← اعمل مسابقتك</b> (أو من كارت تحدي المعلومات): <b>＋ مسابقة جديدة</b>، اكتب اسمها، وكل سؤال: السؤال، <b>أربع إجابات</b>، ودوس ✓ جنب الصح. كلام وإيموجي بس.</li>
                <li>دوسة على أي سؤال في القايمة تفتحه وتعدّله مكانه: ⧉ نسخة، 🗑️ امسح، ▲▼ أو اسحب ⋮⋮ عشان ترتّب. لحد 60 سؤال.</li>
                <li><b>📂 قسم من هنا</b> يحط عنوان قسم قبل السؤال («أفلام»، «أسئلة عن جدو»): في لوحة الفرق كل قسم بيبقى عمود باسمه، وفي الغرفة والجرس اسم القسم بيظهر فوق السؤال.</li>
                <li>كل حاجة بتتحفظ على الموبايل وإنت بتكتب. <b>احفظ وخد الكود</b> بيبعتها للسيرفر وبيديك كود من 6 حروف تبعته للعيلة.</li>
                <li>بعد الحفظ تختار: <b>📱 غرفة</b> (كل واحد يجاوب من موبايله، أسرع إجابة صح بتاخد أكتر)، <b>🏆 لوحة الفرق</b> (فريقين على شاشة واحدة: الأسئلة بترتيبها، 5 في كل عمود من 100 لـ 500)، أو <b>🔔 الجرس</b> (إنت بتقرا، والإجابة الصح على موبايلك إنت بس).</li>
                <li>اللي معاه الكود يفتحها من <b>عندك كود مسابقة؟</b> ويلعبها؛ التعديل عند اللي عملها بس، والباقي يقدر يعمل نسخة ليه.</li>
                <li>المسابقة اللي محدش لعبها سنة كاملة بتتمسح من السيرفر لوحدها.</li>
            </ol>`,
      wordpack: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>من <b>الأدوات ← كلماتنا</b>: اكتب مرة واحدة كلمات العيلة وأساميها وقفشاتها (لحد 300، كل واحدة لحد 40 حرف).</li>
                <li>بتظهر <b>فئة «✍️ كلماتنا»</b> في الجاسوس، الحرباء (16 كلمة على الأقل)، بدون كلام، على راسك، من أنا؟ وارسم وخمّن: على موبايل واحد وفي الغرفة.</li>
                <li><b>احفظ وخد الكود</b> وابعته للعيلة: اللي يفتحه يلاقي نفس الكلمات عنده. في الغرفة السيرفر بيجيب الكلمات بالكود.</li>
                <li>أوصف لي والمختلف مش بيستخدموها: الأولى محتاجة كلمات ممنوعة لكل كارت، والتانية محتاجة كلمتين قريبين من بعض.</li>
            </ol>`,
    },
    en: {
      quizmaker: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>From <b>Tools → Make your quiz</b> (or the Trivia card): <b>＋ New quiz</b>, name it, and for each question write it, <b>four answers</b>, and tap ✓ beside the right one. Words and emoji only.</li>
                <li>Tap any question in the list to edit it in place: ⧉ copy, 🗑️ delete, ▲▼ or drag ⋮⋮ to reorder. Up to 60 questions.</li>
                <li><b>📂 Section from here</b> puts a section heading before a question («Films», «About Grandpa»): on the team board each section is a column with its name, and in a room and on the buzzer its name shows over the question.</li>
                <li>Everything is kept on the phone as you type. <b>Save and get the code</b> sends it to the server and gives you a 6-letter code to send the family.</li>
                <li>Then pick: <b>📱 A room</b> (everyone answers on their phone, the fastest right answer scores most), <b>🏆 Team board</b> (two teams on one screen: the questions in order, 5 a column from 100 to 500) or <b>🔔 The buzzer</b> (you read; the right answer is on your phone only).</li>
                <li>Anyone with the code opens it from <b>Got a quiz code?</b> and plays it; only its author can change it, the rest can make their own copy.</li>
                <li>A quiz nobody has played for a whole year is deleted from the server by itself.</li>
            </ol>`,
      wordpack: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>From <b>Tools → Our words</b>: write the family's words, names and inside jokes once (up to 300, 40 letters each).</li>
                <li>They show as the category <b>«✍️ Our words»</b> in Imposter, Chameleon (16 words at least), Charades, Heads Up, Who Am I? and Draw & Guess: on one phone and in a room.</li>
                <li><b>Save and get the code</b> and send it to the family: whoever opens it has the same words. In a room the server fetches the words by the code.</li>
                <li>Describe It and Undercover don't use them: one needs forbidden words for every card, the other two close words.</li>
            </ol>`,
    }
  }
});
