/**
 * Wraps the compiled tailwind output in a <style> tag as Tailwind.html, which
 * Controller.html pulls in with include(). Apps Script has no static file
 * hosting, so CSS has to reach the page as an inlined include.
 */
import { readFile, writeFile, unlink } from 'node:fs/promises';

const css = await readFile(new URL('./.out.css', import.meta.url), 'utf8');
const banner =
  '<!-- GENERATED by tools/ (npm run build:css) - do not edit by hand -->\n';

await writeFile(
  new URL('../Tailwind.html', import.meta.url),
  `${banner}<style>\n${css.trim()}\n</style>\n`,
  'utf8'
);
await unlink(new URL('./.out.css', import.meta.url));

console.log(`Tailwind.html written (${(css.length / 1024).toFixed(1)} KB of CSS)`);
