/**
 * Wraps the compiled tailwind output in a <style> tag as Tailwind.html, which
 * Controller.html pulls in with include(), so the CSS is inlined into the
 * built page and arrives with it, in one file.
 */
import { readFile, writeFile, unlink } from 'node:fs/promises';
import srcMod from './sources.cjs';
const { srcPath } = srcMod;

const css = await readFile(new URL('./.out.css', import.meta.url), 'utf8');
const banner =
  '<!-- GENERATED by tools/ (npm run build:css) - do not edit by hand -->\n';

await writeFile(
  srcPath('Tailwind.html'),
  `${banner}<style>\n${css.trim()}\n</style>\n`,
  'utf8'
);
await unlink(new URL('./.out.css', import.meta.url));

console.log(`Tailwind.html written (${(css.length / 1024).toFixed(1)} KB of CSS)`);
