/* tournament: the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].<id>, as everywhere. */
gameText({
  translations: {
    ar: {
      tour_mode_label: "طريقة اللعب",
      tour_mode_stay: "اللي يكسب يفضل",
      tour_mode_tour: "بطولة",
      tour_mode_stay_hint: "اتنين بيلعبوا والباقي بيتفرج، واللي يكسب يفضل قاعد.",
      tour_mode_hint: "خروج المغلوب: القرعة بتقسمكم اتنين اتنين، وماتشات كل دور بتتلعب في نفس الوقت، واللي يكسب يطلع للدور اللي بعده لحد ما يبان البطل.",
      tour_mode_bots: "لاعيبة الكمبيوتر مش بيدخلوا البطولة.",
      tour_title_of: "بطولة {game}",
      tour_round_final: "النهائي",
      tour_round_semi: "نص النهائي",
      tour_round_quarter: "ربع النهائي",
      tour_round_16: "دور الـ16",
      tour_round_n: "الدور {n}",
      tour_bye: "عدّى على طول",
      tour_live: "مباشر",
      tour_live_now: "بيتلعب دلوقتي",
      tour_starts_in: "يبدأ بعد {n}",
      tour_replay_in: "الإعادة بعد {n}",
      tour_after_draws: "بعد {n} تعادل",
      tour_walkover: "بالانسحاب",
      tour_watch: "اتفرج",
      tour_bracket: "جدول البطولة",
      tour_your_next: "ماتشك: انت ضد {name}",
      tour_you_wait: "كسبت! مستني الفايز من {a} ضد {b}",
      tour_you_wait_one: "كسبت! مستني اللي هيلعب قصادك",
      tour_bye_wait: "عدّيت على طول! مستني الفايز من {a} ضد {b}",
      tour_bye_wait_one: "عدّيت على طول! مستني اللي هيلعب قصادك",
      tour_you_out: "خرجت من البطولة، بس لسه تقدر تتفرج على الباقيين",
      tour_out_in: "خرجت في {round}",
      tour_round_first: "الدور الأول",
      tour_watch_on: "اتفرج على:",
      tour_watch_none: "مفيش ماتش شغال دلوقتي: الماتش الجاي هيظهر هنا.",
      tour_latecomer: "البطولة شغالة: اتفرج دلوقتي، وهتلعب في البطولة الجاية",
      tour_through: "{name} طلع {round}!",
      tour_replay: "تعادل! هيلعبوا تاني و{name} يبدأ",
      tour_champion: "البطل",
      tour_runner: "الوصيف",
      tour_semi: "نص النهائي",
      tour_champ_line: "👑 {name} بطل البطولة!",
      tour_no_champ: "البطولة خلصت من غير بطل",
      tour_over: "البطولة خلصت",
      tour_matches_on: "{n} ماتشات شغالة",
      tour_more_live: "+{n} ماتشات تانية شغالة",
      tour_new: "بطولة جديدة (قرعة جديدة)",
      tour_to_stay: "ارجعوا للي يكسب يفضل",
      tour_host_next: "المضيف يختار: بطولة جديدة، ولا نرجع للي يكسب يفضل.",
      tour_points: "نقط البطولات",
      tour_points_hint: "البطل 3، الوصيف 2، وكل واحد وصل نص النهائي 1.",
      tour_host_feature: "اعرضه على التلفزيون",
      tour_tv_hint: "دوس على أي ماتش عشان يتعرض كبير.",
      tour_faces_left: "وش",
      ch_arma_short: "أرماجدون",
      ch_replay_short: "بعد إعادة",
      ch_tour_replay_next: "تعادل! إعادة بالألوان معكوسة: {name} بالأبيض",
      ch_tour_arma_next: "تعادل تاني! أرماجدون: التعادل للأسود، والأبيض بالقرعة",
    },
    en: {
      tour_mode_label: "How to play",
      tour_mode_stay: "Winner stays",
      tour_mode_tour: "Tournament",
      tour_mode_stay_hint: "Two play, the rest watch, and the winner stays on.",
      tour_mode_hint: "A knockout: the draw pairs you up, every match of a round is played at once, and each winner goes through until one champion is left.",
      tour_mode_bots: "Computer players sit a tournament out.",
      tour_title_of: "{game} tournament",
      tour_round_final: "Final",
      tour_round_semi: "Semi-finals",
      tour_round_quarter: "Quarter-finals",
      tour_round_16: "Round of 16",
      tour_round_n: "Round {n}",
      tour_bye: "Bye",
      tour_live: "Live",
      tour_live_now: "Playing now",
      tour_starts_in: "Starts in {n}",
      tour_replay_in: "Replay in {n}",
      tour_after_draws: "after {n} draw(s)",
      tour_walkover: "walkover",
      tour_watch: "Watch",
      tour_bracket: "The bracket",
      tour_your_next: "Your match: you vs {name}",
      tour_you_wait: "You won! Waiting for the winner of {a} vs {b}",
      tour_you_wait_one: "You won! Waiting for your next opponent",
      tour_bye_wait: "A bye! Waiting for the winner of {a} vs {b}",
      tour_bye_wait_one: "A bye! Waiting for your next opponent",
      tour_you_out: "You're out of the tournament, but you can watch the rest",
      tour_out_in: "You went out in: {round}",
      tour_round_first: "the first round",
      tour_watch_on: "watch:",
      tour_watch_none: "No match is on right now: the next one shows up here.",
      tour_latecomer: "A tournament is on: watch now, and play in the next one",
      tour_through: "{name} goes through to the {round}!",
      tour_replay: "A draw! Replayed, with {name} starting",
      tour_champion: "Champion",
      tour_runner: "Runner-up",
      tour_semi: "Semi-finalist",
      tour_champ_line: "👑 {name} is the champion!",
      tour_no_champ: "The tournament ended with no champion",
      tour_over: "Tournament over",
      tour_matches_on: "{n} matches on",
      tour_more_live: "+{n} more matches on",
      tour_new: "New tournament (new draw)",
      tour_to_stay: "Back to winner stays",
      tour_host_next: "The host picks: a new tournament, or back to winner stays.",
      tour_points: "Tournament points",
      tour_points_hint: "Champion 3, runner-up 2, each semi-finalist 1.",
      tour_host_feature: "Show it on the TV",
      tour_tv_hint: "Tap any match to show it big.",
      tour_faces_left: "faces",
      ch_arma_short: "Armageddon",
      ch_replay_short: "after a replay",
      ch_tour_replay_next: "A draw! Replayed with the colours swapped: {name} has White",
      ch_tour_arma_next: "Drawn again! Armageddon: a draw is Black's win, White drawn by lot",
    }
  }
});
