/* Laser (الليزر): the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].laser, as everywhere. Made by tools/new-game.mjs. */
gameText({
  translations: {
    ar: {
      setup_laser: "الليزر",
      cat_laser: "استخبى وصوّب من غير ما تشوف حد، وبعدين الكل يضرب مرة واحدة",
      laser_lobby_hint: "كل واحد يختار مكانه واتجاهه على موبايله من غير ما يشوف حد. بعدين الكل يظهر ويضرب مرة واحدة، واللي في خط ليزر يخرج. آخر واحد واقف يكسب.",
      laser_teams_label: "الفرق",
      laser_teams_off: "كل واحد لنفسه",
      laser_t2: "فريقين",
      laser_t3: "٣ فرق",
      laser_t4: "٤ فرق",
      laser_team_0: "السماوي",
      laser_team_1: "الوردي",
      laser_team_2: "الأصفر",
      laser_team_3: "الأخضر",
      laser_your_team: "فريقك",
      laser_teams_title: "الفرق",
      laser_shuffle: "🔀 خلّط الفرق",
      laser_go: "يلا نبدأ",
      laser_teams_wait: "المضيف بيظبط الفرق…",
      laser_hide_hint: "المس مكانك واسحب لاتجاهك · محدش شايفك",
      laser_ready: "جاهز ✓",
      laser_unready: "استنى، هغيّر",
      laser_ready_wait: "جاهز. مستنيين الباقيين أو الوقت…",
      laser_you: "انت",
      laser_out_watch: "خرجت. بتتفرج على الباقيين",
      laser_watch: "بتتفرج: هتلعب الجاية",
      laser_tv_hide: "استخبّوا وصوّبوا على موبايلاتكم",
      laser_show: "اظهروا!",
      laser_charge: "بيشحنوا…",
      laser_fire: "⚡ ضرب!",
      laser_out: "خرج:",
      laser_nobody: "ولا حد اتضرب!",
      laser_shrink: "الحلبة بتصغر",
      laser_tie: "كلهم خرجوا مع بعض: هم بس يكمّلوا",
      laser_next: "التالي",
      laser_won: "آخر واحد واقف",
      laser_team_won: "الفريق الكسبان",
      laser_out_in: "خرج في الجولة",
      laser_last: "فضل لحد الآخر",
      laser_left: "باقيين",
      laser_o_pickups: "🎁 الكبسولات",
      laser_o_pickups_hint: "حاجات على الأرض من الجولة التانية: اللي يقف عليها لوحده وينجى ياخدها ويستعملها بعدين",
      laser_o_pillars: "🧱 العواميد",
      laser_o_pillars_hint: "عواميد ثابتة بتوقف الليزر، ومحدش يقف فيها",
      laser_o_pieces: "🕳️ الأرض تقع حتت",
      laser_o_pieces_hint: "بدل الحلقة: بلاط بيتشقق ويقع آخر الجولة",
      laser_pk_double: "⚡ دبل",
      laser_pk_second: "🔄 شعاع تاني",
      laser_pk_shield: "🛡️ درع",
      laser_pk_wide: "🎯 عريض",
      laser_map: "الخريطة:",
      laser_map_hex: "السداسي",
      laser_map_circle: "الدايرة",
      laser_map_donut: "الدونات",
      laser_map_cross: "الصليب",
      laser_broken: "اتخانقوا عليه!",
      laser_taken: "خد:",
      laser_use: "استخدم",
      laser_using: "شغّال:",
      laser_pk_hint_second: "اسحب النقطة البنفسجي لاتجاه الشعاع التاني",
      laser_v_out: "اتضربت!",
      laser_v_hurt: "−❤ فاضلك",
      laser_v_safe: "نجيت!",
      laser_card_left: "فاضل",
      laser_card_shrunk: "الحلبة صغرت",
      laser_card_fell: "الأرض وقعت",
      laser_card_sudden: "موت مفاجئ!",
      laser_card_tie: "تعادل: هم بس يكمّلوا",
      laser_ready_lock: "جاهز 🔒",
      laser_coach_tap: "المس هنا",
      laser_coach_drag: "واسحب كده",
      laser_hiding: "بيستخبى…",
      laser_all_rank: "كل الترتيب",
      laser_replay: "⏪ إعادة · أحلى ضربة",
      laser_replay_hit: "ضرب",
      laser_replay_one: "في ضربة واحدة",
      laser_skip: "تخطّي",
      laser_floor_cracked: "البلاط المشقوق هيقع آخر الجولة",
      laser_preset_label: "طريقة اللعب",
      laser_p_classic: "كلاسيك",
      laser_p_chaos: "فوضى",
      laser_p_long: "طويلة",
      laser_more: "خيارات أكتر",
      laser_hearts_label: "❤️ القلوب",
      laser_time_label: "⏱️ وقت الاستخبا",
      laser_time_hint: "بيقل ثانية كل جولة، ومش أقل من ٨",
      laser_o_ghosts: "👻 الأشباح",
      laser_o_ghosts_hint: "اللي يخرج يحط لغم مستخبي كل جولة",
      laser_o_swap: "🔁 تبديل الأماكن",
      laser_o_swap_hint: "الشبح اللي لغمه يخرّج حد يرجع مكانه",
      laser_o_bounce: "↩️ الليزر بيرتد",
      laser_o_bounce_hint: "الليزر يخبط في الحيطة ويرتد مرة",
      laser_o_block: "🧍 الليزر يقف عند أول واحد",
      laser_o_block_hint: "اللي قدام يحمي اللي وراه",
      laser_o_sight: "👀 الفريق شايف بعضه",
      laser_o_sight_hint: "وانت مستخبي تشوف زمايلك بس",
      laser_shield: "🛡️ الدرع (مرة واحدة)",
      laser_shield_on: "🛡️ الدرع شغّال",
      laser_shield_on_hint: "الدرع شغّال: مفيش ليزر هيعدّي منك، بس مش هتضرب الجولة دي",
      laser_shield_used: "🛡️ الدرع اتستخدم",
      laser_turn_l: "لف لفة صغيرة عكس عقارب الساعة",
      laser_turn_r: "لف لفة صغيرة مع عقارب الساعة",
      laser_ghost_hint: "👻 انت شبح: المس مكان تحط فيه لغم. اللي يقف عليه يتضرب",
      laser_ghost_set: "💣 اللغم في مكانه · تقدر تحركه",
      laser_mine_clear: "شيل اللغم",
      laser_got_you: "ضربك:",
      laser_feed_title: "مين ضرب مين",
      laser_sudden: "⚠️ موت مفاجئ! الحلبة بتصغر",
      laser_back: "👻 رجع:",
      laser_lost_heart: "خسر قلب:",
      laser_hits: "ضربات",
      laser_awards: "الجوايز",
      laser_aw_sniper: "🎯 القناص",
      laser_aw_ghost: "🕊️ الشبح",
      laser_aw_close: "😮‍💨 نجا بأعجوبة",
      laser_aw_both: "💥 ضرب وخرج",
      laser_hearts_left: "قلوبك",
      laser_turret: "البرج",
      laser_turret_tv: "🗼 البرج هيضرب على الخط الأحمر",
      laser_turret_hint: "البرج هيضرب على الخط الأحمر",
      laser_o_turret: "🗼 البرج",
      laser_o_turret_hint: "برج في النص بيصوّب على خط الكل شايفه، ويضرب مع الكل",
      laser_o_mirrors: "🪞 مرايات",
      laser_o_mirrors_hint: "شوية من العواميد فضي: بتعكس الليزر بدل ما توقفه",
      laser_practice: "جولة تجربة",
      laser_pr_hint: "جولة تجربة: محدش هيخرج ولا هيخسر قلب",
      laser_pr_first: "أول لعبة: هنبدأ بجولة تجربة",
      laser_pr_skip: "نبدأ علطول",
      laser_pr_would: "كانوا هيتضربوا:",
      laser_pr_next: "الجولة الجاية بجد!",
      laser_pr_v_hit: "كنت هتتضرب!",
      laser_pr_by: "كان هيضربك",
      laser_pr_safe: "محدش كان هيضربك",
      laser_pr_mine: "انت كنت هتضرب",
      laser_pr_missed: "وليزرك ماجاش في حد",
      laser_pr_shield: "ودرعك كان شغّال",
      laser_pr_real: "بجد دلوقتي!",
    },
    en: {
      setup_laser: "Laser",
      cat_laser: "Hide and aim without seeing anyone, then everyone fires at once",
      laser_lobby_hint: "Everyone picks a spot and an aim on their phone without seeing anyone. Then everyone appears and fires at once, and whoever is in a laser's line is out. The last one standing wins.",
      laser_teams_label: "Teams",
      laser_teams_off: "Every one for themselves",
      laser_t2: "2 teams",
      laser_t3: "3 teams",
      laser_t4: "4 teams",
      laser_team_0: "Cyan",
      laser_team_1: "Pink",
      laser_team_2: "Yellow",
      laser_team_3: "Green",
      laser_your_team: "Your team",
      laser_teams_title: "The teams",
      laser_shuffle: "🔀 Shuffle the teams",
      laser_go: "Let's go",
      laser_teams_wait: "The host is setting the teams…",
      laser_hide_hint: "Touch your spot and drag to aim · nobody can see you",
      laser_ready: "Ready ✓",
      laser_unready: "Wait, I'll change",
      laser_ready_wait: "Ready. Waiting for the others or the clock…",
      laser_you: "You",
      laser_out_watch: "You're out. Watching the others",
      laser_watch: "Watching: you're in the next game",
      laser_tv_hide: "Hide and aim on your phones",
      laser_show: "Show yourselves!",
      laser_charge: "Charging…",
      laser_fire: "⚡ Fire!",
      laser_out: "Out:",
      laser_nobody: "Nobody was hit!",
      laser_shrink: "The arena shrinks",
      laser_tie: "They all went out together: only they play on",
      laser_next: "Next",
      laser_won: "Last one standing",
      laser_team_won: "The winning team",
      laser_out_in: "Out in round",
      laser_last: "Stood to the end",
      laser_left: "left",
      laser_o_pickups: "🎁 Pickups",
      laser_o_pickups_hint: "Things on the floor from round two: stand on one alone and survive to take it, then use it later",
      laser_o_pillars: "🧱 Pillars",
      laser_o_pillars_hint: "Fixed pillars that stop lasers; nobody stands in one",
      laser_o_pieces: "🕳️ Falling floor",
      laser_o_pieces_hint: "Instead of the ring: tiles crack and fall at the end of the round",
      laser_pk_double: "⚡ Double",
      laser_pk_second: "🔄 Second beam",
      laser_pk_shield: "🛡️ Shield",
      laser_pk_wide: "🎯 Wide",
      laser_map: "Map:",
      laser_map_hex: "Hexagon",
      laser_map_circle: "Circle",
      laser_map_donut: "Donut",
      laser_map_cross: "Cross",
      laser_broken: "They fought over it!",
      laser_taken: "Took:",
      laser_use: "Use",
      laser_using: "On:",
      laser_pk_hint_second: "Drag the purple dot to aim the second beam",
      laser_v_out: "You're hit!",
      laser_v_hurt: "−❤ left:",
      laser_v_safe: "Safe!",
      laser_card_left: "Left:",
      laser_card_shrunk: "The arena shrank",
      laser_card_fell: "The floor fell",
      laser_card_sudden: "Sudden death!",
      laser_card_tie: "A tie: only they play on",
      laser_ready_lock: "Ready 🔒",
      laser_coach_tap: "Touch here",
      laser_coach_drag: "and drag like this",
      laser_hiding: "hiding…",
      laser_all_rank: "The full ranking",
      laser_replay: "⏪ Replay · the best shot",
      laser_replay_hit: "hit",
      laser_replay_one: "in one shot",
      laser_skip: "Skip",
      laser_floor_cracked: "Cracked tiles fall at the end of the round",
      laser_preset_label: "Style",
      laser_p_classic: "Classic",
      laser_p_chaos: "Chaos",
      laser_p_long: "Long",
      laser_more: "More options",
      laser_hearts_label: "❤️ Hearts",
      laser_time_label: "⏱️ Hiding time",
      laser_time_hint: "One second less each round, never under 8",
      laser_o_ghosts: "👻 Ghosts",
      laser_o_ghosts_hint: "Whoever is out drops a hidden mine each round",
      laser_o_swap: "🔁 Swap places",
      laser_o_swap_hint: "A ghost whose mine takes someone out comes back in their place",
      laser_o_bounce: "↩️ Bouncing beams",
      laser_o_bounce_hint: "A beam bounces off the wall once",
      laser_o_block: "🧍 Beams stop at the first",
      laser_o_block_hint: "Whoever is in front shields whoever is behind",
      laser_o_sight: "👀 Teams see each other",
      laser_o_sight_hint: "While hiding you see your teammates only",
      laser_shield: "🛡️ Shield (once)",
      laser_shield_on: "🛡️ Shield up",
      laser_shield_on_hint: "Shield up: no laser gets through you, but you won't fire this round",
      laser_shield_used: "🛡️ Shield used",
      laser_turn_l: "Turn a little anticlockwise",
      laser_turn_r: "Turn a little clockwise",
      laser_ghost_hint: "👻 You're a ghost: touch a spot to drop a mine. Whoever stands on it is hit",
      laser_ghost_set: "💣 Mine set · you can move it",
      laser_mine_clear: "Remove the mine",
      laser_got_you: "Got you:",
      laser_feed_title: "Who hit whom",
      laser_sudden: "⚠️ Sudden death! The arena shrinks",
      laser_back: "👻 Back:",
      laser_lost_heart: "Lost a heart:",
      laser_hits: "hits",
      laser_awards: "Awards",
      laser_aw_sniper: "🎯 The sniper",
      laser_aw_ghost: "🕊️ The phantom",
      laser_aw_close: "😮‍💨 Close call",
      laser_aw_both: "💥 Took one with them",
      laser_hearts_left: "Your hearts",
      laser_turret: "The turret",
      laser_turret_tv: "🗼 The turret fires along the red line",
      laser_turret_hint: "the turret fires along the red line",
      laser_o_turret: "🗼 Turret",
      laser_o_turret_hint: "A turret in the middle aims along a line everyone sees, and fires with everyone",
      laser_o_mirrors: "🪞 Mirrors",
      laser_o_mirrors_hint: "Some pillars are silver: they reflect a laser instead of stopping it",
      laser_practice: "Practice round",
      laser_pr_hint: "Practice round: nobody goes out or loses a heart",
      laser_pr_first: "First game: we start with a practice round",
      laser_pr_skip: "Start for real now",
      laser_pr_would: "Would have been hit:",
      laser_pr_next: "The next round is for real!",
      laser_pr_v_hit: "You'd have been hit!",
      laser_pr_by: "Would have hit you:",
      laser_pr_safe: "Nobody would have hit you",
      laser_pr_mine: "You'd have hit",
      laser_pr_missed: "your laser missed everyone",
      laser_pr_shield: "your shield was up",
      laser_pr_real: "For real now!",
    }
  },
  rules: {
    ar: {
      laser: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>كل جولة: المس مكانك على الحلبة واسحب لاتجاهك (أو ⟲ ⟳ للظبط). محدش شايف حد. الوقت بيقل ثانية كل جولة.</li>
                <li>بعدين الكل يظهر و<b>الكل يضرب مرة واحدة</b>. الليزر بيعدّي من كل اللي في خطه، واللي يتضرب يخسر قلب، ولو مالوش قلوب يخرج.</li>
                <li><b>🛡️ الدرع</b> مرة واحدة في اللعبة: بيوقف أي ليزر، بس مش هتضرب الجولة دي.</li>
                <li><b>👻 الأشباح</b>: اللي خرج يحط لغم مستخبي كل جولة، واللي يقف عليه يتضرب.</li>
                <li>الحلبة بتصغر كل جولة، ولو عدّت جولتين من غير ما حد يتضرب: <b>موت مفاجئ</b>، تصغر أكتر.</li>
                <li>آخر واحد واقف يكسب. لو اللي فاضلين خرجوا كلهم مع بعض، هم بس يكمّلوا. في نفس الجولة، اللي ضرب أكتر يتقدّم.</li>
                <li>بالفرق: الليزر واللغم بيعدّوا من زميلك من غير ما يأذوه، وآخر فريق فيه حد واقف يكسب.</li>
                <li><b>🎁 الكبسولات</b> (من الجولة التانية): اللي يقف على كبسولة لوحده وينجى ياخدها، ويستعملها في جولة بعدها (⚡ دبل قدام وورا، 🔄 شعاع تاني، 🛡️ درع، 🎯 ليزر عريض). اتنين عليها؟ بتتكسر.</li>
                <li>كل لعبة بخريطة: سداسي، دايرة، دونات (الحفرة اللي في النص بتوقف الليزر)، أو صليب. <b>🧱 العواميد</b> بتوقف الليزر، و<b>🕳️ الأرض تقع حتت</b> بدل الحلقة: البلاط المشقوق بيقع آخر الجولة.</li>
                <li><b>🪞 مرايات</b> (مع العواميد): العمود الفضي بيعكس الليزر بدل ما يوقفه، فضربة شاطرة تلف حوالين ركن.</li>
                <li><b>🗼 البرج</b>: برج في نص الحلبة، اتجاهه باين للكل وانتوا مستخبيين (الخط الأحمر)، ويضرب عليه مع الكل. اتجاه جديد كل جولة.</li>
                <li>أول لعبة ليزر في الغرفة بتبدأ بـ<b>جولة تجربة</b>: الكل يستخبى ويضرب، بس محدش بيخرج ولا بيخسر قلب، وكل موبايل يقول حصل له إيه. المضيف يقدر يدوس «نبدأ علطول».</li>
            </ol>`,
    },
    en: {
      laser: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>Each round: touch your spot on the arena and drag to aim (or ⟲ ⟳ to fine-tune). Nobody sees anyone. The clock is a second shorter each round.</li>
                <li>Then everyone appears and <b>everyone fires at once</b>. A laser goes through everyone in its line; whoever is hit loses a heart, and with none left is out.</li>
                <li><b>🛡️ The shield</b>, once a game: it stops every laser, but you don't fire that round.</li>
                <li><b>👻 Ghosts</b>: whoever is out drops a hidden mine each round; whoever stands on it is hit.</li>
                <li>The arena shrinks every round; after two rounds with nobody hit, <b>sudden death</b> shrinks it further.</li>
                <li>The last one standing wins. If the last ones all go out together, only they play on. Among those out in the same round, more hits ranks higher.</li>
                <li>In teams: lasers and mines pass your teammates harmlessly, and the last team with anyone standing wins.</li>
                <li><b>🎁 Pickups</b> (from round two): stand on one alone and survive to take it, then use it in a later round (⚡ double, forward and back; 🔄 a second beam; 🛡️ a shield; 🎯 a wide laser). Two on one? It breaks.</li>
                <li>Every game has a map: a hexagon, a circle, a donut (its hole stops lasers) or a cross. <b>🧱 Pillars</b> stop lasers, and <b>🕳️ Falling floor</b> replaces the ring: cracked tiles fall at the end of the round.</li>
                <li><b>🪞 Mirrors</b> (with pillars): a silver pillar reflects a laser instead of stopping it, so a clever shot goes round a corner.</li>
                <li><b>🗼 The turret</b>: a turret in the middle of the arena; everyone sees its aim while hiding (the red line), and it fires along it with everyone. A new aim every round.</li>
                <li>A room's first laser game starts with a <b>practice round</b>: everyone hides and fires, but nobody goes out or loses a heart, and each phone says what happened to it. The host can press «Start for real now».</li>
            </ol>`,
    }
  }
});
