/* Laser (الليزر): the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].laser, as everywhere. Made by tools/new-game.mjs. */
gameText({
  translations: {
    ar: {
      setup_laser: "الليزر",
      cat_laser: "استخبى وصوّب من غير ما تشوف حد، وبعدين الكل يضرب مرة واحدة",
      laser_lobby_hint: "كل واحد يختار مكانه واتجاهه على موبايله من غير ما يشوف حد. بعدين الكل يظهر ويضرب مرة واحدة، واللي في خط ليزر يخرج. آخر واحد واقف يكسب.",
      laser_teams_label: "الفرق",
      laser_teams_off: "كل واحد لنفسه",
      laser_t2: "فريقين",
      laser_t3: "٣ فرق",
      laser_t4: "٤ فرق",
      laser_team_0: "السماوي",
      laser_team_1: "الوردي",
      laser_team_2: "الأصفر",
      laser_team_3: "الأخضر",
      laser_your_team: "فريقك",
      laser_teams_title: "الفرق",
      laser_shuffle: "🔀 خلّط الفرق",
      laser_go: "يلا نبدأ",
      laser_teams_wait: "المضيف بيظبط الفرق…",
      laser_hide_hint: "المس مكانك واسحب لاتجاهك · محدش شايفك",
      laser_ready: "جاهز ✓",
      laser_unready: "استنى، هغيّر",
      laser_ready_wait: "جاهز. مستنيين الباقيين أو الوقت…",
      laser_you: "انت",
      laser_out_watch: "خرجت. بتتفرج على الباقيين",
      laser_watch: "بتتفرج: هتلعب الجاية",
      laser_tv_hide: "استخبّوا وصوّبوا على موبايلاتكم",
      laser_show: "اظهروا!",
      laser_charge: "بيشحنوا…",
      laser_fire: "⚡ ضرب!",
      laser_out: "خرج:",
      laser_nobody: "ولا حد اتضرب!",
      laser_shrink: "الحلبة بتصغر",
      laser_tie: "كلهم خرجوا مع بعض: هم بس يكمّلوا",
      laser_next: "التالي",
      laser_won: "آخر واحد واقف",
      laser_team_won: "الفريق الكسبان",
      laser_out_in: "خرج في الجولة",
      laser_last: "فضل لحد الآخر",
      laser_left: "باقيين",
      laser_preset_label: "طريقة اللعب",
      laser_p_classic: "كلاسيك",
      laser_p_chaos: "فوضى",
      laser_p_long: "طويلة",
      laser_more: "خيارات أكتر",
      laser_hearts_label: "❤️ القلوب",
      laser_time_label: "⏱️ وقت الاستخبا",
      laser_time_hint: "بيقل ثانية كل جولة، ومش أقل من ٨",
      laser_o_ghosts: "👻 الأشباح",
      laser_o_ghosts_hint: "اللي يخرج يحط لغم مستخبي كل جولة",
      laser_o_swap: "🔁 تبديل الأماكن",
      laser_o_swap_hint: "الشبح اللي لغمه يخرّج حد يرجع مكانه",
      laser_o_bounce: "↩️ الليزر بيرتد",
      laser_o_bounce_hint: "الليزر يخبط في الحيطة ويرتد مرة",
      laser_o_block: "🧍 الليزر يقف عند أول واحد",
      laser_o_block_hint: "اللي قدام يحمي اللي وراه",
      laser_o_sight: "👀 الفريق شايف بعضه",
      laser_o_sight_hint: "وانت مستخبي تشوف زمايلك بس",
      laser_shield: "🛡️ الدرع (مرة واحدة)",
      laser_shield_on: "🛡️ الدرع شغّال",
      laser_shield_on_hint: "الدرع شغّال: مفيش ليزر هيعدّي منك، بس مش هتضرب الجولة دي",
      laser_shield_used: "🛡️ الدرع اتستخدم",
      laser_turn_l: "لف لفة صغيرة عكس عقارب الساعة",
      laser_turn_r: "لف لفة صغيرة مع عقارب الساعة",
      laser_ghost_hint: "👻 انت شبح: المس مكان تحط فيه لغم. اللي يقف عليه يتضرب",
      laser_ghost_set: "💣 اللغم في مكانه · تقدر تحركه",
      laser_mine_clear: "شيل اللغم",
      laser_got_you: "ضربك:",
      laser_feed_title: "مين ضرب مين",
      laser_sudden: "⚠️ موت مفاجئ! الحلبة بتصغر",
      laser_back: "👻 رجع:",
      laser_lost_heart: "خسر قلب:",
      laser_hits: "ضربات",
      laser_awards: "الجوايز",
      laser_aw_sniper: "🎯 القناص",
      laser_aw_ghost: "🕊️ الشبح",
      laser_aw_close: "😮‍💨 نجا بأعجوبة",
      laser_aw_both: "💥 ضرب وخرج",
      laser_hearts_left: "قلوبك",
    },
    en: {
      setup_laser: "Laser",
      cat_laser: "Hide and aim without seeing anyone, then everyone fires at once",
      laser_lobby_hint: "Everyone picks a spot and an aim on their phone without seeing anyone. Then everyone appears and fires at once, and whoever is in a laser's line is out. The last one standing wins.",
      laser_teams_label: "Teams",
      laser_teams_off: "Every one for themselves",
      laser_t2: "2 teams",
      laser_t3: "3 teams",
      laser_t4: "4 teams",
      laser_team_0: "Cyan",
      laser_team_1: "Pink",
      laser_team_2: "Yellow",
      laser_team_3: "Green",
      laser_your_team: "Your team",
      laser_teams_title: "The teams",
      laser_shuffle: "🔀 Shuffle the teams",
      laser_go: "Let's go",
      laser_teams_wait: "The host is setting the teams…",
      laser_hide_hint: "Touch your spot and drag to aim · nobody can see you",
      laser_ready: "Ready ✓",
      laser_unready: "Wait, I'll change",
      laser_ready_wait: "Ready. Waiting for the others or the clock…",
      laser_you: "You",
      laser_out_watch: "You're out. Watching the others",
      laser_watch: "Watching: you're in the next game",
      laser_tv_hide: "Hide and aim on your phones",
      laser_show: "Show yourselves!",
      laser_charge: "Charging…",
      laser_fire: "⚡ Fire!",
      laser_out: "Out:",
      laser_nobody: "Nobody was hit!",
      laser_shrink: "The arena shrinks",
      laser_tie: "They all went out together: only they play on",
      laser_next: "Next",
      laser_won: "Last one standing",
      laser_team_won: "The winning team",
      laser_out_in: "Out in round",
      laser_last: "Stood to the end",
      laser_left: "left",
      laser_preset_label: "Style",
      laser_p_classic: "Classic",
      laser_p_chaos: "Chaos",
      laser_p_long: "Long",
      laser_more: "More options",
      laser_hearts_label: "❤️ Hearts",
      laser_time_label: "⏱️ Hiding time",
      laser_time_hint: "One second less each round, never under 8",
      laser_o_ghosts: "👻 Ghosts",
      laser_o_ghosts_hint: "Whoever is out drops a hidden mine each round",
      laser_o_swap: "🔁 Swap places",
      laser_o_swap_hint: "A ghost whose mine takes someone out comes back in their place",
      laser_o_bounce: "↩️ Bouncing beams",
      laser_o_bounce_hint: "A beam bounces off the wall once",
      laser_o_block: "🧍 Beams stop at the first",
      laser_o_block_hint: "Whoever is in front shields whoever is behind",
      laser_o_sight: "👀 Teams see each other",
      laser_o_sight_hint: "While hiding you see your teammates only",
      laser_shield: "🛡️ Shield (once)",
      laser_shield_on: "🛡️ Shield up",
      laser_shield_on_hint: "Shield up: no laser gets through you, but you won't fire this round",
      laser_shield_used: "🛡️ Shield used",
      laser_turn_l: "Turn a little anticlockwise",
      laser_turn_r: "Turn a little clockwise",
      laser_ghost_hint: "👻 You're a ghost: touch a spot to drop a mine. Whoever stands on it is hit",
      laser_ghost_set: "💣 Mine set · you can move it",
      laser_mine_clear: "Remove the mine",
      laser_got_you: "Got you:",
      laser_feed_title: "Who hit whom",
      laser_sudden: "⚠️ Sudden death! The arena shrinks",
      laser_back: "👻 Back:",
      laser_lost_heart: "Lost a heart:",
      laser_hits: "hits",
      laser_awards: "Awards",
      laser_aw_sniper: "🎯 The sniper",
      laser_aw_ghost: "🕊️ The phantom",
      laser_aw_close: "😮‍💨 Close call",
      laser_aw_both: "💥 Took one with them",
      laser_hearts_left: "Your hearts",
    }
  },
  rules: {
    ar: {
      laser: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>كل جولة: المس مكانك على الحلبة واسحب لاتجاهك (أو ⟲ ⟳ للظبط). محدش شايف حد. الوقت بيقل ثانية كل جولة.</li>
                <li>بعدين الكل يظهر و<b>الكل يضرب مرة واحدة</b>. الليزر بيعدّي من كل اللي في خطه، واللي يتضرب يخسر قلب، ولو مالوش قلوب يخرج.</li>
                <li><b>🛡️ الدرع</b> مرة واحدة في اللعبة: بيوقف أي ليزر، بس مش هتضرب الجولة دي.</li>
                <li><b>👻 الأشباح</b>: اللي خرج يحط لغم مستخبي كل جولة، واللي يقف عليه يتضرب.</li>
                <li>الحلبة بتصغر كل جولة، ولو عدّت جولتين من غير ما حد يتضرب: <b>موت مفاجئ</b>، تصغر أكتر.</li>
                <li>آخر واحد واقف يكسب. لو اللي فاضلين خرجوا كلهم مع بعض، هم بس يكمّلوا. في نفس الجولة، اللي ضرب أكتر يتقدّم.</li>
                <li>بالفرق: الليزر واللغم بيعدّوا من زميلك من غير ما يأذوه، وآخر فريق فيه حد واقف يكسب.</li>
            </ol>`,
    },
    en: {
      laser: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li>Each round: touch your spot on the arena and drag to aim (or ⟲ ⟳ to fine-tune). Nobody sees anyone. The clock is a second shorter each round.</li>
                <li>Then everyone appears and <b>everyone fires at once</b>. A laser goes through everyone in its line; whoever is hit loses a heart, and with none left is out.</li>
                <li><b>🛡️ The shield</b>, once a game: it stops every laser, but you don't fire that round.</li>
                <li><b>👻 Ghosts</b>: whoever is out drops a hidden mine each round; whoever stands on it is hit.</li>
                <li>The arena shrinks every round; after two rounds with nobody hit, <b>sudden death</b> shrinks it further.</li>
                <li>The last one standing wins. If the last ones all go out together, only they play on. Among those out in the same round, more hits ranks higher.</li>
                <li>In teams: lasers and mines pass your teammates harmlessly, and the last team with anyone standing wins.</li>
            </ol>`,
    }
  }
});
