/* crew: the words only this game's screens show, and its rules (Help, the
   first-play card). The build puts them into TRANSLATIONS and GAME_RULES (tools/game-text.cjs):
   read them as t.<key> and GAME_RULES[lang].<id>, as everywhere. */
gameText({
  translations: {
    ar: {
      crew_brand: "عشري · كارنيه عضوية",
      crew_door_sub: "جدول شهري لعيلتك أو صحابك: مين كسب ليالي أكتر، وبطل كل شهر",
      crew_door_have: "الجدول والأبطال والألقاب",
      crew_create: "اعمل شلة",
      crew_join: "ادخل شلة بكود",
      crew_add: "شلة تانية",
      crew_empty_title: "الشلة: الدوري بتاعكم",
      crew_empty_text: "كل سهرة بتلعبوها في غرفة للشلة بتتحسب: اللي يكسب ليالي أكتر في الشهر هو البطل، وليه مكان على حيطة الأبطال.",
      crew_create_sub: "اسم للشلة، واسمك فيها. الكود بيتعمل لوحده وتبعته للباقيين.",
      crew_name_label: "اسم الشلة",
      crew_name_ph: "مثلاً: شلة بيت الشناوي",
      crew_me_label: "اسمك في الشلة",
      crew_create_go: "اعمل الشلة",
      crew_made: "اتعملت شلة «{name}» 🎉",
      crew_join_sub: "اكتب كود الشلة أو الصق اللينك",
      crew_next: "التالي",
      crew_who: "إنت مين فيهم؟",
      crew_im_new: "أنا جديد، ضيفني",
      crew_join_go: "ضيفني للشلة",
      crew_welcome: "أهلاً بيك في «{name}» 🎉",
      crew_code: "كود الشلة",
      crew_invite: "ادعي",
      crew_invite_title: "ادعي حد لـ «{name}»",
      crew_invite_sub: "يمسح الكود، أو ابعتله اللينك، أو يكتب الكود من «ادخل شلة بكود»",
      crew_share: "ابعت لينك الشلة",
      crew_share_text: "تعالى شلتنا «{name}» على عشرى جيمينج، الكود {code}",
      crew_members: "الأعضاء",
      crew_members_title: "الأعضاء ({n})",
      crew_members_sub: "اللي ماسك الشلة بيعدّل الأسامي ويطلّع حد. إنت تقدر تخرج.",
      crew_members_mgr: "إنت ماسك الشلة: ✏️ تصلّح اسم، 👑 تسلّم الشلة لحد، ✕ تطلّع حد",
      crew_manager: "ماسك الشلة",
      crew_you: "إنت",
      crew_rename: "غيّر اسم الشلة",
      crew_rename_member: "صلّح الاسم",
      crew_hand_over: "سلّمه الشلة",
      crew_hand_over_q: "تسلّم الشلة لـ «{name}»؟ هيبقى هو اللي بيعدّل الأسامي ويطلّع حد.",
      crew_remove: "طلّعه من الشلة",
      crew_remove_q: "تطلّع «{name}» من الشلة؟ مش هيبقى في الجدول.",
      crew_leave: "اخرج من الشلة",
      crew_leave_q: "تخرج من «{name}»؟ هتطلع من الجدول، وترجع بالكود لو حبيت.",
      crew_left: "خرجت من الشلة",
      crew_left_phone: "الموبايل ده خرج من الشلة",
      crew_pair_add: "ضيف موبايلك التاني",
      crew_pair_title: "موبايلك التاني",
      crew_pair_sub: "على موبايلك التاني: ادخل الشلة واختار اسمك، وبعدين من «الأعضاء» اكتب الكود ده. شغّال ١٠ دقايق.",
      crew_pair_here: "إنت ماسك الشلة؟ اكتب الكود اللي هيطلع على موبايلك الأول («ضيف موبايلك التاني») عشان تمسكها من هنا كمان.",
      crew_pair_ph: "الكود (٦ أرقام)",
      crew_pair_ok: "الموبايل ده بقى ماسك الشلة",
      crew_open_room: "افتح غرفة",
      crew_tab_month: "الشهر",
      crew_tab_champs: "الأبطال",
      crew_tab_titles: "الألقاب",
      crew_tab_nights: "السهرات",
      crew_season: "موسم {month} · اليوم {day} من {of}",
      crew_nights_1: "ليلة واحدة",
      crew_nights_n: "{n} ليالي",
      crew_points_n: "{n} نقطة",
      crew_col_nights: "ليالي",
      crew_col_points: "نقطة",
      crew_month_empty: "لسه مفيش سهرات الشهر ده. افتحوا غرفة للشلة والعبوا، وكل سهرة هتتحسب.",
      crew_month_nowin: "فيه سهرات الشهر ده، بس كسبها ضيوف. العبوا تاني!",
      crew_month_hint: "الترتيب بالليالي اللي كسبتها، والتعادل بالنقط. الجدول بيبدأ من جديد أول كل شهر.",
      crew_peek_none: "لسه",
      crew_peek_last: "آخرها {day}",
      crew_champs_empty: "أول بطل هيتعلّق هنا أول الشهر الجاي.",
      crew_titles_empty: "الألقاب بتتوزع من اللعب نفسه: أسرع إيد، ملك الكدب، المحقق كونان… العبوا وهتظهر.",
      crew_records: "الأرقام القياسية",
      crew_records_empty: "الأرقام القياسية بتظهر بعد أول سهرة.",
      crew_nights_empty: "لسه مفيش سهرات. افتحوا غرفة للشلة وأي لعبة بنقط هتتحسب.",
      crew_guest: "ضيف",
      crew_t_fast: "أسرع إيد",
      crew_t_liar: "ملك الكدب",
      crew_t_detective: "المحقق كونان",
      crew_t_oracle: "العرّاف",
      crew_t_cards: "ملك الورق",
      crew_t_brain: "العقل المدبر",
      crew_t_words: "أستاذ الكلام",
      crew_t_sport: "البطل الرياضي",
      crew_t_luck: "صاحب الحظ",
      crew_tw_fast: "كسب {n} في الجرس والكراسي والسرعة",
      crew_tw_liar: "ضحك على الشلة {n} مرة",
      crew_tw_detective: "كشف اللعبة {n} مرة في ألعاب الجاسوس",
      crew_tw_oracle: "توقّع الكسبان صح {n} مرة",
      crew_tw_cards: "كسب {n} في الورق والدومينو",
      crew_tw_brain: "كسب {n} في الشطرنج والألغاز",
      crew_tw_words: "كسب {n} في ألعاب الكلام والأسئلة",
      crew_tw_sport: "كسب {n} في البولينج والجولف",
      crew_tw_luck: "كسب {n} في لودو والسلم وبنك الحظ",
      crew_r_best_bowling: "أعلى بولينج",
      crew_r_best_trivia: "أعلى نقط في تحدي المعلومات",
      crew_r_night_points: "أكتر نقط في سهرة",
      crew_r_night_games: "أكتر ألعاب كسبها في سهرة",
      crew_r_streak: "أطول سلسلة ليالي ورا بعض",
      crew_r_month_nights: "أكتر ليالي في شهر",
      crew_room_ask: "السهرة دي للشلة؟",
      crew_room_for: "السهرة دي محسوبة لـ «{name}»",
      crew_crown_title: "بطل الشلة",
      crew_crown_moved: "👑 التاج اتنقل!",
      crew_crown_to: "{name} عدّى {from} الليلة",
      crew_room_pick: "السهرة دي لأنهي شلة؟",
      crew_room_pick_sub: "كل لعبة بنقط هتتحسب في جدول الشلة، والضيوف بيلعبوا عادي",
      crew_room_none: "مش للشلة",
      crew_join_this: "انضم للشلة",
      crew_offer: "عجبتك السهرة؟ انضم لـ «{name}» وخلي لياليك تتحسب",
      crew_err_net: "مش قادرين نوصل للسيرفر، جرّب تاني",
      crew_packs_title: "مسابقاتنا وكلماتنا",
      crew_packs_add: "ضيف",
      crew_packs_add_title: "ضيف للشلة",
      crew_packs_add_sub: "المسابقات والكلمات اللي على موبايلك وليها كود",
      crew_packs_none_here: "مفيش مسابقة ولا كلمات على موبايلك ليها كود لسه. اعمل واحدة واحفظها.",
      crew_packs_make: "اعمل مسابقتك",
      crew_pack_remove: "شيل «{t}» من الشلة",
      crew_pack_remove_q: "تشيل «{t}» من الشلة؟ الكود نفسه هيفضل شغّال.",
      crew_pack_removed: "اتشالت من الشلة",
      crew_pack_add_btn: "ضيفها للشلة",
      crew_pack_in: "موجودة في الشلة",
      crew_pack_in_all: "موجودة في شللك كلها",
      crew_pack_added: "اتضافت لـ «{name}» - كل الشلة تشوفها دلوقتي",
      crew_pack_pick: "تضيفها لأنهي شلة؟",
      crew_words_where: "كلمات الشلة: بتظهر فئة «{t}» في ألعاب الكلمات (الجاسوس، الحرباء، بدون كلام، على راسك، من أنا؟، ارسم وخمّن)",
      crew_prog_badge: "برنامج السهرة",
      crew_prog_champ: "👑 بطل البرنامج: {name}",
      crew_err_code: "الكود 6 حروف إنجليزي، زي ABCDEF",
      crew_err_notfound: "مفيش شلة بالكود ده",
      crew_err_name: "اكتب اسم الشلة",
      crew_err_me: "اكتب اسمك",
      crew_err_taken: "«{name}» موجود في الشلة: لو ده إنت دوس على اسمك فوق",
      crew_err_gone: "الشلة دي اتقفلت",
      crew_err_out: "إنت مبقتش في الشلة دي",
    },
    en: {
      crew_brand: "Ashry · membership card",
      crew_door_sub: "A monthly table for your family or friends: who wins most nights, and each month's champion",
      crew_door_have: "The table, the champions, the titles",
      crew_create: "Start a crew",
      crew_join: "Join with a code",
      crew_add: "Another crew",
      crew_empty_title: "The crew: your own league",
      crew_empty_text: "Every night you play in a room for the crew counts: whoever wins the most nights in a month is the champion, with a place on the wall of champions.",
      crew_create_sub: "A name for the crew and your name in it. The code is made for you to send to the others.",
      crew_name_label: "The crew's name",
      crew_name_ph: "e.g. The Shenawy house",
      crew_me_label: "Your name in the crew",
      crew_create_go: "Start the crew",
      crew_made: "“{name}” is started 🎉",
      crew_join_sub: "Type the crew's code or paste the link",
      crew_next: "Next",
      crew_who: "Which one are you?",
      crew_im_new: "I'm new, add me",
      crew_join_go: "Add me to the crew",
      crew_welcome: "Welcome to “{name}” 🎉",
      crew_code: "Crew code",
      crew_invite: "Invite",
      crew_invite_title: "Invite someone to “{name}”",
      crew_invite_sub: "They scan the code, open the link you send, or type the code under «Join with a code»",
      crew_share: "Send the crew's link",
      crew_share_text: "Join our crew “{name}” on Ashry Gaming, code {code}",
      crew_members: "Members",
      crew_members_title: "Members ({n})",
      crew_members_sub: "Whoever runs the crew fixes names and takes someone out. You can leave.",
      crew_members_mgr: "You run the crew: ✏️ fix a name, 👑 hand the crew over, ✕ take someone out",
      crew_manager: "Runs the crew",
      crew_you: "You",
      crew_rename: "Rename the crew",
      crew_rename_member: "Fix the name",
      crew_hand_over: "Hand the crew over",
      crew_hand_over_q: "Hand the crew to “{name}”? They will fix names and take people out.",
      crew_remove: "Take out of the crew",
      crew_remove_q: "Take “{name}” out of the crew? They leave the table.",
      crew_leave: "Leave the crew",
      crew_leave_q: "Leave “{name}”? You leave the table; the code brings you back.",
      crew_left: "You left the crew",
      crew_left_phone: "This phone left the crew",
      crew_pair_add: "Add your other phone",
      crew_pair_title: "Your other phone",
      crew_pair_sub: "On your other phone: open the crew and pick your name, then type this code under Members. It works for 10 minutes.",
      crew_pair_here: "Do you run the crew? Type the code your first phone shows (“Add your other phone”) to run it from here too.",
      crew_pair_ph: "The code (6 digits)",
      crew_pair_ok: "This phone runs the crew now",
      crew_open_room: "Open a room",
      crew_tab_month: "Month",
      crew_tab_champs: "Champions",
      crew_tab_titles: "Titles",
      crew_tab_nights: "Nights",
      crew_season: "{month} season · day {day} of {of}",
      crew_nights_1: "{n} night",
      crew_nights_n: "{n} nights",
      crew_points_n: "{n} pts",
      crew_col_nights: "nights",
      crew_col_points: "pts",
      crew_month_empty: "No nights yet this month. Open a room for the crew and play: every night counts.",
      crew_month_nowin: "There were nights this month, but guests won them. Play again!",
      crew_month_hint: "Ranked by nights won, then points. The table starts again on the 1st of every month.",
      crew_peek_none: "Not yet",
      crew_peek_last: "Last: {day}",
      crew_champs_empty: "The first champion goes up here at the start of next month.",
      crew_titles_empty: "Titles come from playing: fastest hand, king of lies, the detective… play and they show up.",
      crew_records: "Records",
      crew_records_empty: "Records show up after the first night.",
      crew_nights_empty: "No nights yet. Open a room for the crew; any game with points counts.",
      crew_guest: "guest",
      crew_t_fast: "Fastest hand",
      crew_t_liar: "King of lies",
      crew_t_detective: "The detective",
      crew_t_oracle: "The oracle",
      crew_t_cards: "King of cards",
      crew_t_brain: "The mastermind",
      crew_t_words: "Word wizard",
      crew_t_sport: "The athlete",
      crew_t_luck: "Lady luck",
      crew_tw_fast: "Won {n} in the buzzer, the chairs and the quick games",
      crew_tw_liar: "Fooled the crew {n} times",
      crew_tw_detective: "Cracked it {n} times in the spy games",
      crew_tw_oracle: "Called the winner {n} times",
      crew_tw_cards: "Won {n} at cards and dominoes",
      crew_tw_brain: "Won {n} at chess and puzzles",
      crew_tw_words: "Won {n} at word and quiz games",
      crew_tw_sport: "Won {n} at bowling and golf",
      crew_tw_luck: "Won {n} at Ludo, Snakes and the bank",
      crew_r_best_bowling: "Best bowling score",
      crew_r_best_trivia: "Best trivia score",
      crew_r_night_points: "Most points in a night",
      crew_r_night_games: "Most games won in a night",
      crew_r_streak: "Longest run of nights won",
      crew_r_month_nights: "Most nights in a month",
      crew_room_ask: "Is tonight for the crew?",
      crew_room_for: "Tonight counts for “{name}”",
      crew_crown_title: "The crew's champion",
      crew_crown_moved: "👑 The crown moved!",
      crew_crown_to: "{name} got past {from} tonight",
      crew_room_pick: "Which crew is tonight for?",
      crew_room_pick_sub: "Every game with points counts on the crew's table; guests play as usual",
      crew_room_none: "Not for a crew",
      crew_join_this: "Join the crew",
      crew_offer: "Enjoyed tonight? Join “{name}” and your nights will count",
      crew_err_net: "Can't reach the server - try again",
      crew_packs_title: "Our quizzes & words",
      crew_packs_add: "Add",
      crew_packs_add_title: "Add to the crew",
      crew_packs_add_sub: "The quizzes and words on your phone that have a code",
      crew_packs_none_here: "No quiz or words with a code on your phone yet. Make one and save it.",
      crew_packs_make: "Make your quiz",
      crew_pack_remove: "Take «{t}» off the crew",
      crew_pack_remove_q: "Take «{t}» off the crew? Its code keeps working.",
      crew_pack_removed: "Taken off the crew",
      crew_pack_add_btn: "Add to the crew",
      crew_pack_in: "In the crew",
      crew_pack_in_all: "In all your crews",
      crew_pack_added: "Added to «{name}» - the whole crew sees it now",
      crew_pack_pick: "Add it to which crew?",
      crew_words_where: "The crew's words: a «{t}» category in the word games (Spy, Chameleon, Charades, Heads Up, Who Am I?, Draw & Guess)",
      crew_prog_badge: "The night's program",
      crew_prog_champ: "👑 Program champion: {name}",
      crew_err_code: "The code is 6 letters, like ABCDEF",
      crew_err_notfound: "No crew has that code",
      crew_err_name: "Type the crew's name",
      crew_err_me: "Type your name",
      crew_err_taken: "“{name}” is in the crew already: if that's you, tap your name above",
      crew_err_gone: "That crew has closed",
      crew_err_out: "You're no longer in that crew",
    }
  },
  rules: {
    ar: {
      crew: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li><b>اعمل شلة</b> من «مع بعض» أو الإعدادات: اسم للشلة واسمك. بيتعمل كود من 6 حروف.</li>
                <li>ابعت اللينك أو خلّيهم يمسحوا الكود. كل واحد يختار اسمه من «إنت مين فيهم؟» أو «أنا جديد»، وأسامي الشلة كلها بتتحفظ على موبايله.</li>
                <li>افتحوا غرفة: الموبايل اللي في شلة بيفتحها للشلة اللي استخدمها آخر مرة، والمضيف يغيّرها من «السهرة دي للشلة؟» في الغرفة.</li>
                <li>كل لعبة بنقط في السهرة بتدي 3 و2 و1 للأول والتاني والتالت، واللي يجمع أكتر نقط يكسب الليلة. الألعاب على موبايل واحد مش بتتحسب.</li>
            </ol>
            <p class="help-sub">🏆 الجدول والأبطال</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>الموسم شهر: الترتيب بالليالي اللي كسبتها، والتعادل بالنقط. أول كل شهر الجدول بيبدأ من جديد، وبطل الشهر بيتعلّق على حيطة الأبطال.</li>
                <li>الضيوف بيلعبوا عادي ونتايجهم بتتحسب في السهرة، بس مش في الجدول. في آخر السهرة الغرفة بتعرض عليهم «انضم للشلة».</li>
            </ul>
            <p class="help-sub">🏷️ الألقاب والأرقام</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>ألقاب الشهر من اللعب نفسه: أسرع إيد (الجرس والكراسي)، ملك الكدب (كدّاب وكذبة وصدقة)، المحقق كونان (ألعاب الجاسوس)، العرّاف (توقعات «مين هيكسب؟») وغيرهم. اللقب لواحد لوحده في الأول، ومن مرتين.</li>
                <li>الأرقام القياسية: أعلى بولينج، أكتر نقط في سهرة، أطول سلسلة ليالي…</li>
            </ul>
            <p class="help-sub">👑 اللي ماسك الشلة</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>اللي عمل الشلة بيغيّر اسمها، يصلّح اسم حد، يطلّع حد، أو يسلّم الشلة لحد تاني. الباقيين يقدروا يخرجوا بس.</li>
                <li>من غير حسابات ولا باسوردات: الكود هو اللي بيدخّل. الشلة اللي محدش يلعب فيها سنة بتتمسح لوحدها.</li>
            </ul>`,
    },
    en: {
      crew: `
            <ol class="list-decimal list-inside space-y-1 text-xs">
                <li><b>Start a crew</b> from «Together» or Settings: a name for the crew and yours. A 6-letter code is made.</li>
                <li>Send the link or let them scan the code. Each one picks their name under «Which one are you?» or «I'm new», and every name in the crew is saved on their phone.</li>
                <li>Open a room: a phone in a crew opens it for the crew it used last, and the host changes it under «Is tonight for the crew?» in the room.</li>
                <li>Every game with points gives 3, 2 and 1 to the first three, and the most points wins the night. Games on one phone don't count.</li>
            </ol>
            <p class="help-sub">🏆 The table and the champions</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>A season is a month: ranked by nights won, then points. On the 1st the table starts again, and the month's champion goes up on the wall of champions.</li>
                <li>Guests play as usual and count on the night, but not on the table. At the end of the night the room offers them «Join the crew».</li>
            </ul>
            <p class="help-sub">🏷️ Titles and records</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>The month's titles come from playing: fastest hand (the buzzer, the chairs), king of lies (I Doubt It, Fibbage), the detective (the spy games), the oracle («Who'll win?») and more. A title needs someone alone on top, twice at least.</li>
                <li>Records: best bowling, most points in a night, longest run of nights won…</li>
            </ul>
            <p class="help-sub">👑 Who runs the crew</p>
            <ul class="list-disc list-inside space-y-1 text-xs">
                <li>Whoever started the crew renames it, fixes a name, takes someone out, or hands the crew to someone else. Everyone else can leave.</li>
                <li>No accounts, no passwords: the code lets you in. A crew nobody plays in for a year deletes itself.</li>
            </ul>`,
    }
  }
});
